-- TRUSTWEAVE D12 CANONICAL CURRENT-STATE BASELINE.
-- Materialized after fresh-project structural/security/API/behavior/product parity on 2026-09-20.
-- DO NOT apply these files to the historical golden project as an upgrade sequence.
-- Historical supabase/migrations/001..123 remain immutable upgrade history.

-- OWNER-CONTEXT ONLY: apply through Supabase platform/dashboard migration tooling.
-- Do not include in direct postgres/psql apply_order because storage tables are owned by supabase_storage_admin.
CREATE POLICY "authenticated can delete community media" ON "storage"."objects" AS PERMISSIVE FOR DELETE TO "authenticated" USING (((bucket_id = 'community-media'::text) AND has_active_network_membership(storage_path_network_id(name), auth.uid()) AND ((storage_path_owner_user_id(name) = auth.uid()) OR is_network_admin(storage_path_network_id(name)))));
CREATE POLICY "authenticated can delete own profile photos" ON "storage"."objects" AS PERMISSIVE FOR DELETE TO "authenticated" USING (((bucket_id = 'profile-photos'::text) AND has_active_network_membership(storage_path_network_id(name), auth.uid()) AND ((storage_path_owner_user_id(name) = auth.uid()) OR is_network_admin(storage_path_network_id(name)))));
CREATE POLICY "authenticated can update own profile photos" ON "storage"."objects" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (((bucket_id = 'profile-photos'::text) AND (storage_path_owner_user_id(name) = auth.uid()) AND has_active_network_membership(storage_path_network_id(name), auth.uid()))) WITH CHECK (((bucket_id = 'profile-photos'::text) AND (storage_path_owner_user_id(name) = auth.uid()) AND has_active_network_membership(storage_path_network_id(name), auth.uid())));
CREATE POLICY "authenticated can upload community media" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (((bucket_id = 'community-media'::text) AND (storage_path_owner_user_id(name) = auth.uid()) AND has_active_network_membership(storage_path_network_id(name), auth.uid()) AND ((storage.foldername(name))[2] = 'community'::text)));
CREATE POLICY "authenticated can upload profile photos" ON "storage"."objects" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (((bucket_id = 'profile-photos'::text) AND (storage_path_owner_user_id(name) = auth.uid()) AND has_active_network_membership(storage_path_network_id(name), auth.uid()) AND ((storage.foldername(name))[2] = 'profiles'::text)));
CREATE POLICY "visibility-aware community media reads" ON "storage"."objects" AS PERMISSIVE FOR SELECT TO "authenticated" USING (((bucket_id = 'community-media'::text) AND can_read_community_media(name)));
CREATE POLICY "visibility-aware profile photo reads" ON "storage"."objects" AS PERMISSIVE FOR SELECT TO "authenticated" USING (((bucket_id = 'profile-photos'::text) AND can_read_profile_photo(name)));
