"use client";
import {useState} from "react";
import {AlertTriangle,CheckCircle2,Download,FileSpreadsheet,ShieldCheck,UploadCloud,XCircle} from "lucide-react";
import type {NetworkVerticalKind} from "../../core/verticals/contracts";
import {getImportSchema} from "../../core/import/registry";
import {downloadImportWorkbook} from "../../core/import/workbook";
import {parseImportWorkbook} from "../../core/import/parser";
import type {ImportCommitResult,ImportReview} from "../../core/import/contracts";
import {NetworkSectionHead} from "./NetworkUi";
import {useLanguage} from "../../lib/i18n";

export default function GuidedWorkbookImport({kind,onCommit,onCommitted,title}:{kind:NetworkVerticalKind;onCommit:(review:ImportReview)=>Promise<ImportCommitResult>;onCommitted?:(result:ImportCommitResult)=>Promise<void>|void;title?:string}){
 const {t:xp2t}=useLanguage();
 const schema=getImportSchema(kind);const [review,setReview]=useState<ImportReview|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const read=async(file:File)=>{setBusy(true);setMessage("");try{setReview(await parseImportWorkbook(await file.arrayBuffer(),file.name,schema))}catch(e:any){setReview(null);setMessage(e.message||"Could not read workbook.")}finally{setBusy(false)}};
 const commit=async()=>{if(!review?.canCommit)return;setBusy(true);setMessage("");try{const result=await onCommit(review);setMessage(result.message);setReview(null);await onCommitted?.(result)}catch(e:any){setMessage(e.message||"Import failed.")}finally{setBusy(false)}};
 return <section data-testid={`qa-guided-import-${kind}`} className="card xp1-guided-import"><NetworkSectionHead kicker={<><FileSpreadsheet size={12}/>  {xp2t("XP2Visible0559Txt")}</>} title={title||schema.title} description={xp2t("XP2Visible0560Txt")}/><div className="product-import-card"><div><FileSpreadsheet/><span><h3>{xp2t("XP2Visible0561Txt")}</h3><p>{schema.description}  {xp2t("XP2Visible0562Txt")} {schema.version}</p></span></div><button data-testid="qa-guided-import-download" className="btn" onClick={()=>downloadImportWorkbook(schema)}><Download size={15}/>  {xp2t("XP2Visible0563Txt")}</button><label className="btn primary"><UploadCloud size={15}/> {busy?xp2t("XP2ImportReadingTxt"):xp2t("XP2ImportChooseFileTxt")}<input data-testid="qa-guided-import-file" hidden disabled={busy} type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&void read(e.target.files[0])}/></label></div><div className="import-assurance"><ShieldCheck/><span><b>{xp2t("XP2Visible0564Txt")}</b> {schema.privacyNotes[0]}  {xp2t("XP2Visible0565Txt")}</span></div>
 {review&&<div data-testid="qa-guided-import-review" className="xp1-review"><div className={`review-hero ${review.canCommit?"ready":"needs-help"}`}>{review.canCommit?<CheckCircle2/>:<AlertTriangle/>}<div><h3>{review.canCommit?xp2t("XP2ImportReadyTxt"):xp2t("XP2ImportFixTxt")}</h3><p>{review.fileName} · {review.validRows}  {xp2t("XP2Visible0566Txt")} {review.warningRows}  {xp2t("XP2Visible0567Txt")} {review.rejectedRows}  {xp2t("XP2Visible0568Txt")}</p></div></div><div className="network-metric-grid">{review.sheets.map(s=><div className="network-metric" key={s.schema.key}><b>{s.rows.length}</b><span>{s.schema.name}</span><small>{s.rejectedRows?`${s.rejectedRows} ${xp2t("XP2Visible0568Txt")}`:xp2t("XP2ImportValidatedTxt")}</small></div>)}</div>{review.issues.length>0&&<div className="friendly-issues">{review.issues.slice(0,20).map((i,n)=><div className={`issue-row ${i.severity==="error"?"error":"warning"}`} key={n}>{i.severity==="error"?<XCircle/>:<AlertTriangle/>}<span><b>{i.sheet}{i.row?` · row ${i.row}`:""}{i.column?` · ${i.column}`:""}</b>{i.message}</span></div>)}</div>}<div className="table-wrap"><table><thead><tr><th>{xp2t("XP2Visible0569Txt")}</th><th>{xp2t("XP2Visible0570Txt")}</th><th>{xp2t("XP2Visible0091Txt")}</th><th>{xp2t("XP2Visible0571Txt")}</th></tr></thead><tbody>{review.sheets.flatMap(s=>s.rows.slice(0,8)).slice(0,30).map(r=><tr key={`${r.sheetKey}-${r.rowNumber}`}><td>{r.sheetName}</td><td>{r.rowNumber}</td><td>{r.status}</td><td>{Object.values(r.values).filter(Boolean).slice(0,4).map(String).join(" · ")||"—"}</td></tr>)}</tbody></table></div><div className="form-actions"><button className="btn" onClick={()=>setReview(null)}>{xp2t("XP2Visible0572Txt")}</button><button data-testid="qa-guided-import-commit" className="btn primary" disabled={busy||!review.canCommit} onClick={()=>void commit()}>{busy?xp2t("XP2ImportImportingTxt"):xp2t("ConfirmImportTxt")}</button></div></div>}
 {message&&<div data-testid="qa-guided-import-message" className="notice">{message}</div>}</section>;
}
