"use client";
import {useLanguage} from "../../lib/i18n";
import {Building2,GitFork,Link2,MapPin,MessageCircleQuestion,Pencil,Route,Sparkles,X} from "lucide-react";
import type {NetworkAffiliatedEntity} from "../../core/network-os/contracts";
import type {NetworkEntityRelationship} from "../../capabilities/template-product/remote";
import type {VerticalTemplateDefinition} from "../../core/templates/contracts";
import {InitialsAvatar} from "./NetworkUi";

export default function NetworkEntityDetail({item,template,relationships,onClose,onEdit,onViewStructure,onExploreConnection,onUpdateConnection,onAskNetwork,actionCopy}:{item:NetworkAffiliatedEntity;template:VerticalTemplateDefinition;relationships:readonly NetworkEntityRelationship[];onClose:()=>void;onEdit?:()=>void;onViewStructure?:()=>void;onExploreConnection?:()=>void;onUpdateConnection?:()=>void;onAskNetwork?:()=>void;actionCopy?:{structure?:string;connection?:string;updateConnection?:string;ask?:string}}){
 const {t:xp2t}=useLanguage();
 const {t:tr}=useLanguage();
 const related=relationships.filter(r=>r.fromEntityId===item.entity.id||r.toEntityId===item.entity.id);
 const m=item.entity.metadata||{};
 const metadataRows=[["Relationship",m.relation],["Age",m.age],["Date of birth",m.dob],["Phone",m.phone],["Email",m.email],["Profession",m.profession],["Company / Business",m.company],["Designation",m.designation],["Industry",m.industry],["Expertise",m.expertise],["City",m.city],["Area / Locality",m.area],["Bio",m.bio],["LinkedIn",m.linkedin],["Instagram",m.instagram],["Facebook",m.facebook],["Website",m.website],["Code",m.code]].filter((row):row is [string,string|number]=>typeof row[1]==="string"||typeof row[1]==="number");
 return <div className="modal-backdrop entity-detail-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal network-entity-detail" role="dialog" aria-modal="true" aria-label={`${item.entity.label} network details`}><button className="modal-x" onClick={onClose}><X/></button><div className="entity-detail-hero"><InitialsAvatar name={item.entity.label}/><div><span className="entity-kind-pill">{item.entity.kind.replaceAll("_"," ")}</span><h2>{item.entity.label}</h2><p>{String(m.role||m.contact||m.description||m.manager||"")}</p></div>{onEdit&&<button className="btn small" onClick={onEdit}><Pencil size={14}/> {tr("EditTxt")}</button>}</div><div className="entity-action-strip">{onViewStructure&&<button onClick={onViewStructure}><GitFork/><span><b>{actionCopy?.structure||tr("ViewInStructureTxt")}</b><small>{tr("SeeWhereThisEntitySitsTxt")}</small></span></button>}{onExploreConnection&&<button onClick={onExploreConnection}><Route/><span><b>{actionCopy?.connection||tr("HowAreWeConnectedTxt")}</b><small>{tr("TraceKnownNetworkPathsTxt")}</small></span></button>}{onUpdateConnection&&<button onClick={onUpdateConnection}><Link2/><span><b>{actionCopy?.updateConnection||tr("UpdateConnectionTxt")}</b><small>{tr("AddOrCorrectARelationshipTxt")}</small></span></button>}{onAskNetwork&&<button onClick={onAskNetwork}><MessageCircleQuestion/><span><b>{actionCopy?.ask||tr("AskTheNetworkTxt")}</b><small>{tr("RequestHelpOrContextTxt")}</small></span></button>}</div><div className="entity-detail-grid"><section><h3><Building2/> {tr("NetworkContextTxt")}</h3>{template.dimensions.filter(d=>(item.affiliations[d.key]||[]).length).map(d=><div className="entity-detail-row" key={d.key}><small>{d.label}</small><b>{item.affiliations[d.key].join(", ")}</b></div>)}</section><section><h3><Link2/> {tr("Relationships3Txt")}</h3>{related.slice(0,8).map(r=><div className="entity-detail-row" key={r.id}><small>{r.label}</small><b>{r.fromEntityId===item.entity.id?r.toLabel:r.fromLabel}</b></div>)}{!related.length&&<p className="muted">{tr("NoTypedRelationshipsYetTxt")}</p>}</section></div>{metadataRows.length>0&&<div className="entity-detail-profile"><h3><MapPin/>  {xp2t("XP2Visible0574Txt")}</h3><div className="entity-detail-profile-grid">{metadataRows.map(([label,value])=><div key={label}><small>{label}</small><b>{String(value)}</b></div>)}</div></div>}<div className="entity-detail-insight"><Sparkles size={14}/><span>{tr("ThisProfileBecomesMoreUsefulAsRelationshipsTxt")}</span></div></section></div>
}
