"use client";
import {useEffect,useMemo,useState} from "react";
import {BarChart3,CheckCircle2,LockKeyhole,Plus,ShieldCheck,UsersRound,Vote} from "lucide-react";
import {addBallotOption,castNetworkBallotVote,closeNetworkBallot,fetchNetworkBallots,openNetworkBallot,publishNetworkBallotResults,reviewBallotNomination,saveNetworkBallot,submitBallotNomination,type BallotsSnapshot,type NetworkBallot} from "../../capabilities/participation/voting-remote";
import {useLanguage} from "../../lib/i18n";
import {NetworkEmpty,NetworkMetric,NetworkSectionHead} from "./NetworkUi";
import ResponsiveSectionTabs from "./ResponsiveSectionTabs";

const pct=(a:number,b:number)=>b>0?Math.round((a/b)*100):0;
type VotingSection="ballots"|"nominate"|"manage";
export default function NetworkVotingPanel({onNotify}:{onNotify:(s:string)=>void}){
 const {t}=useLanguage();
 const [data,setData]=useState<BallotsSnapshot|null>(null),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Record<string,string[]>>({}),[section,setSection]=useState<VotingSection>("ballots");
 const [draft,setDraft]=useState({ballotType:"election",title:"",description:"",eligibilityMode:"members",maxChoices:"1",secretBallot:true,allowNominations:true,opensAt:"",closesAt:""});
 const [option,setOption]=useState({ballotId:"",label:"",description:"",candidateEntityId:""});
 const [nomination,setNomination]=useState({ballotId:"",nomineeEntityId:"",statement:""});
 const load=async()=>{try{setData(await fetchNetworkBallots())}catch(e:any){onNotify(e.message||t("E7CouldNotSaveTxt"))}};
 useEffect(()=>{void load()},[]);
 const run=async(fn:()=>Promise<any>,message:string)=>{setBusy(true);try{const result=await fn();onNotify(result&&typeof result==="string"&&message.includes("{receipt}")?message.replace("{receipt}",result):message);await load()}catch(e:any){onNotify(e.message||t("E7CouldNotSaveTxt"))}finally{setBusy(false)}};
 const openCount=useMemo(()=>data?.ballots.filter(b=>b.status==="open").length||0,[data]);
 const pendingNominations=useMemo(()=>data?.ballots.reduce((n,b)=>n+b.nominations.filter(x=>x.status==="pending").length,0)||0,[data]);
 const voteFor=(b:NetworkBallot,id:string)=>setSelected(s=>{const current=s[b.id]||[];if(b.max_choices===1)return {...s,[b.id]:current.includes(id)?[]:[id]};return {...s,[b.id]:current.includes(id)?current.filter(x=>x!==id):current.length>=b.max_choices?current:[...current,id]}});
 if(!data)return <NetworkEmpty title={t("E7ElectionsVotingTxt")} description={t("E7ElectionsDescTxt")}/>;
 return <div className="network-voting-panel" data-testid="qa-network-voting-panel">
  <NetworkSectionHead kicker={<><Vote size={13}/> {t("E7GovernanceParticipationTxt")}</>} title={t("E7ElectionsVotingTxt")} description={t("E7ElectionsDescTxt")}/>
  <div className="network-metric-grid"><NetworkMetric value={data.ballots.length} label={t("E7BallotsTxt")}/><NetworkMetric value={openCount} label={t("E7OpenNowTxt")}/><NetworkMetric value={pendingNominations} label={t("E7PendingNominationsTxt")}/><NetworkMetric value={data.ballots.reduce((n,b)=>n+b.participation_count,0)} label={t("E7VotesRecordedTxt")}/></div>
  <ResponsiveSectionTabs active={section} onChange={setSection} label="Voting sections" options={[{id:"ballots",label:"Ballots & results",description:"Vote, review participation and publish results"},...(data.ballots.some(b=>b.ballot_type==="election"&&b.allow_nominations&&b.status==="draft")?[{id:"nominate" as const,label:"Nominations",description:"Nominate eligible candidates"}]:[]),...(data.is_admin?[{id:"manage" as const,label:"Manage voting",description:"Create ballots and configure choices"}]:[])]}/>
  {section==="ballots"&&(data.ballots.length===0?<NetworkEmpty icon={<Vote/>} title={t("E7NoBallotsTxt")} description={t("E7NoBallotsDescTxt")}/>:<div className="network-ballot-list">{data.ballots.map(b=><BallotCard key={b.id} b={b} selected={selected[b.id]||[]} choose={id=>voteFor(b,id)} busy={busy} isAdmin={data.is_admin} t={t} run={run}/>)}</div>)}
  {section==="nominate"&&data.ballots.some(b=>b.ballot_type==="election"&&b.allow_nominations&&b.status==="draft")&&<section className="card network-ballot-nomination"><NetworkSectionHead title={t("E7NominateCandidateTxt")} description={t("E7NominateCandidateDescTxt")}/><div className="form-grid"><label className="field"><span>{t("E7ElectionTxt")}</span><select className="select" value={nomination.ballotId} onChange={e=>setNomination({...nomination,ballotId:e.target.value})}><option value="">{t("E6ChooseTxt")}</option>{data.ballots.filter(b=>b.ballot_type==="election"&&b.allow_nominations&&b.status==="draft").map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label><label className="field"><span>{t("E7CandidateTxt")}</span><select className="select" value={nomination.nomineeEntityId} onChange={e=>setNomination({...nomination,nomineeEntityId:e.target.value})}><option value="">{t("E6ChooseTxt")}</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label className="field full"><span>{t("E7StatementTxt")}</span><textarea className="text-input" value={nomination.statement} onChange={e=>setNomination({...nomination,statement:e.target.value})}/></label></div><button className="btn" disabled={busy||!nomination.ballotId||!nomination.nomineeEntityId} onClick={()=>run(()=>submitBallotNomination(nomination.ballotId,nomination.nomineeEntityId,nomination.statement),t("E7NominationSubmittedTxt"))}><UsersRound size={14}/> {t("E7SubmitNominationTxt")}</button></section>}
  {section==="manage"&&data.is_admin&&<div className="network-voting-admin-grid">
   <section className="card"><NetworkSectionHead title={t("E7CreateBallotTxt")} description={t("E7CreateBallotDescTxt")}/><div className="form-grid"><label className="field"><span>{t("E7BallotTypeTxt")}</span><select className="select" value={draft.ballotType} onChange={e=>setDraft({...draft,ballotType:e.target.value})}><option value="election">{t("E7ElectionTxt")}</option><option value="poll">{t("E7PollTxt")}</option></select></label><label className="field"><span>{t("E7EligibleVotersTxt")}</span><select className="select" value={draft.eligibilityMode} onChange={e=>setDraft({...draft,eligibilityMode:e.target.value})}><option value="members">{t("E7AllMembersTxt")}</option><option value="admins">{t("E7AdminsOnlyTxt")}</option><option value="family_representatives">{t("E7FamilyRepresentativesTxt")}</option></select></label><label className="field full"><span>{t("E7TitleTxt")}</span><input data-testid="qa-vote-title" className="text-input" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field full"><span>{t("E7DescriptionTxt")}</span><textarea className="text-input" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="field"><span>{t("E7MaxChoicesTxt")}</span><input className="text-input" type="number" min="1" max="10" value={draft.maxChoices} onChange={e=>setDraft({...draft,maxChoices:e.target.value})}/></label><label className="field"><span>{t("E7OpensAtTxt")}</span><input className="text-input" type="datetime-local" value={draft.opensAt} onChange={e=>setDraft({...draft,opensAt:e.target.value})}/></label><label className="field"><span>{t("E7ClosesAtTxt")}</span><input className="text-input" type="datetime-local" value={draft.closesAt} onChange={e=>setDraft({...draft,closesAt:e.target.value})}/></label><label className="field network-check-field"><input type="checkbox" checked={draft.secretBallot} onChange={e=>setDraft({...draft,secretBallot:e.target.checked})}/><span>{t("E7SecretBallotTxt")}</span></label><label className="field network-check-field"><input type="checkbox" checked={draft.allowNominations} onChange={e=>setDraft({...draft,allowNominations:e.target.checked})}/><span>{t("E7AllowNominationsTxt")}</span></label></div><button data-testid="qa-vote-create" className="btn primary" disabled={busy||draft.title.trim().length<3} onClick={()=>run(async()=>{await saveNetworkBallot({ballotType:draft.ballotType,title:draft.title,description:draft.description,eligibilityMode:draft.eligibilityMode,maxChoices:Number(draft.maxChoices||1),secretBallot:draft.secretBallot,allowNominations:draft.allowNominations,opensAt:draft.opensAt?new Date(draft.opensAt).toISOString():null,closesAt:draft.closesAt?new Date(draft.closesAt).toISOString():null});setDraft({...draft,title:"",description:""})},t("E7BallotCreatedTxt"))}><Plus size={14}/> {t("E7CreateBallotTxt")}</button></section>
   <section className="card"><NetworkSectionHead title={t("E7AddChoiceTxt")} description={t("E7AddChoiceDescTxt")}/><div className="form-grid"><label className="field full"><span>{t("E7DraftBallotTxt")}</span><select data-testid="qa-vote-option-ballot" className="select" value={option.ballotId} onChange={e=>setOption({...option,ballotId:e.target.value})}><option value="">{t("E6ChooseTxt")}</option>{data.ballots.filter(b=>b.status==="draft").map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label><label className="field full"><span>{t("E7ChoiceLabelTxt")}</span><input data-testid="qa-vote-option-label" className="text-input" value={option.label} onChange={e=>setOption({...option,label:e.target.value})}/></label><label className="field full"><span>{t("E7CandidateOptionalTxt")}</span><select className="select" value={option.candidateEntityId} onChange={e=>setOption({...option,candidateEntityId:e.target.value})}><option value="">{t("E7NoLinkedCandidateTxt")}</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label className="field full"><span>{t("E7DescriptionTxt")}</span><textarea className="text-input" value={option.description} onChange={e=>setOption({...option,description:e.target.value})}/></label></div><button data-testid="qa-vote-option-add" className="btn" disabled={busy||!option.ballotId||option.label.trim().length<1} onClick={()=>run(async()=>{await addBallotOption(option.ballotId,option.label,option.description,option.candidateEntityId||null);setOption({...option,label:"",description:"",candidateEntityId:""})},t("E7ChoiceAddedTxt"))}><Plus size={14}/> {t("E7AddChoiceTxt")}</button></section>
  </div>}
 </div>;
}
function BallotCard({b,selected,choose,busy,isAdmin,t,run}:{b:NetworkBallot;selected:string[];choose:(id:string)=>void;busy:boolean;isAdmin:boolean;t:(k:any)=>string;run:(fn:()=>Promise<any>,msg:string)=>Promise<void>}){
 const showResults=b.status==="published"||(isAdmin&&b.status==="closed");
 return <article data-testid="qa-ballot-card" data-ballot-id={b.id} className="card network-ballot-card"><div className="network-ballot-head"><div><span className={`entity-kind-pill ballot-${b.ballot_type}`}>{b.ballot_type}</span><h3>{b.title}</h3>{b.description&&<p>{b.description}</p>}</div><span className={`network-ballot-status status-${b.status}`}>{b.status}</span></div>
  <div className="network-ballot-meta"><span><UsersRound size={13}/> {b.participation_count}/{b.eligible_count} {t("E7ParticipatedTxt")}</span><span>{t("E7UpToChoicesTxt").replace("{count}",String(b.max_choices))}</span>{b.secret_ballot&&<span><LockKeyhole size={13}/> {t("E7SecretTxt")}</span>}</div>
  {b.secret_ballot&&<div className="network-ballot-privacy"><ShieldCheck size={16}/><span>{t("E7SecretBallotHelpTxt")}</span></div>}
  <div className="network-ballot-options">{b.options.map(o=>{const checked=selected.includes(o.id);const votes=Number(o.votes||0);const share=pct(votes,b.participation_count);return <button data-testid="qa-ballot-option" type="button" key={o.id} className={`network-ballot-option ${checked?"selected":""}`} disabled={!b.can_vote||b.has_voted} onClick={()=>choose(o.id)}><span className="network-ballot-choice-dot">{checked&&<CheckCircle2 size={16}/>}</span><span className="network-ballot-option-copy"><b>{o.label}</b>{o.description&&<small>{o.description}</small>}{showResults&&<span className="network-result-row"><i><em style={{width:`${share}%`}}/></i><strong>{votes} · {share}%</strong></span>}</span></button>})}</div>
  {b.can_vote&&!b.has_voted&&<button data-testid="qa-ballot-cast" className="btn primary" disabled={busy||selected.length<1} onClick={()=>run(()=>castNetworkBallotVote(b.id,selected),t("E7VoteRecordedReceiptTxt"))}><Vote size={14}/> {t("E7CastVoteTxt")}</button>}
  {b.has_voted&&<p className="network-ballot-voted"><CheckCircle2 size={15}/> {t("E7VoteAlreadyRecordedTxt")}</p>}
  {b.allow_nominations&&b.nominations.length>0&&<div className="network-nomination-list"><b>{t("E7NominationsTxt")}</b>{b.nominations.map(n=><div className="network-nomination-row" key={n.id}><span><strong>{n.nominee_label}</strong>{n.statement&&<small>{n.statement}</small>}</span><span className={`network-ballot-status status-${n.status}`}>{n.status}</span>{isAdmin&&n.status==="pending"&&<span className="network-nomination-actions"><button className="btn mini" disabled={busy} onClick={()=>run(()=>reviewBallotNomination(n.id,"approved"),t("E7NominationApprovedTxt"))}>{t("E7ApproveTxt")}</button><button className="btn mini" disabled={busy} onClick={()=>run(()=>reviewBallotNomination(n.id,"rejected"),t("E7NominationRejectedTxt"))}>{t("E7RejectTxt")}</button></span>}</div>)}</div>}
  {isAdmin&&<div className="network-ballot-admin-actions">{b.status==="draft"&&<button data-testid="qa-ballot-open" className="btn" disabled={busy||b.options.length<2} onClick={()=>run(async()=>{const n=await openNetworkBallot(b.id);return n},t("E7BallotOpenedTxt"))}>{t("E7OpenVotingTxt")}</button>}{b.status==="open"&&<button data-testid="qa-ballot-close" className="btn" disabled={busy} onClick={()=>run(()=>closeNetworkBallot(b.id),t("E7BallotClosedTxt"))}>{t("E7CloseVotingTxt")}</button>}{b.status==="closed"&&<button className="btn" disabled={busy} onClick={()=>run(()=>publishNetworkBallotResults(b.id),t("E7ResultsPublishedTxt"))}><BarChart3 size={14}/> {t("E7PublishResultsTxt")}</button>}</div>}
 </article>;
}
