-- TRUSTWEAVE D12 CANONICAL CURRENT-STATE BASELINE.
-- Materialized after fresh-project structural/security/API/behavior/product parity on 2026-09-20.
-- DO NOT apply these files to the historical golden project as an upgrade sequence.
-- Historical supabase/migrations/001..123 remain immutable upgrade history.

REVOKE ALL ON FUNCTION "public"."hs1_accept_resident_invitation"(p_token uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs1_accept_resident_invitation"(p_token uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs1_accept_resident_invitation"(p_token uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs1_accept_resident_invitation"(p_token uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs1_accept_resident_invitation"(p_token uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs1_allocate_parking"(p_slot_id uuid, p_unit_id uuid, p_vehicle_id uuid, p_starts_on date, p_ends_on date, p_allocation_type text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs1_allocate_parking"(p_slot_id uuid, p_unit_id uuid, p_vehicle_id uuid, p_starts_on date, p_ends_on date, p_allocation_type text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs1_allocate_parking"(p_slot_id uuid, p_unit_id uuid, p_vehicle_id uuid, p_starts_on date, p_ends_on date, p_allocation_type text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs1_allocate_parking"(p_slot_id uuid, p_unit_id uuid, p_vehicle_id uuid, p_starts_on date, p_ends_on date, p_allocation_type text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs1_allocate_parking"(p_slot_id uuid, p_unit_id uuid, p_vehicle_id uuid, p_starts_on date, p_ends_on date, p_allocation_type text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs1_assert_network"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs1_assert_network"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs1_assert_network"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs1_assert_network"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs1_assert_network"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs1_create_resident_invitation"(p_person_entity_id uuid, p_unit_entity_id uuid, p_email text, p_expires_days integer) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs1_create_resident_invitation"(p_person_entity_id uuid, p_unit_entity_id uuid, p_email text, p_expires_days integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs1_create_resident_invitation"(p_person_entity_id uuid, p_unit_entity_id uuid, p_email text, p_expires_days integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs1_create_resident_invitation"(p_person_entity_id uuid, p_unit_entity_id uuid, p_email text, p_expires_days integer) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs1_create_resident_invitation"(p_person_entity_id uuid, p_unit_entity_id uuid, p_email text, p_expires_days integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs1_get_import_template"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_import_template"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_import_template"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_import_template"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_import_template"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs1_get_my_flat"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_my_flat"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_my_flat"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_my_flat"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_my_flat"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs1_get_property_snapshot"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_property_snapshot"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_property_snapshot"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_property_snapshot"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_property_snapshot"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs1_get_resident_invitation_preview"(p_token uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_resident_invitation_preview"(p_token uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_resident_invitation_preview"(p_token uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_resident_invitation_preview"(p_token uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs1_get_resident_invitation_preview"(p_token uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs1_import_resident_rows"(p_rows jsonb, p_file_name text, p_column_mapping jsonb) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs1_import_resident_rows"(p_rows jsonb, p_file_name text, p_column_mapping jsonb) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs1_import_resident_rows"(p_rows jsonb, p_file_name text, p_column_mapping jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs1_import_resident_rows"(p_rows jsonb, p_file_name text, p_column_mapping jsonb) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs1_import_resident_rows"(p_rows jsonb, p_file_name text, p_column_mapping jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs1_set_occupancy"(p_unit_id uuid, p_subject_id uuid, p_role text, p_starts_on date, p_ends_on date, p_is_primary boolean, p_notes text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs1_set_occupancy"(p_unit_id uuid, p_subject_id uuid, p_role text, p_starts_on date, p_ends_on date, p_is_primary boolean, p_notes text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs1_set_occupancy"(p_unit_id uuid, p_subject_id uuid, p_role text, p_starts_on date, p_ends_on date, p_is_primary boolean, p_notes text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs1_set_occupancy"(p_unit_id uuid, p_subject_id uuid, p_role text, p_starts_on date, p_ends_on date, p_is_primary boolean, p_notes text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs1_set_occupancy"(p_unit_id uuid, p_subject_id uuid, p_role text, p_starts_on date, p_ends_on date, p_is_primary boolean, p_notes text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs1_upsert_parking_slot"(p_id uuid, p_slot_code text, p_zone text, p_slot_type text, p_status text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs1_upsert_parking_slot"(p_id uuid, p_slot_code text, p_zone text, p_slot_type text, p_status text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs1_upsert_parking_slot"(p_id uuid, p_slot_code text, p_zone text, p_slot_type text, p_status text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs1_upsert_parking_slot"(p_id uuid, p_slot_code text, p_zone text, p_slot_type text, p_status text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs1_upsert_parking_slot"(p_id uuid, p_slot_code text, p_zone text, p_slot_type text, p_status text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs1_upsert_vehicle"(p_id uuid, p_unit_id uuid, p_owner_entity_id uuid, p_registration_no text, p_vehicle_type text, p_make_model text, p_color text, p_is_ev boolean) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs1_upsert_vehicle"(p_id uuid, p_unit_id uuid, p_owner_entity_id uuid, p_registration_no text, p_vehicle_type text, p_make_model text, p_color text, p_is_ev boolean) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs1_upsert_vehicle"(p_id uuid, p_unit_id uuid, p_owner_entity_id uuid, p_registration_no text, p_vehicle_type text, p_make_model text, p_color text, p_is_ev boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs1_upsert_vehicle"(p_id uuid, p_unit_id uuid, p_owner_entity_id uuid, p_registration_no text, p_vehicle_type text, p_make_model text, p_color text, p_is_ev boolean) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs1_upsert_vehicle"(p_id uuid, p_unit_id uuid, p_owner_entity_id uuid, p_registration_no text, p_vehicle_type text, p_make_model text, p_color text, p_is_ev boolean) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs2_add_complaint_comment"(p_complaint_id uuid, p_body text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs2_add_complaint_comment"(p_complaint_id uuid, p_body text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs2_add_complaint_comment"(p_complaint_id uuid, p_body text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs2_add_complaint_comment"(p_complaint_id uuid, p_body text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs2_add_complaint_comment"(p_complaint_id uuid, p_body text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs2_assert_network"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs2_assert_network"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs2_assert_network"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs2_assert_network"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs2_assert_network"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs2_create_amenity_booking"(p_amenity_id uuid, p_unit_entity_id uuid, p_starts_at timestamp with time zone, p_ends_at timestamp with time zone, p_purpose text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_amenity_booking"(p_amenity_id uuid, p_unit_entity_id uuid, p_starts_at timestamp with time zone, p_ends_at timestamp with time zone, p_purpose text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_amenity_booking"(p_amenity_id uuid, p_unit_entity_id uuid, p_starts_at timestamp with time zone, p_ends_at timestamp with time zone, p_purpose text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_amenity_booking"(p_amenity_id uuid, p_unit_entity_id uuid, p_starts_at timestamp with time zone, p_ends_at timestamp with time zone, p_purpose text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_amenity_booking"(p_amenity_id uuid, p_unit_entity_id uuid, p_starts_at timestamp with time zone, p_ends_at timestamp with time zone, p_purpose text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs2_create_complaint"(p_unit_entity_id uuid, p_category text, p_title text, p_description text, p_priority text, p_photo_url text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_complaint"(p_unit_entity_id uuid, p_category text, p_title text, p_description text, p_priority text, p_photo_url text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_complaint"(p_unit_entity_id uuid, p_category text, p_title text, p_description text, p_priority text, p_photo_url text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_complaint"(p_unit_entity_id uuid, p_category text, p_title text, p_description text, p_priority text, p_photo_url text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_complaint"(p_unit_entity_id uuid, p_category text, p_title text, p_description text, p_priority text, p_photo_url text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs2_create_notice"(p_title text, p_body text, p_notice_type text, p_pinned boolean, p_expires_at timestamp with time zone) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_notice"(p_title text, p_body text, p_notice_type text, p_pinned boolean, p_expires_at timestamp with time zone) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_notice"(p_title text, p_body text, p_notice_type text, p_pinned boolean, p_expires_at timestamp with time zone) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_notice"(p_title text, p_body text, p_notice_type text, p_pinned boolean, p_expires_at timestamp with time zone) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_notice"(p_title text, p_body text, p_notice_type text, p_pinned boolean, p_expires_at timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs2_create_vendor_contract"(p_vendor_id uuid, p_title text, p_starts_on date, p_ends_on date, p_sla text, p_amount numeric) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_vendor_contract"(p_vendor_id uuid, p_title text, p_starts_on date, p_ends_on date, p_sla text, p_amount numeric) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_vendor_contract"(p_vendor_id uuid, p_title text, p_starts_on date, p_ends_on date, p_sla text, p_amount numeric) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_vendor_contract"(p_vendor_id uuid, p_title text, p_starts_on date, p_ends_on date, p_sla text, p_amount numeric) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs2_create_vendor_contract"(p_vendor_id uuid, p_title text, p_starts_on date, p_ends_on date, p_sla text, p_amount numeric) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs2_get_operations_snapshot"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs2_get_operations_snapshot"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs2_get_operations_snapshot"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs2_get_operations_snapshot"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs2_get_operations_snapshot"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs2_review_amenity_booking"(p_booking_id uuid, p_status text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs2_review_amenity_booking"(p_booking_id uuid, p_status text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs2_review_amenity_booking"(p_booking_id uuid, p_status text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs2_review_amenity_booking"(p_booking_id uuid, p_status text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs2_review_amenity_booking"(p_booking_id uuid, p_status text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs2_update_complaint"(p_complaint_id uuid, p_status text, p_assigned_to uuid, p_assigned_vendor_id uuid, p_sla_due_at timestamp with time zone, p_resolution_note text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs2_update_complaint"(p_complaint_id uuid, p_status text, p_assigned_to uuid, p_assigned_vendor_id uuid, p_sla_due_at timestamp with time zone, p_resolution_note text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs2_update_complaint"(p_complaint_id uuid, p_status text, p_assigned_to uuid, p_assigned_vendor_id uuid, p_sla_due_at timestamp with time zone, p_resolution_note text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs2_update_complaint"(p_complaint_id uuid, p_status text, p_assigned_to uuid, p_assigned_vendor_id uuid, p_sla_due_at timestamp with time zone, p_resolution_note text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs2_update_complaint"(p_complaint_id uuid, p_status text, p_assigned_to uuid, p_assigned_vendor_id uuid, p_sla_due_at timestamp with time zone, p_resolution_note text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs2_upsert_amenity"(p_id uuid, p_name text, p_description text, p_location text, p_capacity integer, p_booking_mode text, p_status text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs2_upsert_amenity"(p_id uuid, p_name text, p_description text, p_location text, p_capacity integer, p_booking_mode text, p_status text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs2_upsert_amenity"(p_id uuid, p_name text, p_description text, p_location text, p_capacity integer, p_booking_mode text, p_status text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs2_upsert_amenity"(p_id uuid, p_name text, p_description text, p_location text, p_capacity integer, p_booking_mode text, p_status text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs2_upsert_amenity"(p_id uuid, p_name text, p_description text, p_location text, p_capacity integer, p_booking_mode text, p_status text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs2_upsert_vendor"(p_id uuid, p_name text, p_category text, p_contact_name text, p_phone text, p_email text, p_status text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs2_upsert_vendor"(p_id uuid, p_name text, p_category text, p_contact_name text, p_phone text, p_email text, p_status text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs2_upsert_vendor"(p_id uuid, p_name text, p_category text, p_contact_name text, p_phone text, p_email text, p_status text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs2_upsert_vendor"(p_id uuid, p_name text, p_category text, p_contact_name text, p_phone text, p_email text, p_status text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs2_upsert_vendor"(p_id uuid, p_name text, p_category text, p_contact_name text, p_phone text, p_email text, p_status text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs3_add_bill_adjustment"(p_bill_id uuid, p_type text, p_amount numeric, p_reason text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs3_add_bill_adjustment"(p_bill_id uuid, p_type text, p_amount numeric, p_reason text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs3_add_bill_adjustment"(p_bill_id uuid, p_type text, p_amount numeric, p_reason text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs3_add_bill_adjustment"(p_bill_id uuid, p_type text, p_amount numeric, p_reason text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs3_add_bill_adjustment"(p_bill_id uuid, p_type text, p_amount numeric, p_reason text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs3_assert_network"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs3_assert_network"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs3_assert_network"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs3_assert_network"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs3_assert_network"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs3_create_billing_cycle"(p_label text, p_period_start date, p_period_end date, p_due_on date, p_grace_days integer, p_penalty_rate_monthly numeric) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs3_create_billing_cycle"(p_label text, p_period_start date, p_period_end date, p_due_on date, p_grace_days integer, p_penalty_rate_monthly numeric) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs3_create_billing_cycle"(p_label text, p_period_start date, p_period_end date, p_due_on date, p_grace_days integer, p_penalty_rate_monthly numeric) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs3_create_billing_cycle"(p_label text, p_period_start date, p_period_end date, p_due_on date, p_grace_days integer, p_penalty_rate_monthly numeric) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs3_create_billing_cycle"(p_label text, p_period_start date, p_period_end date, p_due_on date, p_grace_days integer, p_penalty_rate_monthly numeric) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs3_generate_cycle_bills"(p_cycle_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs3_generate_cycle_bills"(p_cycle_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs3_generate_cycle_bills"(p_cycle_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs3_generate_cycle_bills"(p_cycle_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs3_generate_cycle_bills"(p_cycle_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs3_get_finance_snapshot"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs3_get_finance_snapshot"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs3_get_finance_snapshot"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs3_get_finance_snapshot"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs3_get_finance_snapshot"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs3_recalculate_bill"(p_bill_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs3_recalculate_bill"(p_bill_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs3_recalculate_bill"(p_bill_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs3_recalculate_bill"(p_bill_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs3_recalculate_bill"(p_bill_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs3_record_expense"(p_category text, p_description text, p_amount numeric, p_incurred_on date, p_fund_id uuid, p_vendor_id uuid, p_payment_reference text, p_visibility text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs3_record_expense"(p_category text, p_description text, p_amount numeric, p_incurred_on date, p_fund_id uuid, p_vendor_id uuid, p_payment_reference text, p_visibility text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs3_record_expense"(p_category text, p_description text, p_amount numeric, p_incurred_on date, p_fund_id uuid, p_vendor_id uuid, p_payment_reference text, p_visibility text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs3_record_expense"(p_category text, p_description text, p_amount numeric, p_incurred_on date, p_fund_id uuid, p_vendor_id uuid, p_payment_reference text, p_visibility text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs3_record_expense"(p_category text, p_description text, p_amount numeric, p_incurred_on date, p_fund_id uuid, p_vendor_id uuid, p_payment_reference text, p_visibility text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs3_record_payment"(p_bill_id uuid, p_amount numeric, p_paid_on date, p_payment_mode text, p_payment_reference text, p_receipt_number text, p_notes text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs3_record_payment"(p_bill_id uuid, p_amount numeric, p_paid_on date, p_payment_mode text, p_payment_reference text, p_receipt_number text, p_notes text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs3_record_payment"(p_bill_id uuid, p_amount numeric, p_paid_on date, p_payment_mode text, p_payment_reference text, p_receipt_number text, p_notes text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs3_record_payment"(p_bill_id uuid, p_amount numeric, p_paid_on date, p_payment_mode text, p_payment_reference text, p_receipt_number text, p_notes text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs3_record_payment"(p_bill_id uuid, p_amount numeric, p_paid_on date, p_payment_mode text, p_payment_reference text, p_receipt_number text, p_notes text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs3_upsert_budget_line"(p_financial_year text, p_category text, p_label text, p_budget_amount numeric, p_visibility text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs3_upsert_budget_line"(p_financial_year text, p_category text, p_label text, p_budget_amount numeric, p_visibility text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs3_upsert_budget_line"(p_financial_year text, p_category text, p_label text, p_budget_amount numeric, p_visibility text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs3_upsert_budget_line"(p_financial_year text, p_category text, p_label text, p_budget_amount numeric, p_visibility text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs3_upsert_budget_line"(p_financial_year text, p_category text, p_label text, p_budget_amount numeric, p_visibility text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs3_upsert_charge_head"(p_id uuid, p_code text, p_label text, p_category text, p_default_amount numeric, p_active boolean) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs3_upsert_charge_head"(p_id uuid, p_code text, p_label text, p_category text, p_default_amount numeric, p_active boolean) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs3_upsert_charge_head"(p_id uuid, p_code text, p_label text, p_category text, p_default_amount numeric, p_active boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs3_upsert_charge_head"(p_id uuid, p_code text, p_label text, p_category text, p_default_amount numeric, p_active boolean) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs3_upsert_charge_head"(p_id uuid, p_code text, p_label text, p_category text, p_default_amount numeric, p_active boolean) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs3_upsert_fund"(p_id uuid, p_code text, p_label text, p_opening_balance numeric, p_visibility text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs3_upsert_fund"(p_id uuid, p_code text, p_label text, p_opening_balance numeric, p_visibility text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs3_upsert_fund"(p_id uuid, p_code text, p_label text, p_opening_balance numeric, p_visibility text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs3_upsert_fund"(p_id uuid, p_code text, p_label text, p_opening_balance numeric, p_visibility text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs3_upsert_fund"(p_id uuid, p_code text, p_label text, p_opening_balance numeric, p_visibility text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_add_agenda_item"(p_meeting_id uuid, p_title text, p_description text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_add_agenda_item"(p_meeting_id uuid, p_title text, p_description text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_add_agenda_item"(p_meeting_id uuid, p_title text, p_description text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_add_agenda_item"(p_meeting_id uuid, p_title text, p_description text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_add_agenda_item"(p_meeting_id uuid, p_title text, p_description text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_add_complaint_comment"(p_complaint_id uuid, p_body text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_add_complaint_comment"(p_complaint_id uuid, p_body text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_add_complaint_comment"(p_complaint_id uuid, p_body text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_add_complaint_comment"(p_complaint_id uuid, p_body text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_add_complaint_comment"(p_complaint_id uuid, p_body text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_add_governance_document"(p_meeting_id uuid, p_resolution_id uuid, p_document_type text, p_title text, p_version_label text, p_document_url text, p_visibility text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_add_governance_document"(p_meeting_id uuid, p_resolution_id uuid, p_document_type text, p_title text, p_version_label text, p_document_url text, p_visibility text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_add_governance_document"(p_meeting_id uuid, p_resolution_id uuid, p_document_type text, p_title text, p_version_label text, p_document_url text, p_visibility text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_add_governance_document"(p_meeting_id uuid, p_resolution_id uuid, p_document_type text, p_title text, p_version_label text, p_document_url text, p_visibility text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_add_governance_document"(p_meeting_id uuid, p_resolution_id uuid, p_document_type text, p_title text, p_version_label text, p_document_url text, p_visibility text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_assert_network"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_assert_network"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_assert_network"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_assert_network"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_assert_network"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_assign_committee_role"(p_term_id uuid, p_person_entity_id uuid, p_role_key text, p_role_label text, p_starts_on date, p_ends_on date) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_assign_committee_role"(p_term_id uuid, p_person_entity_id uuid, p_role_key text, p_role_label text, p_starts_on date, p_ends_on date) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_assign_committee_role"(p_term_id uuid, p_person_entity_id uuid, p_role_key text, p_role_label text, p_starts_on date, p_ends_on date) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_assign_committee_role"(p_term_id uuid, p_person_entity_id uuid, p_role_key text, p_role_label text, p_starts_on date, p_ends_on date) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_assign_committee_role"(p_term_id uuid, p_person_entity_id uuid, p_role_key text, p_role_label text, p_starts_on date, p_ends_on date) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_cast_resolution_vote"(p_resolution_id uuid, p_choice text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_cast_resolution_vote"(p_resolution_id uuid, p_choice text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_cast_resolution_vote"(p_resolution_id uuid, p_choice text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_cast_resolution_vote"(p_resolution_id uuid, p_choice text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_cast_resolution_vote"(p_resolution_id uuid, p_choice text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_category_key"(p_category text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_category_key"(p_category text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_category_key"(p_category text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_category_key"(p_category text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_category_key"(p_category text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_close_resolution"(p_resolution_id uuid, p_result_status text, p_result_note text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_close_resolution"(p_resolution_id uuid, p_result_status text, p_result_note text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_close_resolution"(p_resolution_id uuid, p_result_status text, p_result_note text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_close_resolution"(p_resolution_id uuid, p_result_status text, p_result_note text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_close_resolution"(p_resolution_id uuid, p_result_status text, p_result_note text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_create_action_item"(p_meeting_id uuid, p_title text, p_owner_label text, p_due_on date) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_action_item"(p_meeting_id uuid, p_title text, p_owner_label text, p_due_on date) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_action_item"(p_meeting_id uuid, p_title text, p_owner_label text, p_due_on date) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_action_item"(p_meeting_id uuid, p_title text, p_owner_label text, p_due_on date) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_action_item"(p_meeting_id uuid, p_title text, p_owner_label text, p_due_on date) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_create_committee_term"(p_label text, p_starts_on date, p_ends_on date, p_notes text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_committee_term"(p_label text, p_starts_on date, p_ends_on date, p_notes text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_committee_term"(p_label text, p_starts_on date, p_ends_on date, p_notes text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_committee_term"(p_label text, p_starts_on date, p_ends_on date, p_notes text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_committee_term"(p_label text, p_starts_on date, p_ends_on date, p_notes text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_create_complaint"(p_unit_entity_id uuid, p_category text, p_title text, p_description text, p_priority text, p_photo_path text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_complaint"(p_unit_entity_id uuid, p_category text, p_title text, p_description text, p_priority text, p_photo_path text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_complaint"(p_unit_entity_id uuid, p_category text, p_title text, p_description text, p_priority text, p_photo_path text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_complaint"(p_unit_entity_id uuid, p_category text, p_title text, p_description text, p_priority text, p_photo_path text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_complaint"(p_unit_entity_id uuid, p_category text, p_title text, p_description text, p_priority text, p_photo_path text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_create_meeting"(p_meeting_type text, p_title text, p_scheduled_at timestamp with time zone, p_location text, p_quorum_required integer) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_meeting"(p_meeting_type text, p_title text, p_scheduled_at timestamp with time zone, p_location text, p_quorum_required integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_meeting"(p_meeting_type text, p_title text, p_scheduled_at timestamp with time zone, p_location text, p_quorum_required integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_meeting"(p_meeting_type text, p_title text, p_scheduled_at timestamp with time zone, p_location text, p_quorum_required integer) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_meeting"(p_meeting_type text, p_title text, p_scheduled_at timestamp with time zone, p_location text, p_quorum_required integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_create_resolution"(p_meeting_id uuid, p_resolution_number text, p_title text, p_body text, p_vote_mode text, p_opens_at timestamp with time zone, p_closes_at timestamp with time zone, p_quorum_percent numeric) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_resolution"(p_meeting_id uuid, p_resolution_number text, p_title text, p_body text, p_vote_mode text, p_opens_at timestamp with time zone, p_closes_at timestamp with time zone, p_quorum_percent numeric) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_resolution"(p_meeting_id uuid, p_resolution_number text, p_title text, p_body text, p_vote_mode text, p_opens_at timestamp with time zone, p_closes_at timestamp with time zone, p_quorum_percent numeric) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_resolution"(p_meeting_id uuid, p_resolution_number text, p_title text, p_body text, p_vote_mode text, p_opens_at timestamp with time zone, p_closes_at timestamp with time zone, p_quorum_percent numeric) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_create_resolution"(p_meeting_id uuid, p_resolution_number text, p_title text, p_body text, p_vote_mode text, p_opens_at timestamp with time zone, p_closes_at timestamp with time zone, p_quorum_percent numeric) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_get_complaint_routes"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_get_complaint_routes"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_get_complaint_routes"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_get_complaint_routes"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_get_complaint_routes"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_get_governance_snapshot"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_get_governance_snapshot"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_get_governance_snapshot"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_get_governance_snapshot"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_get_governance_snapshot"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_get_operations_snapshot"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_get_operations_snapshot"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_get_operations_snapshot"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_get_operations_snapshot"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_get_operations_snapshot"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_publish_minutes"(p_meeting_id uuid, p_minutes text, p_attendee_count integer) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_publish_minutes"(p_meeting_id uuid, p_minutes text, p_attendee_count integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_publish_minutes"(p_meeting_id uuid, p_minutes text, p_attendee_count integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_publish_minutes"(p_meeting_id uuid, p_minutes text, p_attendee_count integer) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_publish_minutes"(p_meeting_id uuid, p_minutes text, p_attendee_count integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_set_complaint_route"(p_category text, p_role_key text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_set_complaint_route"(p_category text, p_role_key text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_set_complaint_route"(p_category text, p_role_key text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_set_complaint_route"(p_category text, p_role_key text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_set_complaint_route"(p_category text, p_role_key text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_update_action_item"(p_action_id uuid, p_status text, p_completion_note text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_update_action_item"(p_action_id uuid, p_status text, p_completion_note text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_update_action_item"(p_action_id uuid, p_status text, p_completion_note text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_update_action_item"(p_action_id uuid, p_status text, p_completion_note text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_update_action_item"(p_action_id uuid, p_status text, p_completion_note text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs4_update_complaint"(p_complaint_id uuid, p_status text, p_assigned_to uuid, p_assigned_vendor_id uuid, p_sla_due_at timestamp with time zone, p_resolution_note text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs4_update_complaint"(p_complaint_id uuid, p_status text, p_assigned_to uuid, p_assigned_vendor_id uuid, p_sla_due_at timestamp with time zone, p_resolution_note text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs4_update_complaint"(p_complaint_id uuid, p_status text, p_assigned_to uuid, p_assigned_vendor_id uuid, p_sla_due_at timestamp with time zone, p_resolution_note text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs4_update_complaint"(p_complaint_id uuid, p_status text, p_assigned_to uuid, p_assigned_vendor_id uuid, p_sla_due_at timestamp with time zone, p_resolution_note text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs4_update_complaint"(p_complaint_id uuid, p_status text, p_assigned_to uuid, p_assigned_vendor_id uuid, p_sla_due_at timestamp with time zone, p_resolution_note text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_add_asset_service"(p_asset_id uuid, p_service_type text, p_serviced_on date, p_next_due_on date, p_notes text, p_cost numeric) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_add_asset_service"(p_asset_id uuid, p_service_type text, p_serviced_on date, p_next_due_on date, p_notes text, p_cost numeric) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_add_asset_service"(p_asset_id uuid, p_service_type text, p_serviced_on date, p_next_due_on date, p_notes text, p_cost numeric) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_add_asset_service"(p_asset_id uuid, p_service_type text, p_serviced_on date, p_next_due_on date, p_notes text, p_cost numeric) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_add_asset_service"(p_asset_id uuid, p_service_type text, p_serviced_on date, p_next_due_on date, p_notes text, p_cost numeric) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_assert_network"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_assert_network"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_assert_network"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_assert_network"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_assert_network"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_authorize_staff_unit"(p_staff_id uuid, p_unit_entity_id uuid, p_starts_on date, p_ends_on date) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_authorize_staff_unit"(p_staff_id uuid, p_unit_entity_id uuid, p_starts_on date, p_ends_on date) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_authorize_staff_unit"(p_staff_id uuid, p_unit_entity_id uuid, p_starts_on date, p_ends_on date) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_authorize_staff_unit"(p_staff_id uuid, p_unit_entity_id uuid, p_starts_on date, p_ends_on date) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_authorize_staff_unit"(p_staff_id uuid, p_unit_entity_id uuid, p_starts_on date, p_ends_on date) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_create_move_request"(p_unit_entity_id uuid, p_move_type text, p_scheduled_on date, p_contact_name text, p_notes text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_create_move_request"(p_unit_entity_id uuid, p_move_type text, p_scheduled_on date, p_contact_name text, p_notes text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_create_move_request"(p_unit_entity_id uuid, p_move_type text, p_scheduled_on date, p_contact_name text, p_notes text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_create_move_request"(p_unit_entity_id uuid, p_move_type text, p_scheduled_on date, p_contact_name text, p_notes text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_create_move_request"(p_unit_entity_id uuid, p_move_type text, p_scheduled_on date, p_contact_name text, p_notes text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_create_renovation_request"(p_unit_entity_id uuid, p_title text, p_description text, p_contractor_name text, p_starts_on date, p_ends_on date) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_create_renovation_request"(p_unit_entity_id uuid, p_title text, p_description text, p_contractor_name text, p_starts_on date, p_ends_on date) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_create_renovation_request"(p_unit_entity_id uuid, p_title text, p_description text, p_contractor_name text, p_starts_on date, p_ends_on date) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_create_renovation_request"(p_unit_entity_id uuid, p_title text, p_description text, p_contractor_name text, p_starts_on date, p_ends_on date) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_create_renovation_request"(p_unit_entity_id uuid, p_title text, p_description text, p_contractor_name text, p_starts_on date, p_ends_on date) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_create_visitor"(p_unit_entity_id uuid, p_visitor_name text, p_visit_type text, p_expected_at timestamp with time zone, p_purpose text, p_phone text, p_vehicle_number text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_create_visitor"(p_unit_entity_id uuid, p_visitor_name text, p_visit_type text, p_expected_at timestamp with time zone, p_purpose text, p_phone text, p_vehicle_number text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_create_visitor"(p_unit_entity_id uuid, p_visitor_name text, p_visit_type text, p_expected_at timestamp with time zone, p_purpose text, p_phone text, p_vehicle_number text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_create_visitor"(p_unit_entity_id uuid, p_visitor_name text, p_visit_type text, p_expected_at timestamp with time zone, p_purpose text, p_phone text, p_vehicle_number text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_create_visitor"(p_unit_entity_id uuid, p_visitor_name text, p_visit_type text, p_expected_at timestamp with time zone, p_purpose text, p_phone text, p_vehicle_number text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_get_snapshot"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_get_snapshot"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_get_snapshot"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_get_snapshot"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_get_snapshot"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_grant_operator"(p_user_id uuid, p_scope text, p_active boolean) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_grant_operator"(p_user_id uuid, p_scope text, p_active boolean) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_grant_operator"(p_user_id uuid, p_scope text, p_active boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_grant_operator"(p_user_id uuid, p_scope text, p_active boolean) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_grant_operator"(p_user_id uuid, p_scope text, p_active boolean) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_is_operator"(p_network_id uuid, p_scope text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_is_operator"(p_network_id uuid, p_scope text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_is_operator"(p_network_id uuid, p_scope text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_is_operator"(p_network_id uuid, p_scope text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_is_operator"(p_network_id uuid, p_scope text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_review_request"(p_kind text, p_id uuid, p_status text, p_note text, p_noc_reference text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_review_request"(p_kind text, p_id uuid, p_status text, p_note text, p_noc_reference text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_review_request"(p_kind text, p_id uuid, p_status text, p_note text, p_noc_reference text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_review_request"(p_kind text, p_id uuid, p_status text, p_note text, p_noc_reference text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_review_request"(p_kind text, p_id uuid, p_status text, p_note text, p_noc_reference text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_update_visitor_status"(p_visitor_id uuid, p_status text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_update_visitor_status"(p_visitor_id uuid, p_status text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_update_visitor_status"(p_visitor_id uuid, p_status text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_update_visitor_status"(p_visitor_id uuid, p_status text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_update_visitor_status"(p_visitor_id uuid, p_status text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_upsert_asset"(p_id uuid, p_asset_code text, p_name text, p_category text, p_location text, p_warranty_until date) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_asset"(p_id uuid, p_asset_code text, p_name text, p_category text, p_location text, p_warranty_until date) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_asset"(p_id uuid, p_asset_code text, p_name text, p_category text, p_location text, p_warranty_until date) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_asset"(p_id uuid, p_asset_code text, p_name text, p_category text, p_location text, p_warranty_until date) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_asset"(p_id uuid, p_asset_code text, p_name text, p_category text, p_location text, p_warranty_until date) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_upsert_compliance"(p_id uuid, p_category text, p_title text, p_due_on date, p_owner_label text, p_document_url text, p_visibility text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_compliance"(p_id uuid, p_category text, p_title text, p_due_on date, p_owner_label text, p_document_url text, p_visibility text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_compliance"(p_id uuid, p_category text, p_title text, p_due_on date, p_owner_label text, p_document_url text, p_visibility text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_compliance"(p_id uuid, p_category text, p_title text, p_due_on date, p_owner_label text, p_document_url text, p_visibility text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_compliance"(p_id uuid, p_category text, p_title text, p_due_on date, p_owner_label text, p_document_url text, p_visibility text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_upsert_emergency_contact"(p_category text, p_label text, p_phone text, p_notes text, p_priority integer) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_emergency_contact"(p_category text, p_label text, p_phone text, p_notes text, p_priority integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_emergency_contact"(p_category text, p_label text, p_phone text, p_notes text, p_priority integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_emergency_contact"(p_category text, p_label text, p_phone text, p_notes text, p_priority integer) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_emergency_contact"(p_category text, p_label text, p_phone text, p_notes text, p_priority integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs5_upsert_staff"(p_id uuid, p_name text, p_staff_type text, p_phone text, p_identity_last4 text, p_verification_status text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_staff"(p_id uuid, p_name text, p_staff_type text, p_phone text, p_identity_last4 text, p_verification_status text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_staff"(p_id uuid, p_name text, p_staff_type text, p_phone text, p_identity_last4 text, p_verification_status text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_staff"(p_id uuid, p_name text, p_staff_type text, p_phone text, p_identity_last4 text, p_verification_status text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs5_upsert_staff"(p_id uuid, p_name text, p_staff_type text, p_phone text, p_identity_last4 text, p_verification_status text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs6_assert_admin_network"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs6_assert_admin_network"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs6_assert_admin_network"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs6_assert_admin_network"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs6_assert_admin_network"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs6_assert_network"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs6_assert_network"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs6_assert_network"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs6_assert_network"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs6_assert_network"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs6_get_pilot_snapshot"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs6_get_pilot_snapshot"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs6_get_pilot_snapshot"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs6_get_pilot_snapshot"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs6_get_pilot_snapshot"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs6_mark_notice_reads"(p_notice_ids uuid[]) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs6_mark_notice_reads"(p_notice_ids uuid[]) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs6_mark_notice_reads"(p_notice_ids uuid[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs6_mark_notice_reads"(p_notice_ids uuid[]) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs6_mark_notice_reads"(p_notice_ids uuid[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs6_record_checkpoint"(p_run_id uuid, p_admin_hours_saved numeric, p_offline_operations_remaining integer, p_willingness_to_pay text, p_renewal_intent text, p_repeatable_onboarding_confirmed boolean, p_founder_specific_code_required boolean, p_committee_note text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs6_record_checkpoint"(p_run_id uuid, p_admin_hours_saved numeric, p_offline_operations_remaining integer, p_willingness_to_pay text, p_renewal_intent text, p_repeatable_onboarding_confirmed boolean, p_founder_specific_code_required boolean, p_committee_note text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs6_record_checkpoint"(p_run_id uuid, p_admin_hours_saved numeric, p_offline_operations_remaining integer, p_willingness_to_pay text, p_renewal_intent text, p_repeatable_onboarding_confirmed boolean, p_founder_specific_code_required boolean, p_committee_note text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs6_record_checkpoint"(p_run_id uuid, p_admin_hours_saved numeric, p_offline_operations_remaining integer, p_willingness_to_pay text, p_renewal_intent text, p_repeatable_onboarding_confirmed boolean, p_founder_specific_code_required boolean, p_committee_note text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs6_record_checkpoint"(p_run_id uuid, p_admin_hours_saved numeric, p_offline_operations_remaining integer, p_willingness_to_pay text, p_renewal_intent text, p_repeatable_onboarding_confirmed boolean, p_founder_specific_code_required boolean, p_committee_note text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs6_record_pricing_experiment"(p_run_id uuid, p_pricing_model text, p_amount numeric, p_currency text, p_response text, p_notes text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs6_record_pricing_experiment"(p_run_id uuid, p_pricing_model text, p_amount numeric, p_currency text, p_response text, p_notes text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs6_record_pricing_experiment"(p_run_id uuid, p_pricing_model text, p_amount numeric, p_currency text, p_response text, p_notes text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs6_record_pricing_experiment"(p_run_id uuid, p_pricing_model text, p_amount numeric, p_currency text, p_response text, p_notes text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs6_record_pricing_experiment"(p_run_id uuid, p_pricing_model text, p_amount numeric, p_currency text, p_response text, p_notes text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs6_record_usage_event"(p_event_key text, p_metadata jsonb) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs6_record_usage_event"(p_event_key text, p_metadata jsonb) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs6_record_usage_event"(p_event_key text, p_metadata jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs6_record_usage_event"(p_event_key text, p_metadata jsonb) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs6_record_usage_event"(p_event_key text, p_metadata jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs6_start_pilot"(p_phase text, p_target_units integer, p_cohort_label text, p_notes text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs6_start_pilot"(p_phase text, p_target_units integer, p_cohort_label text, p_notes text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs6_start_pilot"(p_phase text, p_target_units integer, p_cohort_label text, p_notes text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs6_start_pilot"(p_phase text, p_target_units integer, p_cohort_label text, p_notes text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs6_start_pilot"(p_phase text, p_target_units integer, p_cohort_label text, p_notes text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."hs6_update_pilot_status"(p_run_id uuid, p_status text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."hs6_update_pilot_status"(p_run_id uuid, p_status text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."hs6_update_pilot_status"(p_run_id uuid, p_status text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."hs6_update_pilot_status"(p_run_id uuid, p_status text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."hs6_update_pilot_status"(p_run_id uuid, p_status text) TO "service_role";
