-- TRUSTWEAVE D12 CANONICAL CURRENT-STATE BASELINE.
-- Materialized after fresh-project structural/security/API/behavior/product parity on 2026-09-20.
-- DO NOT apply these files to the historical golden project as an upgrade sequence.
-- Historical supabase/migrations/001..123 remain immutable upgrade history.

REVOKE ALL ON FUNCTION "public"."accept_alumni_invitation"(p_token text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."accept_alumni_invitation"(p_token text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."accept_alumni_invitation"(p_token text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."accept_alumni_invitation"(p_token text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."accept_alumni_invitation"(p_token text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."admin_upsert_alumni_profile"(p_full_name text, p_email text, p_graduation_year integer, p_program text, p_department text, p_city text, p_company text, p_job_title text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_upsert_alumni_profile"(p_full_name text, p_email text, p_graduation_year integer, p_program text, p_department text, p_city text, p_company text, p_job_title text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."admin_upsert_alumni_profile"(p_full_name text, p_email text, p_graduation_year integer, p_program text, p_department text, p_city text, p_company text, p_job_title text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."admin_upsert_alumni_profile"(p_full_name text, p_email text, p_graduation_year integer, p_program text, p_department text, p_city text, p_company text, p_job_title text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_upsert_alumni_profile"(p_full_name text, p_email text, p_graduation_year integer, p_program text, p_department text, p_city text, p_company text, p_job_title text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."claim_alumni_profile_by_verified_email"(p_profile_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."claim_alumni_profile_by_verified_email"(p_profile_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."claim_alumni_profile_by_verified_email"(p_profile_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."claim_alumni_profile_by_verified_email"(p_profile_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."claim_alumni_profile_by_verified_email"(p_profile_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."create_alumni_connection"(p_related_profile_id uuid, p_relation_kind character varying) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."create_alumni_connection"(p_related_profile_id uuid, p_relation_kind character varying) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."create_alumni_connection"(p_related_profile_id uuid, p_relation_kind character varying) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."create_alumni_connection"(p_related_profile_id uuid, p_relation_kind character varying) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."create_alumni_connection"(p_related_profile_id uuid, p_relation_kind character varying) TO "service_role";
REVOKE ALL ON FUNCTION "public"."create_alumni_invitation"(p_profile_id uuid, p_recipient_hint text, p_expires_days integer) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."create_alumni_invitation"(p_profile_id uuid, p_recipient_hint text, p_expires_days integer) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."create_alumni_invitation"(p_profile_id uuid, p_recipient_hint text, p_expires_days integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."create_alumni_invitation"(p_profile_id uuid, p_recipient_hint text, p_expires_days integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."create_alumni_invitation"(p_profile_id uuid, p_recipient_hint text, p_expires_days integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."create_alumni_network"(p_name text, p_institution text, p_description text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."create_alumni_network"(p_name text, p_institution text, p_description text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."create_alumni_network"(p_name text, p_institution text, p_description text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."create_alumni_network"(p_name text, p_institution text, p_description text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."create_alumni_network"(p_name text, p_institution text, p_description text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."g7_sync_alumni_profile"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."g7_sync_alumni_profile"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."g7_sync_alumni_profile"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."g7_sync_alumni_profile"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."g7_sync_alumni_profile"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."g7_sync_alumni_profile_row"(p_profile uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."g7_sync_alumni_profile_row"(p_profile uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."g7_sync_alumni_profile_row"(p_profile uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."g7_sync_alumni_profile_row"(p_profile uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."g7_sync_alumni_profile_row"(p_profile uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_alumni_directory"(p_query text, p_year integer, p_program text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_alumni_directory"(p_query text, p_year integer, p_program text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_alumni_directory"(p_query text, p_year integer, p_program text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_alumni_directory"(p_query text, p_year integer, p_program text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_alumni_directory"(p_query text, p_year integer, p_program text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_alumni_network_overview"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_alumni_network_overview"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_alumni_network_overview"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_alumni_network_overview"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_alumni_network_overview"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_my_alumni_connections"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_my_alumni_connections"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_my_alumni_connections"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_my_alumni_connections"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_alumni_connections"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_my_claimable_alumni_profiles"() FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_my_claimable_alumni_profiles"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_my_claimable_alumni_profiles"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_my_claimable_alumni_profiles"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_claimable_alumni_profiles"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."import_alumni_profiles"(p_rows jsonb) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."import_alumni_profiles"(p_rows jsonb) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."import_alumni_profiles"(p_rows jsonb) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."import_alumni_profiles"(p_rows jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."import_alumni_profiles"(p_rows jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."preview_alumni_invitation"(p_token text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."preview_alumni_invitation"(p_token text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."preview_alumni_invitation"(p_token text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."preview_alumni_invitation"(p_token text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."preview_alumni_invitation"(p_token text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."record_organization_intelligence_query"(p_question text, p_intent text, p_confidence text, p_evidence_count integer, p_matched_entity_ids text[]) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."record_organization_intelligence_query"(p_question text, p_intent text, p_confidence text, p_evidence_count integer, p_matched_entity_ids text[]) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."record_organization_intelligence_query"(p_question text, p_intent text, p_confidence text, p_evidence_count integer, p_matched_entity_ids text[]) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."record_organization_intelligence_query"(p_question text, p_intent text, p_confidence text, p_evidence_count integer, p_matched_entity_ids text[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."record_organization_intelligence_query"(p_question text, p_intent text, p_confidence text, p_evidence_count integer, p_matched_entity_ids text[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."upsert_my_alumni_profile"(p_full_name text, p_graduation_year integer, p_program text, p_department text, p_city text, p_company text, p_job_title text, p_bio text) FROM PUBLIC, "anon", "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."upsert_my_alumni_profile"(p_full_name text, p_graduation_year integer, p_program text, p_department text, p_city text, p_company text, p_job_title text, p_bio text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."upsert_my_alumni_profile"(p_full_name text, p_graduation_year integer, p_program text, p_department text, p_city text, p_company text, p_job_title text, p_bio text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."upsert_my_alumni_profile"(p_full_name text, p_graduation_year integer, p_program text, p_department text, p_city text, p_company text, p_job_title text, p_bio text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."upsert_my_alumni_profile"(p_full_name text, p_graduation_year integer, p_program text, p_department text, p_city text, p_company text, p_job_title text, p_bio text) TO "service_role";
