import type {NetworkVerticalKind} from "../verticals/contracts";
export type QuickStartAction="import"|"add-primary"|"add-person"|"invite"|"add-structure"|"publish-notice"|"create-group"|"complete-profile"|"add-expertise"|"add-project";
export type QuickStartSignal="primary"|"people"|"relationships"|"members"|"activities"|"groups"|"profile";
export type QuickStartStep={id:string;title:string;description:string;action:QuickStartAction;actionLabel:string;minimumRole:"owner"|"admin"|"member";completeWhen?:{signal:QuickStartSignal;atLeast:number}};
export type QuickStartDefinition={kind:NetworkVerticalKind;title:string;description:string;steps:readonly QuickStartStep[]};
const s=(id:string,title:string,description:string,action:QuickStartAction,actionLabel:string,completeWhen?:QuickStartStep["completeWhen"],minimumRole:QuickStartStep["minimumRole"]="admin"):QuickStartStep=>({id,title,description,action,actionLabel,minimumRole,completeWhen});
export const QUICK_START_REGISTRY:Record<NetworkVerticalKind,QuickStartDefinition>={
 family:{kind:"family",title:"Quick Family Start",description:"Start with the smallest useful family and grow together.",steps:[s("family-self","Add myself","Create or claim your own family profile first.","add-person","Add myself",{signal:"people",atLeast:1}),s("family-relative","Add a close relative","Add one trusted relationship so the family is immediately understandable.","add-person","Add relative",{signal:"relationships",atLeast:1}),s("family-import","Import existing family data","Use the guided workbook when you already have a list.","import","Open Excel guide")]},
 alumni:{kind:"alumni",title:"Activate your alumni network",description:"A few clean profiles and one cohort are enough to make the network useful.",steps:[s("alumni-self","Add myself","Make sure your own alumni identity exists.","complete-profile","Add myself",{signal:"people",atLeast:1}),s("alumni-cohort","Add first cohort","Create the first batch/program structure.","add-structure","Open structure",{signal:"primary",atLeast:1}),s("alumni-invite","Invite alumni","Bring another alumnus into the network.","invite","Invite alumni",{signal:"members",atLeast:2}),s("alumni-import","Import alumni workbook","Use guided validation for an existing list.","import","Open workbook")]},
 "housing-society":{kind:"housing-society",title:"Activate your society",description:"Represent the property first, then invite residents and publish the first useful communication.",steps:[s("hs-import","Import units & residents","Start with the guided Housing Society workbook.","import","Import workbook"),s("hs-building","Add first building / flat","Create the first physical structure.","add-primary","Add property",{signal:"primary",atLeast:1}),s("hs-invite","Invite committee / resident","Bring another verified user into the society.","invite","Open invitations",{signal:"members",atLeast:2}),s("hs-notice","Publish first notice","Give residents an immediate reason to return.","publish-notice","Open notices",{signal:"activities",atLeast:1})]},
 association:{kind:"association",title:"Activate your association",description:"Add members, a group and the first community activity.",steps:[s("assoc-member","Add first member","Create the first member profile.","add-person","Add member",{signal:"people",atLeast:1}),s("assoc-group","Create first chapter / group","Give members a shared structure.","create-group","Create group",{signal:"groups",atLeast:1}),s("assoc-invite","Invite another member","Grow beyond the creator account.","invite","Invite member",{signal:"members",atLeast:2}),s("assoc-import","Import workbook","Use guided import for an existing register.","import","Open workbook")]},
 "family-association":{kind:"family-association",title:"Activate your family association",description:"Represent families and people first, then invite and establish annual operations.",steps:[s("fca-family","Add first family","Create the first household/family record.","add-primary","Add family",{signal:"primary",atLeast:1}),s("fca-person","Add family member","Add a person and connect them to a family.","add-person","Add member",{signal:"people",atLeast:1}),s("fca-invite","Invite member","Bring a family representative or member in.","invite","Invite member",{signal:"members",atLeast:2}),s("fca-import","Import association workbook","Use guided workbook onboarding.","import","Open workbook")]},
 organization:{kind:"organization",title:"Activate your organization",description:"Start with people, a team/project structure and a colleague invite.",steps:[s("org-self","Add myself","Create your own organization identity.","add-person","Add myself",{signal:"people",atLeast:1}),s("org-team","Create team","Add the first team or structure node.","add-structure","Add team",{signal:"primary",atLeast:1}),s("org-project","Add first project","Create a real collaboration context.","add-project","Add project"),s("org-invite","Invite colleague","Bring another user into the organization.","invite","Invite colleague",{signal:"members",atLeast:2}),s("org-import","Import organization workbook","Start from existing people/teams/projects.","import","Open workbook")]},
 "business-trust":{kind:"business-trust",title:"Activate your business trust network",description:"Add trusted businesses and record why the relationship exists.",steps:[s("trust-business","Add my business","Create the first business profile.","add-primary","Add business",{signal:"primary",atLeast:1}),s("trust-partner","Add trusted partner","Add another business and connect it with provenance.","add-primary","Add partner",{signal:"primary",atLeast:2}),s("trust-group","Create category / circle","Create a useful sourcing or partner group.","create-group","Create circle",{signal:"groups",atLeast:1}),s("trust-import","Import workbook","Use the guided business-trust workbook.","import","Open workbook")]},
 franchise:{kind:"franchise",title:"Activate your franchise network",description:"Start with a branch/location and its operator, then establish geography.",steps:[s("franchise-branch","Add first branch","Create the first franchise location.","add-primary","Add branch",{signal:"primary",atLeast:1}),s("franchise-owner","Add owner / operator","Add a person responsible for the location.","add-person","Add operator",{signal:"people",atLeast:1}),s("franchise-geo","Define geography","Use city/state/region affiliations for the first branch.","add-structure","Open structure",{signal:"primary",atLeast:1}),s("franchise-import","Import workbook","Use guided branch/operator onboarding.","import","Open workbook")]},
 professional:{kind:"professional",title:"Activate your professional network",description:"Complete expertise first, then invite a trusted professional connection.",steps:[s("pro-profile","Complete my professional profile","Create your professional identity and core specialty.","complete-profile","Complete profile",{signal:"people",atLeast:1}),s("pro-expertise","Add expertise","Record at least one specialty/service.","add-expertise","Add expertise",{signal:"primary",atLeast:1}),s("pro-invite","Invite professional connection","Bring another trusted expert into the network.","invite","Invite professional",{signal:"members",atLeast:2}),s("pro-import","Import workbook","Use the guided professional workbook.","import","Open workbook")]}
};
export function getQuickStart(kind:NetworkVerticalKind){return QUICK_START_REGISTRY[kind]}
