import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import net from 'node:net';import zlib from 'node:zlib';import {spawn,spawnSync} from 'node:child_process';import {chromium as playwrightChromium} from '@playwright/test';import serverlessChromium from '@sparticuz/chromium';
const at=()=>new Date().toISOString();const delay=ms=>new Promise(r=>setTimeout(r,ms));
export class EnvironmentManager{
 constructor({root=process.cwd(),evidenceDir='release-evidence/environment'}={}){this.root=path.resolve(root);this.evidenceDir=path.resolve(root,evidenceDir);this.children=[];fs.mkdirSync(this.evidenceDir,{recursive:true})}
 inspect(requiredEnv=[]){const lock=path.join(this.root,'package-lock.json');return {at:at(),node:process.version,lockfile:{present:fs.existsSync(lock),bytes:fs.existsSync(lock)?fs.statSync(lock).size:0},dependencies:{ready:fs.existsSync(path.join(this.root,'node_modules','typescript'))},environment:requiredEnv.map(name=>({name,present:Boolean(process.env[name])})),secretsExposed:false}}
 restoreDependencies(){if(fs.existsSync(path.join(this.root,'node_modules','typescript')))return {status:'PASS',action:'already-locked'};const r=spawnSync('npm',['ci','--ignore-scripts'],{cwd:this.root,encoding:'utf8'});return {status:r.status===0?'PASS':'FAIL',action:'npm-ci',exitCode:r.status,stderr:(r.stderr||'').slice(-1000)}}
 async freePort(){return new Promise((resolve,reject)=>{const s=net.createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const address=s.address();const port=typeof address==='object'&&address?address.port:0;s.close(()=>resolve(port))})})}
 async startPreview({port=null,env={}}={}){const selected=port||await this.freePort();const child=spawn(process.execPath,[path.join(this.root,'node_modules','next','dist','bin','next'),'dev','-H','127.0.0.1','-p',String(selected)],{cwd:this.root,env:{...process.env,...env},stdio:['ignore','pipe','pipe'],detached:process.platform!=='win32'});let log='';child.stdout.on('data',d=>{log+=d});child.stderr.on('data',d=>{log+=d});this.children.push(child);const baseURL=`http://127.0.0.1:${selected}`;for(let i=0;i<120;i++){if(child.exitCode!==null)throw new Error(`Preview exited ${child.exitCode}: ${log.slice(-1500)}`);try{const response=await fetch(`${baseURL}/api/health`);if(response.status<500)return {status:'PASS',baseURL,port:selected,pid:child.pid,log:()=>log}}catch{}await delay(500)}throw new Error(`Preview readiness timed out: ${log.slice(-1500)}`)}
 prepareBrowser(){const expected=playwrightChromium.executablePath();if(fs.existsSync(expected))return {executablePath:expected,args:[],source:'playwright-cache'};const bin=path.join(this.root,'node_modules','@sparticuz','chromium','bin'),tmp=os.tmpdir(),browser=path.join(tmp,'chromium');if(!fs.existsSync(browser)){fs.writeFileSync(browser,zlib.brotliDecompressSync(fs.readFileSync(path.join(bin,'chromium.br'))),{mode:0o700});fs.chmodSync(browser,0o700)}for(const [name,target] of [['fonts.tar','fonts'],['swiftshader.tar','']]){const tar=path.join(tmp,name);if(!fs.existsSync(tar))fs.writeFileSync(tar,zlib.brotliDecompressSync(fs.readFileSync(path.join(bin,`${name}.br`))));const destination=path.join(tmp,target);fs.mkdirSync(destination,{recursive:true});const marker=path.join(destination,`.trustweave-${name}.ready`);if(!fs.existsSync(marker)){const r=spawnSync('tar',['--no-same-owner','-xf',tar,'-C',destination]);if(r.status!==0)throw new Error(`Browser support extraction failed: ${name}`);fs.writeFileSync(marker,at())}}return {executablePath:browser,args:serverlessChromium.args,source:'locked-serverless-chromium'}}
 async launchBrowser(){const prepared=this.prepareBrowser();const browser=await playwrightChromium.launch({headless:true,executablePath:prepared.executablePath,args:prepared.args});return {browser,source:prepared.source}}
 async browserProbe(baseURL,{paths=['/'],screenshots=true,browser=null,browserSource=null,page=null}={}){let owned=false,active=browser,source=browserSource,probePage=page;if(!active){const launched=await this.launchBrowser();active=launched.browser;source=launched.source;owned=true}if(!probePage)probePage=await active.newPage();const results=[];try{for(const [index,route] of paths.entries()){await probePage.setViewportSize({width:index%2?390:1440,height:index%2?844:900});const errors=[];probePage.removeAllListeners('pageerror');probePage.removeAllListeners('console');probePage.on('pageerror',e=>errors.push(String(e)));probePage.on('console',m=>{if(m.type()==='error')errors.push(m.text())});const response=await probePage.goto(`${baseURL}${route}`,{waitUntil:'domcontentloaded',timeout:60000});await probePage.locator('body').waitFor({state:'visible'});const body=(await probePage.locator('body').innerText()).slice(0,500);const fatal=/Unhandled Runtime Error|Application error/i.test(body);let screenshot=null;if(screenshots){screenshot=path.join(this.evidenceDir,`browser-${index}-${route.replace(/[^a-z0-9]/gi,'_')||'root'}.png`);await probePage.screenshot({path:screenshot,fullPage:false})}results.push({route,status:response?.status()||0,visible:body.length>0,fatal,errors:errors.slice(0,10),screenshot:path.relative(this.root,screenshot||'')})}}finally{if(owned)await active.close()}return {status:results.every(x=>x.status<500&&x.visible&&!x.fatal&&x.errors.length===0)?'PASS':'FAIL',browserSource:source,results}}
 cleanup(){for(const child of this.children.splice(0)){if(child.exitCode!==null)continue;try{if(process.platform==='win32')child.kill();else process.kill(-child.pid,'SIGTERM')}catch{try{child.kill('SIGTERM')}catch{}}}return {status:'PASS',at:at()}}
 async certify({paths=['/'],screenshots=false}={}){const report={startedAt:at(),inspection:this.inspect(),dependencyRepair:this.restoreDependencies()};let browser=null,keepAlive=null;try{const launched=await this.launchBrowser();browser=launched.browser;keepAlive=await browser.newPage();const preview=await this.startPreview();report.preview={status:preview.status,baseURL:preview.baseURL,port:preview.port};report.browser=await this.browserProbe(preview.baseURL,{paths,screenshots,browser,browserSource:launched.source,page:keepAlive});report.status=report.dependencyRepair.status==='PASS'&&report.browser.status==='PASS'?'PASS':'FAIL';report.previewLog=preview.log().slice(-2000)}catch(error){report.status='FAIL';report.error=String(error)}finally{if(keepAlive)await keepAlive.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});report.cleanup=this.cleanup();report.finishedAt=at()}const file=path.join(this.evidenceDir,'environment-certification.json');fs.writeFileSync(file,JSON.stringify(report,null,2)+'\n');return {...report,evidence:path.relative(this.root,file)}}
}
