import fs from 'node:fs';import path from 'node:path';import {execFileSync,spawnSync} from 'node:child_process';
const dimensions=['architecture','security','privacy','data-integrity','accessibility','ux','maintainability','performance','regression','evidence-quality','scope'];
const finding=(dimension,severity,summary,evidence)=>({dimension,severity,summary,evidence});
function globPrefix(pattern){return pattern.endsWith('/**')?pattern.slice(0,-2):pattern.replace('*','')}
export function reviewManifest(manifest){const findings=[];if(!manifest.candidate) findings.push(finding('evidence-quality','BLOCKER','Candidate identity is missing.','candidate'));if(!manifest.evidenceBound)findings.push(finding('evidence-quality','BLOCKER','Evidence is not bound to the candidate.','evidenceBound'));if(!manifest.reviewer||manifest.reviewer===manifest.builder)findings.push(finding('evidence-quality','BLOCKER','Builder cannot approve the candidate.','reviewer'));
 for(const file of manifest.changedFiles||[]){if((manifest.forbiddenWrites||[]).some(pattern=>file.startsWith(globPrefix(pattern))))findings.push(finding('scope','BLOCKER',`Forbidden path changed: ${file}`,file));if(/^supabase\/migrations\/\d+/.test(file)&&manifest.risk!=='R3')findings.push(finding('data-integrity','BLOCKER','Migration change is not authorized by an R3 mission.',file));}
 const source=manifest.sourceText||'';if(/SUPABASE_SERVICE_ROLE_KEY\s*=\s*["'][^"']+/i.test(source)||/-----BEGIN (?:RSA |EC )?PRIVATE KEY-----/.test(source))findings.push(finding('security','BLOCKER','Candidate contains credential-like material.','secret-pattern'));if(/dangerouslySetInnerHTML/.test(source)&&!/DOMPurify|sanitize/.test(source))findings.push(finding('security','HIGH','Unsanitized HTML sink requires review.','dangerouslySetInnerHTML'));if(/localStorage\.(?:setItem|getItem)\([^)]*(?:token|secret|password)/i.test(source))findings.push(finding('privacy','HIGH','Sensitive client persistence pattern detected.','localStorage'));
 if(manifest.runtimeRequired&&!manifest.runtimePass)findings.push(finding('regression','BLOCKER','Required runtime proof is missing or red.','runtime'));if(manifest.userVisible&&!manifest.accessibilityEvidence)findings.push(finding('accessibility','HIGH','User-visible change lacks accessibility evidence.','accessibility'));if(manifest.userVisible&&!manifest.uxEvidence)findings.push(finding('ux','HIGH','User-visible change lacks persona journey evidence.','ux'));if((manifest.maxChangedFileLines||0)>2000)findings.push(finding('maintainability','MEDIUM','A changed file exceeds the maintainability review threshold.',manifest.maxChangedFileLines));if(manifest.performanceSensitive&&!manifest.performanceEvidence)findings.push(finding('performance','HIGH','Performance-sensitive change lacks a budget measurement.','performance'));
 for(const dimension of dimensions)if(!findings.some(x=>x.dimension===dimension))findings.push(finding(dimension,'INFO','No blocking signal found in the supplied candidate evidence.','automated-review'));
 const blockers=findings.filter(x=>x.severity==='BLOCKER');return {status:blockers.length?'REJECTED':'APPROVED',blockingFindings:blockers.length,findings,dimensionsReviewed:dimensions};}
export function candidateManifest({mission,candidate,reviewer='risk-board/process-v1',builder='work-session/root',evidencePath=null}){const missionJson=JSON.parse(fs.readFileSync(mission,'utf8'));const changed=execFileSync('git',['show','--pretty=format:','--name-only',candidate],{encoding:'utf8'}).split(/\r?\n/).filter(Boolean);let sourceText='';for(const file of changed.filter(x=>/\.(?:ts|tsx|js|mjs|json)$/.test(x))){try{sourceText+=fs.readFileSync(file,'utf8').slice(0,200000)}catch{}}let evidence=null;if(evidencePath&&fs.existsSync(evidencePath))evidence=JSON.parse(fs.readFileSync(evidencePath,'utf8'));const runtimeRequired=Boolean(missionJson.runtimeEvidenceRequired),runtimePass=Boolean(evidence?.results?.some(x=>x.kind==='runtime'&&x.status==='PASS'));return {missionId:missionJson.id,candidate,reviewer,builder,risk:missionJson.risk,changedFiles:changed,forbiddenWrites:missionJson.scope?.forbiddenWrites||[],sourceText,evidenceBound:!evidence||evidence.candidateSha===candidate,runtimeRequired,runtimePass,userVisible:changed.some(x=>x.startsWith('app/')||x.startsWith('components/')),accessibilityEvidence:!changed.some(x=>x.startsWith('app/')||x.startsWith('components/')),uxEvidence:!changed.some(x=>x.startsWith('app/')||x.startsWith('components/')),performanceSensitive:changed.some(x=>/(bundle|query|performance)/i.test(x)),performanceEvidence:false,maxChangedFileLines:Math.max(0,...changed.map(file=>{try{return fs.readFileSync(file,'utf8').split(/\r?\n/).length}catch{return 0}}))}}
export function runRiskBoard({mission,candidate,reviewer='risk-board/process-v1',builder='work-session/root',evidencePath=null,out=null}){const manifest=candidateManifest({mission,candidate,reviewer,builder,evidencePath});const base=reviewManifest(manifest);const deterministic=[['mission-contract',`node scripts/agentic/mission-contract-gate.mjs --mission ${mission}`],['architecture','node scripts/agentic/architecture-gate.mjs'],['mission-source',`node scripts/agentic/mission-source-gate.mjs --mission ${mission}`]];const gateEvidence=[];for(const [gate,command] of deterministic){const r=spawnSync('bash',['-lc',command],{encoding:'utf8'});gateEvidence.push({gate,status:r.status===0?'PASS':'FAIL',exitCode:r.status});if(r.status!==0)base.findings.push(finding('regression','BLOCKER',`${gate} failed.`,(r.stderr||r.stdout).slice(0,500)))}const blockingFindings=base.findings.filter(x=>x.severity==='BLOCKER').length;const review={...base,status:blockingFindings?'REJECTED':'APPROVED',blockingFindings,builder,reviewer,candidate,candidateSha:candidate,missionId:manifest.missionId,generatedAt:new Date().toISOString(),evidence:gateEvidence,independence:{processIsolated:true,inputBoundToCommittedCandidate:true,builderCannotSetStatus:true}};if(out){fs.mkdirSync(path.dirname(path.resolve(out)),{recursive:true});fs.writeFileSync(out,JSON.stringify(review,null,2)+'\n')}return review}
