import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';import {classifyFailure} from '../agentic/failure-classifier.mjs';
const digest=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
export function detectConflicts(tasks){const owners=new Map(),conflicts=[];for(const task of tasks)for(const file of task.writes||[]){if(owners.has(file)&&!(task.dependsOn||[]).includes(owners.get(file)))conflicts.push({file,first:owners.get(file),second:task.id});else owners.set(file,task.id)}return conflicts}
export function decompose(objective){return [{id:'discover',title:`Discover evidence for ${objective}`,writes:[]},{id:'build',title:'Implement bounded repair',dependsOn:['discover'],writes:['candidate/source.mjs']},{id:'verify',title:'Verify independently',dependsOn:['build'],writes:['candidate/evidence.json']}]} 
const strategies=[
 {name:'missing-expression',matches:text=>/unexpected token ['"]?;|expression expected/i.test(text),apply:source=>source.replace(/=\s*;/g,'= null;')},
 {name:'missing-paren',matches:text=>/missing \) after argument list/i.test(text),apply:source=>source.replace(/console\.log\(([^;\n]+);/g,'console.log($1);')}
];
export function heal({file,verifyCommand=null,maxAttempts=3,sameFailureMaxRepeats=2,allowedFiles=[file]}){const absolute=path.resolve(file),baseline=new Map(allowedFiles.map(x=>[path.resolve(x),fs.existsSync(x)?digest(path.resolve(x)):null])),attempts=[],counts=new Map();for(let attempt=1;attempt<=maxAttempts;attempt++){const command=verifyCommand||`${process.execPath} --check "${absolute}"`;const result=spawnSync(process.platform==='win32'?'cmd.exe':'bash',process.platform==='win32'?['/d','/s','/c',command]:['-lc',command],{encoding:'utf8'});if(result.status===0)return {status:'PASS',attempts,verification:{command,exitCode:0},scopeDrift:scopeDrift(baseline,allowedFiles)};const output=`${result.stdout||''}\n${result.stderr||''}`,classification=classifyFailure(output),signature=crypto.createHash('sha1').update(output.replace(/\d+/g,'#')).digest('hex').slice(0,12);counts.set(signature,(counts.get(signature)||0)+1);const strategy=strategies.find(x=>x.matches(output));attempts.push({attempt,classification,signature,strategy:strategy?.name||null,exitCode:result.status});if(counts.get(signature)>sameFailureMaxRepeats||!strategy)break;const before=fs.readFileSync(absolute,'utf8'),after=strategy.apply(before);if(after===before)break;fs.writeFileSync(absolute,after)}return {status:'FAIL',attempts,verification:null,scopeDrift:scopeDrift(baseline,allowedFiles)}}
function scopeDrift(baseline,allowedFiles){const allowed=new Set(allowedFiles.map(x=>path.resolve(x)));const changed=[];for(const [file,before] of baseline){const after=fs.existsSync(file)?digest(file):null;if(before!==after)changed.push(file)}return {changed,withinBounds:changed.every(x=>allowed.has(x))}}
