import {fetchNetworkAffiliatedEntities} from "../affiliation/remote";
import {createNetworkEntityRelationship,fetchNetworkEntityRelationships,upsertNetworkEntity} from "../template-product/remote";
import {importAlumniProfiles,type AlumniImportRow} from "../../verticals/alumni/data/remote";
import type {ImportCommitResult,ImportReview} from "../../core/import/contracts";
const good=(r:any)=>r.status!=="rejected";
export async function commitAlumniWorkbook(review:ImportReview):Promise<ImportCommitResult>{
 if(!review.canCommit)throw new Error("Resolve import validation errors before committing.");const alumni=review.sheets.find(s=>s.schema.key==="alumni")?.rows.filter(good)||[];const rows:AlumniImportRow[]=alumni.map(r=>({full_name:String(r.values.name||""),email:String(r.values.email||"")||undefined,graduation_year:r.values.graduation_year?Number(r.values.graduation_year):undefined,program:String(r.values.program||"")||undefined,department:String(r.values.department||"")||undefined,city:String(r.values.city||"")||undefined,company:String(r.values.company||"")||undefined,job_title:String(r.values.job_title||"")||undefined}));const result=await importAlumniProfiles(rows);
 for(const sheet of review.sheets.filter(s=>s.schema.key==="cohorts"))for(const row of sheet.rows.filter(good)){const stableId=String(row.values.stable_id||"");await upsertNetworkEntity({kind:"organization",label:String(row.values.name||""),metadata:{description:row.values.description,importStableId:stableId,importSchemaVersion:review.schema.version}})}
 const entities=await fetchNetworkAffiliatedEntities();const refs=new Map<string,string>();for(const row of alumni){const stable=String(row.values.stable_id||"").toLowerCase();const email=String(row.values.email||"").toLowerCase();const name=String(row.values.name||"").toLowerCase();const entity=entities.find(e=>(email&&String(e.entity.metadata?.email||"").toLowerCase()===email)||String(e.entity.label||"").toLowerCase()===name);if(stable&&entity)refs.set(stable,entity.entity.id)}
 const existing=new Set((await fetchNetworkEntityRelationships()).map(r=>`${r.fromEntityId}|${r.toEntityId}|${r.relationshipType}`));let relationships=0,skipped=result.skipped||0;for(const sheet of review.sheets.filter(s=>s.schema.key==="connections"))for(const row of sheet.rows.filter(good)){const from=refs.get(String(row.values.from_id||"").toLowerCase()),to=refs.get(String(row.values.to_id||"").toLowerCase()),rel=String(row.values.relationship||"");if(!from||!to||!rel){skipped++;continue}const key=`${from}|${to}|${rel}`;if(existing.has(key)){skipped++;continue}await createNetworkEntityRelationship(from,to,rel,{importSchemaVersion:review.schema.version});existing.add(key);relationships++}
 return {created:result.inserted,updated:result.updated,relationships,skipped,message:`Imported ${result.inserted} new and updated ${result.updated} alumni; created ${relationships} connections${skipped?` and skipped ${skipped} existing/incomplete rows`:""}.`};
}
