import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {DurableStateStore,now} from './state-store.mjs';
const roleOrder=['ceo','chiefOfStaff','ctoArchitect','cpoUserAdvocate','criticRedTeam'];
const d3Patterns=[/production\s+(delete|purge|deploy)/i,/accept.{0,20}(privacy|security).{0,20}risk/i,/(contract|subscription|recurring spend|purchase)/i,/(change|amend).{0,20}(constitution|founder boundary)/i,/sell|share.{0,20}personal data/i];
export function classifyDecision(intent,evidence=[]){const text=`${intent} ${evidence.map(x=>x.summary||x).join(' ')}`;return d3Patterns.some(rx=>rx.test(text))?'D3':/(release|external|staging|migration)/i.test(text)?'D2':/(architecture|product|pilot|material)/i.test(text)?'D1':'D0'}
function recommendations(intent,evidence){const evidenceIds=evidence.map(x=>x.id||x.source||String(x)).filter(Boolean);return [
 {role:'ceo',position:'PROCEED',recommendation:`Advance the highest-value bounded outcome in: ${intent}`,tradeoffs:['speed over completeness','protect strategic coherence'],evidence:evidenceIds},
 {role:'chiefOfStaff',position:'SEQUENCE',recommendation:'Split discovery, reversible implementation, verification and closure with explicit dependencies.',tradeoffs:['more checkpoints','crash-safe continuity'],evidence:evidenceIds},
 {role:'ctoArchitect',position:'CONSTRAIN',recommendation:'Reuse platform contracts; prohibit migration and new infrastructure unless evidence makes them necessary.',tradeoffs:['smaller blast radius','may defer ambitious redesign'],evidence:evidenceIds},
 {role:'cpoUserAdvocate',position:'PILOT_FIRST',recommendation:'Start from the most fragile real user journey and require observable usability proof.',tradeoffs:['user value over feature breadth','representative personas required'],evidence:evidenceIds},
 {role:'criticRedTeam',position:'CHALLENGE',recommendation:'Assume the proposed change can create local optimization; demand regression and falsification evidence.',tradeoffs:['slower closure','lower false confidence'],evidence:evidenceIds}
 ]}
export function deliberate({intent,evidence=[],constraints=[],delegatedClasses=['D0','D1','D2'],stateRoot='company-state',decisionId=null}){
 if(!intent)throw new Error('Council intent is required.');const decisionClass=classifyDecision(intent,evidence);const voices=recommendations(intent,evidence);if(new Set(voices.map(x=>x.recommendation)).size<3)throw new Error('Council failed to produce competing recommendations.');const id=decisionId||`DEC-${Date.now()}-${crypto.randomBytes(2).toString('hex')}`;
 const alternatives=[{id:'A',title:'Architecture-first expansion',supportedBy:['ctoArchitect'],rejectedBecause:'Insufficient user evidence for a broader redesign.'},{id:'B',title:'Pilot-journey bounded improvement',supportedBy:['ceo','cpoUserAdvocate','chiefOfStaff'],selected:true},{id:'C',title:'Defer and collect evidence only',supportedBy:['criticRedTeam'],rejectedBecause:'Existing evidence supports a reversible bounded experiment.'}];
 const dissent={role:'criticRedTeam',position:'The selected path can overfit one pilot.',response:'Require cross-vertical regression, evidence binding and rollback before closure.'};const delegated=delegatedClasses.includes(decisionClass);const record={id,createdAt:now(),intent,evidence,constraints,decisionClass,authority:{delegated,status:delegated?'AUTHORIZED':'FOUNDER_APPROVAL_REQUIRED'},voices,alternatives,dissent,decision:delegated?'Run alternative B as a bounded, reversible mission with critic conditions.':'Pause before external effect and request Founder approval.',rationale:'Balances user value, platform integrity, reversibility and evidence quality.',adoptedFrom:['ceo','cpoUserAdvocate','chiefOfStaff','criticRedTeam'],firstThoughtSilentlyAdopted:false,status:delegated?'DECIDED':'AWAITING_FOUNDER'};
 const dir=path.resolve(stateRoot,'decisions');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,`${id}.json`),JSON.stringify(record,null,2)+'\n');const store=new DurableStateStore(stateRoot);store.transaction('EXECUTIVE_DECISION',{decisionId:id,decisionClass,status:record.status},state=>{state.decisions=state.decisions||[];state.decisions.push({id,decisionClass,status:record.status,path:`decisions/${id}.json`})});return record;
}
export const councilRoles=()=>[...roleOrder];
