"use client";
import {useEffect,useMemo,useState} from "react";
import {CheckCircle2,Database,Download,FileSpreadsheet,RefreshCw,ShieldCheck,TriangleAlert,Upload} from "lucide-react";
import type {LaunchDataset,LaunchSeedCommitResult,LaunchSeedContext,LaunchSeedDryRun,LaunchSeedKind} from "../../core/launch-seed/contracts";
import {BUNDLED_LAUNCH_DATASETS,authorizeAndInspectLaunchDataset,commitLaunchDataset,inspectLaunchDataset,loadBundledLaunchDataset,parseLaunchDatasetFile} from "../../capabilities/launch-seed";

export default function LaunchDemoDataLoader({kind,networkId,networkName,isAdmin,isPlatformOwner=false,onNotify,onCommitted}:{kind:LaunchSeedKind;networkId:string;networkName:string;isAdmin:boolean;isPlatformOwner?:boolean;onNotify?:(message:string)=>void;onCommitted?:()=>Promise<void>|void}){
 const meta=BUNDLED_LAUNCH_DATASETS[kind];
 const [data,setData]=useState<LaunchDataset|null>(null),[sourceLabel,setSourceLabel]=useState(meta.label),[context,setContext]=useState<LaunchSeedContext|null>(null),[dryRun,setDryRun]=useState<LaunchSeedDryRun|null>(null);
 const [busy,setBusy]=useState(false),[confirmName,setConfirmName]=useState(""),[syntheticConfirmed,setSyntheticConfirmed]=useState(false),[allowRealNetwork,setAllowRealNetwork]=useState(false),[error,setError]=useState(""),[progress,setProgress]=useState(""),[result,setResult]=useState<LaunchSeedCommitResult|null>(null);
 const demoLike=useMemo(()=>/(demo|pilot|sample|sandbox|test)/i.test(networkName),[networkName]);
 const canOperate=isAdmin||isPlatformOwner;
 const inspect=async(next:LaunchDataset)=>{const inspected=await inspectLaunchDataset(next,kind);setContext(inspected.context);setDryRun(inspected.dryRun);return inspected};
 const loadBundled=async()=>{setBusy(true);setError("");setResult(null);try{const next=await loadBundledLaunchDataset(kind);setData(next);setSourceLabel(`${meta.label} · bundled JSON`);await inspect(next)}catch(e:any){setError(e?.message||"Could not load launch dataset.")}finally{setBusy(false)}};
 useEffect(()=>{if(canOperate)void loadBundled()},[kind,networkId]); // eslint-disable-line react-hooks/exhaustive-deps
 const loadFile=async(file:File)=>{setBusy(true);setError("");setResult(null);try{const next=await parseLaunchDatasetFile(file,kind);setData(next);setSourceLabel(file.name);await inspect(next)}catch(e:any){setError(e?.message||"Could not read launch dataset.")}finally{setBusy(false)}};
 const authorize=async()=>{if(!data)return;setBusy(true);setError("");setResult(null);try{const inspected=await authorizeAndInspectLaunchDataset(data,kind,confirmName,allowRealNetwork);setContext(inspected.context);setDryRun(inspected.dryRun);onNotify?.(`Synthetic launch data authorized for ${networkName}.`)}catch(e:any){setError(e?.message||"Could not authorize launch data.")}finally{setBusy(false)}};
 const commit=async()=>{if(!data)return;setBusy(true);setError("");setResult(null);setProgress("Preparing persisted launch seed…");try{const next=await commitLaunchDataset(data,kind,networkId,{onProgress:p=>setProgress(`${p.message} (${p.current}/${p.total})`)});setResult(next);setProgress("");await inspect(data);await onCommitted?.();onNotify?.(next.message)}catch(e:any){setProgress("");setError(e?.message||"Could not seed launch data.")}finally{setBusy(false)}};
 const downloadReport=()=>{if(!result)return;const payload=result.report||{run:{id:result.runId,dataset_version:result.datasetVersion,vertical_kind:result.kind,created:result.created,updated:result.updated,skipped:result.skipped,errors:result.errors},issues:result.diagnostics,warnings:result.warnings};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`trustweave-seed-report-${result.kind}-${result.runId||Date.now()}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)};
 if(!canOperate)return null;
 const authorized=Boolean(context?.authorized&&context.networkId===networkId);
 const safetyReady=syntheticConfirmed&&confirmName===networkName&&(demoLike||allowRealNetwork);
 return <section className="card launch-seed-loader" data-testid="qa-launch-data-loader">
  <div className="launch-seed-head"><div><span className="warm-kicker"><Database size={13}/> Final launch data</span><h3>Populate this real network with synthetic showcase data</h3><p>This loader uses the same persisted product APIs as normal usage. It is network-scoped, audited and idempotent; it does not reset or directly bulk-write product tables.</p></div><span className={`launch-seed-state ${authorized?"ready":"guarded"}`}>{authorized?<><CheckCircle2 size={14}/> Authorized</>:<><ShieldCheck size={14}/> Guarded</>}</span></div>
  <div className="launch-seed-source"><div><FileSpreadsheet size={18}/><span><b>{sourceLabel}</b><small>{data?.version||meta.version} · synthetic launch dataset</small></span></div><div className="card-actions"><button data-testid="qa-launch-load-bundled" className="btn small" disabled={busy} onClick={()=>void loadBundled()}><RefreshCw size={14}/> Bundled dataset</button><label className={`btn small ${busy?"disabled":""}`}><Upload size={14}/> Upload JSON/XLSX<input data-testid="qa-launch-upload" hidden type="file" accept=".json,.xlsx,application/json,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void loadFile(file);e.currentTarget.value=""}}/></label></div></div>
  {dryRun&&<><div className="launch-seed-metrics" data-testid="qa-launch-dry-run"><span><b>{dryRun.totals.rows}</b><small>source rows</small></span><span><b>{dryRun.totals.create}</b><small>create</small></span><span><b>{dryRun.totals.update}</b><small>update</small></span><span><b>{dryRun.totals.skip}</b><small>unchanged</small></span><span><b>{dryRun.totals.errors}</b><small>reference errors</small></span></div>{dryRun.issues.length>0&&<div className="launch-seed-issues">{dryRun.issues.slice(0,8).map((issue,i)=><p key={`${issue.section}-${issue.rowRef}-${i}`}><TriangleAlert size={14}/><span><b>{issue.section||"Dataset"}</b> {issue.message}</span></p>)}</div>}<details className="launch-seed-sections"><summary>Dry-run section plan ({dryRun.sections.length})</summary><div>{dryRun.sections.map(section=><span key={section.section}><b>{section.section}</b><small>{section.rows} rows · {section.create} create · {section.update} update · {section.skip} unchanged{section.errors?` · ${section.errors} errors`:""}</small></span>)}</div></details></>}
  {!authorized&&<div className="launch-seed-safety"><div><span className="warm-kicker">Explicit safety confirmation</span><p>Type the exact active network name. Authorization applies only to <b>{data?.version||meta.version}</b> in this network.</p></div><label className="field full"><span>Active network name</span><input data-testid="qa-launch-confirm-name" className="text-input" value={confirmName} onChange={e=>setConfirmName(e.target.value)} placeholder={networkName}/></label><label className="launch-seed-check"><input data-testid="qa-launch-synthetic-confirm" type="checkbox" checked={syntheticConfirmed} onChange={e=>setSyntheticConfirmed(e.target.checked)}/><span>I confirm this is synthetic showcase data and I intend to persist it into this network.</span></label>{!demoLike&&<label className="launch-seed-check danger"><input data-testid="qa-launch-real-network-override" type="checkbox" checked={allowRealNetwork} onChange={e=>setAllowRealNetwork(e.target.checked)}/><span>This network is not named like a demo/pilot network. I explicitly allow synthetic seeding into this real-looking network.</span></label>}<button data-testid="qa-launch-authorize" className="btn primary" disabled={busy||!data||!dryRun?.valid||!safetyReady} onClick={()=>void authorize()}><ShieldCheck size={15}/> Authorize this dataset</button></div>}
  {authorized&&<div className="launch-seed-commit"><div><b>Authorization is bound to this active network and dataset version.</b><p>Reruns compare stable row references and payload hashes. Unchanged rows skip; mutable rows update; historical/immutable rows are not duplicated.</p></div><button data-testid="qa-launch-commit" className="btn primary" disabled={busy||!data||!dryRun?.valid} onClick={()=>void commit()}><Database size={15}/> {busy?"Seeding…":"Persist launch dataset"}</button></div>}
  {progress&&<div className="notice launch-seed-progress" data-testid="qa-launch-progress"><RefreshCw size={15}/><span>{progress}</span></div>}
  {error&&<div className="notice launch-seed-error" data-testid="qa-launch-error"><TriangleAlert size={15}/><span>{error}</span></div>}
  {result&&<div className={`notice launch-seed-result ${result.errors?"warn":"success"}`} data-testid="qa-launch-result"><CheckCircle2 size={15}/><span><b>{result.message}</b>{result.runId&&<small>Seed run: {result.runId}</small>}{result.diagnostics.length>0&&<small>{result.diagnostics.filter(x=>x.severity==="error").length} error + {result.diagnostics.filter(x=>x.severity==="warning").length} constrained warning diagnostic{result.diagnostics.length===1?"":"s"} recorded with row-level context.</small>}{result.diagnostics.slice(0,8).map((d,i)=><small className="launch-seed-diagnostic" key={`${d.section}-${d.rowRef}-${i}`}><b>{d.section} / {d.rowRef}</b>{d.code?` [${d.code}]`:""} · {d.operation} · {d.message}</small>)}<button data-testid="qa-launch-download-report" className="btn small" onClick={downloadReport}><Download size={14}/> Download seed report</button></span></div>}
 </section>
}
