"use client";
import {useEffect,useMemo,useState} from "react";
import {Archive,HardDrive,Image as ImageIcon,RotateCcw,Trash2} from "lucide-react";
import {fetchMediaManagementSnapshot,permanentlyDeleteManagedMedia,setMediaArchived,type ManagedMediaAsset,type MediaManagementSnapshot} from "../../lib/storage";
import {useLanguage} from "../../lib/i18n";
import {NetworkEmpty,NetworkMetric,NetworkSectionHead} from "./NetworkUi";
import ResponsiveSectionTabs from "./ResponsiveSectionTabs";
const mb=(n:number)=>(n/1048576).toFixed(n>=10*1048576?0:1);
export default function MediaManagementPanel({onNotify}:{onNotify:(s:string)=>void}){
 const {t}=useLanguage();const [data,setData]=useState<MediaManagementSnapshot|null>(null),[busy,setBusy]=useState<string|null>(null),[filter,setFilter]=useState<'all'|'active'|'archived'|'unbound'>('all');
 const load=async()=>{try{setData(await fetchMediaManagementSnapshot())}catch(e:any){onNotify(e.message||t("E8CouldNotLoadTxt"))}};useEffect(()=>{void load()},[]);
 const assets=useMemo(()=>{const a=(data?.assets||[]).filter(x=>x.lifecycle_state!=="deleted"&&x.lifecycle_state!=="delete_pending");if(filter==='unbound')return a.filter(x=>x.unbound);if(filter==='all')return a;return a.filter(x=>x.lifecycle_state===filter)},[data,filter]);
 const archived=(data?.assets||[]).filter(a=>a.lifecycle_state==='archived').length,unbound=(data?.assets||[]).filter(a=>a.lifecycle_state!=='deleted'&&a.unbound).length,pct=Math.min(100,Math.round((data?.media_usage_bytes||0)/Math.max(1,data?.storage_limit_bytes||1)*100));
 const action=async(id:string,fn:()=>Promise<void>,msg:string)=>{setBusy(id);try{await fn();onNotify(msg);await load()}catch(e:any){onNotify(e.message||t("E8CouldNotUpdateTxt"))}finally{setBusy(null)}};
 if(!data)return <NetworkEmpty title={t("E8MediaStorageTxt")} description={t("E8MediaStorageDescTxt")}/>;
 return <div className="media-management-panel" data-testid="qa-media-management-panel"><NetworkSectionHead kicker={<><HardDrive size={13}/> {t("E8StorageLifecycleTxt")}</>} title={t("E8MediaStorageTxt")} description={t("E8MediaStorageDescTxt")}/>
  <div className="network-metric-grid"><NetworkMetric value={`${mb(data.media_usage_bytes)} MB`} label={t("E8UsedTxt")}/><NetworkMetric value={`${mb(data.storage_limit_bytes)} MB`} label={t("E8AllowanceTxt")}/><NetworkMetric value={archived} label={t("E8ArchivedTxt")}/><NetworkMetric value={unbound} label={t("E8UnboundTxt")}/></div>
  <section className="card media-storage-meter"><div><b>{t("E8StorageUsageTxt")}</b><span>{pct}% · {mb(Math.max(0,data.storage_limit_bytes-data.media_usage_bytes))} MB {t("E8RemainingTxt")}</span></div><div className="usage-bar large"><i style={{width:`${pct}%`}}/></div>{pct>=80&&<p className="admin-storage-warning"><b>{t("E8StorageAttentionTxt")}</b><span>{t("E8StorageAttentionDescTxt")}</span></p>}</section>
  <ResponsiveSectionTabs active={filter} onChange={setFilter} label="Media filter" options={(['all','active','archived','unbound'] as const).map(x=>({id:x,label:x==='all'?t("E8AllMediaTxt"):x==='active'?t("E8ActiveTxt"):x==='archived'?t("E8ArchivedTxt"):t("E8UnboundTxt")}))}/>
  {assets.length===0?<NetworkEmpty icon={<ImageIcon/>} title={t("E8NoMediaTxt")} description={t("E8NoMediaDescTxt")}/>:<div className="media-management-grid">{assets.map(a=><MediaCard key={a.id} a={a} busy={busy===a.id} admin={data.is_admin} t={t} archive={()=>action(a.id,()=>setMediaArchived(a.id,true),t("E8ArchivedDoneTxt"))} restore={()=>action(a.id,()=>setMediaArchived(a.id,false),t("E8RestoredDoneTxt"))} remove={()=>{if(!confirm(t("E8DeleteConfirmTxt")))return;void action(a.id,()=>permanentlyDeleteManagedMedia(a.id,t("E8DeleteReasonTxt")),t("E8DeletedDoneTxt"))}}/>)}</div>}
 </div>;
}
function MediaCard({a,busy,admin,t,archive,restore,remove}:{a:ManagedMediaAsset;busy:boolean;admin:boolean;t:(k:any)=>string;archive:()=>void;restore:()=>void;remove:()=>void}){const can=admin||a.owned_by_me;return <article className="card media-management-card">{a.thumbnail_url?<img src={a.thumbnail_url} alt="" loading="lazy"/>:<div className="media-management-placeholder"><ImageIcon/></div>}<div className="media-management-copy"><div><span className={`entity-kind-pill media-${a.media_kind}`}>{a.media_kind}</span><span className={`network-ballot-status status-${a.lifecycle_state}`}>{a.lifecycle_state}</span></div><b>{a.entity_type||t("E8UnboundMediaTxt")}</b><small>{new Date(a.created_at).toLocaleDateString()} · {Math.round((a.bytes+a.thumbnail_bytes)/1024)} KB{a.unbound?` · ${t("E8UnboundTxt")}`:""}</small></div>{can&&<div className="card-actions">{a.lifecycle_state==='active'?<button className="btn mini" disabled={busy} onClick={archive}><Archive size={13}/> {t("E8ArchiveTxt")}</button>:<><button className="btn mini" disabled={busy} onClick={restore}><RotateCcw size={13}/> {t("E8RestoreTxt")}</button><button className="btn mini danger-text" disabled={busy} onClick={remove}><Trash2 size={13}/> {t("E8DeleteTxt")}</button></>}</div>}</article>}
