"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowUpRight,BellRing,Heart,ImagePlus,MessageSquareText,Pin,PinOff,Plus,Send,Share2,ShieldAlert,Sparkles,UsersRound} from "lucide-react";
import type {NetworkActivity} from "../../core/network-os/contracts";
import {createNetworkPost,setNetworkActivityPinned,toggleNetworkActivityLike} from "../../capabilities/activity/remote";
import {bindMediaAsset,removeMediaAsset,uploadMediaAsset,type NetworkMediaAsset} from "../../lib/storage";
import {extractMentions} from "../../lib/mentions";
import {routeNetworkMentions} from "../../lib/remote";
import {clearNotificationDeepLink,readNotificationDeepLink} from "../../lib/notification-routing";
import {networkObjectHref,navigateNetworkObject} from "../../lib/network-routes";
import {useLanguage} from "../../lib/i18n";
import {NetworkEmpty,NetworkSectionHead} from "./NetworkUi";
import CommunityObjectDetail,{type CommunityMemberProfile} from "./CommunityObjectDetail";

type Importance="normal"|"important"|"urgent";
const score=(a:NetworkActivity)=>a.metadata?.pinned_at?0:a.metadata?.importance==="urgent"?1:a.metadata?.importance==="important"?2:3;
export default function NetworkPostsPanel({networkId,currentUserId,memberProfiles=[],activities,isAdmin=false,readOnly=false,onRefresh,onNotify}:{networkId:string;currentUserId?:string|null;memberProfiles?:readonly CommunityMemberProfile[];activities:readonly NetworkActivity[];isAdmin?:boolean;readOnly?:boolean;onRefresh:()=>Promise<void>|void;onNotify:(message:string)=>void}){
 const {t}=useLanguage();
 const [composer,setComposer]=useState(false),[title,setTitle]=useState(""),[body,setBody]=useState(""),[photo,setPhoto]=useState<File|null>(null),[importance,setImportance]=useState<Importance>("normal"),[notifyAll,setNotifyAll]=useState(false),[busy,setBusy]=useState(false);
 const [selectedPostId,setSelectedPostId]=useState("");
 const deep=readNotificationDeepLink();
 const posts=useMemo(()=>activities.filter(a=>a.metadata?.content_kind==="post").sort((a,b)=>score(a)-score(b)||new Date(b.createdAt||0).getTime()-new Date(a.createdAt||0).getTime()),[activities]);
 const selectedPost=posts.find(p=>p.id===selectedPostId)||null;
 useEffect(()=>{if(deep.itemId&&deep.objectType==="post")setSelectedPostId(deep.itemId)},[deep.itemId,deep.objectType]);
 const openPost=(id:string)=>{setSelectedPostId(id);if(!readOnly)navigateNetworkObject(networkId,"community","post",id)};
 const closePost=()=>{setSelectedPostId("");clearNotificationDeepLink()};
 const submit=async()=>{if(title.trim().length<2)return;setBusy(true);let media:NetworkMediaAsset|undefined;try{if(photo)media=await uploadMediaAsset(photo,"post");const id=await createNetworkPost({title:title.trim(),body:body.trim()||undefined,importance:isAdmin?importance:"normal",notifyAll:isAdmin&&notifyAll});if(media)await bindMediaAsset(media.assetId,"activity",id);const mentions=extractMentions(title+" "+body);if(mentions.length)await routeNetworkMentions({mentions,title:"Mentioned in community post · "+title.trim(),body:body.trim()||title.trim(),surface:"community",entityType:"activity",entityId:id,priority:importance==="urgent"?"urgent":importance==="important"?"high":"normal"});setTitle("");setBody("");setPhoto(null);setImportance("normal");setNotifyAll(false);setComposer(false);onNotify(t("E9PostPublishedTxt"));await onRefresh();openPost(id)}catch(e:any){if(media)await removeMediaAsset(media).catch(()=>{});onNotify(e.message||t("E9PostPublishFailedTxt"))}finally{setBusy(false)}};
 const sharePost=async(post:NetworkActivity)=>{try{const url=new URL(networkObjectHref(networkId,"community","post",post.id),window.location.origin).toString();if(navigator.share)await navigator.share({title:post.title,text:post.body||"View this community post",url});else{await navigator.clipboard.writeText(url);onNotify("Link copied.")}}catch{}};
 return <section className="network-posts-panel" data-testid="qa-network-posts-panel">
  <NetworkSectionHead kicker={<><Sparkles size={12}/> {t("E9CommunityFeedTxt")}</>} title={t("E9PostsAndImportantUpdatesTxt")} description={t("E9PostsDescTxt")} action={!readOnly?<button data-testid="qa-post-create" className="btn primary small" onClick={()=>setComposer(v=>!v)}><Plus size={14}/> {t("E9CreatePostTxt")}</button>:undefined}/>
  {composer&&<div data-testid="qa-post-composer" className="card network-post-composer"><div className="form-grid"><label className="field full"><span>{t("TitleTxt")}</span><input className="text-input" value={title} onChange={e=>setTitle(e.target.value)} placeholder={t("E9PostTitlePlaceholderTxt")}/></label><label className="field full"><span>{t("E9PostBodyTxt")}</span><textarea className="text-input" rows={4} value={body} onChange={e=>setBody(e.target.value)} placeholder={t("E9PostBodyPlaceholderTxt")}/></label><small className="form-help full">{t("MentionPeopleRolesHelpTxt")}</small><label className="network-post-photo full"><ImagePlus size={18}/><span><b>{t("E9AddPhotoTxt")}</b><small>{photo?photo.name:t("SharedMediaCompressionHelpTxt")}</small></span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label>{isAdmin&&<><label className="field"><span>{t("E9ImportanceTxt")}</span><select className="select" value={importance} onChange={e=>setImportance(e.target.value as Importance)}><option value="normal">{t("E9NormalTxt")}</option><option value="important">{t("ImportantTxt")}</option><option value="urgent">{t("UrgentTxt")}</option></select></label><label className="network-post-broadcast"><input type="checkbox" checked={notifyAll} onChange={e=>setNotifyAll(e.target.checked)}/><span><b>{t("E9NotifyEveryoneTxt")}</b><small>{t("E9NotifyEveryoneDescTxt")}</small></span></label></>}<div className="form-actions full"><button className="btn" onClick={()=>setComposer(false)}>{t("CancelTxt")}</button><button className="btn primary" disabled={busy||title.trim().length<2} onClick={submit}><Send size={14}/> {t("PublishTxt")}</button></div></div></div>}
  <div className="network-post-list">{posts.map(post=>{const rawImportance=post.metadata?.importance;const imp:Importance=rawImportance==="urgent"||rawImportance==="important"?rawImportance:"normal";const pinned=!!post.metadata?.pinned_at;const linked=deep.itemId===post.id;return <article data-testid="qa-post-card" data-post-id={post.id} id={"activity-"+post.id} className={"card network-post-card importance-"+imp+" "+(pinned?"pinned ":"")+(linked?"deep-linked":"")} key={post.id}>
   <div className="network-post-head"><button className="community-card-title" onClick={()=>openPost(post.id)}><span className="warm-kicker"><UsersRound size={12}/> {post.authorLabel||t("E9CommunityMemberTxt")} {post.createdAt?"· "+new Date(post.createdAt).toLocaleString():""}</span><h3>{post.title}</h3></button><div className="network-post-badges">{pinned&&<span><Pin size={12}/>{t("E9PinnedTxt")}</span>}{imp!=="normal"&&<span className={imp}><ShieldAlert size={12}/>{imp==="urgent"?t("UrgentTxt"):t("ImportantTxt")}</span>}</div></div>
   {post.body&&<p className="network-post-body">{post.body}</p>}{post.thumbnailUrl&&<button className="network-post-media-open" onClick={()=>openPost(post.id)}><img className="network-post-media" src={post.thumbnailUrl} alt="" loading="lazy"/></button>}
   <div className="network-post-actions">{!readOnly&&<button className={post.myLiked?"active":""} onClick={async()=>{await toggleNetworkActivityLike(post.id);await onRefresh()}}><Heart size={15}/>{post.likeCount||0}</button>}<button onClick={()=>openPost(post.id)}><MessageSquareText size={15}/>{post.commentCount||0}</button>{isAdmin&&!readOnly&&<button onClick={async()=>{try{await setNetworkActivityPinned(post.id,!pinned);await onRefresh()}catch(e:any){onNotify(e.message||t("E9PinFailedTxt"))}}}>{pinned?<PinOff size={15}/>:<Pin size={15}/>} {pinned?t("E9UnpinTxt"):t("E9PinTxt")}</button>}<button onClick={()=>void sharePost(post)}><Share2 size={15}/> Share</button><button className="view-detail-action" onClick={()=>openPost(post.id)}><ArrowUpRight size={12}/><span>Details</span></button>{Boolean(post.metadata?.notify_all)&&<span className="network-post-broadcasted"><BellRing size={14}/>{t("E9BroadcastTxt")}</span>}</div>
  </article>})}{posts.length===0&&<NetworkEmpty icon={<MessageSquareText/>} title={t("E9NoPostsTxt")} description={t("E9NoPostsDescTxt")}/>}</div>
  {selectedPost&&<CommunityObjectDetail networkId={networkId} activity={selectedPost} objectType="post" currentUserId={currentUserId} isAdmin={isAdmin} readOnly={readOnly} memberProfiles={memberProfiles} onClose={closePost} onRefresh={onRefresh} onNotify={onNotify}/>}
 </section>;
}
