"use client";
import {useEffect,useMemo,useState} from "react";
import {BadgeIndianRupee,CalendarDays,Landmark,Plus,ReceiptIndianRupee,WalletCards} from "lucide-react";
import {createNetworkFund,fetchNetworkFundsSnapshot,recordNetworkFundTransaction,type NetworkFundsSnapshot} from "../../capabilities/template-product/remote";
import {useLanguage} from "../../lib/i18n";
import {NetworkEmpty,NetworkMetric,NetworkSectionHead} from "./NetworkUi";
import ResponsiveSectionTabs from "./ResponsiveSectionTabs";

const money=(v:number)=>`₹${Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
type FundsSection="overview"|"manage"|"dues"|"transactions";
export default function NetworkFundsPanel({onNotify}:{onNotify:(s:string)=>void}){
 const {t}=useLanguage();
 const [data,setData]=useState<NetworkFundsSnapshot|null>(null),[busy,setBusy]=useState(false),[section,setSection]=useState<FundsSection>("overview");
 const [fund,setFund]=useState({name:"",fundKind:"general",purpose:"",targetAmount:"",openingBalance:"",visibility:"members",membershipYearId:"",activityId:""});
 const [tx,setTx]=useState({fundId:"",transactionKind:"collection",amount:"",sourceEntityId:"",membershipYearId:"",paymentMethod:"bank",reference:"",note:"",visibility:"members"});
 const load=async()=>{try{setData(await fetchNetworkFundsSnapshot())}catch(e:any){onNotify(e.message||t("E6CouldNotSaveTxt"))}};
 useEffect(()=>{void load()},[]);
 const totals=useMemo(()=>{const funds=data?.funds||[];return {balance:funds.reduce((n,f)=>n+Number(f.balance||0),0),collected:funds.reduce((n,f)=>n+Number(f.collected||0),0),spent:funds.reduce((n,f)=>n+Number(f.spent||0),0),active:funds.filter(f=>f.status==="active").length}},[data]);
 const run=async(fn:()=>Promise<any>,message:string)=>{setBusy(true);try{await fn();onNotify(message);await load()}catch(e:any){onNotify(e.message||t("E6CouldNotSaveTxt"))}finally{setBusy(false)}};
 if(!data)return <NetworkEmpty title={t("E6FundsCollectionsTxt")} description={t("E6FundsDescTxt")}/>;
 return <div className="network-funds-panel" data-testid="qa-network-funds-panel">
  <NetworkSectionHead kicker={<><WalletCards size={13}/> {t("E6FundsCollectionsTxt")}</>} title={t("E6FundsCollectionsTxt")} description={t("E6FundsDescTxt")}/>
  <div className="network-metric-grid"><NetworkMetric value={money(totals.balance)} label={t("E6TotalBalanceTxt")}/><NetworkMetric value={money(totals.collected)} label={t("E6CollectedTxt")}/><NetworkMetric value={money(totals.spent)} label={t("E6SpentTxt")}/><NetworkMetric value={totals.active} label={t("E6ActiveFundsTxt")}/></div>
  <ResponsiveSectionTabs active={section} onChange={setSection} label="Funds and collections sections" options={[{id:"overview",label:"Funds",description:"Balances, targets and current collections"},...(data.is_admin?[{id:"manage" as const,label:"Record & manage",description:"Create funds and record transactions"},...(data.membership_dues.length?[{id:"dues" as const,label:"Membership dues",description:"Annual dues and outstanding balances",badge:data.membership_dues.filter(d=>Number(d.outstanding)>0).length||undefined}]:[])]:[]),{id:"transactions",label:"Transactions",description:"Recent receipts, collections and expenses"}]}/>
  {section==="overview"&&(data.funds.length===0?<NetworkEmpty icon={<Landmark/>} title={t("E6NoFundsTxt")} description={t("E6NoFundsDescTxt")}/>:<div className="network-fund-grid">{data.funds.map(f=>{const pct=f.target_amount?Math.min(100,Math.round((Number(f.collected||0)/Number(f.target_amount))*100)):0;return <article className="card network-fund-card" key={f.id}><div className="network-fund-head"><span className={`entity-kind-pill fund-${f.fund_kind}`}>{f.fund_kind.replaceAll("_"," ")}</span><b>{f.name}</b></div>{f.purpose&&<p>{f.purpose}</p>}<div className="network-fund-balance"><strong>{money(f.balance)}</strong><small>{t("E6BalanceTxt")}</small></div>{f.target_amount!=null&&<><div className="network-fund-progress"><i style={{width:`${pct}%`}}/></div><small>{t("E6ProgressTxt")}: {pct}% · {t("E6TargetTxt")} {money(Number(f.target_amount))}</small></>}<div className="network-fund-meta"><span>{t("E6CollectedTxt")} {money(f.collected)}</span><span>{t("E6SpentTxt")} {money(f.spent)}</span>{f.activity_title&&<span><CalendarDays size={12}/> {f.activity_title}</span>}</div></article>})}</div>)}
  {section==="overview"&&!data.is_admin&&data.visibility_mode==="admins"&&<section className="card network-finance-private"><Landmark/><p>{t("E6FinancePrivateTxt")}</p></section>}
  {section==="manage"&&data.is_admin&&<div className="network-funds-admin-grid">
   <section className="card"><NetworkSectionHead title={t("E6CreateFundTxt")}/><div className="form-grid"><label className="field full"><span>{t("E6FundNameTxt")}</span><input className="text-input" value={fund.name} onChange={e=>setFund({...fund,name:e.target.value})}/></label><label className="field"><span>{t("E6FundTypeTxt")}</span><select className="select" value={fund.fundKind} onChange={e=>setFund({...fund,fundKind:e.target.value})}><option value="membership">{t("E6MembershipFundTxt")}</option><option value="general">{t("E6GeneralFundTxt")}</option><option value="event">{t("E6EventFundTxt")}</option><option value="donation">{t("E6DonationFundTxt")}</option><option value="reserve">{t("E6ReserveFundTxt")}</option><option value="other">{t("E6OtherFundTxt")}</option></select></label><label className="field"><span>{t("E6TargetAmountTxt")}</span><input className="text-input" type="number" value={fund.targetAmount} onChange={e=>setFund({...fund,targetAmount:e.target.value})}/></label><label className="field"><span>{t("E6OpeningBalanceTxt")}</span><input className="text-input" type="number" value={fund.openingBalance} onChange={e=>setFund({...fund,openingBalance:e.target.value})}/></label><label className="field"><span>{t("E6VisibilityTxt")}</span><select className="select" value={fund.visibility} onChange={e=>setFund({...fund,visibility:e.target.value})}><option value="members">{t("E6MembersTxt")}</option><option value="highlighted">{t("E6HighlightedTxt")}</option><option value="admins">{t("E6AdminsTxt")}</option></select></label><label className="field full"><span>{t("E6LinkEventTxt")}</span><select className="select" value={fund.activityId} onChange={e=>setFund({...fund,activityId:e.target.value})}><option value="">{t("E6ChooseTxt")}</option>{data.events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label className="field full"><span>{t("E6PurposeTxt")}</span><textarea className="text-input" value={fund.purpose} onChange={e=>setFund({...fund,purpose:e.target.value})}/></label></div><button className="btn primary" disabled={busy||fund.name.trim().length<2} onClick={()=>run(()=>createNetworkFund({name:fund.name,fundKind:fund.fundKind,purpose:fund.purpose,targetAmount:fund.targetAmount?Number(fund.targetAmount):null,openingBalance:Number(fund.openingBalance||0),visibility:fund.visibility,activityId:fund.activityId||null}),t("E6FundCreatedTxt"))}><Plus size={14}/> {t("E6CreateFundTxt")}</button></section>
   <section className="card"><NetworkSectionHead title={t("E6RecordTransactionTxt")}/><div className="form-grid"><label className="field full"><span>{t("E6SelectFundTxt")}</span><select className="select" value={tx.fundId} onChange={e=>setTx({...tx,fundId:e.target.value})}><option value="">{t("E6ChooseTxt")}</option>{data.funds.filter(f=>f.status==="active").map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label className="field"><span>{t("E6TransactionTypeTxt")}</span><select className="select" value={tx.transactionKind} onChange={e=>setTx({...tx,transactionKind:e.target.value})}><option value="collection">{t("E6CollectionTxt")}</option><option value="expense">{t("E6ExpenseTxt")}</option><option value="refund">{t("E6RefundTxt")}</option><option value="adjustment">{t("E6AdjustmentTxt")}</option></select></label><label className="field"><span>{t("E6AmountTxt")}</span><input className="text-input" type="number" value={tx.amount} onChange={e=>setTx({...tx,amount:e.target.value})}/></label><label className="field"><span>{t("E6SourceFamilyTxt")}</span><select className="select" value={tx.sourceEntityId} onChange={e=>{const due=data.membership_dues.find(d=>d.family_entity_id===e.target.value);setTx({...tx,sourceEntityId:e.target.value,membershipYearId:due?.membership_year_id||tx.membershipYearId})}}><option value="">{t("E6ChooseTxt")}</option>{data.membership_dues.map(d=><option key={d.membership_id} value={d.family_entity_id}>{d.family_label} · {money(d.outstanding)}</option>)}</select></label><label className="field"><span>{t("E6PaymentMethodTxt")}</span><select className="select" value={tx.paymentMethod} onChange={e=>setTx({...tx,paymentMethod:e.target.value})}><option value="bank">{t("E6BankTxt")}</option><option value="cash">{t("E6CashTxt")}</option><option value="card">{t("E6CardTxt")}</option><option value="cheque">{t("E6ChequeTxt")}</option></select></label><label className="field"><span>{t("E6ReferenceTxt")}</span><input className="text-input" value={tx.reference} onChange={e=>setTx({...tx,reference:e.target.value})}/></label><label className="field full"><span>{t("E6NoteTxt")}</span><textarea className="text-input" value={tx.note} onChange={e=>setTx({...tx,note:e.target.value})}/></label></div><button className="btn primary" disabled={busy||!tx.fundId||Number(tx.amount)<=0} onClick={()=>run(()=>recordNetworkFundTransaction({fundId:tx.fundId,transactionKind:tx.transactionKind,amount:Number(tx.amount),sourceEntityId:tx.sourceEntityId||null,membershipYearId:tx.membershipYearId||null,paymentMethod:tx.paymentMethod,reference:tx.reference,note:tx.note,visibility:tx.visibility}),t("E6TransactionRecordedTxt"))}><ReceiptIndianRupee size={14}/> {t("E6RecordTransactionTxt")}</button></section>
  </div>}
  {section==="dues"&&data.is_admin&&data.membership_dues.length>0&&<section className="card network-membership-dues"><NetworkSectionHead title={t("E6MembershipDuesTxt")}/><div className="network-table-scroll"><table className="network-data-table"><thead><tr><th>{t("E6FamilyTxt")}</th><th>{t("E6MembershipYearTxt")}</th><th>{t("E6AmountTxt")}</th><th>{t("E6CollectedTxt")}</th><th>{t("E6OutstandingTxt")}</th><th>{t("E6PaymentStatusTxt")}</th></tr></thead><tbody>{data.membership_dues.map(d=><tr key={d.membership_id}><td><b>{d.family_label}</b><small>{d.representative_label||""}</small></td><td>{d.year_label}</td><td>{money(d.amount_due)}</td><td>{money(d.amount_paid)}</td><td>{money(d.outstanding)}</td><td>{d.payment_status}</td></tr>)}</tbody></table></div></section>}
  {section==="transactions"&&<section className="card"><NetworkSectionHead title={t("E6RecentTransactionsTxt")}/>{data.transactions.length===0?<p className="muted-copy">{t("E6NoTransactionsTxt")}</p>:<div className="network-table-scroll"><table className="network-data-table"><thead><tr><th>{t("E6ReceiptTxt")}</th><th>{t("E6FundNameTxt")}</th><th>{t("E6TransactionTypeTxt")}</th><th>{t("E6SourceFamilyTxt")}</th><th>{t("E6AmountTxt")}</th></tr></thead><tbody>{data.transactions.slice(0,80).map(x=><tr key={x.id}><td><b>{x.receipt_no||"—"}</b><small>{x.occurred_on}</small></td><td>{x.fund_name}</td><td>{x.transaction_kind}</td><td>{x.source_label||"—"}</td><td className={x.signed_amount<0?"money-negative":"money-positive"}>{x.signed_amount<0?"−":"+"}{money(Math.abs(x.signed_amount))}</td></tr>)}</tbody></table></div>}</section>}
 </div>;
}
