"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowUpRight,CalendarDays,Heart,MapPin,MessageSquareText,Plus,Share2,Sparkles,UsersRound} from "lucide-react";
import type {NetworkActivity,NetworkActivityType} from "../../core/network-os/contracts";
import type {NetworkGroup} from "../../capabilities/activity/remote";
import {networkObjectHref,navigateNetworkObject} from "../../lib/network-routes";
import {clearNotificationDeepLink,readNotificationDeepLink} from "../../lib/notification-routing";
import {NetworkEmpty,NetworkSectionHead} from "./NetworkUi";
import ResponsiveSectionTabs from "./ResponsiveSectionTabs";
import CommunityObjectDetail,{type CommunityMemberProfile} from "./CommunityObjectDetail";
import {useLanguage} from "../../lib/i18n";

const defaultTypeLabel:Record<NetworkActivityType,string>={event:"Meetups & events",memory:"Memories",milestone:"Milestones",announcement:"Updates"};
export default function NetworkActivityHub({networkId,currentUserId,memberProfiles=[],activities,groups=[],isAdmin=false,readOnly=false,onRefresh,onNotify,onCreate,onRsvp,onCreateGroup,onToggleGroup,onLike,copy}:{networkId:string;currentUserId?:string|null;memberProfiles?:readonly CommunityMemberProfile[];activities:readonly NetworkActivity[];groups?:readonly NetworkGroup[];isAdmin?:boolean;readOnly?:boolean;onRefresh:()=>Promise<void>|void;onNotify?:(message:string)=>void;onCreate?:(input:{type:NetworkActivityType;title:string;body?:string;startsAt?:string;place?:string;photoFile?:File})=>Promise<void>|void;onRsvp?:(id:string,response:"going"|"maybe"|"declined")=>Promise<void>|void;onCreateGroup?:(input:{name:string;groupType?:string;description?:string})=>Promise<void>|void;onToggleGroup?:(group:NetworkGroup)=>Promise<void>|void;onLike?:(id:string)=>Promise<void>|void;copy?:{title?:string;description?:string;eventLabel?:string;memoryLabel?:string;milestoneLabel?:string;announcementLabel?:string;groupTitle?:string;groupDescription?:string}}){
 const {t}=useLanguage();
 const typeLabel:Record<NetworkActivityType,string>={event:copy?.eventLabel||defaultTypeLabel.event,memory:copy?.memoryLabel||defaultTypeLabel.memory,milestone:copy?.milestoneLabel||defaultTypeLabel.milestone,announcement:copy?.announcementLabel||defaultTypeLabel.announcement};
 const [area,setArea]=useState<"activities"|"groups">("activities"),[type,setType]=useState<NetworkActivityType>("event"),[composer,setComposer]=useState(false),[title,setTitle]=useState(""),[body,setBody]=useState(""),[place,setPlace]=useState(""),[startsAt,setStartsAt]=useState(""),[photoFile,setPhotoFile]=useState<File|null>(null);
 const [groupComposer,setGroupComposer]=useState(false),[groupName,setGroupName]=useState(""),[groupType,setGroupType]=useState("chapter"),[groupDescription,setGroupDescription]=useState("");
 const [selectedActivityId,setSelectedActivityId]=useState(""),[selectedGroupId,setSelectedGroupId]=useState("");
 const filtered=useMemo(()=>activities.filter(a=>a.type===type),[activities,type]);
 const selectedActivity=activities.find(a=>a.id===selectedActivityId)||null,selectedGroup=groups.find(g=>g.id===selectedGroupId)||null;
 useEffect(()=>{const deep=readNotificationDeepLink();if(!deep.itemId)return;if(deep.objectType==="group"){setArea("groups");setSelectedGroupId(deep.itemId)}else if(deep.objectType==="activity"){setArea("activities");setSelectedActivityId(deep.itemId)}},[]);
 const openActivity=(id:string)=>{setSelectedActivityId(id);setSelectedGroupId("");if(!readOnly)navigateNetworkObject(networkId,"community","activity",id)};
 const openGroup=(id:string)=>{setSelectedGroupId(id);setSelectedActivityId("");setArea("groups");if(!readOnly)navigateNetworkObject(networkId,"community","group",id)};
 const closeDetail=()=>{setSelectedActivityId("");setSelectedGroupId("");clearNotificationDeepLink()};
 const submit=async()=>{if(!title.trim())return;await onCreate?.({type,title:title.trim(),body:body.trim()||undefined,place:place.trim()||undefined,startsAt:startsAt||undefined,photoFile:photoFile||undefined});setComposer(false);setTitle("");setBody("");setPlace("");setStartsAt("");setPhotoFile(null)};
 const submitGroup=async()=>{if(!groupName.trim())return;await onCreateGroup?.({name:groupName.trim(),groupType:groupType.trim()||"group",description:groupDescription.trim()||undefined});setGroupComposer(false);setGroupName("");setGroupType("chapter");setGroupDescription("")};
 const shareCard=async(a:NetworkActivity)=>{try{const url=readOnly?window.location.href:new URL(networkObjectHref(networkId,"community","activity",a.id),window.location.origin).toString();if(navigator.share)await navigator.share({title:a.title,text:a.body||"View this community item",url});else{await navigator.clipboard.writeText(url);onNotify?.("Link copied.")}}catch{}};
 return <div className="network-activity-hub"><NetworkSectionHead kicker={<><Sparkles size={12}/> {t("SharedNetworkLifeTxt")}</>} title={copy?.title||t("CommunityEventsAndMemoriesTxt")} description={copy?.description||t("TheSameActivityEngineCanPowerFamilyTxt")} action={!readOnly?<button data-testid="qa-activity-create" className="btn primary small" onClick={()=>{setArea("activities");setComposer(v=>!v)}}><Plus size={14}/> {t("AddTxt")}</button>:undefined}/>
  <ResponsiveSectionTabs active={area} onChange={setArea} label="Community life areas" options={[{id:"activities",label:"Activities & updates",description:"Events, memories, milestones and announcements"},{id:"groups",label:"Groups & chapters",description:copy?.groupDescription||t("ChaptersGuildsCommitteesOrInterestGroupsCanTxt")}]}/>
  {area==="activities"&&<><ResponsiveSectionTabs active={type} onChange={setType} label="Activity type" options={(["event","memory","milestone","announcement"] as NetworkActivityType[]).map(k=>({id:k,label:typeLabel[k],icon:k==="event"?<CalendarDays size={14}/>:k==="memory"?<Heart size={14}/>:k==="milestone"?<Sparkles size={14}/>:<MessageSquareText size={14}/>}))}/>
   {composer&&<section data-testid="qa-activity-composer" className="card activity-composer"><div className="form-grid"><label className="field full"><span>{t("TypeTxt")}</span><select className="select" value={type} onChange={e=>setType(e.target.value as NetworkActivityType)}>{Object.entries(typeLabel).filter(([k])=>isAdmin||k==="memory"||k==="milestone").map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field full"><span>{t("TitleTxt")}</span><input className="text-input" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field full"><span>{t("StoryDetailsTxt")}</span><textarea className="text-input" value={body} onChange={e=>setBody(e.target.value)} rows={3}/></label>{type!=="milestone"&&<label className="field full"><span>{t("ActivityPhotoOptionalTxt")}</span><input className="text-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhotoFile(e.target.files?.[0]||null)}/><small className="field-help">{t("SharedMediaCompressionHelpTxt")}</small></label>}{type==="event"&&<><label className="field"><span>{t("DateAndTimeTxt")}</span><input className="text-input" type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><label className="field"><span>{t("PlaceTxt")}</span><input className="text-input" value={place} onChange={e=>setPlace(e.target.value)}/></label></>}<div className="form-actions full"><button className="btn" onClick={()=>setComposer(false)}>{t("CancelTxt")}</button><button className="btn primary" onClick={submit}>{t("PublishTxt")}</button></div></div></section>}
   <div className="activity-grid">{filtered.map(a=><article data-testid="qa-activity-card" data-activity-id={a.id} className="card activity-card community-object-card" key={a.id}>{a.thumbnailUrl&&<button className="activity-media-open" onClick={()=>openActivity(a.id)}><img className="activity-media-thumb" src={a.thumbnailUrl} alt="" loading="lazy"/></button>}<span className={"activity-type "+a.type}>{typeLabel[a.type]}</span><button className="community-card-title" onClick={()=>openActivity(a.id)}><h3>{a.title}</h3></button>{a.body&&<p>{a.body}</p>}<div className="activity-meta">{a.startsAt&&<span><CalendarDays size={13}/>{new Date(a.startsAt).toLocaleString()}</span>}{a.place&&<span><MapPin size={13}/>{a.place}</span>}{a.type==="event"&&<button type="button" className="activity-rsvp-summary" onClick={()=>openActivity(a.id)}><UsersRound size={13}/>{a.goingCount||0} going · View people</button>}</div>{a.type==="event"&&!readOnly&&<div className="activity-rsvp"><button className={a.myRsvp==="going"?"active":""} onClick={()=>onRsvp?.(a.id,"going")}>Going</button><button className={a.myRsvp==="maybe"?"active":""} onClick={()=>onRsvp?.(a.id,"maybe")}>Maybe</button><button className={a.myRsvp==="declined"?"active":""} onClick={()=>onRsvp?.(a.id,"declined")}>Can’t go</button></div>}<div className="activity-engagement">{!readOnly&&<button className={a.myLiked?"active":""} onClick={()=>onLike?.(a.id)}><Heart size={14}/>{a.likeCount||0}</button>}<button onClick={()=>openActivity(a.id)}><MessageSquareText size={14}/>{a.commentCount||0}</button><button onClick={()=>void shareCard(a)}><Share2 size={14}/> Share</button><button className="view-detail-action" onClick={()=>openActivity(a.id)}><ArrowUpRight size={12}/><span>Details</span></button></div></article>)}{filtered.length===0&&<NetworkEmpty icon={type==="event"?<CalendarDays/>:<Heart/>} title={"No "+typeLabel[type].toLowerCase()+" yet"} description={t("ThisSpaceWillGrowAsTheNetworkTxt")}/>}</div>
  </>}
  {area==="groups"&&<section className="groups-strip card community-groups-workspace"><div className="community-groups-head"><div><span className="warm-kicker"><UsersRound size={12}/> {t("GroupsAndChaptersTxt")}</span><h3>{copy?.groupTitle||t("SmallerCirclesInsideTheNetworkTxt")}</h3><p>{copy?.groupDescription||t("ChaptersGuildsCommitteesOrInterestGroupsCanTxt")}</p></div>{isAdmin&&!readOnly&&onCreateGroup&&<button className="btn primary small" onClick={()=>setGroupComposer(v=>!v)}><Plus size={14}/> Create group</button>}</div>
   {groupComposer&&<div className="community-group-composer form-grid"><label className="field full"><span>Name</span><input className="text-input" value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="e.g. Cultural Committee"/></label><label className="field"><span>Type</span><select className="select" value={groupType} onChange={e=>setGroupType(e.target.value)}><option value="chapter">Chapter</option><option value="committee">Committee</option><option value="interest">Interest group</option><option value="group">Group</option></select></label><label className="field full"><span>Purpose / description</span><textarea className="text-input" rows={3} value={groupDescription} onChange={e=>setGroupDescription(e.target.value)}/></label><div className="form-actions full"><button className="btn" onClick={()=>setGroupComposer(false)}>Cancel</button><button className="btn primary" disabled={!groupName.trim()} onClick={submitGroup}>Create group</button></div></div>}
   <div className="community-group-card-grid">{groups.map(g=><article className={"community-group-card "+(g.myMember?"joined":"")} key={g.id}><button className="community-group-open" onClick={()=>openGroup(g.id)}><span><UsersRound/></span><div><b>{g.name}</b><small>{g.groupType} · {g.memberCount} member{g.memberCount===1?"":"s"}</small><p>{g.description||"Open to view details and members."}</p></div></button><div><button className="btn small" onClick={()=>openGroup(g.id)}>View</button>{!readOnly&&<button className={g.myMember?"btn small":"btn primary small"} onClick={()=>onToggleGroup?.(g)}>{g.myMember?"Leave":"Join"}</button>}</div></article>)}{groups.length===0&&<NetworkEmpty icon={<UsersRound/>} title="No groups yet" description="Create committees, chapters or interest groups with a clear purpose and visible membership."/>}</div>
  </section>}
  {(selectedActivity||selectedGroup)&&<CommunityObjectDetail networkId={networkId} activity={selectedActivity} group={selectedGroup} objectType={selectedActivity?"activity":"group"} currentUserId={currentUserId} isAdmin={isAdmin} readOnly={readOnly} memberProfiles={memberProfiles} onClose={closeDetail} onRefresh={onRefresh} onNotify={onNotify} labels={{groupLabel:copy?.groupTitle,eventLabel:copy?.eventLabel,memoryLabel:copy?.memoryLabel,milestoneLabel:copy?.milestoneLabel}}/>}
 </div>
}
