"use client";
import {useMemo,useState} from "react";
import {BellRing,Heart,ImagePlus,MessageSquareText,Pin,PinOff,Plus,Send,ShieldAlert,Sparkles,UsersRound} from "lucide-react";
import type {NetworkActivity} from "../../core/network-os/contracts";
import {addNetworkPostComment,createNetworkPost,fetchNetworkActivityComments,setNetworkActivityPinned,toggleNetworkActivityLike,type NetworkActivityComment} from "../../capabilities/activity/remote";
import {bindMediaAsset,removeMediaAsset,uploadMediaAsset,type NetworkMediaAsset} from "../../lib/storage";
import {extractMentions} from "../../lib/mentions";
import {routeNetworkMentions} from "../../lib/remote";
import {readNotificationDeepLink} from "../../lib/notification-routing";
import {useLanguage} from "../../lib/i18n";
import {NetworkEmpty,NetworkSectionHead} from "./NetworkUi";

type Importance="normal"|"important"|"urgent";
const score=(a:NetworkActivity)=>a.metadata?.pinned_at?0:a.metadata?.importance==="urgent"?1:a.metadata?.importance==="important"?2:3;
export default function NetworkPostsPanel({activities,isAdmin=false,readOnly=false,onRefresh,onNotify}:{activities:readonly NetworkActivity[];isAdmin?:boolean;readOnly?:boolean;onRefresh:()=>Promise<void>|void;onNotify:(message:string)=>void}){
 const {t}=useLanguage();
 const [composer,setComposer]=useState(false),[title,setTitle]=useState(""),[body,setBody]=useState(""),[photo,setPhoto]=useState<File|null>(null),[importance,setImportance]=useState<Importance>("normal"),[notifyAll,setNotifyAll]=useState(false),[busy,setBusy]=useState(false);
 const [openComments,setOpenComments]=useState(""),[comments,setComments]=useState<Record<string,NetworkActivityComment[]>>({}),[comment,setComment]=useState("");
 const deep=readNotificationDeepLink();
 const posts=useMemo(()=>activities.filter(a=>a.metadata?.content_kind==="post").sort((a,b)=>score(a)-score(b)||new Date(b.createdAt||0).getTime()-new Date(a.createdAt||0).getTime()),[activities]);
 const submit=async()=>{if(title.trim().length<2)return;setBusy(true);let media:NetworkMediaAsset|undefined;try{if(photo)media=await uploadMediaAsset(photo,"post");const id=await createNetworkPost({title:title.trim(),body:body.trim()||undefined,importance:isAdmin?importance:"normal",notifyAll:isAdmin&&notifyAll});if(media)await bindMediaAsset(media.assetId,"activity",id);const mentions=extractMentions(`${title} ${body}`);if(mentions.length)await routeNetworkMentions({mentions,title:`Mentioned in community post · ${title.trim()}`,body:body.trim()||title.trim(),surface:"community",entityType:"activity",entityId:id,priority:importance==="urgent"?"urgent":importance==="important"?"high":"normal"});setTitle("");setBody("");setPhoto(null);setImportance("normal");setNotifyAll(false);setComposer(false);onNotify(t("E9PostPublishedTxt"));await onRefresh()}catch(e:any){if(media)await removeMediaAsset(media).catch(()=>{});onNotify(e.message||t("E9PostPublishFailedTxt"))}finally{setBusy(false)}};
 const loadComments=async(id:string)=>{try{const nextComments=await fetchNetworkActivityComments(id);setComments(x=>({...x,[id]:nextComments}));setOpenComments(id)}catch(e:any){onNotify(e.message||t("E9CommentsLoadFailedTxt"))}};
 const sendComment=async(id:string)=>{if(comment.trim().length<1)return;setBusy(true);try{await addNetworkPostComment(id,comment.trim());const mentions=extractMentions(comment);if(mentions.length)await routeNetworkMentions({mentions,title:t("E9MentionedInCommentTxt"),body:comment.trim(),surface:"community",entityType:"activity",entityId:id});setComment("");await loadComments(id);await onRefresh()}catch(e:any){onNotify(e.message||t("E9CommentFailedTxt"))}finally{setBusy(false)}};
 return <section className="network-posts-panel" data-testid="qa-network-posts-panel">
  <NetworkSectionHead kicker={<><Sparkles size={12}/> {t("E9CommunityFeedTxt")}</>} title={t("E9PostsAndImportantUpdatesTxt")} description={t("E9PostsDescTxt")} action={!readOnly?<button className="btn primary small" onClick={()=>setComposer(v=>!v)}><Plus size={14}/> {t("E9CreatePostTxt")}</button>:undefined}/>
  {composer&&<div className="card network-post-composer"><div className="form-grid"><label className="field full"><span>{t("TitleTxt")}</span><input className="text-input" value={title} onChange={e=>setTitle(e.target.value)} placeholder={t("E9PostTitlePlaceholderTxt")}/></label><label className="field full"><span>{t("E9PostBodyTxt")}</span><textarea className="text-input" rows={4} value={body} onChange={e=>setBody(e.target.value)} placeholder={t("E9PostBodyPlaceholderTxt")}/></label><small className="form-help full">{t("MentionPeopleRolesHelpTxt")}</small><label className="network-post-photo full"><ImagePlus size={18}/><span><b>{t("E9AddPhotoTxt")}</b><small>{photo?photo.name:t("SharedMediaCompressionHelpTxt")}</small></span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label>{isAdmin&&<><label className="field"><span>{t("E9ImportanceTxt")}</span><select className="select" value={importance} onChange={e=>setImportance(e.target.value as Importance)}><option value="normal">{t("E9NormalTxt")}</option><option value="important">{t("ImportantTxt")}</option><option value="urgent">{t("UrgentTxt")}</option></select></label><label className="network-post-broadcast"><input type="checkbox" checked={notifyAll} onChange={e=>setNotifyAll(e.target.checked)}/><span><b>{t("E9NotifyEveryoneTxt")}</b><small>{t("E9NotifyEveryoneDescTxt")}</small></span></label></>}<div className="form-actions full"><button className="btn" onClick={()=>setComposer(false)}>{t("CancelTxt")}</button><button className="btn primary" disabled={busy||title.trim().length<2} onClick={submit}><Send size={14}/> {t("PublishTxt")}</button></div></div></div>}
  <div className="network-post-list">{posts.map(post=>{const imp=String(post.metadata?.importance||"normal") as Importance;const pinned=!!post.metadata?.pinned_at;const linked=deep.itemId===post.id;return <article id={`activity-${post.id}`} className={`card network-post-card importance-${imp} ${pinned?"pinned":""} ${linked?"deep-linked":""}`} key={post.id}>
    <div className="network-post-head"><div><span className="warm-kicker"><UsersRound size={12}/> {post.authorLabel||t("E9CommunityMemberTxt")} {post.createdAt?`· ${new Date(post.createdAt).toLocaleString()}`:""}</span><h3>{post.title}</h3></div><div className="network-post-badges">{pinned&&<span><Pin size={12}/>{t("E9PinnedTxt")}</span>}{imp!=="normal"&&<span className={imp}><ShieldAlert size={12}/>{imp==="urgent"?t("UrgentTxt"):t("ImportantTxt")}</span>}</div></div>
    {post.body&&<p className="network-post-body">{post.body}</p>}{post.thumbnailUrl&&<img className="network-post-media" src={post.thumbnailUrl} alt="" loading="lazy" decoding="async"/>}
    <div className="network-post-actions"><button className={post.myLiked?"active":""} onClick={async()=>{await toggleNetworkActivityLike(post.id);await onRefresh()}}><Heart size={15}/>{post.likeCount||0}</button><button onClick={async()=>{if(openComments===post.id)setOpenComments("");else await loadComments(post.id)}}><MessageSquareText size={15}/>{post.commentCount||0}</button>{isAdmin&&!readOnly&&<button onClick={async()=>{try{await setNetworkActivityPinned(post.id,!pinned);await onRefresh()}catch(e:any){onNotify(e.message||t("E9PinFailedTxt"))}}}>{pinned?<PinOff size={15}/>:<Pin size={15}/>} {pinned?t("E9UnpinTxt"):t("E9PinTxt")}</button>}{Boolean(post.metadata?.notify_all)&&<span className="network-post-broadcasted"><BellRing size={14}/>{t("E9BroadcastTxt")}</span>}</div>
    {openComments===post.id&&<div className="network-post-comments">{(comments[post.id]||[]).map(c=><div key={c.id}><b>{c.authorLabel}</b><span>{c.body}</span><small>{new Date(c.createdAt).toLocaleString()}</small></div>)}{!readOnly&&<div className="network-post-comment-form"><input className="text-input" value={comment} onChange={e=>setComment(e.target.value)} placeholder={t("E9WriteCommentTxt")}/><button className="btn small" disabled={busy||comment.trim().length<1} onClick={()=>sendComment(post.id)}><Send size={13}/>{t("E9CommentTxt")}</button></div>}</div>}
  </article>})}{posts.length===0&&<NetworkEmpty icon={<MessageSquareText/>} title={t("E9NoPostsTxt")} description={t("E9NoPostsDescTxt")}/>}</div>
 </section>;
}
