import {runtimeObservabilityStore} from './store';
type Cleanup=()=>void;let cleanup:Cleanup|null=null;
export function startBrowserObservation():Cleanup{if(cleanup)return cleanup;const ds:Cleanup[]=[];patchFetch(ds);patchConsole(ds);observeVitals(ds);observeErrors(ds);observeInteractions(ds);cleanup=()=>{while(ds.length){try{ds.pop()?.()}catch{}}cleanup=null};return cleanup}
function patchFetch(ds:Cleanup[]){if(typeof window==='undefined'||typeof window.fetch!=='function')return;const orig=window.fetch;window.fetch=async function(input:RequestInfo|URL,init?:RequestInit){const method=String(init?.method??(input instanceof Request?input.method:'GET')).toUpperCase(),url=input instanceof Request?input.url:String(input),t=performance.now();try{const r=await orig.call(this,input,init);runtimeObservabilityStore.recordNetwork({method,url,status:r.status,ok:r.ok,durationMs:performance.now()-t,at:Date.now(),type:r.headers.get('content-type')||undefined,responseSizeKB:size(r)});return r}catch(e){runtimeObservabilityStore.recordNetwork({method,url,status:null,ok:false,durationMs:performance.now()-t,at:Date.now(),error:e instanceof Error?e.message:String(e)});throw e}};ds.push(()=>{window.fetch=orig})}
function size(r:Response){const n=Number(r.headers.get('content-length'));return Number.isFinite(n)&&n>0?Math.round(n/1024*10)/10:null}
function patchConsole(ds:Cleanup[]){const levels=['log','info','warn','error','debug'] as const;for(const level of levels){const orig=console[level];console[level]=(...args:any[])=>{try{runtimeObservabilityStore.recordConsole({level,message:args.map(safe).join(' '),at:Date.now()})}catch{}orig.apply(console,args)};ds.push(()=>{console[level]=orig})}}
function safe(v:any){if(typeof v==='string')return v;if(v instanceof Error)return v.stack||v.message;try{return JSON.stringify(v,(_k,x)=>typeof x==='bigint'?String(x):x).slice(0,1200)}catch{return String(v)}}
function observeErrors(ds:Cleanup[]){const a=(e:ErrorEvent)=>runtimeObservabilityStore.recordError({kind:'error',message:e.message||'Unknown browser error',stack:e.error instanceof Error?e.error.stack:undefined,at:Date.now()}),b=(e:PromiseRejectionEvent)=>{const r=e.reason;runtimeObservabilityStore.recordError({kind:'unhandledrejection',message:r instanceof Error?r.message:String(r),stack:r instanceof Error?r.stack:undefined,at:Date.now()})};window.addEventListener('error',a);window.addEventListener('unhandledrejection',b);ds.push(()=>window.removeEventListener('error',a));ds.push(()=>window.removeEventListener('unhandledrejection',b))}
function observeInteractions(ds:Cleanup[]){let prev=0;const h=(e:Event)=>{const t=Date.now();runtimeObservabilityStore.recordInteraction({type:e.type,target:describe(e.target),at:t,elapsedFromPreviousMs:prev?t-prev:null});prev=t};for(const name of ['click','input','change','submit','keydown']){document.addEventListener(name,h,true);ds.push(()=>document.removeEventListener(name,h,true))}}
function describe(x:EventTarget|null){if(!(x instanceof Element))return String(x||'unknown');const id=x.id?`#${x.id}`:'',c=typeof x.className==='string'&&x.className?'.'+x.className.trim().split(/\s+/).slice(0,2).join('.'):'';return`${x.tagName.toLowerCase()}${id}${c}`}
function observeVitals(ds:Cleanup[]){if(typeof PerformanceObserver==='undefined')return;try{const o=new PerformanceObserver(list=>{for(const e of list.getEntries() as any){const el=e.element as Element|undefined;runtimeObservabilityStore.setLcp(e.startTime,el?describe(el):undefined)}});o.observe({type:'largest-contentful-paint',buffered:true} as any);ds.push(()=>o.disconnect())}catch{}
 try{const o=new PerformanceObserver(list=>{for(const e of list.getEntries() as any){if(!e.hadRecentInput)runtimeObservabilityStore.addCls(e.value,e.sources?.[0]?.node?describe(e.sources[0].node):undefined)}});o.observe({type:'layout-shift',buffered:true} as any);ds.push(()=>o.disconnect())}catch{}
 try{const o=new PerformanceObserver(list=>{for(const e of list.getEntries() as any){const d=e.duration||0;if(d)runtimeObservabilityStore.setInp(d,`${e.name||'interaction'} ${e.target?describe(e.target):''}`)}});o.observe({type:'event',buffered:true,durationThreshold:40} as any);ds.push(()=>o.disconnect())}catch{}
 try{const o=new PerformanceObserver(list=>{for(const e of list.getEntries())runtimeObservabilityStore.recordLongTask({durationMs:e.duration,at:Date.now()})});o.observe({type:'longtask',buffered:true} as any);ds.push(()=>o.disconnect())}catch{}}
