import type {ConsoleSample,DiagnosticFinding,HistorySnapshot,InspectionSnapshot,InteractionSample,LongTaskSample,MountSample,NetworkSample,RenderSample,RuntimeErrorSample,RuntimeSnapshot,VitalsSnapshot} from "./types";
const MAX=400;
const emptyVitals=():VitalsSnapshot=>({cls:{value:0,at:Date.now()},longTasks:[]});
class Store{
 private startedAt=Date.now(); private renders:RenderSample[]=[]; private network:NetworkSample[]=[]; private errors:RuntimeErrorSample[]=[]; private console:ConsoleSample[]=[]; private longTasks:LongTaskSample[]=[]; private mounts:MountSample[]=[]; private interactions:InteractionSample[]=[]; private vitals:VitalsSnapshot=emptyVitals(); private inspection:InspectionSnapshot|null=null; private listeners=new Set<()=>void>(); private history:HistorySnapshot[]=[];
 subscribe=(f:()=>void)=>{this.listeners.add(f);return()=>this.listeners.delete(f)}; private emit(){for(const f of this.listeners)f()} private push<T>(a:T[],v:T){a.push(v);if(a.length>MAX)a.splice(0,a.length-MAX);this.emit()}
 recordRender(v:RenderSample){this.push(this.renders,v)} recordNetwork(v:NetworkSample){this.push(this.network,v)} recordError(v:RuntimeErrorSample){this.push(this.errors,v)} recordConsole(v:ConsoleSample){this.push(this.console,v)} recordLongTask(v:LongTaskSample){this.longTasks.push(v);if(this.longTasks.length>MAX)this.longTasks.shift();this.vitals.longTasks=[...this.longTasks];this.emit()} recordMount(v:MountSample){this.push(this.mounts,v)} recordInteraction(v:InteractionSample){this.push(this.interactions,v)}
 setLcp(value:number,detail?:string){this.vitals={...this.vitals,lcp:{value,detail,at:Date.now()}};this.emit()} addCls(value:number,detail?:string){this.vitals={...this.vitals,cls:{value:this.vitals.cls.value+value,detail,at:Date.now()}};this.emit()} setInp(value:number,detail?:string){if(!this.vitals.inp||value>this.vitals.inp.value)this.vitals={...this.vitals,inp:{value,detail,at:Date.now()}};this.emit()} setInspection(v:InspectionSnapshot|null){this.inspection=v;this.emit()}
 reset(){this.startedAt=Date.now();this.renders=[];this.network=[];this.errors=[];this.console=[];this.longTasks=[];this.mounts=[];this.interactions=[];this.vitals=emptyVitals();this.inspection=null;this.emit()}
 snapshot():RuntimeSnapshot{return{startedAt:this.startedAt,renders:[...this.renders],network:[...this.network],errors:[...this.errors],console:[...this.console],longTasks:[...this.longTasks],mounts:[...this.mounts],interactions:[...this.interactions],vitals:{...this.vitals,longTasks:[...this.vitals.longTasks]},inspection:this.inspection,domNodes:typeof document==='undefined'?0:document.getElementsByTagName('*').length,route:typeof location==='undefined'?'':location.pathname+location.search,environment:env(this.startedAt)}}
 saveHistory(label='Snapshot'){const report=this.snapshot();const item={id:String(Date.now()),label,at:Date.now(),report,findings:this.findings(report)};this.history=[...this.history,item].slice(-20);this.emit();return item} getHistory(){return[...this.history]} clearHistory(){this.history=[];this.emit()}
 findings(s=this.snapshot()):DiagnosticFinding[]{const out:DiagnosticFinding[]=[];const groups=new Map<string,RenderSample[]>();for(const x of s.renders){const g=groups.get(x.name)||[];g.push(x);groups.set(x.name,g)}for(const[name,a]of groups){const slow=a.filter(x=>x.actualDurationMs>=50);if(slow.length){const worst=Math.max(...slow.map(x=>x.actualDurationMs));out.push(f(worst>=150?'critical':'warning','Performance',`${name} has expensive React commits`,`${slow.length}/${a.length} commits took ≥50ms`,`worst ${worst.toFixed(1)}ms`,'Inspect this boundary for expensive render work, unstable props, large lists, or synchronous child work.'))}}
 const slow=s.network.filter(x=>x.durationMs>=1000);if(slow.length){const w=slow.reduce((a,b)=>a.durationMs>b.durationMs?a:b);out.push(f(w.durationMs>=3000?'critical':'warning','Network','Slow API calls detected',`${slow.length} request(s) exceeded 1s`,`${w.method} ${short(w.url)} ${w.durationMs.toFixed(0)}ms`,'Check backend latency, request waterfalls, caching and whether the request is necessary on this route.'))}
 const failed=s.network.filter(x=>x.ok===false||((x.status||0)>=400));if(failed.length)out.push(f('critical','Network','Failed network requests observed',`${failed.length} request(s) failed`,failed.slice(-3).map(x=>`${x.status||'ERR'} ${short(x.url)}`).join(' | '),'Inspect the request payload/auth/RLS/API response and the user flow that initiated it.'));
 const repeats=new Map<string,NetworkSample[]>();for(const x of s.network){if(!['GET','HEAD'].includes(x.method))continue;const k=x.method+' '+norm(x.url);const g=repeats.get(k)||[];g.push(x);repeats.set(k,g)}for(const[k,a]of repeats){if(a.length>=4&&a[a.length-1].at-a[0].at<=10000)out.push(f('warning','Network','Repeated request burst',`${a.length} equivalent requests occurred within 10s`,k,'Look for duplicated effects, remount-triggered fetching, missing request dedupe or unstable query keys.'))}
 if(s.errors.length){const e=s.errors[s.errors.length-1];out.push(f('critical','Errors','Runtime errors observed',`${s.errors.length} error/rejection event(s) captured`,e.message,'Inspect the latest stack. The observability tool only observes errors and does not suppress them.'))}
 const cErr=s.console.filter(x=>x.level==='error').length,cWarn=s.console.filter(x=>x.level==='warn').length;if(cErr)out.push(f('warning','Console','Console errors present',`${cErr} console.error call(s) captured`,s.console.filter(x=>x.level==='error').slice(-1)[0]?.message||'','Remove unexpected runtime errors and noisy failure paths.'));else if(cWarn>=10)out.push(f('warning','Console','High console warning volume',`${cWarn} warnings captured`,'warning volume','Repeated warnings often reveal loops, deprecated paths, failed resources or noisy retries.'));
 const recent=s.longTasks.filter(x=>Date.now()-x.at<=30000);if(recent.length>=3){const total=recent.reduce((n,x)=>n+x.durationMs,0);out.push(f(total>=1000?'critical':'warning','Vitals','Main thread repeatedly blocked',`${recent.length} long tasks in the last 30s`,`${total.toFixed(0)}ms total`,'Correlate the timestamps with React commits and interactions; split or defer heavy synchronous work.'))}
 if(s.vitals.lcp&&s.vitals.lcp.value>=4000)out.push(f('critical','Vitals','Poor LCP',`Largest Contentful Paint is ${s.vitals.lcp.value.toFixed(0)}ms`,s.vitals.lcp.detail||'','Optimize the LCP element, blocking data, images and critical rendering path.'));if(s.vitals.cls.value>=.25)out.push(f('critical','Vitals','High layout shift',`CLS is ${s.vitals.cls.value.toFixed(3)}`,s.vitals.cls.detail||'','Reserve space for late content/images and avoid layout-changing inserts above visible content.'));if(s.vitals.inp&&s.vitals.inp.value>=500)out.push(f('critical','Vitals','Poor interaction responsiveness',`Worst observed interaction is ${s.vitals.inp.value.toFixed(0)}ms`,s.vitals.inp.detail||'','Correlate the interaction with long tasks and expensive React commits.'));
 const byName=new Map<string,MountSample[]>();for(const x of s.mounts){const g=byName.get(x.name)||[];g.push(x);byName.set(x.name,g)}for(const[name,a]of byName){const recent=a.filter(x=>Date.now()-x.at<=5000);const m=recent.filter(x=>x.action==='mount').length,u=recent.filter(x=>x.action==='unmount').length;if(m>=4&&u>=4)out.push(f('warning','Lifecycle',`${name} is rapidly remounting`,`${m} mounts + ${u} unmounts within 5s`,'mount/unmount churn','Check keys, conditional trees, route boundaries and parent state that recreates this subtree.'))}
 if(s.domNodes>=5000)out.push(f(s.domNodes>=10000?'critical':'warning','DOM','Large DOM detected',`${s.domNodes.toLocaleString()} DOM nodes are currently present`,'DOM size','Virtualize large collections and avoid rendering hidden/unused subtrees.'));
 return out.sort((a,b)=>rank(b.severity)-rank(a.severity))}
}
const f=(severity:DiagnosticFinding['severity'],category:string,title:string,detail:string,evidence:string,recommendation:string):DiagnosticFinding=>({severity,category,title,detail,evidence,recommendation});const rank=(x:DiagnosticFinding['severity'])=>x==='critical'?3:x==='warning'?2:1;
function env(startedAt:number){const n:any=typeof navigator==='undefined'?{}:navigator;const c:any=n.connection;return{url:typeof location==='undefined'?'':location.href,userAgent:n.userAgent||'',viewport:typeof innerWidth==='undefined'?'':`${innerWidth}x${innerHeight} @${devicePixelRatio||1}x`,cpuCores:n.hardwareConcurrency||'unknown',deviceMemoryGB:n.deviceMemory||'unknown',connection:c?`${c.effectiveType||''} ${c.downlink||''}Mbps ${c.rtt||''}ms`:undefined,startedAt}}
function norm(u:string){try{const x=new URL(u,location.href);x.searchParams.sort();return x.origin+x.pathname+'?'+x.searchParams.toString()}catch{return u}}function short(u:string){try{const x=new URL(u,location.href);return(x.pathname+x.search).slice(0,100)}catch{return u.slice(0,100)}}
export const runtimeObservabilityStore=new Store();
