-- TRUSTWEAVE D12 CANONICAL CURRENT-STATE BASELINE.
-- Materialized after fresh-project structural/security/API/behavior/product parity on 2026-09-20.
-- DO NOT apply these files to the historical golden project as an upgrade sequence.
-- Historical supabase/migrations/001..123 remain immutable upgrade history.

ALTER TABLE "public"."community_event_responses" ADD CONSTRAINT "community_event_responses_event_id_fkey" FOREIGN KEY (event_id) REFERENCES community_events(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_event_responses" ADD CONSTRAINT "community_event_responses_guest_count_check" CHECK (guest_count >= 0 AND guest_count <= 20);
ALTER TABLE "public"."community_event_responses" ADD CONSTRAINT "community_event_responses_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_event_responses" ADD CONSTRAINT "community_event_responses_response_check" CHECK (response::text = ANY (ARRAY['going'::character varying, 'interested'::character varying, 'not_going'::character varying]::text[]));
ALTER TABLE "public"."community_event_responses" ADD CONSTRAINT "community_event_responses_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_events" ADD CONSTRAINT "community_events_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."community_events" ADD CONSTRAINT "community_events_group_id_fkey" FOREIGN KEY (group_id) REFERENCES community_groups(id) ON DELETE SET NULL;
ALTER TABLE "public"."community_events" ADD CONSTRAINT "community_events_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_events" ADD CONSTRAINT "community_events_status_check" CHECK (status::text = ANY (ARRAY['planning'::character varying, 'open'::character varying, 'closed'::character varying, 'cancelled'::character varying]::text[]));
ALTER TABLE "public"."community_family_links" ADD CONSTRAINT "community_family_links_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_family_links" ADD CONSTRAINT "community_family_links_requested_by_fkey" FOREIGN KEY (requested_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."community_family_links" ADD CONSTRAINT "community_family_links_reviewed_by_fkey" FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."community_family_links" ADD CONSTRAINT "community_family_links_space_id_fkey" FOREIGN KEY (space_id) REFERENCES community_spaces(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_family_links" ADD CONSTRAINT "community_family_links_status_check" CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[]));
ALTER TABLE "public"."community_group_members" ADD CONSTRAINT "community_group_members_group_id_fkey" FOREIGN KEY (group_id) REFERENCES community_groups(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_group_members" ADD CONSTRAINT "community_group_members_member_id_fkey" FOREIGN KEY (member_id) REFERENCES family_members(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_group_members" ADD CONSTRAINT "community_group_members_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_groups" ADD CONSTRAINT "community_groups_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."community_groups" ADD CONSTRAINT "community_groups_group_type_check" CHECK (group_type::text = ANY (ARRAY['branch'::character varying, 'household'::character varying, 'circle'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."community_groups" ADD CONSTRAINT "community_groups_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_introduction_requests" ADD CONSTRAINT "community_introduction_requests_requester_network_id_fkey" FOREIGN KEY (requester_network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_introduction_requests" ADD CONSTRAINT "community_introduction_requests_requester_user_id_fkey" FOREIGN KEY (requester_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_introduction_requests" ADD CONSTRAINT "community_introduction_requests_responded_by_fkey" FOREIGN KEY (responded_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."community_introduction_requests" ADD CONSTRAINT "community_introduction_requests_space_id_fkey" FOREIGN KEY (space_id) REFERENCES community_spaces(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_introduction_requests" ADD CONSTRAINT "community_introduction_requests_status_check" CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'declined'::character varying, 'cancelled'::character varying, 'connected'::character varying]::text[]));
ALTER TABLE "public"."community_introduction_requests" ADD CONSTRAINT "community_introduction_requests_target_card_id_fkey" FOREIGN KEY (target_card_id) REFERENCES community_profile_cards(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_introduction_requests" ADD CONSTRAINT "community_introduction_requests_target_network_id_fkey" FOREIGN KEY (target_network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_introduction_requests" ADD CONSTRAINT "community_introduction_requests_target_user_id_fkey" FOREIGN KEY (target_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_posts" ADD CONSTRAINT "community_posts_author_user_id_fkey" FOREIGN KEY (author_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_posts" ADD CONSTRAINT "community_posts_category_check" CHECK (category::text = ANY (ARRAY['marriage'::character varying, 'professional'::character varying, 'service'::character varying, 'event'::character varying, 'opportunity'::character varying, 'announcement'::character varying, 'help'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."community_posts" ADD CONSTRAINT "community_posts_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_posts" ADD CONSTRAINT "community_posts_space_id_fkey" FOREIGN KEY (space_id) REFERENCES community_spaces(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_posts" ADD CONSTRAINT "community_posts_status_check" CHECK (status::text = ANY (ARRAY['open'::character varying, 'closed'::character varying, 'expired'::character varying]::text[]));
ALTER TABLE "public"."community_posts" ADD CONSTRAINT "community_posts_target_member_id_fkey" FOREIGN KEY (target_member_id) REFERENCES family_members(id) ON DELETE SET NULL;
ALTER TABLE "public"."community_profile_cards" ADD CONSTRAINT "community_profile_cards_category_check" CHECK (category::text = ANY (ARRAY['marriage'::character varying, 'professional'::character varying, 'service'::character varying, 'mentor'::character varying, 'speaker'::character varying, 'education'::character varying, 'social_service'::character varying, 'business'::character varying, 'arts'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."community_profile_cards" ADD CONSTRAINT "community_profile_cards_contact_mode_check" CHECK (contact_mode::text = ANY (ARRAY['family_intro'::character varying, 'direct_request'::character varying]::text[]));
ALTER TABLE "public"."community_profile_cards" ADD CONSTRAINT "community_profile_cards_member_id_fkey" FOREIGN KEY (member_id) REFERENCES family_members(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_profile_cards" ADD CONSTRAINT "community_profile_cards_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_profile_cards" ADD CONSTRAINT "community_profile_cards_owner_user_id_fkey" FOREIGN KEY (owner_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_profile_cards" ADD CONSTRAINT "community_profile_cards_space_id_fkey" FOREIGN KEY (space_id) REFERENCES community_spaces(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_spaces" ADD CONSTRAINT "community_spaces_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."community_spaces" ADD CONSTRAINT "community_spaces_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES community_spaces(id) ON DELETE SET NULL;
ALTER TABLE "public"."community_spaces" ADD CONSTRAINT "community_spaces_space_type_check" CHECK (space_type::text = ANY (ARRAY['community'::character varying, 'city'::character varying, 'chapter'::character varying, 'association'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."community_spaces" ADD CONSTRAINT "community_spaces_status_check" CHECK (status::text = ANY (ARRAY['active'::character varying, 'archived'::character varying]::text[]));
ALTER TABLE "public"."community_trust_edges" ADD CONSTRAINT "community_trust_edges_check" CHECK (requester_network_id <> recipient_network_id);
ALTER TABLE "public"."community_trust_edges" ADD CONSTRAINT "community_trust_edges_recipient_network_id_fkey" FOREIGN KEY (recipient_network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_trust_edges" ADD CONSTRAINT "community_trust_edges_requested_by_fkey" FOREIGN KEY (requested_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_trust_edges" ADD CONSTRAINT "community_trust_edges_requester_network_id_fkey" FOREIGN KEY (requester_network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_trust_edges" ADD CONSTRAINT "community_trust_edges_reviewed_by_fkey" FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."community_trust_edges" ADD CONSTRAINT "community_trust_edges_space_id_fkey" FOREIGN KEY (space_id) REFERENCES community_spaces(id) ON DELETE CASCADE;
ALTER TABLE "public"."community_trust_edges" ADD CONSTRAINT "community_trust_edges_status_check" CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'declined'::character varying, 'revoked'::character varying]::text[]));
ALTER TABLE "public"."network_activities" ADD CONSTRAINT "network_activities_activity_type_check" CHECK (activity_type::text = ANY (ARRAY['event'::character varying, 'memory'::character varying, 'milestone'::character varying, 'announcement'::character varying]::text[]));
ALTER TABLE "public"."network_activities" ADD CONSTRAINT "network_activities_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_activities" ADD CONSTRAINT "network_activities_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_activities" ADD CONSTRAINT "network_activities_visibility_check" CHECK (visibility::text = ANY (ARRAY['members'::character varying, 'private'::character varying]::text[]));
ALTER TABLE "public"."network_activity_comments" ADD CONSTRAINT "network_activity_comments_activity_id_network_id_fkey" FOREIGN KEY (activity_id, network_id) REFERENCES network_activities(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."network_activity_comments" ADD CONSTRAINT "network_activity_comments_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_activity_comments" ADD CONSTRAINT "network_activity_comments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_activity_reactions" ADD CONSTRAINT "network_activity_reactions_activity_id_network_id_fkey" FOREIGN KEY (activity_id, network_id) REFERENCES network_activities(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."network_activity_reactions" ADD CONSTRAINT "network_activity_reactions_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_activity_reactions" ADD CONSTRAINT "network_activity_reactions_reaction_check" CHECK (reaction::text = 'like'::text);
ALTER TABLE "public"."network_activity_reactions" ADD CONSTRAINT "network_activity_reactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_activity_rsvps" ADD CONSTRAINT "fk_network_activity_rsvp_tenant" FOREIGN KEY (activity_id, network_id) REFERENCES network_activities(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."network_activity_rsvps" ADD CONSTRAINT "network_activity_rsvps_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_activity_rsvps" ADD CONSTRAINT "network_activity_rsvps_response_check" CHECK (response::text = ANY (ARRAY['going'::character varying, 'maybe'::character varying, 'declined'::character varying]::text[]));
ALTER TABLE "public"."network_activity_rsvps" ADD CONSTRAINT "network_activity_rsvps_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_media_assets" ADD CONSTRAINT "network_media_assets_archived_by_fkey" FOREIGN KEY (archived_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_media_assets" ADD CONSTRAINT "network_media_assets_bucket_check" CHECK (bucket::text = ANY (ARRAY['profile-photos'::character varying, 'community-media'::character varying]::text[]));
ALTER TABLE "public"."network_media_assets" ADD CONSTRAINT "network_media_assets_bytes_check" CHECK (bytes >= 0);
ALTER TABLE "public"."network_media_assets" ADD CONSTRAINT "network_media_assets_delete_requested_by_fkey" FOREIGN KEY (delete_requested_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_media_assets" ADD CONSTRAINT "network_media_assets_deleted_by_fkey" FOREIGN KEY (deleted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_media_assets" ADD CONSTRAINT "network_media_assets_media_kind_check" CHECK (media_kind::text = ANY (ARRAY['profile'::character varying, 'memory'::character varying, 'event'::character varying, 'announcement'::character varying, 'complaint'::character varying, 'post'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."network_media_assets" ADD CONSTRAINT "network_media_assets_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_media_assets" ADD CONSTRAINT "network_media_assets_owner_user_id_fkey" FOREIGN KEY (owner_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_media_assets" ADD CONSTRAINT "network_media_assets_thumbnail_bytes_check" CHECK (thumbnail_bytes >= 0);
ALTER TABLE "public"."network_media_assets" ADD CONSTRAINT "network_media_lifecycle_check" CHECK (lifecycle_state::text = ANY (ARRAY['active'::character varying, 'archived'::character varying, 'delete_pending'::character varying, 'deleted'::character varying]::text[]));
ALTER TABLE "public"."participation_events" ADD CONSTRAINT "participation_events_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."participation_events" ADD CONSTRAINT "participation_events_public_member_id_fkey" FOREIGN KEY (public_member_id) REFERENCES family_members(id) ON DELETE SET NULL;
