-- TRUSTWEAVE D12 CANONICAL CURRENT-STATE BASELINE.
-- Materialized after fresh-project structural/security/API/behavior/product parity on 2026-09-20.
-- DO NOT apply these files to the historical golden project as an upgrade sequence.
-- Historical supabase/migrations/001..123 remain immutable upgrade history.

ALTER TABLE "public"."family_creation_requests" ADD CONSTRAINT "family_creation_requests_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_creation_requests" ADD CONSTRAINT "family_creation_requests_requester_user_id_fkey" FOREIGN KEY (requester_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_creation_requests" ADD CONSTRAINT "family_creation_requests_reviewed_by_fkey" FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_creation_requests" ADD CONSTRAINT "family_creation_requests_status_check" CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[]));
ALTER TABLE "public"."family_digest_state" ADD CONSTRAINT "family_digest_state_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_digest_state" ADD CONSTRAINT "family_digest_state_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_engagement_events" ADD CONSTRAINT "family_engagement_events_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_engagement_events" ADD CONSTRAINT "family_engagement_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_intake_access" ADD CONSTRAINT "family_intake_access_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_intake_access" ADD CONSTRAINT "family_intake_access_max_submissions_check" CHECK (max_submissions >= 1 AND max_submissions <= 10);
ALTER TABLE "public"."family_intake_access" ADD CONSTRAINT "family_intake_access_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_access" ADD CONSTRAINT "family_intake_access_session_id_fkey" FOREIGN KEY (session_id) REFERENCES family_intake_sessions(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_access" ADD CONSTRAINT "family_intake_access_status_check" CHECK (status::text = ANY (ARRAY['active'::character varying, 'submitted'::character varying, 'committed'::character varying, 'revoked'::character varying, 'expired'::character varying]::text[]));
ALTER TABLE "public"."family_intake_conflicts" ADD CONSTRAINT "family_intake_conflicts_member_id_fkey" FOREIGN KEY (member_id) REFERENCES family_members(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_conflicts" ADD CONSTRAINT "family_intake_conflicts_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_conflicts" ADD CONSTRAINT "family_intake_conflicts_resolved_by_fkey" FOREIGN KEY (resolved_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_intake_conflicts" ADD CONSTRAINT "family_intake_conflicts_session_id_fkey" FOREIGN KEY (session_id) REFERENCES family_intake_sessions(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_conflicts" ADD CONSTRAINT "family_intake_conflicts_staged_person_id_fkey" FOREIGN KEY (staged_person_id) REFERENCES family_intake_people(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_conflicts" ADD CONSTRAINT "family_intake_conflicts_status_check" CHECK (status::text = ANY (ARRAY['open'::character varying, 'kept_existing'::character varying, 'accepted_reported'::character varying, 'unresolved'::character varying]::text[]));
ALTER TABLE "public"."family_intake_decisions" ADD CONSTRAINT "family_intake_decisions_candidate_id_fkey" FOREIGN KEY (candidate_id) REFERENCES family_intake_match_candidates(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_intake_decisions" ADD CONSTRAINT "family_intake_decisions_decided_by_fkey" FOREIGN KEY (decided_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_intake_decisions" ADD CONSTRAINT "family_intake_decisions_decision_check" CHECK (decision::text = ANY (ARRAY['same'::character varying, 'different'::character varying, 'not_sure'::character varying, 'create_new'::character varying]::text[]));
ALTER TABLE "public"."family_intake_decisions" ADD CONSTRAINT "family_intake_decisions_decision_source_check" CHECK (decision_source::text = ANY (ARRAY['automatic_high_confidence'::character varying, 'contributor'::character varying, 'owner'::character varying]::text[]));
ALTER TABLE "public"."family_intake_decisions" ADD CONSTRAINT "family_intake_decisions_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_decisions" ADD CONSTRAINT "family_intake_decisions_session_id_fkey" FOREIGN KEY (session_id) REFERENCES family_intake_sessions(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_decisions" ADD CONSTRAINT "family_intake_decisions_staged_person_id_fkey" FOREIGN KEY (staged_person_id) REFERENCES family_intake_people(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_events" ADD CONSTRAINT "family_intake_events_access_id_fkey" FOREIGN KEY (access_id) REFERENCES family_intake_access(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_events" ADD CONSTRAINT "family_intake_events_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_intake_events" ADD CONSTRAINT "family_intake_events_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_events" ADD CONSTRAINT "family_intake_events_session_id_fkey" FOREIGN KEY (session_id) REFERENCES family_intake_sessions(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_match_candidates" ADD CONSTRAINT "family_intake_match_candidates_candidate_member_id_fkey" FOREIGN KEY (candidate_member_id) REFERENCES family_members(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_match_candidates" ADD CONSTRAINT "family_intake_match_candidates_candidate_staged_person_id_fkey" FOREIGN KEY (candidate_staged_person_id) REFERENCES family_intake_people(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_match_candidates" ADD CONSTRAINT "family_intake_match_candidates_check" CHECK (((candidate_member_id IS NOT NULL)::integer + (candidate_staged_person_id IS NOT NULL)::integer) = 1);
ALTER TABLE "public"."family_intake_match_candidates" ADD CONSTRAINT "family_intake_match_candidates_confidence_band_check" CHECK (confidence_band::text = ANY (ARRAY['high'::character varying, 'medium'::character varying, 'low'::character varying]::text[]));
ALTER TABLE "public"."family_intake_match_candidates" ADD CONSTRAINT "family_intake_match_candidates_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_match_candidates" ADD CONSTRAINT "family_intake_match_candidates_score_check" CHECK (score >= 0 AND score <= 100);
ALTER TABLE "public"."family_intake_match_candidates" ADD CONSTRAINT "family_intake_match_candidates_session_id_fkey" FOREIGN KEY (session_id) REFERENCES family_intake_sessions(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_match_candidates" ADD CONSTRAINT "family_intake_match_candidates_staged_person_id_fkey" FOREIGN KEY (staged_person_id) REFERENCES family_intake_people(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_match_candidates" ADD CONSTRAINT "family_intake_match_candidates_status_check" CHECK (status::text = ANY (ARRAY['open'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'unsure'::character varying]::text[]));
ALTER TABLE "public"."family_intake_people" ADD CONSTRAINT "family_intake_people_access_id_fkey" FOREIGN KEY (access_id) REFERENCES family_intake_access(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_people" ADD CONSTRAINT "family_intake_people_birth_year_check" CHECK (birth_year IS NULL OR birth_year >= 1800 AND birth_year <= 2200);
ALTER TABLE "public"."family_intake_people" ADD CONSTRAINT "family_intake_people_gender_check" CHECK (gender IS NULL OR (gender::text = ANY (ARRAY['Male'::character varying, 'Female'::character varying, 'Other'::character varying]::text[])));
ALTER TABLE "public"."family_intake_people" ADD CONSTRAINT "family_intake_people_generation_offset_check" CHECK (generation_offset >= '-5'::integer AND generation_offset <= 5);
ALTER TABLE "public"."family_intake_people" ADD CONSTRAINT "family_intake_people_match_confidence_check" CHECK (match_confidence IS NULL OR match_confidence >= 0 AND match_confidence <= 100);
ALTER TABLE "public"."family_intake_people" ADD CONSTRAINT "family_intake_people_matched_member_id_fkey" FOREIGN KEY (matched_member_id) REFERENCES family_members(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_intake_people" ADD CONSTRAINT "family_intake_people_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_people" ADD CONSTRAINT "family_intake_people_session_id_fkey" FOREIGN KEY (session_id) REFERENCES family_intake_sessions(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_people" ADD CONSTRAINT "family_intake_people_status_check" CHECK (status::text = ANY (ARRAY['staged'::character varying, 'matched'::character varying, 'new'::character varying, 'ambiguous'::character varying, 'committed'::character varying, 'rejected'::character varying]::text[]));
ALTER TABLE "public"."family_intake_relationships" ADD CONSTRAINT "family_intake_relationships_access_id_fkey" FOREIGN KEY (access_id) REFERENCES family_intake_access(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_relationships" ADD CONSTRAINT "family_intake_relationships_canonical_relationship_id_fkey" FOREIGN KEY (canonical_relationship_id) REFERENCES family_relationships(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_intake_relationships" ADD CONSTRAINT "family_intake_relationships_check" CHECK (from_staged_person_id <> to_staged_person_id);
ALTER TABLE "public"."family_intake_relationships" ADD CONSTRAINT "family_intake_relationships_from_staged_person_id_fkey" FOREIGN KEY (from_staged_person_id) REFERENCES family_intake_people(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_relationships" ADD CONSTRAINT "family_intake_relationships_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_relationships" ADD CONSTRAINT "family_intake_relationships_relationship_type_check" CHECK (relationship_type::text = ANY (ARRAY['parent'::character varying, 'child'::character varying, 'spouse'::character varying]::text[]));
ALTER TABLE "public"."family_intake_relationships" ADD CONSTRAINT "family_intake_relationships_session_id_fkey" FOREIGN KEY (session_id) REFERENCES family_intake_sessions(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_relationships" ADD CONSTRAINT "family_intake_relationships_status_check" CHECK (status::text = ANY (ARRAY['staged'::character varying, 'committed'::character varying, 'rejected'::character varying]::text[]));
ALTER TABLE "public"."family_intake_relationships" ADD CONSTRAINT "family_intake_relationships_to_staged_person_id_fkey" FOREIGN KEY (to_staged_person_id) REFERENCES family_intake_people(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_sessions" ADD CONSTRAINT "family_intake_sessions_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_intake_sessions" ADD CONSTRAINT "family_intake_sessions_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_intake_sessions" ADD CONSTRAINT "family_intake_sessions_status_check" CHECK (status::text = ANY (ARRAY['draft'::character varying, 'collecting'::character varying, 'review'::character varying, 'completed'::character varying, 'closed'::character varying]::text[]));
ALTER TABLE "public"."family_join_codes" ADD CONSTRAINT "family_join_codes_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_join_codes" ADD CONSTRAINT "family_join_codes_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_relationships" ADD CONSTRAINT "family_relationships_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_relationships" ADD CONSTRAINT "family_relationships_no_self" CHECK (person_id <> related_person_id);
ALTER TABLE "public"."family_relationships" ADD CONSTRAINT "family_relationships_person_id_fkey" FOREIGN KEY (person_id) REFERENCES family_members(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_relationships" ADD CONSTRAINT "family_relationships_related_person_id_fkey" FOREIGN KEY (related_person_id) REFERENCES family_members(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_relationships" ADD CONSTRAINT "family_relationships_relationship_type_check" CHECK (relationship_type::text = ANY (ARRAY['parent'::character varying, 'child'::character varying, 'spouse'::character varying]::text[]));
ALTER TABLE "public"."member_life_events" ADD CONSTRAINT "member_life_events_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."member_life_events" ADD CONSTRAINT "member_life_events_event_type_check" CHECK (event_type::text = ANY (ARRAY['birth'::character varying, 'marriage'::character varying, 'move'::character varying, 'education'::character varying, 'career'::character varying, 'family'::character varying, 'milestone'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."member_life_events" ADD CONSTRAINT "member_life_events_member_id_fkey" FOREIGN KEY (member_id) REFERENCES family_members(id) ON DELETE CASCADE;
ALTER TABLE "public"."member_life_events" ADD CONSTRAINT "member_life_events_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."member_life_events" ADD CONSTRAINT "member_life_events_visibility_check" CHECK (visibility::text = ANY (ARRAY['public'::character varying, 'member'::character varying, 'admin'::character varying]::text[]));
ALTER TABLE "public"."memories" ADD CONSTRAINT "memories_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."memories" ADD CONSTRAINT "memories_event_id_fkey" FOREIGN KEY (event_id) REFERENCES community_events(id) ON DELETE SET NULL;
ALTER TABLE "public"."memories" ADD CONSTRAINT "memories_member_id_fkey" FOREIGN KEY (member_id) REFERENCES family_members(id) ON DELETE CASCADE;
ALTER TABLE "public"."memories" ADD CONSTRAINT "memories_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."memories" ADD CONSTRAINT "memories_visibility_check" CHECK (visibility::text = ANY (ARRAY['public'::character varying, 'member'::character varying, 'admin'::character varying]::text[]));
ALTER TABLE "public"."memory_people" ADD CONSTRAINT "memory_people_member_id_fkey" FOREIGN KEY (member_id) REFERENCES family_members(id) ON DELETE CASCADE;
ALTER TABLE "public"."memory_people" ADD CONSTRAINT "memory_people_memory_id_fkey" FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE CASCADE;
ALTER TABLE "public"."memory_people" ADD CONSTRAINT "memory_people_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."memory_reactions" ADD CONSTRAINT "memory_reactions_memory_id_fkey" FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE CASCADE;
ALTER TABLE "public"."memory_reactions" ADD CONSTRAINT "memory_reactions_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."memory_reactions" ADD CONSTRAINT "memory_reactions_reaction_check" CHECK (reaction::text = ANY (ARRAY['heart'::character varying, 'smile'::character varying, 'pray'::character varying, 'celebrate'::character varying]::text[]));
ALTER TABLE "public"."memory_reactions" ADD CONSTRAINT "memory_reactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."profile_submissions" ADD CONSTRAINT "profile_submissions_contact_visibility_check" CHECK (contact_visibility::text = ANY (ARRAY['member'::character varying, 'admin'::character varying]::text[]));
ALTER TABLE "public"."profile_submissions" ADD CONSTRAINT "profile_submissions_member_id_fkey" FOREIGN KEY (member_id) REFERENCES family_members(id) ON DELETE SET NULL;
ALTER TABLE "public"."profile_submissions" ADD CONSTRAINT "profile_submissions_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."profile_submissions" ADD CONSTRAINT "profile_submissions_profile_visibility_check" CHECK (profile_visibility::text = ANY (ARRAY['public'::character varying, 'member'::character varying, 'admin'::character varying]::text[]));
ALTER TABLE "public"."profile_submissions" ADD CONSTRAINT "profile_submissions_status_check" CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[]));
ALTER TABLE "public"."profile_submissions" ADD CONSTRAINT "profile_submissions_submitted_by_fkey" FOREIGN KEY (submitted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
