-- TRUSTWEAVE D12 CANONICAL CURRENT-STATE BASELINE.
-- Materialized after fresh-project structural/security/API/behavior/product parity on 2026-09-20.
-- DO NOT apply these files to the historical golden project as an upgrade sequence.
-- Historical supabase/migrations/001..123 remain immutable upgrade history.

ALTER TABLE "public"."association_household_admins" ADD CONSTRAINT "association_household_admin_entity_fk" FOREIGN KEY (household_entity_id, network_id) REFERENCES network_entities(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."association_household_admins" ADD CONSTRAINT "association_household_admins_granted_by_fkey" FOREIGN KEY (granted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."association_household_admins" ADD CONSTRAINT "association_household_admins_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."association_household_admins" ADD CONSTRAINT "association_household_admins_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_association_awards" ADD CONSTRAINT "family_association_awards_membership_year_id_fkey" FOREIGN KEY (membership_year_id) REFERENCES family_association_membership_years(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_association_awards" ADD CONSTRAINT "family_association_awards_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_association_awards" ADD CONSTRAINT "family_association_awards_person_entity_id_network_id_fkey" FOREIGN KEY (person_entity_id, network_id) REFERENCES network_entities(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."family_association_family_memberships" ADD CONSTRAINT "family_association_family_mem_representative_entity_id_net_fkey" FOREIGN KEY (representative_entity_id, network_id) REFERENCES network_entities(id, network_id) ON DELETE SET NULL;
ALTER TABLE "public"."family_association_family_memberships" ADD CONSTRAINT "family_association_family_memb_family_entity_id_network_id_fkey" FOREIGN KEY (family_entity_id, network_id) REFERENCES network_entities(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."family_association_family_memberships" ADD CONSTRAINT "family_association_family_membershi_transfer_to_network_id_fkey" FOREIGN KEY (transfer_to_network_id) REFERENCES networks(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_association_family_memberships" ADD CONSTRAINT "family_association_family_memberships_membership_year_id_fkey" FOREIGN KEY (membership_year_id) REFERENCES family_association_membership_years(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_association_family_memberships" ADD CONSTRAINT "family_association_family_memberships_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_association_family_memberships" ADD CONSTRAINT "family_association_family_memberships_payment_status_check" CHECK (payment_status::text = ANY (ARRAY['unpaid'::character varying, 'paid'::character varying, 'waived'::character varying, 'partial'::character varying, 'not_required'::character varying]::text[]));
ALTER TABLE "public"."family_association_family_memberships" ADD CONSTRAINT "family_association_family_memberships_status_check" CHECK (status::text = ANY (ARRAY['pending'::character varying, 'active'::character varying, 'grace'::character varying, 'inactive'::character varying, 'removed'::character varying, 'transferred'::character varying]::text[]));
ALTER TABLE "public"."family_association_finance_ledger" ADD CONSTRAINT "family_association_finance_ledger_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_association_finance_ledger" ADD CONSTRAINT "family_association_finance_ledger_entry_type_check" CHECK (entry_type::text = ANY (ARRAY['opening_balance'::character varying, 'membership_collection'::character varying, 'donation'::character varying, 'event_contribution'::character varying, 'sponsorship'::character varying, 'event_allocation'::character varying, 'good_cause'::character varying, 'expense'::character varying, 'carry_forward'::character varying, 'adjustment'::character varying]::text[]));
ALTER TABLE "public"."family_association_finance_ledger" ADD CONSTRAINT "family_association_finance_ledger_membership_year_id_fkey" FOREIGN KEY (membership_year_id) REFERENCES family_association_membership_years(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_association_finance_ledger" ADD CONSTRAINT "family_association_finance_ledger_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_association_finance_ledger" ADD CONSTRAINT "family_association_finance_ledger_visibility_check" CHECK (visibility::text = ANY (ARRAY['admins'::character varying, 'members'::character varying, 'highlighted'::character varying]::text[]));
ALTER TABLE "public"."family_association_membership_years" ADD CONSTRAINT "family_association_membership_years_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_association_membership_years" ADD CONSTRAINT "family_association_membership_years_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_association_membership_years" ADD CONSTRAINT "family_association_membership_years_status_check" CHECK (status::text = ANY (ARRAY['planned'::character varying, 'open'::character varying, 'closed'::character varying, 'archived'::character varying]::text[]));
ALTER TABLE "public"."family_association_role_catalog" ADD CONSTRAINT "family_association_role_catalog_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_association_role_catalog" ADD CONSTRAINT "family_association_role_catalog_role_type_check" CHECK (role_type::text = ANY (ARRAY['office_bearer'::character varying, 'director'::character varying, 'chairperson'::character varying, 'committee'::character varying, 'volunteer'::character varying, 'mentor'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."family_association_role_history" ADD CONSTRAINT "family_association_role_histor_person_entity_id_network_id_fkey" FOREIGN KEY (person_entity_id, network_id) REFERENCES network_entities(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."family_association_role_history" ADD CONSTRAINT "family_association_role_history_membership_year_id_fkey" FOREIGN KEY (membership_year_id) REFERENCES family_association_membership_years(id) ON DELETE SET NULL;
ALTER TABLE "public"."family_association_role_history" ADD CONSTRAINT "family_association_role_history_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_association_role_history" ADD CONSTRAINT "family_association_role_history_role_catalog_id_fkey" FOREIGN KEY (role_catalog_id) REFERENCES family_association_role_catalog(id) ON DELETE RESTRICT;
ALTER TABLE "public"."family_association_settings" ADD CONSTRAINT "family_association_settings_default_contact_visibility_check" CHECK (default_contact_visibility::text = ANY (ARRAY['members'::character varying, 'private'::character varying]::text[]));
ALTER TABLE "public"."family_association_settings" ADD CONSTRAINT "family_association_settings_default_profile_visibility_check" CHECK (default_profile_visibility::text = ANY (ARRAY['members'::character varying, 'private'::character varying]::text[]));
ALTER TABLE "public"."family_association_settings" ADD CONSTRAINT "family_association_settings_dependent_age_limit_check" CHECK (dependent_age_limit >= 16 AND dependent_age_limit <= 40);
ALTER TABLE "public"."family_association_settings" ADD CONSTRAINT "family_association_settings_finance_visibility_check" CHECK (finance_visibility::text = ANY (ARRAY['admins'::character varying, 'members'::character varying, 'highlighted'::character varying]::text[]));
ALTER TABLE "public"."family_association_settings" ADD CONSTRAINT "family_association_settings_grace_period_days_check" CHECK (grace_period_days >= 0 AND grace_period_days <= 90);
ALTER TABLE "public"."family_association_settings" ADD CONSTRAINT "family_association_settings_max_auto_children_check" CHECK (max_auto_children >= 0 AND max_auto_children <= 10);
ALTER TABLE "public"."family_association_settings" ADD CONSTRAINT "family_association_settings_membership_cycle_start_month_check" CHECK (membership_cycle_start_month >= 1 AND membership_cycle_start_month <= 12);
ALTER TABLE "public"."family_association_settings" ADD CONSTRAINT "family_association_settings_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."family_association_settings" ADD CONSTRAINT "family_association_settings_onboarding_policy_check" CHECK (onboarding_policy::text = ANY (ARRAY['join_review_later'::character varying, 'approval_required'::character varying, 'invitation_only'::character varying]::text[]));
ALTER TABLE "public"."family_association_settings" ADD CONSTRAINT "family_association_settings_voting_eligibility_check" CHECK (voting_eligibility::text = ANY (ARRAY['one_per_family'::character varying, 'representative_spouse'::character varying, 'all_adult_members'::character varying, 'custom'::character varying]::text[]));
