import {normalizeConfig} from './config';
import {runFindingRules} from './plugins';
import type {ConsoleSample,DomSample,Finding,HistorySnapshot,InspectionSnapshot,InteractionSample,LoafSample,LongTaskSample,MemorySample,NetworkSample,ReactCommitSample,ResourceSample,RuntimeConfig,RuntimeErrorSample,RuntimeSnapshot,TimerSnapshot,VitalSnapshot} from './types';
const mb=(bytes:number)=>Math.round(bytes/1024/1024*10)/10;
export class RuntimeStore{
  config=normalizeConfig(); private startedAt=Date.now(); private listeners=new Set<()=>void>(); private history:HistorySnapshot[]=[];
  interactions:InteractionSample[]=[];commits:ReactCommitSample[]=[];network:NetworkSample[]=[];resources:ResourceSample[]=[];loafs:LoafSample[]=[];longTasks:LongTaskSample[]=[];errors:RuntimeErrorSample[]=[];console:ConsoleSample[]=[];dom:DomSample[]=[];memory:MemorySample[]=[];timers:TimerSnapshot[]=[];inspection:InspectionSnapshot|null=null;rendererVersions:string[]=[];vitals:VitalSnapshot={cls:0};
  configure(c:RuntimeConfig){this.config=normalizeConfig(c);this.emit()} subscribe=(fn:()=>void)=>{this.listeners.add(fn);return()=>this.listeners.delete(fn)}; private emit(){for(const fn of this.listeners)fn()}; private add<T>(arr:T[],v:T){arr.push(v);if(arr.length>this.config.maxEntries)arr.splice(0,arr.length-this.config.maxEntries);this.emit()}
  recordInteraction(v:InteractionSample){this.add(this.interactions,v)} recordCommit(v:ReactCommitSample){this.add(this.commits,v)} recordNetwork(v:NetworkSample){this.add(this.network,v)} recordResource(v:ResourceSample){this.add(this.resources,v)} recordLoaf(v:LoafSample){this.add(this.loafs,v)} recordLongTask(v:LongTaskSample){this.add(this.longTasks,v)} recordError(v:RuntimeErrorSample){this.add(this.errors,v)} recordConsole(v:ConsoleSample){this.add(this.console,v)} recordDom(v:DomSample){this.add(this.dom,v)} recordMemory(v:MemorySample){this.add(this.memory,v)} recordTimers(v:TimerSnapshot){this.add(this.timers,v)} setInspection(v:InspectionSnapshot|null){this.inspection=v;this.emit()} setVital<K extends keyof VitalSnapshot>(k:K,v:VitalSnapshot[K]){this.vitals={...this.vitals,[k]:v};this.emit()} addCls(v:number,target?:string){this.vitals={...this.vitals,cls:this.vitals.cls+v,clsTarget:target||this.vitals.clsTarget};this.emit()} addRendererVersion(v:string){if(v&&!this.rendererVersions.includes(v)){this.rendererVersions=[...this.rendererVersions,v];this.emit()}}
  recentInteraction(at=Date.now(),windowMs=1200){for(let i=this.interactions.length-1;i>=0;i--){const x=this.interactions[i];if(at-x.at<=windowMs)return x;if(at-x.at>windowMs)break}return undefined}
  reset(){this.startedAt=Date.now();this.interactions=[];this.commits=[];this.network=[];this.resources=[];this.loafs=[];this.longTasks=[];this.errors=[];this.console=[];this.dom=[];this.memory=[];this.timers=[];this.inspection=null;this.vitals={cls:0};this.emit()}
  snapshot():RuntimeSnapshot{return{startedAt:this.startedAt,route:typeof location==='undefined'?'':location.pathname+location.search,vitals:{...this.vitals},interactions:[...this.interactions],commits:[...this.commits],network:[...this.network],resources:[...this.resources],loafs:[...this.loafs],longTasks:[...this.longTasks],errors:[...this.errors],console:[...this.console],dom:[...this.dom],memory:[...this.memory],timers:[...this.timers],inspection:this.inspection,rendererVersions:[...this.rendererVersions],environment:environment()}}
  saveHistory(label='Snapshot'){const snapshot=this.snapshot();const item={id:String(Date.now()),label,at:Date.now(),snapshot,findings:this.findings(snapshot)};this.history=[...this.history,item].slice(-20);this.emit();return item} getHistory(){return[...this.history]} clearHistory(){this.history=[];this.emit()}
  findings(s=this.snapshot()):Finding[]{const c=this.config,out:Finding[]=[];const push=(severity:Finding['severity'],category:string,title:string,detail:string,evidence:string,recommendation:string)=>out.push({severity,category,title,detail,evidence,recommendation});
    const slow=s.network.filter(x=>x.durationMs>=c.slowNetworkMs);if(slow.length){const w=slow.reduce((a,b)=>a.durationMs>b.durationMs?a:b);push(w.durationMs>=c.slowNetworkMs*3?'critical':'warning','Network','Slow requests',`${slow.length} request(s) exceeded ${c.slowNetworkMs}ms`,`${w.method} ${short(w.url)} ${w.durationMs.toFixed(0)}ms`,'Check request waterfalls, server latency, query shape, caching and whether the request is needed for this interaction.')}
    const failed=s.network.filter(x=>x.ok===false||(x.status??0)>=400);if(failed.length)push('critical','Network','Failed requests',`${failed.length} request(s) failed`,failed.slice(-3).map(x=>`${x.status??'ERR'} ${short(x.url)}`).join(' | '),'Inspect auth/RLS, payload, response body and the initiating interaction.');
    const dup=new Map<string,NetworkSample[]>();for(const x of s.network){if(!['GET','HEAD'].includes(x.method))continue;const k=x.method+' '+normalizeUrl(x.url);const a=dup.get(k)||[];a.push(x);dup.set(k,a)}for(const[k,a]of dup){if(a.length>=4&&a[a.length-1].startAt-a[0].startAt<=10000)push('warning','Network','Duplicate request burst',`${a.length} equivalent reads fired within 10s`,k,'Look for duplicated effects, remount-triggered fetching, unstable query keys or missing request dedupe.')}
    const big=s.resources.filter(x=>(x.transferKB??x.encodedKB??0)>=c.largeResourceKB);if(big.length){const w=big.reduce((a,b)=>(a.transferKB??a.encodedKB??0)>(b.transferKB??b.encodedKB??0)?a:b);push('warning','Resources','Large transferred resources',`${big.length} resource(s) exceeded ${c.largeResourceKB}KB`,`${w.initiatorType} ${short(w.url)} ${(w.transferKB??w.encodedKB)?.toFixed(0)}KB`,'Code-split large JS, resize/compress images, subset fonts and verify caching/compression.')}
    const slowCommits=s.commits.flatMap(x=>x.components.filter(y=>(y.actualDurationMs??0)>=c.slowCommitMs).map(y=>({commit:x,component:y})));if(slowCommits.length){const w=slowCommits.reduce((a,b)=>(a.component.actualDurationMs??0)>(b.component.actualDurationMs??0)?a:b);push((w.component.actualDurationMs??0)>=c.slowCommitMs*3?'critical':'warning','React','Expensive component work',`${slowCommits.length} component sample(s) exceeded ${c.slowCommitMs}ms`,`${w.component.name} ${(w.component.actualDurationMs??0).toFixed(1)}ms · ${w.component.reason}`,'Inspect prop/state changes, list size, synchronous computations and child work. Memoize only after confirming the cause.')}
    const churn=new Map<string,number>();for(const commit of s.commits)for(const comp of commit.components)for(const p of comp.referentialChurn)churn.set(`${comp.name}.${p}`,(churn.get(`${comp.name}.${p}`)||0)+1);for(const[k,count]of churn)if(count>=5)push('warning','React','Referential prop churn',`${k} changed reference ${count} times while remaining shallow-equivalent`,k,'Stabilize object/array/function props with structure changes, memoization, or by moving creation closer to the consumer when it meaningfully reduces work.');
    for(const i of s.interactions){const commits=s.commits.filter(x=>x.interactionId===i.id&&x.at-i.at<=c.commitBurstWindowMs);if(commits.length>=c.commitBurstCount){push('warning','Causality','Commit burst after one interaction',`${commits.length} React commits followed ${i.type} on ${i.target}`,`${commits.reduce((n,x)=>n+x.changedCount,0)} changed component summaries`,'Inspect the commit sequence for cascading state updates, duplicated effects, synchronous stores or state that can be batched/derived.');break}}
    const long=s.longTasks.filter(x=>x.durationMs>=100);if(!s.loafs.length&&long.length){const w=long.reduce((a,b)=>a.durationMs>b.durationMs?a:b);push(w.durationMs>=200?'critical':'warning','Responsiveness','Long main-thread tasks',`${long.length} task(s) exceeded 100ms`,`${w.durationMs.toFixed(0)}ms ${w.attribution||''}`,'Break up long synchronous work and correlate the timestamp with actions and React commits.')}
    const loaf=s.loafs.filter(x=>x.blockingDurationMs>=100);if(loaf.length){const w=loaf.reduce((a,b)=>a.blockingDurationMs>b.blockingDurationMs?a:b);push(w.blockingDurationMs>=200?'critical':'warning','Responsiveness','Long animation frame',`${w.durationMs.toFixed(0)}ms frame with ${w.blockingDurationMs.toFixed(0)}ms blocking`,w.scripts.slice(0,3).map(x=>`${x.sourceFunctionName||'script'} ${x.durationMs?.toFixed(0)||'?'}ms`).join(' | '),'Use the script attribution to reduce blocking JavaScript and forced style/layout in the interaction path.')}
    if((s.vitals.inpMs??0)>=500)push('critical','Vitals','Poor interaction responsiveness',`Worst observed Event Timing duration is ${s.vitals.inpMs?.toFixed(0)}ms`,s.vitals.inpTarget||'','Correlate this interaction with React commit bursts, LoAFs and network activity.');if((s.vitals.lcpMs??0)>=4000)push('critical','Vitals','Poor LCP',`LCP is ${s.vitals.lcpMs?.toFixed(0)}ms`,s.vitals.lcpTarget||'','Optimize the LCP element, blocking data, image priority and critical rendering path.');if(s.vitals.cls>=.25)push('critical','Vitals','High CLS',`CLS is ${s.vitals.cls.toFixed(3)}`,s.vitals.clsTarget||'','Reserve space for images/late content and avoid layout-changing inserts above visible content.');
    if(s.errors.length){const e=s.errors[s.errors.length-1];push('critical','Errors','Runtime errors observed',`${s.errors.length} error(s) captured`,e.message,'Start from the latest stack/component stack and correlate it with the interaction and network timeline.')}
    const d=s.dom[s.dom.length-1];if(d?.nodes>=5000)push(d.nodes>=10000?'critical':'warning','DOM','Large DOM',`${d.nodes.toLocaleString()} nodes · max depth ${d.maxDepth}`,`${d.mutationRate}/s mutation rate`,'Virtualize large collections and avoid rendering hidden/unused subtrees.');if((d?.mutationRate??0)>=200)push('warning','DOM','DOM mutation burst',`${d.mutationRate} node additions/removals per second`,`+${d.added} / -${d.removed}`,'Correlate with commit bursts; avoid rebuilding large subtrees when smaller updates are possible.');if((d?.detachedSuspects??0)>20)push('warning','Memory','Detached DOM suspects',`${d.detachedSuspects} removed nodes remained reachable after the grace period`,'WeakRef/FinalizationRegistry probe','Repeat the same navigation several times and check whether this count grows monotonically before treating it as a leak.');
    const t=s.timers[s.timers.length-1];if(t&&t.activeIntervals>20)push('warning','Runtime','Many active intervals',`${t.activeIntervals} setInterval callbacks are currently active`,t.oldestIntervalMs?`oldest ${(t.oldestIntervalMs/1000).toFixed(0)}s`:'','Verify intervals are cleared on unmount/route changes and consider event-driven or shared scheduling.');
    return [...out,...runFindingRules(s,c)].sort((a,b)=>rank(b.severity)-rank(a.severity));}
  sampleHeap(){const p:any=performance,m:any=p.memory;this.recordMemory({at:Date.now(),jsHeapUsedMB:m?mb(m.usedJSHeapSize):undefined,jsHeapTotalMB:m?mb(m.totalJSHeapSize):undefined,jsHeapLimitMB:m?mb(m.jsHeapSizeLimit):undefined,detachedSuspects:this.dom[this.dom.length-1]?.detachedSuspects||0})}
  async measureMemory(){const p:any=performance;let ua:number|undefined;try{if(typeof p.measureUserAgentSpecificMemory==='function'&&typeof crossOriginIsolated!=='undefined'&&crossOriginIsolated){const r=await p.measureUserAgentSpecificMemory();ua=mb(r.bytes)}}catch{}const m:any=p.memory;this.recordMemory({at:Date.now(),jsHeapUsedMB:m?mb(m.usedJSHeapSize):undefined,jsHeapTotalMB:m?mb(m.totalJSHeapSize):undefined,jsHeapLimitMB:m?mb(m.jsHeapSizeLimit):undefined,uaSpecificMB:ua,detachedSuspects:this.dom[this.dom.length-1]?.detachedSuspects||0})}
}
function rank(x:Finding['severity']){return x==='critical'?3:x==='warning'?2:1}function short(u:string){try{const x=new URL(u,location.href);return(x.pathname+x.search).slice(0,110)}catch{return u.slice(0,110)}}function normalizeUrl(u:string){try{const x=new URL(u,location.href);x.searchParams.sort();return x.origin+x.pathname+'?'+x.searchParams.toString()}catch{return u}}
function environment(){const n:any=typeof navigator==='undefined'?{}:navigator,c=n.connection,p:any=typeof performance==='undefined'?{}:performance,nav:any=p.getEntriesByType?.('navigation')?.[0];return{url:typeof location==='undefined'?'':location.href,userAgent:n.userAgent||'',viewport:typeof innerWidth==='undefined'?'':`${innerWidth}x${innerHeight} @${devicePixelRatio||1}x`,cpuCores:n.hardwareConcurrency||'unknown',deviceMemoryGB:n.deviceMemory||'unknown',connection:c?`${c.effectiveType||''} ${c.downlink||''}Mbps ${c.rtt||''}ms`:undefined,domInteractiveMs:nav?.domInteractive?Math.round(nav.domInteractive):undefined,loadMs:nav?.loadEventEnd?Math.round(nav.loadEventEnd):undefined,reactDeepHook:typeof window!=='undefined'&&!!(window as any).__REACT_RUNTIME_TOOLKIT_PRELOAD__}}
export const runtimeStore=new RuntimeStore();
