export type Severity = 'info' | 'warning' | 'critical';
export type RuntimeConfig = {
  brand?: string;
  slowNetworkMs?: number;
  slowCommitMs?: number;
  largeResourceKB?: number;
  commitBurstCount?: number;
  commitBurstWindowMs?: number;
  highlightRenders?: boolean;
  captureConsole?: boolean;
  captureStacks?: boolean;
  trackTimers?: boolean;
  maxEntries?: number;
};
export type InteractionSample = { id:string; type:string; target:string; at:number; durationMs?:number; processingStartMs?:number; presentationDelayMs?:number };
export type PropChange = { key:string; oldValue:string; newValue:string; kind:'value'|'reference'|'function'; shallowEqual?:boolean };
export type HookChange = { index:number; oldValue:string; newValue:string };
export type ReactComponentChange = { name:string; depth:number; reason:'mount'|'props'|'state'|'props+state'|'context/parent'|'unknown'; props:PropChange[]; hooks:HookChange[]; source?:string; host?:string; actualDurationMs?:number; selfDurationMs?:number; referentialChurn:string[] };
export type ReactCommitSample = { id:string; rendererId:number; at:number; interactionId?:string; componentCount:number; changedCount:number; effectDurationMs?:number; passiveEffectDurationMs?:number; components:ReactComponentChange[] };
export type NetworkSample = { id:string; transport:'fetch'|'xhr'; method:string; url:string; status:number|null; ok:boolean|null; startAt:number; at:number; durationMs:number; error?:string; requestStack?:string; responseType?:string; responseSizeKB?:number|null; interactionId?:string; decoded?:unknown };
export type ResourceSample = { url:string; initiatorType:string; durationMs:number; transferKB:number|null; encodedKB:number|null; decodedKB:number|null; ttfbMs:number|null; cache:'hit'|'miss'|'unknown'; protocol?:string; serverTiming:string[]; at:number };
export type LoafScript = { sourceURL?:string; sourceFunctionName?:string; invoker?:string; durationMs?:number; forcedStyleAndLayoutDurationMs?:number };
export type LongTaskSample = { at:number; durationMs:number; attribution?:string };
export type LoafSample = { at:number; durationMs:number; blockingDurationMs:number; renderStartMs?:number; firstUIEventTimestampMs?:number; scripts:LoafScript[] };
export type VitalSnapshot = { lcpMs?:number; lcpTarget?:string; cls:number; clsTarget?:string; inpMs?:number; inpTarget?:string; fcpMs?:number; ttfbMs?:number; fps?:number };
export type RuntimeErrorSample = { kind:'error'|'unhandledrejection'|'resource'|'react-boundary'; message:string; stack?:string; componentStack?:string; target?:string; at:number };
export type ConsoleSample = { level:'log'|'info'|'warn'|'error'|'debug'; message:string; at:number };
export type DomSample = { at:number; nodes:number; maxDepth:number; added:number; removed:number; mutationRate:number; detachedSuspects:number };
export type MemorySample = { at:number; jsHeapUsedMB?:number; jsHeapTotalMB?:number; jsHeapLimitMB?:number; uaSpecificMB?:number; detachedSuspects:number };
export type TimerSnapshot = { at:number; activeTimeouts:number; activeIntervals:number; activeRafs:number; oldestIntervalMs:number };
export type InspectionSnapshot = { target:string; rect:string; component?:string; componentChain:string[]; props:Record<string,string>; hooks:string[]; attributes:Record<string,string>; source?:string; at:number };
export type Finding = { severity:Severity; category:string; title:string; detail:string; evidence:string; recommendation:string };
export type RuntimeSnapshot = { startedAt:number; route:string; vitals:VitalSnapshot; interactions:InteractionSample[]; commits:ReactCommitSample[]; network:NetworkSample[]; resources:ResourceSample[]; loafs:LoafSample[]; longTasks:LongTaskSample[]; errors:RuntimeErrorSample[]; console:ConsoleSample[]; dom:DomSample[]; memory:MemorySample[]; timers:TimerSnapshot[]; inspection:InspectionSnapshot|null; rendererVersions:string[]; environment:Record<string,string|number|boolean|undefined> };
export type HistorySnapshot = { id:string; label:string; at:number; snapshot:RuntimeSnapshot; findings:Finding[] };
export type NetworkDecoder = (sample:NetworkSample) => unknown | null | undefined;
export type FindingRule = (snapshot:RuntimeSnapshot, config:Required<RuntimeConfig>) => Finding[];
