import type {ImportColumnSchema,ImportSchema,ImportSheetSchema} from "./contracts";
import type {NetworkVerticalKind} from "../verticals/contracts";

const c=(key:string,label:string,type:ImportColumnSchema["type"],target:ImportColumnSchema["target"],description:string,extra:Partial<ImportColumnSchema>={}):ImportColumnSchema=>({key,label,type,target,description,...extra});
const entity=(key:string,name:string,entityKind:string,description:string,columns:ImportColumnSchema[],sampleRows:Record<string,unknown>[],required=true):ImportSheetSchema=>({key,name,entityKind,description,columns,sampleRows,required,recordType:"entity"});
const domain=(key:string,name:string,description:string,columns:ImportColumnSchema[],sampleRows:Record<string,unknown>[],required=false):ImportSheetSchema=>({key,name,description,columns,sampleRows,required,recordType:"domain"});
const relation=(key:string,name:string,description:string,columns:ImportColumnSchema[],sampleRows:Record<string,unknown>[],required=false):ImportSheetSchema=>({key,name,description,columns,sampleRows,required,recordType:"relationship"});
const stable=(label="Stable ID")=>c("stable_id",label,"text","stableId","A friendly identifier used only inside this workbook to connect sheets.",{required:true,example:"P001",privacyNote:"Do not use Aadhaar, PAN, passport numbers or other sensitive government identifiers."});
const name=(label="Name")=>c("name",label,"text","label","Display name.",{required:true,example:"Aarav Sharma"});
const email=()=>c("email","Email","email","metadata.email","Email used for contact/claiming when the vertical supports it.",{example:"aarav@example.com",privacyNote:"Only include an email when you are authorized to import it."});
const ref=(key:string,label:string,sheet:string,description:string)=>c(key,label,"reference",key==="from_id"?"fromRef":key==="to_id"?"toRef":`metadata.${key}`,description,{required:true,referenceSheet:sheet,example:"P001"});
const enumCol=(key:string,label:string,target:ImportColumnSchema["target"],values:string[],description:string,required=false)=>c(key,label,"enum",target,description,{required,acceptedValues:values,example:values[0]});
const text=(key:string,label:string,target:ImportColumnSchema["target"],description:string,required=false,example="")=>c(key,label,"text",target,description,{required,example});

const family:ImportSchema={verticalKind:"family",version:"family-import.v2",title:"Family guided workbook",description:"People and kinship relationships with friendly cross-sheet IDs.",privacyNotes:["Use friendly IDs such as P001; never use government identifiers.","Leave unknown personal details blank and complete them later."],duplicatePolicy:"Friendly IDs must be unique in the workbook. Existing Family validation decides whether a person/relationship is merged or needs review.",sheets:[
 entity("people","Family Members","person","Add each person once.",[stable("Person ID"),name("Full Name"),c("date_of_birth","Date of Birth","date","metadata.date_of_birth","YYYY-MM-DD when known.",{example:"1990-08-21"}),text("profession","Profession","metadata.profession","Optional profession."),text("city","City","metadata.city","Optional city."),email()], [{stable_id:"P001",name:"Aarav Sharma",date_of_birth:"1990-08-21",profession:"Engineer",city:"Pune",email:"aarav@example.com"},{stable_id:"P002",name:"Meera Sharma",city:"Pune"}]),
 relation("relationships","Relationships","Connect people already listed in Family Members.",[ref("from_id","Person ID","Family Members","Person whose relationship is being recorded."),ref("to_id","Related Person ID","Family Members","Related person."),enumCol("relationship","Relationship","relationshipType",["Parent","Child","Spouse"],"Relationship direction from Person ID to Related Person ID.",true)],[{from_id:"P001",to_id:"P002",relationship:"Spouse"}])
]};

const alumni:ImportSchema={verticalKind:"alumni",version:"alumni-import.v1",title:"Alumni guided workbook",description:"Alumni profiles plus optional cohort/chapter and connection references.",privacyNotes:["Import only information the alumni network is entitled to hold."],duplicatePolicy:"Stable Alumni IDs must be unique. Existing records with the same imported stable ID may be updated by import adapters; duplicate rows are rejected before commit.",sheets:[
 entity("alumni","Alumni","person","One row per alumnus/alumna.",[stable("Alumni ID"),name("Full Name"),email(),c("graduation_year","Graduation Year","number","affiliation.batch","Graduation year.",{example:2012}),text("program","Program / Course","affiliation.program","Course or stream."),text("department","Department / School","affiliation.department","Department or school."),text("city","City","affiliation.city","Current city."),text("company","Company","affiliation.company","Current company."),text("job_title","Job Title","metadata.job_title","Current role/title.")],[{stable_id:"A001",name:"Neha Kulkarni",email:"neha@example.com",graduation_year:2012,program:"Computer Science",department:"Engineering",city:"Pune",company:"Acme",job_title:"Principal Engineer"},{stable_id:"A002",name:"Rohan Desai",graduation_year:2011,program:"Computer Science",department:"Engineering",city:"Mumbai",company:"Northstar",job_title:"Director"}]),
 entity("cohorts","Cohorts / Chapters","organization","Optional cohorts or chapters that can be referenced during enrichment.",[stable("Cohort ID"),name("Cohort / Chapter"),text("description","Description","metadata.description","Optional context.")],[{stable_id:"C2012",name:"Class of 2012"}],false),
 relation("connections","Connections","Optional trusted alumni connections.",[ref("from_id","From Alumni ID","Alumni","Source alumnus."),ref("to_id","To Alumni ID","Alumni","Target alumnus."),enumCol("relationship","Relationship","relationshipType",["batchmate","classmate","mentor","professional_connection"],"Connection type.",true)],[{from_id:"A001",to_id:"A002",relationship:"mentor"}])
]};

const association:ImportSchema={verticalKind:"association",version:"association-import.v1",title:"Association / Community workbook",description:"Members, chapters/groups and role affiliations.",privacyNotes:["Keep contact fields limited to what the association is allowed to publish to members."],duplicatePolicy:"Stable IDs are idempotency keys for this workbook lineage. Reusing one updates that record; duplicate IDs inside one workbook are rejected.",sheets:[
 entity("members","Members","person","Association members.",[stable("Member ID"),name("Member Name"),email(),text("area","Area / Locality","affiliation.area","Area/locality."),text("profession","Profession","affiliation.profession","Profession."),text("membership_year","Membership Year","affiliation.membership_year","Joining/renewal year.")],[{stable_id:"M001",name:"Riya Shah",email:"riya@example.com",area:"Kharadi",profession:"Architect",membership_year:"2026"}]),
 entity("groups","Chapters / Groups","organization","Chapters, circles or groups.",[stable("Group ID"),name("Chapter / Group"),text("area","Area","affiliation.area","Area served."),text("description","Description","metadata.description","Purpose/context.")],[{stable_id:"G001",name:"Pune East",area:"Pune East"}],false),
 relation("roles","Roles / Affiliations","Optional member-to-group affiliation rows.",[ref("from_id","Member ID","Members","Member reference."),ref("to_id","Group ID","Chapters / Groups","Group reference."),enumCol("relationship","Role / Affiliation","relationshipType",["serves_on","supports"],"Governed member-to-group affiliation relationship.",true)],[{from_id:"M001",to_id:"G001",relationship:"serves_on"}])
]};

const familyAssociation:ImportSchema={verticalKind:"family-association",version:"family-association-import.v2",title:"Family Association activation workbook",description:"Families, people, governed household membership, annual membership and leadership history.",privacyNotes:["Use family-local friendly IDs, not official identity numbers.","Fees, contact details and membership fields should follow association privacy settings."],duplicatePolicy:"Family and Person stable IDs are unique within the workbook and reused on later activations to update the same imported record. Possible real-world duplicates are surfaced by Network Activation Autopilot for human review.",sheets:[
 entity("families","Families","family","One row per participating household/family.",[stable("Family ID"),name("Family / Household Name"),text("area","Area","affiliation.area","Chapter/locality."),text("membership_status","Membership Status","affiliation.membership_status","Current association status.")],[{stable_id:"F001",name:"Sharma Family",area:"Pune East",membership_status:"Active"}]),
 entity("people","People","person","People participating through a family.",[stable("Person ID"),name("Full Name"),email(),text("phone","Phone","metadata.phone","Optional phone number."),c("date_of_birth","Date of Birth","date","metadata.date_of_birth","YYYY-MM-DD when known.",{example:"1988-05-12"}),text("profession","Profession","affiliation.profession","Profession."),text("city","City","affiliation.city","City.")],[{stable_id:"P001",name:"Aarav Sharma",email:"aarav@example.com",phone:"9876543210",date_of_birth:"1988-05-12",profession:"Engineer",city:"Pune"},{stable_id:"P002",name:"Meera Sharma",profession:"Architect",city:"Pune"}]),
 relation("household_membership","Household Membership","Connect people to families.",[ref("from_id","Person ID","People","Person reference."),ref("to_id","Family ID","Families","Family reference."),enumCol("relationship","Household Relationship","relationshipType",["member_of_family"],"Person-to-family membership relationship.",true)],[{from_id:"P001",to_id:"F001",relationship:"member_of_family"},{from_id:"P002",to_id:"F001",relationship:"member_of_family"}]),
 domain("association_membership","Association Membership","Annual household membership, representative and payment state.",[
  ref("family_id","Family ID","Families","Family reference."),
  text("membership_year","Membership Year","metadata.membership_year","Cycle/year.",true,"2026-27"),
  c("representative_id","Representative Person ID","reference","metadata.representative_id","Optional family representative for this membership year.",{referenceSheet:"People",example:"P001"}),
  enumCol("status","Status","metadata.status",["active","grace","expired","inactive"],"Membership state.",true),
  enumCol("payment_status","Payment Status","metadata.payment_status",["unpaid","paid","waived","partial","not_required"],"Payment state."),
  c("amount_paid","Amount Paid","number","metadata.amount_paid","Amount collected for the family in this membership year.",{example:2100}),
  text("payment_reference","Payment Reference","metadata.payment_reference","Optional receipt/reference."),
  text("notes","Notes","metadata.notes","Optional non-sensitive note.")
 ],[{family_id:"F001",membership_year:"2026-27",representative_id:"P001",status:"active",payment_status:"paid",amount_paid:2100,payment_reference:"RCPT-001"}]),
 domain("leadership_history","Leadership History","Current and historical Association roles.",[
  ref("person_id","Person ID","People","Person holding the role."),
  text("membership_year","Membership Year","metadata.membership_year","Membership cycle/year.",true,"2026-27"),
  enumCol("role_key","Role","metadata.role_key",["president","president-elect","past-president","secretary","treasurer","director","chairperson","committee-member","volunteer","mentor"],"Association role.",true),
  c("starts_on","Starts On","date","metadata.starts_on","Optional role start date.",{example:"2026-04-01"}),
  c("ends_on","Ends On","date","metadata.ends_on","Optional role end date.",{example:"2027-03-31"}),
  text("notes","Notes","metadata.notes","Optional role context.")
 ],[{person_id:"P001",membership_year:"2026-27",role_key:"president",starts_on:"2026-04-01",ends_on:"2027-03-31"}])
]};

const housing:ImportSchema={verticalKind:"housing-society",version:"housing-society-import.v1",title:"Housing Society guided workbook",description:"Buildings/units, residents, occupancy, households, vehicles and parking with stable cross-sheet references.",privacyNotes:["Do not import Aadhaar/PAN/passport data.","Resident email and phone are personal data; import only with society authorization."],duplicatePolicy:"Unit/Resident stable IDs must be unique in this workbook. The Housing Society importer updates matching units/residents by domain keys and records occupancy history rather than overwriting it.",sheets:[
 entity("units","Buildings / Units","unit","Physical units/flats.",[stable("Unit ID"),name("Unit / Flat"),text("building","Building / Tower","affiliation.building","Building."),text("wing","Wing","affiliation.wing","Wing."),text("floor","Floor","affiliation.floor","Floor."),text("unit_type","Unit Type","affiliation.unit_type","e.g. 2 BHK."),text("area","Area","metadata.area","Area/locality.")],[{stable_id:"U001",name:"A-101",building:"A",wing:"A",floor:"1",unit_type:"2 BHK"}]),
 entity("residents","Residents","person","Residents/owners/tenants.",[stable("Resident ID"),name("Resident Name"),email(),text("phone","Phone","metadata.phone","Optional phone."),text("profession","Profession","metadata.profession","Optional profession.")],[{stable_id:"R001",name:"Priya Mehta",email:"priya@example.com",phone:"9876543210"}]),
 domain("occupancy","Occupancy / Ownership / Tenancy","Connect resident to unit with time-bounded role.",[ref("resident_id","Resident ID","Residents","Resident reference."),ref("unit_id","Unit ID","Buildings / Units","Unit reference."),enumCol("occupancy_role","Role","metadata.occupancy_role",["owner","co-owner","tenant","occupant"],"Occupancy role.",true),c("starts_on","Starts On","date","metadata.starts_on","YYYY-MM-DD.",{example:"2026-04-01"}),text("household","Household","metadata.household","Optional household label.")],[{resident_id:"R001",unit_id:"U001",occupancy_role:"owner",starts_on:"2026-04-01",household:"Mehta Family"}],true),
 domain("vehicles","Vehicles","Optional vehicles linked to residents/units.",[stable("Vehicle ID"),ref("resident_id","Resident ID","Residents","Owner/resident reference."),ref("unit_id","Unit ID","Buildings / Units","Unit reference."),text("registration","Registration","metadata.vehicle_registration","Vehicle registration.",true,"MH12AB1234"),enumCol("vehicle_type","Vehicle Type","metadata.vehicle_type",["car","two-wheeler","cycle"],"Vehicle type."),c("is_ev","EV?","boolean","metadata.is_ev","Yes/No or true/false.",{example:"No"})],[{stable_id:"V001",resident_id:"R001",unit_id:"U001",registration:"MH12AB1234",vehicle_type:"car",is_ev:"No"}]),
 domain("parking","Parking","Optional parking slots/allocations.",[stable("Parking ID"),text("slot","Parking Slot","metadata.parking_slot","Slot code.",true,"P-12"),text("zone","Zone / Basement","metadata.parking_zone","Zone."),ref("unit_id","Unit ID","Buildings / Units","Allocated unit."),c("vehicle_id","Vehicle ID","reference","metadata.vehicle_id","Optional vehicle reference.",{referenceSheet:"Vehicles",example:"V001"})],[{stable_id:"PK001",slot:"P-12",zone:"B1",unit_id:"U001",vehicle_id:"V001"}])
]};

const organization:ImportSchema={verticalKind:"organization",version:"organization-import.v1",title:"Organization workbook",description:"People, teams, projects, skills and reporting/working relationships.",privacyNotes:["Do not place secrets, credentials or HR-confidential fields in the workbook."],duplicatePolicy:"Stable IDs are used to update imported records and resolve cross-sheet links.",sheets:[
 entity("people","People","person","Organization people.",[stable("Person ID"),name("Full Name"),email(),text("role","Role / Title","metadata.role","Role/title."),text("city","City","affiliation.city","City.")],[{stable_id:"P001",name:"Anita Rao",email:"anita@example.com",role:"Engineering Manager",city:"Pune"}]),
 entity("teams","Teams","team","Teams and functions.",[stable("Team ID"),name("Team Name"),text("department","Department","affiliation.department","Department/function.")],[{stable_id:"T001",name:"Platform UI",department:"Engineering"}]),
 entity("projects","Projects","project","Projects/workstreams.",[stable("Project ID"),name("Project Name"),text("status","Status","metadata.status","Project status."),text("team","Team","affiliation.team","Primary team label.")],[{stable_id:"PR001",name:"Design System",status:"Active",team:"Platform UI"}]),
 entity("skills","Skills","product","Reusable skills/capabilities.",[stable("Skill ID"),name("Skill"),text("category","Category","affiliation.category","Skill category.")],[{stable_id:"S001",name:"TypeScript",category:"Engineering"}],false),
 relation("relationships","Reporting / Relationships","Optional reporting, team or project relationships.",[ref("from_id","From ID","People","Source person."),c("to_id","To ID","reference","toRef","Target person/team/project ID.",{required:true,referenceSheets:["People","Teams","Projects"],example:"T001"}),text("relationship","Relationship","relationshipType","Allowed organization relationship: reports_to, works_with, owns or depends_on.",true,"works_with")],[{from_id:"P001",to_id:"T001",relationship:"works_with"}],false)
]};

const businessTrust:ImportSchema={verticalKind:"business-trust",version:"business-trust-import.v1",title:"Business Trust workbook",description:"Businesses, contacts, categories and trust/business relationships.",privacyNotes:["Record only business/contact information appropriate for the trust network."],duplicatePolicy:"Business/contact IDs are stable import keys; repeated IDs update, duplicates in the same workbook are rejected.",sheets:[
 entity("businesses","Businesses","organization","Trusted businesses.",[stable("Business ID"),name("Business Name"),text("category","Category","affiliation.category","Business category."),text("region","Region","affiliation.region","Operating region."),text("website","Website","metadata.website","Website.")],[{stable_id:"B001",name:"Shree Foods",category:"Food",region:"Pune",website:"https://example.com"},{stable_id:"B002",name:"Northstar Packaging",category:"Packaging",region:"Mumbai"}]),
 entity("contacts","Contacts","person","Business contacts.",[stable("Contact ID"),name("Contact Name"),email(),text("business","Business","affiliation.business","Business name."),text("role","Role","metadata.role","Role/title.")],[{stable_id:"C001",name:"Rohan Jain",email:"rohan@example.com",business:"Shree Foods",role:"Founder"}]),
 entity("categories","Categories","product","Optional controlled category list.",[stable("Category ID"),name("Category")],[{stable_id:"CAT01",name:"Food"}],false),
 relation("relationships","Trust / Business Relationships","Optional typed trusted relationship.",[ref("from_id","From Business ID","Businesses","Source business."),ref("to_id","To Business ID","Businesses","Target business."),text("relationship","Relationship","relationshipType","Allowed trust relationship: recommends, verified_by, supplies_to or worked_with.",true,"supplies_to")],[{from_id:"B001",to_id:"B002",relationship:"supplies_to"}],false)
]};

const franchise:ImportSchema={verticalKind:"franchise",version:"franchise-import.v1",title:"Franchise workbook",description:"Branches, owners/operators, geography and organizational relationships.",privacyNotes:["Keep personal operator contact details limited to operational need."],duplicatePolicy:"Branch/operator stable IDs are import keys. Duplicate IDs in one workbook are rejected.",sheets:[
 entity("branches","Branches","branch","Franchise locations.",[stable("Branch ID"),name("Branch / Location"),text("city","City","affiliation.city","City."),text("state","State","affiliation.state","State."),text("country","Country","affiliation.country","Country."),text("store_type","Store Type","affiliation.store_type","Store/location type.")],[{stable_id:"BR001",name:"Kharadi Store",city:"Pune",state:"Maharashtra",country:"India",store_type:"Retail"}]),
 entity("operators","Owners / Operators","person","Owners/operators/managers.",[stable("Operator ID"),name("Owner / Operator"),email(),text("role","Role","metadata.role","Owner/operator/manager.")],[{stable_id:"O001",name:"Kunal Shah",email:"kunal@example.com",role:"Owner"}]),
 entity("geography","Geography","location","Optional reusable geography nodes.",[stable("Geography ID"),name("Geography"),text("level","Level","metadata.level","Region/state/city.")],[{stable_id:"G001",name:"Pune",level:"City"}],false),
 relation("relationships","Organizational Relationships","Connect operators and branches.",[ref("from_id","Operator ID","Owners / Operators","Operator reference."),ref("to_id","Branch ID","Branches","Branch reference."),enumCol("relationship","Relationship","relationshipType",["owns","operates","manages","supports"],"Operator-to-branch relation.",true)],[{from_id:"O001",to_id:"BR001",relationship:"owns"}])
]};

const professional:ImportSchema={verticalKind:"professional",version:"professional-import.v1",title:"Professional Network workbook",description:"Professionals, expertise, affiliations and trusted professional relationships.",privacyNotes:["Credentials and contact details should be imported only when permitted by the professional/community."],duplicatePolicy:"Professional/expertise IDs are stable import keys and relationship references.",sheets:[
 entity("professionals","Professionals","person","Professional profiles.",[stable("Professional ID"),name("Full Name"),email(),text("profession","Profession","affiliation.profession","Profession."),text("specialty","Specialty","affiliation.specialty","Specialty."),text("city","City","affiliation.city","City."),text("credential","Credential","affiliation.credential","Credential label.")],[{stable_id:"P001",name:"Dr. Kavya Joshi",email:"kavya@example.com",profession:"Consultant",specialty:"Strategy",city:"Pune",credential:"MBA"},{stable_id:"P002",name:"Arjun Mehta",profession:"Consultant",specialty:"Finance",city:"Mumbai",credential:"CA"}]),
 entity("expertise","Expertise","organization","Reusable expertise/service labels.",[stable("Expertise ID"),name("Expertise"),text("industry","Industry","affiliation.industry","Industry."),text("service","Service","affiliation.service","Service area.")],[{stable_id:"E001",name:"Growth Strategy",industry:"Technology",service:"Advisory"}],false),
 entity("affiliations","Affiliations","organization","Professional bodies/firms.",[stable("Affiliation ID"),name("Affiliation"),text("type","Type","metadata.type","Firm, association, institute.")],[{stable_id:"A001",name:"Pune Advisory Forum",type:"Association"}],false),
 relation("relationships","Professional Relationships","Trusted professional connection paths.",[ref("from_id","From Professional ID","Professionals","Source professional."),ref("to_id","To Professional ID","Professionals","Target professional."),enumCol("relationship","Relationship","relationshipType",["worked_with","referred_by","collaborates_with","mentors"],"Relationship type.",true)],[{from_id:"P001",to_id:"P002",relationship:"collaborates_with"}],false)
]};

export const IMPORT_SCHEMA_REGISTRY:Record<NetworkVerticalKind,ImportSchema>={family,alumni,association,"family-association":familyAssociation,"housing-society":housing,organization,"business-trust":businessTrust,franchise,professional};
export const IMPORT_SCHEMA_KINDS=Object.keys(IMPORT_SCHEMA_REGISTRY) as NetworkVerticalKind[];
export function getImportSchema(kind:NetworkVerticalKind){return IMPORT_SCHEMA_REGISTRY[kind];}
