-- TRUSTWEAVE D12 CANONICAL CURRENT-STATE BASELINE.
-- Materialized after fresh-project structural/security/API/behavior/product parity on 2026-09-20.
-- DO NOT apply these files to the historical golden project as an upgrade sequence.
-- Historical supabase/migrations/001..123 remain immutable upgrade history.

ALTER TABLE "public"."hs_amenities" ADD CONSTRAINT "hs_amenities_network_id_name_key" UNIQUE (network_id, name);
ALTER TABLE "public"."hs_amenities" ADD CONSTRAINT "hs_amenities_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_amenity_bookings" ADD CONSTRAINT "hs_amenity_bookings_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_asset_service_records" ADD CONSTRAINT "hs_asset_service_records_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_assets" ADD CONSTRAINT "hs_assets_network_id_asset_code_key" UNIQUE (network_id, asset_code);
ALTER TABLE "public"."hs_assets" ADD CONSTRAINT "hs_assets_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_bill_adjustments" ADD CONSTRAINT "hs_bill_adjustments_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_bill_line_items" ADD CONSTRAINT "hs_bill_line_items_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_billing_cycles" ADD CONSTRAINT "hs_billing_cycles_network_id_period_start_period_end_key" UNIQUE (network_id, period_start, period_end);
ALTER TABLE "public"."hs_billing_cycles" ADD CONSTRAINT "hs_billing_cycles_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_budget_lines" ADD CONSTRAINT "hs_budget_lines_network_id_financial_year_category_label_key" UNIQUE (network_id, financial_year, category, label);
ALTER TABLE "public"."hs_budget_lines" ADD CONSTRAINT "hs_budget_lines_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_charge_heads" ADD CONSTRAINT "hs_charge_heads_network_id_code_key" UNIQUE (network_id, code);
ALTER TABLE "public"."hs_charge_heads" ADD CONSTRAINT "hs_charge_heads_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_committee_assignments" ADD CONSTRAINT "hs_committee_assignments_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_committee_terms" ADD CONSTRAINT "hs_committee_terms_network_id_label_starts_on_key" UNIQUE (network_id, label, starts_on);
ALTER TABLE "public"."hs_committee_terms" ADD CONSTRAINT "hs_committee_terms_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_complaint_comments" ADD CONSTRAINT "hs_complaint_comments_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_complaint_routes" ADD CONSTRAINT "hs_complaint_routes_pkey" PRIMARY KEY (network_id, category_key);
ALTER TABLE "public"."hs_complaints" ADD CONSTRAINT "hs_complaints_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_compliance_items" ADD CONSTRAINT "hs_compliance_items_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_domestic_staff" ADD CONSTRAINT "hs_domestic_staff_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_emergency_contacts" ADD CONSTRAINT "hs_emergency_contacts_network_id_category_label_key" UNIQUE (network_id, category, label);
ALTER TABLE "public"."hs_emergency_contacts" ADD CONSTRAINT "hs_emergency_contacts_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_expenses" ADD CONSTRAINT "hs_expenses_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_funds" ADD CONSTRAINT "hs_funds_network_id_code_key" UNIQUE (network_id, code);
ALTER TABLE "public"."hs_funds" ADD CONSTRAINT "hs_funds_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_governance_action_items" ADD CONSTRAINT "hs_governance_action_items_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_governance_documents" ADD CONSTRAINT "hs_governance_documents_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_governance_meetings" ADD CONSTRAINT "hs_governance_meetings_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_import_batches" ADD CONSTRAINT "hs_import_batches_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_meeting_agenda_items" ADD CONSTRAINT "hs_meeting_agenda_items_meeting_id_item_order_key" UNIQUE (meeting_id, item_order);
ALTER TABLE "public"."hs_meeting_agenda_items" ADD CONSTRAINT "hs_meeting_agenda_items_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_move_requests" ADD CONSTRAINT "hs_move_requests_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_notice_reads" ADD CONSTRAINT "hs_notice_reads_pkey" PRIMARY KEY (network_id, notice_id, user_id);
ALTER TABLE "public"."hs_notices" ADD CONSTRAINT "hs_notices_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_parking_allocations" ADD CONSTRAINT "hs_parking_allocations_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_parking_slots" ADD CONSTRAINT "hs_parking_slots_network_id_slot_code_key" UNIQUE (network_id, slot_code);
ALTER TABLE "public"."hs_parking_slots" ADD CONSTRAINT "hs_parking_slots_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_payments" ADD CONSTRAINT "hs_payments_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_pilot_checkpoints" ADD CONSTRAINT "hs_pilot_checkpoints_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_pilot_pricing_experiments" ADD CONSTRAINT "hs_pilot_pricing_experiments_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_pilot_runs" ADD CONSTRAINT "hs_pilot_runs_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_pilot_usage_events" ADD CONSTRAINT "hs_pilot_usage_events_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_renovation_requests" ADD CONSTRAINT "hs_renovation_requests_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_resident_invitations" ADD CONSTRAINT "hs_resident_invitations_network_id_person_entity_id_key" UNIQUE (network_id, person_entity_id);
ALTER TABLE "public"."hs_resident_invitations" ADD CONSTRAINT "hs_resident_invitations_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_resident_invitations" ADD CONSTRAINT "hs_resident_invitations_token_key" UNIQUE (token);
ALTER TABLE "public"."hs_resolution_votes" ADD CONSTRAINT "hs_resolution_votes_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_resolution_votes" ADD CONSTRAINT "hs_resolution_votes_resolution_id_voter_user_id_key" UNIQUE (resolution_id, voter_user_id);
ALTER TABLE "public"."hs_resolutions" ADD CONSTRAINT "hs_resolutions_network_id_resolution_number_key" UNIQUE (network_id, resolution_number);
ALTER TABLE "public"."hs_resolutions" ADD CONSTRAINT "hs_resolutions_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_security_operator_grants" ADD CONSTRAINT "hs_security_operator_grants_network_id_user_id_scope_key" UNIQUE (network_id, user_id, scope);
ALTER TABLE "public"."hs_security_operator_grants" ADD CONSTRAINT "hs_security_operator_grants_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_staff_unit_permissions" ADD CONSTRAINT "hs_staff_unit_permissions_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_unit_bills" ADD CONSTRAINT "hs_unit_bills_network_id_billing_cycle_id_unit_entity_id_key" UNIQUE (network_id, billing_cycle_id, unit_entity_id);
ALTER TABLE "public"."hs_unit_bills" ADD CONSTRAINT "hs_unit_bills_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_unit_occupancy_history" ADD CONSTRAINT "hs_unit_occupancy_history_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_vehicles" ADD CONSTRAINT "hs_vehicles_network_id_registration_no_key" UNIQUE (network_id, registration_no);
ALTER TABLE "public"."hs_vehicles" ADD CONSTRAINT "hs_vehicles_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_vendor_contracts" ADD CONSTRAINT "hs_vendor_contracts_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_vendors" ADD CONSTRAINT "hs_vendors_network_id_name_category_key" UNIQUE (network_id, name, category);
ALTER TABLE "public"."hs_vendors" ADD CONSTRAINT "hs_vendors_pkey" PRIMARY KEY (id);
ALTER TABLE "public"."hs_visitors" ADD CONSTRAINT "hs_visitors_pkey" PRIMARY KEY (id);
