import {supabase} from "../../lib/supabase";
import {postCommand} from "../../lib/api-client";
import type {NetworkTrustBridge,NetworkBridgeCapabilities,NetworkBridgeRelationshipType} from "../../core/trust/network-bridge";
import type {NetworkBridgeCodeResult,RequestNetworkBridgeResult,ReviewNetworkBridgeResult,RevokeNetworkBridgeResult} from "../../core/api/contracts";
function required(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}
export async function fetchMyNetworkTrustBridges():Promise<NetworkTrustBridge[]>{const {data,error}=await required().rpc("get_my_network_trust_bridges");if(error)throw error;return (data||[]).map((r:any)=>({id:String(r.id),requesterNetworkId:String(r.requester_network_id),requesterNetworkName:String(r.requester_network_name),recipientNetworkId:String(r.recipient_network_id),recipientNetworkName:String(r.recipient_network_name),relationshipType:r.relationship_type,status:r.status,contextLabel:r.context_label||null,capabilities:{discovery:!!r.discovery_enabled,introductions:!!r.introductions_enabled,pathTraversal:!!r.path_traversal_enabled},direction:r.direction,canReview:!!r.can_review,canRevoke:!!r.can_revoke,createdAt:r.created_at,updatedAt:r.updated_at}))}
export async function getNetworkBridgeCode(networkId:string,regenerate=false){return (await postCommand<NetworkBridgeCodeResult>("/api/v1/trust-bridges/code",{networkId,regenerate})).code}
export async function requestNetworkTrustBridge(input:{sourceNetworkId:string;targetCode:string;relationshipType:NetworkBridgeRelationshipType;contextLabel?:string;capabilities:NetworkBridgeCapabilities}){return (await postCommand<RequestNetworkBridgeResult>("/api/v1/trust-bridges/request",input)).bridgeId}
export async function reviewNetworkTrustBridge(bridgeId:string,accept:boolean){return postCommand<ReviewNetworkBridgeResult>("/api/v1/trust-bridges/review",{bridgeId,accept})}
export async function revokeNetworkTrustBridge(bridgeId:string){return postCommand<RevokeNetworkBridgeResult>("/api/v1/trust-bridges/revoke",{bridgeId})}
