import type {VerticalAppComposition} from "../../../core/verticals/app-composition";
const label=(en:string)=>({en,hi:en,mr:en});
export const ALUMNI_APP_COMPOSITION={kind:"alumni",renderStatus:"active",featureCatalogId:"alumni",primaryNavigation:[
 {viewId:"home",featureKey:"alumni.core.home",iconToken:"home",label:label("Home")},
 {viewId:"intelligence",featureKey:"alumni.shared.intelligence",iconToken:"intelligence",label:label("Intelligence")},
 {viewId:"explorer",featureKey:"alumni.shared.explorer",iconToken:"layers",label:label("Explore")},
 {viewId:"directory",featureKey:"alumni.core.directory",iconToken:"users",label:label("Directory")},
 {viewId:"community",featureKey:"alumni.shared.community",iconToken:"calendar",label:label("Community")},
 {viewId:"places",featureKey:"alumni.shared.places",iconToken:"map",label:label("Places")},
 {viewId:"connections",featureKey:"alumni.core.connections",iconToken:"heart-handshake",label:label("Connections")},
 {viewId:"guide",iconToken:"book-open",label:label("Guide")}
],mobileMoreNavigation:[{viewId:"admin",featureKey:"alumni.admin.manage",iconToken:"settings",label:label("Admin"),adminOnly:true}],mobileBottomViewIds:["home","explorer","directory","community"],mobileMoreActiveViewIds:["intelligence","places","connections","admin","guide"],guide:{registryId:"alumni-guide-g7",guideByView:{home:"alumni-home",intelligence:"alumni-intelligence",explorer:"alumni-network-explorer",directory:"alumni-directory",community:"alumni-community",places:"alumni-places",connections:"alumni-connections",admin:"alumni-admin"},actionToView:{"Open network explorer":"explorer","Open alumni directory":"directory","Open alumni community":"community","Open alumni admin":"admin"},playgroundViewIds:["home","intelligence","explorer","directory","community","places"]},playground:{enabled:true,startView:"home",publicNetworkSettings:{name:"Sample Alumni Network",network_template:"alumni",vertical_kind:"alumni"}},launch:{bundles:[{key:"core",label:"Core",description:"Alumni home"},{key:"intelligence",label:"Intelligence",description:"Evidence-backed alumni discovery, health and warm paths"},{key:"discover",label:"Discover",description:"Explorer, directory and places"},{key:"community",label:"Community",description:"Events, RSVP, memories and groups"},{key:"connect",label:"Connect",description:"Identity and connections"},{key:"admin",label:"Admin",description:"Import and management"},{key:"network-effect",label:"Advanced network effect",description:"M6 trusted reach, bridges, discovery, pulse and governed multi-hop paths"},
{key:"federation",label:"Federation growth",description:"NF federation architecture and distribution-supernode onboarding leverage."},{key:"showcase",label:"Advanced showcase",description:"M7 synthetic WOW theater"},{key:"pilot-ops",label:"Advanced pilot operations",description:"M7 guided launch, pilot console, feedback, certification and decision gate"}],playgroundExcludedBundles:["network-effect","federation","showcase","pilot-ops"],playgroundTitle:"Alumni Playground",playgroundDescription:"Explore a living institutional network with multiple hierarchy projections, people, community activity and places.",playgroundRecommendation:"Switch Explorer projections to see the same people organized in different useful ways.",dayOneTitle:"Alumni on Network OS",dayOneDescription:"Living alumni network powered by shared platform capabilities",pilotTargetsTitle:"Alumni pilot",pilotTargetsDescription:"Start with one institution and a few complete cohorts.",footnoteTitle:"Shared engine, Alumni semantics",footnoteDescription:"Affiliation, activity and discovery mechanics are shared; institutional semantics remain Alumni-owned."},whatsNew:{featureToView:{"alumni.shared.intelligence":"intelligence","alumni.shared.explorer":"explorer","alumni.core.directory":"directory","alumni.core.cohorts":"explorer","alumni.shared.community":"community","alumni.shared.places":"places","alumni.admin.import":"admin"},defaultView:"home",kicker:"New in Alumni",fallbackTitle:"Alumni update",fallbackDescription:"A new Alumni capability is ready."}} satisfies VerticalAppComposition;
