import type {Reporter,TestCase,TestResult,FullResult} from '@playwright/test/reporter';
import fs from 'node:fs';
import path from 'node:path';
class BugReporter implements Reporter{
 rows:any[]=[];
 onTestEnd(test:TestCase,result:TestResult){if(result.status==='passed'||result.status==='skipped')return;this.rows.push({severity:result.status==='timedOut'?'P1':'P1',test:test.titlePath().join(' > '),status:result.status,error:result.error?.message||'',retry:result.retry,durationMs:result.duration,attachments:result.attachments.map(a=>({name:a.name,path:a.path,contentType:a.contentType}))})}
 onEnd(result:FullResult){const root=process.env.QA_PLAYWRIGHT_RESULTS_DIR||'qa-results',runtimeFile=path.join(root,'issues','runtime.ndjson');fs.mkdirSync(root,{recursive:true});fs.writeFileSync(path.join(root,'test-failures.json'),JSON.stringify(this.rows,null,2));const runtime=fs.existsSync(runtimeFile)?fs.readFileSync(runtimeFile,'utf8').trim().split('\n').filter(Boolean).map(x=>JSON.parse(x)):[];const all=[...this.rows,...runtime.map((x:any)=>({severity:x.status>=500?'P1':'P2',test:x.test,status:x.type,error:x.message,url:x.url}))];const md=['# TrustWeave Automated Bug Report','',`Generated: ${new Date().toISOString()}`,`Overall Playwright status: ${result.status}`,`Total captured issues: ${all.length}`,'','## Priority summary','',`- P0: ${all.filter(x=>x.severity==='P0').length}`,`- P1: ${all.filter(x=>x.severity==='P1').length}`,`- P2: ${all.filter(x=>x.severity==='P2').length}`,'','## Findings',''];all.forEach((x:any,i)=>{md.push(`### ${i+1}. [${x.severity}] ${x.test||x.status}`,'',`- Type/status: ${x.status||'runtime'}`,x.url?`- URL: ${x.url}`:'',`- Evidence: ${String(x.error||'').replace(/\n/g,' ')}`,'','**Fix action:** Reproduce from the named flow and trace; fix root cause, add regression assertion, rerun impacted vertical/role matrix.','')});fs.writeFileSync(path.join(root,'BUG-REPORT.md'),md.filter(Boolean).join('\n'))}
}
export default BugReporter;
