import * as XLSX from "xlsx";
import type {ImportColumnSchema,ImportIssue,ImportReview,ImportSchema,ParsedImportRow,ParsedImportSheet} from "./contracts";
import {getImportWorkbookSheetNames} from "./sheet-names";

const norm=(v:unknown)=>String(v??"").trim();
const normHeader=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");
const asDate=(v:unknown)=>{if(v===""||v==null)return "";if(v instanceof Date&&!Number.isNaN(v.getTime()))return v.toISOString().slice(0,10);if(typeof v==="number"){const d=XLSX.SSF.parse_date_code(v);if(d)return `${d.y}-${String(d.m).padStart(2,"0")}-${String(d.d).padStart(2,"0")}`;}const s=norm(v);const match=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!match)throw new Error("Use an unambiguous date such as 2026-04-01.");const y=Number(match[1]),m=Number(match[2]),d=Number(match[3]);const check=new Date(Date.UTC(y,m-1,d));if(check.getUTCFullYear()!==y||check.getUTCMonth()!==m-1||check.getUTCDate()!==d)throw new Error("Use a valid date such as 2026-04-01.");return s};
const asBool=(v:unknown)=>{if(v===""||v==null)return "";if(typeof v==="boolean")return v;const s=norm(v).toLowerCase();if(["true","yes","y","1"].includes(s))return true;if(["false","no","n","0"].includes(s))return false;throw new Error("Use Yes/No or true/false.")};
export function convertImportValue(value:unknown,col:ImportColumnSchema){const s=norm(value);if(!s)return "";if(col.type==="number"){const n=Number(value);if(!Number.isFinite(n))throw new Error("Use a number.");return n}if(col.type==="date")return asDate(value);if(col.type==="boolean")return asBool(value);if(col.type==="email"&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s))throw new Error("Use a valid email address.");if(col.type==="enum"&&col.acceptedValues&&!col.acceptedValues.some(v=>v.toLowerCase()===s.toLowerCase()))throw new Error(`Accepted values: ${col.acceptedValues.join(", ")}.`);return s}
function columnMap(headers:string[],columns:readonly ImportColumnSchema[]){const out=new Map<string,string>();for(const h of headers){const nh=normHeader(h);const col=columns.find(c=>[c.key,c.label,...(c.aliases||[])].some(x=>normHeader(x)===nh));if(col)out.set(col.key,h)}return out}

export async function parseImportWorkbook(input:ArrayBuffer,fileName:string,schema:ImportSchema):Promise<ImportReview>{
 const wb=XLSX.read(input,{type:"array",cellDates:true});const issues:ImportIssue[]=[];const sheets:ParsedImportSheet[]=[];const stableBySheet=new Map<string,Set<string>>();const globalStable=new Map<string,{sheet:string,row:number}>();const refs:{row:ParsedImportRow;col:ImportColumnSchema;value:string}[]=[];const workbookSheetNames=getImportWorkbookSheetNames(schema);
 for(const ss of schema.sheets){
  const generatedName=workbookSheetNames.get(ss.key)!;const actual=wb.SheetNames.find(n=>normHeader(n)===normHeader(generatedName)||normHeader(n)===normHeader(ss.name));if(!actual){if(ss.required)issues.push({severity:"error",code:"MISSING_SHEET",sheet:ss.name,message:`Required sheet “${ss.name}” is missing.`});continue}
  const rawRows=XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[actual],{defval:"",raw:true});const headers=rawRows[0]?Object.keys(rawRows[0]):[];const cmap=columnMap(headers,ss.columns);for(const col of ss.columns.filter(c=>c.required&&!cmap.has(c.key)))issues.push({severity:"error",code:"MISSING_COLUMN",sheet:ss.name,column:col.label,message:`Required column “${col.label}” is missing from ${ss.name}.`});const parsedRows:ParsedImportRow[]=[];const stableSet=new Set<string>();stableBySheet.set(ss.name,stableSet);
  rawRows.forEach((raw,index)=>{if(Object.values(raw).every(v=>!norm(v)))return;const rowIssues:ImportIssue[]=[];const values:Record<string,unknown>={};const rowRefs:{col:ImportColumnSchema;value:string}[]=[];
   for(const col of ss.columns){const source=cmap.get(col.key);const rawValue=source?raw[source]:"";try{const converted=convertImportValue(rawValue,col);values[col.key]=converted;if(col.required&&!norm(converted))rowIssues.push({severity:"error",code:"REQUIRED_VALUE",sheet:ss.name,row:index+2,column:col.label,message:`${col.label} is required.`});if(col.target==="stableId"&&norm(converted)){const id=norm(converted).toLowerCase();if(stableSet.has(id))rowIssues.push({severity:"error",code:"DUPLICATE_STABLE_ID",sheet:ss.name,row:index+2,column:col.label,message:`Stable ID “${converted}” is duplicated in ${ss.name}.`});const prior=globalStable.get(id);if(prior&&prior.sheet!==ss.name)rowIssues.push({severity:"error",code:"AMBIGUOUS_STABLE_ID",sheet:ss.name,row:index+2,column:col.label,message:`Stable ID “${converted}” is also used in ${prior.sheet} row ${prior.row}. Stable IDs must be unique across the workbook.`});stableSet.add(id);if(!prior)globalStable.set(id,{sheet:ss.name,row:index+2})}if(col.type==="reference"&&norm(converted))rowRefs.push({col,value:norm(converted)})}catch(e:any){rowIssues.push({severity:"error",code:"INVALID_VALUE",sheet:ss.name,row:index+2,column:col.label,message:`${col.label}: ${e.message}`})}}
   const parsed:ParsedImportRow={sheetKey:ss.key,sheetName:ss.name,rowNumber:index+2,values,raw,status:"valid",issues:rowIssues};parsed.status=rowIssues.some(i=>i.severity==="error")?"rejected":rowIssues.length?"warning":"valid";parsedRows.push(parsed);issues.push(...rowIssues);for(const r of rowRefs)refs.push({row:parsed,col:r.col,value:r.value});
  });sheets.push({schema:ss,rows:parsedRows,validRows:0,warningRows:0,rejectedRows:0});
 }
 for(const p of refs){const targets=p.col.referenceSheets?.length?[...p.col.referenceSheets]:p.col.referenceSheet?[p.col.referenceSheet]:[];if(!targets.length)continue;const found=targets.some(sheet=>stableBySheet.get(sheet)?.has(p.value.toLowerCase()));if(!found){const targetLabel=targets.join(" / ");const issue:ImportIssue={severity:"error",code:"UNRESOLVED_REFERENCE",sheet:p.row.sheetName,row:p.row.rowNumber,column:p.col.label,message:`Reference “${p.value}” was not found in ${targetLabel}.`};p.row.issues.push(issue);p.row.status="rejected";issues.push(issue)}}
 const known=new Set(schema.sheets.flatMap(s=>[normHeader(s.name),normHeader(workbookSheetNames.get(s.key)!) ]).concat(["readme","column_guide"]));for(const n of wb.SheetNames)if(!known.has(normHeader(n)))issues.push({severity:"warning",code:"UNKNOWN_SHEET",sheet:n,message:`Sheet “${n}” is not part of ${schema.version} and will be ignored.`});
 for(const s of sheets){s.validRows=s.rows.filter(r=>r.status==="valid").length;s.warningRows=s.rows.filter(r=>r.status==="warning").length;s.rejectedRows=s.rows.filter(r=>r.status==="rejected").length}const validRows=sheets.reduce((n,s)=>n+s.validRows,0),warningRows=sheets.reduce((n,s)=>n+s.warningRows,0),rejectedRows=sheets.reduce((n,s)=>n+s.rejectedRows,0);const canCommit=!issues.some(i=>i.severity==="error")&&validRows+warningRows>0;return {schema,fileName,issues,sheets,validRows,warningRows,rejectedRows,canCommit};
}
