"use client";
import {useLanguage} from "../lib/i18n";
import {useEffect,useMemo,useState} from "react";
import {Check,Clipboard,GitMerge,Link2,Plus,RefreshCw,Send,ShieldCheck,UsersRound,X} from "lucide-react";
import {commitFamilyIntakeBranch,createFamilyIntakeLink,createFamilyIntakeSession,decideFamilyIntakeMatch,fetchFamilyIntakeDashboard,revokeFamilyIntakeLink} from "../lib/remote";
import type {FamilyIntakeDashboard} from "../lib/family-intake-types";

const empty:FamilyIntakeDashboard={sessions:[],branches:[],people:[],candidates:[],conflicts:[],metrics:{links_opened:0,submissions:0,people_reported:0,branches_committed:0}};
export default function FamilyIntakeAdmin({familyName,onClose,onCommitted,onNotify}:{familyName:string;onClose:()=>void;onCommitted:()=>Promise<void>|void;onNotify:(m:string)=>void}){
 const {t:tr}=useLanguage();
 const [data,setData]=useState<FamilyIntakeDashboard>(empty),[busy,setBusy]=useState(false),[label,setLabel]=useState(""),[sessionTitle,setSessionTitle]=useState("Build our family together"),[rawLink,setRawLink]=useState(""),[error,setError]=useState("");
 const load=async()=>{try{setData(await fetchFamilyIntakeDashboard())}catch(e:any){setError(e.message||"Could not load family intake.")}};
 useEffect(()=>{load()},[]);
 const activeSession=data.sessions.find(s=>s.status!=="closed"&&s.status!=="completed")||data.sessions[0];
 const waiting=data.branches.filter(b=>b.status==="submitted");
 const peopleById=useMemo(()=>Object.fromEntries(data.people.map(p=>[p.id,p])),[data.people]);
 const createSession=async()=>{setBusy(true);setError("");try{await createFamilyIntakeSession(sessionTitle);await load();onNotify(tr("FamilyContributionIntakeCreatedTxt"))}catch(e:any){setError(e.message||"Could not create intake.")}finally{setBusy(false)}};
 const createLink=async()=>{if(!activeSession)return;setBusy(true);setError("");try{const token=await createFamilyIntakeLink(activeSession.id,label);const url=`${window.location.origin}/contribute/${token}`;setRawLink(url);setLabel("");await load();}catch(e:any){setError(e.message||"Could not create contribution link.")}finally{setBusy(false)}};
 const copy=async()=>{if(!rawLink)return;await navigator.clipboard.writeText(rawLink);onNotify(tr("ContributionLinkCopiedTxt"))};
 const decide=async(id:string,d:"same"|"different"|"not_sure")=>{setBusy(true);try{await decideFamilyIntakeMatch(id,d);await load()}catch(e:any){onNotify(e.message||"Could not save match decision.")}finally{setBusy(false)}};
 const commit=async(id:string)=>{setBusy(true);try{const r=await commitFamilyIntakeBranch(id);await load();await onCommitted();onNotify(`Branch added: ${r.created_people} new, ${r.matched_people} matched, ${r.relationships} relationships.`)}catch(e:any){onNotify(e.message||"Could not add this branch yet.")}finally{setBusy(false)}};
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="modal intake-admin-modal"><div className="modal-head"><div><span className="warm-kicker"><UsersRound size={13}/> {tr("S3A1BuildTogetherTxt")}</span><h2>{tr("CollectFamilyBranchesTxt")}</h2><p>{tr("ShareSimpleFormsFirstNothingEntersTxt")}{" "}{familyName} {tr("UntilYouReviewAndApproveItHereTxt")}</p></div><button className="icon-button" onClick={onClose}><X/></button></div>
   <div className="intake-admin-stats"><div><b>{data.metrics.links_opened}</b><span>{tr("LinkOpensTxt")}</span></div><div><b>{data.metrics.submissions}</b><span>{tr("BranchesSubmittedTxt")}</span></div><div><b>{data.metrics.people_reported}</b><span>{tr("PeopleReportedTxt")}</span></div><div><b>{data.metrics.branches_committed}</b><span>{tr("BranchesAddedTxt")}</span></div></div>
   {!activeSession?<div className="card intake-create-session"><h3>{tr("StartDistributedFamilyIntakeTxt")}</h3><p>{tr("CreateOneCollectionSessionThenMakeATxt")}</p><label><span>{tr("IntakeTitleTxt")}</span><input className="text-input" value={sessionTitle} onChange={e=>setSessionTitle(e.target.value)}/></label><button className="btn primary" disabled={busy} onClick={createSession}><Plus size={15}/> {tr("StartIntakeTxt")}</button></div>:<>
     <div className="card intake-share-box"><div><h3>{tr("Invite35BranchRepresentativesTxt")}</h3><p>{tr("UseASeparateLinkForEachPersonTxt")}</p></div><div className="intake-link-create"><input className="text-input" value={label} onChange={e=>setLabel(e.target.value)} placeholder={tr("EGRameshUnclePaternalBranchTxt")}/><button className="btn primary" disabled={busy} onClick={createLink}><Link2 size={15}/> {tr("CreateLinkTxt")}</button></div>{rawLink&&<div className="intake-generated-link"><input className="text-input" readOnly value={rawLink}/><button className="btn" onClick={copy}><Clipboard size={15}/> {tr("CopyTxt")}</button></div>}<div className="intake-privacy-note"><ShieldCheck/> {tr("SecureRandomTokensAreStoredOnlyAsTxt")}</div></div>
     <div className="intake-admin-section"><div className="section-title"><div><h3>{tr("BranchesTxt")}</h3><p className="page-subtitle">{tr("SubmittedBranchesStayStagedUntilYouApproveTxt")}</p></div><button className="btn small" onClick={load}><RefreshCw size={14}/> {tr("RefreshTxt")}</button></div>{data.branches.length===0?<div className="empty compact">{tr("CreateYourFirstRepresentativeLinkAboveTxt")}</div>:data.branches.map(b=>{const branchPeople=data.people.filter(p=>p.access_id===b.id);const branchCandidates=data.candidates.filter(c=>branchPeople.some(p=>p.id===c.staged_person_id)&&(c.status==="open"||c.status==="unsure"));return <div className={`card intake-branch-card ${b.status}`} key={b.id}><div className="intake-branch-head"><span><b>{b.representative_label||tr("FamilyRepresentativeTxt")}</b><small>{b.people_count} {tr("People3Txt")}{" "}{b.relationship_count} {tr("Relationships2Txt")}{" "}{b.status}</small></span>{b.status==="active"&&<button className="btn small" disabled={busy} onClick={async()=>{await revokeFamilyIntakeLink(b.id);await load()}}>{tr("RevokeTxt")}</button>}</div>{branchPeople.length>0&&<div className="intake-branch-people">{branchPeople.map(p=><span key={p.id}>{p.full_name}<small>{p.role_from_anchor?.replaceAll("_"," ")}{p.birth_year?` · ${p.birth_year}`:""}</small></span>)}</div>}{branchCandidates.length>0&&<div className="intake-match-review"><h4>{tr("PossibleOverlapsTxt")}</h4>{branchCandidates.map(c=>{const p=peopleById[c.staged_person_id];return <div className="intake-match-row" key={c.id}><div><b>{p?.full_name}</b><span>{tr("MayBeTxt")}{" "}<strong>{c.candidate_name}</strong></span><small>{c.score}{tr("ConfidenceTxt")}{" "}{c.confidence_band}{c.status==="unsure"?tr("MarkedNotSureTxt"):""}</small></div><div className="intake-match-actions"><button className="btn small" disabled={busy} onClick={()=>decide(c.id,"same")}><Check size={13}/> {tr("SameTxt")}</button><button className="btn small" disabled={busy} onClick={()=>decide(c.id,"different")}>{tr("DifferentTxt")}</button><button className="btn small" disabled={busy} onClick={()=>decide(c.id,"not_sure")}>{tr("NotSureTxt")}</button></div></div>})}</div>}{b.status==="submitted"&&<div className="intake-branch-commit"><button className="btn primary" disabled={busy||branchCandidates.some(c=>c.confidence_band!=="low")} onClick={()=>commit(b.id)}><GitMerge size={15}/> {tr("AddReviewedBranchToFamilyTxt")}</button>{branchCandidates.some(c=>c.confidence_band!=="low")&&<small>{tr("ResolveMediumHighPossibleOverlapsFirstLowTxt")}</small>}</div>}</div>})}</div>
   </>}
   {data.conflicts.length>0&&<div className="notice"><b>{data.conflicts.length} {tr("PreservedFactConflictTxt")}{data.conflicts.length>1?"s":""}.</b> {tr("ExistingFamilyFactsWereNotSilentlyOverwrittenTxt")}</div>}
   {error&&<div className="notice danger-text">{error}</div>}
   <div className="modal-actions"><button className="btn" onClick={onClose}>{tr("CloseTxt")}</button>{waiting.length>0&&<span className="intake-waiting"><Send size={14}/> {waiting.length} {tr("BranchTxt")}{waiting.length>1?tr("EsTxt"):""} {tr("WaitingTxt")}</span>}</div>
 </section></div>;
}
