"use client";
import {useEffect,useMemo,useState} from "react";
import {BadgeCheck,Compass,Eye,EyeOff,Search,ShieldCheck,Sparkles,Tags,UsersRound} from "lucide-react";
import {FEDERATED_APPLICATION_SCOPES,FEDERATED_SCOPE_GUARDRAILS,type FederatedScopeContext,type FederatedScopeProfile,type MyFederatedScopeProfile} from "../core/federation/application-scopes";
import {getFederatedScopeContexts,getMyFederatedScopeProfiles,saveFederatedScopeProfile,searchFederatedScopeProfiles,setFederatedScopeProfileActive} from "../capabilities/federation/application-scopes-remote";
import {useLanguage} from "../lib/i18n";

export default function FederatedPurposeScopeFramework(){
 const {t:tr}=useLanguage();
 const [contexts,setContexts]=useState<FederatedScopeContext[]>([]),[mine,setMine]=useState<MyFederatedScopeProfile[]>([]),[results,setResults]=useState<FederatedScopeProfile[]>([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
 const [contextKey,setContextKey]=useState(""),[scopeKey,setScopeKey]=useState("jobs"),[displayName,setDisplayName]=useState(""),[headline,setHeadline]=useState(""),[summary,setSummary]=useState(""),[location,setLocation]=useState(""),[tags,setTags]=useState(""),[contactMode,setContactMode]=useState("introduction_only"),[query,setQuery]=useState("");
 const load=async()=>{setLoading(true);try{const [c,m]=await Promise.all([getFederatedScopeContexts(),getMyFederatedScopeProfiles()]);setContexts(c);setMine(m);if(!contextKey&&c[0]){setContextKey(`${c[0].networkId}|${c[0].umbrellaId}|${c[0].scopeKey}`);setScopeKey(c[0].scopeKey)}}catch(e:any){setMessage(e.message||tr("NF5LoadFailedTxt"))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const chosen=useMemo(()=>contexts.find(c=>`${c.networkId}|${c.umbrellaId}|${c.scopeKey}`===contextKey)||null,[contexts,contextKey]);
 const scopes=useMemo(()=>Array.from(new Set(contexts.map(c=>c.scopeKey))).sort(),[contexts]);
 const save=async()=>{if(!chosen)return;setLoading(true);setMessage("");try{await saveFederatedScopeProfile({networkId:chosen.networkId,umbrellaId:chosen.umbrellaId,scopeKey:chosen.scopeKey,displayName,headline,summary,locationLabel:location,tags:tags.split(",").map(x=>x.trim()).filter(Boolean).slice(0,12),contactMode});setMessage(tr("NF5SavedTxt"));await load()}catch(e:any){setMessage(e.message||tr("NF5SaveFailedTxt"));setLoading(false)}};
 const search=async()=>{setLoading(true);setMessage("");try{setResults(await searchFederatedScopeProfiles(scopeKey,query))}catch(e:any){setMessage(e.message||tr("NF5SearchFailedTxt"))}finally{setLoading(false)}};
 const toggle=async(p:MyFederatedScopeProfile)=>{setLoading(true);try{await setFederatedScopeProfileActive(p.id,!p.active);await load()}catch(e:any){setMessage(e.message||tr("NF5UpdateFailedTxt"));setLoading(false)}};
 return <section className="card nf5-scope-card">
  <div className="nf5-head"><div><span className="warm-kicker"><Sparkles size={13}/> {tr("NF5KickerTxt")}</span><h2>{tr("NF5TitleTxt")}</h2><p>{tr("NF5DescTxt")}</p></div><span className="nf5-badge"><ShieldCheck size={14}/>{tr("NF5ExplicitOptInTxt")}</span></div>
  <div className="nf5-split"><article><h3>{tr("NF5PublishTitleTxt")}</h3><p>{tr("NF5PublishDescTxt")}</p><label>{tr("NF5ContextTxt")}<select value={contextKey} onChange={e=>{setContextKey(e.target.value);const c=contexts.find(x=>`${x.networkId}|${x.umbrellaId}|${x.scopeKey}`===e.target.value);if(c)setScopeKey(c.scopeKey)}}><option value="">{tr("NF5ChooseContextTxt")}</option>{contexts.map(c=><option key={`${c.networkId}-${c.umbrellaId}-${c.scopeKey}`} value={`${c.networkId}|${c.umbrellaId}|${c.scopeKey}`}>{c.networkName} → {c.umbrellaName} · {c.scopeKey}</option>)}</select></label><label>{tr("NF5DisplayNameTxt")}<input value={displayName} onChange={e=>setDisplayName(e.target.value)} /></label><label>{tr("NF5HeadlineTxt")}<input value={headline} onChange={e=>setHeadline(e.target.value)} /></label><label>{tr("NF5SummaryTxt")}<textarea value={summary} onChange={e=>setSummary(e.target.value)} /></label><div className="nf5-row"><label>{tr("NF5LocationTxt")}<input value={location} onChange={e=>setLocation(e.target.value)} /></label><label>{tr("NF5ContactModeTxt")}<select value={contactMode} onChange={e=>setContactMode(e.target.value)}><option value="introduction_only">{tr("NF5IntroductionOnlyTxt")}</option><option value="direct_request">{tr("NF5DirectRequestTxt")}</option></select></label></div><label>{tr("NF5TagsTxt")}<input value={tags} onChange={e=>setTags(e.target.value)} placeholder={tr("NF5TagsPlaceholderTxt")}/></label><button className="btn primary" onClick={()=>void save()} disabled={!chosen||!displayName.trim()||loading}>{tr("NF5PublishTxt")}</button></article>
   <article><h3>{tr("NF5MyOptInsTxt")}</h3><p>{tr("NF5MyOptInsDescTxt")}</p><div className="nf5-my-list">{mine.length===0?<small>{tr("NF5NoOptInsTxt")}</small>:mine.map(p=><div key={p.id}><span><b>{p.scopeKey}</b><small>{p.networkName} → {p.umbrellaName}</small></span><button className="btn" onClick={()=>void toggle(p)}>{p.active?<><EyeOff size={13}/>{tr("NF5WithdrawTxt")}</>:<><Eye size={13}/>{tr("NF5RepublishTxt")}</>}</button></div>)}</div></article></div>
  <div className="nf5-discovery"><div><h3>{tr("NF5DiscoveryTitleTxt")}</h3><p>{tr("NF5DiscoveryDescTxt")}</p></div><div className="nf5-search"><select value={scopeKey} onChange={e=>setScopeKey(e.target.value)}>{(scopes.length?scopes:FEDERATED_APPLICATION_SCOPES.map(s=>s.key)).map(s=><option key={s} value={s}>{s}</option>)}</select><div><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void search()}} placeholder={tr("NF5SearchPlaceholderTxt")}/></div><button className="btn primary" onClick={()=>void search()} disabled={loading}>{tr("NF5SearchTxt")}</button></div></div>
  <div className="nf5-results">{results.map(r=><article key={`${r.id}-${r.sourceNetworkId}`}><div className="nf5-person"><UsersRound size={17}/></div><div><small>{r.scopeKey} · {r.contactMode}</small><h4>{r.displayName}</h4><b>{r.headline||tr("NF5HeadlineFallbackTxt")}</b><p>{r.summary||tr("NF5SummaryFallbackTxt")}</p><div className="nf5-tags">{r.locationLabel&&<em><Compass size={10}/>{r.locationLabel}</em>}{r.tags.map(x=><em key={x}><Tags size={10}/>{x}</em>)}</div></div><aside><span><BadgeCheck size={12}/>{tr("NF5TrustReceiptTxt")}</span><b>{r.sourceNetworkName}</b><i>→</i><b>{r.umbrellaName}</b><i>→</i><b>{r.networkName}</b><small>{tr("NF5TrustReceiptHelpTxt")}</small></aside></article>)}</div>
  {message&&<div className="nf5-message">{message}</div>}
  <details className="nf5-guardrails"><summary><ShieldCheck size={15}/>{tr("NF5GuardrailsTxt")}</summary><div>{FEDERATED_SCOPE_GUARDRAILS.map(x=><p key={x}><b>✓</b>{x}</p>)}</div></details>
 </section>;
}
