"use client";
import {useLanguage} from "../lib/i18n";
import {useEffect,useMemo,useState} from "react";
import {Flag,FlaskConical,MessageSquareText,Radio,RefreshCw,Rocket,ShieldCheck,Sparkles,Trash2,UserPlus,Users,WandSparkles,Network,Palette,SlidersHorizontal,Settings2} from "lucide-react";
import {LaunchState} from "../lib/features";
import type {FeatureDefinition} from "../core/features/contracts";
import type {NetworkVerticalKind} from "../core/verticals/contracts";
import {getVerticalDefinition} from "../app-shell/vertical-registry";
import {getVerticalAppComposition} from "../app-shell/vertical-runtime";
import {addPlatformOwnerByEmail,applyAlphaDay1LaunchPreset,fetchPlatformNetworkTargets,fetchPlatformVerticalLaunchConsole,fetchPlatformOwnerAudit,fetchPlatformOwners,fetchPlatformRolloutAudit,fetchPlatformFamilyCreationRequests,reviewFamilyCreationRequest,fetchFamilyCreationPolicy,setFamilyCreationPolicy,fetchPlatformGuideFeedback,fetchGuideFeedbackSignals,updatePlatformGuideFeedbackStatus,PlatformGuideFeedback,fetchPlaygroundLaunchConsole,setPlaygroundFeatureVisibility,PlaygroundFeatureRow,PlatformFamilyCreationRequest,PlatformFamilyTarget,PlatformLaunchFeature,PlatformOwnerAuditRow,PlatformOwnerRow,PlatformRolloutAudit,removePlatformOwner,setPlatformVerticalBundleRollout,setPlatformFeatureRollout,fetchPlatformShowcaseVerticalSettings,setPlatformShowcaseVerticalSetting,getDefaultShowcaseVerticalSetting,ShowcaseVerticalSetting,ShowcasePaletteKey,fetchPlatformNetworkRegistry,fetchNetworkCreationPolicy,setNetworkCreationPolicy,reviewNetworkCreation,PlatformNetworkRegistryRow} from "../lib/remote";

const STATES:LaunchState[]=["hidden","test","pilot","released"];
const ACTIVE_VERTICALS:NetworkVerticalKind[]=["family","housing-society","family-association","association","alumni","organization","business-trust","franchise","professional"];
const stateHelp:Record<LaunchState,string>={hidden:"Nobody sees it.",test:"Only platform owners see it.",pilot:"Only selected pilot networks see it.",released:"Available to all eligible networks."};
type ConsoleSection="networks"|"showcase"|"rollout"|"governance";
type RegistryStatus="all"|"pending"|"approved"|"rejected";

export default function FounderLaunchConsole({onChanged,onNotify,initialVertical="family"}:{onChanged:()=>Promise<void>|void;onNotify:(message:string)=>void;initialVertical?:NetworkVerticalKind}){
 const {t:tr}=useLanguage();
 const [section,setSection]=useState<ConsoleSection>("networks");
 const [verticalKind,setVerticalKind]=useState<NetworkVerticalKind>(initialVertical);
 const [registryKind,setRegistryKind]=useState<"all"|NetworkVerticalKind>("all");
 const [registryStatus,setRegistryStatus]=useState<RegistryStatus>("all");
 const verticalDefinition=getVerticalDefinition(verticalKind);
 const FEATURE_REGISTRY=verticalDefinition.featureCatalog.features as readonly FeatureDefinition<string,string,string>[];
 const LAUNCH_COMPOSITION=getVerticalAppComposition(verticalKind).launch;
 const PLAYGROUND_EXCLUDED_BUNDLES=LAUNCH_COMPOSITION.playgroundExcludedBundles as readonly string[];
 const BUNDLES=LAUNCH_COMPOSITION.bundles as readonly {key:string;label:string;description:string}[];
 const [showcaseRows,setShowcaseRows]=useState<ShowcaseVerticalSetting[]>([]);
 const [rows,setRows]=useState<PlatformLaunchFeature[]>([]),[playgroundRows,setPlaygroundRows]=useState<PlaygroundFeatureRow[]>([]),[families,setFamilies]=useState<PlatformFamilyTarget[]>([]),[audit,setAudit]=useState<PlatformRolloutAudit[]>([]),[owners,setOwners]=useState<PlatformOwnerRow[]>([]),[ownerAudit,setOwnerAudit]=useState<PlatformOwnerAuditRow[]>([]),[creationRequests,setCreationRequests]=useState<PlatformFamilyCreationRequest[]>([]),[guideFeedback,setGuideFeedback]=useState<PlatformGuideFeedback[]>([]),[feedbackSignals,setFeedbackSignals]=useState<{guide_key:string;feedback_type:string;family_count:number;feedback_count:number}[]>([]),[approvalRequired,setApprovalRequiredState]=useState(true),[busy,setBusy]=useState(true),[pilotIds,setPilotIds]=useState<string[]>([]),[newOwnerEmail,setNewOwnerEmail]=useState(""),[networkRegistry,setNetworkRegistry]=useState<PlatformNetworkRegistryRow[]>([]),[networkApprovalRequired,setNetworkApprovalRequired]=useState(false);

 const load=async()=>{setBusy(true);try{const [features,playground,targets,history,ownerRows,ownerHistory,requests,policy,feedback,signals,showcase,registry,genericPolicy]=await Promise.all([fetchPlatformVerticalLaunchConsole(verticalKind),fetchPlaygroundLaunchConsole(),fetchPlatformNetworkTargets(),fetchPlatformRolloutAudit(20),fetchPlatformOwners(),fetchPlatformOwnerAudit(12),fetchPlatformFamilyCreationRequests(),fetchFamilyCreationPolicy(),fetchPlatformGuideFeedback(),fetchGuideFeedbackSignals(),fetchPlatformShowcaseVerticalSettings().catch(()=>[]),fetchPlatformNetworkRegistry().catch(()=>[]),fetchNetworkCreationPolicy().catch(()=>false)]);setShowcaseRows(showcase);setRows(features);setPlaygroundRows(playground);setFamilies(targets.filter(target=>!target.vertical_kind||target.vertical_kind===verticalKind));setAudit(history);setOwners(ownerRows);setOwnerAudit(ownerHistory);setCreationRequests(requests);setApprovalRequiredState(policy);setGuideFeedback(feedback);setFeedbackSignals(signals);setNetworkRegistry(registry);setNetworkApprovalRequired(genericPolicy)}catch(e:any){onNotify(e.message||"Could not load Launch Control.")}finally{setBusy(false)}};
 useEffect(()=>{void load()},[verticalKind]);

 const byKey=useMemo(()=>Object.fromEntries(rows.map(r=>[r.feature_key,r])) as Record<string,PlatformLaunchFeature>,[rows]);
 const playgroundByKey=useMemo(()=>new Map(playgroundRows.map(r=>[r.feature_key,r] as const)),[playgroundRows]);
 const pendingCount=useMemo(()=>networkRegistry.filter(r=>r.approval_status==="pending").length,[networkRegistry]);
 const approvedCount=useMemo(()=>networkRegistry.filter(r=>r.approval_status==="approved").length,[networkRegistry]);
 const registryRows=useMemo(()=>networkRegistry.filter(row=>(registryKind==="all"||row.vertical_kind===registryKind)&&(registryStatus==="all"||row.approval_status===registryStatus)),[networkRegistry,registryKind,registryStatus]);
 const registryCount=(kind:NetworkVerticalKind)=>networkRegistry.filter(r=>r.vertical_kind===kind).length;
 const registryPending=(kind:NetworkVerticalKind)=>networkRegistry.filter(r=>r.vertical_kind===kind&&r.approval_status==="pending").length;

 const togglePilot=(id:string)=>setPilotIds(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const saveFeature=async(key:string,state:LaunchState,announce=false,pilotOverride?:string[])=>{const targets=pilotOverride??pilotIds;if(state==="pilot"&&targets.length===0){onNotify(tr("SelectAtLeastOnePilotNetworkFirstTxt"));return}setBusy(true);try{await setPlatformFeatureRollout(key,state,state==="pilot"?targets:[],announce);await load();await onChanged();onNotify(`${FEATURE_REGISTRY.find(f=>f.key===key)?.label||key} is now ${state}.`)}catch(e:any){onNotify(e.message||"Could not change feature rollout.")}finally{setBusy(false)}};
 const saveBundle=async(bundle:string,state:LaunchState,announce=false)=>{if(state==="pilot"&&pilotIds.length===0){onNotify(tr("SelectAtLeastOnePilotNetworkFirstTxt"));return}setBusy(true);try{const changed=await setPlatformVerticalBundleRollout(verticalKind,bundle,state,state==="pilot"?pilotIds:[],announce);await load();await onChanged();onNotify(`${changed} feature${changed===1?"":"s"} moved to ${state}.`)}catch(e:any){onNotify(e.message||"Could not change bundle rollout.")}finally{setBusy(false)}};
 const addOwner=async()=>{if(!newOwnerEmail.trim())return;setBusy(true);try{await addPlatformOwnerByEmail(newOwnerEmail);setNewOwnerEmail("");await load();onNotify(tr("LaunchControlAccessGrantedTxt"))}catch(e:any){onNotify(e.message||"Could not add platform owner.")}finally{setBusy(false)}};
 const removeOwner=async(row:PlatformOwnerRow)=>{if(row.is_me){onNotify(tr("ForSafetyAskAnotherPlatformOwnerToTxt"));return}setBusy(true);try{await removePlatformOwner(row.user_id);await load();onNotify(tr("LaunchControlAccessRemovedTxt"))}catch(e:any){onNotify(e.message||"Could not remove platform owner.")}finally{setBusy(false)}};
 const applyDay1=async()=>{setBusy(true);try{const changed=await applyAlphaDay1LaunchPreset();setPilotIds([]);await load();await onChanged();onNotify(changed?`Day-1 Alpha preset applied to ${changed} feature${changed===1?"":"s"}.`:"Day-1 Alpha preset is already active.")}catch(e:any){onNotify(e.message||"Could not apply the Day-1 Alpha preset.")}finally{setBusy(false)}};
 const reviewCreation=async(row:PlatformFamilyCreationRequest,action:"approve"|"reject")=>{setBusy(true);try{await reviewFamilyCreationRequest(row.id,action);await load();onNotify(action==="approve"?`${row.name} approved. The requester is now Family Owner.`:`${row.name} request rejected.`)}catch(e:any){onNotify(e.message||"Could not review family request.")}finally{setBusy(false)}};
 const toggleCreationPolicy=async(next:boolean)=>{setBusy(true);try{await setFamilyCreationPolicy(next);setApprovalRequiredState(next);onNotify(next?"Family creation approval is now required.":"Alpha auto-approval is ON. Signed-in users can create families immediately.")}catch(e:any){onNotify(e.message||"Could not change family creation policy.")}finally{setBusy(false)}};
 const toggleNetworkApprovalPolicy=async(next:boolean)=>{setBusy(true);try{await setNetworkCreationPolicy(next);setNetworkApprovalRequired(next);setApprovalRequiredState(next);onNotify(tr("NetworkCreationPolicyUpdatedTxt"))}catch(e:any){onNotify(e.message||"Could not change network approval policy.")}finally{setBusy(false)}};
 const reviewNetwork=async(row:PlatformNetworkRegistryRow,action:"approve"|"reject")=>{setBusy(true);try{await reviewNetworkCreation(row.network_id,action);await load();onNotify(action==="approve"?tr("NetworkApprovedTxt"):tr("NetworkRejectedTxt"))}catch(e:any){onNotify(e.message||"Could not review network.")}finally{setBusy(false)}};
 const togglePlayground=async(key:string,enabled:boolean)=>{setBusy(true);try{await setPlaygroundFeatureVisibility(key,enabled);setPlaygroundRows(v=>v.map(r=>r.feature_key===key?{...r,enabled}:r));onNotify(`${FEATURE_REGISTRY.find(f=>f.key===key)?.label||key} ${enabled?"shown":"hidden"} in Playground.`)}catch(e:any){onNotify(e.message||"Could not change Playground visibility.")}finally{setBusy(false)}};
 const saveShowcaseRow=async(row:ShowcaseVerticalSetting)=>{setBusy(true);try{await setPlatformShowcaseVerticalSetting(row);setShowcaseRows(v=>v.map(x=>x.vertical_kind===row.vertical_kind?row:x));onNotify(`${getVerticalDefinition(row.vertical_kind).displayName} showcase settings updated.`)}catch(e:any){onNotify(e.message||"Could not update showcase settings. Apply migration 099 first.")}finally{setBusy(false)}};
 const updateShowcaseRow=(kind:NetworkVerticalKind,patch:Partial<ShowcaseVerticalSetting>)=>{const current=showcaseRows.find(x=>x.vertical_kind===kind)||getDefaultShowcaseVerticalSetting(kind);void saveShowcaseRow({...current,...patch})};
 const setFeedbackStatus=async(id:string,status:string)=>{setBusy(true);try{await updatePlatformGuideFeedbackStatus(id,status);await load();onNotify(tr("FeedbackStatusUpdatedRoadmapFilesWereNotTxt"))}catch(e:any){onNotify(e.message||"Could not update feedback status.")}finally{setBusy(false)}};
 const setAllPlayground=async(enabled:boolean)=>{setBusy(true);try{for(const feature of FEATURE_REGISTRY.filter(f=>!PLAYGROUND_EXCLUDED_BUNDLES.includes(f.bundle)&&playgroundByKey.has(f.key)))await setPlaygroundFeatureVisibility(feature.key,enabled);await load();onNotify(enabled?"All available member-facing Playground features are visible.":"All available member-facing Playground features are hidden.")}catch(e:any){onNotify(e.message||"Could not update Playground visibility.")}finally{setBusy(false)}};

 const verticalSwitcher=<div className="vertical-launch-switch card"><div className="vertical-launch-options">{ACTIVE_VERTICALS.map(kind=><button key={kind} className={verticalKind===kind?"active":""} onClick={()=>{setPilotIds([]);setVerticalKind(kind)}}>{getVerticalDefinition(kind).displayName}</button>)}</div><span>{verticalDefinition.displayName} {tr("RolloutAndPlaygroundControlsTxt")}</span></div>;

 return <div className="founder-launch-console founder-console-v2">
  <div className="founder-launch-hero"><div><span className="warm-kicker"><Rocket size={13}/> {tr("PlatformOwnerTxt")}</span><h1>{tr("LaunchControlTxt")}</h1><p>{tr("LC2IntroDescTxt")}</p></div><button className="btn" onClick={load} disabled={busy}><RefreshCw size={15}/> {tr("RefreshTxt")}</button></div>

  <nav className="founder-console-tabs card" aria-label={tr("LC2SectionsAriaTxt")}>
   <button className={section==="networks"?"active":""} onClick={()=>setSection("networks")}><Network size={17}/><span><b>{tr("LC2NetworksApprovalsTxt")}</b><small>{pendingCount} {tr("LC2PendingTxt")} · {networkRegistry.length} {tr("LC2TotalTxt")}</small></span></button>
   <button className={section==="showcase"?"active":""} onClick={()=>setSection("showcase")}><Palette size={17}/><span><b>{tr("LC2ShowcaseTxt")}</b><small>{tr("LC2ShowcaseDescTxt")}</small></span></button>
   <button className={section==="rollout"?"active":""} onClick={()=>setSection("rollout")}><SlidersHorizontal size={17}/><span><b>{tr("LC2FeatureRolloutTxt")}</b><small>{tr("LC2FeatureRolloutDescTxt")}</small></span></button>
   <button className={section==="governance"?"active":""} onClick={()=>setSection("governance")}><Settings2 size={17}/><span><b>{tr("LC2GovernanceTxt")}</b><small>{tr("LC2GovernanceDescTxt")}</small></span></button>
  </nav>

  {section==="networks"&&<>
   <section className="founder-summary-grid">
    <article className="card founder-summary-card"><small>{tr("LC2CreatedNetworksTxt")}</small><b>{networkRegistry.length}</b><span>{tr("LC2AcrossTxt")} {ACTIVE_VERTICALS.filter(k=>registryCount(k)>0).length} {tr("LC2VerticalsTxt")}</span></article>
    <article className="card founder-summary-card attention"><small>{tr("LC2PendingApprovalTxt")}</small><b>{pendingCount}</b><span>{networkApprovalRequired?"Manual approval is enabled":"Auto-approval is enabled"}</span></article>
    <article className="card founder-summary-card"><small>{tr("LC2ApprovedTxt")}</small><b>{approvedCount}</b><span>{tr("LC2AvailableMembersTxt")}</span></article>
   </section>

   <section className="card network-registry-panel">
    <div className="section-title registry-title"><div><span className="warm-kicker"><ShieldCheck size={13}/> {tr("LC2PlatformRegistryTxt")}</span><h2>{tr("NetworkRegistryApprovalsTxt")}</h2><p className="page-subtitle">{tr("LC2RegistryDescTxt")}</p></div><label className="living-setting founder-policy-toggle"><span><b>{networkApprovalRequired?tr("ManualApprovalNetworksTxt"):tr("AutoApproveNetworksTxt")}</b><small>{networkApprovalRequired?tr("ManualApprovalNetworksDescTxt"):tr("AutoApproveNetworksDescTxt")}</small></span><input type="checkbox" checked={networkApprovalRequired} disabled={busy} onChange={e=>toggleNetworkApprovalPolicy(e.target.checked)}/></label></div>
    <div className={`notice ${networkApprovalRequired?"":"success-notice"}`}><b>{networkApprovalRequired?"Manual review mode":"Auto-approval mode"}.</b> {networkApprovalRequired?"New networks wait here before becoming visible to normal members.":"New networks should activate immediately and still remain visible in this registry."}</div>

    <div className="registry-toolbar">
     <div className="registry-vertical-tabs" role="tablist" aria-label={tr("LC2NetworkVerticalsTxt")}>
      <button className={registryKind==="all"?"active":""} onClick={()=>setRegistryKind("all")}><span>{tr("LC2AllTxt")}</span><em>{networkRegistry.length}</em>{pendingCount>0&&<i>{pendingCount}</i>}</button>
      {ACTIVE_VERTICALS.map(kind=>{const count=registryCount(kind),pending=registryPending(kind);return <button key={kind} className={registryKind===kind?"active":""} onClick={()=>setRegistryKind(kind)}><span>{getVerticalDefinition(kind).displayName}</span><em>{count}</em>{pending>0&&<i>{pending}</i>}</button>})}
     </div>
     <select className="select registry-status-filter" value={registryStatus} onChange={e=>setRegistryStatus(e.target.value as RegistryStatus)}><option value="all">{tr("LC2AllStatusesTxt")}</option><option value="pending">{tr("LC2PendingTxt")}</option><option value="approved">{tr("LC2ApprovedTxt")}</option><option value="rejected">{tr("LC2RejectedTxt")}</option></select>
    </div>

    {registryRows.length===0?<div className="empty compact">{tr("LC2NoRegistryMatchesTxt")}</div>:<div className="registry-table-wrap"><table className="registry-table"><thead><tr><th>{tr("LC2NetworkTxt")}</th><th>{tr("LC2CreatorTxt")}</th><th>{tr("LC2CreatedTxt")}</th><th>{tr("LC2MembersTxt")}</th><th>{tr("LC2StatusTxt")}</th><th>{tr("LC2ActionsTxt")}</th></tr></thead><tbody>{registryRows.map(row=><tr key={row.network_id}><td><b>{row.name}</b><small>{getVerticalDefinition(row.vertical_kind).displayName}</small></td><td>{row.creator_email||tr("UnknownAccountTxt")}</td><td>{new Date(row.created_at).toLocaleString()}</td><td>{row.member_count}</td><td><span className={`status ${row.approval_status}`}>{row.approval_status}</span></td><td><div className="registry-row-actions">{row.approval_status==="pending"?<><button className="btn small" disabled={busy} onClick={()=>reviewNetwork(row,"reject")}>{tr("RejectNetworkTxt")}</button><button className="btn primary small" disabled={busy} onClick={()=>reviewNetwork(row,"approve")}>{tr("ApproveNetworkTxt")}</button></>:<span className="registry-no-action">—</span>}</div></td></tr>)}</tbody></table></div>}
   </section>
  </>}

  {section==="showcase"&&<>
   <section className="card showcase-network-control"><div className="section-title"><div><span className="warm-kicker"><Sparkles size={13}/> {tr("ShowcaseLaunchKickerTxt")}</span><h2>{tr("ShowcaseLaunchTitleTxt")}</h2><p className="page-subtitle">{tr("LC2ShowcaseControlDescTxt")}</p></div></div>
    <div className="showcase-network-grid">{ACTIVE_VERTICALS.map(kind=>{const row=showcaseRows.find(x=>x.vertical_kind===kind);const value=row||getDefaultShowcaseVerticalSetting(kind);return <article className="showcase-network-row" key={kind}><div><b>{getVerticalDefinition(kind).displayName}</b><small>{row?tr("ShowcaseFounderControlledTxt"):value.create_enabled||value.playground_enabled?tr("ShowcaseDefaultEditableTxt"):tr("ShowcaseHiddenDefaultEditableTxt")}</small></div><label><span>{tr("ShowcaseCreateLabelTxt")}</span><input type="checkbox" checked={value.create_enabled} disabled={busy||!row} onChange={e=>updateShowcaseRow(kind,{create_enabled:e.target.checked})}/></label><label><span>{tr("ShowcasePlaygroundLabelTxt")}</span><input type="checkbox" checked={value.playground_enabled} disabled={busy||!row} onChange={e=>updateShowcaseRow(kind,{playground_enabled:e.target.checked})}/></label><label><span>{tr("ShowcaseFeaturedLabelTxt")}</span><input type="checkbox" checked={value.featured} disabled={busy||!row} onChange={e=>updateShowcaseRow(kind,{featured:e.target.checked})}/></label><div className={`showcase-palette-picker palette-preview-${value.palette_key}`}><span className="showcase-palette-swatches" aria-hidden="true"><i/><i/><i/></span><select className="select" value={value.palette_key} disabled={busy||!row} onChange={e=>updateShowcaseRow(kind,{palette_key:e.target.value as ShowcasePaletteKey})}><option value="signature">{tr("ShowcasePaletteSignatureTxt")}</option><option value="warm">{tr("ShowcasePaletteWarmTxt")}</option><option value="modern">{tr("ShowcasePaletteModernTxt")}</option><option value="classic">{tr("ShowcasePaletteClassicTxt")}</option><option value="minimal">{tr("ShowcasePaletteMinimalTxt")}</option></select></div></article>})}</div>
   </section>
   {verticalSwitcher}
   <section className="card playground-feature-control"><div className="section-title"><div><span className="warm-kicker"><FlaskConical size={13}/> {tr("PlaygroundShowcaseTxt")}</span><h2>{LAUNCH_COMPOSITION.playgroundTitle}</h2><p className="page-subtitle">{tr("LC2PlaygroundFineTuneTxt")}</p></div><div className="card-actions"><button className="btn small" disabled={busy} onClick={()=>setAllPlayground(false)}>{tr("HideAllTxt")}</button><button className="btn primary small" disabled={busy} onClick={()=>setAllPlayground(true)}>{tr("ShowAllTxt")}</button></div></div><div className="family-feature-list">{FEATURE_REGISTRY.filter(f=>!PLAYGROUND_EXCLUDED_BUNDLES.includes(f.bundle)).map(feature=>{const row=playgroundByKey.get(feature.key);const backendReady=Boolean(row);const loading=busy&&playgroundRows.length===0;const enabled=row?.enabled===true;return <div className="admin-setting" key={feature.key}><span><b>{feature.label}</b><small>{feature.description} · {loading?tr("LoadingPlaygroundRegistryTxt"):backendReady?tr("PlaygroundOnlyTxt"):tr("DatabaseUpdateRequiredBeforeThisControlCanTxt")}</small></span><input type="checkbox" checked={enabled} disabled={busy||!backendReady} onChange={e=>togglePlayground(feature.key,e.target.checked)}/></div>})}</div></section>
  </>}

  {section==="rollout"&&<>
   {verticalSwitcher}
   <div className="launch-rule card"><ShieldCheck/><div><b>{tr("ReleasePrecedenceTxt")}</b><span>{tr("FounderRolloutNetworkMemberSettingExperienceLevelTxt")}</span></div></div>
   {verticalKind==="family"&&<section className="card alpha-preset"><div><span className="warm-kicker"><WandSparkles size={13}/> {tr("FirstFamilyReleaseTxt")}</span><h2>{LAUNCH_COMPOSITION.dayOneTitle}</h2><p>{LAUNCH_COMPOSITION.dayOneDescription}</p></div><button className="btn" type="button" disabled={busy} onClick={applyDay1}><WandSparkles size={15}/> {tr("ApplySafeDay1PresetTxt")}</button></section>}
   <section className="card pilot-targets"><div className="section-title"><div><h2>{LAUNCH_COMPOSITION.pilotTargetsTitle}</h2><p className="page-subtitle">{LAUNCH_COMPOSITION.pilotTargetsDescription}</p></div><span className="role-pill member">{pilotIds.length} {tr("SelectedTxt")}</span></div><div className="pilot-family-grid">{families.length===0?<div className="empty compact">{tr("NoNetworksForThisVerticalAreAvailableTxt")}</div>:families.map(f=><label key={f.network_id} className={`pilot-family ${pilotIds.includes(f.network_id)?"selected":""}`}><input type="checkbox" checked={pilotIds.includes(f.network_id)} onChange={()=>togglePilot(f.network_id)}/><span><b>{f.name}</b><small>/{f.slug} · {f.member_count} {tr("ActiveAccountTxt")}{f.member_count===1?"":"s"}</small></span></label>)}</div></section>
   <div className="launch-legend">{STATES.map(state=><span key={state} className={`launch-state ${state}`}><i/>{state}<small>{stateHelp[state]}</small></span>)}</div>
   <div className="launch-bundles">{BUNDLES.map(bundle=>{const defs=FEATURE_REGISTRY.filter(f=>f.bundle===bundle.key);const states=defs.map(d=>byKey[d.key]?.rollout_state||d.defaultLaunch);const common=states.every(x=>x===states[0])?states[0]:null;return <section className="card launch-bundle" key={bundle.key}><div className="launch-bundle-head"><div><span className="warm-kicker"><Flag size={13}/> {bundle.label}</span><h2>{bundle.label}</h2><p>{bundle.description}</p></div><div className="bundle-actions"><select className="select" value={common||""} disabled={busy} onChange={e=>e.target.value&&saveBundle(bundle.key,e.target.value as LaunchState,false)}><option value="" disabled>{tr("MixedTxt")}</option>{STATES.map(state=><option key={state} value={state}>{state}</option>)}</select><button className="btn small" disabled={busy||!(common==="pilot"||common==="released")} onClick={()=>common&&saveBundle(bundle.key,common,true)}><Radio size={14}/> {tr("AnnounceTxt")}</button></div></div><div className="launch-feature-list">{defs.map(def=>{const row=byKey[def.key];const backendReady=Boolean(row);const loading=busy&&rows.length===0;const state=row?.rollout_state||def.defaultLaunch;return <div className="launch-feature-row" key={def.key}><div><b>{def.label}</b><small>{def.description}{loading?tr("LoadingLaunchRegistryTxt"):backendReady?"":tr("DatabaseUpdateRequiredTxt")}</small></div><span className={`launch-state compact ${state}`}>{state}</span><select className="select" value={state} disabled={busy||!backendReady} onChange={e=>saveFeature(def.key,e.target.value as LaunchState,false)}>{STATES.map(s=><option key={s} value={s}>{s}</option>)}</select><button className="icon-button" title={backendReady?"Announce this feature as new":"Apply pending database migrations first"} disabled={busy||!backendReady||!(state==="pilot"||state==="released")} onClick={()=>saveFeature(def.key,state,true,row?.pilot_network_ids||[])}><FlaskConical size={15}/></button></div>})}</div></section>})}</div>
   <section className="card rollout-history"><div className="section-title"><div><h2>{tr("RecentRolloutActivityTxt")}</h2><p className="page-subtitle">{tr("AFounderOnlyAuditTrailOfFeatureTxt")}</p></div></div>{audit.length===0?<div className="empty compact">{tr("NoRolloutChangesRecordedYetTxt")}</div>:audit.map(item=><div className="rollout-history-row" key={item.id}><span><b>{FEATURE_REGISTRY.find(f=>f.key===item.feature_key)?.label||item.feature_key}</b><small>{new Date(item.changed_at).toLocaleString()} · {item.bundle_key}{item.announced?tr("AnnouncedTxt"):""}</small></span><em>{item.previous_state} → {item.new_state}</em></div>)}</section>
  </>}

  {section==="governance"&&<>
   <section className="card platform-owners"><div className="section-title"><div><h2>{tr("WhoCanControlLaunchesTxt")}</h2><p className="page-subtitle">{tr("LaunchControlBelongsToPlatformOwnersNotTxt")}</p></div><span className="role-pill member">{owners.length} {tr("Owner2Txt")}{owners.length===1?"":"s"}</span></div><div className="owner-add-row"><input className="text-input" type="email" value={newOwnerEmail} onChange={e=>setNewOwnerEmail(e.target.value)} placeholder={tr("TrustedOwnerExampleComTxt")} aria-label={tr("PlatformOwnerEmailTxt")}/><button className="btn primary" type="button" disabled={busy||!newOwnerEmail.trim()} onClick={addOwner}><UserPlus size={15}/> {tr("AddOwnerTxt")}</button></div><div className="platform-owner-list">{owners.map(row=><div className="platform-owner-row" key={row.user_id}><span><b>{row.email||tr("AccountWithoutEmailTxt")}</b><small>{row.is_me?tr("You2Txt"):""}{tr("LaunchControlAccessSinceTxt")} {new Date(row.created_at).toLocaleDateString()}</small></span><button className="icon-button danger" type="button" disabled={busy||row.is_me||owners.length<=1} onClick={()=>removeOwner(row)}><Trash2 size={15}/></button></div>)}</div><div className="notice"><b>{tr("SafetyTxt")}</b> {tr("TheDatabaseRefusesToRemoveTheFinalTxt")}</div>{ownerAudit.length>0&&<details className="owner-audit"><summary>{tr("RecentOwnerAccessChangesTxt")}</summary>{ownerAudit.map(row=><div className="rollout-history-row" key={row.id}><span><b>{row.target_email||tr("UnknownAccountTxt")}</b><small>{new Date(row.created_at).toLocaleString()} {tr("ByTxt")} {row.actor_email||tr("PreviousOwnerTxt")}</small></span><em>{row.action}</em></div>)}</details>}</section>

   {verticalKind==="family"&&<section className="card guide-feedback-triage"><div className="section-title"><div><h2>{tr("FamilyFeedbackIntelligenceTxt")}</h2><p className="page-subtitle">{tr("StructuredProductFeedbackAcrossGuidesAndScreensTxt")}</p></div><span className="role-pill member"><MessageSquareText size={12}/> {guideFeedback.filter(x=>x.status==="new").length} {tr("NewTxt")}</span></div>{feedbackSignals.length>0&&<div className="feedback-signal-grid">{feedbackSignals.slice(0,6).map(s=><div key={`${s.guide_key}-${s.feedback_type}`}><b>{s.family_count} {tr("LC2FamiliesTxt")}</b><span>{s.feedback_type.replaceAll("_"," ")} · {s.guide_key||"general"}</span><small>{s.feedback_count} {tr("LC2ResponsesTxt")}</small></div>)}</div>}<div className="feedback-triage-list">{guideFeedback.slice(0,30).map(f=><article key={f.id}><div><span className="warm-kicker">{f.feedback_type.replaceAll("_"," ")} · {f.guide_key||f.screen||"general"}</span><p>{f.message||tr("QuickHelpfulnessSignalTxt")}</p><small>{new Date(f.created_at).toLocaleString()} · {f.role||"member"}</small></div><select value={f.status} disabled={busy} onChange={e=>setFeedbackStatus(f.id,e.target.value)}><option value="new">{tr("LC2NewTxt")}</option><option value="reviewing">{tr("LC2ReviewingTxt")}</option><option value="planned">{tr("LC2PlannedTxt")}</option><option value="already_supported">{tr("LC2AlreadySupportedTxt")}</option><option value="not_planned">{tr("LC2NotPlannedTxt")}</option><option value="implemented">{tr("LC2ImplementedTxt")}</option></select></article>)}{guideFeedback.length===0&&<div className="empty">{tr("NoGuideFeedbackYetTxt")}</div>}</div></section>}

   {creationRequests.length>0&&<section className="card family-creation-approvals"><div className="section-title"><div><h2>{tr("LC2LegacyFamilyRequestsTxt")}</h2><p className="page-subtitle">{tr("LC2LegacyFamilyRequestsDescTxt")}</p></div><label className="living-setting founder-policy-toggle"><span><b>{approvalRequired?"Legacy approval required":"Legacy auto-approval"}</b><small>{tr("LC2LegacyPolicyAuthoritativeTxt")}</small></span><input type="checkbox" checked={approvalRequired} disabled={busy} onChange={e=>toggleCreationPolicy(e.target.checked)}/></label></div><div className="family-creation-request-list">{creationRequests.slice(0,20).map(row=><div className="family-creation-review-row" key={row.id}><span><b>{row.name}</b><small>{row.requester_email||tr("UnknownAccountTxt")} · {new Date(row.created_at).toLocaleString()}</small>{row.description&&<em>{row.description}</em>}</span><div className="family-creation-review-actions"><span className={`status ${row.status}`}>{row.status}</span>{row.status==="pending"&&<><button className="btn small" disabled={busy} onClick={()=>reviewCreation(row,"reject")}>{tr("RejectTxt")}</button><button className="btn primary small" disabled={busy} onClick={()=>reviewCreation(row,"approve")}>{tr("ApproveFamilyTxt")}</button></>}</div></div>)}</div></section>}
  </>}

  <div className="card launch-footnote"><Users/><div><b>{tr("LC2OneControlPlaneTxt")}</b><span>{tr("LC2ControlPlaneDescTxt")}</span></div></div>
 </div>;
}
