"use client";
import {useEffect,useMemo,useState} from "react";
import {BadgeCheck,Check,Handshake,LockKeyhole,MessageCircle,Send,ShieldCheck,X} from "lucide-react";
import {GOVERNED_INTRODUCTION_GUARDRAILS,type FederatedIntroduction,type IntroductionRouteCandidate} from "../core/federation/governed-introductions";
import {cancelFederatedIntroduction,getMyFederatedIntroductions,getShortlistedIntroductionRoutes,requestFederatedIntroduction,respondToFederatedIntroduction} from "../capabilities/federation/governed-introductions-remote";
import {useLanguage} from "../lib/i18n";

export default function GovernedFederatedIntroductions(){
 const {t}=useLanguage();
 const [routes,setRoutes]=useState<IntroductionRouteCandidate[]>([]),[items,setItems]=useState<FederatedIntroduction[]>([]),[routeId,setRouteId]=useState(""),[alias,setAlias]=useState(""),[message,setMessage]=useState(""),[contact,setContact]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const [responseNotes,setResponseNotes]=useState<Record<string,string>>({}),[responseContacts,setResponseContacts]=useState<Record<string,string>>({});
 const selected=useMemo(()=>routes.find(x=>x.routeId===routeId)||null,[routes,routeId]);
 const load=async()=>{setBusy(true);try{const [r,i]=await Promise.all([getShortlistedIntroductionRoutes(),getMyFederatedIntroductions()]);setRoutes(r);setItems(i);if(!routeId&&r[0])setRouteId(r[0].routeId)}catch(e:any){setNotice(e.message||t("NF7LoadFailedTxt"))}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 const send=async()=>{if(!selected||alias.trim().length<2||message.trim().length<3||contact.trim().length<3)return;setBusy(true);try{await requestFederatedIntroduction({routeId:selected.routeId,requesterAlias:alias,message,contactNote:contact});setMessage("");setContact("");setNotice(t("NF7RequestedTxt"));await load()}catch(e:any){setNotice(e.message||t("NF7RequestFailedTxt"));setBusy(false)}};
 const respond=async(item:FederatedIntroduction,accept:boolean)=>{setBusy(true);try{await respondToFederatedIntroduction({introductionId:item.id,accept,responseNote:responseNotes[item.id]||"",contactNote:accept?(responseContacts[item.id]||""):""});setNotice(accept?t("NF7AcceptedTxt"):t("NF7DeclinedTxt"));await load()}catch(e:any){setNotice(e.message||t("NF7RespondFailedTxt"));setBusy(false)}};
 const cancel=async(id:string)=>{setBusy(true);try{await cancelFederatedIntroduction(id);setNotice(t("NF7CancelledTxt"));await load()}catch(e:any){setNotice(e.message||t("NF7CancelFailedTxt"));setBusy(false)}};
 const inbound=items.filter(x=>x.direction==="inbound"),outbound=items.filter(x=>x.direction==="outbound");
 return <section className="card nf7-intro-card">
  <div className="nf7-head"><div><span className="warm-kicker"><Handshake size={13}/>{t("NF7KickerTxt")}</span><h2>{t("NF7TitleTxt")}</h2><p>{t("NF7DescTxt")}</p></div><span className="nf7-badge"><LockKeyhole size={14}/>{t("NF7ConsentBadgeTxt")}</span></div>
  <div className="nf7-compose"><div><h3>{t("NF7CreateTitleTxt")}</h3><p>{t("NF7CreateDescTxt")}</p><label>{t("NF7RouteTxt")}<select value={routeId} onChange={e=>setRouteId(e.target.value)}><option value="">{t("NF7ChooseRouteTxt")}</option>{routes.map(r=><option key={r.routeId} value={r.routeId}>{r.requestTitle} · {r.targetDisplayName} · {r.targetNetworkName}</option>)}</select></label>{selected&&<div className="nf7-route-preview"><b>{selected.targetDisplayName}</b><small>{selected.targetHeadline||t("NF7ParticipantFallbackTxt")} · {selected.score} {t("NF7MatchTxt")}</small><span><ShieldCheck size={11}/>{selected.trustPathLabel}</span></div>}<label>{t("NF7AliasTxt")}<input value={alias} onChange={e=>setAlias(e.target.value)} placeholder={t("NF7AliasPlaceholderTxt")}/></label><label>{t("NF7MessageTxt")}<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder={t("NF7MessagePlaceholderTxt")}/></label><label>{t("NF7ContactTxt")}<input value={contact} onChange={e=>setContact(e.target.value)} placeholder={t("NF7ContactPlaceholderTxt")}/><small>{t("NF7ContactHelpTxt")}</small></label><button className="btn primary" disabled={!selected||alias.trim().length<2||message.trim().length<3||contact.trim().length<3||busy} onClick={()=>void send()}><Send size={13}/>{t("NF7RequestIntroTxt")}</button></div>
   <aside><ShieldCheck size={18}/><b>{t("NF7BoundaryTitleTxt")}</b><p>{t("NF7BoundaryDescTxt")}</p></aside></div>
  <div className="nf7-columns"><article><div className="nf7-section-head"><div><h3>{t("NF7InboundTxt")}</h3><p>{t("NF7InboundDescTxt")}</p></div><span>{inbound.length}</span></div><div className="nf7-list">{inbound.length===0?<small>{t("NF7NoInboundTxt")}</small>:inbound.map(i=><div className={`nf7-item ${i.status}`} key={i.id}><div className="nf7-item-head"><span><b>{i.requesterAlias}</b><small>{i.scopeKey} · {i.targetNetworkName}</small></span><em>{i.status}</em></div><p><MessageCircle size={12}/>{i.message}</p><div className="nf7-trust"><BadgeCheck size={12}/><span><b>{t("NF7TrustReceiptTxt")}</b><small>{i.trustPathLabel}</small></span></div>{i.status==="pending"&&<><label>{t("NF7ResponseNoteTxt")}<textarea value={responseNotes[i.id]||""} onChange={e=>setResponseNotes(v=>({...v,[i.id]:e.target.value}))}/></label><label>{t("NF7YourContactTxt")}<input value={responseContacts[i.id]||""} onChange={e=>setResponseContacts(v=>({...v,[i.id]:e.target.value}))} placeholder={t("NF7YourContactPlaceholderTxt")}/><small>{t("NF7YourContactHelpTxt")}</small></label><div className="nf7-actions"><button className="btn primary" onClick={()=>void respond(i,true)} disabled={busy}><Check size={12}/>{t("NF7AcceptTxt")}</button><button className="btn" onClick={()=>void respond(i,false)} disabled={busy}><X size={12}/>{t("NF7DeclineTxt")}</button></div></>}{i.status==="accepted"&&<div className="nf7-unlocked"><LockKeyhole size={12}/><span><b>{t("NF7ConnectionUnlockedTxt")}</b>{i.requesterContactNote&&<small>{t("NF7RequesterContactTxt")}: {i.requesterContactNote}</small>}{i.targetContactNote&&<small>{t("NF7YourSharedContactTxt")}: {i.targetContactNote}</small>}{i.targetResponseNote&&<small>{i.targetResponseNote}</small>}</span></div>}</div>)}</div></article>
   <article><div className="nf7-section-head"><div><h3>{t("NF7OutboundTxt")}</h3><p>{t("NF7OutboundDescTxt")}</p></div><span>{outbound.length}</span></div><div className="nf7-list">{outbound.length===0?<small>{t("NF7NoOutboundTxt")}</small>:outbound.map(i=><div className={`nf7-item ${i.status}`} key={i.id}><div className="nf7-item-head"><span><b>{i.targetDisplayName}</b><small>{i.targetHeadline||i.targetNetworkName}</small></span><em>{i.status}</em></div><p>{i.message}</p><div className="nf7-trust"><BadgeCheck size={12}/><span><b>{t("NF7TrustReceiptTxt")}</b><small>{i.trustPathLabel}</small></span></div>{i.status==="pending"&&<button className="btn" onClick={()=>void cancel(i.id)} disabled={busy}>{t("NF7CancelTxt")}</button>}{i.status==="accepted"&&<div className="nf7-unlocked"><LockKeyhole size={12}/><span><b>{t("NF7ConnectionUnlockedTxt")}</b>{i.targetContactNote&&<small>{t("NF7TargetContactTxt")}: {i.targetContactNote}</small>}{i.requesterContactNote&&<small>{t("NF7YourSharedContactTxt")}: {i.requesterContactNote}</small>}{i.targetResponseNote&&<small>{i.targetResponseNote}</small>}</span></div>}</div>)}</div></article></div>
  {notice&&<div className="nf7-message">{notice}</div>}
  <details className="nf7-guardrails"><summary><ShieldCheck size={15}/>{t("NF7GuardrailsTxt")}</summary><div>{GOVERNED_INTRODUCTION_GUARDRAILS.map(x=><p key={x}><b>✓</b>{x}</p>)}</div></details>
 </section>;
}
