"use client";
import {useLanguage} from "../lib/i18n";
import {useMemo,useState} from "react";
import {ArrowRight,BookOpen,ChevronDown,ChevronUp,Compass,Heart,Lightbulb,PlayCircle,Search,ShieldCheck,Sparkles,Users,UserRound,Waypoints} from "lucide-react";
import type {GuideAudience,GuideEntry} from "../lib/guide-types";
import {FUTURE_INTERESTS,GUIDE_ENTRIES,GUIDE_GOALS,GUIDE_SECTIONS,IDEAS_FOR_FAMILY,PERSONAS,guideVisibleTo,searchGuides} from "../lib/user-guide-content";
import GuideFeedback from "./GuideFeedback";
import ResponsiveSectionTabs from "./shared/ResponsiveSectionTabs";
import {submitGuideFeedback} from "../lib/remote";

type Props={audience:GuideAudience;experience:string;demo:boolean;featureVisible:(key:string)=>boolean;initialKey?:string;onOpenFeature:(action?:string)=>void;onTryPlayground:(key?:string)=>void;onNotify:(s:string)=>void};
const statusLabel=(s:GuideEntry["status"])=>s==="live"?"Live":s==="live_verify"?"Live · verify deployment":s==="partial"?"Partial":"Being explored";
export default function GuidePortal({audience,experience,demo,featureVisible,initialKey,onOpenFeature,onTryPlayground,onNotify}:Props){
 const {t:tr}=useLanguage();
 const visible=useMemo(()=>GUIDE_ENTRIES.filter(e=>guideVisibleTo(e,audience,featureVisible)),[audience,featureVisible]);
 const [query,setQuery]=useState(""),[selected,setSelected]=useState(initialKey||""),[personaOpen,setPersonaOpen]=useState<string>(""),[mode,setMode]=useState<"overview"|"library"|"privacy">(initialKey?"library":"overview"),[overviewSection,setOverviewSection]=useState<"discover"|"people"|"build"|"ideas">("discover");
 const results=useMemo(()=>searchGuides(query,visible),[query,visible]);
 const selectedEntry=visible.find(e=>e.key===selected);
 const openEntry=(key:string)=>{setSelected(key);setMode("library");window.setTimeout(()=>document.getElementById("guide-detail")?.scrollIntoView({behavior:"smooth",block:"start"}),20)};
 return <div className="guide-portal">
  <section className="guide-hero">
   <div><span className="warm-kicker"><Compass size={14}/> {tr("ExploreGuideTxt")}</span><h1>{tr("YourFamilyIsMoreThanATreeTxt")}</h1><p>{tr("FamilyNetworkIsAPrivateLivingFamilyTxt")}</p><div className="guide-pillars"><span><Waypoints/>{tr("KnowYourFamilyTxt")}</span><span><Heart/>{tr("RememberYourStoryTxt")}</span><span><Users/>{tr("StayConnectedTxt")}</span><span><Sparkles/>{tr("BuildItTogetherTxt")}</span></div></div>
   <div className="guide-hero-note"><b>{tr("PowerfulUnderneathEffortlessOnTheSurfaceTxt")}</b><span>{tr("UseTheGuideByGoalByFeatureTxt")}</span></div>
  </section>

  <div className="guide-search-wrap"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={tr("TryAddMyMotherFindCousinsImportTxt")} aria-label={tr("SearchFamilyNetworkGuideTxt")}/>{query&&<button className="btn small" onClick={()=>setQuery("")}>{tr("ClearTxt")}</button>}</div>
  {query&&<section className="guide-search-results"><div className="section-title"><div><h2>{tr("GuideSearchTxt")}</h2><p className="page-subtitle">{tr("FastDeterministicHelpAcrossTheProductGuideTxt")}</p></div></div>{results.length===0?<div className="empty">{tr("NoExactGuideMatchYetTryATxt")}</div>:<div className="guide-result-list">{results.map(e=><button key={e.key} onClick={()=>openEntry(e.key)}><span><b>{e.title}</b><small>{e.summary}</small></span><ArrowRight size={16}/></button>)}</div>}</section>}

  {!query&&<>
   <section><div className="section-title"><div><h2>{tr("WhatBringsYouHereTxt")}</h2><p className="page-subtitle">{tr("StartFromWhatYouWantNotFromTxt")}</p></div></div><div className="guide-path-grid">
    <button onClick={()=>{setMode("overview");setOverviewSection("discover")}}><Sparkles/><b>{tr("IMNewShowMeWhatThisTxt")}</b><span>{tr("SeeRealFamilyStoriesAndUseCasesTxt")}</span></button>
    <button onClick={()=>openEntry("add-myself")}><Users/><b>{tr("IWantToBuildMyFamilyTxt")}</b><span>{tr("StartSmallInviteOthersOrImportATxt")}</span></button>
    <button onClick={()=>setMode("library")}><BookOpen/><b>{tr("IWantToUnderstandAFeatureTxt")}</b><span>{tr("BrowseTheCompleteModuleLibraryTxt")}</span></button>
    <button onClick={()=>{setMode("overview");setOverviewSection("people")}}><Lightbulb/><b>{tr("INeedHelpWithSomethingTxt")}</b><span>{tr("ChooseAGoalInNormalEverydayLanguageTxt")}</span></button>
   </div></section>

   <nav className="guide-subnav" aria-label={tr("GuideSectionsTxt")}><button className={mode==="overview"?"active":""} onClick={()=>setMode("overview")}>{tr("ExploreEverythingTxt")}</button><button className={mode==="library"?"active":""} onClick={()=>setMode("library")}>{tr("ModuleLibraryTxt")}</button><button className={mode==="privacy"?"active":""} onClick={()=>{setMode("privacy");setSelected("privacy-trust")}}>{tr("PrivacyAndTrustTxt")}</button></nav>

   {mode==="overview"&&<section className="section-workspace" data-ui-progressive="workspace" data-testid="qa-family-guide-workspace"><ResponsiveSectionTabs active={overviewSection} onChange={setOverviewSection} label="Family guide overview sections" options={[{id:"discover",label:"Discover",description:"What Family Network is and how families use it"},{id:"people",label:"People & goals",description:"Value by generation and everyday goals"},{id:"build",label:"Build together",description:"A practical activation path for family owners"},{id:"ideas",label:"Ideas & future",description:"Prompts, hidden capabilities, what is new and ideas being explored"}]}/><div className="section-workspace-stage">
    {overviewSection==="discover"&&<><section className="guide-story card"><span className="warm-kicker">{tr("WhatIsFamilyNetworkTxt")}</span><h2>{tr("ALivingFamilySpaceNotAStaticTxt")}</h2><p>{tr("ATreeCanShowNamesAndLinesTxt")}</p><div className="guide-value-grid"><div><b>{tr("KnowTxt")}</b><span>{tr("UnderstandPeopleGenerationsAndRelationshipPathsTxt")}</span></div><div><b>{tr("RememberTxt")}</b><span>{tr("PreservePhotosStoriesLifeEventsAndOriginsTxt")}</span></div><div><b>{tr("ConnectTxt")}</b><span>{tr("CelebrateMomentsFindRelativesAndUseTrustedTxt")}</span></div><div><b>{tr("CompoundTxt")}</b><span>{tr("EveryVerifiedProfileRelationshipAndMemoryMakesTxt")}</span></div></div></section>

    <section><div className="section-title"><div><h2>{tr("ImagineYourFamilyUsingThisTxt")}</h2><p className="page-subtitle">{tr("TheProductBecomesMeaningfulWhenItCreatesTxt")}</p></div></div><div className="guide-story-grid">{[tr("GrandmaRecordsAStoryAboutGrandpaTxt"),tr("AYoungRelativeMovesToAnotherCityTxt"),tr("ANewlyMarriedPersonLearnsALargeTxt"),tr("RelativesIdentifyPeopleInAnOldPhotoTxt"),tr("AReunionBecomesAPermanentFamilyMemoryTxt"),tr("ChildrenExploreGreatGrandparentsAndFamilyOriginsTxt"),tr("SomeoneFindsATrustedProfessionalOrMentorTxt"),tr("AFamilySeeksARespectfulOptInTxt")].map(x=><article className="card" key={x}><Heart size={18}/><p>{x}</p></article>)}</div></section>
    </>}

    {overviewSection==="people"&&<><section id="guide-personas"><div className="section-title"><div><h2>{tr("FamilyNetworkForPeopleLikeMeTxt")}</h2><p className="page-subtitle">{tr("DifferentGenerationsShouldFindDifferentValueWithoutTxt")}</p></div></div><div className="persona-list">{PERSONAS.map(p=><article className="card persona-card" key={p.title}><button className="persona-head" onClick={()=>setPersonaOpen(personaOpen===p.title?"":p.title)}><UserRound size={17}/><span><b>{p.title}</b><small>{p.care}</small></span>{personaOpen===p.title?<ChevronUp/>:<ChevronDown/>}</button>{personaOpen===p.title&&<div className="persona-body"><b>{tr("UsefulCapabilitiesTxt")}</b><div className="chip-row">{p.capabilities.map(x=><span className="role-pill member" key={x}>{x}</span>)}</div><b>{tr("SampleJourneyTxt")}</b><p>{p.journey}</p></div>}</article>)}</div></section>

    <section id="guide-goals"><div className="section-title"><div><h2>{tr("WhatDoYouWantToDoTxt")}</h2><p className="page-subtitle">{tr("UsersThinkInGoalsNotFeatureNamesTxt")}</p></div></div><div className="guide-goal-grid">{GUIDE_GOALS.map(([goal,key])=><button key={goal} onClick={()=>openEntry(key)}><span>{goal}</span><ArrowRight size={15}/></button>)}</div></section>
    </>}

    {overviewSection==="ideas"&&<section><div className="section-title"><div><h2>{tr("IdeasForYourFamilyTxt")}</h2><p className="page-subtitle">{tr("SmallPromptsThatCanTurnAnEmptyTxt")}</p></div></div><div className="ideas-grid">{Object.entries(IDEAS_FOR_FAMILY).map(([title,ideas])=><article className="card" key={title}><h3>{title}</h3>{ideas.map(x=><p key={x}>• {x}</p>)}</article>)}</div></section>}

    {overviewSection==="build"&&<><section className="card owner-playbook"><div className="section-title"><div><h2>{tr("FamilyOwnerPlaybookTxt")}</h2><p className="page-subtitle">{tr("APracticalPathFromEmptyFamilyToTxt")}</p></div></div><ol>{[tr("SetupCreateFamilyTxt"),tr("AddYourselfTxt"),tr("AddClosestRelativesTxt"),tr("Invite35PeopleTxt"),tr("ImportTheLargerFamilyIfAvailableTxt"),tr("ReviewSubmissionsCorrectionsTxt"),tr("AddMeaningfulMemoriesTxt"),tr("PreserveFamilyHistoryTxt"),tr("EncourageProfileCompletionTxt"),tr("AddOrganizeAGatheringTxt"),tr("ReviewFamilyActivityTxt"),tr("ConnectToTheWiderCommunityWhenUsefulTxt")].map(x=><li key={x}>{x}</li>)}</ol></section>

    <section className="card first-seven"><div className="section-title"><div><h2>{tr("First7StepsTxt")}</h2><p className="page-subtitle">{tr("AGentleActivationJourneyProgressNotPressureTxt")}</p></div></div><div className="seven-step-grid">{[tr("KnowYourFamilyTxt"),tr("CompleteYourselfTxt"),tr("PreserveOneMemoryTxt"),tr("InviteOneRelativeTxt"),tr("DiscoverFamilyHistoryTxt"),tr("HelpCompleteOneFamilyDetailTxt"),tr("ShareSomethingMeaningfulTxt")].map((x,i)=><div key={x}><b>{i+1}</b><span>{x}</span></div>)}</div></section>
    </>}

    {overviewSection==="ideas"&&<><section><div className="section-title"><div><h2>{tr("ThingsYouMayNotKnowFamilyNetworkTxt")}</h2></div></div><div className="surprise-grid">{[tr("ExplainRelationshipToMeTxt"),tr("SwitchBetweenPersonalAndFullLineageTxt"),tr("PreserveDeceasedRelativeStoriesAndHistoryTxt"),tr("SearchByProfessionOrCityTxt"),tr("ShowFamilyGeographicSpreadTxt"),tr("UseGovernedCorrectionRequestsTxt"),tr("SupportMultipleFamilyNetworksTxt"),tr("ExploreCommunityWithoutExposingThePrivateTreeTxt"),tr("ExplainTrustedFamilyPathsTxt"),tr("ShareAMemoryDigestWithoutSharingTheTxt")].map(x=><div className="card" key={x}><Sparkles size={16}/><span>{x}</span></div>)}</div></section>

    <section><div className="section-title"><div><h2>{tr("WhatsNewTxt")}</h2><p className="page-subtitle">{tr("UserFacingDiscoveriesNotTechnicalChangelogsTxt")}</p></div></div><div className="guide-story-grid"><article className="card"><Waypoints/><h3>{tr("TrustedIntroductions2Txt")}</h3><p>{tr("UseExplicitFamilyTrustPathsAndConsentTxt")}</p><button className="text-action" onClick={()=>openEntry("introductions")}>{tr("LearnMoreTxt")}{" "}<ArrowRight size={13}/></button></article><article className="card"><Heart/><h3>{tr("QuietFamilyDigest2Txt")}</h3><p>{tr("CatchUpOnMeaningfulFamilyActivityWithoutTxt")}</p><button className="text-action" onClick={()=>openEntry("digest")}>{tr("LearnMoreTxt")}{" "}<ArrowRight size={13}/></button></article></div></section>

    <section><div className="section-title"><div><h2>{tr("BeingExploredTxt")}</h2><p className="page-subtitle">{tr("IdeasWeMayExploreInterestIsATxt")}</p></div></div><div className="future-grid">{FUTURE_INTERESTS.map(x=><article className="card" key={x}><b>{x}</b><button className="btn small" onClick={async()=>{if(demo){onNotify(tr("SignInToRegisterProductInterestTxt"));return}try{await submitGuideFeedback({guide_key:"future-roadmap",screen:"guide:future",feedback_type:"future_interest",message:x,role:audience,experience_mode:experience,app_version:"S2-E"});onNotify(tr("ThanksYourInterestWasRecordedAsATxt"))}catch(e:any){onNotify(e.message||tr("CouldNotRecordInterestTxt"))}}}>{tr("IDUseThisTxt")}</button></article>)}</div></section>
    </>}
    </div></section>}

   {(mode==="library"||mode==="privacy")&&<section className="guide-library"><div className="guide-library-nav">{GUIDE_SECTIONS.filter(s=>visible.some(e=>e.section===s.key)).map(s=><div key={s.key}><h3>{s.label}</h3>{visible.filter(e=>e.section===s.key).map(e=><button className={selected===e.key?"active":""} key={e.key} onClick={()=>setSelected(e.key)}>{e.title}<small>{statusLabel(e.status)}</small></button>)}</div>)}</div><div className="guide-library-main" id="guide-detail">{selectedEntry?<GuideDetail entry={selectedEntry} onOpenFeature={onOpenFeature} onTryPlayground={onTryPlayground} onOpen={openEntry} role={audience} experience={experience} demo={demo} onNotify={onNotify}/>:<div className="card empty-guide"><BookOpen size={30}/><h2>{tr("ChooseAFeatureTxt")}</h2><p>{tr("EveryGuideUsesTheSameStructuredProductTxt")}</p></div>}</div></section>}
   {mode==="privacy"&&!selectedEntry&&<GuideDetail entry={visible.find(e=>e.key==="privacy-trust")!} onOpenFeature={onOpenFeature} onTryPlayground={onTryPlayground} onOpen={openEntry} role={audience} experience={experience} demo={demo} onNotify={onNotify}/>} 
  </>}
 </div>;
}

function GuideDetail({entry,onOpenFeature,onTryPlayground,onOpen,role,experience,demo,onNotify}:{entry:GuideEntry;onOpenFeature:(a?:string)=>void;onTryPlayground:(k?:string)=>void;onOpen:(k:string)=>void;role:GuideAudience;experience:string;demo:boolean;onNotify:(s:string)=>void}){
 const {t:tr}=useLanguage();
 return <article className="guide-detail card"><div className="guide-detail-head"><div><span className={`guide-status ${entry.status}`}>{statusLabel(entry.status)}</span><h1>{entry.title}</h1><p>{entry.summary}</p></div><BookOpen size={26}/></div><div className="guide-detail-section"><h3>{tr("WhatIsItTxt")}</h3><p>{entry.summary}</p></div><div className="guide-detail-section"><h3>{tr("WhyUseItTxt")}</h3><p>{entry.why}</p></div><div className="guide-detail-section"><h3>{tr("HowToUseItTxt")}</h3><ol>{entry.steps.map(x=><li key={x}>{x}</li>)}</ol></div><div className="guide-detail-section"><h3>{tr("ExamplesAndIdeasTxt")}</h3>{entry.examples.map(x=><p key={x}>• {x}</p>)}{entry.ideas?.map(x=><p key={x}>• {x}</p>)}</div><div className="guide-two-col"><div className="guide-detail-section"><h3>{tr("WhoCanDoWhatTxt")}</h3><p>{entry.permissions}</p></div><div className="guide-detail-section"><h3>{tr("PrivacyTxt")}</h3><p>{entry.privacy}</p></div></div>{entry.faq&&<div className="guide-detail-section"><h3>{tr("CommonQuestionsTxt")}</h3>{entry.faq.map(x=><details key={x.q}><summary>{x.q}</summary><p>{x.a}</p></details>)}</div>}{entry.troubleshooting&&<div className="guide-detail-section"><h3>{tr("TroubleshootingAndRecoveryTxt")}</h3>{entry.troubleshooting.map(x=><p key={x}>• {x}</p>)}</div>}{entry.related&&<div className="guide-detail-section"><h3>{tr("RelatedFeaturesTxt")}</h3><div className="chip-row">{entry.related.map(k=><button className="role-pill member" key={k} onClick={()=>onOpen(k)}>{GUIDE_ENTRIES.find(e=>e.key===k)?.title||k}</button>)}</div></div>}<div className="card-actions guide-detail-actions">{entry.action&&<button className="btn primary" onClick={()=>onOpenFeature(entry.action)}>{tr("OpenThisFeatureTxt")}{" "}<ArrowRight size={14}/></button>}{entry.playground&&<button className="btn" onClick={()=>onTryPlayground(entry.key)}><PlayCircle size={14}/> {tr("TryInPlaygroundNoSaveTxt")}</button>}</div><GuideFeedback guideKey={entry.key} screen={`guide:${entry.key}`} role={role} experience={experience} demo={demo} onNotify={onNotify}/></article>;
}
