"use client";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,ArrowRight,Building2,CalendarClock,CalendarDays,CheckCircle2,ClipboardList,CreditCard,DoorOpen,FileText,Landmark,LoaderCircle,ShieldCheck,UsersRound,Wrench} from "lucide-react";
import type {NetworkAffiliatedEntity,NetworkActivity} from "../core/network-os/contracts";
import {fetchHsOpsSnapshot,type HsOpsSnapshot} from "../verticals/housing-society/runtime/operations-remote";
import {fetchHsFinanceSnapshot,type HsFinanceSnapshot} from "../verticals/housing-society/runtime/finance-remote";
import {fetchHsGovernanceSnapshot,type HsGovernanceSnapshot} from "../verticals/housing-society/runtime/governance-remote";
import {fetchHsSecuritySnapshot,type HsSecuritySnapshot} from "../verticals/housing-society/runtime/security-remote";
import {useLanguage} from "../lib/i18n";

type Target="me"|"directory"|"notices"|"complaints"|"amenities"|"maintenance"|"governance"|"security"|"community"|"explorer";
const EMPTY_OPS:HsOpsSnapshot={notices:[],complaints:[],vendors:[],amenities:[],bookings:[]};
const EMPTY_FINANCE:HsFinanceSnapshot={chargeHeads:[],cycles:[],bills:[],funds:[],budget:[],summary:{totalBilled:0,totalCollected:0,totalOutstanding:0,overdueBills:0}};
const EMPTY_GOV:HsGovernanceSnapshot={terms:[],meetings:[],actions:[],resolutions:[],documents:[]};
const EMPTY_SECURITY:HsSecuritySnapshot={isSecurityOperator:false,visitors:[],staff:[],moveRequests:[],renovations:[],assets:[],compliance:[],emergencyContacts:[]};
const DEMO_OPS:HsOpsSnapshot={
 notices:[
  {id:"n1",title:"Water tank cleaning · Sunday 10 AM–2 PM",body:"Water supply will pause during the maintenance window.",noticeType:"urgent",pinned:true,createdAt:"2026-09-11T08:00:00+05:30"},
  {id:"n2",title:"AGM on 27 September at Clubhouse",body:"Annual report, budget and proposed resolutions are ready for owners.",noticeType:"general",pinned:true,createdAt:"2026-09-10T08:00:00+05:30"},
  {id:"n3",title:"EV charging pilot registration open",body:"Residents with EVs can register interest for designated parking bays.",noticeType:"general",pinned:false,createdAt:"2026-09-09T08:00:00+05:30"},
 ],
 complaints:[
  {id:"c1",category:"Lift",title:"Cedar B lift vibration",description:"Kone inspection assigned.",priority:"high",status:"in_progress",createdAt:"2026-09-10T12:00:00+05:30",updatedAt:"2026-09-11T10:00:00+05:30"},
  {id:"c2",category:"Electrical",title:"Street light near Aster gate not working",priority:"medium",status:"open",createdAt:"2026-09-11T07:00:00+05:30",updatedAt:"2026-09-11T07:00:00+05:30"},
  {id:"c3",category:"Civil",title:"Seepage near Maple basement parking",priority:"high",status:"in_progress",createdAt:"2026-09-09T09:00:00+05:30",updatedAt:"2026-09-11T11:00:00+05:30"},
 ],
 vendors:[{id:"v1",name:"Kone Elevators",category:"Lift Maintenance",status:"active",contractCount:1},{id:"v2",name:"SecureGate Services",category:"Security",status:"active",contractCount:1},{id:"v3",name:"GreenLeaf Facility Management",category:"Housekeeping",status:"active",contractCount:1}],
 amenities:[{id:"a1",name:"Clubhouse Hall",location:"Clubhouse",capacity:80,bookingMode:"approval",status:"active"},{id:"a2",name:"Badminton Court",location:"Sports Zone",capacity:8,bookingMode:"instant",status:"active"},{id:"a3",name:"Guest Room 1",location:"Clubhouse",capacity:4,bookingMode:"approval",status:"active"},{id:"a4",name:"Terrace Party Deck",location:"Aster Terrace",capacity:50,bookingMode:"approval",status:"active"}],
 bookings:[{id:"b1",amenityId:"a1",amenityName:"Clubhouse Hall",unitEntityId:"demo-unit-aster-a-804",unitLabel:"Aster-A-804",startsAt:"2026-09-12T18:00:00+05:30",endsAt:"2026-09-12T22:00:00+05:30",status:"confirmed",purpose:"Birthday celebration"},{id:"b2",amenityId:"a2",amenityName:"Badminton Court",unitEntityId:"demo-unit-cedar-b-504",unitLabel:"Cedar-B-504",startsAt:"2026-09-12T20:00:00+05:30",endsAt:"2026-09-12T21:00:00+05:30",status:"confirmed",purpose:"Resident game"}],
};
const DEMO_FINANCE:HsFinanceSnapshot={...EMPTY_FINANCE,cycles:[{id:"cycle1",label:"September 2026",periodStart:"2026-09-01",periodEnd:"2026-09-30",dueOn:"2026-09-15",status:"issued",graceDays:5,penaltyRateMonthly:1.5}],funds:[{id:"f1",code:"OPERATING",label:"Operating Fund",openingBalance:480000,currentBalance:612000,visibility:"members"},{id:"f2",code:"SINKING",label:"Sinking Fund",openingBalance:1850000,currentBalance:2025000,visibility:"members"},{id:"f3",code:"REPAIR",label:"Major Repair Fund",openingBalance:925000,currentBalance:1010000,visibility:"members"}],summary:{totalBilled:381600,totalCollected:344500,totalOutstanding:37100,overdueBills:7}};
const DEMO_GOV:HsGovernanceSnapshot={terms:[{id:"t1",label:"Committee 2026-27",startsOn:"2026-04-01",status:"active",assignments:[{id:"a1",personEntityId:"p1",personLabel:"Sanjay Mehta",roleKey:"chairperson",startsOn:"2026-04-01"},{id:"a2",personEntityId:"p2",personLabel:"Anita Shah",roleKey:"secretary",startsOn:"2026-04-01"},{id:"a3",personEntityId:"p3",personLabel:"Vivek Kulkarni",roleKey:"treasurer",startsOn:"2026-04-01"}]}],meetings:[{id:"m1",meetingType:"agm",title:"Annual General Meeting",scheduledAt:"2026-09-27T18:30:00+05:30",location:"Clubhouse",status:"scheduled",agenda:[]}],actions:[{id:"ac1",title:"Collect lift AMC quotations",ownerLabel:"Secretary",dueOn:"2026-09-15",status:"in_progress"},{id:"ac2",title:"Complete Cedar CCTV replacement comparison",ownerLabel:"Security Portfolio",dueOn:"2026-09-18",status:"open"},{id:"ac3",title:"Publish AGM annual report",ownerLabel:"Treasurer",dueOn:"2026-09-20",status:"open"}],resolutions:[{id:"r1",resolutionNumber:"RES-014",title:"Approve EV charging pilot",body:"Controlled EV charging pilot.",voteMode:"approval",status:"passed",quorumPercent:0,yesCount:5,noCount:1,abstainCount:0,myVote:null},{id:"r2",resolutionNumber:"RES-016",title:"Revise clubhouse booking deposit",body:"Review refundable deposit.",voteMode:"approval",status:"open",quorumPercent:0,yesCount:0,noCount:0,abstainCount:0,myVote:null}],documents:[]};
const DEMO_SECURITY:HsSecuritySnapshot={isSecurityOperator:false,visitors:[{id:"v1",unitLabel:"Aster-A-804",visitorName:"Rajesh Kulkarni",visitType:"guest",expectedAt:"2026-09-12T19:45:00+05:30",status:"expected"},{id:"v2",unitLabel:"Cedar-B-704",visitorName:"UrbanFix Technician",visitType:"service",expectedAt:"2026-09-12T16:00:00+05:30",status:"inside"},{id:"v3",unitLabel:"Maple-C-603",visitorName:"Food Delivery",visitType:"delivery",expectedAt:"2026-09-12T20:10:00+05:30",status:"expected"}],staff:[{id:"s1",fullName:"Savita Kamble",staffType:"househelp",status:"active",unitLabels:["Aster-A-804","Aster-A-903"]}],moveRequests:[{id:"m1",unitLabel:"B-304",moveType:"move_in",scheduledOn:"2026-09-15",status:"approved"}],renovations:[{id:"r1",unitLabel:"A-402",title:"Kitchen renovation",startsOn:"2026-09-10",status:"approved",nocReference:"NOC-2026-17"}],assets:[{id:"as1",assetCode:"DG-125",name:"Diesel Generator 125 KVA",category:"Power",location:"Utility Block",status:"active",nextServiceOn:"2026-10-10"},{id:"as2",assetCode:"LIFT-CB2",name:"Cedar Lift B2",category:"Lift",location:"Cedar",status:"attention",nextServiceOn:"2026-09-12"},{id:"as3",assetCode:"CCTV-CEDAR",name:"Cedar CCTV NVR",category:"Security",location:"Security Room",status:"replacement_planned",nextServiceOn:"2026-09-20"}],compliance:[{id:"co1",category:"Fire Safety",title:"Fire equipment inspection",dueOn:"2026-09-30",status:"open",visibility:"members"},{id:"co2",category:"Water",title:"Water quality test",dueOn:"2026-09-18",status:"open",visibility:"members"}],emergencyContacts:[{id:"e1",category:"Emergency",label:"Society Security",phone:"020-40000000",priority:1}]};

const money=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value||0);
const dateLabel=(value?:string|null)=>{if(!value)return "—";try{return new Date(value).toLocaleDateString(undefined,{day:"numeric",month:"short"})}catch{return value}};

export default function HousingSocietyHome({networkName,entities,activities,demo,isAdmin,onGo}:{networkName:string;entities:NetworkAffiliatedEntity[];activities:NetworkActivity[];demo:boolean;isAdmin:boolean;onGo:(target:Target)=>void}){
 const {t}=useLanguage();
 const [ops,setOps]=useState<HsOpsSnapshot>(demo?DEMO_OPS:EMPTY_OPS);
 const [finance,setFinance]=useState<HsFinanceSnapshot>(demo?DEMO_FINANCE:EMPTY_FINANCE);
 const [governance,setGovernance]=useState<HsGovernanceSnapshot>(demo?DEMO_GOV:EMPTY_GOV);
 const [security,setSecurity]=useState<HsSecuritySnapshot>(demo?DEMO_SECURITY:EMPTY_SECURITY);
 const [loading,setLoading]=useState(!demo);
 useEffect(()=>{if(demo){setOps(DEMO_OPS);setFinance(DEMO_FINANCE);setGovernance(DEMO_GOV);setSecurity(DEMO_SECURITY);setLoading(false);return;}let alive=true;setLoading(true);Promise.allSettled([fetchHsOpsSnapshot(),fetchHsFinanceSnapshot(),fetchHsGovernanceSnapshot(),fetchHsSecuritySnapshot()]).then(rows=>{if(!alive)return;if(rows[0].status==="fulfilled")setOps(rows[0].value);if(rows[1].status==="fulfilled")setFinance(rows[1].value);if(rows[2].status==="fulfilled")setGovernance(rows[2].value);if(rows[3].status==="fulfilled")setSecurity(rows[3].value);setLoading(false)});return()=>{alive=false}},[demo]);
 const units=entities.filter(e=>e.entity.kind==="unit").length;
 const residents=entities.filter(e=>e.entity.kind==="person").length;
 const openComplaints=ops.complaints.filter(c=>!["closed","resolved"].includes(c.status));
 const urgentNotices=ops.notices.filter(n=>n.noticeType==="urgent");
 const openActions=governance.actions.filter(a=>!["done","cancelled"].includes(a.status));
 const attentionAssets=security.assets.filter(a=>!["active","ok","healthy"].includes(String(a.status||"").toLowerCase()));
 const openCompliance=security.compliance.filter(c=>String(c.status||"").toLowerCase()!=="closed");
 const activeVisitors=security.visitors.filter(v=>["expected","inside"].includes(String(v.status)));
 const upcomingBookings=ops.bookings.filter(b=>!["cancelled","rejected"].includes(b.status)).slice(0,3);
 const committee=governance.terms.find(t=>t.status==="active")?.assignments||[];
 const upcomingEvents=activities.filter(a=>a.type==="event"&&a.startsAt&&new Date(a.startsAt).getTime()>Date.now()).slice(0,3);
 const attentionCount=openComplaints.filter(c=>c.priority==="high"||c.priority==="urgent").length+urgentNotices.length+openActions.length+openCompliance.length+attentionAssets.length+(finance.summary.overdueBills||0);
 const heroSubtitle=demo?t("ResidentialFlagshipDemoDescTxt"):isAdmin?t("ResidentialFlagshipAdminDescTxt"):t("ResidentialFlagshipMemberDescTxt");
 const metrics=useMemo(()=>[
  {label:t("OpenComplaintsTxt"),value:openComplaints.length,icon:<ClipboardList/>,target:"complaints" as Target,tone:openComplaints.length?"attention":"good"},
  {label:t("OutstandingDuesTxt"),value:money(finance.summary.totalOutstanding),sub:`${finance.summary.overdueBills||0} ${t("OverdueHomesTxt")}`,icon:<CreditCard/>,target:"maintenance" as Target,tone:finance.summary.totalOutstanding>0?"attention":"good"},
  {label:t("VisitorsTodayTxt"),value:activeVisitors.length,icon:<DoorOpen/>,target:"security" as Target,tone:"neutral"},
  {label:t("CommitteeActionsTxt"),value:openActions.length,icon:<CheckCircle2/>,target:"governance" as Target,tone:openActions.length?"attention":"good"},
  {label:t("ComplianceDueTxt"),value:openCompliance.length,icon:<CalendarClock/>,target:"security" as Target,tone:openCompliance.length?"attention":"good"},
  {label:t("AssetsAttentionTxt"),value:attentionAssets.length,icon:<Wrench/>,target:"security" as Target,tone:attentionAssets.length?"attention":"good"},
 ],[openComplaints.length,finance.summary.totalOutstanding,finance.summary.overdueBills,activeVisitors.length,openActions.length,openCompliance.length,attentionAssets.length,t]);
 return <div data-testid="qa-hs-flagship-home" className="hs-flagship-home">
  <section className="hs-chairman-hero">
   <div className="hs-chairman-hero-copy"><span className="warm-kicker"><Building2 size={13}/> {t("ResidentialCommunityTxt")}</span><h1>{networkName}</h1><p>{heroSubtitle}</p><div className="hs-chairman-actions"><button className="btn primary" onClick={()=>onGo("notices")}><FileText size={16}/>{t("PublishViewNoticesTxt")}</button><button className="btn" onClick={()=>onGo("complaints")}><ClipboardList size={16}/>{t("ReviewComplaintsTxt")}</button><button className="btn" onClick={()=>onGo("maintenance")}><CreditCard size={16}/>{t("MaintenanceDuesTxt")}</button><button className="btn" onClick={()=>onGo("governance")}><Landmark size={16}/>{t("CommitteeMeetingsTxt")}</button></div></div>
   <div className="hs-chairman-status"><span>{demo||isAdmin?t("ChairmanAdminViewTxt"):t("ResidentViewTxt")}</span><strong>{attentionCount}</strong><small>{t("ItemsNeedAttentionTxt")}</small><div><b>{demo?72:units}</b><small>{t("HomesTxt")}</small><b>{demo?164:residents}</b><small>{t("ResidentsTxt")}</small></div></div>
  </section>
  {loading&&<div className="hs-dashboard-loading"><LoaderCircle className="spin" size={18}/><span>{t("LoadingSocietyOverviewTxt")}</span></div>}
  <section className="hs-chairman-metrics">{metrics.map(m=><button key={m.label} className={m.tone} onClick={()=>onGo(m.target)}><span className="hs-metric-icon">{m.icon}</span><span><small>{m.label}</small><strong>{m.value}</strong>{m.sub&&<em>{m.sub}</em>}</span><ArrowRight size={15}/></button>)}</section>
  <div className="hs-chairman-grid">
   <section className="card hs-attention-card"><div className="hs-card-head"><div><span className="warm-kicker"><AlertTriangle size={12}/> {t("NeedsAttentionTxt")}</span><h2>{t("SocietyTodayTxt")}</h2></div><button className="btn small" onClick={()=>onGo("complaints")}>{t("ViewOperationsTxt")}</button></div><div className="hs-attention-list">
    {urgentNotices.slice(0,1).map(n=><button key={n.id} onClick={()=>onGo("notices")}><span className="danger"><FileText/></span><div><b>{n.title}</b><small>{t("UrgentNoticeTxt")}</small></div><ArrowRight/></button>)}
    {openComplaints.slice(0,3).map(c=><button key={c.id} onClick={()=>onGo("complaints")}><span className={c.priority==="high"||c.priority==="urgent"?"danger":"warn"}><ClipboardList/></span><div><b>{c.title}</b><small>{c.category} · {c.status.replaceAll("_"," ")}</small></div><ArrowRight/></button>)}
    {openActions.slice(0,2).map(a=><button key={a.id} onClick={()=>onGo("governance")}><span className="neutral"><CheckCircle2/></span><div><b>{a.title}</b><small>{a.ownerLabel||t("CommitteeTxt")} · {dateLabel(a.dueOn)}</small></div><ArrowRight/></button>)}
    {!urgentNotices.length&&!openComplaints.length&&!openActions.length&&<div className="hs-all-clear"><CheckCircle2/><div><b>{t("AllClearTxt")}</b><small>{t("NoUrgentSocietyItemsTxt")}</small></div></div>}
   </div></section>
   <section className="card hs-finance-card"><div className="hs-card-head"><div><span className="warm-kicker"><CreditCard size={12}/> {t("MaintenanceFinanceTxt")}</span><h2>{t("CollectionSnapshotTxt")}</h2></div><button className="btn small" onClick={()=>onGo("maintenance")}>{t("OpenFinanceTxt")}</button></div><div className="hs-finance-summary"><article><small>{t("BilledTxt")}</small><strong>{money(finance.summary.totalBilled)}</strong></article><article><small>{t("CollectedTxt")}</small><strong>{money(finance.summary.totalCollected)}</strong></article><article className={finance.summary.totalOutstanding>0?"attention":""}><small>{t("OutstandingTxt")}</small><strong>{money(finance.summary.totalOutstanding)}</strong></article></div><div className="hs-fund-list">{finance.funds.slice(0,3).map(f=><div key={f.id}><span><b>{f.label}</b><small>{t("CurrentBalanceTxt")}</small></span><strong>{money(f.currentBalance)}</strong></div>)}</div></section>
   <section className="card hs-activity-card"><div className="hs-card-head"><div><span className="warm-kicker"><CalendarDays size={12}/> {t("ComingUpTxt")}</span><h2>{t("BookingsEventsTxt")}</h2></div><button className="btn small" onClick={()=>onGo("amenities")}>{t("AmenitiesTxt")}</button></div><div className="hs-upcoming-list">{upcomingBookings.map(b=><button key={b.id} onClick={()=>onGo("amenities")}><CalendarDays/><span><b>{b.amenityName}</b><small>{b.purpose||t("ResidentBookingTxt")} · {dateLabel(b.startsAt)} · {b.status}</small></span></button>)}{upcomingEvents.map(e=><button key={e.id} onClick={()=>onGo("community")}><UsersRound/><span><b>{e.title}</b><small>{dateLabel(e.startsAt)} · {t("CommunityEventTxt")}</small></span></button>)}{!upcomingBookings.length&&!upcomingEvents.length&&<div className="hs-empty-row">{t("NothingScheduledYetTxt")}</div>}</div></section>
   <section className="card hs-governance-card"><div className="hs-card-head"><div><span className="warm-kicker"><Landmark size={12}/> {t("GovernanceTxt")}</span><h2>{t("CommitteeDecisionsTxt")}</h2></div><button className="btn small" onClick={()=>onGo("governance")}>{t("OpenGovernanceTxt")}</button></div><div className="hs-committee-strip">{committee.slice(0,4).map(c=><div key={c.id}><span>{c.personLabel?.split(" ").map((x:string)=>x[0]).slice(0,2).join("")}</span><b>{c.personLabel}</b><small>{String(c.roleKey||"").replaceAll("_"," ")}</small></div>)}</div><div className="hs-resolution-list">{governance.resolutions.slice(0,3).map(r=><button key={r.id} onClick={()=>onGo("governance")}><ShieldCheck/><span><b>{r.title}</b><small>{r.resolutionNumber||t("ResolutionTxt")} · {r.status}</small></span></button>)}</div></section>
   <section className="card hs-safety-card"><div className="hs-card-head"><div><span className="warm-kicker"><ShieldCheck size={12}/> {t("SafetyComplianceTxt")}</span><h2>{t("AssetsComplianceTxt")}</h2></div><button className="btn small" onClick={()=>onGo("security")}>{t("OpenSecurityTxt")}</button></div><div className="hs-safety-list">{attentionAssets.slice(0,3).map(a=><button key={a.id} onClick={()=>onGo("security")}><Wrench/><span><b>{a.name}</b><small>{a.location||a.category} · {String(a.status).replaceAll("_"," ")}</small></span><em>{dateLabel(a.nextServiceOn)}</em></button>)}{openCompliance.slice(0,3).map(c=><button key={c.id} onClick={()=>onGo("security")}><CalendarClock/><span><b>{c.title}</b><small>{c.category} · {c.status}</small></span><em>{dateLabel(c.dueOn)}</em></button>)}</div></section>
   <section className="card hs-resident-card"><div className="hs-card-head"><div><span className="warm-kicker"><UsersRound size={12}/> {t("ResidentsHomesTxt")}</span><h2>{t("SocietyAtGlanceTxt")}</h2></div><button className="btn small" onClick={()=>onGo("directory")}>{t("OpenResidentsTxt")}</button></div><div className="hs-resident-stats"><button onClick={()=>onGo("explorer")}><Building2/><strong>{demo?72:units}</strong><small>{t("HomesTxt")}</small></button><button onClick={()=>onGo("directory")}><UsersRound/><strong>{demo?164:residents}</strong><small>{t("ResidentsTxt")}</small></button><button onClick={()=>onGo("amenities")}><CalendarDays/><strong>{ops.amenities.length}</strong><small>{t("AmenitiesTxt")}</small></button><button onClick={()=>onGo("security")}><DoorOpen/><strong>{activeVisitors.length}</strong><small>{t("ActiveVisitorsTxt")}</small></button></div></section>
  </div>
  <section className="card hs-capability-rail"><div><span className="warm-kicker">{t("AllSocietyCapabilitiesTxt")}</span><h3>{t("NothingRemovedResidentialTxt")}</h3><p>{t("ResidentialCapabilitiesDescTxt")}</p></div><div>{[["maintenance",t("MaintenanceDuesTxt")],["governance",t("CommitteeMeetingsTxt")],["security",t("VisitorsSecurityTxt")],["explorer",t("SocietyStructureTxt")],["community",t("CommunityTxt")]].map(([target,label])=><button key={target} onClick={()=>onGo(target as Target)}>{label}<ArrowRight size={14}/></button>)}</div></section>
 </div>;
}
