"use client";
import {useEffect,useMemo,useState} from "react";
import {Building2,Check,Link2,PauseCircle,Plus,RotateCcw,Search,ShieldCheck,X} from "lucide-react";
import type {TrustedPersonIdentity} from "../core/identity/trusted-person";
import type {FederationAffiliationRelationship,FederationUmbrella,NetworkUmbrellaAffiliation} from "../core/federation/umbrella-affiliation";
import {FEDERATION_AFFILIATION_GUARDRAILS} from "../core/federation/umbrella-affiliation";
import {createFederationUmbrella,fetchMyFederationUmbrellas,fetchMyNetworkUmbrellaAffiliations,requestNetworkUmbrellaAffiliation,reviewNetworkUmbrellaAffiliation,revokeNetworkUmbrellaAffiliation,searchFederationUmbrellas,suspendNetworkUmbrellaAffiliation} from "../capabilities/federation/affiliation-remote";
import {fetchMyNetworkPassports} from "../capabilities/federation/passport-remote";
import type {NetworkPassport} from "../core/federation/network-passport";
import {useLanguage} from "../lib/i18n";

const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,180);
const relationships:FederationAffiliationRelationship[]=["member","chapter","affiliate","constituent","franchisee","partner","other"];
export default function NetworkFederationAffiliationManager({identity}:{identity:TrustedPersonIdentity}){
 const {t:tr}=useLanguage();
 const adminMemberships=useMemo(()=>identity.memberships.filter(m=>m.status==="active"&&(m.role==="owner"||m.role==="admin")),[identity.memberships]);
 const [umbrellas,setUmbrellas]=useState<FederationUmbrella[]>([]),[affiliations,setAffiliations]=useState<NetworkUmbrellaAffiliation[]>([]),[passports,setPassports]=useState<NetworkPassport[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const [networkId,setNetworkId]=useState(adminMemberships[0]?.network.id||""),[umbrellaQuery,setUmbrellaQuery]=useState(""),[relationship,setRelationship]=useState<FederationAffiliationRelationship>("member"),[contextLabel,setContextLabel]=useState("");
 const [umbrellaName,setUmbrellaName]=useState(""),[umbrellaSlug,setUmbrellaSlug]=useState(""),[umbrellaType,setUmbrellaType]=useState("community"),[umbrellaSummary,setUmbrellaSummary]=useState(""),[umbrellaLocation,setUmbrellaLocation]=useState("");
 const load=async()=>{const [u,a,p]=await Promise.all([fetchMyFederationUmbrellas(),fetchMyNetworkUmbrellaAffiliations(),fetchMyNetworkPassports()]);setUmbrellas(u);setAffiliations(a);setPassports(p)};
 useEffect(()=>{void load().catch((e:any)=>setMessage(e.message||tr("NF2LoadFailedTxt")))},[]);
 if(!adminMemberships.length)return null;
 const passport=passports.find(p=>p.networkId===networkId);const ready=passport&&(passport.visibility==="federation"||passport.visibility==="public");
 const relationshipLabel=(r:FederationAffiliationRelationship)=>r==="member"?tr("NF2RelMemberTxt"):r==="chapter"?tr("NF2RelChapterTxt"):r==="affiliate"?tr("NF2RelAffiliateTxt"):r==="constituent"?tr("NF2RelConstituentTxt"):r==="franchisee"?tr("NF2RelFranchiseeTxt"):r==="partner"?tr("NF2RelPartnerTxt"):tr("NF2OtherTxt");
 const umbrellaTypeLabel=(r:string)=>r==="community"?tr("NF2TypeCommunityTxt"):r==="association"?tr("NF2TypeAssociationTxt"):r==="federation"?tr("NF2TypeFederationTxt"):r==="institution"?tr("NF2TypeInstitutionTxt"):r==="ecosystem"?tr("NF2TypeEcosystemTxt"):tr("NF2OtherTxt");
 const request=async()=>{setBusy(true);setMessage("");try{const matches=await searchFederationUmbrellas(umbrellaQuery);const target=matches.find(x=>x.slug===slugify(umbrellaQuery))||matches[0];if(!target)throw new Error(tr("NF2UmbrellaNotFoundTxt"));await requestNetworkUmbrellaAffiliation(networkId,target.slug,relationship,contextLabel);setMessage(tr("NF2RequestedTxt"));setUmbrellaQuery("");setContextLabel("");await load()}catch(e:any){setMessage(e.message||tr("NF2RequestFailedTxt"))}finally{setBusy(false)}};
 const createUmbrella=async()=>{setBusy(true);setMessage("");try{await createFederationUmbrella({name:umbrellaName,slug:slugify(umbrellaSlug||umbrellaName),umbrellaType,summary:umbrellaSummary,locationLabel:umbrellaLocation});setMessage(tr("NF2UmbrellaCreatedTxt"));setUmbrellaName("");setUmbrellaSlug("");setUmbrellaSummary("");setUmbrellaLocation("");await load()}catch(e:any){setMessage(e.message||tr("NF2CreateFailedTxt"))}finally{setBusy(false)}};
 const act=async(fn:()=>Promise<void>,ok:string)=>{setBusy(true);setMessage("");try{await fn();setMessage(ok);await load()}catch(e:any){setMessage(e.message||tr("NF2ActionFailedTxt"))}finally{setBusy(false)}};
 return <section className="card nf2-affiliation-card">
  <div className="nf2-head"><div><span className="warm-kicker"><Link2 size={13}/> {tr("NF2KickerTxt")}</span><h2>{tr("NF2TitleTxt")}</h2><p>{tr("NF2DescTxt")}</p></div><span className="nf2-badge"><ShieldCheck size={14}/>{tr("NF2NoMemberAccessTxt")}</span></div>
  <div className="nf2-grid">
   <article className="nf2-panel"><h3>{tr("NF2RequestTitleTxt")}</h3><label>{tr("NF2NetworkTxt")}<select value={networkId} onChange={e=>setNetworkId(e.target.value)}>{adminMemberships.map(m=><option key={m.network.id} value={m.network.id}>{m.network.name}</option>)}</select></label>
    <div className={`nf2-passport-state ${ready?"ready":"blocked"}`}><ShieldCheck size={15}/><span><b>{ready?tr("NF2PassportReadyTxt"):tr("NF2PassportRequiredTxt")}</b><small>{ready?`${passport?.publicSlug} · ${passport?.visibility}`:tr("NF2PassportRequiredHelpTxt")}</small></span></div>
    <label>{tr("NF2UmbrellaSearchTxt")}<div className="nf2-inline"><Search size={15}/><input value={umbrellaQuery} onChange={e=>setUmbrellaQuery(e.target.value)} placeholder={tr("NF2UmbrellaPlaceholderTxt")}/></div></label>
    <label>{tr("NF2RelationshipTxt")}<select value={relationship} onChange={e=>setRelationship(e.target.value as FederationAffiliationRelationship)}>{relationships.map(r=><option key={r} value={r}>{relationshipLabel(r)}</option>)}</select></label>
    <label>{tr("NF2ContextTxt")}<input value={contextLabel} maxLength={160} onChange={e=>setContextLabel(e.target.value)} placeholder={tr("NF2ContextPlaceholderTxt")}/></label>
    <button className="btn primary" disabled={busy||!ready||!umbrellaQuery.trim()} onClick={request}>{tr("NF2RequestBtnTxt")}</button>
   </article>
   <article className="nf2-panel"><h3>{tr("NF2CreateUmbrellaTitleTxt")}</h3><p className="nf2-muted">{tr("NF2CreateUmbrellaDescTxt")}</p><label>{tr("NF2UmbrellaNameTxt")}<input value={umbrellaName} onChange={e=>{setUmbrellaName(e.target.value);if(!umbrellaSlug)setUmbrellaSlug(slugify(e.target.value))}}/></label><div className="nf2-two"><label>{tr("NF2SlugTxt")}<input value={umbrellaSlug} onChange={e=>setUmbrellaSlug(e.target.value)}/></label><label>{tr("NF2TypeTxt")}<select value={umbrellaType} onChange={e=>setUmbrellaType(e.target.value)}><option value="community">{umbrellaTypeLabel("community")}</option><option value="association">{umbrellaTypeLabel("association")}</option><option value="federation">{umbrellaTypeLabel("federation")}</option><option value="institution">{umbrellaTypeLabel("institution")}</option><option value="ecosystem">{umbrellaTypeLabel("ecosystem")}</option><option value="other">{umbrellaTypeLabel("other")}</option></select></label></div><label>{tr("NF2SummaryTxt")}<textarea value={umbrellaSummary} maxLength={600} onChange={e=>setUmbrellaSummary(e.target.value)}/></label><label>{tr("NF2LocationTxt")}<input value={umbrellaLocation} maxLength={120} onChange={e=>setUmbrellaLocation(e.target.value)}/></label><button className="btn" disabled={busy||umbrellaName.trim().length<2} onClick={createUmbrella}><Plus size={14}/>{tr("NF2CreateUmbrellaBtnTxt")}</button>
    {umbrellas.length>0&&<div className="nf2-owned"><small>{tr("NF2YouGovernTxt")}</small>{umbrellas.map(u=><span key={u.id}><Building2 size={13}/><b>{u.name}</b><em>{umbrellaTypeLabel(u.umbrellaType)}</em></span>)}</div>}
   </article>
  </div>
  <div className="nf2-list"><h3>{tr("NF2AffiliationsTitleTxt")}</h3>{affiliations.length===0?<p className="nf2-muted">{tr("NF2NoAffiliationsTxt")}</p>:affiliations.map(a=><article key={a.id} className="nf2-aff-row"><div><span className={`nf2-status ${a.status}`}>{a.status}</span><small>{relationshipLabel(a.relationshipType)}</small><h4>{a.networkName} <b>→</b> {a.umbrellaName}</h4><p>{a.passportTagline||a.passportSummary||tr("NF2PassportReviewFallbackTxt")}</p><small>{a.passportLocation}{a.contextLabel?` · ${a.contextLabel}`:""}</small></div><div className="nf2-row-actions">{a.canReview&&<><button className="btn primary" disabled={busy} onClick={()=>void act(()=>reviewNetworkUmbrellaAffiliation(a.id,true),tr("NF2ApprovedTxt"))}><Check size={14}/>{tr("NF2ApproveTxt")}</button><button className="btn" disabled={busy} onClick={()=>void act(()=>reviewNetworkUmbrellaAffiliation(a.id,false),tr("NF2DeclinedTxt"))}><X size={14}/>{tr("NF2DeclineTxt")}</button></>}{a.canSuspend&&<button className="btn" disabled={busy} onClick={()=>void act(()=>suspendNetworkUmbrellaAffiliation(a.id),tr("NF2SuspendedTxt"))}><PauseCircle size={14}/>{tr("NF2SuspendTxt")}</button>}{a.canRevoke&&<button className="btn" disabled={busy} onClick={()=>void act(()=>revokeNetworkUmbrellaAffiliation(a.id),tr("NF2RevokedTxt"))}><RotateCcw size={14}/>{tr("NF2RevokeTxt")}</button>}</div></article>)}</div>
  {message&&<div className="nf2-message">{message}</div>}
  <details className="nf2-guardrails"><summary><ShieldCheck size={15}/>{tr("NF2GuardrailsTxt")}</summary><div>{FEDERATION_AFFILIATION_GUARDRAILS.map(x=><p key={x}><b>✓</b>{x}</p>)}</div></details>
 </section>;
}
