"use client";
import {useLanguage} from "../lib/i18n";
import {useEffect,useState} from "react";
import {ArrowLeft,ExternalLink,GitBranch,MapPin,ShieldCheck,UserRound} from "lucide-react";
import {IdentityAvatar,safeExternalUrl} from "../lib/identity";
import type {Member} from "../lib/types";
import {supabase} from "../lib/supabase";
import {trackPublicParticipation} from "../lib/remote";

type PublicMember=Pick<Member,"id"|"full_name"|"generation_level"|"profession"|"city"|"country"|"bio"|"date_of_death"|"avatar_style"|"facebook_url"|"instagram_url"|"other_social_url"|"other_social_label">;
const initials=(name:string)=>name.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();
export default function PublicMemberPage({memberId}:{memberId:string}){
 const {t:tr}=useLanguage();
 const [member,setMember]=useState<PublicMember|null>(null),[network,setNetwork]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{(async()=>{try{if(!supabase)throw new Error("This network is not configured for shared access.");const [m,n]=await Promise.all([supabase.rpc("get_public_family_member",{p_member_id:memberId}),supabase.rpc("get_public_network_info")]);if(m.error)throw m.error;if(n.error)throw n.error;const found=(m.data||[])[0];if(!found)throw new Error("This profile is not public or is no longer available.");setMember(found);setNetwork((n.data||[])[0]);const source=new URLSearchParams(window.location.search).get("source");trackPublicParticipation(source==="qr"?"qr_view":"profile_view",memberId,source||"direct").catch(()=>{})}catch(e:any){setError(e.message||"Could not load this profile.")}finally{setLoading(false)}})()},[memberId]);
 if(loading)return <div className="loading-screen"><GitBranch size={28}/><div><b>{tr("OpeningProfileTxt")}</b><div className="page-subtitle">{tr("OnlyPublicInformationWillBeShownTxt")}</div></div></div>;
 if(error||!member)return <main className="landing"><div className="landing-card"><h1>{tr("ProfileUnavailableTxt")}</h1><p className="page-subtitle">{error}</p><a className="btn primary" href="/public">{tr("ViewPublicDirectoryTxt")}</a></div></main>;
 return <main className="public-profile-page"><div className="public-profile-shell"><a href="/public" className="back-link"><ArrowLeft size={15}/> {tr("PublicDirectoryTxt")}</a><article className="card public-profile-card"><IdentityAvatar member={member} size="lg" className={member.date_of_death?"grayscale":""}/><div><span className="mode-pill shared">{tr("PublicProfileTxt")}</span><h1>{member.full_name}</h1>{member.date_of_death&&<p className="in-memoriam">{tr("RememberedWithLoveTxt")}</p>}<p className="public-role"><UserRound size={16}/>{member.profession||network?.entity_label||tr("MemberTxt")}</p>{(member.city||member.country)&&<p className="public-role"><MapPin size={16}/>{[member.city,member.country].filter(Boolean).join(", ")}</p>}<p className="public-role"><GitBranch size={16}/>{network?.level_label||tr("GenerationTxt")} {member.generation_level}</p>{member.bio&&<div className="public-bio">{member.bio}</div>}<div className="public-social-links">{[{label:tr("FacebookTxt"),url:safeExternalUrl(member.facebook_url)},{label:tr("InstagramTxt"),url:safeExternalUrl(member.instagram_url)},{label:member.other_social_label||tr("WebsiteTxt"),url:safeExternalUrl(member.other_social_url)}].filter(x=>x.url).map(x=><a key={x.label} href={x.url} target="_blank" rel="noopener noreferrer nofollow" className="social-link-chip">{x.label}<ExternalLink size={12}/></a>)}</div></div></article><div className="card privacy-note"><ShieldCheck size={22}/><div><b>{tr("PrivacyRespectingPublicProfileTxt")}</b><p>{tr("NoPhoneNumberEmailAddressExactLocationTxt")}</p></div></div><div className="card public-join"><h3>{tr("AreYouPartOfTxt")}{" "}{network?.name||tr("ThisNetworkTxt")}?</h3><p>{tr("UseYourPrivateInvitationToClaimYourTxt")}</p><a className="btn primary" href="/">{tr("SignInToThePrivateNetworkTxt")}</a></div></div></main>;
}
