"use client";
import {useEffect,useMemo,useState} from "react";
import {BadgeCheck,Compass,Route,Search,ShieldCheck,Sparkles,Star,Tags,XCircle} from "lucide-react";
import {TRUSTED_REQUEST_ROUTING_GUARDRAILS,type FederatedRequestContext,type FederatedRequestRoute,type FederatedTrustedRequest} from "../core/federation/trusted-request-routing";
import {createFederatedRequest,getFederatedRequestRoutes,getMyFederatedRequests,getTrustedRequestContexts,refreshFederatedRequestRoutes,setFederatedRequestStatus,setFederatedRouteStatus} from "../capabilities/federation/trusted-request-routing-remote";
import {useLanguage} from "../lib/i18n";

export default function TrustedRequestRouting(){
 const {t:tr}=useLanguage();
 const [contexts,setContexts]=useState<FederatedRequestContext[]>([]),[requests,setRequests]=useState<FederatedTrustedRequest[]>([]),[routes,setRoutes]=useState<FederatedRequestRoute[]>([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
 const [contextKey,setContextKey]=useState(""),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[location,setLocation]=useState(""),[tags,setTags]=useState(""),[selectedId,setSelectedId]=useState("");
 const chosen=useMemo(()=>contexts.find(c=>`${c.networkId}|${c.umbrellaId}|${c.scopeKey}`===contextKey)||null,[contexts,contextKey]);
 const selected=useMemo(()=>requests.find(r=>r.id===selectedId)||null,[requests,selectedId]);
 const load=async()=>{setLoading(true);try{const [c,r]=await Promise.all([getTrustedRequestContexts(),getMyFederatedRequests()]);setContexts(c);setRequests(r);if(!contextKey&&c[0])setContextKey(`${c[0].networkId}|${c[0].umbrellaId}|${c[0].scopeKey}`);const id=selectedId||r.find(x=>x.status==="open")?.id||r[0]?.id||"";setSelectedId(id);setRoutes(id?await getFederatedRequestRoutes(id):[])}catch(e:any){setMessage(e.message||tr("NF6LoadFailedTxt"))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const create=async()=>{if(!chosen||!title.trim())return;setLoading(true);setMessage("");try{const id=await createFederatedRequest({networkId:chosen.networkId,umbrellaId:chosen.umbrellaId,scopeKey:chosen.scopeKey,title,description,locationLabel:location,tags:tags.split(",").map(x=>x.trim()).filter(Boolean).slice(0,12)});setTitle("");setDescription("");setLocation("");setTags("");setSelectedId(id);setMessage(tr("NF6CreatedTxt"));await refreshFederatedRequestRoutes(id);await load()}catch(e:any){setMessage(e.message||tr("NF6CreateFailedTxt"));setLoading(false)}};
 const select=async(id:string)=>{setSelectedId(id);setLoading(true);try{setRoutes(await getFederatedRequestRoutes(id))}catch(e:any){setMessage(e.message||tr("NF6RoutesFailedTxt"))}finally{setLoading(false)}};
 const refresh=async()=>{if(!selected)return;setLoading(true);try{setRoutes(await refreshFederatedRequestRoutes(selected.id));setMessage(tr("NF6RefreshedTxt"))}catch(e:any){setMessage(e.message||tr("NF6RoutesFailedTxt"))}finally{setLoading(false)}};
 const updateRoute=async(r:FederatedRequestRoute,status:"suggested"|"shortlisted"|"dismissed")=>{setLoading(true);try{await setFederatedRouteStatus(r.id,status);setRoutes(await getFederatedRequestRoutes(r.requestId))}catch(e:any){setMessage(e.message||tr("NF6RouteUpdateFailedTxt"))}finally{setLoading(false)}};
 const close=async(status:"closed"|"cancelled")=>{if(!selected)return;setLoading(true);try{await setFederatedRequestStatus(selected.id,status);await load()}catch(e:any){setMessage(e.message||tr("NF6RequestUpdateFailedTxt"));setLoading(false)}};
 return <section className="card nf6-routing-card">
  <div className="nf6-head"><div><span className="warm-kicker"><Route size={13}/>{tr("NF6KickerTxt")}</span><h2>{tr("NF6TitleTxt")}</h2><p>{tr("NF6DescTxt")}</p></div><span className="nf6-badge"><ShieldCheck size={14}/>{tr("NF6NoIntroductionTxt")}</span></div>
  <div className="nf6-grid"><article><h3>{tr("NF6CreateTitleTxt")}</h3><p>{tr("NF6CreateDescTxt")}</p><label>{tr("NF6ContextTxt")}<select value={contextKey} onChange={e=>setContextKey(e.target.value)}><option value="">{tr("NF6ChooseContextTxt")}</option>{contexts.map(c=><option key={`${c.networkId}-${c.umbrellaId}-${c.scopeKey}`} value={`${c.networkId}|${c.umbrellaId}|${c.scopeKey}`}>{c.networkName} → {c.umbrellaName} · {c.scopeKey}</option>)}</select></label><label>{tr("NF6NeedTitleTxt")}<input value={title} onChange={e=>setTitle(e.target.value)} placeholder={tr("NF6NeedPlaceholderTxt")}/></label><label>{tr("NF6DescriptionTxt")}<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="nf6-row"><label>{tr("NF6LocationTxt")}<input value={location} onChange={e=>setLocation(e.target.value)}/></label><label>{tr("NF6TagsTxt")}<input value={tags} onChange={e=>setTags(e.target.value)} placeholder={tr("NF6TagsPlaceholderTxt")}/></label></div><button className="btn primary" onClick={()=>void create()} disabled={!chosen||!title.trim()||loading}><Sparkles size={14}/>{tr("NF6RouteRequestTxt")}</button></article>
   <article><h3>{tr("NF6MyRequestsTxt")}</h3><p>{tr("NF6MyRequestsDescTxt")}</p><div className="nf6-request-list">{requests.length===0?<small>{tr("NF6NoRequestsTxt")}</small>:requests.map(r=><button key={r.id} className={selectedId===r.id?"active":""} onClick={()=>void select(r.id)}><span><b>{r.title}</b><small>{r.scopeKey} · {r.networkName} → {r.umbrellaName}</small></span><em>{r.status}</em></button>)}</div></article></div>
  {selected&&<div className="nf6-routes"><div className="nf6-routes-head"><div><h3>{tr("NF6RoutesTitleTxt")}</h3><p>{selected.title} · {tr("NF6RoutesDescTxt")}</p></div><div>{selected.status==="open"&&<><button className="btn" onClick={()=>void refresh()} disabled={loading}><Search size={13}/>{tr("NF6RefreshTxt")}</button><button className="btn" onClick={()=>void close("closed")} disabled={loading}>{tr("NF6CloseTxt")}</button><button className="btn" onClick={()=>void close("cancelled")} disabled={loading}>{tr("NF6CancelTxt")}</button></>}</div></div><div className="nf6-route-list">{routes.length===0?<small>{tr("NF6NoRoutesTxt")}</small>:routes.map(r=><article key={r.id} className={`nf6-route ${r.status}`}><div className="nf6-score"><b>{r.score}</b><small>{tr("NF6MatchTxt")}</small></div><div><small>{r.targetNetworkName} · {r.contactMode}</small><h4>{r.displayName}</h4><b>{r.headline||tr("NF6ParticipantFallbackTxt")}</b><p>{r.summary||tr("NF6SummaryFallbackTxt")}</p><div className="nf6-tags">{r.locationLabel&&<em><Compass size={10}/>{r.locationLabel}</em>}{r.tags.map(x=><em key={x}><Tags size={10}/>{x}</em>)}</div><div className="nf6-reasons">{r.reasons.map(x=><span key={x}><BadgeCheck size={11}/>{x}</span>)}</div></div><aside><span><ShieldCheck size={12}/>{tr("NF6TrustReceiptTxt")}</span><b>{r.trustPathLabel}</b><small>{tr("NF6TrustReceiptHelpTxt")}</small><div><button className="btn" onClick={()=>void updateRoute(r,r.status==="shortlisted"?"suggested":"shortlisted")}><Star size={12}/>{r.status==="shortlisted"?tr("NF6UnshortlistTxt"):tr("NF6ShortlistTxt")}</button><button className="btn" onClick={()=>void updateRoute(r,"dismissed")}><XCircle size={12}/>{tr("NF6DismissTxt")}</button></div></aside></article>)}</div></div>}
  {message&&<div className="nf6-message">{message}</div>}
  <details className="nf6-guardrails"><summary><ShieldCheck size={15}/>{tr("NF6GuardrailsTxt")}</summary><div>{TRUSTED_REQUEST_ROUTING_GUARDRAILS.map(x=><p key={x}><b>✓</b>{x}</p>)}</div></details>
 </section>;
}
