"use client";
import {useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {Building2,CheckCircle2,ShieldCheck} from "lucide-react";
import {supabase} from "../../../lib/supabase";
import {acceptHsInvitation,fetchHsInvitationPreview} from "../../../verticals/housing-society/runtime/remote";
import {useLanguage} from "../../../lib/i18n";
export default function SocietyInvitePage(){
 const {t:xp2t}=useLanguage();
 const {token}=useParams<{token:string}>(),router=useRouter();const [preview,setPreview]=useState<any>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[existing,setExisting]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[joined,setJoined]=useState(false);
 useEffect(()=>{fetchHsInvitationPreview(String(token)).then(p=>{setPreview(p);setEmail(p?.email||"")}).catch(e=>setMessage(e.message||"Could not open invitation."))},[token]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setMessage("");try{if(existing){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error}else{const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:preview?.resident_name}}});if(error)throw error;if(!data.session){setMessage("Confirm your email, then reopen this invitation to complete claiming.");return}}await acceptHsInvitation(String(token));setJoined(true)}catch(e:any){setMessage(e.message||"Could not join this society.")}finally{setBusy(false)}};
 if(joined)return <main className="invite-friendly-page"><section className="invite-friendly-card invite-success"><CheckCircle2/><span className="warm-kicker">{xp2t("XP2Visible0001Txt")}</span><h1>{xp2t("XP2Visible0002Txt")} {preview?.society_name}</h1><p>{xp2t("XP2Visible0003Txt")} {preview?.resident_name}{preview?.unit_label?` · ${preview.unit_label}`:""}{xp2t("XP2Visible0004Txt")}</p><button className="btn primary invite-main-action" onClick={()=>router.push("/")}>{xp2t("XP2Visible0005Txt")}</button></section></main>;
 if(!preview)return <main className="invite-friendly-page"><section className="invite-friendly-card"><Building2/><h1>{xp2t("XP2Visible0006Txt")}</h1><p>{message||"Opening your invitation…"}</p></section></main>;
 if(preview.status!=="active")return <main className="invite-friendly-page"><section className="invite-friendly-card"><Building2/><h1>{xp2t("XP2Visible0007Txt")} {preview.status}</h1><p>{xp2t("XP2Visible0008Txt")}</p></section></main>;
 return <main className="invite-friendly-page"><section className="invite-friendly-card"><Building2/><span className="warm-kicker">{preview.society_name}</span><h1>{xp2t("XP2Visible0009Txt")} {preview.resident_name}</h1><p>{preview.unit_label?`Resident record for ${preview.unit_label}. `:""}{xp2t("XP2Visible0010Txt")} <b>{preview.email}</b>.</p><div className="segmented activation-toggle"><button type="button" className={!existing?"active":""} onClick={()=>setExisting(false)}>{xp2t("XP2Visible0011Txt")}</button><button type="button" className={existing?"active":""} onClick={()=>setExisting(true)}>{xp2t("XP2Visible0012Txt")}</button></div><form onSubmit={submit}><label className="field"><span>{xp2t("XP2Visible0013Txt")}</span><input className="text-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label className="field"><span>{xp2t("XP2Visible0014Txt")}</span><input className="text-input" type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<div className="notice invite-message">{message}</div>}<button className="btn primary invite-main-action" disabled={busy}>{busy?"Connecting…":"Join & claim resident profile"}</button></form><div className="invite-privacy"><ShieldCheck size={17}/><span>{xp2t("XP2Visible0015Txt")}</span></div></section></main>;
}
