import {supabase} from "../../lib/supabase";
import type {FederationAffiliationRelationship,FederationUmbrella,FederationUmbrellaSearchResult,NetworkUmbrellaAffiliation} from "../../core/federation/umbrella-affiliation";
function required(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}
const mapUmbrella=(r:any):FederationUmbrella=>({id:String(r.id),name:String(r.name),slug:String(r.slug),umbrellaType:r.umbrella_type,summary:r.summary||"",locationLabel:r.location_label||"",status:r.status||"active",role:r.role||"admin",createdAt:r.created_at||null});
const mapSearch=(r:any):FederationUmbrellaSearchResult=>({id:String(r.id),name:String(r.name),slug:String(r.slug),umbrellaType:r.umbrella_type,summary:r.summary||"",locationLabel:r.location_label||""});
const mapAff=(r:any):NetworkUmbrellaAffiliation=>({id:String(r.id),networkId:String(r.network_id),networkName:String(r.network_name),verticalKind:String(r.vertical_kind),umbrellaId:String(r.umbrella_id),umbrellaName:String(r.umbrella_name),umbrellaSlug:String(r.umbrella_slug),relationshipType:r.relationship_type,status:r.status,contextLabel:r.context_label||"",direction:r.direction||"network",canReview:!!r.can_review,canSuspend:!!r.can_suspend,canRevoke:!!r.can_revoke,passportSlug:r.passport_slug||"",passportTagline:r.passport_tagline||"",passportSummary:r.passport_summary||"",passportLocation:r.passport_location||"",passportVerification:r.passport_verification||"self_declared",requestedAt:r.requested_at||null,updatedAt:r.updated_at||null});
export async function fetchMyFederationUmbrellas():Promise<FederationUmbrella[]>{const {data,error}=await required().rpc("get_my_federation_umbrellas");if(error)throw error;return (data||[]).map(mapUmbrella)}
export async function searchFederationUmbrellas(query:string):Promise<FederationUmbrellaSearchResult[]>{const {data,error}=await required().rpc("search_federation_umbrellas",{p_query:query});if(error)throw error;return (data||[]).map(mapSearch)}
export async function createFederationUmbrella(input:{name:string;slug:string;umbrellaType:string;summary:string;locationLabel:string}):Promise<string>{const {data,error}=await required().rpc("create_federation_umbrella",{p_name:input.name,p_slug:input.slug,p_umbrella_type:input.umbrellaType,p_summary:input.summary,p_location_label:input.locationLabel});if(error)throw error;return String(data)}
export async function fetchMyNetworkUmbrellaAffiliations():Promise<NetworkUmbrellaAffiliation[]>{const {data,error}=await required().rpc("get_my_network_umbrella_affiliations");if(error)throw error;return (data||[]).map(mapAff)}
export async function requestNetworkUmbrellaAffiliation(networkId:string,umbrellaSlug:string,relationshipType:FederationAffiliationRelationship,contextLabel:string):Promise<string>{const {data,error}=await required().rpc("request_network_umbrella_affiliation",{p_network_id:networkId,p_umbrella_slug:umbrellaSlug,p_relationship_type:relationshipType,p_context_label:contextLabel});if(error)throw error;return String(data)}
export async function reviewNetworkUmbrellaAffiliation(id:string,approve:boolean):Promise<void>{const {error}=await required().rpc("review_network_umbrella_affiliation",{p_affiliation_id:id,p_approve:approve});if(error)throw error}
export async function suspendNetworkUmbrellaAffiliation(id:string):Promise<void>{const {error}=await required().rpc("suspend_network_umbrella_affiliation",{p_affiliation_id:id});if(error)throw error}
export async function revokeNetworkUmbrellaAffiliation(id:string):Promise<void>{const {error}=await required().rpc("revoke_network_umbrella_affiliation",{p_affiliation_id:id});if(error)throw error}
