import {supabase} from "../../lib/supabase";
import type {FederatedScopeContext,FederatedScopeProfile,MyFederatedScopeProfile} from "../../core/federation/application-scopes";
function required(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}
const list=(v:unknown)=>Array.isArray(v)?v.map(String):[];
const context=(r:any):FederatedScopeContext=>({networkId:String(r.network_id),networkName:String(r.network_name),umbrellaId:String(r.umbrella_id),umbrellaName:String(r.umbrella_name),scopeKey:String(r.scope_key),passportVisibility:r.passport_visibility||"federation"});
const mine=(r:any):MyFederatedScopeProfile=>({id:String(r.id),scopeKey:String(r.scope_key),displayName:r.display_name||"",headline:r.headline||"",summary:r.summary||"",locationLabel:r.location_label||"",tags:list(r.tags),contactMode:r.contact_mode||"introduction_only",networkId:String(r.network_id),networkName:String(r.network_name),umbrellaId:String(r.umbrella_id),umbrellaName:String(r.umbrella_name),active:Boolean(r.active),updatedAt:r.updated_at||null});
const result=(r:any):FederatedScopeProfile=>({id:String(r.id),scopeKey:String(r.scope_key),displayName:r.display_name||"",headline:r.headline||"",summary:r.summary||"",locationLabel:r.location_label||"",tags:list(r.tags),contactMode:r.contact_mode||"introduction_only",networkId:String(r.network_id),networkName:String(r.network_name),umbrellaId:String(r.umbrella_id),umbrellaName:String(r.umbrella_name),sourceNetworkId:String(r.source_network_id),sourceNetworkName:String(r.source_network_name),trustPathLabel:r.trust_path_label||"",isMine:Boolean(r.is_mine),updatedAt:r.updated_at||null});
export async function getFederatedScopeContexts():Promise<FederatedScopeContext[]>{const {data,error}=await required().rpc("get_my_federated_scope_contexts");if(error)throw error;return (data||[]).map(context)}
export async function getMyFederatedScopeProfiles():Promise<MyFederatedScopeProfile[]>{const {data,error}=await required().rpc("get_my_federated_scope_profiles");if(error)throw error;return (data||[]).map(mine)}
export async function saveFederatedScopeProfile(input:{networkId:string;umbrellaId:string;scopeKey:string;displayName:string;headline?:string;summary?:string;locationLabel?:string;tags?:string[];contactMode?:string}):Promise<string>{const {data,error}=await required().rpc("save_my_federated_scope_profile",{p_network_id:input.networkId,p_umbrella_id:input.umbrellaId,p_scope_key:input.scopeKey,p_display_name:input.displayName,p_headline:input.headline||null,p_summary:input.summary||null,p_location_label:input.locationLabel||null,p_tags:input.tags||[],p_contact_mode:input.contactMode||"introduction_only"});if(error)throw error;return String(data)}
export async function setFederatedScopeProfileActive(id:string,active:boolean):Promise<void>{const {error}=await required().rpc("set_my_federated_scope_profile_active",{p_profile_id:id,p_active:active});if(error)throw error}
export async function searchFederatedScopeProfiles(scopeKey:string,query="",limit=40):Promise<FederatedScopeProfile[]>{const {data,error}=await required().rpc("search_federated_scope_profiles",{p_scope_key:scopeKey,p_query:query,p_limit:limit});if(error)throw error;return (data||[]).map(result)}
