import {supabase} from "../../lib/supabase";
import type {FederatedIntroduction,IntroductionRouteCandidate} from "../../core/federation/governed-introductions";
function required(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}
const candidate=(r:any):IntroductionRouteCandidate=>({routeId:String(r.route_id),requestId:String(r.request_id),requestTitle:r.request_title||"",scopeKey:r.scope_key||"",targetScopeProfileId:String(r.target_scope_profile_id),targetDisplayName:r.target_display_name||"",targetHeadline:r.target_headline||"",targetNetworkName:r.target_network_name||"",umbrellaName:r.umbrella_name||"",score:Number(r.score||0),trustPathLabel:r.trust_path_label||""});
const intro=(r:any):FederatedIntroduction=>({id:String(r.id),direction:r.direction||"outbound",status:r.status||"pending",scopeKey:r.scope_key||"",requestTitle:r.request_title||"",requesterAlias:r.requester_alias||"",message:r.message||"",requesterContactNote:r.requester_contact_note||"",targetResponseNote:r.target_response_note||"",targetContactNote:r.target_contact_note||"",targetDisplayName:r.target_display_name||"",targetHeadline:r.target_headline||"",targetNetworkName:r.target_network_name||"",umbrellaName:r.umbrella_name||"",trustPathLabel:r.trust_path_label||"",createdAt:r.created_at||null,respondedAt:r.responded_at||null,updatedAt:r.updated_at||null});
export async function getShortlistedIntroductionRoutes():Promise<IntroductionRouteCandidate[]>{const {data,error}=await required().rpc("get_my_shortlisted_federated_routes");if(error)throw error;return (data||[]).map(candidate)}
export async function getMyFederatedIntroductions():Promise<FederatedIntroduction[]>{const {data,error}=await required().rpc("get_my_federated_introductions_v2");if(error)throw error;return (data||[]).map(intro)}
export async function requestFederatedIntroduction(input:{routeId:string;requesterAlias:string;message:string;contactNote:string}):Promise<string>{const {data,error}=await required().rpc("request_federated_introduction_v2",{p_route_id:input.routeId,p_requester_alias:input.requesterAlias,p_message:input.message,p_contact_note:input.contactNote});if(error)throw error;return String(data)}
export async function respondToFederatedIntroduction(input:{introductionId:string;accept:boolean;responseNote?:string;contactNote?:string}):Promise<void>{const {error}=await required().rpc("respond_to_federated_introduction_v2",{p_introduction_id:input.introductionId,p_accept:input.accept,p_response_note:input.responseNote||null,p_contact_note:input.contactNote||null});if(error)throw error}
export async function cancelFederatedIntroduction(id:string):Promise<void>{const {error}=await required().rpc("cancel_federated_introduction_v2",{p_introduction_id:id});if(error)throw error}
