import {supabase} from "../../lib/supabase";
import type {FederatedRequestContext,FederatedRequestRoute,FederatedTrustedRequest} from "../../core/federation/trusted-request-routing";
function required(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}
const list=(v:unknown)=>Array.isArray(v)?v.map(String):[];
const context=(r:any):FederatedRequestContext=>({networkId:String(r.network_id),networkName:String(r.network_name),umbrellaId:String(r.umbrella_id),umbrellaName:String(r.umbrella_name),scopeKey:String(r.scope_key),passportVisibility:r.passport_visibility||"federation"});
const request=(r:any):FederatedTrustedRequest=>({id:String(r.id),scopeKey:String(r.scope_key),title:r.title||"",description:r.description||"",locationLabel:r.location_label||"",tags:list(r.tags),status:r.status||"open",networkId:String(r.network_id),networkName:String(r.network_name),umbrellaId:String(r.umbrella_id),umbrellaName:String(r.umbrella_name),createdAt:r.created_at||null,updatedAt:r.updated_at||null});
const route=(r:any):FederatedRequestRoute=>({id:String(r.id),requestId:String(r.request_id),targetScopeProfileId:String(r.target_scope_profile_id),displayName:r.display_name||"",headline:r.headline||"",summary:r.summary||"",locationLabel:r.location_label||"",tags:list(r.tags),contactMode:r.contact_mode||"introduction_only",targetNetworkId:String(r.target_network_id),targetNetworkName:String(r.target_network_name),umbrellaId:String(r.umbrella_id),umbrellaName:String(r.umbrella_name),score:Number(r.score||0),reasons:list(r.reasons),trustPathLabel:r.trust_path_label||"",status:r.status||"suggested",generatedAt:r.generated_at||null});
export async function getTrustedRequestContexts():Promise<FederatedRequestContext[]>{const {data,error}=await required().rpc("get_my_trusted_request_contexts");if(error)throw error;return (data||[]).map(context)}
export async function getMyFederatedRequests():Promise<FederatedTrustedRequest[]>{const {data,error}=await required().rpc("get_my_federated_requests");if(error)throw error;return (data||[]).map(request)}
export async function createFederatedRequest(input:{networkId:string;umbrellaId:string;scopeKey:string;title:string;description?:string;locationLabel?:string;tags?:string[]}):Promise<string>{const {data,error}=await required().rpc("create_my_federated_request",{p_network_id:input.networkId,p_umbrella_id:input.umbrellaId,p_scope_key:input.scopeKey,p_title:input.title,p_description:input.description||null,p_location_label:input.locationLabel||null,p_tags:input.tags||[]});if(error)throw error;return String(data)}
export async function setFederatedRequestStatus(id:string,status:"open"|"closed"|"cancelled"):Promise<void>{const {error}=await required().rpc("set_my_federated_request_status",{p_request_id:id,p_status:status});if(error)throw error}
export async function refreshFederatedRequestRoutes(id:string,limit=20):Promise<FederatedRequestRoute[]>{const {error}=await required().rpc("refresh_my_federated_request_routes",{p_request_id:id,p_limit:limit});if(error)throw error;return getFederatedRequestRoutes(id)}
export async function getFederatedRequestRoutes(id:string):Promise<FederatedRequestRoute[]>{const {data,error}=await required().rpc("get_my_federated_request_routes",{p_request_id:id});if(error)throw error;return (data||[]).map(route)}
export async function setFederatedRouteStatus(id:string,status:"suggested"|"shortlisted"|"dismissed"):Promise<void>{const {error}=await required().rpc("set_my_federated_request_route_status",{p_route_id:id,p_status:status});if(error)throw error}
