-- TRUSTWEAVE D12 CANONICAL CURRENT-STATE BASELINE.
-- Materialized after fresh-project structural/security/API/behavior/product parity on 2026-09-20.
-- DO NOT apply these files to the historical golden project as an upgrade sequence.
-- Historical supabase/migrations/001..123 remain immutable upgrade history.

ALTER TABLE "public"."audit_log" ADD CONSTRAINT "audit_log_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."audit_log" ADD CONSTRAINT "audit_log_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."launch_demo_seed_authorizations" ADD CONSTRAINT "launch_demo_seed_authorizations_authorized_by_fkey" FOREIGN KEY (authorized_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."launch_demo_seed_authorizations" ADD CONSTRAINT "launch_demo_seed_authorizations_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."launch_demo_seed_authorizations" ADD CONSTRAINT "launch_demo_seed_authorizations_synthetic_check" CHECK (synthetic);
ALTER TABLE "public"."launch_demo_seed_issues" ADD CONSTRAINT "launch_demo_seed_issues_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."launch_demo_seed_issues" ADD CONSTRAINT "launch_demo_seed_issues_run_id_fkey" FOREIGN KEY (run_id) REFERENCES launch_demo_seed_runs(id) ON DELETE CASCADE;
ALTER TABLE "public"."launch_demo_seed_issues" ADD CONSTRAINT "launch_demo_seed_issues_severity_check" CHECK (severity::text = ANY (ARRAY['error'::character varying, 'warning'::character varying]::text[]));
ALTER TABLE "public"."launch_demo_seed_lineage" ADD CONSTRAINT "launch_demo_seed_lineage_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."launch_demo_seed_lineage" ADD CONSTRAINT "launch_demo_seed_lineage_network_id_dataset_version_fkey" FOREIGN KEY (network_id, dataset_version) REFERENCES launch_demo_seed_authorizations(network_id, dataset_version) ON DELETE CASCADE;
ALTER TABLE "public"."launch_demo_seed_lineage" ADD CONSTRAINT "launch_demo_seed_lineage_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."launch_demo_seed_lineage" ADD CONSTRAINT "launch_demo_seed_lineage_status_check" CHECK (status::text = ANY (ARRAY['committed'::character varying, 'skipped'::character varying, 'warning'::character varying, 'partial'::character varying, 'error'::character varying]::text[]));
ALTER TABLE "public"."launch_demo_seed_runs" ADD CONSTRAINT "launch_demo_seed_runs_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."launch_demo_seed_runs" ADD CONSTRAINT "launch_demo_seed_runs_created_count_check" CHECK (created_count >= 0);
ALTER TABLE "public"."launch_demo_seed_runs" ADD CONSTRAINT "launch_demo_seed_runs_error_count_check" CHECK (error_count >= 0);
ALTER TABLE "public"."launch_demo_seed_runs" ADD CONSTRAINT "launch_demo_seed_runs_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."launch_demo_seed_runs" ADD CONSTRAINT "launch_demo_seed_runs_skipped_count_check" CHECK (skipped_count >= 0);
ALTER TABLE "public"."launch_demo_seed_runs" ADD CONSTRAINT "launch_demo_seed_runs_status_check" CHECK (status::text = ANY (ARRAY['running'::character varying, 'completed'::character varying, 'completed_with_errors'::character varying, 'failed'::character varying]::text[]));
ALTER TABLE "public"."launch_demo_seed_runs" ADD CONSTRAINT "launch_demo_seed_runs_total_rows_check" CHECK (total_rows >= 0);
ALTER TABLE "public"."launch_demo_seed_runs" ADD CONSTRAINT "launch_demo_seed_runs_updated_count_check" CHECK (updated_count >= 0);
ALTER TABLE "public"."launch_demo_seed_runs" ADD CONSTRAINT "launch_demo_seed_runs_warning_count_check" CHECK (warning_count >= 0);
ALTER TABLE "public"."network_archive_membership_state" ADD CONSTRAINT "network_archive_membership_state_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_archive_membership_state" ADD CONSTRAINT "network_archive_membership_state_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_assertion_decisions" ADD CONSTRAINT "network_assertion_decisions_action_check" CHECK (action = ANY (ARRAY['accept'::text, 'reject'::text, 'merge'::text, 'supersede'::text]));
ALTER TABLE "public"."network_assertion_decisions" ADD CONSTRAINT "network_assertion_decisions_assertion_id_fkey" FOREIGN KEY (assertion_id) REFERENCES network_candidate_assertions(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_assertion_decisions" ADD CONSTRAINT "network_assertion_decisions_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_bridge_codes" ADD CONSTRAINT "network_bridge_codes_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE "public"."network_bridge_codes" ADD CONSTRAINT "network_bridge_codes_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_candidate_assertions" ADD CONSTRAINT "network_candidate_assertions_confidence_check" CHECK (confidence >= 0::numeric AND confidence <= 1::numeric);
ALTER TABLE "public"."network_candidate_assertions" ADD CONSTRAINT "network_candidate_assertions_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_candidate_assertions" ADD CONSTRAINT "network_candidate_assertions_status_check" CHECK (status = ANY (ARRAY['candidate'::text, 'verified'::text, 'rejected'::text, 'superseded'::text, 'conflicted'::text]));
ALTER TABLE "public"."network_candidate_assertions" ADD CONSTRAINT "network_candidate_assertions_supersedes_assertion_id_fkey" FOREIGN KEY (supersedes_assertion_id) REFERENCES network_candidate_assertions(id);
ALTER TABLE "public"."network_contribution_audit" ADD CONSTRAINT "network_contribution_audit_actor_user_id_fkey" FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_contribution_audit" ADD CONSTRAINT "network_contribution_audit_contribution_id_fkey" FOREIGN KEY (contribution_id) REFERENCES network_contributions(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_contribution_audit" ADD CONSTRAINT "network_contribution_audit_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_contributions" ADD CONSTRAINT "fk_network_contribution_entity_tenant" FOREIGN KEY (entity_id, network_id) REFERENCES network_entities(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."network_contributions" ADD CONSTRAINT "network_contributions_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_contributions" ADD CONSTRAINT "network_contributions_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_contributions" ADD CONSTRAINT "network_contributions_reviewed_by_fkey" FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_contributions" ADD CONSTRAINT "network_contributions_status_check" CHECK (status::text = ANY (ARRAY['open'::character varying, 'accepted'::character varying, 'rejected'::character varying]::text[]));
ALTER TABLE "public"."network_dimension_values" ADD CONSTRAINT "fk_network_dimension_value_dimension_tenant" FOREIGN KEY (dimension_id, network_id) REFERENCES network_dimensions(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."network_dimension_values" ADD CONSTRAINT "network_dimension_values_dimension_id_fkey" FOREIGN KEY (dimension_id) REFERENCES network_dimensions(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_dimension_values" ADD CONSTRAINT "network_dimension_values_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_dimensions" ADD CONSTRAINT "network_dimensions_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_entities" ADD CONSTRAINT "network_entities_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_entities" ADD CONSTRAINT "network_entities_owner_user_id_fkey" FOREIGN KEY (owner_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_entities" ADD CONSTRAINT "network_entities_visibility_check" CHECK (visibility::text = ANY (ARRAY['members'::character varying, 'private'::character varying]::text[]));
ALTER TABLE "public"."network_entity_affiliations" ADD CONSTRAINT "fk_network_affiliation_dimension_tenant" FOREIGN KEY (dimension_id, network_id) REFERENCES network_dimensions(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."network_entity_affiliations" ADD CONSTRAINT "fk_network_affiliation_entity_tenant" FOREIGN KEY (entity_id, network_id) REFERENCES network_entities(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."network_entity_affiliations" ADD CONSTRAINT "fk_network_affiliation_value_tenant" FOREIGN KEY (value_id, network_id) REFERENCES network_dimension_values(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."network_entity_affiliations" ADD CONSTRAINT "network_entity_affiliations_dimension_id_fkey" FOREIGN KEY (dimension_id) REFERENCES network_dimensions(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_entity_affiliations" ADD CONSTRAINT "network_entity_affiliations_entity_id_fkey" FOREIGN KEY (entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_entity_affiliations" ADD CONSTRAINT "network_entity_affiliations_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_entity_affiliations" ADD CONSTRAINT "network_entity_affiliations_value_id_fkey" FOREIGN KEY (value_id) REFERENCES network_dimension_values(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_entity_relationships" ADD CONSTRAINT "fk_network_entity_relationship_from_tenant" FOREIGN KEY (from_entity_id, network_id) REFERENCES network_entities(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."network_entity_relationships" ADD CONSTRAINT "fk_network_entity_relationship_to_tenant" FOREIGN KEY (to_entity_id, network_id) REFERENCES network_entities(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."network_entity_relationships" ADD CONSTRAINT "network_entity_relationships_check" CHECK (from_entity_id <> to_entity_id);
ALTER TABLE "public"."network_entity_relationships" ADD CONSTRAINT "network_entity_relationships_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_entity_relationships" ADD CONSTRAINT "network_entity_relationships_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_evidence_records" ADD CONSTRAINT "network_evidence_records_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_evidence_records" ADD CONSTRAINT "network_evidence_records_source_id_fkey" FOREIGN KEY (source_id) REFERENCES network_knowledge_sources(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_evidence_records" ADD CONSTRAINT "network_evidence_records_visibility_check" CHECK (visibility = ANY (ARRAY['network'::text, 'restricted'::text]));
ALTER TABLE "public"."network_feature_settings" ADD CONSTRAINT "network_feature_settings_feature_key_fkey" FOREIGN KEY (feature_key) REFERENCES platform_feature_flags(feature_key) ON DELETE CASCADE;
ALTER TABLE "public"."network_feature_settings" ADD CONSTRAINT "network_feature_settings_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_feature_settings" ADD CONSTRAINT "network_feature_settings_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_group_memberships" ADD CONSTRAINT "fk_network_group_membership_tenant" FOREIGN KEY (group_id, network_id) REFERENCES network_groups(id, network_id) ON DELETE CASCADE;
ALTER TABLE "public"."network_group_memberships" ADD CONSTRAINT "network_group_memberships_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_group_memberships" ADD CONSTRAINT "network_group_memberships_role_check" CHECK (role::text = ANY (ARRAY['member'::character varying, 'lead'::character varying]::text[]));
ALTER TABLE "public"."network_group_memberships" ADD CONSTRAINT "network_group_memberships_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_groups" ADD CONSTRAINT "fk_network_group_dimension_tenant" FOREIGN KEY (dimension_value_id, network_id) REFERENCES network_dimension_values(id, network_id) ON DELETE SET NULL;
ALTER TABLE "public"."network_groups" ADD CONSTRAINT "network_groups_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_groups" ADD CONSTRAINT "network_groups_dimension_value_id_fkey" FOREIGN KEY (dimension_value_id) REFERENCES network_dimension_values(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_groups" ADD CONSTRAINT "network_groups_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_join_codes" ADD CONSTRAINT "network_join_codes_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_join_codes" ADD CONSTRAINT "network_join_codes_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_knowledge_sources" ADD CONSTRAINT "network_knowledge_sources_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_knowledge_sources" ADD CONSTRAINT "network_knowledge_sources_visibility_check" CHECK (visibility = ANY (ARRAY['network'::text, 'restricted'::text]));
ALTER TABLE "public"."network_projections" ADD CONSTRAINT "network_projections_levels_check" CHECK (cardinality(levels) > 0);
ALTER TABLE "public"."network_projections" ADD CONSTRAINT "network_projections_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_purge_receipts" ADD CONSTRAINT "network_purge_receipts_purged_by_fkey" FOREIGN KEY (purged_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_quick_start_state" ADD CONSTRAINT "network_quick_start_state_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_quick_start_state" ADD CONSTRAINT "network_quick_start_state_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_settings" ADD CONSTRAINT "network_settings_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_settings" ADD CONSTRAINT "network_settings_self_edit_mode_check" CHECK (self_edit_mode::text = ANY (ARRAY['review'::character varying, 'safe_fields_direct'::character varying]::text[]));
ALTER TABLE "public"."network_settings" ADD CONSTRAINT "network_settings_vertical_kind_check" CHECK (vertical_kind::text = ANY (ARRAY['family'::character varying, 'alumni'::character varying, 'association'::character varying, 'family-association'::character varying, 'housing-society'::character varying, 'organization'::character varying, 'business-trust'::character varying, 'franchise'::character varying, 'professional'::character varying]::text[]));
ALTER TABLE "public"."networks" ADD CONSTRAINT "networks_approval_reviewed_by_fkey" FOREIGN KEY (approval_reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."networks" ADD CONSTRAINT "networks_approval_status_check" CHECK (approval_status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[]));
ALTER TABLE "public"."networks" ADD CONSTRAINT "networks_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."networks" ADD CONSTRAINT "networks_media_usage_bytes_check" CHECK (media_usage_bytes >= 0);
ALTER TABLE "public"."networks" ADD CONSTRAINT "networks_photo_max_bytes_check" CHECK (photo_max_bytes >= 10240 AND photo_max_bytes <= 1048576);
ALTER TABLE "public"."networks" ADD CONSTRAINT "networks_status_check" CHECK (status::text = ANY (ARRAY['active'::character varying, 'archived'::character varying]::text[]));
ALTER TABLE "public"."networks" ADD CONSTRAINT "networks_storage_limit_bytes_check" CHECK (storage_limit_bytes >= 1048576 AND storage_limit_bytes <= '10737418240'::bigint);
ALTER TABLE "public"."networks" ADD CONSTRAINT "networks_vertical_kind_check" CHECK (vertical_kind::text = ANY (ARRAY['family'::character varying, 'alumni'::character varying, 'association'::character varying, 'family-association'::character varying, 'housing-society'::character varying, 'organization'::character varying, 'business-trust'::character varying, 'franchise'::character varying, 'professional'::character varying]::text[]));
ALTER TABLE "public"."pilot_feedback" ADD CONSTRAINT "pilot_feedback_friction_code_check" CHECK (friction_code::text = ANY (ARRAY['none'::character varying, 'next_step'::character varying, 'setup'::character varying, 'data'::character varying, 'permission'::character varying, 'discovery'::character varying, 'consent'::character varying, 'technical'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."pilot_feedback" ADD CONSTRAINT "pilot_feedback_moment_type_check" CHECK (moment_type::text = ANY (ARRAY['launch'::character varying, 'participation'::character varying, 'claim'::character varying, 'bridge'::character varying, 'discovery'::character varying, 'introduction'::character varying, 'outcome'::character varying, 'general'::character varying]::text[]));
ALTER TABLE "public"."pilot_feedback" ADD CONSTRAINT "pilot_feedback_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."pilot_feedback" ADD CONSTRAINT "pilot_feedback_outcome_check" CHECK (outcome::text = ANY (ARRAY['helpful'::character varying, 'partial'::character varying, 'blocked'::character varying]::text[]));
ALTER TABLE "public"."pilot_feedback" ADD CONSTRAINT "pilot_feedback_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."pilot_product_decisions" ADD CONSTRAINT "pilot_product_decisions_decided_by_fkey" FOREIGN KEY (decided_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."pilot_product_decisions" ADD CONSTRAINT "pilot_product_decisions_disposition_check" CHECK (disposition::text = ANY (ARRAY['invest'::character varying, 'fix'::character varying, 'hold'::character varying, 'stop'::character varying]::text[]));
ALTER TABLE "public"."pilot_product_decisions" ADD CONSTRAINT "pilot_product_decisions_evidence_days_check" CHECK (evidence_days >= 7 AND evidence_days <= 90);
ALTER TABLE "public"."pilot_product_decisions" ADD CONSTRAINT "pilot_product_decisions_moment_type_check" CHECK (moment_type::text = ANY (ARRAY['launch'::character varying, 'participation'::character varying, 'claim'::character varying, 'bridge'::character varying, 'discovery'::character varying, 'introduction'::character varying, 'outcome'::character varying, 'general'::character varying]::text[]));
ALTER TABLE "public"."pilot_product_decisions" ADD CONSTRAINT "pilot_product_decisions_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."platform_feature_flags" ADD CONSTRAINT "platform_feature_flags_rollout_state_check" CHECK (rollout_state::text = ANY (ARRAY['hidden'::character varying, 'test'::character varying, 'pilot'::character varying, 'released'::character varying]::text[]));
ALTER TABLE "public"."platform_feature_flags" ADD CONSTRAINT "platform_feature_flags_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."platform_feature_flags" ADD CONSTRAINT "platform_feature_flags_vertical_kind_check" CHECK (vertical_kind::text = ANY (ARRAY['family'::character varying, 'alumni'::character varying, 'association'::character varying, 'family-association'::character varying, 'housing-society'::character varying, 'organization'::character varying, 'business-trust'::character varying, 'franchise'::character varying, 'professional'::character varying]::text[]));
ALTER TABLE "public"."platform_feature_rollout_audit" ADD CONSTRAINT "platform_feature_rollout_audit_changed_by_fkey" FOREIGN KEY (changed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."platform_onboarding_settings" ADD CONSTRAINT "platform_onboarding_settings_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."platform_owner_audit" ADD CONSTRAINT "platform_owner_audit_action_check" CHECK (action::text = ANY (ARRAY['added'::character varying, 'removed'::character varying]::text[]));
ALTER TABLE "public"."platform_owner_audit" ADD CONSTRAINT "platform_owner_audit_actor_user_id_fkey" FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."platform_owner_audit" ADD CONSTRAINT "platform_owner_audit_target_user_id_fkey" FOREIGN KEY (target_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."platform_owners" ADD CONSTRAINT "platform_owners_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."platform_playground_features" ADD CONSTRAINT "platform_playground_features_feature_key_fkey" FOREIGN KEY (feature_key) REFERENCES platform_feature_flags(feature_key) ON DELETE CASCADE;
ALTER TABLE "public"."platform_playground_features" ADD CONSTRAINT "platform_playground_features_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."platform_showcase_verticals" ADD CONSTRAINT "platform_showcase_verticals_palette_chk" CHECK (palette_key::text = ANY (ARRAY['signature'::character varying, 'warm'::character varying, 'modern'::character varying, 'classic'::character varying, 'minimal'::character varying]::text[]));
ALTER TABLE "public"."productized_network_settings" ADD CONSTRAINT "productized_network_settings_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."productized_network_settings" ADD CONSTRAINT "productized_network_settings_template_id_check" CHECK (template_id::text = ANY (ARRAY['association'::character varying, 'family-association'::character varying, 'housing-society'::character varying, 'organization'::character varying, 'business-trust'::character varying, 'franchise'::character varying, 'professional'::character varying]::text[]));
ALTER TABLE "public"."user_feature_discoveries" ADD CONSTRAINT "user_feature_discoveries_feature_key_fkey" FOREIGN KEY (feature_key) REFERENCES platform_feature_flags(feature_key) ON DELETE CASCADE;
ALTER TABLE "public"."user_feature_discoveries" ADD CONSTRAINT "user_feature_discoveries_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
