-- TRUSTWEAVE D12 CANONICAL CURRENT-STATE BASELINE.
-- Materialized after fresh-project structural/security/API/behavior/product parity on 2026-09-20.
-- DO NOT apply these files to the historical golden project as an upgrade sequence.
-- Historical supabase/migrations/001..123 remain immutable upgrade history.

ALTER TABLE "public"."cross_network_discovery_candidates" ADD CONSTRAINT "cross_network_discovery_candidates_bridge_id_fkey" FOREIGN KEY (bridge_id) REFERENCES network_trust_bridges(id) ON DELETE CASCADE;
ALTER TABLE "public"."cross_network_discovery_candidates" ADD CONSTRAINT "cross_network_discovery_candidates_path_depth_check" CHECK (path_depth = ANY (ARRAY[1, 2]));
ALTER TABLE "public"."cross_network_discovery_candidates" ADD CONSTRAINT "cross_network_discovery_candidates_requester_user_id_fkey" FOREIGN KEY (requester_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."cross_network_discovery_candidates" ADD CONSTRAINT "cross_network_discovery_candidates_source_network_id_fkey" FOREIGN KEY (source_network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."cross_network_discovery_candidates" ADD CONSTRAINT "cross_network_discovery_candidates_target_entity_id_fkey" FOREIGN KEY (target_entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."cross_network_discovery_candidates" ADD CONSTRAINT "cross_network_discovery_candidates_target_network_id_fkey" FOREIGN KEY (target_network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."cross_network_discovery_candidates" ADD CONSTRAINT "cross_network_discovery_candidates_target_user_id_fkey" FOREIGN KEY (target_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_introduction_outcomes" ADD CONSTRAINT "federated_introduction_outcomes_actor_role_check" CHECK (actor_role::text = ANY (ARRAY['requester'::character varying, 'recipient'::character varying]::text[]));
ALTER TABLE "public"."federated_introduction_outcomes" ADD CONSTRAINT "federated_introduction_outcomes_actor_user_id_fkey" FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_introduction_outcomes" ADD CONSTRAINT "federated_introduction_outcomes_introduction_id_fkey" FOREIGN KEY (introduction_id) REFERENCES federated_introductions(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_introduction_outcomes" ADD CONSTRAINT "federated_introduction_outcomes_outcome_code_check" CHECK (outcome_code::text = ANY (ARRAY['connected'::character varying, 'helpful'::character varying, 'resolved'::character varying, 'not_resolved'::character varying, 'no_follow_up'::character varying]::text[]));
ALTER TABLE "public"."federated_introduction_outcomes" ADD CONSTRAINT "federated_introduction_outcomes_receipt_id_fkey" FOREIGN KEY (receipt_id) REFERENCES federated_trust_receipts(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_introductions" ADD CONSTRAINT "federated_introductions_message_check" CHECK (length(TRIM(BOTH FROM message)) >= 3 AND length(TRIM(BOTH FROM message)) <= 800);
ALTER TABLE "public"."federated_introductions" ADD CONSTRAINT "federated_introductions_request_id_fkey" FOREIGN KEY (request_id) REFERENCES federated_requests(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_introductions" ADD CONSTRAINT "federated_introductions_requester_alias_check" CHECK (length(TRIM(BOTH FROM requester_alias)) >= 2 AND length(TRIM(BOTH FROM requester_alias)) <= 180);
ALTER TABLE "public"."federated_introductions" ADD CONSTRAINT "federated_introductions_requester_contact_note_check" CHECK (length(TRIM(BOTH FROM requester_contact_note)) >= 3 AND length(TRIM(BOTH FROM requester_contact_note)) <= 320);
ALTER TABLE "public"."federated_introductions" ADD CONSTRAINT "federated_introductions_requester_user_id_fkey" FOREIGN KEY (requester_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_introductions" ADD CONSTRAINT "federated_introductions_route_id_fkey" FOREIGN KEY (route_id) REFERENCES federated_request_routes(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_introductions" ADD CONSTRAINT "federated_introductions_status_check" CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'declined'::character varying, 'cancelled'::character varying]::text[]));
ALTER TABLE "public"."federated_introductions" ADD CONSTRAINT "federated_introductions_target_scope_profile_id_fkey" FOREIGN KEY (target_scope_profile_id) REFERENCES federated_scope_profiles(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_introductions" ADD CONSTRAINT "federated_introductions_target_user_id_fkey" FOREIGN KEY (target_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_request_routes" ADD CONSTRAINT "federated_request_routes_request_id_fkey" FOREIGN KEY (request_id) REFERENCES federated_requests(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_request_routes" ADD CONSTRAINT "federated_request_routes_score_check" CHECK (score >= 0 AND score <= 100);
ALTER TABLE "public"."federated_request_routes" ADD CONSTRAINT "federated_request_routes_status_check" CHECK (status::text = ANY (ARRAY['suggested'::character varying, 'shortlisted'::character varying, 'dismissed'::character varying]::text[]));
ALTER TABLE "public"."federated_request_routes" ADD CONSTRAINT "federated_request_routes_target_scope_profile_id_fkey" FOREIGN KEY (target_scope_profile_id) REFERENCES federated_scope_profiles(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_requests" ADD CONSTRAINT "federated_requests_requester_user_id_fkey" FOREIGN KEY (requester_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_requests" ADD CONSTRAINT "federated_requests_scope_key_check" CHECK (length(TRIM(BOTH FROM scope_key)) >= 2 AND length(TRIM(BOTH FROM scope_key)) <= 48);
ALTER TABLE "public"."federated_requests" ADD CONSTRAINT "federated_requests_source_network_id_fkey" FOREIGN KEY (source_network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_requests" ADD CONSTRAINT "federated_requests_status_check" CHECK (status::text = ANY (ARRAY['open'::character varying, 'closed'::character varying, 'cancelled'::character varying]::text[]));
ALTER TABLE "public"."federated_requests" ADD CONSTRAINT "federated_requests_tags_check" CHECK (COALESCE(array_length(tags, 1), 0) <= 12);
ALTER TABLE "public"."federated_requests" ADD CONSTRAINT "federated_requests_title_check" CHECK (length(TRIM(BOTH FROM title)) >= 3 AND length(TRIM(BOTH FROM title)) <= 180);
ALTER TABLE "public"."federated_requests" ADD CONSTRAINT "federated_requests_umbrella_id_fkey" FOREIGN KEY (umbrella_id) REFERENCES federation_umbrellas(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_scope_profiles" ADD CONSTRAINT "federated_scope_profiles_contact_mode_check" CHECK (contact_mode::text = ANY (ARRAY['introduction_only'::character varying, 'direct_request'::character varying]::text[]));
ALTER TABLE "public"."federated_scope_profiles" ADD CONSTRAINT "federated_scope_profiles_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_scope_profiles" ADD CONSTRAINT "federated_scope_profiles_owner_user_id_fkey" FOREIGN KEY (owner_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_scope_profiles" ADD CONSTRAINT "federated_scope_profiles_scope_key_check" CHECK (length(TRIM(BOTH FROM scope_key)) >= 2 AND length(TRIM(BOTH FROM scope_key)) <= 48);
ALTER TABLE "public"."federated_scope_profiles" ADD CONSTRAINT "federated_scope_profiles_tags_check" CHECK (COALESCE(array_length(tags, 1), 0) <= 12);
ALTER TABLE "public"."federated_scope_profiles" ADD CONSTRAINT "federated_scope_profiles_umbrella_id_fkey" FOREIGN KEY (umbrella_id) REFERENCES federation_umbrellas(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_trust_receipts" ADD CONSTRAINT "federated_trust_receipts_introduction_id_fkey" FOREIGN KEY (introduction_id) REFERENCES federated_introductions(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_trust_receipts" ADD CONSTRAINT "federated_trust_receipts_request_id_fkey" FOREIGN KEY (request_id) REFERENCES federated_requests(id) ON DELETE CASCADE;
ALTER TABLE "public"."federated_trust_receipts" ADD CONSTRAINT "federated_trust_receipts_route_id_fkey" FOREIGN KEY (route_id) REFERENCES federated_request_routes(id) ON DELETE CASCADE;
ALTER TABLE "public"."federation_umbrella_admins" ADD CONSTRAINT "federation_umbrella_admins_role_check" CHECK (role::text = ANY (ARRAY['owner'::character varying, 'admin'::character varying]::text[]));
ALTER TABLE "public"."federation_umbrella_admins" ADD CONSTRAINT "federation_umbrella_admins_status_check" CHECK (status::text = ANY (ARRAY['active'::character varying, 'suspended'::character varying]::text[]));
ALTER TABLE "public"."federation_umbrella_admins" ADD CONSTRAINT "federation_umbrella_admins_umbrella_id_fkey" FOREIGN KEY (umbrella_id) REFERENCES federation_umbrellas(id) ON DELETE CASCADE;
ALTER TABLE "public"."federation_umbrella_admins" ADD CONSTRAINT "federation_umbrella_admins_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."federation_umbrellas" ADD CONSTRAINT "federation_umbrellas_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."federation_umbrellas" ADD CONSTRAINT "federation_umbrellas_slug_check" CHECK (slug::text ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text);
ALTER TABLE "public"."federation_umbrellas" ADD CONSTRAINT "federation_umbrellas_status_check" CHECK (status::text = ANY (ARRAY['active'::character varying, 'archived'::character varying]::text[]));
ALTER TABLE "public"."federation_umbrellas" ADD CONSTRAINT "federation_umbrellas_umbrella_type_check" CHECK (umbrella_type::text = ANY (ARRAY['community'::character varying, 'association'::character varying, 'federation'::character varying, 'institution'::character varying, 'ecosystem'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."network_effect_events" ADD CONSTRAINT "network_effect_events_actor_user_id_fkey" FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_effect_events" ADD CONSTRAINT "network_effect_events_bridge_id_fkey" FOREIGN KEY (bridge_id) REFERENCES network_trust_bridges(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_effect_events" ADD CONSTRAINT "network_effect_events_event_count_check" CHECK (event_count >= 1 AND event_count <= 1000);
ALTER TABLE "public"."network_effect_events" ADD CONSTRAINT "network_effect_events_event_type_check" CHECK (event_type::text = ANY (ARRAY['discovery_search'::character varying, 'discovery_opportunity'::character varying, 'trusted_path_opportunity'::character varying, 'introduction_requested'::character varying, 'introduction_accepted'::character varying, 'introduction_declined'::character varying]::text[]));
ALTER TABLE "public"."network_effect_events" ADD CONSTRAINT "network_effect_events_source_network_id_fkey" FOREIGN KEY (source_network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_passports" ADD CONSTRAINT "network_passports_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_passports" ADD CONSTRAINT "network_passports_external_url_check" CHECK (external_url::text = ''::text OR external_url::text ~ '^https://'::text);
ALTER TABLE "public"."network_passports" ADD CONSTRAINT "network_passports_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_passports" ADD CONSTRAINT "network_passports_public_slug_check" CHECK (public_slug::text ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text);
ALTER TABLE "public"."network_passports" ADD CONSTRAINT "network_passports_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_passports" ADD CONSTRAINT "network_passports_verification_state_check" CHECK (verification_state::text = ANY (ARRAY['self_declared'::character varying, 'network_admin_reviewed'::character varying]::text[]));
ALTER TABLE "public"."network_passports" ADD CONSTRAINT "network_passports_visibility_check" CHECK (visibility::text = ANY (ARRAY['private'::character varying, 'federation'::character varying, 'public'::character varying]::text[]));
ALTER TABLE "public"."network_trust_bridges" ADD CONSTRAINT "network_trust_bridges_capabilities_check" CHECK (jsonb_typeof(capabilities) = 'object'::text);
ALTER TABLE "public"."network_trust_bridges" ADD CONSTRAINT "network_trust_bridges_check" CHECK (requester_network_id <> recipient_network_id);
ALTER TABLE "public"."network_trust_bridges" ADD CONSTRAINT "network_trust_bridges_recipient_network_id_fkey" FOREIGN KEY (recipient_network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_trust_bridges" ADD CONSTRAINT "network_trust_bridges_relationship_type_check" CHECK (relationship_type::text = ANY (ARRAY['affiliation'::character varying, 'community'::character varying, 'partner'::character varying, 'parent_child'::character varying, 'trusted_peer'::character varying]::text[]));
ALTER TABLE "public"."network_trust_bridges" ADD CONSTRAINT "network_trust_bridges_requested_by_fkey" FOREIGN KEY (requested_by) REFERENCES auth.users(id);
ALTER TABLE "public"."network_trust_bridges" ADD CONSTRAINT "network_trust_bridges_requester_network_id_fkey" FOREIGN KEY (requester_network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_trust_bridges" ADD CONSTRAINT "network_trust_bridges_reviewed_by_fkey" FOREIGN KEY (reviewed_by) REFERENCES auth.users(id);
ALTER TABLE "public"."network_trust_bridges" ADD CONSTRAINT "network_trust_bridges_revoked_by_fkey" FOREIGN KEY (revoked_by) REFERENCES auth.users(id);
ALTER TABLE "public"."network_trust_bridges" ADD CONSTRAINT "network_trust_bridges_status_check" CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'declined'::character varying, 'revoked'::character varying]::text[]));
ALTER TABLE "public"."network_umbrella_affiliations" ADD CONSTRAINT "network_umbrella_affiliations_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."network_umbrella_affiliations" ADD CONSTRAINT "network_umbrella_affiliations_relationship_type_check" CHECK (relationship_type::text = ANY (ARRAY['member'::character varying, 'chapter'::character varying, 'affiliate'::character varying, 'constituent'::character varying, 'franchisee'::character varying, 'partner'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."network_umbrella_affiliations" ADD CONSTRAINT "network_umbrella_affiliations_requested_by_fkey" FOREIGN KEY (requested_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_umbrella_affiliations" ADD CONSTRAINT "network_umbrella_affiliations_reviewed_by_fkey" FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_umbrella_affiliations" ADD CONSTRAINT "network_umbrella_affiliations_revoked_by_fkey" FOREIGN KEY (revoked_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_umbrella_affiliations" ADD CONSTRAINT "network_umbrella_affiliations_status_check" CHECK (status::text = ANY (ARRAY['requested'::character varying, 'approved'::character varying, 'declined'::character varying, 'suspended'::character varying, 'revoked'::character varying]::text[]));
ALTER TABLE "public"."network_umbrella_affiliations" ADD CONSTRAINT "network_umbrella_affiliations_suspended_by_fkey" FOREIGN KEY (suspended_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."network_umbrella_affiliations" ADD CONSTRAINT "network_umbrella_affiliations_umbrella_id_fkey" FOREIGN KEY (umbrella_id) REFERENCES federation_umbrellas(id) ON DELETE CASCADE;
ALTER TABLE "public"."trusted_introduction_requests" ADD CONSTRAINT "trusted_introduction_requests_bridge_id_fkey" FOREIGN KEY (bridge_id) REFERENCES network_trust_bridges(id) ON DELETE CASCADE;
ALTER TABLE "public"."trusted_introduction_requests" ADD CONSTRAINT "trusted_introduction_requests_candidate_id_fkey" FOREIGN KEY (candidate_id) REFERENCES cross_network_discovery_candidates(id) ON DELETE CASCADE;
ALTER TABLE "public"."trusted_introduction_requests" ADD CONSTRAINT "trusted_introduction_requests_path_depth_check" CHECK (path_depth = ANY (ARRAY[1, 2]));
ALTER TABLE "public"."trusted_introduction_requests" ADD CONSTRAINT "trusted_introduction_requests_requester_user_id_fkey" FOREIGN KEY (requester_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."trusted_introduction_requests" ADD CONSTRAINT "trusted_introduction_requests_source_network_id_fkey" FOREIGN KEY (source_network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."trusted_introduction_requests" ADD CONSTRAINT "trusted_introduction_requests_status_check" CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'declined'::character varying, 'cancelled'::character varying]::text[]));
ALTER TABLE "public"."trusted_introduction_requests" ADD CONSTRAINT "trusted_introduction_requests_target_entity_id_fkey" FOREIGN KEY (target_entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."trusted_introduction_requests" ADD CONSTRAINT "trusted_introduction_requests_target_network_id_fkey" FOREIGN KEY (target_network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."trusted_introduction_requests" ADD CONSTRAINT "trusted_introduction_requests_target_user_id_fkey" FOREIGN KEY (target_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
