-- TRUSTWEAVE D12 CANONICAL CURRENT-STATE BASELINE.
-- Materialized after fresh-project structural/security/API/behavior/product parity on 2026-09-20.
-- DO NOT apply these files to the historical golden project as an upgrade sequence.
-- Historical supabase/migrations/001..123 remain immutable upgrade history.

ALTER TABLE "public"."hs_amenities" ADD CONSTRAINT "hs_amenities_booking_mode_check" CHECK (booking_mode::text = ANY (ARRAY['approval'::character varying, 'instant'::character varying, 'disabled'::character varying]::text[]));
ALTER TABLE "public"."hs_amenities" ADD CONSTRAINT "hs_amenities_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_amenities" ADD CONSTRAINT "hs_amenities_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_amenities" ADD CONSTRAINT "hs_amenities_status_check" CHECK (status::text = ANY (ARRAY['active'::character varying, 'maintenance'::character varying, 'inactive'::character varying]::text[]));
ALTER TABLE "public"."hs_amenity_bookings" ADD CONSTRAINT "hs_amenity_bookings_amenity_id_fkey" FOREIGN KEY (amenity_id) REFERENCES hs_amenities(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_amenity_bookings" ADD CONSTRAINT "hs_amenity_bookings_check" CHECK (ends_at > starts_at);
ALTER TABLE "public"."hs_amenity_bookings" ADD CONSTRAINT "hs_amenity_bookings_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_amenity_bookings" ADD CONSTRAINT "hs_amenity_bookings_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_amenity_bookings" ADD CONSTRAINT "hs_amenity_bookings_reviewed_by_fkey" FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_amenity_bookings" ADD CONSTRAINT "hs_amenity_bookings_status_check" CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'cancelled'::character varying, 'completed'::character varying]::text[]));
ALTER TABLE "public"."hs_amenity_bookings" ADD CONSTRAINT "hs_amenity_bookings_unit_entity_id_fkey" FOREIGN KEY (unit_entity_id) REFERENCES network_entities(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_asset_service_records" ADD CONSTRAINT "hs_asset_service_records_asset_id_fkey" FOREIGN KEY (asset_id) REFERENCES hs_assets(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_asset_service_records" ADD CONSTRAINT "hs_asset_service_records_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_asset_service_records" ADD CONSTRAINT "hs_asset_service_records_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_asset_service_records" ADD CONSTRAINT "hs_asset_service_records_vendor_id_fkey" FOREIGN KEY (vendor_id) REFERENCES hs_vendors(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_assets" ADD CONSTRAINT "hs_assets_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_assets" ADD CONSTRAINT "hs_assets_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_assets" ADD CONSTRAINT "hs_assets_status_check" CHECK (status::text = ANY (ARRAY['active'::character varying, 'maintenance'::character varying, 'inactive'::character varying, 'retired'::character varying]::text[]));
ALTER TABLE "public"."hs_assets" ADD CONSTRAINT "hs_assets_vendor_id_fkey" FOREIGN KEY (vendor_id) REFERENCES hs_vendors(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_bill_adjustments" ADD CONSTRAINT "hs_bill_adjustments_adjustment_type_check" CHECK (adjustment_type::text = ANY (ARRAY['credit'::character varying, 'debit'::character varying, 'waiver'::character varying, 'penalty'::character varying]::text[]));
ALTER TABLE "public"."hs_bill_adjustments" ADD CONSTRAINT "hs_bill_adjustments_amount_check" CHECK (amount >= 0::numeric);
ALTER TABLE "public"."hs_bill_adjustments" ADD CONSTRAINT "hs_bill_adjustments_bill_id_fkey" FOREIGN KEY (bill_id) REFERENCES hs_unit_bills(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_bill_adjustments" ADD CONSTRAINT "hs_bill_adjustments_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_bill_adjustments" ADD CONSTRAINT "hs_bill_adjustments_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_bill_line_items" ADD CONSTRAINT "hs_bill_line_items_bill_id_fkey" FOREIGN KEY (bill_id) REFERENCES hs_unit_bills(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_bill_line_items" ADD CONSTRAINT "hs_bill_line_items_charge_head_id_fkey" FOREIGN KEY (charge_head_id) REFERENCES hs_charge_heads(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_bill_line_items" ADD CONSTRAINT "hs_bill_line_items_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_billing_cycles" ADD CONSTRAINT "hs_billing_cycles_check" CHECK (period_end >= period_start);
ALTER TABLE "public"."hs_billing_cycles" ADD CONSTRAINT "hs_billing_cycles_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_billing_cycles" ADD CONSTRAINT "hs_billing_cycles_grace_days_check" CHECK (grace_days >= 0 AND grace_days <= 90);
ALTER TABLE "public"."hs_billing_cycles" ADD CONSTRAINT "hs_billing_cycles_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_billing_cycles" ADD CONSTRAINT "hs_billing_cycles_penalty_rate_monthly_check" CHECK (penalty_rate_monthly >= 0::numeric);
ALTER TABLE "public"."hs_billing_cycles" ADD CONSTRAINT "hs_billing_cycles_status_check" CHECK (status::text = ANY (ARRAY['draft'::character varying, 'issued'::character varying, 'closed'::character varying, 'cancelled'::character varying]::text[]));
ALTER TABLE "public"."hs_budget_lines" ADD CONSTRAINT "hs_budget_lines_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_budget_lines" ADD CONSTRAINT "hs_budget_lines_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_budget_lines" ADD CONSTRAINT "hs_budget_lines_visibility_check" CHECK (visibility::text = ANY (ARRAY['admin'::character varying, 'members'::character varying]::text[]));
ALTER TABLE "public"."hs_charge_heads" ADD CONSTRAINT "hs_charge_heads_calculation_mode_check" CHECK (calculation_mode::text = ANY (ARRAY['fixed_per_unit'::character varying, 'manual'::character varying]::text[]));
ALTER TABLE "public"."hs_charge_heads" ADD CONSTRAINT "hs_charge_heads_category_check" CHECK (category::text = ANY (ARRAY['maintenance'::character varying, 'sinking_fund'::character varying, 'repair_fund'::character varying, 'parking'::character varying, 'water'::character varying, 'common_electricity'::character varying, 'non_occupancy'::character varying, 'special_assessment'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."hs_charge_heads" ADD CONSTRAINT "hs_charge_heads_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_charge_heads" ADD CONSTRAINT "hs_charge_heads_default_amount_check" CHECK (default_amount >= 0::numeric);
ALTER TABLE "public"."hs_charge_heads" ADD CONSTRAINT "hs_charge_heads_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_committee_assignments" ADD CONSTRAINT "hs_committee_assignments_check" CHECK (ends_on IS NULL OR ends_on >= starts_on);
ALTER TABLE "public"."hs_committee_assignments" ADD CONSTRAINT "hs_committee_assignments_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_committee_assignments" ADD CONSTRAINT "hs_committee_assignments_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_committee_assignments" ADD CONSTRAINT "hs_committee_assignments_person_entity_id_fkey" FOREIGN KEY (person_entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_committee_assignments" ADD CONSTRAINT "hs_committee_assignments_role_key_check" CHECK (role_key::text = ANY (ARRAY['chairperson'::character varying, 'secretary'::character varying, 'treasurer'::character varying, 'committee_member'::character varying, 'manager'::character varying, 'auditor'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."hs_committee_assignments" ADD CONSTRAINT "hs_committee_assignments_term_id_fkey" FOREIGN KEY (term_id) REFERENCES hs_committee_terms(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_committee_terms" ADD CONSTRAINT "hs_committee_terms_check" CHECK (ends_on IS NULL OR ends_on >= starts_on);
ALTER TABLE "public"."hs_committee_terms" ADD CONSTRAINT "hs_committee_terms_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_committee_terms" ADD CONSTRAINT "hs_committee_terms_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_committee_terms" ADD CONSTRAINT "hs_committee_terms_status_check" CHECK (status::text = ANY (ARRAY['planned'::character varying, 'active'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[]));
ALTER TABLE "public"."hs_complaint_comments" ADD CONSTRAINT "hs_complaint_comments_complaint_id_fkey" FOREIGN KEY (complaint_id) REFERENCES hs_complaints(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_complaint_comments" ADD CONSTRAINT "hs_complaint_comments_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_complaint_comments" ADD CONSTRAINT "hs_complaint_comments_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_complaint_routes" ADD CONSTRAINT "hs_complaint_routes_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_complaint_routes" ADD CONSTRAINT "hs_complaint_routes_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_complaints" ADD CONSTRAINT "hs_complaints_assigned_to_fkey" FOREIGN KEY (assigned_to) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_complaints" ADD CONSTRAINT "hs_complaints_assigned_vendor_id_fkey" FOREIGN KEY (assigned_vendor_id) REFERENCES hs_vendors(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_complaints" ADD CONSTRAINT "hs_complaints_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_complaints" ADD CONSTRAINT "hs_complaints_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_complaints" ADD CONSTRAINT "hs_complaints_priority_check" CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[]));
ALTER TABLE "public"."hs_complaints" ADD CONSTRAINT "hs_complaints_status_check" CHECK (status::text = ANY (ARRAY['open'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying, 'reopened'::character varying]::text[]));
ALTER TABLE "public"."hs_complaints" ADD CONSTRAINT "hs_complaints_unit_entity_id_fkey" FOREIGN KEY (unit_entity_id) REFERENCES network_entities(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_compliance_items" ADD CONSTRAINT "hs_compliance_items_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_compliance_items" ADD CONSTRAINT "hs_compliance_items_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_compliance_items" ADD CONSTRAINT "hs_compliance_items_status_check" CHECK (status::text = ANY (ARRAY['open'::character varying, 'renewed'::character varying, 'completed'::character varying, 'expired'::character varying, 'not_applicable'::character varying]::text[]));
ALTER TABLE "public"."hs_compliance_items" ADD CONSTRAINT "hs_compliance_items_visibility_check" CHECK (visibility::text = ANY (ARRAY['admin'::character varying, 'members'::character varying]::text[]));
ALTER TABLE "public"."hs_domestic_staff" ADD CONSTRAINT "hs_domestic_staff_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_domestic_staff" ADD CONSTRAINT "hs_domestic_staff_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_domestic_staff" ADD CONSTRAINT "hs_domestic_staff_staff_type_check" CHECK (staff_type::text = ANY (ARRAY['maid'::character varying, 'driver'::character varying, 'cook'::character varying, 'nanny'::character varying, 'caregiver'::character varying, 'cleaner'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."hs_domestic_staff" ADD CONSTRAINT "hs_domestic_staff_verification_status_check" CHECK (verification_status::text = ANY (ARRAY['pending'::character varying, 'verified'::character varying, 'expired'::character varying, 'rejected'::character varying]::text[]));
ALTER TABLE "public"."hs_emergency_contacts" ADD CONSTRAINT "hs_emergency_contacts_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_emergency_contacts" ADD CONSTRAINT "hs_emergency_contacts_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_expenses" ADD CONSTRAINT "hs_expenses_amount_check" CHECK (amount > 0::numeric);
ALTER TABLE "public"."hs_expenses" ADD CONSTRAINT "hs_expenses_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_expenses" ADD CONSTRAINT "hs_expenses_fund_id_fkey" FOREIGN KEY (fund_id) REFERENCES hs_funds(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_expenses" ADD CONSTRAINT "hs_expenses_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_expenses" ADD CONSTRAINT "hs_expenses_vendor_id_fkey" FOREIGN KEY (vendor_id) REFERENCES hs_vendors(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_expenses" ADD CONSTRAINT "hs_expenses_visibility_check" CHECK (visibility::text = ANY (ARRAY['admin'::character varying, 'members'::character varying]::text[]));
ALTER TABLE "public"."hs_funds" ADD CONSTRAINT "hs_funds_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_funds" ADD CONSTRAINT "hs_funds_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_funds" ADD CONSTRAINT "hs_funds_visibility_check" CHECK (visibility::text = ANY (ARRAY['admin'::character varying, 'members'::character varying]::text[]));
ALTER TABLE "public"."hs_governance_action_items" ADD CONSTRAINT "hs_governance_action_items_agenda_item_id_fkey" FOREIGN KEY (agenda_item_id) REFERENCES hs_meeting_agenda_items(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_governance_action_items" ADD CONSTRAINT "hs_governance_action_items_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_governance_action_items" ADD CONSTRAINT "hs_governance_action_items_meeting_id_fkey" FOREIGN KEY (meeting_id) REFERENCES hs_governance_meetings(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_governance_action_items" ADD CONSTRAINT "hs_governance_action_items_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_governance_action_items" ADD CONSTRAINT "hs_governance_action_items_owner_user_id_fkey" FOREIGN KEY (owner_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_governance_action_items" ADD CONSTRAINT "hs_governance_action_items_status_check" CHECK (status::text = ANY (ARRAY['open'::character varying, 'in_progress'::character varying, 'done'::character varying, 'cancelled'::character varying]::text[]));
ALTER TABLE "public"."hs_governance_documents" ADD CONSTRAINT "hs_governance_documents_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_governance_documents" ADD CONSTRAINT "hs_governance_documents_document_type_check" CHECK (document_type::text = ANY (ARRAY['agenda'::character varying, 'minutes'::character varying, 'resolution'::character varying, 'notice'::character varying, 'supporting'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."hs_governance_documents" ADD CONSTRAINT "hs_governance_documents_meeting_id_fkey" FOREIGN KEY (meeting_id) REFERENCES hs_governance_meetings(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_governance_documents" ADD CONSTRAINT "hs_governance_documents_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_governance_documents" ADD CONSTRAINT "hs_governance_documents_resolution_id_fkey" FOREIGN KEY (resolution_id) REFERENCES hs_resolutions(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_governance_documents" ADD CONSTRAINT "hs_governance_documents_visibility_check" CHECK (visibility::text = ANY (ARRAY['admin'::character varying, 'members'::character varying]::text[]));
ALTER TABLE "public"."hs_governance_meetings" ADD CONSTRAINT "hs_governance_meetings_attendee_count_check" CHECK (attendee_count IS NULL OR attendee_count >= 0);
ALTER TABLE "public"."hs_governance_meetings" ADD CONSTRAINT "hs_governance_meetings_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_governance_meetings" ADD CONSTRAINT "hs_governance_meetings_meeting_type_check" CHECK (meeting_type::text = ANY (ARRAY['committee'::character varying, 'agm'::character varying, 'sgm'::character varying, 'general'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."hs_governance_meetings" ADD CONSTRAINT "hs_governance_meetings_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_governance_meetings" ADD CONSTRAINT "hs_governance_meetings_quorum_required_check" CHECK (quorum_required IS NULL OR quorum_required >= 0);
ALTER TABLE "public"."hs_governance_meetings" ADD CONSTRAINT "hs_governance_meetings_status_check" CHECK (status::text = ANY (ARRAY['draft'::character varying, 'scheduled'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[]));
ALTER TABLE "public"."hs_import_batches" ADD CONSTRAINT "hs_import_batches_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_import_batches" ADD CONSTRAINT "hs_import_batches_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_import_batches" ADD CONSTRAINT "hs_import_batches_status_check" CHECK (status::text = ANY (ARRAY['preview'::character varying, 'committed'::character varying, 'failed'::character varying]::text[]));
ALTER TABLE "public"."hs_meeting_agenda_items" ADD CONSTRAINT "hs_meeting_agenda_items_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_meeting_agenda_items" ADD CONSTRAINT "hs_meeting_agenda_items_item_order_check" CHECK (item_order > 0);
ALTER TABLE "public"."hs_meeting_agenda_items" ADD CONSTRAINT "hs_meeting_agenda_items_meeting_id_fkey" FOREIGN KEY (meeting_id) REFERENCES hs_governance_meetings(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_meeting_agenda_items" ADD CONSTRAINT "hs_meeting_agenda_items_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_move_requests" ADD CONSTRAINT "hs_move_requests_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_move_requests" ADD CONSTRAINT "hs_move_requests_move_type_check" CHECK (move_type::text = ANY (ARRAY['move_in'::character varying, 'move_out'::character varying]::text[]));
ALTER TABLE "public"."hs_move_requests" ADD CONSTRAINT "hs_move_requests_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_move_requests" ADD CONSTRAINT "hs_move_requests_reviewed_by_fkey" FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_move_requests" ADD CONSTRAINT "hs_move_requests_status_check" CHECK (status::text = ANY (ARRAY['requested'::character varying, 'approved'::character varying, 'rejected'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[]));
ALTER TABLE "public"."hs_move_requests" ADD CONSTRAINT "hs_move_requests_unit_entity_id_fkey" FOREIGN KEY (unit_entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_notice_reads" ADD CONSTRAINT "hs_notice_reads_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_notice_reads" ADD CONSTRAINT "hs_notice_reads_notice_id_fkey" FOREIGN KEY (notice_id) REFERENCES hs_notices(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_notice_reads" ADD CONSTRAINT "hs_notice_reads_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_notices" ADD CONSTRAINT "hs_notices_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_notices" ADD CONSTRAINT "hs_notices_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_notices" ADD CONSTRAINT "hs_notices_notice_type_check" CHECK (notice_type::text = ANY (ARRAY['general'::character varying, 'urgent'::character varying, 'targeted'::character varying]::text[]));
ALTER TABLE "public"."hs_parking_allocations" ADD CONSTRAINT "hs_parking_allocations_allocation_type_check" CHECK (allocation_type::text = ANY (ARRAY['assigned'::character varying, 'temporary'::character varying, 'visitor'::character varying]::text[]));
ALTER TABLE "public"."hs_parking_allocations" ADD CONSTRAINT "hs_parking_allocations_check" CHECK (ends_on IS NULL OR ends_on >= starts_on);
ALTER TABLE "public"."hs_parking_allocations" ADD CONSTRAINT "hs_parking_allocations_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_parking_allocations" ADD CONSTRAINT "hs_parking_allocations_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_parking_allocations" ADD CONSTRAINT "hs_parking_allocations_parking_slot_id_fkey" FOREIGN KEY (parking_slot_id) REFERENCES hs_parking_slots(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_parking_allocations" ADD CONSTRAINT "hs_parking_allocations_unit_entity_id_fkey" FOREIGN KEY (unit_entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_parking_allocations" ADD CONSTRAINT "hs_parking_allocations_vehicle_id_fkey" FOREIGN KEY (vehicle_id) REFERENCES hs_vehicles(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_parking_slots" ADD CONSTRAINT "hs_parking_slots_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_parking_slots" ADD CONSTRAINT "hs_parking_slots_slot_type_check" CHECK (slot_type::text = ANY (ARRAY['car'::character varying, 'two-wheeler'::character varying, 'visitor'::character varying, 'accessible'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."hs_parking_slots" ADD CONSTRAINT "hs_parking_slots_status_check" CHECK (status::text = ANY (ARRAY['available'::character varying, 'allocated'::character varying, 'blocked'::character varying, 'inactive'::character varying]::text[]));
ALTER TABLE "public"."hs_payments" ADD CONSTRAINT "hs_payments_amount_check" CHECK (amount > 0::numeric);
ALTER TABLE "public"."hs_payments" ADD CONSTRAINT "hs_payments_bill_id_fkey" FOREIGN KEY (bill_id) REFERENCES hs_unit_bills(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_payments" ADD CONSTRAINT "hs_payments_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_payments" ADD CONSTRAINT "hs_payments_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_payments" ADD CONSTRAINT "hs_payments_payment_mode_check" CHECK (payment_mode::text = ANY (ARRAY['manual'::character varying, 'cash'::character varying, 'cheque'::character varying, 'bank_transfer'::character varying, 'upi'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."hs_payments" ADD CONSTRAINT "hs_payments_status_check" CHECK (status::text = ANY (ARRAY['recorded'::character varying, 'reversed'::character varying]::text[]));
ALTER TABLE "public"."hs_payments" ADD CONSTRAINT "hs_payments_unit_entity_id_fkey" FOREIGN KEY (unit_entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_pilot_checkpoints" ADD CONSTRAINT "hs_pilot_checkpoints_admin_hours_saved_check" CHECK (admin_hours_saved IS NULL OR admin_hours_saved >= 0::numeric);
ALTER TABLE "public"."hs_pilot_checkpoints" ADD CONSTRAINT "hs_pilot_checkpoints_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_pilot_checkpoints" ADD CONSTRAINT "hs_pilot_checkpoints_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_pilot_checkpoints" ADD CONSTRAINT "hs_pilot_checkpoints_offline_operations_remaining_check" CHECK (offline_operations_remaining IS NULL OR offline_operations_remaining >= 0);
ALTER TABLE "public"."hs_pilot_checkpoints" ADD CONSTRAINT "hs_pilot_checkpoints_pilot_run_id_fkey" FOREIGN KEY (pilot_run_id) REFERENCES hs_pilot_runs(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_pilot_checkpoints" ADD CONSTRAINT "hs_pilot_checkpoints_renewal_intent_check" CHECK (renewal_intent::text = ANY (ARRAY['unknown'::character varying, 'no'::character varying, 'maybe'::character varying, 'yes'::character varying]::text[]));
ALTER TABLE "public"."hs_pilot_checkpoints" ADD CONSTRAINT "hs_pilot_checkpoints_willingness_to_pay_check" CHECK (willingness_to_pay::text = ANY (ARRAY['unknown'::character varying, 'no'::character varying, 'maybe'::character varying, 'yes'::character varying]::text[]));
ALTER TABLE "public"."hs_pilot_pricing_experiments" ADD CONSTRAINT "hs_pilot_pricing_experiments_amount_check" CHECK (amount IS NULL OR amount >= 0::numeric);
ALTER TABLE "public"."hs_pilot_pricing_experiments" ADD CONSTRAINT "hs_pilot_pricing_experiments_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_pilot_pricing_experiments" ADD CONSTRAINT "hs_pilot_pricing_experiments_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_pilot_pricing_experiments" ADD CONSTRAINT "hs_pilot_pricing_experiments_pilot_run_id_fkey" FOREIGN KEY (pilot_run_id) REFERENCES hs_pilot_runs(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_pilot_pricing_experiments" ADD CONSTRAINT "hs_pilot_pricing_experiments_pricing_model_check" CHECK (pricing_model::text = ANY (ARRAY['per_unit_month'::character varying, 'society_annual'::character varying, 'base_plus_modules'::character varying, 'setup_fee'::character varying, 'undecided'::character varying]::text[]));
ALTER TABLE "public"."hs_pilot_pricing_experiments" ADD CONSTRAINT "hs_pilot_pricing_experiments_response_check" CHECK (response::text = ANY (ARRAY['untested'::character varying, 'rejected'::character varying, 'neutral'::character varying, 'interested'::character varying, 'accepted'::character varying]::text[]));
ALTER TABLE "public"."hs_pilot_runs" ADD CONSTRAINT "hs_pilot_runs_check" CHECK (ended_on IS NULL OR started_on IS NULL OR ended_on >= started_on);
ALTER TABLE "public"."hs_pilot_runs" ADD CONSTRAINT "hs_pilot_runs_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_pilot_runs" ADD CONSTRAINT "hs_pilot_runs_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_pilot_runs" ADD CONSTRAINT "hs_pilot_runs_phase_check" CHECK (phase::text = ANY (ARRAY['A'::character varying, 'B'::character varying, 'C'::character varying, 'D'::character varying]::text[]));
ALTER TABLE "public"."hs_pilot_runs" ADD CONSTRAINT "hs_pilot_runs_status_check" CHECK (status::text = ANY (ARRAY['planning'::character varying, 'active'::character varying, 'paused'::character varying, 'completed'::character varying, 'stopped'::character varying]::text[]));
ALTER TABLE "public"."hs_pilot_runs" ADD CONSTRAINT "hs_pilot_runs_target_units_check" CHECK (target_units >= 1 AND target_units <= 5000);
ALTER TABLE "public"."hs_pilot_usage_events" ADD CONSTRAINT "hs_pilot_usage_events_event_key_check" CHECK (event_key::text = ANY (ARRAY['home_view'::character varying, 'my_flat_view'::character varying, 'directory_view'::character varying, 'notice_view'::character varying, 'complaint_view'::character varying, 'maintenance_view'::character varying, 'amenity_view'::character varying, 'governance_view'::character varying, 'security_view'::character varying, 'pilot_export'::character varying]::text[]));
ALTER TABLE "public"."hs_pilot_usage_events" ADD CONSTRAINT "hs_pilot_usage_events_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_pilot_usage_events" ADD CONSTRAINT "hs_pilot_usage_events_unit_entity_id_fkey" FOREIGN KEY (unit_entity_id) REFERENCES network_entities(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_pilot_usage_events" ADD CONSTRAINT "hs_pilot_usage_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_renovation_requests" ADD CONSTRAINT "hs_renovation_requests_check" CHECK (ends_on IS NULL OR starts_on IS NULL OR ends_on >= starts_on);
ALTER TABLE "public"."hs_renovation_requests" ADD CONSTRAINT "hs_renovation_requests_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_renovation_requests" ADD CONSTRAINT "hs_renovation_requests_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_renovation_requests" ADD CONSTRAINT "hs_renovation_requests_reviewed_by_fkey" FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_renovation_requests" ADD CONSTRAINT "hs_renovation_requests_status_check" CHECK (status::text = ANY (ARRAY['requested'::character varying, 'approved'::character varying, 'rejected'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[]));
ALTER TABLE "public"."hs_renovation_requests" ADD CONSTRAINT "hs_renovation_requests_unit_entity_id_fkey" FOREIGN KEY (unit_entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_resident_invitations" ADD CONSTRAINT "hs_resident_invitations_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_resident_invitations" ADD CONSTRAINT "hs_resident_invitations_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_resident_invitations" ADD CONSTRAINT "hs_resident_invitations_person_entity_id_fkey" FOREIGN KEY (person_entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_resident_invitations" ADD CONSTRAINT "hs_resident_invitations_status_check" CHECK (status::text = ANY (ARRAY['pending'::character varying, 'claimed'::character varying, 'revoked'::character varying, 'expired'::character varying]::text[]));
ALTER TABLE "public"."hs_resident_invitations" ADD CONSTRAINT "hs_resident_invitations_unit_entity_id_fkey" FOREIGN KEY (unit_entity_id) REFERENCES network_entities(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_resolution_votes" ADD CONSTRAINT "hs_resolution_votes_choice_check" CHECK (choice::text = ANY (ARRAY['yes'::character varying, 'no'::character varying, 'abstain'::character varying]::text[]));
ALTER TABLE "public"."hs_resolution_votes" ADD CONSTRAINT "hs_resolution_votes_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_resolution_votes" ADD CONSTRAINT "hs_resolution_votes_resolution_id_fkey" FOREIGN KEY (resolution_id) REFERENCES hs_resolutions(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_resolution_votes" ADD CONSTRAINT "hs_resolution_votes_voter_user_id_fkey" FOREIGN KEY (voter_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_resolutions" ADD CONSTRAINT "hs_resolutions_check" CHECK (closes_at IS NULL OR opens_at IS NULL OR closes_at >= opens_at);
ALTER TABLE "public"."hs_resolutions" ADD CONSTRAINT "hs_resolutions_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_resolutions" ADD CONSTRAINT "hs_resolutions_meeting_id_fkey" FOREIGN KEY (meeting_id) REFERENCES hs_governance_meetings(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_resolutions" ADD CONSTRAINT "hs_resolutions_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_resolutions" ADD CONSTRAINT "hs_resolutions_quorum_percent_check" CHECK (quorum_percent >= 0::numeric AND quorum_percent <= 100::numeric);
ALTER TABLE "public"."hs_resolutions" ADD CONSTRAINT "hs_resolutions_status_check" CHECK (status::text = ANY (ARRAY['draft'::character varying, 'open'::character varying, 'approved'::character varying, 'rejected'::character varying, 'withdrawn'::character varying, 'closed'::character varying]::text[]));
ALTER TABLE "public"."hs_resolutions" ADD CONSTRAINT "hs_resolutions_vote_mode_check" CHECK (vote_mode::text = ANY (ARRAY['advisory'::character varying, 'approval'::character varying]::text[]));
ALTER TABLE "public"."hs_security_operator_grants" ADD CONSTRAINT "hs_security_operator_grants_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_security_operator_grants" ADD CONSTRAINT "hs_security_operator_grants_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_security_operator_grants" ADD CONSTRAINT "hs_security_operator_grants_scope_check" CHECK (scope::text = ANY (ARRAY['security'::character varying, 'facility'::character varying, 'compliance'::character varying]::text[]));
ALTER TABLE "public"."hs_security_operator_grants" ADD CONSTRAINT "hs_security_operator_grants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_staff_unit_permissions" ADD CONSTRAINT "hs_staff_unit_permissions_check" CHECK (ends_on IS NULL OR ends_on >= starts_on);
ALTER TABLE "public"."hs_staff_unit_permissions" ADD CONSTRAINT "hs_staff_unit_permissions_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_staff_unit_permissions" ADD CONSTRAINT "hs_staff_unit_permissions_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_staff_unit_permissions" ADD CONSTRAINT "hs_staff_unit_permissions_staff_id_fkey" FOREIGN KEY (staff_id) REFERENCES hs_domestic_staff(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_staff_unit_permissions" ADD CONSTRAINT "hs_staff_unit_permissions_status_check" CHECK (status::text = ANY (ARRAY['active'::character varying, 'revoked'::character varying, 'expired'::character varying]::text[]));
ALTER TABLE "public"."hs_staff_unit_permissions" ADD CONSTRAINT "hs_staff_unit_permissions_unit_entity_id_fkey" FOREIGN KEY (unit_entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_unit_bills" ADD CONSTRAINT "hs_unit_bills_billing_cycle_id_fkey" FOREIGN KEY (billing_cycle_id) REFERENCES hs_billing_cycles(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_unit_bills" ADD CONSTRAINT "hs_unit_bills_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_unit_bills" ADD CONSTRAINT "hs_unit_bills_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_unit_bills" ADD CONSTRAINT "hs_unit_bills_status_check" CHECK (status::text = ANY (ARRAY['unpaid'::character varying, 'partial'::character varying, 'paid'::character varying, 'waived'::character varying, 'void'::character varying]::text[]));
ALTER TABLE "public"."hs_unit_bills" ADD CONSTRAINT "hs_unit_bills_unit_entity_id_fkey" FOREIGN KEY (unit_entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_unit_occupancy_history" ADD CONSTRAINT "hs_unit_occupancy_history_check" CHECK (ends_on IS NULL OR ends_on >= starts_on);
ALTER TABLE "public"."hs_unit_occupancy_history" ADD CONSTRAINT "hs_unit_occupancy_history_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_unit_occupancy_history" ADD CONSTRAINT "hs_unit_occupancy_history_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_unit_occupancy_history" ADD CONSTRAINT "hs_unit_occupancy_history_occupancy_role_check" CHECK (occupancy_role::text = ANY (ARRAY['owner'::character varying, 'co-owner'::character varying, 'tenant'::character varying, 'occupant'::character varying]::text[]));
ALTER TABLE "public"."hs_unit_occupancy_history" ADD CONSTRAINT "hs_unit_occupancy_history_subject_entity_id_fkey" FOREIGN KEY (subject_entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_unit_occupancy_history" ADD CONSTRAINT "hs_unit_occupancy_history_unit_entity_id_fkey" FOREIGN KEY (unit_entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_vehicles" ADD CONSTRAINT "hs_vehicles_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_vehicles" ADD CONSTRAINT "hs_vehicles_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_vehicles" ADD CONSTRAINT "hs_vehicles_owner_entity_id_fkey" FOREIGN KEY (owner_entity_id) REFERENCES network_entities(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_vehicles" ADD CONSTRAINT "hs_vehicles_status_check" CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[]));
ALTER TABLE "public"."hs_vehicles" ADD CONSTRAINT "hs_vehicles_unit_entity_id_fkey" FOREIGN KEY (unit_entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_vehicles" ADD CONSTRAINT "hs_vehicles_vehicle_type_check" CHECK (vehicle_type::text = ANY (ARRAY['car'::character varying, 'two-wheeler'::character varying, 'cycle'::character varying, 'other'::character varying]::text[]));
ALTER TABLE "public"."hs_vendor_contracts" ADD CONSTRAINT "hs_vendor_contracts_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_vendor_contracts" ADD CONSTRAINT "hs_vendor_contracts_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_vendor_contracts" ADD CONSTRAINT "hs_vendor_contracts_status_check" CHECK (status::text = ANY (ARRAY['draft'::character varying, 'active'::character varying, 'expired'::character varying, 'terminated'::character varying]::text[]));
ALTER TABLE "public"."hs_vendor_contracts" ADD CONSTRAINT "hs_vendor_contracts_vendor_id_fkey" FOREIGN KEY (vendor_id) REFERENCES hs_vendors(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_vendors" ADD CONSTRAINT "hs_vendors_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_vendors" ADD CONSTRAINT "hs_vendors_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_vendors" ADD CONSTRAINT "hs_vendors_status_check" CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'blocked'::character varying]::text[]));
ALTER TABLE "public"."hs_visitors" ADD CONSTRAINT "hs_visitors_checked_by_fkey" FOREIGN KEY (checked_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_visitors" ADD CONSTRAINT "hs_visitors_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE "public"."hs_visitors" ADD CONSTRAINT "hs_visitors_network_id_fkey" FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_visitors" ADD CONSTRAINT "hs_visitors_status_check" CHECK (status::text = ANY (ARRAY['expected'::character varying, 'inside'::character varying, 'exited'::character varying, 'cancelled'::character varying, 'denied'::character varying]::text[]));
ALTER TABLE "public"."hs_visitors" ADD CONSTRAINT "hs_visitors_unit_entity_id_fkey" FOREIGN KEY (unit_entity_id) REFERENCES network_entities(id) ON DELETE CASCADE;
ALTER TABLE "public"."hs_visitors" ADD CONSTRAINT "hs_visitors_visit_type_check" CHECK (visit_type::text = ANY (ARRAY['guest'::character varying, 'delivery'::character varying, 'service'::character varying, 'cab'::character varying, 'other'::character varying]::text[]));
