import {supabase} from "../../../lib/supabase";
function db(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}

export type HsChargeHead={id:string;code:string;label:string;category:string;amount:number;active:boolean};
export type HsBillingCycle={id:string;label:string;periodStart:string;periodEnd:string;dueOn:string;status:string;graceDays:number;penaltyRateMonthly:number};
export type HsBillLine={id:string;label:string;amount:number};
export type HsPayment={id:string;amount:number;paidOn:string;paymentMode:string;paymentReference?:string|null;receiptNumber?:string|null;status:string};
export type HsUnitBill={id:string;cycleId:string;cycleLabel:string;unitEntityId:string;unitLabel:string;dueOn:string;subtotal:number;adjustmentAmount:number;totalAmount:number;paidAmount:number;balanceAmount:number;status:string;lineItems:HsBillLine[];payments:HsPayment[]};
export type HsFund={id:string;code:string;label:string;openingBalance:number;currentBalance:number;visibility:string};
export type HsBudgetLine={id:string;financialYear:string;category:string;label:string;budgetAmount:number;actualAmount:number;visibility:string};
export type HsFinanceSnapshot={chargeHeads:HsChargeHead[];cycles:HsBillingCycle[];bills:HsUnitBill[];funds:HsFund[];budget:HsBudgetLine[];summary:{totalBilled:number;totalCollected:number;totalOutstanding:number;overdueBills:number}};
const EMPTY:HsFinanceSnapshot={chargeHeads:[],cycles:[],bills:[],funds:[],budget:[],summary:{totalBilled:0,totalCollected:0,totalOutstanding:0,overdueBills:0}};

export async function fetchHsFinanceSnapshot(){const {data,error}=await db().rpc("hs3_get_finance_snapshot");if(error)throw error;return (data||EMPTY) as HsFinanceSnapshot}
export async function upsertHsChargeHead(input:{id?:string;code:string;label:string;category:string;amount:number;active?:boolean}){const {data,error}=await db().rpc("hs3_upsert_charge_head",{p_id:input.id||null,p_code:input.code,p_label:input.label,p_category:input.category,p_default_amount:input.amount,p_active:input.active??true});if(error)throw error;return String(data)}
export async function createHsBillingCycle(input:{label:string;periodStart:string;periodEnd:string;dueOn:string;graceDays?:number;penaltyRateMonthly?:number}){const {data,error}=await db().rpc("hs3_create_billing_cycle",{p_label:input.label,p_period_start:input.periodStart,p_period_end:input.periodEnd,p_due_on:input.dueOn,p_grace_days:input.graceDays??0,p_penalty_rate_monthly:input.penaltyRateMonthly??0});if(error)throw error;return String(data)}
export async function generateHsCycleBills(cycleId:string){const {data,error}=await db().rpc("hs3_generate_cycle_bills",{p_cycle_id:cycleId});if(error)throw error;return data as {cycleId:string;unitCount:number;chargeHeadCount:number}}
export async function addHsBillAdjustment(input:{billId:string;type:"credit"|"debit"|"waiver"|"penalty";amount:number;reason:string}){const {data,error}=await db().rpc("hs3_add_bill_adjustment",{p_bill_id:input.billId,p_type:input.type,p_amount:input.amount,p_reason:input.reason});if(error)throw error;return String(data)}
export async function recordHsPayment(input:{billId:string;amount:number;paidOn?:string;paymentMode?:string;paymentReference?:string;receiptNumber?:string;notes?:string}){const {data,error}=await db().rpc("hs3_record_payment",{p_bill_id:input.billId,p_amount:input.amount,p_paid_on:input.paidOn||null,p_payment_mode:input.paymentMode||"manual",p_payment_reference:input.paymentReference||null,p_receipt_number:input.receiptNumber||null,p_notes:input.notes||null});if(error)throw error;return String(data)}
export async function upsertHsFund(input:{id?:string;code:string;label:string;openingBalance?:number;visibility?:"admin"|"members"}){const {data,error}=await db().rpc("hs3_upsert_fund",{p_id:input.id||null,p_code:input.code,p_label:input.label,p_opening_balance:input.openingBalance??0,p_visibility:input.visibility||"members"});if(error)throw error;return String(data)}
export async function upsertHsBudgetLine(input:{financialYear:string;category:string;label:string;budgetAmount:number;visibility?:"admin"|"members"}){const {data,error}=await db().rpc("hs3_upsert_budget_line",{p_financial_year:input.financialYear,p_category:input.category,p_label:input.label,p_budget_amount:input.budgetAmount,p_visibility:input.visibility||"members"});if(error)throw error;return String(data)}
export async function recordHsExpense(input:{category:string;description:string;amount:number;incurredOn?:string;fundId?:string|null;vendorId?:string|null;paymentReference?:string;visibility?:"admin"|"members"}){const {data,error}=await db().rpc("hs3_record_expense",{p_category:input.category,p_description:input.description,p_amount:input.amount,p_incurred_on:input.incurredOn||null,p_fund_id:input.fundId||null,p_vendor_id:input.vendorId||null,p_payment_reference:input.paymentReference||null,p_visibility:input.visibility||"members"});if(error)throw error;return String(data)}
