import {supabase} from "../../../lib/supabase";
function db(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}
export type HsCommitteeAssignment={id:string;personEntityId:string;personLabel:string;roleKey:string;roleLabel?:string|null;startsOn:string;endsOn?:string|null};
export type HsCommitteeTerm={id:string;label:string;startsOn:string;endsOn?:string|null;status:string;notes?:string|null;assignments:HsCommitteeAssignment[]};
export type HsAgendaItem={id:string;itemOrder:number;title:string;description?:string|null;outcomeText?:string|null};
export type HsGovernanceMeeting={id:string;meetingType:string;title:string;scheduledAt:string;location?:string|null;status:string;quorumRequired?:number|null;attendeeCount?:number|null;minutesText?:string|null;minutesPublishedAt?:string|null;agenda:HsAgendaItem[]};
export type HsGovernanceAction={id:string;meetingId?:string|null;title:string;ownerLabel?:string|null;dueOn?:string|null;status:string;completionNote?:string|null};
export type HsResolution={id:string;meetingId?:string|null;resolutionNumber?:string|null;title:string;body:string;voteMode:"advisory"|"approval";status:string;opensAt?:string|null;closesAt?:string|null;quorumPercent:number;resultNote?:string|null;yesCount:number;noCount:number;abstainCount:number;myVote?:"yes"|"no"|"abstain"|null};
export type HsGovernanceDocument={id:string;meetingId?:string|null;resolutionId?:string|null;documentType:string;title:string;versionLabel?:string|null;documentUrl?:string|null;visibility:string;createdAt:string};
export type HsGovernanceSnapshot={terms:HsCommitteeTerm[];meetings:HsGovernanceMeeting[];actions:HsGovernanceAction[];resolutions:HsResolution[];documents:HsGovernanceDocument[]};
export async function fetchHsGovernanceSnapshot(){const {data,error}=await db().rpc("hs4_get_governance_snapshot");if(error)throw error;return (data||{terms:[],meetings:[],actions:[],resolutions:[],documents:[]}) as HsGovernanceSnapshot}
export async function createHsCommitteeTerm(input:{label:string;startsOn:string;endsOn?:string|null;notes?:string}){const {data,error}=await db().rpc("hs4_create_committee_term",{p_label:input.label,p_starts_on:input.startsOn,p_ends_on:input.endsOn||null,p_notes:input.notes||null});if(error)throw error;return String(data)}
export async function assignHsCommitteeRole(input:{termId:string;personEntityId:string;roleKey:string;roleLabel?:string;startsOn:string;endsOn?:string|null}){const {data,error}=await db().rpc("hs4_assign_committee_role",{p_term_id:input.termId,p_person_entity_id:input.personEntityId,p_role_key:input.roleKey,p_role_label:input.roleLabel||null,p_starts_on:input.startsOn,p_ends_on:input.endsOn||null});if(error)throw error;return String(data)}
export async function createHsGovernanceMeeting(input:{meetingType:string;title:string;scheduledAt:string;location?:string;quorumRequired?:number|null}){const {data,error}=await db().rpc("hs4_create_meeting",{p_meeting_type:input.meetingType,p_title:input.title,p_scheduled_at:input.scheduledAt,p_location:input.location||null,p_quorum_required:input.quorumRequired??null});if(error)throw error;return String(data)}
export async function addHsAgendaItem(meetingId:string,title:string,description?:string){const {data,error}=await db().rpc("hs4_add_agenda_item",{p_meeting_id:meetingId,p_title:title,p_description:description||null});if(error)throw error;return String(data)}
export async function publishHsMinutes(meetingId:string,minutes:string,attendeeCount?:number|null){const {error}=await db().rpc("hs4_publish_minutes",{p_meeting_id:meetingId,p_minutes:minutes,p_attendee_count:attendeeCount??null});if(error)throw error}
export async function createHsGovernanceAction(input:{meetingId?:string|null;title:string;ownerLabel?:string;dueOn?:string|null}){const {data,error}=await db().rpc("hs4_create_action_item",{p_meeting_id:input.meetingId||null,p_title:input.title,p_owner_label:input.ownerLabel||null,p_due_on:input.dueOn||null});if(error)throw error;return String(data)}
export async function updateHsGovernanceAction(id:string,status:"open"|"in_progress"|"done"|"cancelled",completionNote?:string){const {error}=await db().rpc("hs4_update_action_item",{p_action_id:id,p_status:status,p_completion_note:completionNote||null});if(error)throw error}
export async function createHsResolution(input:{meetingId?:string|null;resolutionNumber?:string;title:string;body:string;voteMode?:"advisory"|"approval";opensAt?:string|null;closesAt?:string|null;quorumPercent?:number}){const {data,error}=await db().rpc("hs4_create_resolution",{p_meeting_id:input.meetingId||null,p_resolution_number:input.resolutionNumber||null,p_title:input.title,p_body:input.body,p_vote_mode:input.voteMode||"approval",p_opens_at:input.opensAt||null,p_closes_at:input.closesAt||null,p_quorum_percent:input.quorumPercent??0});if(error)throw error;return String(data)}
export async function castHsResolutionVote(id:string,choice:"yes"|"no"|"abstain"){const {data,error}=await db().rpc("hs4_cast_resolution_vote",{p_resolution_id:id,p_choice:choice});if(error)throw error;return String(data)}
export async function closeHsResolution(id:string,status:"approved"|"rejected"|"closed"|"withdrawn",resultNote?:string){const {error}=await db().rpc("hs4_close_resolution",{p_resolution_id:id,p_result_status:status,p_result_note:resultNote||null});if(error)throw error}
export async function addHsGovernanceDocument(input:{meetingId?:string|null;resolutionId?:string|null;documentType:string;title:string;versionLabel?:string;documentUrl?:string;visibility?:"admin"|"members"}){const {data,error}=await db().rpc("hs4_add_governance_document",{p_meeting_id:input.meetingId||null,p_resolution_id:input.resolutionId||null,p_document_type:input.documentType,p_title:input.title,p_version_label:input.versionLabel||null,p_document_url:input.documentUrl||null,p_visibility:input.visibility||"members"});if(error)throw error;return String(data)}
