import {supabase} from "../../../lib/supabase";
function db(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}

export type HsPilotRun={id:string;phase:"A"|"B"|"C"|"D";status:"planning"|"active"|"paused"|"completed"|"stopped";cohortLabel?:string|null;targetUnits:number;startedOn?:string|null;endedOn?:string|null;notes?:string|null};
export type HsPilotSignal={key:string;label:string;passed:boolean};
export type HsPilotMetrics={totalUnits:number;occupiedUnits:number;claimedUnits:number;claimRate:number;weeklyActiveUnits:number;activeMembers:number;notices30d:number;noticeReaders30d:number;noticeReadReach:number;complaints30d:number;resolvedComplaints30d:number;medianResolutionHours:number;maintenanceViews30d:number;billingCycles:number;paymentsRecorded:number;completedMeetings:number;securityComplianceCycles:number;committedImports:number};
export type HsPilotCheckpoint={id:string;checkpoint_on:string;admin_hours_saved?:number|null;offline_operations_remaining?:number|null;willingness_to_pay:string;renewal_intent:string;repeatable_onboarding_confirmed:boolean;founder_specific_code_required:boolean;committee_note?:string|null;created_at:string};
export type HsPricingExperiment={id:string;pricing_model:string;amount?:number|null;currency:string;response:string;notes?:string|null;tested_on:string;created_at:string};
export type HsPilotSnapshot={run:HsPilotRun|null;readiness:number;signals:HsPilotSignal[];metrics:HsPilotMetrics;latestCheckpoint?:HsPilotCheckpoint|null;checkpoints:HsPilotCheckpoint[];pricingExperiments:HsPricingExperiment[]};

export async function fetchHsPilotSnapshot(){const {data,error}=await db().rpc("hs6_get_pilot_snapshot");if(error)throw error;return data as HsPilotSnapshot}
export async function startHsPilot(i:{phase:"A"|"B"|"C"|"D";targetUnits:number;cohortLabel?:string;notes?:string}){const {data,error}=await db().rpc("hs6_start_pilot",{p_phase:i.phase,p_target_units:i.targetUnits,p_cohort_label:i.cohortLabel||null,p_notes:i.notes||null});if(error)throw error;return String(data)}
export async function updateHsPilotStatus(runId:string,status:HsPilotRun["status"]){const {error}=await db().rpc("hs6_update_pilot_status",{p_run_id:runId,p_status:status});if(error)throw error}
export async function recordHsPilotCheckpoint(i:{runId:string;adminHoursSaved?:number|null;offlineOperationsRemaining?:number|null;willingnessToPay?:string;renewalIntent?:string;repeatableOnboardingConfirmed?:boolean;founderSpecificCodeRequired?:boolean;committeeNote?:string}){const {data,error}=await db().rpc("hs6_record_checkpoint",{p_run_id:i.runId,p_admin_hours_saved:i.adminHoursSaved??null,p_offline_operations_remaining:i.offlineOperationsRemaining??null,p_willingness_to_pay:i.willingnessToPay||"unknown",p_renewal_intent:i.renewalIntent||"unknown",p_repeatable_onboarding_confirmed:!!i.repeatableOnboardingConfirmed,p_founder_specific_code_required:!!i.founderSpecificCodeRequired,p_committee_note:i.committeeNote||null});if(error)throw error;return String(data)}
export async function recordHsPricingExperiment(i:{runId?:string|null;pricingModel:string;amount?:number|null;currency?:string;response?:string;notes?:string}){const {data,error}=await db().rpc("hs6_record_pricing_experiment",{p_run_id:i.runId||null,p_pricing_model:i.pricingModel,p_amount:i.amount??null,p_currency:i.currency||"INR",p_response:i.response||"untested",p_notes:i.notes||null});if(error)throw error;return String(data)}
export async function recordHsPilotUsageEvent(eventKey:string,metadata:Record<string,unknown>={}){const {error}=await db().rpc("hs6_record_usage_event",{p_event_key:eventKey,p_metadata:metadata});if(error)throw error}
export async function markHsNoticesRead(ids:string[]){if(!ids.length)return 0;const {data,error}=await db().rpc("hs6_mark_notice_reads",{p_notice_ids:ids});if(error)throw error;return Number(data||0)}
