import {supabase} from "../../../lib/supabase";
function db(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}
export type HsOccupancy={id:string;unitId:string;unitLabel:string;subjectId:string;subjectLabel:string;subjectKind:string;role:"owner"|"co-owner"|"tenant"|"occupant";startsOn:string;endsOn?:string|null;isPrimary:boolean};
export type HsVehicle={id:string;unitId:string;unitLabel?:string;ownerEntityId?:string|null;registrationNo:string;vehicleType:string;makeModel?:string|null;isEv:boolean;status?:string};
export type HsParkingSlot={id:string;slotCode:string;zone?:string|null;slotType:string;status:string};
export type HsInvitation={id:string;personEntityId:string;personLabel:string;unitEntityId?:string|null;email:string;token?:string;status:string;expiresAt:string};
export type HsPropertySnapshot={occupancy:HsOccupancy[];vehicles:HsVehicle[];parkingSlots:HsParkingSlot[];parkingAllocations:any[];invitations:HsInvitation[]};
export type HsMyFlat={claimed:boolean;personId?:string;personLabel?:string;units?:Array<{unitId:string;unitLabel:string;role:string;startsOn:string;endsOn?:string|null;metadata?:Record<string,unknown>}>;households?:Array<{householdId:string;householdLabel:string}>;vehicles?:HsVehicle[]};
export async function fetchHsPropertySnapshot(){const {data,error}=await db().rpc("hs1_get_property_snapshot");if(error)throw error;return (data||{occupancy:[],vehicles:[],parkingSlots:[],parkingAllocations:[],invitations:[]}) as HsPropertySnapshot}
export async function fetchHsMyFlat(){const {data,error}=await db().rpc("hs1_get_my_flat");if(error)throw error;return (data||{claimed:false}) as HsMyFlat}
export async function setHsOccupancy(input:{unitId:string;subjectId:string;role:string;startsOn?:string;endsOn?:string|null;isPrimary?:boolean;notes?:string}){const {data,error}=await db().rpc("hs1_set_occupancy",{p_unit_id:input.unitId,p_subject_id:input.subjectId,p_role:input.role,p_starts_on:input.startsOn||null,p_ends_on:input.endsOn||null,p_is_primary:!!input.isPrimary,p_notes:input.notes||null});if(error)throw error;return String(data)}
export async function upsertHsParkingSlot(input:{id?:string;slotCode:string;zone?:string;slotType?:string;status?:string}){const {data,error}=await db().rpc("hs1_upsert_parking_slot",{p_id:input.id||null,p_slot_code:input.slotCode,p_zone:input.zone||null,p_slot_type:input.slotType||"car",p_status:input.status||"available"});if(error)throw error;return String(data)}
export async function upsertHsVehicle(input:{id?:string;unitId:string;ownerEntityId?:string|null;registrationNo:string;vehicleType?:string;makeModel?:string;color?:string;isEv?:boolean}){const {data,error}=await db().rpc("hs1_upsert_vehicle",{p_id:input.id||null,p_unit_id:input.unitId,p_owner_entity_id:input.ownerEntityId||null,p_registration_no:input.registrationNo,p_vehicle_type:input.vehicleType||"car",p_make_model:input.makeModel||null,p_color:input.color||null,p_is_ev:!!input.isEv});if(error)throw error;return String(data)}
export async function allocateHsParking(input:{slotId:string;unitId:string;vehicleId?:string|null;startsOn?:string;endsOn?:string|null;allocationType?:string}){const {data,error}=await db().rpc("hs1_allocate_parking",{p_slot_id:input.slotId,p_unit_id:input.unitId,p_vehicle_id:input.vehicleId||null,p_starts_on:input.startsOn||null,p_ends_on:input.endsOn||null,p_allocation_type:input.allocationType||"assigned"});if(error)throw error;return String(data)}
export async function createHsResidentInvitation(personEntityId:string,unitEntityId:string|null,email?:string){const {data,error}=await db().rpc("hs1_create_resident_invitation",{p_person_entity_id:personEntityId,p_unit_entity_id:unitEntityId,p_email:email||null,p_expires_days:14});if(error)throw error;return String(data)}
export async function fetchHsImportTemplate(){const {data,error}=await db().rpc("hs1_get_import_template");if(error)throw error;return data as {required:string[];recommended:string[];aliases:Record<string,string>}}
export async function importHsResidentRows(rows:Record<string,unknown>[],fileName?:string,columnMapping:Record<string,string>={}){const {data,error}=await db().rpc("hs1_import_resident_rows",{p_rows:rows,p_file_name:fileName||null,p_column_mapping:columnMapping});if(error)throw error;return data as {batchId:string;inserted:number;updated:number;skipped:number}}

export async function fetchHsInvitationPreview(token:string){const {data,error}=await db().rpc("hs1_get_resident_invitation_preview",{p_token:token});if(error)throw error;return (data||[])[0] as {status:string;society_name:string;resident_name:string;email:string;unit_label?:string|null;expires_at:string}|undefined}
export async function acceptHsInvitation(token:string){const {data,error}=await db().rpc("hs1_accept_resident_invitation",{p_token:token});if(error)throw error;return String(data)}
