import {supabase} from "../../../lib/supabase";function db(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}
export type HsSecuritySnapshot={isSecurityOperator:boolean;visitors:any[];staff:any[];moveRequests:any[];renovations:any[];assets:any[];compliance:any[];emergencyContacts:any[]};
export async function fetchHsSecuritySnapshot(){const {data,error}=await db().rpc("hs5_get_snapshot");if(error)throw error;return (data||{isSecurityOperator:false,visitors:[],staff:[],moveRequests:[],renovations:[],assets:[],compliance:[],emergencyContacts:[]}) as HsSecuritySnapshot}
export async function createHsVisitor(i:{unitId:string;visitorName:string;visitType?:string;expectedAt?:string|null;purpose?:string;phone?:string;vehicleNumber?:string}){const {data,error}=await db().rpc("hs5_create_visitor",{p_unit_entity_id:i.unitId,p_visitor_name:i.visitorName,p_visit_type:i.visitType||"guest",p_expected_at:i.expectedAt||null,p_purpose:i.purpose||null,p_phone:i.phone||null,p_vehicle_number:i.vehicleNumber||null});if(error)throw error;return String(data)}
export async function updateHsVisitorStatus(id:string,status:string){const {error}=await db().rpc("hs5_update_visitor_status",{p_visitor_id:id,p_status:status});if(error)throw error}
export async function grantHsSecurityOperator(userId:string,scope:"security"|"facility"|"compliance"="security",active=true){const {data,error}=await db().rpc("hs5_grant_operator",{p_user_id:userId,p_scope:scope,p_active:active});if(error)throw error;return String(data)}
export async function upsertHsStaff(i:{id?:string;name:string;staffType:string;phone?:string;identityLast4?:string;verificationStatus?:string}){const {data,error}=await db().rpc("hs5_upsert_staff",{p_id:i.id||null,p_name:i.name,p_staff_type:i.staffType,p_phone:i.phone||null,p_identity_last4:i.identityLast4||null,p_verification_status:i.verificationStatus||"pending"});if(error)throw error;return String(data)}
export async function authorizeHsStaffUnit(staffId:string,unitId:string,startsOn?:string,endsOn?:string|null){const {data,error}=await db().rpc("hs5_authorize_staff_unit",{p_staff_id:staffId,p_unit_entity_id:unitId,p_starts_on:startsOn||null,p_ends_on:endsOn||null});if(error)throw error;return String(data)}
export async function createHsMoveRequest(i:{unitId:string;moveType:"move_in"|"move_out";scheduledOn:string;contactName?:string;notes?:string}){const {data,error}=await db().rpc("hs5_create_move_request",{p_unit_entity_id:i.unitId,p_move_type:i.moveType,p_scheduled_on:i.scheduledOn,p_contact_name:i.contactName||null,p_notes:i.notes||null});if(error)throw error;return String(data)}
export async function createHsRenovationRequest(i:{unitId:string;title:string;description?:string;contractorName?:string;startsOn?:string|null;endsOn?:string|null}){const {data,error}=await db().rpc("hs5_create_renovation_request",{p_unit_entity_id:i.unitId,p_title:i.title,p_description:i.description||null,p_contractor_name:i.contractorName||null,p_starts_on:i.startsOn||null,p_ends_on:i.endsOn||null});if(error)throw error;return String(data)}
export async function reviewHsOperationalRequest(kind:"move"|"renovation",id:string,status:string,note?:string,nocReference?:string){const {error}=await db().rpc("hs5_review_request",{p_kind:kind,p_id:id,p_status:status,p_note:note||null,p_noc_reference:nocReference||null});if(error)throw error}
export async function upsertHsAsset(i:{id?:string;assetCode:string;name:string;category:string;location?:string;warrantyUntil?:string|null}){const {data,error}=await db().rpc("hs5_upsert_asset",{p_id:i.id||null,p_asset_code:i.assetCode,p_name:i.name,p_category:i.category,p_location:i.location||null,p_warranty_until:i.warrantyUntil||null});if(error)throw error;return String(data)}
export async function addHsAssetService(i:{assetId:string;serviceType:string;servicedOn?:string;nextDueOn?:string|null;notes?:string;cost?:number|null}){const {data,error}=await db().rpc("hs5_add_asset_service",{p_asset_id:i.assetId,p_service_type:i.serviceType,p_serviced_on:i.servicedOn||null,p_next_due_on:i.nextDueOn||null,p_notes:i.notes||null,p_cost:i.cost??null});if(error)throw error;return String(data)}
export async function upsertHsCompliance(i:{id?:string;category:string;title:string;dueOn?:string|null;ownerLabel?:string;documentUrl?:string;visibility?:"admin"|"members"}){const {data,error}=await db().rpc("hs5_upsert_compliance",{p_id:i.id||null,p_category:i.category,p_title:i.title,p_due_on:i.dueOn||null,p_owner_label:i.ownerLabel||null,p_document_url:i.documentUrl||null,p_visibility:i.visibility||"members"});if(error)throw error;return String(data)}
export async function upsertHsEmergencyContact(i:{category:string;label:string;phone:string;notes?:string;priority?:number}){const {data,error}=await db().rpc("hs5_upsert_emergency_contact",{p_category:i.category,p_label:i.label,p_phone:i.phone,p_notes:i.notes||null,p_priority:i.priority??100});if(error)throw error;return String(data)}
