import type {IntelligenceAnswer,IntelligenceDataset,IntelligenceEvidence,IntelligenceHealth,IntelligenceInsight,IntelligenceVerticalKind} from "./contracts";

const words=(q:string)=>q.toLowerCase().split(/[^a-z0-9@.+-]+/).filter(x=>x.length>1);
const valueText=(e:IntelligenceDataset["entities"][number])=>[e.entity.label,...Object.values(e.affiliations).flat(),...Object.values(e.entity.metadata||{}).filter(v=>typeof v==="string"||typeof v==="number").map(String)].join(" ").toLowerCase();
export function searchNetwork(dataset:IntelligenceDataset,query:string){const qs=words(query);if(!qs.length)return [];return dataset.entities.map(e=>({entity:e,score:qs.reduce((n,w)=>n+(valueText(e).includes(w)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.entity.entity.label.localeCompare(b.entity.entity.label));}
export function shortestPath(start:string,end:string,relationships:IntelligenceDataset["relationships"]){if(start===end)return [start];const q:Array<[string,string[]]>= [[start,[start]]],seen=new Set([start]);while(q.length){const [id,path]=q.shift()!;for(const r of relationships){const next=r.fromEntityId===id?r.toEntityId:r.toEntityId===id?r.fromEntityId:null;if(next&&!seen.has(next)){const p=[...path,next];if(next===end)return p;seen.add(next);q.push([next,p])}}}return []}
function sharedAffiliations(a:IntelligenceDataset["entities"][number],b:IntelligenceDataset["entities"][number]){const out:string[]=[];for(const [k,av] of Object.entries(a.affiliations)){const bv=b.affiliations[k]||[];const common=av.filter(v=>bv.includes(v));if(common.length)out.push(...common.map(v=>`${k}: ${v}`));}return out}
export function analyzeHealth(dataset:IntelligenceDataset,dimensionKeys:readonly string[]=[]):IntelligenceHealth{const degree=new Map<string,number>();dataset.entities.forEach(e=>degree.set(e.entity.id,0));dataset.relationships.forEach(r=>{degree.set(r.fromEntityId,(degree.get(r.fromEntityId)||0)+1);degree.set(r.toEntityId,(degree.get(r.toEntityId)||0)+1)});const isolated=[...degree].filter(([,d])=>d===0).map(([id])=>id);const high=[...degree].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([entityId,d])=>({entityId,degree:d}));const direct=new Set(dataset.relationships.flatMap(r=>[`${r.fromEntityId}|${r.toEntityId}`,`${r.toEntityId}|${r.fromEntityId}`]));const candidates:{fromEntityId:string;toEntityId:string;sharedContext:string[];score:number}[]=[];for(let i=0;i<dataset.entities.length;i++)for(let j=i+1;j<dataset.entities.length;j++){const a=dataset.entities[i],b=dataset.entities[j];if(direct.has(`${a.entity.id}|${b.entity.id}`))continue;const shared=sharedAffiliations(a,b);if(shared.length>=2)candidates.push({fromEntityId:a.entity.id,toEntityId:b.entity.id,sharedContext:shared.slice(0,4),score:shared.length});}candidates.sort((a,b)=>b.score-a.score);let filled=0,total=0;for(const e of dataset.entities)for(const k of dimensionKeys){total++;if((e.affiliations[k]||[]).length)filled++;}return {completeness:total?Math.round(filled*100/total):100,isolatedEntityIds:isolated,highConnectivity:high,missingLinkCandidates:candidates.slice(0,8)};}
const copy={
 organization:{risk:"Knowledge concentration",opportunity:"Expertise & ownership opportunity",ask:["Who understands authentication best?","Which people are highly connected?","Where are ownership or knowledge gaps?"]},
 "business-trust":{risk:"Trust evidence gap",opportunity:"Warm-path opportunity",ask:["Who can introduce me to a packaging supplier?","Which businesses have the strongest network evidence?","Where are trust relationships missing?"]},
 franchise:{risk:"Operational knowledge gap",opportunity:"Cross-location learning opportunity",ask:["Which locations can help with an operating issue?","Which stores are strongest connectors?","Where are coverage or learning gaps?"]},
 alumni:{risk:"Alumni network gap",opportunity:"Mentoring & introduction opportunity",ask:["Who from my network works in Pune?","Who are the strongest alumni connectors?","Where can alumni introductions help?"]},
 "family-association":{risk:"Family/community participation or profile gap",opportunity:"Family/community connection & participation opportunity",ask:["Which members share this profession or area?","Which families need renewal follow-up?","Who has contributed to this activity before?"]},
 association:{risk:"Community participation or context gap",opportunity:"Community connection & participation opportunity",ask:["Which households or members share the same area?","Who are the strongest community connectors?","Where can community participation or introductions help?"]},
 family:{risk:"Family information gap",opportunity:"Family connection opportunity",ask:["Which family branches need more information?","Who connects different parts of the family?","Which relatives share the same city?"]},
 professional:{risk:"Expertise or referral evidence gap",opportunity:"Trusted expertise & referral opportunity",ask:["Who has the strongest expertise for this need?","Who can provide a warm introduction to the right specialist?","Which professionals have reusable case knowledge in this area?"]},
 "housing-society":{risk:"Resident or property context gap",opportunity:"Neighbour and society coordination opportunity",ask:["Which residents or flats share relevant context?","Where are resident or property records incomplete?","Which community connections could help coordinate society work?"]}
} as const;
export function buildInsights(kind:IntelligenceVerticalKind,dataset:IntelligenceDataset,dimensionKeys:readonly string[]=[]):IntelligenceInsight[]{const h=analyzeHealth(dataset,dimensionKeys),name=(id:string)=>dataset.entities.find(e=>e.entity.id===id)?.entity.label||id,out:IntelligenceInsight[]=[];if(h.highConnectivity[0])out.push({id:"connector",severity:"info",title:`${name(h.highConnectivity[0].entityId)} is a key network connector`,summary:`${h.highConnectivity[0].degree} known relationship links make this entity structurally important.`,reason:"Highly connected entities can accelerate introductions, knowledge flow and coordination.",actionLabel:"Explore connections",actionTarget:"connections",evidence:[{kind:"health",label:"Connectivity",detail:`Degree ${h.highConnectivity[0].degree}`,entityId:h.highConnectivity[0].entityId}]});if(h.isolatedEntityIds.length)out.push({id:"isolated",severity:"attention",title:`${h.isolatedEntityIds.length} entities are isolated`,summary:"These entities have no typed relationship to the rest of the network.",reason:copy[kind].risk,actionLabel:"Improve network",actionTarget:"contribute",evidence:h.isolatedEntityIds.slice(0,4).map(id=>({kind:"entity",label:name(id),detail:"No known relationship",entityId:id}))});if(h.missingLinkCandidates.length)out.push({id:"missing-link",severity:"opportunity",title:copy[kind].opportunity,summary:`${name(h.missingLinkCandidates[0].fromEntityId)} and ${name(h.missingLinkCandidates[0].toEntityId)} share context but have no known direct relationship.`,reason:"Shared affiliations can reveal useful missing links without inventing a relationship.",actionLabel:"Review opportunity",actionTarget:"connections",evidence:h.missingLinkCandidates[0].sharedContext.map(x=>({kind:"affiliation",label:"Shared context",detail:x}))});const recent=(dataset.activities||[]).filter(a=>a.type==="memory"||a.type==="milestone").slice(0,2);if(recent.length)out.push({id:"knowledge",severity:"info",title:"Reusable network knowledge is available",summary:`${recent.length} recent lessons, stories or milestones can help the network avoid starting from zero.`,reason:"Captured outcomes are more valuable when connected back to people and structure.",actionLabel:"Open knowledge",actionTarget:"community",evidence:recent.map(a=>({kind:"activity",label:a.title,detail:a.body||a.type,activityId:a.id}))});return out;}
export function suggestedQuestions(kind:IntelligenceVerticalKind){return [...copy[kind].ask];}
export function askNetwork(kind:IntelligenceVerticalKind,dataset:IntelligenceDataset,question:string,dimensionKeys:readonly string[]=[]):IntelligenceAnswer{const matches=searchNetwork(dataset,question).slice(0,6),h=analyzeHealth(dataset,dimensionKeys),q=question.toLowerCase(),name=(id:string)=>dataset.entities.find(e=>e.entity.id===id)?.entity.label||id;let headline="Network evidence found",answer="I found the strongest matches from the network data you are allowed to see.",evidence:IntelligenceEvidence[]=matches.map(m=>({kind:"entity",label:m.entity.entity.label,detail:Object.entries(m.entity.affiliations).filter(([,v])=>v.length).slice(0,3).map(([k,v])=>`${k}: ${v.join(", ")}`).join(" · "),entityId:m.entity.entity.id}));if(q.includes("connect")||q.includes("introduc")||q.includes("path")){const a=matches[0]?.entity.entity.id,b=matches[1]?.entity.entity.id;if(a&&b){const path=shortestPath(a,b,dataset.relationships);headline=path.length?`${path.length-1}-hop known path found`:`No verified path between the top matches`;answer=path.length?path.map(name).join(" → "):"The network has relevant entities, but no typed relationship currently connects the top matches.";evidence=path.map(id=>({kind:"entity",label:name(id),detail:"Path entity",entityId:id}));}else if(a){const direct=dataset.relationships.filter(r=>r.fromEntityId===a||r.toEntityId===a);if(direct.length){const ranked=direct.slice(0,5).map(r=>({r,other:r.fromEntityId===a?r.toEntityId:r.fromEntityId}));headline=`${ranked.length} known introduction path${ranked.length===1?"":"s"} into ${name(a)}`;answer=ranked.map(x=>`${name(x.other)} → ${name(a)}`).join(", ");evidence=ranked.flatMap(x=>[{kind:"relationship" as const,label:x.r.label,detail:`${name(x.other)} ↔ ${name(a)}`,relationshipId:x.r.id},{kind:"entity" as const,label:name(x.other),detail:"Known connected entity",entityId:x.other}]).slice(0,8);}else{headline=`No verified introduction path into ${name(a)}`;answer="A relevant target was found, but no typed relationship currently provides a warm path. Add or verify a relationship rather than inventing one.";evidence=[{kind:"entity",label:name(a),detail:"Relevant target with no known relationship path",entityId:a}];}}}
else if(q.includes("gap")||q.includes("missing")||q.includes("risk")){headline=`${h.isolatedEntityIds.length} isolated entities · ${h.completeness}% context complete`;answer=h.isolatedEntityIds.length?`Start with isolated entities such as ${h.isolatedEntityIds.slice(0,3).map(name).join(", ")}.`:"No isolated entities were found in the current authorized dataset.";evidence=h.isolatedEntityIds.slice(0,5).map(id=>({kind:"health",label:name(id),detail:"No typed relationships",entityId:id}));}
else if(q.includes("expert")||q.includes("understand")||q.includes("skill")||q.includes("supplier")||q.includes("location")||q.includes("store")||q.includes("pune")||q.includes("company")){headline=matches.length?`${matches.length} relevant network matches`:`No strong deterministic match`;answer=matches.length?matches.map(x=>x.entity.entity.label).join(", "):"Try a specific skill, city, company, service, team, batch or operating topic that exists in the network.";}
else if(q.includes("strong")||q.includes("connector")||q.includes("central")){headline="Strongest known connectors";answer=h.highConnectivity.length?h.highConnectivity.map(x=>`${name(x.entityId)} (${x.degree})`).join(", "):"No relationship graph is available yet.";evidence=h.highConnectivity.map(x=>({kind:"health",label:name(x.entityId),detail:`${x.degree} typed relationships`,entityId:x.entityId}));}
const confidence:"high"|"medium"|"low"=evidence.length>=3?"high":evidence.length?"medium":"low";return {question,headline,answer,confidence,evidence,suggestions:suggestedQuestions(kind),matchedEntityIds:matches.map(x=>x.entity.entity.id)};}
