"use client";
import {ArrowRight,BadgeCheck,BellRing,BookOpen,BriefcaseBusiness,CalendarDays,Cake,Camera,Clock3,GitBranch,HeartHandshake,History,ImagePlus,MapPin,Megaphone,PartyPopper,RefreshCw,Sparkles,TrendingUp,UsersRound} from "lucide-react";
import type {NetworkAffiliatedEntity,NetworkActivity} from "../core/network-os/contracts";
import type {NetworkGroup} from "../capabilities/activity/remote";
import {useLanguage} from "../lib/i18n";

type GoTarget="explorer"|"directory"|"community"|"contribute"|"guide"|"connections";

function text(value:unknown){return value==null?"":String(value)}
function dateValue(value:unknown){const raw=text(value);const d=raw?new Date(raw):null;return d&&!Number.isNaN(d.getTime())?d:null}
function nextBirthday(dob:Date){const now=new Date();const next=new Date(now.getFullYear(),dob.getMonth(),dob.getDate());if(next.getTime()<new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime())next.setFullYear(now.getFullYear()+1);return next}
function formatShortDate(d:Date){return d.toLocaleDateString(undefined,{day:"numeric",month:"short"})}
function initials(label:string){return label.split(/\s+/).filter(Boolean).slice(0,2).map(v=>v[0]?.toUpperCase()).join("")||"M"}
function personPhoto(person:NetworkAffiliatedEntity){return text(person.entity.metadata?.photo_display_url)||text(person.entity.metadata?.photo_url)}
function countTop(values:string[],limit=4){const counts=new Map<string,number>();for(const raw of values){const value=raw.trim();if(value)counts.set(value,(counts.get(value)||0)+1)}return [...counts.entries()].sort((x,y)=>y[1]-x[1]||x[0].localeCompare(y[0])).slice(0,limit)}

export default function AssociationHome({networkName,entities,activities,groups,onGo,onOpenActivity,onOpenGroup,familyCommunity=false,coverUrl,onCoverChange,coverBusy=false}:{networkName:string;entities:NetworkAffiliatedEntity[];activities:NetworkActivity[];groups:NetworkGroup[];onGo:(target:GoTarget)=>void;onOpenActivity?:(activityId:string)=>void;onOpenGroup?:(groupId:string)=>void;familyCommunity?:boolean;coverUrl?:string;onCoverChange?:(file:File)=>Promise<void>|void;coverBusy?:boolean}){
 const {t}=useLanguage();
 const households=entities.filter(x=>x.entity.kind==="household"||x.entity.kind==="family");
 const people=entities.filter(x=>x.entity.kind==="person");
 const active=households.filter(x=>(x.affiliations.membership_status||[]).some(v=>v.toLowerCase()==="active")).length;
 const renewalDue=Math.max(0,households.length-active);
 const upcomingEvents=activities.filter(a=>a.type==="event"&&a.startsAt&&new Date(a.startsAt).getTime()>=Date.now()).sort((a,b)=>new Date(a.startsAt!).getTime()-new Date(b.startsAt!).getTime()).slice(0,4);
 const announcements=activities.filter(a=>a.type==="announcement").slice(0,3);
 const birthdays=people.map(person=>{const dob=dateValue(person.entity.metadata?.dob);return dob?{person,dob,next:nextBirthday(dob)}:null}).filter((x):x is NonNullable<typeof x>=>!!x).sort((a,b)=>a.next.getTime()-b.next.getTime()).slice(0,4);
 const timeline=[...activities].filter(a=>a.startsAt||a.type==="memory"||a.type==="milestone").sort((a,b)=>text(b.startsAt).localeCompare(text(a.startsAt))).slice(0,5);
 const currentYear=households.flatMap(h=>h.affiliations.membership_year||[])[0]||"2026–27";
 const attentionCount=(renewalDue?1:0)+(announcements.length?1:0)+(upcomingEvents.length?1:0); const featuredEvent=upcomingEvents[0];
 const photoStories=[...activities].filter(item=>!!item.thumbnailUrl).sort((x,y)=>text(y.createdAt||y.startsAt).localeCompare(text(x.createdAt||x.startsAt))).slice(0,6);
 const professions=countTop(people.flatMap(person=>[text(person.entity.metadata?.profession),...(person.affiliations.profession||[])]).filter(Boolean),5);
 const areas=countTop(people.flatMap(person=>[text(person.entity.metadata?.area),text(person.entity.metadata?.city),...(person.affiliations.area||[]),...(person.affiliations.city||[])]).filter(Boolean),5);
 const maxProfession=Math.max(1,...professions.map(([,count])=>count));
 const openActivity=(id:string)=>{if(onOpenActivity)onOpenActivity(id);else onGo("community")};
 const openGroup=(id:string)=>{if(onOpenGroup)onOpenGroup(id);else onGo("community")};
 if(familyCommunity)return <div data-testid="qa-fca-flagship-home" className="association-signature-home mpf-visual-home">
  <section className={`association-hero mpf-visual-hero ${coverUrl?"has-cover":""}`} style={coverUrl?{backgroundImage:`linear-gradient(105deg,rgba(16,26,61,.92),rgba(24,55,105,.72) 48%,rgba(173,87,38,.28)),url("${coverUrl}")`}:undefined}>
   <div className="association-hero-copy">
    {onCoverChange&&<label className="network-cover-edit"><ImagePlus size={15}/><span>{coverBusy?"Updating…":coverUrl?"Change cover":"Add community cover"}</span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={coverBusy} onChange={e=>{const file=e.target.files?.[0];if(file)void onCoverChange(file);e.currentTarget.value=""}}/></label>}
    <span className="association-kicker"><Sparkles size={13}/> {t("CommunityFamilyBelongingTxt")}</span><h1>{networkName}</h1><p>{t("CommunityHomeHeroDescTxt")}</p>
    <div className="mpf-hero-people"><div className="mpf-avatar-stack">{people.slice(0,7).map(person=>{const photo=personPhoto(person);return <span key={person.entity.id} title={person.entity.label}>{photo?<img src={photo} alt="" loading="lazy"/>:initials(person.entity.label)}</span>})}{people.length===0&&<span><UsersRound size={18}/></span>}</div><span><b>{people.length}</b> members · <b>{households.length}</b> families</span></div>
    <div className="association-hero-actions"><button className="btn primary" onClick={()=>onGo("community")}><CalendarDays size={16}/> See what’s happening</button><button className="btn" onClick={()=>onGo("directory")}><UsersRound size={16}/> Meet the community</button><button className="btn" onClick={()=>onGo("contribute")}><HeartHandshake size={16}/> Contribute</button></div>
   </div>
   <div className="mpf-hero-side">{featuredEvent?<button className="mpf-feature-event" onClick={()=>openActivity(featuredEvent.id)}><div className={`mpf-feature-event-media ${featuredEvent.thumbnailUrl?"has-image":""}`} style={featuredEvent.thumbnailUrl?{backgroundImage:`linear-gradient(180deg,rgba(8,18,40,.02),rgba(8,18,40,.72)),url("${featuredEvent.thumbnailUrl}")`}:undefined}>{!featuredEvent.thumbnailUrl&&<><CalendarDays size={32}/><span>Add an event image to make this moment visual</span></>}<span className="mpf-live-pill">UP NEXT</span></div><div className="mpf-feature-event-copy"><small>{featuredEvent.startsAt?new Date(featuredEvent.startsAt).toLocaleDateString(undefined,{weekday:"short",day:"numeric",month:"short"}):"Upcoming event"}</small><strong>{featuredEvent.title}</strong><span>{featuredEvent.place||"Community event"}{typeof featuredEvent.goingCount==="number"?` · ${featuredEvent.goingCount} going`:""}</span></div></button>:<button className="mpf-feature-event empty" onClick={()=>onGo("community")}><div className="mpf-feature-event-media"><PartyPopper size={36}/><span>Create the next gathering, celebration or community moment</span></div><div className="mpf-feature-event-copy"><small>YOUR NEXT MOMENT</small><strong>Give members something to look forward to</strong><span>Events become the visual heartbeat of the community.</span></div></button>}</div>
  </section>
  <section className="mpf-today-strip"><div className="mpf-today-title"><span><BellRing size={16}/></span><div><small>COMMUNITY TODAY</small><b>{attentionCount?`${attentionCount} things worth a look`:"You’re all caught up"}</b></div></div><button className="celebration" onClick={()=>onGo("community")}><Cake/><strong>{birthdays.length}</strong><span>Birthdays</span></button><button className="events" onClick={()=>onGo("community")}><CalendarDays/><strong>{upcomingEvents.length}</strong><span>Events</span></button><button className="members" onClick={()=>onGo("directory")}><UsersRound/><strong>{people.length}</strong><span>People</span></button><button className="renewal" onClick={()=>onGo("directory")}><RefreshCw/><strong>{renewalDue}</strong><span>Renewals</span></button></section>
  <section className="mpf-browse-grid">
   <article className="card mpf-celebrations-card"><div className="association-section-title"><div><span>Celebrate</span><h2>People & moments</h2></div><button onClick={()=>onGo("community")}>All moments <ArrowRight size={14}/></button></div>{birthdays.length?<div className="mpf-celebration-rail">{birthdays.map(({person,next})=>{const photo=personPhoto(person);return <button key={person.entity.id} onClick={()=>onGo("directory")}><span>{photo?<img src={photo} alt="" loading="lazy"/>:<>{initials(person.entity.label)}<Cake size={14}/></>}</span><b>{person.entity.label}</b><small>{formatShortDate(next)}</small></button>})}</div>:<div className="mpf-visual-empty warm"><Cake/><div><b>Celebrations will appear here</b><span>Add member birthdays to make Home feel personal.</span></div></div>}</article>
   <article className="card mpf-people-card"><div className="association-section-title"><div><span>Discover</span><h2>People in your community</h2></div><button onClick={()=>onGo("directory")}>Directory <ArrowRight size={14}/></button></div>{people.length?<><div className="mpf-people-rail">{people.slice(0,8).map(person=>{const photo=personPhoto(person),profession=text(person.entity.metadata?.profession)||text(person.entity.metadata?.role)||"Community member";return <button key={person.entity.id} onClick={()=>onGo("directory")}><span>{photo?<img src={photo} alt="" loading="lazy"/>:initials(person.entity.label)}</span><b>{person.entity.label}</b><small>{profession}</small></button>})}</div><button className="mpf-inline-link" onClick={()=>onGo("explorer")}><GitBranch size={14}/> Explore families & connections <ArrowRight size={13}/></button></>:<div className="mpf-visual-empty blue"><UsersRound/><div><b>Your community will become visible here</b><span>Add members and profile photos for a people-first experience.</span></div></div>}</article>
   <article className="card mpf-stories-card association-wide-card"><div className="association-section-title"><div><span>From the community</span><h2>Photos, memories & updates</h2></div><button onClick={()=>onGo("community")}>Community life <ArrowRight size={14}/></button></div>{photoStories.length?<div className="mpf-story-rail">{photoStories.map(story=><button key={story.id} onClick={()=>openActivity(story.id)}><div className="mpf-story-image" style={{backgroundImage:`linear-gradient(180deg,transparent 35%,rgba(9,16,35,.8)),url("${story.thumbnailUrl}")`}}><span>{story.type==="memory"?"Memory":story.type==="event"?"Event":story.metadata?.content_kind==="post"?"Post":"Update"}</span><div><b>{story.title}</b>{story.startsAt&&<small>{formatShortDate(new Date(story.startsAt))}</small>}</div></div></button>)}</div>:<div className="mpf-story-placeholder"><div><Camera size={30}/><Sparkles size={18}/></div><section><b>Your community has a story worth seeing</b><p>Add one photo to an event, memory or post. Recent visual moments will appear here automatically.</p><button className="btn small" onClick={()=>onGo("community")}><ImagePlus size={14}/> Add the first visual moment</button></section></div>}</article>
   <article className="card mpf-insight-card"><div className="association-section-title"><div><span>Community pulse</span><h2>What makes us diverse</h2></div><TrendingUp size={18}/></div>{professions.length?<div className="mpf-insight-bars">{professions.map(([label,count])=><div key={label}><span><b>{label}</b><small>{count}</small></span><i><em style={{width:`${Math.max(12,Math.round(count/maxProfession*100))}%`}}/></i></div>)}</div>:<div className="mpf-visual-empty violet"><BriefcaseBusiness/><div><b>Professional mix will appear here</b><span>Add professions to profiles to reveal useful community patterns.</span></div></div>}{areas.length>0&&<div className="mpf-area-cloud"><span><MapPin size={13}/> Around the community</span><div>{areas.map(([label,count])=><button key={label} onClick={()=>onGo("directory")}>{label}<b>{count}</b></button>)}</div></div>}</article>
   <article className="card mpf-news-card"><div className="association-section-title"><div><span>Stay informed</span><h2>Latest from the community</h2></div><button onClick={()=>onGo("community")}>View all <ArrowRight size={14}/></button></div><div className="mpf-news-list">{announcements.length?announcements.map(item=><button key={item.id} onClick={()=>openActivity(item.id)}>{item.thumbnailUrl?<img src={item.thumbnailUrl} alt="" loading="lazy"/>:<span><Megaphone size={17}/></span>}<div><b>{item.title}</b>{item.body&&<small>{item.body}</small>}</div><ArrowRight size={14}/></button>):<div className="mpf-visual-empty saffron"><Megaphone/><div><b>No updates yet</b><span>Announcements and important community posts will collect here.</span></div></div>}</div></article>
   <article className="card mpf-journey-card association-wide-card"><div className="association-section-title"><div><span>Our journey</span><h2>Community history</h2></div><button onClick={()=>onGo("community")}>View history <ArrowRight size={14}/></button></div>{timeline.length?<div className="association-mini-timeline mpf-mini-timeline">{timeline.map(item=><article key={item.id}>{item.thumbnailUrl?<img src={item.thumbnailUrl} alt="" loading="lazy"/>:<span><History size={14}/></span>}<div><small>{item.startsAt?new Date(item.startsAt).getFullYear():item.type==="memory"?"MEMORY":"MOMENT"}</small><b>{item.title}</b>{item.body&&<p>{item.body}</p>}</div></article>)}</div>:<div className="mpf-visual-empty gold"><History/><div><b>Your history grows from today</b><span>Memories, milestones and events become a visual community timeline.</span></div></div>}</article>
   <article className="card mpf-groups-card"><div className="association-section-title"><div><span>Participate</span><h2>Groups & circles</h2></div><button onClick={()=>onGo("community")}>Explore <ArrowRight size={14}/></button></div><div className="association-group-list">{groups.slice(0,4).map(g=><button className="association-group-open" key={g.id} onClick={()=>openGroup(g.id)}><span>{g.name}</span><b>{g.memberCount||0}</b></button>)}{groups.length===0&&<div><span>Community groups</span><b>0</b></div>}</div><div className="association-quick-links"><button onClick={()=>onGo("contribute")}><Clock3/> Build together</button><button onClick={()=>onGo("guide")}><BookOpen/> Guide</button><button onClick={()=>onGo("connections")}><HeartHandshake/> Connections</button></div></article>
   <article className="card mpf-membership-card"><div className="association-section-title"><div><span>Membership</span><h2>{currentYear}</h2></div><BadgeCheck size={19}/></div><div className="mpf-membership-numbers"><div><strong>{active}</strong><span>Active families</span></div><div className={renewalDue?"attention":""}><strong>{renewalDue}</strong><span>Renewals due</span></div></div><button className="btn small" onClick={()=>onGo("directory")}>Review families <ArrowRight size={14}/></button></article>
  </section>
 </div>;
 return <div data-testid="qa-fca-flagship-home" className="association-signature-home">
  <section className={`association-hero ${coverUrl?"has-cover":""}`} style={coverUrl?{backgroundImage:`linear-gradient(90deg,rgba(23,24,52,.86),rgba(23,24,52,.38)),url("${coverUrl}")`}:undefined}>
   <div className="association-hero-copy">{onCoverChange&&<label className="network-cover-edit"><ImagePlus size={15}/><span>{coverBusy?"Updating…":coverUrl?"Change cover":"Add cover photo"}</span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={coverBusy} onChange={e=>{const file=e.target.files?.[0];if(file)void onCoverChange(file);e.currentTarget.value=""}}/></label>}<span className="association-kicker"><Sparkles size={13}/> {t("CommunityFamilyBelongingTxt")}</span><h1>{networkName}</h1><p>{t("CommunityHomeHeroDescTxt")}</p><div className="association-hero-actions"><button className="btn primary" onClick={()=>onGo("directory")}><UsersRound size={16}/> {t("FamiliesTxt")}</button><button className="btn" onClick={()=>onGo("community")}><CalendarDays size={16}/> {t("EventsCommunityTxt")}</button><button className="btn" onClick={()=>onGo("contribute")}><HeartHandshake size={16}/> {t("BuildTogetherTxt")}</button></div></div>
   <div className="association-emblem" aria-label={t("CommunityIdentityTxt")}><div className="association-emblem-mark">म</div><small>{familyCommunity?t("FamilyCommunityTxt"):t("CommunityAssociationTxt")}</small><b>{currentYear}</b><span><BadgeCheck size={14}/> {t("PrivateMemberCommunityTxt")}</span></div>
  </section>

  <section className="association-attention-strip">
   <div><span className="association-attention-icon"><BellRing size={17}/></span><div><small>{t("CommunityTodayTxt")}</small><b>{attentionCount?`${attentionCount} ${t("ThingsWorthAttentionTxt")}`:t("AllCaughtUpTxt")}</b></div></div>
   <div className="association-attention-items">
    <button onClick={()=>onGo("directory")}><strong>{renewalDue}</strong><span>{t("RenewalsDueTxt")}</span></button>
    <button onClick={()=>onGo("community")}><strong>{upcomingEvents.length}</strong><span>{t("UpcomingEventsTxt")}</span></button>
    <button onClick={()=>onGo("community")}><strong>{birthdays.length}</strong><span>{t("BirthdaysComingUpTxt")}</span></button>
   </div>
  </section>

  <section className="association-stat-grid">
   <article><UsersRound/><div><strong>{households.length}</strong><span>{t("FamiliesTxt")}</span></div></article>
   <article><HeartHandshake/><div><strong>{people.length}</strong><span>{t("MembersTxt")}</span></div></article>
   <article><BadgeCheck/><div><strong>{active}</strong><span>{t("ActiveMembershipsTxt")}</span></div></article>
   <article className={renewalDue?"attention":""}><RefreshCw/><div><strong>{renewalDue}</strong><span>{t("RenewalsDueTxt")}</span></div></article>
  </section>

  <div className="association-dashboard-grid">
   <section className="card association-now-card"><div className="association-section-title"><div><span>{t("ComingUpTxt")}</span><h2>{t("CommunityMomentsTxt")}</h2></div><button onClick={()=>onGo("community")}>{t("ViewAllTxt")} <ArrowRight size={14}/></button></div><div className="association-upcoming-list">
    {birthdays.slice(0,2).map(({person,next})=><article key={person.entity.id}><span className="association-date-badge birthday"><Cake size={16}/></span><div><b>{person.entity.label}</b><small>{formatShortDate(next)} · {text(person.entity.metadata?.relation)||t("FamilyMemberTxt")}</small></div></article>)}
    {upcomingEvents.slice(0,3).map(event=><article key={event.id}>{event.thumbnailUrl?<img className="association-moment-thumb" src={event.thumbnailUrl} alt="" loading="lazy"/>:<span className="association-date-badge"><CalendarDays size={16}/></span>}<div><b>{event.title}</b><small>{event.startsAt?formatShortDate(new Date(event.startsAt)):t("UpcomingTxt")}{event.place?` · ${event.place}`:""}{typeof event.goingCount==="number"?` · ${event.goingCount} ${t("GoingTxt")}`:""}</small></div></article>)}
    {!birthdays.length&&!upcomingEvents.length&&<p className="muted">{t("NoUpcomingCommunityMomentsTxt")}</p>}
   </div></section>

   <section className="card association-family-card"><div className="association-section-title"><div><span>{t("PeopleTxt")}</span><h2>{t("FamiliesMembersTxt")}</h2></div><button onClick={()=>onGo("directory")}>{t("OpenDirectoryTxt")} <ArrowRight size={14}/></button></div><p>{t("FamiliesMembersDescTxt")}</p><div className="association-avatar-row">{people.slice(0,6).map(person=>{const photo=text(person.entity.metadata?.photo_display_url)||text(person.entity.metadata?.photo_url);return <span key={person.entity.id} title={person.entity.label}>{photo?<img src={photo} alt=""/>:initials(person.entity.label)}</span>})}</div><div className="association-profile-chips">{people.slice(0,4).map(person=><span key={person.entity.id}><b>{person.entity.label}</b><small>{text(person.entity.metadata?.profession)||text(person.entity.metadata?.role)||t("MemberTxt")}</small></span>)}</div><button className="btn small" onClick={()=>onGo("explorer")}><GitBranch size={14}/> {t("ExploreFamilyStructureTxt")}</button></section>

   <section className="card association-announcement-card"><div className="association-section-title"><div><span>{t("StayInformedTxt")}</span><h2>{t("AnnouncementsTxt")}</h2></div><button onClick={()=>onGo("community")}>{t("CommunityLifeTxt")} <ArrowRight size={14}/></button></div><div className="association-announcement-list">{announcements.length?announcements.map(a=><article key={a.id}>{a.thumbnailUrl?<img className="association-announcement-thumb" src={a.thumbnailUrl} alt="" loading="lazy"/>:<span><Megaphone size={15}/></span>}<div><b>{a.title}</b>{a.body&&<p>{a.body}</p>}</div></article>):<article><span><Megaphone size={15}/></span><div><b>{t("MembershipRenewalOpenTxt")}</b><p>{t("MembershipRenewalOpenDescTxt")}</p></div></article>}</div></section>

   <section className="card association-community-card"><div className="association-section-title"><div><span>{t("ParticipateTxt")}</span><h2>{t("CommunityGroupsTxt")}</h2></div><button onClick={()=>onGo("community")}>{t("ExploreTxt")} <ArrowRight size={14}/></button></div><div className="association-group-list">{groups.slice(0,4).map(g=><button className="association-group-open" key={g.id} onClick={()=>openGroup(g.id)}><span>{g.name}</span><b>{g.memberCount||0}</b></button>)}</div><div className="association-quick-links"><button onClick={()=>onGo("contribute")}><Clock3/> {t("BuildTogetherTxt")}</button><button onClick={()=>onGo("guide")}><BookOpen/> {t("GuideHelpTxt")}</button><button onClick={()=>onGo("connections")}><HeartHandshake/> {t("CommunityConnectionsTxt")}</button></div></section>

   <section className="card association-timeline-card association-wide-card"><div className="association-section-title"><div><span>{t("OurJourneyTxt")}</span><h2>{t("CommunityHistoryTxt")}</h2></div><button onClick={()=>onGo("community")}>{t("ViewHistoryTxt")} <ArrowRight size={14}/></button></div><div className="association-mini-timeline">{timeline.map(item=><article key={item.id}><span><History size={14}/></span><div><small>{item.startsAt?new Date(item.startsAt).getFullYear():t("MemoryTxt")}</small><b>{item.title}</b>{item.body&&<p>{item.body}</p>}</div></article>)}</div></section>
  </div>
 </div>
}
