"use client";
import {useEffect,useMemo,useState} from "react";
import {BadgeIndianRupee,CalendarRange,History,Save,ShieldCheck,UsersRound} from "lucide-react";
import type {NetworkAffiliatedEntity} from "../core/network-os/contracts";
import {addFcaFinanceEntry,assignFcaRole,fetchFcaAdminSnapshot,setFcaFamilyMembership,updateFcaSettings,upsertFcaMembershipYear,type FcaAdminSnapshot} from "../capabilities/template-product/remote";
import {NetworkEmpty,NetworkMetric,NetworkSectionHead} from "./shared/NetworkUi";
import ResponsiveSectionTabs from "./shared/ResponsiveSectionTabs";
import {useLanguage} from "../lib/i18n";

type AdminSection="policy"|"year"|"membership"|"leadership"|"finance";

export default function FamilyAssociationAdminPanel({entities,onNotify}:{entities:NetworkAffiliatedEntity[];onNotify:(s:string)=>void}){
 const {t:xp2t}=useLanguage();
 const [data,setData]=useState<FcaAdminSnapshot|null>(null),[busy,setBusy]=useState(false),[section,setSection]=useState<AdminSection>("policy");
 const load=async()=>{try{setData(await fetchFcaAdminSnapshot())}catch(e:any){onNotify(e.message||"Could not load annual association controls.")}};
 useEffect(()=>{void load()},[]);
 const families=useMemo(()=>entities.filter(e=>e.entity.kind==="family"),[entities]),people=useMemo(()=>entities.filter(e=>e.entity.kind==="person"),[entities]);
 const [settings,setSettings]=useState<any>({dependent_age_limit:22,grace_period_days:30,max_auto_children:2,onboarding_policy:"join_review_later",finance_visibility:"admins"});
 useEffect(()=>{if(data?.settings)setSettings((x:any)=>({...x,...data.settings}))},[data]);
 const [year,setYear]=useState({label:"2026–27",startDate:"2026-04-01",endDate:"2027-03-31",familyFee:"",grace:"30",status:"open"});
 const [membership,setMembership]=useState({yearId:"",familyId:"",representativeId:"",status:"active",paymentStatus:"paid",amountPaid:"",reference:""});
 const [role,setRole]=useState({yearId:"",personId:"",roleId:"",startsOn:"",endsOn:"",notes:""});
 const [finance,setFinance]=useState({yearId:"",entryType:"membership_collection",amount:"",description:"",visibility:"admins"});
 const activeYear=data?.years?.find((y:any)=>y.status==="open")||data?.years?.[0];
 useEffect(()=>{if(activeYear){setMembership(x=>({...x,yearId:x.yearId||activeYear.id}));setRole(x=>({...x,yearId:x.yearId||activeYear.id}));setFinance(x=>({...x,yearId:x.yearId||activeYear.id}))}},[activeYear?.id]);
 const run=async(fn:()=>Promise<any>,msg:string)=>{setBusy(true);try{await fn();onNotify(msg);await load()}catch(e:any){onNotify(e.message||"Could not save.")}finally{setBusy(false)}};
 const totalCollected=(data?.finance||[]).filter((x:any)=>Number(x.amount)>0).reduce((n:number,x:any)=>n+Number(x.amount||0),0),totalSpent=Math.abs((data?.finance||[]).filter((x:any)=>Number(x.amount)<0||["expense","event_allocation","good_cause"].includes(x.entry_type)).reduce((n:number,x:any)=>n+Number(x.amount||0),0));
 if(!data)return <NetworkEmpty title={xp2t("XP2Visible0054Txt")} description={xp2t("XP2Visible0055Txt")}/>;
 const sections=[
  {id:"policy" as const,label:"Community policy",description:"Membership, onboarding and finance visibility defaults.",icon:<ShieldCheck size={14}/>},
  {id:"year" as const,label:"Membership year",description:"Annual cycle, fee and grace period.",icon:<CalendarRange size={14}/>,badge:data.years.length},
  {id:"membership" as const,label:"Family membership",description:"Representative, renewal and payment state.",icon:<UsersRound size={14}/>,badge:data.memberships.length},
  {id:"leadership" as const,label:"Leadership",description:"Committee roles and historical assignments.",icon:<History size={14}/>,badge:data.role_history.length},
  {id:"finance" as const,label:"Finance",description:"Collections, allocations and community entries.",icon:<BadgeIndianRupee size={14}/>,badge:data.finance.length},
 ];
 return <div data-testid="qa-fca-admin-panel" className="fca-admin-panel section-workspace" data-ui-progressive="workspace">
  <NetworkSectionHead kicker={<><ShieldCheck size={12}/> {xp2t("XP2Visible0056Txt")}</>} title={xp2t("XP2Visible0057Txt")} description={xp2t("XP2Visible0058Txt")}/>
  <div className="network-metric-grid"><NetworkMetric value={families.length} label={xp2t("XP2Visible0059Txt")}/><NetworkMetric value={people.length} label={xp2t("XP2Visible0060Txt")}/><NetworkMetric value={data.memberships.filter((m:any)=>m.status==="active").length} label={xp2t("XP2Visible0030Txt")}/><NetworkMetric value={`₹${totalCollected.toLocaleString("en-IN")}`} label={xp2t("XP2Visible0061Txt")}/></div>
  <ResponsiveSectionTabs options={sections} active={section} onChange={setSection} label="Community administration"/>
  <div className="section-workspace-stage" data-testid={`qa-fca-admin-section-${section}`}>
   {section==="policy"&&<section className="card"><span className="warm-kicker"><CalendarRange size={12}/> {xp2t("XP2Visible0062Txt")}</span><h3>{xp2t("XP2Visible0063Txt")}</h3><div className="form-grid"><label className="field"><span>{xp2t("XP2Visible0064Txt")}</span><input className="text-input" type="number" value={settings.dependent_age_limit} onChange={e=>setSettings({...settings,dependent_age_limit:Number(e.target.value)})}/></label><label className="field"><span>{xp2t("XP2Visible0065Txt")}</span><input className="text-input" type="number" value={settings.grace_period_days} onChange={e=>setSettings({...settings,grace_period_days:Number(e.target.value)})}/></label><label className="field"><span>{xp2t("XP2Visible0066Txt")}</span><input className="text-input" type="number" value={settings.max_auto_children} onChange={e=>setSettings({...settings,max_auto_children:Number(e.target.value)})}/></label><label className="field"><span>{xp2t("XP2Visible0067Txt")}</span><select className="select" value={settings.onboarding_policy} onChange={e=>setSettings({...settings,onboarding_policy:e.target.value})}><option value="join_review_later">{xp2t("XP2Visible0068Txt")}</option><option value="approval_required">{xp2t("XP2Visible0069Txt")}</option><option value="invitation_only">{xp2t("XP2Visible0070Txt")}</option></select></label><label className="field"><span>{xp2t("XP2Visible0071Txt")}</span><select className="select" value={settings.finance_visibility} onChange={e=>setSettings({...settings,finance_visibility:e.target.value})}><option value="admins">{xp2t("XP2Visible0072Txt")}</option><option value="members">{xp2t("XP2Visible0073Txt")}</option><option value="highlighted">{xp2t("XP2Visible0074Txt")}</option></select></label></div><button className="btn primary" disabled={busy} onClick={()=>run(()=>updateFcaSettings({dependentAgeLimit:Number(settings.dependent_age_limit),gracePeriodDays:Number(settings.grace_period_days),maxAutoChildren:Number(settings.max_auto_children),onboardingPolicy:settings.onboarding_policy,financeVisibility:settings.finance_visibility}),"Community policy updated.")}><Save size={14}/> {xp2t("XP2Visible0075Txt")}</button></section>}
   {section==="year"&&<section className="card"><span className="warm-kicker"><CalendarRange size={12}/> {xp2t("XP2Visible0076Txt")}</span><h3>{xp2t("XP2Visible0077Txt")}</h3><div className="form-grid"><label className="field"><span>{xp2t("XP2Visible0078Txt")}</span><input className="text-input" value={year.label} onChange={e=>setYear({...year,label:e.target.value})}/></label><label className="field"><span>{xp2t("XP2Visible0079Txt")}</span><input className="text-input" type="number" value={year.familyFee} onChange={e=>setYear({...year,familyFee:e.target.value})}/></label><label className="field"><span>{xp2t("XP2Visible0080Txt")}</span><input className="text-input" type="date" value={year.startDate} onChange={e=>setYear({...year,startDate:e.target.value})}/></label><label className="field"><span>{xp2t("XP2Visible0081Txt")}</span><input className="text-input" type="date" value={year.endDate} onChange={e=>setYear({...year,endDate:e.target.value})}/></label><label className="field"><span>{xp2t("XP2Visible0082Txt")}</span><input className="text-input" type="number" value={year.grace} onChange={e=>setYear({...year,grace:e.target.value})}/></label></div><button className="btn primary" disabled={busy||!year.label||!year.familyFee} onClick={()=>run(()=>upsertFcaMembershipYear({label:year.label,startDate:year.startDate,endDate:year.endDate,familyFee:Number(year.familyFee),gracePeriodDays:Number(year.grace),status:year.status}),"Membership year saved.")}>{xp2t("XP2Visible0083Txt")}</button><div className="fca-history-list">{data.years.map((y:any)=><div key={y.id}><b>{y.label}</b><span>₹{Number(y.family_fee).toLocaleString("en-IN")} {xp2t("XP2Visible0084Txt")}</span><small>{y.start_date} → {y.end_date} · {y.status}</small></div>)}</div></section>}
   {section==="membership"&&<section className="card"><span className="warm-kicker"><UsersRound size={12}/> {xp2t("XP2Visible0085Txt")}</span><h3>{xp2t("XP2Visible0086Txt")}</h3><div className="form-grid"><label className="field full"><span>{xp2t("XP2Visible0087Txt")}</span><select className="select" value={membership.yearId} onChange={e=>setMembership({...membership,yearId:e.target.value})}><option value="">{xp2t("XP2Visible0088Txt")}</option>{data.years.map((y:any)=><option value={y.id} key={y.id}>{y.label}</option>)}</select></label><label className="field"><span>{xp2t("XP2Visible0089Txt")}</span><select className="select" value={membership.familyId} onChange={e=>setMembership({...membership,familyId:e.target.value})}><option value="">{xp2t("XP2Visible0088Txt")}</option>{families.map(f=><option value={f.entity.id} key={f.entity.id}>{f.entity.label}</option>)}</select></label><label className="field"><span>{xp2t("XP2Visible0090Txt")}</span><select className="select" value={membership.representativeId} onChange={e=>setMembership({...membership,representativeId:e.target.value})}><option value="">{xp2t("XP2Visible0088Txt")}</option>{people.map(p=><option value={p.entity.id} key={p.entity.id}>{p.entity.label}</option>)}</select></label><label className="field"><span>{xp2t("XP2Visible0091Txt")}</span><select className="select" value={membership.status} onChange={e=>setMembership({...membership,status:e.target.value})}>{["pending","active","grace","inactive","removed","transferred"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>{xp2t("XP2Visible0092Txt")}</span><select className="select" value={membership.paymentStatus} onChange={e=>setMembership({...membership,paymentStatus:e.target.value})}>{["unpaid","paid","waived","partial","not_required"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>{xp2t("XP2Visible0093Txt")}</span><input className="text-input" type="number" value={membership.amountPaid} onChange={e=>setMembership({...membership,amountPaid:e.target.value})}/></label><label className="field"><span>{xp2t("XP2Visible0094Txt")}</span><input className="text-input" value={membership.reference} onChange={e=>setMembership({...membership,reference:e.target.value})}/></label></div><button className="btn primary" disabled={busy||!membership.yearId||!membership.familyId} onClick={()=>run(()=>setFcaFamilyMembership({yearId:membership.yearId,familyEntityId:membership.familyId,representativeEntityId:membership.representativeId||null,status:membership.status,paymentStatus:membership.paymentStatus,amountPaid:Number(membership.amountPaid||0),paymentReference:membership.reference}),"Family membership updated.")}>{xp2t("XP2Visible0095Txt")}</button></section>}
   {section==="leadership"&&<section className="card"><span className="warm-kicker"><History size={12}/> {xp2t("XP2Visible0096Txt")}</span><h3>{xp2t("XP2Visible0097Txt")}</h3><div className="form-grid"><label className="field"><span>{xp2t("XP2Visible0098Txt")}</span><select className="select" value={role.yearId} onChange={e=>setRole({...role,yearId:e.target.value})}><option value="">{xp2t("XP2Visible0088Txt")}</option>{data.years.map((y:any)=><option value={y.id} key={y.id}>{y.label}</option>)}</select></label><label className="field"><span>{xp2t("XP2Visible0099Txt")}</span><select className="select" value={role.personId} onChange={e=>setRole({...role,personId:e.target.value})}><option value="">{xp2t("XP2Visible0088Txt")}</option>{people.map(p=><option value={p.entity.id} key={p.entity.id}>{p.entity.label}</option>)}</select></label><label className="field"><span>{xp2t("XP2Visible0100Txt")}</span><select className="select" value={role.roleId} onChange={e=>setRole({...role,roleId:e.target.value})}><option value="">{xp2t("XP2Visible0088Txt")}</option>{data.roles.map((r:any)=><option value={r.id} key={r.id}>{r.label}{r.portfolio?` — ${r.portfolio}`:""}</option>)}</select></label><label className="field"><span>{xp2t("XP2Visible0101Txt")}</span><input className="text-input" type="date" value={role.startsOn} onChange={e=>setRole({...role,startsOn:e.target.value})}/></label><label className="field"><span>{xp2t("XP2Visible0102Txt")}</span><input className="text-input" type="date" value={role.endsOn} onChange={e=>setRole({...role,endsOn:e.target.value})}/></label></div><button className="btn primary" disabled={busy||!role.personId||!role.roleId} onClick={()=>run(()=>assignFcaRole({yearId:role.yearId||null,personEntityId:role.personId,roleCatalogId:role.roleId,startsOn:role.startsOn||null,endsOn:role.endsOn||null,notes:role.notes}),"Leadership history updated.")}>{xp2t("XP2Visible0103Txt")}</button><div className="fca-history-list">{data.role_history.slice(0,8).map((h:any)=><div key={h.id}><b>{h.person_label}</b><span>{h.role_label}{h.portfolio?` · ${h.portfolio}`:""}</span><small>{h.year_label||"Historical"}</small></div>)}</div></section>}
   {section==="finance"&&<section className="card"><span className="warm-kicker"><BadgeIndianRupee size={12}/> {xp2t("XP2Visible0104Txt")}</span><h3>{xp2t("XP2Visible0105Txt")}</h3><div className="form-grid"><label className="field"><span>{xp2t("XP2Visible0098Txt")}</span><select className="select" value={finance.yearId} onChange={e=>setFinance({...finance,yearId:e.target.value})}><option value="">{xp2t("XP2Visible0088Txt")}</option>{data.years.map((y:any)=><option value={y.id} key={y.id}>{y.label}</option>)}</select></label><label className="field"><span>{xp2t("XP2Visible0106Txt")}</span><select className="select" value={finance.entryType} onChange={e=>setFinance({...finance,entryType:e.target.value})}>{["opening_balance","membership_collection","donation","event_contribution","sponsorship","event_allocation","good_cause","expense","carry_forward","adjustment"].map(x=><option key={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label className="field"><span>{xp2t("XP2Visible0107Txt")}</span><input className="text-input" type="number" value={finance.amount} onChange={e=>setFinance({...finance,amount:e.target.value})}/></label><label className="field"><span>{xp2t("XP2Visible0108Txt")}</span><select className="select" value={finance.visibility} onChange={e=>setFinance({...finance,visibility:e.target.value})}><option value="admins">{xp2t("XP2Visible0072Txt")}</option><option value="members">{xp2t("XP2Visible0073Txt")}</option><option value="highlighted">{xp2t("XP2Visible0109Txt")}</option></select></label><label className="field full"><span>{xp2t("XP2Visible0110Txt")}</span><input className="text-input" value={finance.description} onChange={e=>setFinance({...finance,description:e.target.value})}/></label></div><button className="btn primary" disabled={busy||!finance.yearId||!finance.amount} onClick={()=>run(()=>addFcaFinanceEntry({yearId:finance.yearId,entryType:finance.entryType,amount:Number(finance.amount),description:finance.description,visibility:finance.visibility}),"Finance entry added.")}>{xp2t("XP2Visible0111Txt")}</button><p className="fca-finance-note">{xp2t("XP2Visible0112Txt")}{totalCollected.toLocaleString("en-IN")} {xp2t("XP2Visible0113Txt")}{totalSpent.toLocaleString("en-IN")} {xp2t("XP2Visible0114Txt")}</p></section>}
  </div>
 </div>;
}
