"use client";
import {useLanguage} from "../lib/i18n";
import {useEffect,useState} from "react";
import {Download,HardDrive,KeyRound,Link2,Settings2,ShieldCheck,Users,UserRoundCog} from "lucide-react";
import {ChangeRequest,Member,Relationship} from "../lib/types";
import {NetworkSettings} from "../lib/network";
import {fetchFamilyAdminSummary,fetchFamilyFeatureSettings,fetchFamilyMemberships,FamilyAdminSummary,FamilyFeatureSetting,FamilyMembershipRow,setFamilyFeatureSetting,setFamilyMemberRole} from "../lib/remote";
import {FEATURE_REGISTRY} from "../lib/features";
import {archiveNetwork,deleteOwnedNetworkPermanently} from "../lib/network-lifecycle";
import NetworkBackupExport from "./shared/NetworkBackupExport";
import MediaManagementPanel from "./shared/MediaManagementPanel";
import ResponsiveSectionTabs from "./shared/ResponsiveSectionTabs";

type Tab="overview"|"members"|"approvals"|"privacy"|"storage"|"scale"|"memberFeatures"|"settings"|"export"|"danger";
export default function FamilyAdminCenter({network,members,relationships,memberCount,relationshipCount,changeRequests,onSaveSettings,onOpenInvitations,onOpenParticipation,onOpenFamilyIntake,onExportCsv,onExportJson,onPrint,onNotify,onFeatureSettingsChanged}:{network:NetworkSettings;members:Member[];relationships:Relationship[];memberCount:number;relationshipCount:number;changeRequests:ChangeRequest[];onSaveSettings:(p:Partial<NetworkSettings>)=>Promise<void>;onOpenInvitations:()=>void;onOpenParticipation:()=>void;onOpenFamilyIntake?:()=>void;onExportCsv:()=>void;onExportJson:()=>void;onPrint:()=>void;onNotify:(s:string)=>void;onFeatureSettingsChanged?:()=>Promise<void>|void}){
 const {t:xp2t}=useLanguage();
 const {t:tr}=useLanguage();
 const [tab,setTab]=useState<Tab>("overview"),[deleteConfirm,setDeleteConfirm]=useState(""),[summary,setSummary]=useState<FamilyAdminSummary|null>(null),[people,setPeople]=useState<FamilyMembershipRow[]>([]),[memberFeatures,setMemberFeatures]=useState<FamilyFeatureSetting[]>([]),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [s,p,f]=await Promise.all([fetchFamilyAdminSummary(),fetchFamilyMemberships(),fetchFamilyFeatureSettings().catch(()=>[])]);setSummary(s);setPeople(p);setMemberFeatures(f)}catch(e:any){onNotify(e.message||"Could not load family administration.")}};
 useEffect(()=>{load()},[network.network_id]);
 const pending=changeRequests.filter(x=>x.status==="pending").length;
 const incomplete=members.filter(m=>!m.date_of_birth||!m.city||!m.bio).length;
 const isolated=members.filter(m=>!relationships.some(r=>r.person_id===m.id||r.related_person_id===m.id)).length;
 const dupes=members.flatMap((m,i)=>members.slice(i+1).filter(n=>m.full_name.trim().toLowerCase()===n.full_name.trim().toLowerCase()&&(m.date_of_birth||"")===(n.date_of_birth||"")).map(n=>[m,n] as const));
 const health=Math.max(0,100-Math.min(45,dupes.length*15)-Math.min(30,isolated*5)-Math.min(25,Math.round(incomplete/Math.max(1,members.length)*25)));
 const storage=summary?.media_usage_bytes||0, limit=summary?.storage_limit_bytes||104857600, pct=Math.min(100,Math.round(storage/Math.max(1,limit)*100)), remaining=Math.max(0,limit-storage);
 const role=async(row:FamilyMembershipRow,next:"admin"|"member")=>{setBusy(true);try{await setFamilyMemberRole(row.user_id,next);await load();onNotify(`${row.display_name||row.email||"Member"} is now ${next}.`)}catch(e:any){onNotify(e.message||"Could not change family role.")}finally{setBusy(false)}};
 const inviteConversion=summary?.member_profiles?Math.round((summary.claimed_profiles||0)/Math.max(1,summary.member_profiles)*100):0;
 const adminReady=(summary?.admin_count||0)>=2, storageReady=pct<80, approvalReady=pending<=5, healthReady=health>=70;
 const scaleChecks=[adminReady,storageReady,approvalReady,healthReady,inviteConversion>=20]; const scaleScore=Math.round(scaleChecks.filter(Boolean).length/scaleChecks.length*100);
 const memberFeatureMap=Object.fromEntries(memberFeatures.map(f=>[f.feature_key,f.enabled]));
 const toggleMemberFeature=async(featureKey:string,enabled:boolean)=>{setBusy(true);try{await setFamilyFeatureSetting(featureKey,enabled);setMemberFeatures(v=>{const rest=v.filter(x=>x.feature_key!==featureKey);return [...rest,{feature_key:featureKey,enabled}]});await onFeatureSettingsChanged?.();onNotify(`${FEATURE_REGISTRY.find(f=>f.key===featureKey)?.label||featureKey} ${enabled?"enabled":"hidden"} for family members.`)}catch(e:any){onNotify(e.message||"Could not update member features.")}finally{setBusy(false)}};
 const tabs:[Tab,string][]=[["overview","Overview"],["members","Members & roles"],["approvals","Approvals"],["privacy","Privacy"],["storage","Storage"],["scale","Pilot readiness"],["memberFeatures","Member features"],["settings","Family settings"],["export","Export / backup"],["danger","Delete network"]];
 return <div data-testid="qa-admin-center" className="family-admin-center">
  <div className="admin-center-hero"><div><span className="warm-kicker"><ShieldCheck size={13}/> {tr("FamilyAdminCenterTxt")}</span><h1>{network.name}</h1><p>{tr("RunYourFamilyFromOnePlaceMembersTxt")}</p></div><div className="card-actions">{onOpenFamilyIntake&&<button className="btn warm" onClick={onOpenFamilyIntake}><Link2 size={15}/> {tr("BuildTogetherTxt")}</button>}<button className="btn primary" onClick={onOpenInvitations}><KeyRound size={15}/> {tr("InviteRelativesTxt")}</button></div></div>
  <ResponsiveSectionTabs className="family-admin-section-tabs" label="Family administration" active={tab} onChange={setTab} options={tabs.map(([id,label])=>({id,label}))}/>
  {tab==="overview"&&<><div className="alpha-readiness"><b>{tr("AlphaLaunchChecklistTxt")}</b><span>{tr("Ui1AddOrImportRelativesTxt")}</span><span>{tr("Ui2InviteAtLeast3RelativesTxt")}</span><span>{tr("Ui3ResolveFamilyHealthSuggestionsTxt")}</span><span>{tr("Ui4ExportABackupBeforeMajorChangesTxt")}</span></div><div className="admin-center-stats"><div><Users/><span><b>{memberCount}</b> {tr("FamilyProfilesTxt")}</span></div><div><UserRoundCog/><span><b>{summary?.claimed_profiles||0}</b> {tr("ClaimedProfilesTxt")}</span></div><div><KeyRound/><span><b>{summary?.active_invitations||0}</b> {tr("ActiveInvitesTxt")}</span></div><div><ShieldCheck/><span><b>{pending}</b> {tr("ApprovalsWaitingTxt")}</span></div></div><div className="admin-center-grid"><div className="card admin-action-card"><h3>{tr("FamilyHealthTxt")}{" "}{health}%</h3><p>{dupes.length?`${dupes.length} possible duplicate${dupes.length>1?"s":""} · `:""}{isolated} {tr("UnconnectedTxt")}{" "}{incomplete} {tr("ProfilesCanBeEnrichedTxt")}</p><button className="btn" onClick={onOpenParticipation}>{tr("ImproveFamilyTxt")}</button></div><div className="card admin-action-card"><h3>{tr("StorageTxt")}</h3><p>{(storage/1048576).toFixed(1)} {tr("MBOfTxt")}{" "}{(limit/1048576).toFixed(0)} {tr("MBUsedTxt")}</p><div className="usage-bar"><i style={{width:`${pct}%`}}/></div><small>{pct}{tr("UsedPhotosTxt")}{" "}{network.photo_upload_enabled?tr("EnabledTxt"):tr("DisabledTxt")}</small></div></div></>}
  {tab==="members"&&<div className="card admin-center-panel"><div className="section-title"><div><h2>{tr("MembersAndRolesTxt")}</h2><p className="page-subtitle">{tr("FamilyRolesApplyOnlyInsideThisFamilyTxt")}</p></div><button className="btn primary" onClick={onOpenInvitations}>{tr("InviteRelativesTxt")}</button></div>{people.length===0?<div className="empty compact">{tr("NoClaimedAccountsYetTxt")}</div>:people.map(p=><div data-testid={`qa-family-membership-${p.user_id}`} className="admin-member-row" key={p.user_id}><div className="admin-member-avatar">{(p.display_name||p.email||"?").slice(0,1).toUpperCase()}</div><span><b>{p.display_name||p.email||tr("FamilyMemberTxt")}</b><small>{p.email||tr("AccountConnectedTxt")}{p.member_name?` · profile: ${p.member_name}`:""}</small></span><em className={`role-pill ${p.role}`}>{p.role}</em>{p.role!=="owner"&&<select data-testid={`qa-family-role-${p.user_id}`} disabled={busy} value={p.role} onChange={e=>role(p,e.target.value as "admin"|"member")}><option value="member">{tr("MemberTxt")}</option><option value="admin">{tr("AdminTxt")}</option></select>}</div>)}</div>}
  {tab==="approvals"&&<div className="card admin-center-panel"><h2>{tr("PendingApprovalsTxt")}</h2><p className="page-subtitle">{tr("GovernedIdentityAndRelationshipChangesStayReviewableTxt")}</p>{changeRequests.filter(x=>x.status==="pending").length===0?<div className="empty compact">{tr("NothingIsWaitingForApprovalTxt")}</div>:changeRequests.filter(x=>x.status==="pending").map(x=><div className="admin-simple-row" key={x.id}><span><b>{x.action.replaceAll("_"," ")}</b><small>{new Date(x.created_at).toLocaleString()}</small></span><em>{tr("PendingTxt")}</em></div>)}</div>}
  {tab==="privacy"&&<div className="card admin-center-panel"><h2>{tr("PrivacyDefaultsTxt")}</h2><div className="admin-setting"><span><b>{tr("PhotoUploadsTxt")}</b><small>{tr("OffIsTheLightweightPrivacyConsciousAlphaTxt")}</small></span><input type="checkbox" checked={!!network.photo_upload_enabled} onChange={e=>onSaveSettings({photo_upload_enabled:e.target.checked})}/></div><div className="admin-setting"><span><b>{tr("SafeSelfEditsTxt")}</b><small>{tr("AllowMembersToDirectlyUpdateLowRiskTxt")}</small></span><input type="checkbox" checked={network.self_edit_mode==="safe_fields_direct"} onChange={e=>onSaveSettings({self_edit_mode:e.target.checked?"safe_fields_direct":"review"})}/></div></div>}
  {tab==="storage"&&<div className="card admin-center-panel"><h2>{tr("FamilyStorageTxt")}</h2><div className="storage-big"><HardDrive/><div><b>{(storage/1048576).toFixed(1)} {tr("MBTxt")}</b><span>{tr("OfTxt")}{" "}{(limit/1048576).toFixed(0)} {tr("MBAlphaAllowanceTxt")}</span></div></div><div className="usage-bar large"><i style={{width:`${pct}%`}}/></div><p className="page-subtitle">{tr("StoredFamilyMediaIsCountedPerFamilyTxt")}{" "}{(summary?.photo_max_bytes||102400)/1024} {tr("KBPerImageTxt")}</p>{pct>=90&&<div className="admin-storage-warning"><b>{pct>=100?tr("StorageLimitReachedTxt"):tr("FamilyStorageIsAlmostFullTxt")}</b><span>{(remaining/1048576).toFixed(1)} {tr("MBRemainingRemoveOlderMediaOrKeepTxt")}</span></div>}</div>}
  {tab==="storage"&&<MediaManagementPanel onNotify={onNotify}/>}
  {tab==="scale"&&<div className="card admin-center-panel"><div className="section-title"><div><h2>{tr("Ui2050FamilyReadinessTxt")}</h2><p className="page-subtitle">{tr("ASimpleOperatingGateForRunningMoreTxt")}</p></div><strong className="scale-score">{scaleScore}{tr("ReadyTxt")}</strong></div><div className="scale-checks">{[[adminReady,tr("ContinuityTxt"),tr("AtLeastTwoOwnerAdminAccountsTxt")],[storageReady,tr("StorageHeadroomTxt"),tr("FamilyStorageStaysBelow80Txt")],[approvalReady,tr("ApprovalLoadTxt"),tr("FiveOrFewerChangesWaitingTxt")],[healthReady,tr("FamilyDataHealthTxt"),tr("FamilyHealthIsAtLeast70Txt")],[inviteConversion>=20,tr("ActivationTxt"),tr("AtLeast20OfProfilesAreClaimedTxt")]].map(([ok,title,note])=><div className={`scale-check ${ok?"pass":"warn"}`} key={String(title)}><ShieldCheck size={17}/><span><b>{title}</b><small>{note}</small></span><em>{ok?tr("Ready2Txt"):tr("NeedsAttentionTxt")}</em></div>)}</div><div className="pilot-guardrails"><h3>{tr("AlphaOperatingGuardrailsTxt")}</h3><p>{tr("ForEachPilotFamilyConfirmAnOwnerTxt")}</p><div className="card-actions"><button className="btn" onClick={onOpenInvitations}>{tr("ImproveActivationTxt")}</button><button className="btn" onClick={onOpenParticipation}>{tr("OpenParticipationTxt")}</button><button className="btn primary" onClick={onExportJson}>{tr("CreateBackupTxt")}</button></div></div></div>}
  {tab==="memberFeatures"&&<div className="card admin-center-panel"><div className="section-title"><div><h2>{tr("FeaturesForFamilyMembersTxt")}</h2><p className="page-subtitle">{tr("ChooseWhichFounderReleasedCapabilitiesYourFamilyTxt")}</p></div></div><div className="family-feature-list">{FEATURE_REGISTRY.filter(f=>f.bundle!=="admin"&&f.minimumExperience!=="admin").map(feature=><div className="admin-setting" key={feature.key}><span><b>{feature.label}</b><small>{feature.description} · {feature.minimumExperience==="simple"?tr("SimpleTxt"):feature.minimumExperience==="connected"?tr("Connected3Txt"):tr("ExplorerTxt")}</small></span><input type="checkbox" disabled={busy} checked={memberFeatureMap[feature.key]!==false} onChange={e=>toggleMemberFeature(feature.key,e.target.checked)}/></div>)}</div><div className="notice"><b>{tr("ImportantTxt")}</b> {tr("TheseAreFamilyPreferencesNotReleaseControlsTxt")}</div></div>}
  {tab==="settings"&&<div className="card admin-center-panel"><h2>{tr("FamSettingsTxt")}</h2><div className="settings-readout"><label>{tr("FamilyNameTxt")}<strong>{network.name}</strong></label><label>{tr("FamilyURLTxt")}<strong>/{network.slug||tr("Family2Txt")}</strong></label><label>{tr("YourRoleTxt")}<strong>{network.membership_role||"admin"}</strong></label></div><div className="admin-setting"><span><b>{tr("UpcomingFamilyMilestonesTxt")}</b><small>{tr("ShowBirthdaysAndFamilyMomentsInTheTxt")}</small></span><input type="checkbox" checked={network.family_milestones_enabled!==false} onChange={e=>onSaveSettings({family_milestones_enabled:e.target.checked})}/></div></div>}
  {tab==="danger"&&<div className="card admin-center-panel fca-danger-zone"><h2>{xp2t("XP2Visible0016Txt")}</h2><p className="page-subtitle">{xp2t("XP2Visible0051Txt")}</p><label className="field"><span>{xp2t("XP2Visible0052Txt")}</span><input data-testid="qa-admin-danger-confirm" className="text-input" value={deleteConfirm} onChange={e=>setDeleteConfirm(e.target.value)} placeholder={network.name}/></label><div className="card-actions"><button data-testid="qa-admin-archive" className="btn" disabled={network.membership_role!=="owner"||deleteConfirm!==network.name||busy} onClick={async()=>{if(!confirm(`Archive ${network.name}? Members will lose active access, but all network data is preserved and restorable.`))return;setBusy(true);try{await archiveNetwork(network.network_id||network.id,deleteConfirm);onNotify("Network archived. Restore it from My Networks → Archived.");window.location.reload()}catch(e:any){onNotify(e.message||"Could not archive network.")}finally{setBusy(false)}}}>{xp2t("XP2Visible0053Txt")}</button><button data-testid="qa-admin-delete" className="btn danger-text" disabled={network.membership_role!=="owner"||deleteConfirm!==network.name||busy} onClick={async()=>{if(!confirm(`Permanently delete ${network.name}? This cannot be undone.`))return;setBusy(true);try{await deleteOwnedNetworkPermanently(network.network_id||network.id,deleteConfirm);onNotify("Network permanently deleted after residue verification.");window.location.reload()}catch(e:any){onNotify(e.message||"Could not delete network.")}finally{setBusy(false)}}}>{xp2t("XP2Visible0020Txt")}</button></div></div>}
  {tab==="export"&&<NetworkBackupExport networkId={network.network_id||network.id} networkName={network.name} onNotify={onNotify}/>}
  {tab==="export"&&<div className="card admin-center-panel"><h2>{tr("ContinuityRecoveryAndBackupTxt")}</h2><p className="page-subtitle">{tr("KeepAPortableCopyBeforeLargeImportsTxt")}</p>{(summary?.admin_count||1)<2&&<div className="admin-storage-warning"><b>{tr("AddASecondFamilyAdminTxt")}</b><span>{tr("ThisProtectsContinuityIfTheOwnerIsTxt")}</span></div>}<div className="card-actions"><button data-testid="qa-export-csv" className="btn primary" onClick={onExportCsv}><Download size={15}/> {tr("ExportCSVTxt")}</button><button data-testid="qa-export-json" className="btn" onClick={onExportJson}><Download size={15}/> {tr("ExportJSONTxt")}</button><button className="btn" onClick={onPrint}><Download size={15}/> {tr("PrintPDFTxt")}</button></div></div>}
 </div>
}
