"use client";
import {useEffect,useMemo,useState} from "react";
import {CheckCircle2,ClipboardList,FileText,Gavel,Plus,UsersRound,Vote} from "lucide-react";
import type {NetworkAffiliatedEntity} from "../core/network-os/contracts";
import {addHsAgendaItem,assignHsCommitteeRole,castHsResolutionVote,closeHsResolution,createHsCommitteeTerm,createHsGovernanceAction,createHsGovernanceMeeting,createHsResolution,fetchHsGovernanceSnapshot,publishHsMinutes,updateHsGovernanceAction,type HsGovernanceSnapshot} from "../verticals/housing-society/runtime/governance-remote";
import HousingSectionTabs from "./shared/HousingSectionTabs";
import {NetworkEmpty,NetworkMetric,NetworkSectionHead} from "./shared/NetworkUi";
import {useLanguage} from "../lib/i18n";
const EMPTY:HsGovernanceSnapshot={terms:[],meetings:[],actions:[],resolutions:[],documents:[]};
const today=()=>new Date().toISOString().slice(0,10),nextWeek=()=>new Date(Date.now()+7*86400000).toISOString().slice(0,16);
export default function HousingSocietyGovernancePanel({isAdmin,demo=false,entities,onNotify}:{isAdmin:boolean;demo?:boolean;entities:NetworkAffiliatedEntity[];onNotify:(s:string)=>void}){
 const {t:xp2t}=useLanguage();
 const people=useMemo(()=>entities.filter(e=>e.entity.kind==="person"),[entities]);const [data,setData]=useState(EMPTY),[busy,setBusy]=useState(false);
 const [governanceView,setGovernanceView]=useState<"committee"|"actions"|"resolutions">("committee");
 const [termLabel,setTermLabel]=useState("Committee 2026-27"),[termStart,setTermStart]=useState(today()),[termEnd,setTermEnd]=useState("");
 const [termId,setTermId]=useState(""),[personId,setPersonId]=useState(""),[role,setRole]=useState("committee_member");
 const [meetingType,setMeetingType]=useState("committee"),[meetingTitle,setMeetingTitle]=useState("Monthly Committee Meeting"),[meetingAt,setMeetingAt]=useState(nextWeek()),[location,setLocation]=useState("Society Office");
 const [meetingId,setMeetingId]=useState(""),[agendaTitle,setAgendaTitle]=useState(""),[minutes,setMinutes]=useState(""),[attendees,setAttendees]=useState("");
 const [actionTitle,setActionTitle]=useState(""),[actionOwner,setActionOwner]=useState(""),[actionDue,setActionDue]=useState("");
 const [resolutionNo,setResolutionNo]=useState("RES-001"),[resolutionTitle,setResolutionTitle]=useState(""),[resolutionBody,setResolutionBody]=useState(""),[voteMode,setVoteMode]=useState<"approval"|"advisory">("approval");
 const load=async()=>{if(demo){setData({terms:[{id:"t1",label:"Committee 2026-27",startsOn:"2026-04-01",status:"active",assignments:[{id:"a1",personEntityId:"p1",personLabel:"Sanjay Mehta",roleKey:"chairperson",startsOn:"2026-04-01"},{id:"a2",personEntityId:"p2",personLabel:"Anita Shah",roleKey:"secretary",startsOn:"2026-04-01"},{id:"a3",personEntityId:"p3",personLabel:"Vivek Kulkarni",roleKey:"treasurer",startsOn:"2026-04-01"},{id:"a4",personEntityId:"p4",personLabel:"Neeraj Patil",roleKey:"committee_member",startsOn:"2026-04-01"}]}],meetings:[{id:"m1",meetingType:"committee",title:"September Managing Committee Meeting",scheduledAt:"2026-09-06T19:30:00+05:30",location:"Clubhouse",status:"completed",agenda:[{id:"ag1",itemOrder:1,title:"Lift AMC renewal"},{id:"ag2",itemOrder:2,title:"Navratri event budget"}]}],actions:[{id:"ac1",meetingId:"m0",title:"Collect lift AMC quotations",ownerLabel:"Secretary",dueOn:"2026-09-15",status:"in_progress"},{id:"ac2",meetingId:"m0",title:"Complete Cedar CCTV replacement comparison",ownerLabel:"Security Portfolio",dueOn:"2026-09-18",status:"open"},{id:"ac3",meetingId:"m0",title:"Publish AGM annual report",ownerLabel:"Treasurer",dueOn:"2026-09-20",status:"open"}],resolutions:[{id:"r1",resolutionNumber:"RES-014",title:"Approve EV charging pilot",body:"Approve the first controlled EV charging pilot in designated parking bays.",voteMode:"approval",status:"passed",quorumPercent:0,yesCount:5,noCount:1,abstainCount:0,myVote:null},{id:"r2",resolutionNumber:"RES-015",title:"Replace Cedar tower CCTV recorder",body:"Replace the failing Cedar NVR within the approved security budget.",voteMode:"approval",status:"passed",quorumPercent:0,yesCount:6,noCount:0,abstainCount:0,myVote:null},{id:"r3",resolutionNumber:"RES-016",title:"Revise clubhouse booking deposit",body:"Review the refundable deposit to reduce no-shows while keeping resident bookings accessible.",voteMode:"approval",status:"open",quorumPercent:0,yesCount:0,noCount:0,abstainCount:0,myVote:null}],documents:[]});return}try{setData(await fetchHsGovernanceSnapshot())}catch(e:any){onNotify(e.message||"Could not load society governance.")}};
 useEffect(()=>{load()},[]);const run=async(fn:()=>Promise<any>,ok:string)=>{setBusy(true);try{await fn();onNotify(ok);await load()}catch(e:any){onNotify(e.message||"Could not save governance change.")}finally{setBusy(false)}};
 const openActions=data.actions.filter(a=>a.status!=="done"&&a.status!=="cancelled");
 return <div data-testid="qa-hs-governance" className="hs4-governance"><NetworkSectionHead kicker={<><Gavel size={12}/>  {xp2t("XP2Visible0232Txt")}</>} title={xp2t("XP2Visible0233Txt")} description={xp2t("XP2Visible0234Txt")}/>
 <section className="network-metric-grid"><NetworkMetric value={data.terms[0]?.assignments.length||0} label={xp2t("XP2Visible0235Txt")}/><NetworkMetric value={data.meetings.length} label={xp2t("XP2Visible0236Txt")}/><NetworkMetric value={openActions.length} label={xp2t("XP2Visible0237Txt")}/><NetworkMetric value={data.resolutions.filter(r=>r.status==="open").length} label={xp2t("XP2Visible0238Txt")}/></section>
 {isAdmin&&<HousingSectionTabs label={xp2t("XP2Visible0233Txt")} value={governanceView} onChange={v=>setGovernanceView(v as "committee"|"actions"|"resolutions")} options={[{id:"committee",label:`${xp2t("XP2Visible0239Txt")} & ${xp2t("XP2Visible0236Txt")}`},{id:"actions",label:xp2t("XP2Visible0286Txt")},{id:"resolutions",label:xp2t("XP2Visible0288Txt")}]} />}
 {!isAdmin&&<><section className="card"><NetworkSectionHead kicker={<><UsersRound size={12}/>  {xp2t("XP2Visible0239Txt")}</>} title={xp2t("XP2Visible0240Txt")} description={xp2t("XP2Visible0241Txt")}/>{data.terms.length?<div className="hs2-list">{data.terms[0].assignments.map(a=><div key={a.id}><UsersRound/><span><b>{a.personLabel}</b><small>{a.roleLabel||a.roleKey.replaceAll("_"," ")}  {xp2t("XP2Visible0242Txt")} {a.startsOn}</small></span></div>)}</div>:<NetworkEmpty icon={<UsersRound/>} title={xp2t("XP2Visible0243Txt")} description={xp2t("XP2Visible0244Txt")}/>}</section>
 <section className="card"><h3>{xp2t("XP2Visible0245Txt")}</h3><div className="hs2-list">{data.meetings.map(m=><div key={m.id}><ClipboardList/><span><b>{m.title}</b><small>{new Date(m.scheduledAt).toLocaleString()} · {m.location||"Location TBD"} · {m.status}</small>{m.minutesText&&<p>{m.minutesText}</p>}</span></div>)}</div></section>
 <section className="card"><h3>{xp2t("XP2Visible0246Txt")}</h3>{data.resolutions.length?<div className="hs2-list">{data.resolutions.map(r=><div key={r.id}><Vote/><span><b>{r.resolutionNumber?`${r.resolutionNumber} · `:""}{r.title}</b><small>{r.voteMode} · {r.status}  {xp2t("XP2Visible0247Txt")} {r.yesCount}  {xp2t("XP2Visible0248Txt")} {r.noCount}  {xp2t("XP2Visible0249Txt")} {r.abstainCount}</small><p>{r.body}</p>{r.status==="open"&&<div className="card-actions"><button className="btn small" disabled={busy||demo} onClick={()=>run(()=>castHsResolutionVote(r.id,"yes"),"Vote recorded.")}>{xp2t("XP2Visible0250Txt")}</button><button className="btn small" disabled={busy||demo} onClick={()=>run(()=>castHsResolutionVote(r.id,"no"),"Vote recorded.")}>{xp2t("XP2Visible0251Txt")}</button><button className="btn small" disabled={busy||demo} onClick={()=>run(()=>castHsResolutionVote(r.id,"abstain"),"Vote recorded.")}>{xp2t("XP2Visible0252Txt")}</button>{r.myVote&&<small>{xp2t("XP2Visible0253Txt")} {r.myVote}</small>}</div>}</span></div>)}</div>:<p className="muted">{xp2t("XP2Visible0254Txt")}</p>}</section></>}
 {isAdmin&&governanceView==="committee"&&<><div className="hs2-admin-grid"><section className="card"><h3>{xp2t("XP2Visible0255Txt")}</h3><div className="stack-form"><input className="text-input" value={termLabel} onChange={e=>setTermLabel(e.target.value)}/><input className="text-input" type="date" value={termStart} onChange={e=>setTermStart(e.target.value)}/><input className="text-input" type="date" value={termEnd} onChange={e=>setTermEnd(e.target.value)}/><button className="btn primary" disabled={busy||!termLabel||!termStart} onClick={()=>run(()=>createHsCommitteeTerm({label:termLabel,startsOn:termStart,endsOn:termEnd||null}),"Committee term saved.")}><Plus size={14}/>  {xp2t("XP2Visible0256Txt")}</button><select className="select" value={termId} onChange={e=>setTermId(e.target.value)}><option value="">{xp2t("XP2Visible0257Txt")}</option>{data.terms.map(t=><option value={t.id} key={t.id}>{t.label}</option>)}</select><select className="select" value={personId} onChange={e=>setPersonId(e.target.value)}><option value="">{xp2t("XP2Visible0133Txt")}</option>{people.map(p=><option value={p.entity.id} key={p.entity.id}>{p.entity.label}</option>)}</select><select className="select" value={role} onChange={e=>setRole(e.target.value)}><option value="chairperson">{xp2t("XP2Visible0258Txt")}</option><option value="secretary">{xp2t("XP2Visible0259Txt")}</option><option value="treasurer">{xp2t("XP2Visible0260Txt")}</option><option value="committee_member">{xp2t("XP2Visible0261Txt")}</option><option value="manager">{xp2t("XP2Visible0262Txt")}</option><option value="auditor">{xp2t("XP2Visible0263Txt")}</option><option value="other">{xp2t("XP2Visible0189Txt")}</option></select><button className="btn" disabled={busy||!termId||!personId} onClick={()=>run(()=>assignHsCommitteeRole({termId,personEntityId:personId,roleKey:role,startsOn:termStart}),"Committee role assigned with history.")}>{xp2t("XP2Visible0103Txt")}</button></div></section>
 <section className="card"><h3>{xp2t("XP2Visible0264Txt")}</h3><div className="stack-form"><select className="select" value={meetingType} onChange={e=>setMeetingType(e.target.value)}><option value="committee">{xp2t("XP2Visible0239Txt")}</option><option value="agm">{xp2t("XP2Visible0265Txt")}</option><option value="sgm">{xp2t("XP2Visible0266Txt")}</option><option value="general">{xp2t("XP2Visible0267Txt")}</option><option value="other">{xp2t("XP2Visible0189Txt")}</option></select><input data-testid="qa-hs-meeting-title" className="text-input" value={meetingTitle} onChange={e=>setMeetingTitle(e.target.value)}/><input className="text-input" type="datetime-local" value={meetingAt} onChange={e=>setMeetingAt(e.target.value)}/><input className="text-input" value={location} onChange={e=>setLocation(e.target.value)}/><button data-testid="qa-hs-meeting-create" className="btn primary" disabled={busy||!meetingTitle||!meetingAt} onClick={()=>run(()=>createHsGovernanceMeeting({meetingType,title:meetingTitle,scheduledAt:meetingAt,location}),"Meeting scheduled.")}><Plus size={14}/>  {xp2t("XP2Visible0268Txt")}</button></div></section></div></>}
 {isAdmin&&governanceView==="actions"&&<><div className="hs2-admin-grid"><section className="card"><h3>{xp2t("XP2Visible0269Txt")}</h3><div className="stack-form"><select className="select" value={meetingId} onChange={e=>setMeetingId(e.target.value)}><option value="">{xp2t("XP2Visible0270Txt")}</option>{data.meetings.map(m=><option value={m.id} key={m.id}>{m.title}</option>)}</select><input className="text-input" value={agendaTitle} onChange={e=>setAgendaTitle(e.target.value)} placeholder={xp2t("XP2Visible0271Txt")}/><button className="btn" disabled={busy||!meetingId||!agendaTitle} onClick={()=>run(()=>addHsAgendaItem(meetingId,agendaTitle),"Agenda item added.")}>{xp2t("XP2Visible0272Txt")}</button><textarea className="text-input" rows={4} value={minutes} onChange={e=>setMinutes(e.target.value)} placeholder={xp2t("XP2Visible0273Txt")}/><input className="text-input" type="number" min="0" value={attendees} onChange={e=>setAttendees(e.target.value)} placeholder={xp2t("XP2Visible0274Txt")}/><button className="btn" disabled={busy||!meetingId||minutes.trim().length<3} onClick={()=>run(()=>publishHsMinutes(meetingId,minutes,attendees?Number(attendees):null),"Meeting minutes published.")}><FileText size={14}/>  {xp2t("XP2Visible0275Txt")}</button><input className="text-input" value={actionTitle} onChange={e=>setActionTitle(e.target.value)} placeholder={xp2t("XP2Visible0276Txt")}/><input className="text-input" value={actionOwner} onChange={e=>setActionOwner(e.target.value)} placeholder={xp2t("XP2Visible0277Txt")}/><input className="text-input" type="date" value={actionDue} onChange={e=>setActionDue(e.target.value)}/><button className="btn" disabled={busy||!actionTitle} onClick={()=>run(()=>createHsGovernanceAction({meetingId:meetingId||null,title:actionTitle,ownerLabel:actionOwner,dueOn:actionDue||null}),"Action item created.")}>{xp2t("XP2Visible0278Txt")}</button></div></section></div></>}
 {isAdmin&&governanceView==="resolutions"&&<div className="hs2-admin-grid"><section className="card"><h3>{xp2t("XP2Visible0279Txt")}</h3><div className="stack-form"><input className="text-input" value={resolutionNo} onChange={e=>setResolutionNo(e.target.value)} placeholder={xp2t("XP2Visible0280Txt")}/><input data-testid="qa-hs-resolution-title" className="text-input" value={resolutionTitle} onChange={e=>setResolutionTitle(e.target.value)} placeholder={xp2t("XP2Visible0281Txt")}/><textarea data-testid="qa-hs-resolution-body" className="text-input" rows={4} value={resolutionBody} onChange={e=>setResolutionBody(e.target.value)} placeholder={xp2t("XP2Visible0282Txt")}/><select className="select" value={voteMode} onChange={e=>setVoteMode(e.target.value as any)}><option value="approval">{xp2t("XP2Visible0283Txt")}</option><option value="advisory">{xp2t("XP2Visible0284Txt")}</option></select><button data-testid="qa-hs-resolution-create" className="btn primary" disabled={busy||resolutionTitle.trim().length<3||resolutionBody.trim().length<3} onClick={()=>run(()=>createHsResolution({meetingId:meetingId||null,resolutionNumber:resolutionNo,title:resolutionTitle,body:resolutionBody,voteMode}),"Resolution opened for controlled member voting.")}><Vote size={14}/>  {xp2t("XP2Visible0285Txt")}</button></div></section></div>}
 {isAdmin&&governanceView==="actions"&&<><section className="card"><h3>{xp2t("XP2Visible0286Txt")}</h3><div className="hs2-list">{data.actions.map(a=><div key={a.id}><CheckCircle2/><span><b>{a.title}</b><small>{a.ownerLabel||"Unassigned"}{a.dueOn?` · due ${a.dueOn}`:""} · {a.status}</small></span>{a.status!=="done"&&<button className="btn small" disabled={busy} onClick={()=>run(()=>updateHsGovernanceAction(a.id,"done","Completed by committee"),"Action item closed.")}>{xp2t("XP2Visible0287Txt")}</button>}</div>)}</div></section></>}
 {isAdmin&&governanceView==="resolutions"&&<><section className="card"><h3>{xp2t("XP2Visible0288Txt")}</h3><div className="hs2-list">{data.resolutions.map(r=><div key={r.id}><Gavel/><span><b>{r.resolutionNumber||"Decision"} · {r.title}</b><small>{r.status}  {xp2t("XP2Visible0247Txt")} {r.yesCount}  {xp2t("XP2Visible0248Txt")} {r.noCount}  {xp2t("XP2Visible0249Txt")} {r.abstainCount}</small></span>{r.status==="open"&&<div className="card-actions"><button className="btn small" onClick={()=>run(()=>closeHsResolution(r.id,"approved","Closed by committee after reviewing recorded votes/quorum."),"Resolution approved and closed.")}>{xp2t("XP2Visible0289Txt")}</button><button className="btn small" onClick={()=>run(()=>closeHsResolution(r.id,"rejected","Closed by committee after reviewing recorded votes/quorum."),"Resolution rejected and closed.")}>{xp2t("XP2Visible0290Txt")}</button></div>}</div>)}</div></section></>}
 </div>
}
