"use client";
import {useEffect,useMemo,useState} from "react";
import {BadgeIndianRupee,CalendarDays,CheckCircle2,Landmark,Plus,ReceiptIndianRupee,WalletCards} from "lucide-react";
import {addHsBillAdjustment,createHsBillingCycle,fetchHsFinanceSnapshot,generateHsCycleBills,recordHsExpense,recordHsPayment,upsertHsBudgetLine,upsertHsChargeHead,upsertHsFund,type HsFinanceSnapshot} from "../verticals/housing-society/runtime/finance-remote";
import HousingSectionTabs from "./shared/HousingSectionTabs";
import {NetworkEmpty,NetworkMetric,NetworkSectionHead} from "./shared/NetworkUi";
import {useLanguage} from "../lib/i18n";

const EMPTY:HsFinanceSnapshot={chargeHeads:[],cycles:[],bills:[],funds:[],budget:[],summary:{totalBilled:0,totalCollected:0,totalOutstanding:0,overdueBills:0}};
const money=(n?:number)=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-01`};
const monthEnd=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth()+1,0).toISOString().slice(0,10)};
export default function HousingSocietyFinancePanel({isAdmin,demo=false,onNotify}:{isAdmin:boolean;demo?:boolean;onNotify:(s:string)=>void}){
 const {t:xp2t}=useLanguage();
 const [data,setData]=useState<HsFinanceSnapshot>(EMPTY),[busy,setBusy]=useState(false);
 const [financeView,setFinanceView]=useState<"billing"|"funds"|"arrears">("billing");
 const [code,setCode]=useState("MAINT"),[headLabel,setHeadLabel]=useState("Monthly Maintenance"),[category,setCategory]=useState("maintenance"),[amount,setAmount]=useState("2500");
 const [cycleLabel,setCycleLabel]=useState("Monthly Maintenance"),[periodStart,setPeriodStart]=useState(monthStart()),[periodEnd,setPeriodEnd]=useState(monthEnd()),[dueOn,setDueOn]=useState(monthEnd()),[graceDays,setGraceDays]=useState("5"),[penaltyRate,setPenaltyRate]=useState("0");
 const [selectedBill,setSelectedBill]=useState(""),[paymentAmount,setPaymentAmount]=useState(""),[paymentRef,setPaymentRef]=useState(""),[receiptNo,setReceiptNo]=useState("");
 const [adjustType,setAdjustType]=useState<"credit"|"debit"|"waiver"|"penalty">("credit"),[adjustAmount,setAdjustAmount]=useState(""),[adjustReason,setAdjustReason]=useState("");
 const [fundCode,setFundCode]=useState("SINKING"),[fundLabel,setFundLabel]=useState("Sinking Fund"),[fundOpening,setFundOpening]=useState("0");
 const [fy,setFy]=useState(`${new Date().getFullYear()}-${String((new Date().getFullYear()+1)%100).padStart(2,"0")}`),[budgetCategory,setBudgetCategory]=useState("Repairs"),[budgetLabel,setBudgetLabel]=useState("Annual repairs"),[budgetAmount,setBudgetAmount]=useState("");
 const [expenseDesc,setExpenseDesc]=useState(""),[expenseAmount,setExpenseAmount]=useState("");
 const load=async()=>{if(demo){setData({...EMPTY,cycles:[{id:"demo-cycle",label:"September 2026",periodStart:"2026-09-01",periodEnd:"2026-09-30",dueOn:"2026-09-15",status:"issued",graceDays:5,penaltyRateMonthly:1.5}],bills:[{id:"demo-bill",cycleId:"demo-cycle",cycleLabel:"September 2026",unitEntityId:"u1",unitLabel:"Aster-A-804",dueOn:"2026-09-15",subtotal:5300,adjustmentAmount:0,totalAmount:5300,paidAmount:5300,balanceAmount:0,status:"paid",lineItems:[{id:"l1",label:"Monthly Maintenance",amount:4200},{id:"l2",label:"Sinking Fund",amount:750},{id:"l3",label:"Water Charge",amount:350}],payments:[{id:"p1",amount:5300,paidOn:"2026-09-05",paymentMode:"upi",paymentReference:"UTR-DEMO",receiptNumber:"EH-0901",status:"recorded"}]}],funds:[{id:"f1",code:"OPERATING",label:"Operating Fund",openingBalance:480000,currentBalance:612000,visibility:"members"},{id:"f2",code:"SINKING",label:"Sinking Fund",openingBalance:1850000,currentBalance:2025000,visibility:"members"},{id:"f3",code:"REPAIR",label:"Major Repair Fund",openingBalance:925000,currentBalance:1010000,visibility:"members"}],summary:{totalBilled:381600,totalCollected:344500,totalOutstanding:37100,overdueBills:7}});return}try{setData(await fetchHsFinanceSnapshot())}catch(e:any){onNotify(e.message||"Could not load society finance.")}};
 useEffect(()=>{load()},[]);
 const run=async(fn:()=>Promise<any>,ok:string)=>{setBusy(true);try{await fn();onNotify(ok);await load()}catch(e:any){onNotify(e.message||"Could not save finance change.")}finally{setBusy(false)}};
 const overdue=useMemo(()=>data.bills.filter(b=>b.balanceAmount>0&&new Date(b.dueOn)<new Date()),[data.bills]);
 const selected=data.bills.find(b=>b.id===selectedBill);
 return <div data-testid="qa-hs-finance" className="hs3-finance"><NetworkSectionHead kicker={<><BadgeIndianRupee size={12}/>  {xp2t("XP2Visible0160Txt")}</>} title={xp2t("XP2Visible0161Txt")} description={xp2t("XP2Visible0162Txt")}/>
 <section className="network-metric-grid"><NetworkMetric value={money(data.summary.totalBilled)} label={xp2t("XP2Visible0163Txt")}/><NetworkMetric value={money(data.summary.totalCollected)} label={xp2t("XP2Visible0164Txt")}/><NetworkMetric value={money(data.summary.totalOutstanding)} label={xp2t("XP2Visible0165Txt")}/><NetworkMetric value={data.summary.overdueBills} label={xp2t("XP2Visible0166Txt")}/></section>
 {isAdmin&&<HousingSectionTabs label={xp2t("XP2Visible0161Txt")} value={financeView} onChange={v=>setFinanceView(v as "billing"|"funds"|"arrears")} options={[{id:"billing",label:xp2t("XP2Visible0191Txt")},{id:"funds",label:xp2t("XP2Visible0217Txt")},{id:"arrears",label:xp2t("XP2Visible0230Txt")}]} />}
 {!isAdmin&&<><section className="card"><NetworkSectionHead kicker={<><ReceiptIndianRupee size={12}/>  {xp2t("XP2Visible0167Txt")}</>} title={xp2t("XP2Visible0168Txt")} description={xp2t("XP2Visible0169Txt")}/>{data.bills.length?<div className="table-wrap"><table><thead><tr><th>{xp2t("XP2Visible0126Txt")}</th><th>{xp2t("XP2Visible0154Txt")}</th><th>{xp2t("XP2Visible0170Txt")}</th><th>{xp2t("XP2Visible0171Txt")}</th><th>{xp2t("XP2Visible0172Txt")}</th><th>{xp2t("XP2Visible0173Txt")}</th><th>{xp2t("XP2Visible0091Txt")}</th></tr></thead><tbody>{data.bills.map(b=><tr key={b.id}><td>{b.cycleLabel}</td><td>{b.unitLabel}</td><td>{b.dueOn}</td><td>{money(b.totalAmount)}</td><td>{money(b.paidAmount)}</td><td>{money(b.balanceAmount)}</td><td>{b.status}</td></tr>)}</tbody></table></div>:<NetworkEmpty icon={<ReceiptIndianRupee/>} title={xp2t("XP2Visible0174Txt")} description={xp2t("XP2Visible0175Txt")}/>}</section><section className="card"><h3>{xp2t("XP2Visible0176Txt")}</h3>{data.bills.flatMap(b=>b.payments.map(p=>({...p,unitLabel:b.unitLabel,cycleLabel:b.cycleLabel}))).length?<div className="hs2-list">{data.bills.flatMap(b=>b.payments.map(p=><div key={p.id}><CheckCircle2/><span><b>{money(p.amount)} · {b.unitLabel}</b><small>{p.paidOn} · {p.receiptNumber||p.paymentReference||p.paymentMode}</small></span></div>))}</div>:<p className="muted">{xp2t("XP2Visible0177Txt")}</p>}</section></>}
 {isAdmin&&financeView==="billing"&&<><div className="hs2-admin-grid"><section className="card"><h3>{xp2t("XP2Visible0178Txt")}</h3><div className="stack-form"><input data-testid="qa-hs-charge-code" className="text-input" placeholder={xp2t("XP2Visible0179Txt")} value={code} onChange={e=>setCode(e.target.value)}/><input data-testid="qa-hs-charge-label" className="text-input" placeholder={xp2t("XP2Visible0180Txt")} value={headLabel} onChange={e=>setHeadLabel(e.target.value)}/><select className="select" value={category} onChange={e=>setCategory(e.target.value)}><option value="maintenance">{xp2t("XP2Visible0181Txt")}</option><option value="sinking_fund">{xp2t("XP2Visible0182Txt")}</option><option value="repair_fund">{xp2t("XP2Visible0183Txt")}</option><option value="parking">{xp2t("XP2Visible0184Txt")}</option><option value="water">{xp2t("XP2Visible0185Txt")}</option><option value="common_electricity">{xp2t("XP2Visible0186Txt")}</option><option value="non_occupancy">{xp2t("XP2Visible0187Txt")}</option><option value="special_assessment">{xp2t("XP2Visible0188Txt")}</option><option value="other">{xp2t("XP2Visible0189Txt")}</option></select><input data-testid="qa-hs-charge-amount" className="text-input" type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)}/><button data-testid="qa-hs-charge-save" className="btn primary" disabled={busy||!code||!headLabel||Number(amount)<0} onClick={()=>run(()=>upsertHsChargeHead({code,label:headLabel,category,amount:Number(amount)}),"Charge head saved.")}><Plus size={14}/>  {xp2t("XP2Visible0190Txt")}</button></div><div className="hs2-list">{data.chargeHeads.map(h=><div key={h.id}><WalletCards/><span><b>{h.label}</b><small>{h.code} · {money(h.amount)} · {h.category}</small></span></div>)}</div></section>
 <section className="card"><h3>{xp2t("XP2Visible0191Txt")}</h3><div className="stack-form"><input className="text-input" value={cycleLabel} onChange={e=>setCycleLabel(e.target.value)} placeholder={xp2t("XP2Visible0192Txt")}/><label className="field"><span>{xp2t("XP2Visible0193Txt")}</span><input className="text-input" type="date" value={periodStart} onChange={e=>setPeriodStart(e.target.value)}/></label><label className="field"><span>{xp2t("XP2Visible0194Txt")}</span><input className="text-input" type="date" value={periodEnd} onChange={e=>setPeriodEnd(e.target.value)}/></label><label className="field"><span>{xp2t("XP2Visible0195Txt")}</span><input className="text-input" type="date" value={dueOn} onChange={e=>setDueOn(e.target.value)}/></label><input className="text-input" type="number" min="0" placeholder={xp2t("XP2Visible0196Txt")} value={graceDays} onChange={e=>setGraceDays(e.target.value)}/><input className="text-input" type="number" min="0" step="0.01" placeholder={xp2t("XP2Visible0197Txt")} value={penaltyRate} onChange={e=>setPenaltyRate(e.target.value)}/><button className="btn" disabled={busy||!cycleLabel||!periodStart||!periodEnd||!dueOn} onClick={()=>run(()=>createHsBillingCycle({label:cycleLabel,periodStart,periodEnd,dueOn,graceDays:Number(graceDays||0),penaltyRateMonthly:Number(penaltyRate||0)}),"Billing cycle saved.")}><CalendarDays size={14}/>  {xp2t("XP2Visible0198Txt")}</button></div><div className="hs2-list">{data.cycles.map(c=><div key={c.id}><CalendarDays/><span><b>{c.label}</b><small>{c.periodStart} → {c.periodEnd}  {xp2t("XP2Visible0199Txt")} {c.dueOn} · {c.status}</small></span>{c.status==="draft"&&<button className="btn small" disabled={busy} onClick={()=>run(async()=>{const r=await generateHsCycleBills(c.id);onNotify(`Issued ${r.unitCount} flat bills with ${r.chargeHeadCount} charge heads.`)},"Bills generated.")}>{xp2t("XP2Visible0200Txt")}</button>}</div>)}</div></section></div>
 <section className="card"><NetworkSectionHead title={xp2t("XP2Visible0201Txt")} description={xp2t("XP2Visible0202Txt")}/><div className="table-wrap"><table><thead><tr><th>{xp2t("XP2Visible0126Txt")}</th><th>{xp2t("XP2Visible0154Txt")}</th><th>{xp2t("XP2Visible0171Txt")}</th><th>{xp2t("XP2Visible0172Txt")}</th><th>{xp2t("XP2Visible0173Txt")}</th><th>{xp2t("XP2Visible0170Txt")}</th><th>{xp2t("XP2Visible0091Txt")}</th></tr></thead><tbody>{data.bills.map(b=><tr key={b.id} onClick={()=>setSelectedBill(b.id)} style={{cursor:"pointer"}}><td>{b.cycleLabel}</td><td>{b.unitLabel}</td><td>{money(b.totalAmount)}</td><td>{money(b.paidAmount)}</td><td>{money(b.balanceAmount)}</td><td>{b.dueOn}</td><td>{b.status}</td></tr>)}</tbody></table></div>{!data.bills.length&&<p className="muted">{xp2t("XP2Visible0203Txt")}</p>}</section>
 {selected&&<div className="hs2-admin-grid"><section className="card"><h3>{xp2t("XP2Visible0204Txt")} {selected.unitLabel}</h3><p>{selected.cycleLabel}  {xp2t("XP2Visible0205Txt")} {money(selected.balanceAmount)}</p><div className="stack-form"><input className="text-input" type="number" min="0.01" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)} placeholder={xp2t("XP2Visible0206Txt")}/><input className="text-input" value={paymentRef} onChange={e=>setPaymentRef(e.target.value)} placeholder={xp2t("XP2Visible0207Txt")}/><input className="text-input" value={receiptNo} onChange={e=>setReceiptNo(e.target.value)} placeholder={xp2t("XP2Visible0208Txt")}/><button className="btn primary" disabled={busy||Number(paymentAmount)<=0} onClick={()=>run(()=>recordHsPayment({billId:selected.id,amount:Number(paymentAmount),paidOn:today(),paymentMode:"manual",paymentReference:paymentRef,receiptNumber:receiptNo}),"Payment and receipt recorded.")}><ReceiptIndianRupee size={14}/>  {xp2t("XP2Visible0209Txt")}</button></div></section><section className="card"><h3>{xp2t("XP2Visible0210Txt")}</h3><div className="stack-form"><select className="select" value={adjustType} onChange={e=>setAdjustType(e.target.value as any)}><option value="credit">{xp2t("XP2Visible0211Txt")}</option><option value="debit">{xp2t("XP2Visible0212Txt")}</option><option value="waiver">{xp2t("XP2Visible0213Txt")}</option><option value="penalty">{xp2t("XP2Visible0214Txt")}</option></select><input className="text-input" type="number" min="0" value={adjustAmount} onChange={e=>setAdjustAmount(e.target.value)} placeholder={xp2t("XP2Visible0107Txt")}/><input className="text-input" value={adjustReason} onChange={e=>setAdjustReason(e.target.value)} placeholder={xp2t("XP2Visible0215Txt")}/><button className="btn" disabled={busy||Number(adjustAmount)<0||adjustReason.trim().length<2} onClick={()=>run(()=>addHsBillAdjustment({billId:selected.id,type:adjustType,amount:Number(adjustAmount),reason:adjustReason}),"Bill adjustment recorded with history.")}>{xp2t("XP2Visible0216Txt")}</button></div></section></div>}</>}
 {isAdmin&&financeView==="funds"&&<><div className="hs2-admin-grid"><section className="card"><h3>{xp2t("XP2Visible0217Txt")}</h3><div className="stack-form"><input className="text-input" value={fundCode} onChange={e=>setFundCode(e.target.value)} placeholder={xp2t("XP2Visible0218Txt")}/><input className="text-input" value={fundLabel} onChange={e=>setFundLabel(e.target.value)} placeholder={xp2t("XP2Visible0219Txt")}/><input className="text-input" type="number" value={fundOpening} onChange={e=>setFundOpening(e.target.value)} placeholder={xp2t("XP2Visible0220Txt")}/><button className="btn" disabled={busy||!fundCode||!fundLabel} onClick={()=>run(()=>upsertHsFund({code:fundCode,label:fundLabel,openingBalance:Number(fundOpening||0)}),"Fund saved.")}><Landmark size={14}/>  {xp2t("XP2Visible0221Txt")}</button></div>{data.funds.map(f=><p key={f.id}><b>{f.label}</b> · {money(f.currentBalance)}</p>)}</section>
 <section className="card"><h3>{xp2t("XP2Visible0222Txt")}</h3><div className="stack-form"><input className="text-input" value={fy} onChange={e=>setFy(e.target.value)} placeholder="2026-27"/><input className="text-input" value={budgetCategory} onChange={e=>setBudgetCategory(e.target.value)} placeholder={xp2t("XP2Visible0223Txt")}/><input className="text-input" value={budgetLabel} onChange={e=>setBudgetLabel(e.target.value)} placeholder={xp2t("XP2Visible0224Txt")}/><input className="text-input" type="number" value={budgetAmount} onChange={e=>setBudgetAmount(e.target.value)} placeholder={xp2t("XP2Visible0225Txt")}/><button className="btn" disabled={busy||!fy||!budgetCategory||!budgetLabel||Number(budgetAmount)<0} onClick={()=>run(()=>upsertHsBudgetLine({financialYear:fy,category:budgetCategory,label:budgetLabel,budgetAmount:Number(budgetAmount||0)}),"Budget line saved.")}>{xp2t("XP2Visible0226Txt")}</button><input className="text-input" value={expenseDesc} onChange={e=>setExpenseDesc(e.target.value)} placeholder={xp2t("XP2Visible0227Txt")}/><input className="text-input" type="number" value={expenseAmount} onChange={e=>setExpenseAmount(e.target.value)} placeholder={xp2t("XP2Visible0228Txt")}/><button className="btn" disabled={busy||expenseDesc.trim().length<2||Number(expenseAmount)<=0} onClick={()=>run(()=>recordHsExpense({category:budgetCategory,description:expenseDesc,amount:Number(expenseAmount),incurredOn:today()}),"Expense recorded.")}>{xp2t("XP2Visible0229Txt")}</button></div>{data.budget.map(b=><div key={b.id} className="hs2-row"><span><b>{b.label}</b><small>{b.financialYear} · {b.category}</small></span><span>{money(b.actualAmount)} / {money(b.budgetAmount)}</span></div>)}</section></div></>}
 {isAdmin&&financeView==="arrears"&&<><section className="card"><h3>{xp2t("XP2Visible0230Txt")}</h3>{overdue.length?<div className="hs2-list">{overdue.map(b=><div key={b.id}><ReceiptIndianRupee/><span><b>{b.unitLabel} · {money(b.balanceAmount)}</b><small>{b.cycleLabel}  {xp2t("XP2Visible0199Txt")} {b.dueOn}</small></span></div>)}</div>:<p className="muted">{xp2t("XP2Visible0231Txt")}</p>}</section></>}
 </div>
}
