"use client";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,Building2,CalendarClock,DoorOpen,HardHat,PhoneCall,Plus,ShieldCheck,UsersRound,Wrench} from "lucide-react";
import type {NetworkAffiliatedEntity} from "../core/network-os/contracts";
import {addHsAssetService,authorizeHsStaffUnit,createHsMoveRequest,createHsRenovationRequest,createHsVisitor,fetchHsSecuritySnapshot,reviewHsOperationalRequest,updateHsVisitorStatus,upsertHsAsset,upsertHsCompliance,upsertHsEmergencyContact,upsertHsStaff,type HsSecuritySnapshot} from "../verticals/housing-society/runtime/security-remote";
import HousingSectionTabs from "./shared/HousingSectionTabs";
import {NetworkEmpty,NetworkMetric,NetworkSectionHead} from "./shared/NetworkUi";
import {useLanguage} from "../lib/i18n";
const EMPTY:HsSecuritySnapshot={isSecurityOperator:false,visitors:[],staff:[],moveRequests:[],renovations:[],assets:[],compliance:[],emergencyContacts:[]};
const today=()=>new Date().toISOString().slice(0,10),soon=()=>new Date(Date.now()+86400000).toISOString().slice(0,16);
export default function HousingSocietySecurityPanel({isAdmin,demo=false,entities,onNotify}:{isAdmin:boolean;demo?:boolean;entities:NetworkAffiliatedEntity[];onNotify:(s:string)=>void}){
 const {t:xp2t}=useLanguage();
 const [securityView,setSecurityView]=useState<"visitors"|"requests"|"assets">("visitors");
 const units=useMemo(()=>entities.filter(e=>e.entity.kind==="unit"),[entities]);const [data,setData]=useState(EMPTY),[busy,setBusy]=useState(false);
 const [unitId,setUnitId]=useState(""),[visitor,setVisitor]=useState(""),[visitType,setVisitType]=useState("guest"),[expectedAt,setExpectedAt]=useState(soon());
 const [moveType,setMoveType]=useState<"move_in"|"move_out">("move_in"),[moveDate,setMoveDate]=useState(today());
 const [renoTitle,setRenoTitle]=useState(""),[renoStart,setRenoStart]=useState(today()),[renoEnd,setRenoEnd]=useState("");
 const [staffName,setStaffName]=useState(""),[staffType,setStaffType]=useState("maid"),[staffPhone,setStaffPhone]=useState(""),[staffUnit,setStaffUnit]=useState(""),[selectedStaff,setSelectedStaff]=useState("");
 const [assetCode,setAssetCode]=useState("LIFT-1"),[assetName,setAssetName]=useState("Tower A Lift"),[assetCategory,setAssetCategory]=useState("Lift"),[assetLocation,setAssetLocation]=useState("Tower A"),[selectedAsset,setSelectedAsset]=useState(""),[nextService,setNextService]=useState("");
 const [compCategory,setCompCategory]=useState("Fire Safety"),[compTitle,setCompTitle]=useState("Fire equipment inspection"),[compDue,setCompDue]=useState("");
 const [ecCategory,setEcCategory]=useState("Emergency"),[ecLabel,setEcLabel]=useState("Society Security"),[ecPhone,setEcPhone]=useState("");
 const load=async()=>{if(demo){setData({isSecurityOperator:false,visitors:[{id:"v1",unitLabel:"Aster-A-804",visitorName:"Rajesh Kulkarni",visitType:"guest",expectedAt:"2026-09-11T19:45:00+05:30",status:"expected"},{id:"v2",unitLabel:"Cedar-B-704",visitorName:"UrbanFix Technician",visitType:"service",expectedAt:"2026-09-11T16:00:00+05:30",status:"inside"},{id:"v3",unitLabel:"Maple-C-603",visitorName:"Food Delivery",visitType:"delivery",expectedAt:"2026-09-11T20:10:00+05:30",status:"expected"}],staff:[{id:"s1",fullName:"Savita Kamble",staffType:"househelp",status:"active",unitLabels:["Aster-A-804","Aster-A-903"]},{id:"s2",fullName:"Ramesh Yadav",staffType:"car_cleaner",status:"active",unitLabels:["Cedar-B-504","Cedar-B-704"]}],moveRequests:[{id:"m1",unitLabel:"B-304",moveType:"move_in",scheduledOn:"2026-09-15",status:"approved"}],renovations:[{id:"r1",unitLabel:"A-402",title:"Kitchen renovation",startsOn:"2026-09-10",status:"approved",nocReference:"NOC-2026-17"}],assets:[{id:"a1",assetCode:"DG-125",name:"Diesel Generator 125 KVA",category:"Power",location:"Utility Block",status:"active",warrantyUntil:null,nextServiceOn:"2026-10-10"},{id:"a2",assetCode:"FIRE-PUMP",name:"Fire Pump System",category:"Safety",location:"Basement",status:"active",warrantyUntil:null,nextServiceOn:"2026-09-30"},{id:"a3",assetCode:"LIFT-CB2",name:"Cedar Lift B2",category:"Lift",location:"Cedar",status:"attention",warrantyUntil:"2027-03-31",nextServiceOn:"2026-09-12"},{id:"a4",assetCode:"CCTV-CEDAR",name:"Cedar CCTV NVR",category:"Security",location:"Security Room",status:"replacement_planned",warrantyUntil:null,nextServiceOn:"2026-09-20"}],compliance:[{id:"c1",category:"Fire Safety",title:"Fire equipment inspection",dueOn:"2026-09-30",status:"open",visibility:"members"},{id:"c2",category:"Lift",title:"Cedar lift fitness certificate",dueOn:"2026-10-15",status:"open",visibility:"members"},{id:"c3",category:"Water",title:"Water quality test",dueOn:"2026-09-18",status:"open",visibility:"members"}],emergencyContacts:[{id:"e1",category:"Emergency",label:"Society Security",phone:"020-40000000",priority:1}]});return}try{setData(await fetchHsSecuritySnapshot())}catch(e:any){onNotify(e.message||"Could not load security and compliance.")}};
 useEffect(()=>{load()},[]);const run=async(fn:()=>Promise<any>,ok:string)=>{setBusy(true);try{await fn();onNotify(ok);await load()}catch(e:any){onNotify(e.message||"Could not save operational change.")}finally{setBusy(false)}};
 const expiring=data.compliance.filter(c=>c.dueOn&&new Date(c.dueOn).getTime()<=Date.now()+30*86400000&&c.status==="open");
 return <div className="hs5-security"><NetworkSectionHead kicker={<><ShieldCheck size={12}/>  {xp2t("XP2Visible0430Txt")}</>} title={xp2t("XP2Visible0431Txt")} description={xp2t("XP2Visible0432Txt")}/>
 <section className="network-metric-grid"><NetworkMetric value={data.visitors.filter(v=>v.status==="inside").length} label={xp2t("XP2Visible0433Txt")}/><NetworkMetric value={data.assets.length} label={xp2t("XP2Visible0434Txt")}/><NetworkMetric value={expiring.length} label={xp2t("XP2Visible0435Txt")}/><NetworkMetric value={data.emergencyContacts.length} label={xp2t("XP2Visible0436Txt")}/></section>
 <HousingSectionTabs label={xp2t("XP2Visible0431Txt")} value={securityView} onChange={v=>setSecurityView(v as "visitors"|"requests"|"assets")} options={[{id:"visitors",label:xp2t("XP2Visible0441Txt")},{id:"requests",label:xp2t("XP2Visible0451Txt")},...(isAdmin?[{id:"assets",label:xp2t("XP2Visible0472Txt")}]:[])]} />
 {securityView==="visitors"&&<><section className="card"><NetworkSectionHead kicker={<><PhoneCall size={12}/>  {xp2t("XP2Visible0437Txt")}</>} title={xp2t("XP2Visible0436Txt")} description={xp2t("XP2Visible0438Txt")}/>{data.emergencyContacts.length?<div className="hs2-list">{data.emergencyContacts.map(e=><div key={e.id}><PhoneCall/><span><b>{e.label}</b><small>{e.category} · {e.phone}</small></span></div>)}</div>:<NetworkEmpty icon={<PhoneCall/>} title={xp2t("XP2Visible0439Txt")} description={xp2t("XP2Visible0440Txt")}/>}</section></>}
 {securityView==="visitors"&&<><div className="hs2-admin-grid"><section className="card"><h3>{xp2t("XP2Visible0441Txt")}</h3><div className="stack-form"><select className="select" value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">{xp2t("XP2Visible0442Txt")}</option>{units.map(u=><option key={u.entity.id} value={u.entity.id}>{u.entity.label}</option>)}</select><input className="text-input" value={visitor} onChange={e=>setVisitor(e.target.value)} placeholder={xp2t("XP2Visible0443Txt")}/><select className="select" value={visitType} onChange={e=>setVisitType(e.target.value)}><option value="guest">{xp2t("XP2Visible0444Txt")}</option><option value="delivery">{xp2t("XP2Visible0445Txt")}</option><option value="service">{xp2t("XP2Visible0446Txt")}</option><option value="cab">{xp2t("XP2Visible0447Txt")}</option><option value="other">{xp2t("XP2Visible0189Txt")}</option></select><input className="text-input" type="datetime-local" value={expectedAt} onChange={e=>setExpectedAt(e.target.value)}/><button className="btn primary" disabled={busy||demo||!unitId||visitor.trim().length<2} onClick={()=>run(()=>createHsVisitor({unitId,visitorName:visitor,visitType,expectedAt}),"Visitor pre-approved.")}><DoorOpen size={14}/>  {xp2t("XP2Visible0448Txt")}</button></div><div className="hs2-list">{data.visitors.slice(0,8).map(v=><div key={v.id}><DoorOpen/><span><b>{v.visitorName} · {v.unitLabel}</b><small>{v.visitType} · {v.status}{v.expectedAt?` · ${new Date(v.expectedAt).toLocaleString()}`:""}</small></span>{data.isSecurityOperator&&v.status==="expected"&&<button className="btn small" onClick={()=>run(()=>updateHsVisitorStatus(v.id,"inside"),"Visitor checked in.")}>{xp2t("XP2Visible0449Txt")}</button>}{data.isSecurityOperator&&v.status==="inside"&&<button className="btn small" onClick={()=>run(()=>updateHsVisitorStatus(v.id,"exited"),"Visitor checked out.")}>{xp2t("XP2Visible0450Txt")}</button>}</div>)}</div></section></div></>}
 {securityView==="requests"&&<div className="hs2-admin-grid"><section className="card"><h3>{xp2t("XP2Visible0451Txt")}</h3><div className="stack-form"><select className="select" value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">{xp2t("XP2Visible0132Txt")}</option>{units.map(u=><option key={u.entity.id} value={u.entity.id}>{u.entity.label}</option>)}</select><select className="select" value={moveType} onChange={e=>setMoveType(e.target.value as any)}><option value="move_in">{xp2t("XP2Visible0452Txt")}</option><option value="move_out">{xp2t("XP2Visible0453Txt")}</option></select><input className="text-input" type="date" value={moveDate} onChange={e=>setMoveDate(e.target.value)}/><button className="btn" disabled={busy||demo||!unitId} onClick={()=>run(()=>createHsMoveRequest({unitId,moveType,scheduledOn:moveDate}),"Move request submitted.")}>{xp2t("XP2Visible0454Txt")}</button><input className="text-input" value={renoTitle} onChange={e=>setRenoTitle(e.target.value)} placeholder={xp2t("XP2Visible0455Txt")}/><input className="text-input" type="date" value={renoStart} onChange={e=>setRenoStart(e.target.value)}/><input className="text-input" type="date" value={renoEnd} onChange={e=>setRenoEnd(e.target.value)}/><button className="btn" disabled={busy||demo||!unitId||renoTitle.trim().length<3} onClick={()=>run(()=>createHsRenovationRequest({unitId,title:renoTitle,startsOn:renoStart,endsOn:renoEnd||null}),"Renovation/NOC request submitted.")}><HardHat size={14}/>  {xp2t("XP2Visible0456Txt")}</button></div></section></div>}
 {isAdmin&&securityView==="requests"&&<><div className="hs2-admin-grid"><section className="card"><h3>{xp2t("XP2Visible0457Txt")}</h3><div className="stack-form"><input className="text-input" value={staffName} onChange={e=>setStaffName(e.target.value)} placeholder={xp2t("XP2Visible0458Txt")}/><select className="select" value={staffType} onChange={e=>setStaffType(e.target.value)}><option>{xp2t("XP2Visible0459Txt")}</option><option>{xp2t("XP2Visible0460Txt")}</option><option>{xp2t("XP2Visible0461Txt")}</option><option>{xp2t("XP2Visible0462Txt")}</option><option>{xp2t("XP2Visible0463Txt")}</option><option>{xp2t("XP2Visible0464Txt")}</option><option>{xp2t("XP2Visible0465Txt")}</option></select><input className="text-input" value={staffPhone} onChange={e=>setStaffPhone(e.target.value)} placeholder={xp2t("XP2Visible0466Txt")}/><button className="btn" disabled={busy||staffName.trim().length<2} onClick={()=>run(()=>upsertHsStaff({name:staffName,staffType,phone:staffPhone}),"Staff record saved.")}>{xp2t("XP2Visible0467Txt")}</button><select className="select" value={selectedStaff} onChange={e=>setSelectedStaff(e.target.value)}><option value="">{xp2t("XP2Visible0468Txt")}</option>{data.staff.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><select className="select" value={staffUnit} onChange={e=>setStaffUnit(e.target.value)}><option value="">{xp2t("XP2Visible0469Txt")}</option>{units.map(u=><option key={u.entity.id} value={u.entity.id}>{u.entity.label}</option>)}</select><button className="btn" disabled={busy||!selectedStaff||!staffUnit} onClick={()=>run(()=>authorizeHsStaffUnit(selectedStaff,staffUnit),"Staff-flat permission recorded.")}>{xp2t("XP2Visible0469Txt")}</button></div></section>
 <section className="card"><h3>{xp2t("XP2Visible0470Txt")}</h3><div className="hs2-list">{data.moveRequests.filter(r=>r.status==="requested").map(r=><div key={r.id}><Building2/><span><b>{r.unitLabel} · {r.moveType.replace("_"," ")}</b><small>{r.scheduledOn}</small></span><button className="btn small" onClick={()=>run(()=>reviewHsOperationalRequest("move",r.id,"approved","Approved by committee"),"Move request approved.")}>{xp2t("XP2Visible0340Txt")}</button></div>)}{data.renovations.filter(r=>r.status==="requested").map(r=><div key={r.id}><HardHat/><span><b>{r.unitLabel} · {r.title}</b><small>{r.startsOn||"Date TBD"}</small></span><button className="btn small" onClick={()=>run(()=>reviewHsOperationalRequest("renovation",r.id,"approved","Follow society work-hour/safety rules",`NOC-${new Date().getFullYear()}-${String(Date.now()).slice(-4)}`),"Renovation/NOC approved.")}>{xp2t("XP2Visible0471Txt")}</button></div>)}</div></section></div></>}
 {isAdmin&&securityView==="assets"&&<><div className="hs2-admin-grid"><section className="card"><h3>{xp2t("XP2Visible0472Txt")}</h3><div className="stack-form"><input className="text-input" value={assetCode} onChange={e=>setAssetCode(e.target.value)} placeholder={xp2t("XP2Visible0473Txt")}/><input className="text-input" value={assetName} onChange={e=>setAssetName(e.target.value)} placeholder={xp2t("XP2Visible0474Txt")}/><input className="text-input" value={assetCategory} onChange={e=>setAssetCategory(e.target.value)} placeholder={xp2t("XP2Visible0475Txt")}/><input className="text-input" value={assetLocation} onChange={e=>setAssetLocation(e.target.value)} placeholder={xp2t("XP2Visible0360Txt")}/><button className="btn" disabled={busy||!assetCode||!assetName} onClick={()=>run(()=>upsertHsAsset({assetCode,name:assetName,category:assetCategory,location:assetLocation}),"Asset saved.")}><Plus size={14}/>  {xp2t("XP2Visible0476Txt")}</button><select className="select" value={selectedAsset} onChange={e=>setSelectedAsset(e.target.value)}><option value="">{xp2t("XP2Visible0477Txt")}</option>{data.assets.map(a=><option value={a.id} key={a.id}>{a.assetCode} · {a.name}</option>)}</select><input className="text-input" type="date" value={nextService} onChange={e=>setNextService(e.target.value)}/><button className="btn" disabled={busy||!selectedAsset} onClick={()=>run(()=>addHsAssetService({assetId:selectedAsset,serviceType:"Preventive service",servicedOn:today(),nextDueOn:nextService||null}),"Asset service history recorded.")}><Wrench size={14}/>  {xp2t("XP2Visible0478Txt")}</button></div><div className="hs2-list">{data.assets.map(a=><div key={a.id}><Wrench/><span><b>{a.assetCode} · {a.name}</b><small>{a.category} · {a.location||"—"}{a.nextServiceOn?` · next ${a.nextServiceOn}`:""}</small></span></div>)}</div></section>
 <section className="card"><h3>{xp2t("XP2Visible0479Txt")}</h3><div className="stack-form"><input className="text-input" value={compCategory} onChange={e=>setCompCategory(e.target.value)}/><input className="text-input" value={compTitle} onChange={e=>setCompTitle(e.target.value)}/><input className="text-input" type="date" value={compDue} onChange={e=>setCompDue(e.target.value)}/><button className="btn" disabled={busy||!compCategory||!compTitle} onClick={()=>run(()=>upsertHsCompliance({category:compCategory,title:compTitle,dueOn:compDue||null}),"Compliance item saved.")}><CalendarClock size={14}/>  {xp2t("XP2Visible0480Txt")}</button></div>{expiring.length>0&&<p className="warning"><AlertTriangle size={14}/> {expiring.length}  {xp2t("XP2Visible0481Txt")}</p>}<div className="hs2-list">{data.compliance.map(c=><div key={c.id}><CalendarClock/><span><b>{c.title}</b><small>{c.category} · {c.dueOn||"No due date"} · {c.status}</small></span></div>)}</div></section></div>
 <section className="card"><h3>{xp2t("XP2Visible0482Txt")}</h3><div className="inline-form"><input className="text-input" value={ecCategory} onChange={e=>setEcCategory(e.target.value)} placeholder={xp2t("XP2Visible0223Txt")}/><input className="text-input" value={ecLabel} onChange={e=>setEcLabel(e.target.value)} placeholder={xp2t("XP2Visible0483Txt")}/><input className="text-input" value={ecPhone} onChange={e=>setEcPhone(e.target.value)} placeholder={xp2t("XP2Visible0466Txt")}/><button className="btn" disabled={busy||!ecLabel||!ecPhone} onClick={()=>run(()=>upsertHsEmergencyContact({category:ecCategory,label:ecLabel,phone:ecPhone}),"Emergency contact published.")}>{xp2t("XP2Visible0299Txt")}</button></div></section></>}
 </div>
}
