"use client";
import {useEffect,useMemo,useState} from "react";
import {Image as ImageIcon,LoaderCircle,Palette,RefreshCw,Trash2,Upload} from "lucide-react";
import type {NetworkVerticalKind} from "../core/verticals/contracts";
import {DEFAULT_PLATFORM_DESIGN,PLATFORM_GLOBAL_SLOTS,fetchPlatformDesign,platformAssetUrl,platformVerticalSlots,removePlatformVisual,savePlatformDesignSettings,uploadPlatformVisual,type PlatformDesignSettings,type PlatformDesignSnapshot,type PlatformVisualSlot} from "../lib/platform-design";

export default function PlatformDesignStudio({verticalKind,onNotify}:{verticalKind:NetworkVerticalKind;onNotify:(message:string)=>void}){
 const [snapshot,setSnapshot]=useState<PlatformDesignSnapshot>({settings:DEFAULT_PLATFORM_DESIGN,assets:[]}),[busy,setBusy]=useState(""),[contractMissing,setContractMissing]=useState(false);
 const slots=useMemo(()=>[...PLATFORM_GLOBAL_SLOTS,...platformVerticalSlots(verticalKind)],[verticalKind]);
 const load=async()=>{try{setSnapshot(await fetchPlatformDesign());setContractMissing(false)}catch(e:any){setContractMissing(true);onNotify(e?.message||"Platform design controls need the VIS1 database contract.")}};
 useEffect(()=>{void load()},[verticalKind]);
 const refreshEverywhere=()=>window.dispatchEvent(new Event("trustweave:platform-design"));
 const saveSettings=async(next:PlatformDesignSettings)=>{setBusy("settings");try{const settings=await savePlatformDesignSettings(next);setSnapshot(x=>({...x,settings}));refreshEverywhere();onNotify("Platform visual style updated.")}catch(e:any){onNotify(e.message||"Could not update platform style.")}finally{setBusy("")}};
 const upload=async(slot:PlatformVisualSlot,file:File)=>{setBusy(slot.key);try{await uploadPlatformVisual(slot.key,file);await load();refreshEverywhere();onNotify(slot.label+" updated.")}catch(e:any){onNotify(e.message||"Could not update this visual.")}finally{setBusy("")}};
 const remove=async(slot:PlatformVisualSlot)=>{if(!confirm("Remove "+slot.label+"? The built-in visual fallback will be used."))return;setBusy(slot.key);try{await removePlatformVisual(slot.key);await load();refreshEverywhere();onNotify(slot.label+" removed.")}catch(e:any){onNotify(e.message||"Could not remove this visual.")}finally{setBusy("")}};
 const setting=<K extends keyof PlatformDesignSettings>(key:K,value:PlatformDesignSettings[K])=>void saveSettings({...snapshot.settings,[key]:value});
 return <div className="platform-design-studio" data-testid="qa-platform-design-studio">
  <section className="card platform-design-intro"><div><span className="warm-kicker"><Palette size={13}/> Founder visual control</span><h2>Platform Design Studio</h2><p>Control the platform shell and Playground visuals from one place. These choices reuse the existing design system and media pipeline rather than creating page-specific forks.</p></div><button className="btn small" disabled={!!busy} onClick={()=>void load()}><RefreshCw size={14}/> Refresh</button></section>
  {contractMissing&&<div className="notice"><b>Source is ready; database contract is not active yet.</b> Apply migration 127 only when you explicitly choose to enable these controls. Until then, every surface keeps its existing visual fallback.</div>}
  <section className="card platform-style-controls"><div className="section-title"><div><span className="warm-kicker">High-level system</span><h3>Typography & layout</h3><p className="page-subtitle">Curated presets keep every screen coherent while letting you change the overall feel without code edits.</p></div>{busy==="settings"&&<LoaderCircle className="spin" size={18}/>}</div><div className="platform-style-grid">
   <label><span>Font character</span><select className="select" value={snapshot.settings.font_key} disabled={!!busy||contractMissing} onChange={e=>setting("font_key",e.target.value as PlatformDesignSettings["font_key"])}><option value="humanist">Humanist</option><option value="editorial">Editorial</option><option value="modern">Modern</option><option value="system">System</option></select></label>
   <label><span>Layout density</span><select className="select" value={snapshot.settings.layout_key} disabled={!!busy||contractMissing} onChange={e=>setting("layout_key",e.target.value as PlatformDesignSettings["layout_key"])}><option value="compact">Compact</option><option value="balanced">Balanced</option><option value="spacious">Spacious</option></select></label>
   <label><span>Hero treatment</span><select className="select" value={snapshot.settings.hero_key} disabled={!!busy||contractMissing} onChange={e=>setting("hero_key",e.target.value as PlatformDesignSettings["hero_key"])}><option value="immersive">Immersive</option><option value="split">Split</option><option value="clean">Clean</option></select></label>
   <label><span>Corner style</span><select className="select" value={snapshot.settings.corner_key} disabled={!!busy||contractMissing} onChange={e=>setting("corner_key",e.target.value as PlatformDesignSettings["corner_key"])}><option value="soft">Soft</option><option value="rounded">Rounded</option><option value="square">Square</option></select></label>
  </div></section>
  <section className="platform-visual-groups">
   <div className="platform-visual-heading"><div><span className="warm-kicker">Media library</span><h3>Global + {verticalKind.replaceAll("-"," ")} Playground</h3><p>Upload once for a named slot; the corresponding surface reads it automatically.</p></div></div>
   <div className="platform-visual-grid">{slots.map(slot=>{const url=platformAssetUrl(snapshot,slot.key),isBusy=busy===slot.key;return <article className="card platform-visual-card" key={slot.key}><div className="platform-visual-preview">{url?<img src={url} alt=""/>:<span><ImageIcon/><small>{slot.aspect}</small></span>}</div><div className="platform-visual-copy"><b>{slot.label}</b><small>{slot.description}</small><code>{slot.key}</code></div><div className="card-actions"><label className="btn small"><Upload size={13}/>{isBusy?"Updating…":url?"Replace":"Upload"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={!!busy||contractMissing} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(slot,file);e.currentTarget.value=""}}/></label>{url&&<button className="btn small danger-text" disabled={!!busy||contractMissing} onClick={()=>void remove(slot)}><Trash2 size={13}/> Remove</button>}</div></article>})}</div>
  </section>
 </div>
}
