#!/usr/bin/env python3
"""Reconstruct a D12 candidate modular SQL baseline from live catalog captures.

The output is deliberately a candidate until it is applied to a fresh disposable
Supabase project and passes the five D12 parity layers. No database connection is
made and no raw capture is copied into the repository.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path
import re
from typing import Any, Iterable


def load_capture(path: Path) -> dict[str, Any]:
    csv.field_size_limit(2**31 - 1)
    with path.open(encoding="utf-8-sig", newline="") as stream:
        rows = list(csv.DictReader(stream))
    if len(rows) != 1 or "doc" not in rows[0]:
        raise ValueError(f"{path}: expected one CSV row with a doc column")
    return json.loads(rows[0]["doc"])


def qident(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def qname(value: str) -> str:
    parts = [x.replace('"', '') for x in value.split(".")]
    return ".".join(qident(x) for x in parts)


def role_sql(value: str) -> str:
    return "PUBLIC" if value.upper() == "PUBLIC" else qident(value)


def safe_file(value: str) -> str:
    return re.sub(r"[^a-z0-9_-]+", "-", value.lower()).strip("-")


def assign_module(name: str, kind: str, manifest: dict[str, Any]) -> str:
    leaf = name.split(".")[-1].replace('"', "").lower()
    rules = manifest["ownership_rules"]
    preferred = ["housing", "family-community", "federation", "notifications", "family",
                 "future-specializations", "activity", "workflow", "identity", "platform-core"]
    for module in preferred:
        rule = rules.get(module, {})
        if kind in {"table", "sequence"}:
            if leaf in {x.lower() for x in rule.get("table_names", [])}:
                return module
            if any(leaf.startswith(x.lower()) for x in rule.get("table_prefixes", [])):
                return module
        else:
            if leaf in {x.lower() for x in rule.get("function_names", [])}:
                return module
            if any(leaf.startswith(x.lower()) for x in rule.get("function_prefixes", [])):
                return module
            if any(x.lower() in leaf for x in rule.get("function_keywords", [])):
                return module
    return "platform-core"


def column_sql(col: dict[str, Any]) -> str:
    bits = [qident(col["name"]), col["type"]]
    identity = col.get("identity") or ""
    generated = col.get("generated") or ""
    default = col.get("default")
    if identity == "a":
        bits.append("GENERATED ALWAYS AS IDENTITY")
    elif identity == "d":
        bits.append("GENERATED BY DEFAULT AS IDENTITY")
    elif generated == "s" and default:
        bits.append(f"GENERATED ALWAYS AS ({default}) STORED")
    elif default is not None:
        bits.append(f"DEFAULT {default}")
    if col.get("not_null"):
        bits.append("NOT NULL")
    return " ".join(bits)


def policy_sql(p: dict[str, Any]) -> str:
    roles = p.get("roles") or []
    if isinstance(roles, str):
        roles = [roles]
    roles_sql = ", ".join(role_sql(str(x)) for x in roles) if roles else "PUBLIC"
    cmd = str(p.get("command") or "ALL").upper()
    permissive = "PERMISSIVE" if str(p.get("permissive", "PERMISSIVE")).upper() == "PERMISSIVE" else "RESTRICTIVE"
    target = f"{qident(p['schema'])}.{qident(p['table'])}"
    sql = f"CREATE POLICY {qident(p['name'])} ON {target} AS {permissive} FOR {cmd} TO {roles_sql}"
    if p.get("using") is not None:
        sql += f" USING ({p['using']})"
    if p.get("check") is not None:
        sql += f" WITH CHECK ({p['check']})"
    return sql + ";"


def grouped_grants(rows: Iterable[dict[str, Any]]) -> list[str]:
    grouped: dict[tuple[str, str, str], set[str]] = {}
    for r in rows:
        key = (r["schema"], r["table"], r["grantee"])
        grouped.setdefault(key, set()).add(r["privilege"])
    order = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES", "TRIGGER"]
    out = []
    for (schema, table, grantee), privileges in sorted(grouped.items()):
        ordered = [x for x in order if x in privileges] + sorted(privileges - set(order))
        out.append(f"GRANT {', '.join(ordered)} ON TABLE {qident(schema)}.{qident(table)} TO {role_sql(grantee)};")
    return out


def parse_acl(acl: str | None) -> list[tuple[str, str]]:
    # Sufficient for captured PostgreSQL ACL strings whose role names do not contain commas.
    if not acl or acl == "{}":
        return []
    raw = acl.strip("{}")
    items = []
    for entry in raw.split(","):
        left = entry.split("/", 1)[0]
        if "=" not in left:
            continue
        principal, privileges = left.split("=", 1)
        principal = principal.strip('"') or "PUBLIC"
        items.append((principal, privileges.replace("*", "")))
    return items


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines).rstrip() + "\n"
    path.write_text(text, encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("primary", type=Path)
    ap.add_argument("--supplement", type=Path)
    ap.add_argument("--project", type=Path, default=Path(__file__).resolve().parent.parent)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    project = args.project.resolve()
    primary = load_capture(args.primary)
    supplement = load_capture(args.supplement) if args.supplement else {}
    manifest = json.loads((project / "db" / "canonical" / "modules.json").read_text(encoding="utf-8"))
    sorted_modules = sorted(manifest["modules"], key=lambda x: x["order"])
    modules = [m["id"] for m in sorted_modules]
    module_order = {m["id"]: m["order"] for m in sorted_modules}
    out = args.out.resolve()
    out.mkdir(parents=True, exist_ok=True)

    header = [
        "-- GENERATED D12 CANDIDATE. DO NOT APPLY TO THE GOLDEN DATABASE.",
        "-- Promote only after fresh-project five-layer parity.",
        "",
    ]

    # Phase 00: extensions.
    ext_lines = header[:]
    for ext in sorted(primary.get("extensions", []), key=lambda x: x["name"]):
        if ext["name"] == "plpgsql":
            continue
        ext_lines.append(f"CREATE EXTENSION IF NOT EXISTS {qident(ext['name'])} WITH SCHEMA {qident(ext['schema'])};")
    write(out / "00-foundation" / "00-extensions.sql", ext_lines)

    # Phase 05: sequences across all modules before table creation.
    seq_by_module: dict[str, list[dict[str, Any]]] = {m: [] for m in modules}
    for seq in supplement.get("sequences", []):
        name = f"{seq['schema']}.{seq['name']}"
        seq_by_module[assign_module(name, "sequence", manifest)].append(seq)
    for module, seqs in seq_by_module.items():
        if not seqs:
            continue
        lines = header[:]
        for s in sorted(seqs, key=lambda x: (x["schema"], x["name"])):
            lines.append(
                f"CREATE SEQUENCE IF NOT EXISTS {qident(s['schema'])}.{qident(s['name'])} AS {s['data_type']} "
                f"INCREMENT BY {s['increment']} MINVALUE {s['min']} MAXVALUE {s['max']} START WITH {s['start']} "
                f"CACHE {s['cache']} {'CYCLE' if s['cycle'] else 'NO CYCLE'};"
            )
        write(out / "05-sequences" / f"{module_order[module]:03d}-{safe_file(module)}.sql", lines)

    relations = {x["name"]: x for x in primary.get("relations", []) if x.get("kind") in ("r", "p")}
    columns: dict[str, list[dict[str, Any]]] = {}
    constraints: dict[str, list[dict[str, Any]]] = {}
    indexes: dict[str, list[dict[str, Any]]] = {}
    for row in primary.get("columns", []):
        columns.setdefault(row["relation"], []).append(row)
    for row in primary.get("constraints", []):
        constraints.setdefault(row["relation"], []).append(row)
    for row in primary.get("indexes", []):
        indexes.setdefault(row["relation"], []).append(row)

    tables_by_module: dict[str, list[str]] = {m: [] for m in modules}
    for name in relations:
        tables_by_module[assign_module(name, "table", manifest)].append(name)

    # Phases 10/20/30 are deliberately phase-first, not module-first. This guarantees every
    # table exists before any cross-module FK/constraint is applied.
    for module in modules:
        prefix = f"{module_order[module]:03d}-{safe_file(module)}.sql"
        table_names = sorted(tables_by_module[module])
        if not table_names:
            continue

        lines = header[:]
        for name in table_names:
            cols = columns.get(name, [])
            lines.append(f"CREATE TABLE IF NOT EXISTS {qname(name)} (")
            lines.append(",\n".join("  " + column_sql(c) for c in cols))
            lines.append(");\n")
        write(out / "10-tables" / prefix, lines)

        lines = header[:]
        for name in table_names:
            for c in sorted(constraints.get(name, []), key=lambda x: x["name"]):
                lines.append(f"ALTER TABLE {qname(name)} ADD CONSTRAINT {qident(c['name'])} {c['definition']};")
        write(out / "20-constraints" / prefix, lines)

        lines = header[:]
        constraint_names = {c["name"] for name in table_names for c in constraints.get(name, [])}
        for name in table_names:
            for idx in sorted(indexes.get(name, []), key=lambda x: x["name"]):
                if idx["name"] in constraint_names:
                    continue
                lines.append(idx["definition"].rstrip(";") + ";")
        write(out / "30-indexes" / prefix, lines)

    # Phase 40: exact live function definitions.
    funcs_by_module: dict[str, list[dict[str, Any]]] = {m: [] for m in modules}
    for fn in primary.get("functions", []):
        funcs_by_module[assign_module(fn["name"], "function", manifest)].append(fn)
    for module, funcs in funcs_by_module.items():
        if not funcs:
            continue
        prefix = f"{module_order[module]:03d}-{safe_file(module)}.sql"
        lines = header[:]
        for fn in sorted(funcs, key=lambda x: (x["name"], x.get("identity_arguments", ""))):
            lines.append(fn["definition"].rstrip(";") + ";\n")
        write(out / "40-functions" / prefix, lines)

    # Phase 45: source/application contracts proved missing from live. They stay explicit so
    # the generated baseline is never confused with a literal live dump.
    migration105 = project / "supabase" / "migrations" / "105_engagement_mentions_role_routing.sql"
    if migration105.exists():
        source105 = migration105.read_text(errors="replace")
        repair_lines = header[:] + [
            "-- D12 explicit DRIFT repair candidate: exact signatures are source-required but absent in the golden live catalog.",
            "-- Extracted from immutable migration 105; validate behavior on the disposable candidate project.",
        ]
        for fname in ("set_network_notification_role", "remove_network_notification_role"):
            match = re.search(
                rf"(create\s+or\s+replace\s+function\s+public\.{fname}\s*\(.*?\n(?:revoke|grant).*?;(?:grant.*?;)?)(?=\n\n|\ncreate\s+or\s+replace\s+function|\Z)",
                source105,
                flags=re.I | re.S,
            )
            if not match:
                raise ValueError(f"Could not extract migration-105 drift repair for {fname}")
            repair_lines.append(match.group(1).strip() + "\n")
        write(out / "45-source-drift-repairs" / "050-notifications.sql", repair_lines)

    # Phase 50: triggers after functions.
    triggers_by_module: dict[str, list[dict[str, Any]]] = {m: [] for m in modules}
    for trigger in primary.get("triggers", []):
        triggers_by_module[assign_module(trigger["relation"], "table", manifest)].append(trigger)
    for module, triggers in triggers_by_module.items():
        if not triggers:
            continue
        prefix = f"{module_order[module]:03d}-{safe_file(module)}.sql"
        lines = header[:]
        for trigger in sorted(triggers, key=lambda x: (x["relation"], x["name"])):
            lines.append(trigger["definition"].rstrip(";") + ";")
            if trigger.get("enabled") == "D":
                lines.append(f"ALTER TABLE {qname(trigger['relation'])} DISABLE TRIGGER {qident(trigger['name'])};")
        write(out / "50-triggers" / prefix, lines)

    # Phase 60: table RLS and policies. Storage policies are isolated in phase 70.
    policies_by_module: dict[str, list[dict[str, Any]]] = {m: [] for m in modules}
    storage_policies: list[dict[str, Any]] = []
    for policy in primary.get("policies", []):
        if policy["schema"] == "storage":
            storage_policies.append(policy)
            continue
        relation = f"{policy['schema']}.{policy['table']}"
        policies_by_module[assign_module(relation, "table", manifest)].append(policy)
    for module in modules:
        prefix = f"{module_order[module]:03d}-{safe_file(module)}.sql"
        owned = sorted(tables_by_module[module])
        policies = policies_by_module[module]
        if not owned and not policies:
            continue
        lines = header[:]
        for name in owned:
            relation = relations[name]
            if relation.get("rls"):
                lines.append(f"ALTER TABLE {qname(name)} ENABLE ROW LEVEL SECURITY;")
            if relation.get("force_rls"):
                lines.append(f"ALTER TABLE {qname(name)} FORCE ROW LEVEL SECURITY;")
        for policy in sorted(policies, key=lambda x: (x["table"], x["name"])):
            lines.append(policy_sql(policy))
        write(out / "60-security" / prefix, lines)

    # Phase 70: Storage bucket configuration and captured Storage policies. Files/objects are never copied.
    storage_lines = header[:]
    for bucket in supplement.get("storage_buckets", []):
        mimes = (
            "NULL"
            if bucket.get("allowed_mime_types") is None
            else "ARRAY[" + ",".join("'" + str(x).replace("'", "''") + "'" for x in bucket["allowed_mime_types"]) + "]::text[]"
        )
        bucket_id = str(bucket["id"]).replace("'", "''")
        bucket_name = str(bucket["name"]).replace("'", "''")
        storage_lines.append(
            "INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types) VALUES "
            f"('{bucket_id}','{bucket_name}',{'true' if bucket.get('public') else 'false'},"
            f"{'NULL' if bucket.get('file_size_limit') is None else int(bucket['file_size_limit'])},{mimes}) "
            "ON CONFLICT(id) DO UPDATE SET name=excluded.name,public=excluded.public,"
            "file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;"
        )
    for policy in sorted(storage_policies, key=lambda x: (x["table"], x["name"])):
        storage_lines.append(policy_sql(policy))
    write(out / "70-storage" / "000-storage.sql", storage_lines)

    # Phase 80: table grants.
    grants_by_module: dict[str, list[dict[str, Any]]] = {m: [] for m in modules}
    for grant in primary.get("grants", []):
        if grant["schema"] == "storage":
            continue
        relation = f"{grant['schema']}.{grant['table']}"
        grants_by_module[assign_module(relation, "table", manifest)].append(grant)
    for module, rows in grants_by_module.items():
        if not rows:
            continue
        prefix = f"{module_order[module]:03d}-{safe_file(module)}.sql"
        write(out / "80-table-grants" / prefix, header[:] + grouped_grants(rows))

    # Phase 90: exact captured function EXECUTE ACLs, using identity arguments from supplement.
    function_grants_by_module: dict[str, list[str]] = {m: [] for m in modules}
    for function_grant in supplement.get("function_grants", []):
        full_name = f"{function_grant['schema']}.{function_grant['name']}"
        signature = (
            f"{qident(function_grant['schema'])}.{qident(function_grant['name'])}"
            f"({function_grant.get('identity_arguments', '')})"
        )
        for principal, privileges in parse_acl(function_grant.get("acl")):
            if "X" in privileges:
                module = assign_module(full_name, "function", manifest)
                function_grants_by_module[module].append(
                    f"GRANT EXECUTE ON FUNCTION {signature} TO {role_sql(principal)};"
                )
    for module, rows in function_grants_by_module.items():
        if not rows:
            continue
        prefix = f"{module_order[module]:03d}-{safe_file(module)}.sql"
        write(out / "90-function-grants" / prefix, header[:] + sorted(set(rows)))

    # Verification manifest: no raw capture/body copy; only capture hashes, counts and generated file hashes.
    generated = sorted(out.rglob("*.sql"))
    result = {
        "format": "trustweave-d12-candidate-baseline-v1",
        "status": "candidate-until-fresh-parity",
        "apply_order": [str(path.relative_to(out)).replace("\\", "/") for path in generated],
        "server_version": primary.get("server_version"),
        "primary_capture_sha256": hashlib.sha256(args.primary.read_bytes()).hexdigest(),
        "supplement_capture_sha256": hashlib.sha256(args.supplement.read_bytes()).hexdigest() if args.supplement else None,
        "object_counts": {
            "relations": len(primary.get("relations", [])),
            "columns": len(primary.get("columns", [])),
            "constraints": len(primary.get("constraints", [])),
            "indexes": len(primary.get("indexes", [])),
            "functions": len(primary.get("functions", [])),
            "triggers": len(primary.get("triggers", [])),
            "policies": len(primary.get("policies", [])),
            "sequences": len(supplement.get("sequences", [])),
        },
        "explicit_source_drift_repairs": [
            "public.set_network_notification_role(text,text,uuid,boolean)",
            "public.remove_network_notification_role(text,uuid)",
        ],
        "files": [
            {"path": str(path.relative_to(out)).replace("\\", "/"), "sha256": sha(path)}
            for path in generated
        ],
    }
    (out / "manifest.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
