#!/usr/bin/env python3
"""Reconstruct a D12 candidate modular SQL baseline from live catalog captures.

The output is deliberately a candidate until it is applied to a fresh disposable
Supabase project and passes the five D12 parity layers. No database connection is
made and no raw capture is copied into the repository.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path
import re
from typing import Any, Iterable


def load_capture(path: Path) -> dict[str, Any]:
    csv.field_size_limit(2**31 - 1)
    with path.open(encoding="utf-8-sig", newline="") as stream:
        rows = list(csv.DictReader(stream))
    if len(rows) != 1 or "doc" not in rows[0]:
        raise ValueError(f"{path}: expected one CSV row with a doc column")
    return json.loads(rows[0]["doc"])


def qident(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def qname(value: str) -> str:
    parts = [x.replace('"', '') for x in value.split(".")]
    return ".".join(qident(x) for x in parts)


def role_sql(value: str) -> str:
    return "PUBLIC" if value.upper() == "PUBLIC" else qident(value)


def safe_file(value: str) -> str:
    return re.sub(r"[^a-z0-9_-]+", "-", value.lower()).strip("-")


def assign_module(name: str, kind: str, manifest: dict[str, Any]) -> str:
    leaf = name.split(".")[-1].replace('"', "").lower()
    rules = manifest["ownership_rules"]
    existing = {m["id"] for m in manifest["modules"]}
    preferred = ["housing", "family-community", "federation", "notifications", "family",
                 "future-specializations", "activity", "workflow", "identity", "platform-core"]
    ordered = [m for m in preferred if m in existing]

    # Exact ownership overrides are global and must beat generic prefixes.
    names_key = "table_names" if kind in {"table", "sequence"} else "function_names"
    for module in ordered:
        if leaf in {x.lower() for x in rules.get(module, {}).get(names_key, [])}:
            return module

    for module in ordered:
        rule = rules.get(module, {})
        if kind in {"table", "sequence"}:
            if any(leaf.startswith(x.lower()) for x in rule.get("table_prefixes", [])):
                return module
        else:
            if any(leaf.startswith(x.lower()) for x in rule.get("function_prefixes", [])):
                return module
            if any(x.lower() in leaf for x in rule.get("function_keywords", [])):
                return module
    return "platform-core"


def column_sql(col: dict[str, Any]) -> str:
    bits = [qident(col["name"]), col["type"]]
    identity = col.get("identity") or ""
    generated = col.get("generated") or ""
    default = col.get("default")
    if identity == "a":
        bits.append("GENERATED ALWAYS AS IDENTITY")
    elif identity == "d":
        bits.append("GENERATED BY DEFAULT AS IDENTITY")
    elif generated == "s" and default:
        bits.append(f"GENERATED ALWAYS AS ({default}) STORED")
    elif default is not None:
        bits.append(f"DEFAULT {default}")
    if col.get("not_null"):
        bits.append("NOT NULL")
    return " ".join(bits)


def policy_sql(p: dict[str, Any]) -> str:
    roles = p.get("roles") or []
    if isinstance(roles, str):
        roles = [roles]
    roles_sql = ", ".join(role_sql(str(x)) for x in roles) if roles else "PUBLIC"
    cmd = str(p.get("command") or "ALL").upper()
    permissive = "PERMISSIVE" if str(p.get("permissive", "PERMISSIVE")).upper() == "PERMISSIVE" else "RESTRICTIVE"
    target = f"{qident(p['schema'])}.{qident(p['table'])}"
    sql = f"CREATE POLICY {qident(p['name'])} ON {target} AS {permissive} FOR {cmd} TO {roles_sql}"
    if p.get("using") is not None:
        sql += f" USING ({p['using']})"
    if p.get("check") is not None:
        sql += f" WITH CHECK ({p['check']})"
    return sql + ";"


def grouped_grants(rows: Iterable[dict[str, Any]]) -> list[str]:
    grouped: dict[tuple[str, str, str], set[str]] = {}
    for r in rows:
        key = (r["schema"], r["table"], r["grantee"], str(r.get("grantable", "NO")).upper() == "YES")
        grouped.setdefault(key, set()).add(r["privilege"])
    order = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES", "TRIGGER"]
    out = []
    for (schema, table, grantee, grantable), privileges in sorted(grouped.items()):
        ordered = [x for x in order if x in privileges] + sorted(privileges - set(order))
        suffix = " WITH GRANT OPTION" if grantable else ""
        out.append(f"GRANT {', '.join(ordered)} ON TABLE {qident(schema)}.{qident(table)} TO {role_sql(grantee)}{suffix};")
    return out


def parse_acl(acl: str | None) -> list[tuple[str, str, set[str]]]:
    # PostgreSQL aclitem text: grantee=privileges/grantor. A '*' after a privilege
    # marks WITH GRANT OPTION for that privilege.
    if not acl or acl == "{}":
        return []
    raw = acl.strip("{}")
    items: list[tuple[str, str, set[str]]] = []
    for entry in raw.split(","):
        left = entry.split("/", 1)[0]
        if "=" not in left:
            continue
        principal, encoded = left.split("=", 1)
        principal = principal.strip('"') or "PUBLIC"
        privileges: list[str] = []
        grantable: set[str] = set()
        i = 0
        while i < len(encoded):
            char = encoded[i]
            if char == "*":
                i += 1
                continue
            privileges.append(char)
            if i + 1 < len(encoded) and encoded[i + 1] == "*":
                grantable.add(char)
                i += 1
            i += 1
        items.append((principal, "".join(privileges), grantable))
    return items


def acl_privilege_name(kind: str, char: str) -> str | None:
    maps = {
        "schema": {"U": "USAGE", "C": "CREATE"},
        "function": {"X": "EXECUTE"},
        "sequence": {"r": "SELECT", "w": "UPDATE", "U": "USAGE"},
    }
    return maps.get(kind, {}).get(char)


def validate_module_graph(manifest: dict[str, Any]) -> None:
    modules = {m["id"]: set(m.get("depends_on", [])) for m in manifest["modules"]}
    unknown = sorted({dep for deps in modules.values() for dep in deps if dep not in modules})
    if unknown:
        raise ValueError(f"Unknown canonical module dependencies: {unknown}")

    visiting: list[str] = []
    visited: set[str] = set()

    def walk(node: str) -> None:
        if node in visiting:
            start = visiting.index(node)
            raise ValueError(f"Canonical module dependency cycle: {' -> '.join(visiting[start:] + [node])}")
        if node in visited:
            return
        visiting.append(node)
        for dep in sorted(modules[node]):
            walk(dep)
        visiting.pop()
        visited.add(node)

    for node in sorted(modules):
        walk(node)


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines).rstrip() + "\n"
    path.write_text(text, encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("primary", type=Path)
    ap.add_argument("--supplement", type=Path)
    ap.add_argument("--project", type=Path, default=Path(__file__).resolve().parent.parent)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    project = args.project.resolve()
    primary = load_capture(args.primary)
    supplement = load_capture(args.supplement) if args.supplement else {}
    manifest = json.loads((project / "db" / "canonical" / "modules.json").read_text(encoding="utf-8"))
    validate_module_graph(manifest)
    sorted_modules = sorted(manifest["modules"], key=lambda x: x["order"])
    modules = [m["id"] for m in sorted_modules]
    module_order = {m["id"]: m["order"] for m in sorted_modules}
    out = args.out.resolve()
    out.mkdir(parents=True, exist_ok=True)

    header = [
        "-- GENERATED D12 CANDIDATE. DO NOT APPLY TO THE GOLDEN DATABASE.",
        "-- Promote only after fresh-project five-layer parity.",
        "",
    ]

    # Phase 00: extensions.
    ext_lines = header[:]
    for ext in sorted(primary.get("extensions", []), key=lambda x: x["name"]):
        if ext["name"] == "plpgsql":
            continue
        ext_lines.append(f"CREATE EXTENSION IF NOT EXISTS {qident(ext['name'])} WITH SCHEMA {qident(ext['schema'])};")
    write(out / "00-foundation" / "00-extensions.sql", ext_lines)

    relations = {x["name"]: x for x in primary.get("relations", []) if x.get("kind") in ("r", "p")}
    columns: dict[str, list[dict[str, Any]]] = {}
    constraints: dict[str, list[dict[str, Any]]] = {}
    indexes: dict[str, list[dict[str, Any]]] = {}
    for row in primary.get("columns", []):
        columns.setdefault(row["relation"], []).append(row)
    for row in primary.get("constraints", []):
        constraints.setdefault(row["relation"], []).append(row)
    for row in primary.get("indexes", []):
        indexes.setdefault(row["relation"], []).append(row)

    tables_by_module: dict[str, list[str]] = {m: [] for m in modules}
    for name in relations:
        tables_by_module[assign_module(name, "table", manifest)].append(name)

    # Sequence ownership must be reconstructed carefully: identity columns create their
    # own sequence as part of CREATE TABLE and must not collide with an earlier CREATE SEQUENCE.
    live_sequences = {
        f"{x['schema']}.{x['name']}": x for x in supplement.get("sequences", [])
    }
    identity_sequence_names: set[str] = set()
    sequence_owners: dict[str, tuple[str, str]] = {}
    for relation, rows in columns.items():
        clean_relation = relation.replace('"', "")
        schema, table = clean_relation.split(".", 1)
        for col in rows:
            conventional = f"{schema}.{table}_{col['name']}_seq"
            if (col.get("identity") or "") in {"a", "d"} and conventional in live_sequences:
                identity_sequence_names.add(conventional)
                sequence_owners[conventional] = (relation, col["name"])
            default = str(col.get("default") or "")
            match = re.search(r"nextval\('([^']+)'::regclass\)", default, flags=re.I)
            if match:
                seq_name = match.group(1).replace('"', "")
                if "." not in seq_name:
                    seq_name = f"{schema}.{seq_name}"
                if seq_name in live_sequences:
                    sequence_owners[seq_name] = (relation, col["name"])

    # Phase 05: create only standalone/serial-style sequences. Identity-owned sequences
    # are created implicitly by their table definitions in phase 10.
    seq_by_module: dict[str, list[tuple[str, dict[str, Any]]]] = {m: [] for m in modules}
    for name, seq in live_sequences.items():
        if name in identity_sequence_names:
            continue
        owner = sequence_owners.get(name)
        module = assign_module(owner[0], "table", manifest) if owner else assign_module(name, "sequence", manifest)
        seq_by_module[module].append((name, seq))
    for module, seqs in seq_by_module.items():
        if not seqs:
            continue
        lines = header[:]
        for name, seq in sorted(seqs, key=lambda x: x[0]):
            lines.append(
                f"CREATE SEQUENCE IF NOT EXISTS {qident(seq['schema'])}.{qident(seq['name'])} AS {seq['data_type']} "
                f"INCREMENT BY {seq['increment']} MINVALUE {seq['min']} MAXVALUE {seq['max']} START WITH {seq['start']} "
                f"CACHE {seq['cache']} {'CYCLE' if seq['cycle'] else 'NO CYCLE'};"
            )
        write(out / "05-sequences" / f"{module_order[module]:03d}-{safe_file(module)}.sql", lines)

    # Some table defaults/checks/index expressions call application functions. Bootstrap
    # only those required functions before table/constraint creation, with body checking
    # disabled because their bodies can legitimately reference tables created later.
    expression_texts: list[str] = []
    expression_texts.extend(str(c.get("default") or "") for rows in columns.values() for c in rows)
    expression_texts.extend(str(c.get("definition") or "") for rows in constraints.values() for c in rows)
    expression_texts.extend(str(i.get("definition") or "") for rows in indexes.values() for i in rows)
    functions = list(primary.get("functions", []))
    by_leaf: dict[str, list[dict[str, Any]]] = {}
    for fn in functions:
        leaf = fn["name"].split(".")[-1].replace('"', "").lower()
        by_leaf.setdefault(leaf, []).append(fn)
    required_leaves = {
        leaf
        for leaf in by_leaf
        if any(re.search(rf"(?<![A-Za-z0-9_])(?:public\.)?{re.escape(leaf)}\s*\(", expr, flags=re.I)
               for expr in expression_texts)
    }
    bootstrap_functions = [
        fn for leaf in sorted(required_leaves)
        for fn in sorted(by_leaf[leaf], key=lambda x: x.get("identity_arguments", ""))
    ]
    relation_leaves = {x.split(".")[-1].replace('"', "").lower() for x in relations}
    for fn in bootstrap_functions:
        signature = f"{fn.get('identity_arguments', '')} {fn.get('result', '')}".lower()
        composite_hits = [leaf for leaf in relation_leaves if f"public.{leaf}" in signature]
        if composite_hits:
            raise ValueError(
                f"Bootstrap function {fn['name']} has table-composite signature dependency: {composite_hits}"
            )
    if bootstrap_functions:
        lines = header[:] + [
            "-- Required before CREATE TABLE/constraints because captured expressions call these functions.",
            "SET check_function_bodies = off;",
        ]
        for fn in bootstrap_functions:
            lines.append(fn["definition"].rstrip(";") + ";\n")
        lines.append("SET check_function_bodies = on;")
        write(out / "08-bootstrap-functions" / "000-required.sql", lines)

    # Phase 10: all table shells before any cross-table constraint.
    for module in modules:
        table_names = sorted(tables_by_module[module])
        if not table_names:
            continue
        prefix = f"{module_order[module]:03d}-{safe_file(module)}.sql"
        lines = header[:]
        for name in table_names:
            cols = columns.get(name, [])
            lines.append(f"CREATE TABLE IF NOT EXISTS {qname(name)} (")
            lines.append(",\n".join("  " + column_sql(c) for c in cols))
            lines.append(");\n")
        write(out / "10-tables" / prefix, lines)

    # Phase 15: restore exact sequence options after identity sequences exist, and attach
    # standalone nextval sequences to their owning columns.
    sequence_lines = header[:]
    for name, seq in sorted(live_sequences.items()):
        sequence_lines.append(
            f"ALTER SEQUENCE {qident(seq['schema'])}.{qident(seq['name'])} AS {seq['data_type']} "
            f"INCREMENT BY {seq['increment']} MINVALUE {seq['min']} MAXVALUE {seq['max']} START WITH {seq['start']} "
            f"CACHE {seq['cache']} {'CYCLE' if seq['cycle'] else 'NO CYCLE'};"
        )
        if name in sequence_owners and name not in identity_sequence_names:
            relation, column = sequence_owners[name]
            sequence_lines.append(
                f"ALTER SEQUENCE {qident(seq['schema'])}.{qident(seq['name'])} "
                f"OWNED BY {qname(relation)}.{qident(column)};"
            )
    if live_sequences:
        write(out / "15-sequence-ownership" / "000-sequences.sql", sequence_lines)

    # Phase 20: all constraints after all tables. Phase 30: expression/non-constraint indexes.
    for module in modules:
        table_names = sorted(tables_by_module[module])
        if not table_names:
            continue
        prefix = f"{module_order[module]:03d}-{safe_file(module)}.sql"
        lines = header[:]
        module_constraints = [
            (name, c)
            for name in table_names
            for c in constraints.get(name, [])
        ]
        # Foreign keys can only be created after the referenced PK/UNIQUE exists.
        # Module order handles cross-module dependencies; this local priority handles
        # same-module references such as audit_log -> networks.
        module_constraints.sort(
            key=lambda item: (
                1 if str(item[1].get("kind") or "").lower() == "f" else 0,
                item[0],
                item[1]["name"],
            )
        )
        for name, c in module_constraints:
            lines.append(f"ALTER TABLE {qname(name)} ADD CONSTRAINT {qident(c['name'])} {c['definition']};")
        write(out / "20-constraints" / prefix, lines)

        lines = header[:]
        constraint_names = {c["name"] for name in table_names for c in constraints.get(name, [])}
        for name in table_names:
            for idx in sorted(indexes.get(name, []), key=lambda x: x["name"]):
                if idx["name"] in constraint_names:
                    continue
                lines.append(idx["definition"].rstrip(";") + ";")
        write(out / "30-indexes" / prefix, lines)

    # Phase 40: exact live function definitions. Body validation is intentionally disabled
    # during creation so SQL-language functions may reference functions emitted later.
    funcs_by_module: dict[str, list[dict[str, Any]]] = {m: [] for m in modules}
    for fn in functions:
        funcs_by_module[assign_module(fn["name"], "function", manifest)].append(fn)
    for module, funcs in funcs_by_module.items():
        if not funcs:
            continue
        prefix = f"{module_order[module]:03d}-{safe_file(module)}.sql"
        lines = header[:] + ["SET check_function_bodies = off;"]
        for fn in sorted(funcs, key=lambda x: (x["name"], x.get("identity_arguments", ""))):
            lines.append(fn["definition"].rstrip(";") + ";\n")
        lines.append("SET check_function_bodies = on;")
        write(out / "40-functions" / prefix, lines)

    # Phase 45: source/application contracts proved missing from live. They stay explicit so
    # the generated baseline is never confused with a literal live dump.
    migration105 = project / "supabase" / "migrations" / "105_engagement_mentions_role_routing.sql"
    if migration105.exists():
        source105 = migration105.read_text(errors="replace")
        repair_lines = header[:] + [
            "-- D12 explicit DRIFT repair candidate: exact signatures are source-required but absent in the golden live catalog.",
            "-- Extracted from immutable migration 105; validate behavior on the disposable candidate project.",
        ]
        for fname in ("set_network_notification_role", "remove_network_notification_role"):
            start = re.search(
                rf"create\s+or\s+replace\s+function\s+public\.{fname}\s*\(",
                source105,
                flags=re.I,
            )
            if not start:
                raise ValueError(f"Could not locate migration-105 drift repair for {fname}")
            nxt = re.search(
                r"\ncreate\s+or\s+replace\s+function\s+public\.",
                source105[start.end():],
                flags=re.I,
            )
            end = start.end() + nxt.start() if nxt else len(source105)
            block = source105[start.start():end].strip()
            if "revoke all on function" not in block.lower() or "grant execute on function" not in block.lower():
                raise ValueError(f"Migration-105 drift repair ACL incomplete for {fname}")
            repair_lines.append(block + "\n")
        write(out / "45-source-drift-repairs" / "050-notifications.sql", repair_lines)

    # Phase 50: triggers after functions.
    triggers_by_module: dict[str, list[dict[str, Any]]] = {m: [] for m in modules}
    for trigger in primary.get("triggers", []):
        triggers_by_module[assign_module(trigger["relation"], "table", manifest)].append(trigger)
    for module, triggers in triggers_by_module.items():
        if not triggers:
            continue
        prefix = f"{module_order[module]:03d}-{safe_file(module)}.sql"
        lines = header[:]
        for trigger in sorted(triggers, key=lambda x: (x["relation"], x["name"])):
            lines.append(trigger["definition"].rstrip(";") + ";")
            if trigger.get("enabled") == "D":
                lines.append(f"ALTER TABLE {qname(trigger['relation'])} DISABLE TRIGGER {qident(trigger['name'])};")
        write(out / "50-triggers" / prefix, lines)

    # Phase 60: table RLS and policies. Storage policies are isolated in phase 70.
    policies_by_module: dict[str, list[dict[str, Any]]] = {m: [] for m in modules}
    storage_policies: list[dict[str, Any]] = []
    for policy in primary.get("policies", []):
        if policy["schema"] == "storage":
            storage_policies.append(policy)
            continue
        relation = f"{policy['schema']}.{policy['table']}"
        policies_by_module[assign_module(relation, "table", manifest)].append(policy)
    for module in modules:
        prefix = f"{module_order[module]:03d}-{safe_file(module)}.sql"
        owned = sorted(tables_by_module[module])
        policies = policies_by_module[module]
        if not owned and not policies:
            continue
        lines = header[:]
        for name in owned:
            relation = relations[name]
            if relation.get("rls"):
                lines.append(f"ALTER TABLE {qname(name)} ENABLE ROW LEVEL SECURITY;")
            if relation.get("force_rls"):
                lines.append(f"ALTER TABLE {qname(name)} FORCE ROW LEVEL SECURITY;")
        for policy in sorted(policies, key=lambda x: (x["table"], x["name"])):
            lines.append(policy_sql(policy))
        write(out / "60-security" / prefix, lines)

    # Phase 70: Storage relation security, bucket configuration and captured policies.
    # Storage object/file rows are never copied.
    storage_lines = header[:] + [
        "-- Built-in storage.buckets/storage.objects are owned by supabase_storage_admin on hosted Supabase.",
        "-- Their RLS/force-RLS state is parity-verified, not mutated by the canonical candidate.",
    ]
    for bucket in supplement.get("storage_buckets", []):
        mimes = (
            "NULL"
            if bucket.get("allowed_mime_types") is None
            else "ARRAY[" + ",".join("'" + str(x).replace("'", "''") + "'" for x in bucket["allowed_mime_types"]) + "]::text[]"
        )
        bucket_id = str(bucket["id"]).replace("'", "''")
        bucket_name = str(bucket["name"]).replace("'", "''")
        storage_lines.append(
            "INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types) VALUES "
            f"('{bucket_id}','{bucket_name}',{'true' if bucket.get('public') else 'false'},"
            f"{'NULL' if bucket.get('file_size_limit') is None else int(bucket['file_size_limit'])},{mimes}) "
            "ON CONFLICT(id) DO UPDATE SET name=excluded.name,public=excluded.public,"
            "file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;"
        )
    for policy in sorted(storage_policies, key=lambda x: (x["table"], x["name"])):
        storage_lines.append(policy_sql(policy))
    write(out / "70-storage" / "000-storage.sql", storage_lines)

    # Phase 75: captured application-schema ACL. Normalize API/public principals, then replay.
    schema_lines = header[:]
    for row in supplement.get("schema_grants", []):
        schema = row["schema"]
        schema_lines.append(
            f"REVOKE ALL ON SCHEMA {qident(schema)} FROM PUBLIC, {qident('anon')}, "
            f"{qident('authenticated')}, {qident('service_role')};"
        )
        for principal, privileges, grantable in parse_acl(row.get("acl")):
            for char in privileges:
                privilege = acl_privilege_name("schema", char)
                if not privilege:
                    continue
                suffix = " WITH GRANT OPTION" if char in grantable else ""
                schema_lines.append(
                    f"GRANT {privilege} ON SCHEMA {qident(schema)} TO {role_sql(principal)}{suffix};"
                )
    if supplement.get("schema_grants"):
        write(out / "75-schema-grants" / "000-schemas.sql", schema_lines)

    # Phase 80: public/application table grants. Built-in storage relation ACLs remain
    # Supabase-managed and are not overwritten by the candidate baseline.
    grants_by_module: dict[str, list[dict[str, Any]]] = {m: [] for m in modules}
    for grant in primary.get("grants", []):
        if grant["schema"] == "storage":
            continue
        relation = f"{grant['schema']}.{grant['table']}"
        grants_by_module[assign_module(relation, "table", manifest)].append(grant)
    for module, rows in grants_by_module.items():
        table_names = sorted(tables_by_module[module])
        if not rows and not table_names:
            continue
        prefix = f"{module_order[module]:03d}-{safe_file(module)}.sql"
        lines = header[:]
        for relation in table_names:
            lines.append(
                f"REVOKE ALL ON TABLE {qname(relation)} FROM PUBLIC, {qident('anon')}, "
                f"{qident('authenticated')}, {qident('service_role')};"
            )
        lines.extend(grouped_grants(rows))
        write(out / "80-table-grants" / prefix, lines)

    # Phase 85: sequence USAGE/SELECT/UPDATE grants captured through information_schema.
    sequence_grants: list[str] = []
    for grant in primary.get("usage_grants", []):
        if str(grant.get("type") or "").upper() != "SEQUENCE":
            continue
        privilege = str(grant.get("privilege") or "").upper()
        if privilege not in {"USAGE", "SELECT", "UPDATE"}:
            continue
        sequence_grants.append(
            f"GRANT {privilege} ON SEQUENCE {qident(grant['schema'])}.{qident(grant['object'])} "
            f"TO {role_sql(grant['grantee'])};"
        )
    if sequence_grants:
        write(out / "85-sequence-grants" / "000-sequences.sql", header[:] + sorted(set(sequence_grants)))

    # Phase 90: explicit captured function ACLs. NULL proacl means PostgreSQL defaults and
    # is deliberately left at its default; explicit ACLs are normalized then replayed.
    function_grants_by_module: dict[str, list[str]] = {m: [] for m in modules}
    for function_grant in supplement.get("function_grants", []):
        acl = function_grant.get("acl")
        if acl is None:
            continue
        full_name = f"{function_grant['schema']}.{function_grant['name']}"
        signature = (
            f"{qident(function_grant['schema'])}.{qident(function_grant['name'])}"
            f"({function_grant.get('identity_arguments', '')})"
        )
        module = assign_module(full_name, "function", manifest)
        function_grants_by_module[module].append(
            f"REVOKE ALL ON FUNCTION {signature} FROM PUBLIC, {qident('anon')}, "
            f"{qident('authenticated')}, {qident('service_role')};"
        )
        for principal, privileges, grantable in parse_acl(acl):
            if "X" not in privileges:
                continue
            suffix = " WITH GRANT OPTION" if "X" in grantable else ""
            function_grants_by_module[module].append(
                f"GRANT EXECUTE ON FUNCTION {signature} TO {role_sql(principal)}{suffix};"
            )
    for module, rows in function_grants_by_module.items():
        if not rows:
            continue
        prefix = f"{module_order[module]:03d}-{safe_file(module)}.sql"
        write(out / "90-function-grants" / prefix, header[:] + sorted(set(rows)))

    # Verification manifest: no raw capture/body copy; only capture hashes, counts and generated file hashes.
    generated = sorted(out.rglob("*.sql"))
    result = {
        "format": "trustweave-d12-candidate-baseline-v1",
        "status": "candidate-until-fresh-parity",
        "apply_order": [str(path.relative_to(out)).replace("\\", "/") for path in generated],
        "server_version": primary.get("server_version"),
        "primary_capture_sha256": hashlib.sha256(args.primary.read_bytes()).hexdigest(),
        "supplement_capture_sha256": hashlib.sha256(args.supplement.read_bytes()).hexdigest() if args.supplement else None,
        "sequence_reconstruction": {
            "captured": len(live_sequences),
            "identity_owned": sorted(identity_sequence_names),
            "owners": {
                name: {"relation": owner[0], "column": owner[1]}
                for name, owner in sorted(sequence_owners.items())
            },
        },
        "bootstrap_functions": [
            f"{fn['name']}({fn.get('identity_arguments', '')})" for fn in bootstrap_functions
        ],
        "security_reconstruction": {
            "schema_acl_source": "supplement.pg_namespace.nspacl",
            "table_grant_source": "primary.information_schema.role_table_grants",
            "sequence_grant_source": "primary.information_schema.usage_privileges",
            "function_acl_source": "supplement.pg_proc.proacl",
            "storage_relation_acl": "Supabase-managed; RLS state and user policies reconstructed, built-in relation ACL not overwritten",
        },
        "object_counts": {
            "relations": len(primary.get("relations", [])),
            "columns": len(primary.get("columns", [])),
            "constraints": len(primary.get("constraints", [])),
            "indexes": len(primary.get("indexes", [])),
            "functions": len(primary.get("functions", [])),
            "triggers": len(primary.get("triggers", [])),
            "policies": len(primary.get("policies", [])),
            "sequences": len(supplement.get("sequences", [])),
        },
        "explicit_source_drift_repairs": [
            "public.set_network_notification_role(text,text,uuid,boolean)",
            "public.remove_network_notification_role(text,uuid)",
        ],
        "files": [
            {"path": str(path.relative_to(out)).replace("\\", "/"), "sha256": sha(path)}
            for path in generated
        ],
    }
    (out / "manifest.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
