-- TRUSTWEAVE D12 CANONICAL CURRENT-STATE BASELINE.
-- Materialized after fresh-project structural/security/API/behavior/product parity on 2026-09-20.
-- DO NOT apply these files to the historical golden project as an upgrade sequence.
-- Historical supabase/migrations/001..123 remain immutable upgrade history.

GRANT EXECUTE ON FUNCTION "public"."accept_network_participation_invitation"(p_token uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."accept_network_participation_invitation"(p_token uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."accept_network_participation_invitation"(p_token uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."accept_network_participation_invitation"(p_token uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."bind_network_media_asset"(p_asset_id uuid, p_entity_type text, p_entity_id text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."bind_network_media_asset"(p_asset_id uuid, p_entity_type text, p_entity_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."bind_network_media_asset"(p_asset_id uuid, p_entity_type text, p_entity_id text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."bind_network_media_asset"(p_asset_id uuid, p_entity_type text, p_entity_id text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."cancel_network_media_asset_delete"(p_asset_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."cancel_network_media_asset_delete"(p_asset_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."cancel_network_media_asset_delete"(p_asset_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."cancel_network_media_asset_delete"(p_asset_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."community_space_is_allowed"(p_space_id uuid, p_network_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."community_space_is_allowed"(p_space_id uuid, p_network_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."community_space_is_allowed"(p_space_id uuid, p_network_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."community_space_is_allowed"(p_space_id uuid, p_network_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."create_network_participation_invitation"(p_network_id uuid, p_email text, p_target_ref uuid, p_target_kind text, p_invited_role text, p_expires_days integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."create_network_participation_invitation"(p_network_id uuid, p_email text, p_target_ref uuid, p_target_kind text, p_invited_role text, p_expires_days integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."create_network_participation_invitation"(p_network_id uuid, p_email text, p_target_ref uuid, p_target_kind text, p_invited_role text, p_expires_days integer) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."create_network_participation_invitation"(p_network_id uuid, p_email text, p_target_ref uuid, p_target_kind text, p_invited_role text, p_expires_days integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."finalize_network_media_asset_delete"(p_asset_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."finalize_network_media_asset_delete"(p_asset_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."finalize_network_media_asset_delete"(p_asset_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."finalize_network_media_asset_delete"(p_asset_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."forget_network_media_asset_by_path"(p_bucket text, p_object_path text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."forget_network_media_asset_by_path"(p_bucket text, p_object_path text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."forget_network_media_asset_by_path"(p_bucket text, p_object_path text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."forget_network_media_asset_by_path"(p_bucket text, p_object_path text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_network_media_assets"(p_entity_type text, p_entity_ids text[]) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_network_media_assets"(p_entity_type text, p_entity_ids text[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_network_media_assets"(p_entity_type text, p_entity_ids text[]) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_network_media_assets"(p_entity_type text, p_entity_ids text[]) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_participation_metrics"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_participation_metrics"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_participation_metrics"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_participation_metrics"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."list_network_participation_invitations"(p_network_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."list_network_participation_invitations"(p_network_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."list_network_participation_invitations"(p_network_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."list_network_participation_invitations"(p_network_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."reconcile_network_media_usage"(p_network_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."reconcile_network_media_usage"(p_network_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."reconcile_network_media_usage"(p_network_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."reconcile_network_media_usage"(p_network_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."register_network_media_asset"(p_bucket text, p_object_path text, p_thumbnail_path text, p_media_kind text, p_entity_type text, p_entity_id text, p_mime_type text, p_bytes bigint, p_thumbnail_bytes bigint, p_width integer, p_height integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."register_network_media_asset"(p_bucket text, p_object_path text, p_thumbnail_path text, p_media_kind text, p_entity_type text, p_entity_id text, p_mime_type text, p_bytes bigint, p_thumbnail_bytes bigint, p_width integer, p_height integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."register_network_media_asset"(p_bucket text, p_object_path text, p_thumbnail_path text, p_media_kind text, p_entity_type text, p_entity_id text, p_mime_type text, p_bytes bigint, p_thumbnail_bytes bigint, p_width integer, p_height integer) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."register_network_media_asset"(p_bucket text, p_object_path text, p_thumbnail_path text, p_media_kind text, p_entity_type text, p_entity_id text, p_mime_type text, p_bytes bigint, p_thumbnail_bytes bigint, p_width integer, p_height integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."request_network_media_asset_delete"(p_asset_id uuid, p_reason text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."request_network_media_asset_delete"(p_asset_id uuid, p_reason text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."request_network_media_asset_delete"(p_asset_id uuid, p_reason text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."request_network_media_asset_delete"(p_asset_id uuid, p_reason text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."resend_network_participation_invitation"(p_network_id uuid, p_invitation_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."resend_network_participation_invitation"(p_network_id uuid, p_invitation_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."resend_network_participation_invitation"(p_network_id uuid, p_invitation_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."resend_network_participation_invitation"(p_network_id uuid, p_invitation_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."revoke_network_participation_invitation"(p_network_id uuid, p_invitation_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."revoke_network_participation_invitation"(p_network_id uuid, p_invitation_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."revoke_network_participation_invitation"(p_network_id uuid, p_invitation_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."revoke_network_participation_invitation"(p_network_id uuid, p_invitation_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."set_network_media_asset_archived"(p_asset_id uuid, p_archived boolean) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."set_network_media_asset_archived"(p_asset_id uuid, p_archived boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."set_network_media_asset_archived"(p_asset_id uuid, p_archived boolean) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."set_network_media_asset_archived"(p_asset_id uuid, p_archived boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."track_public_participation"(p_event_type text, p_public_member_id uuid, p_channel text, p_session_token text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."track_public_participation"(p_event_type text, p_public_member_id uuid, p_channel text, p_session_token text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."track_public_participation"(p_event_type text, p_public_member_id uuid, p_channel text, p_session_token text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."track_public_participation"(p_event_type text, p_public_member_id uuid, p_channel text, p_session_token text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."accept_network_participation_invitation"(p_token uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."bind_network_media_asset"(p_asset_id uuid, p_entity_type text, p_entity_id text) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."cancel_network_media_asset_delete"(p_asset_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."community_space_is_allowed"(p_space_id uuid, p_network_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."create_network_participation_invitation"(p_network_id uuid, p_email text, p_target_ref uuid, p_target_kind text, p_invited_role text, p_expires_days integer) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."finalize_network_media_asset_delete"(p_asset_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."forget_network_media_asset_by_path"(p_bucket text, p_object_path text) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_network_media_assets"(p_entity_type text, p_entity_ids text[]) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_participation_metrics"() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."list_network_participation_invitations"(p_network_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."reconcile_network_media_usage"(p_network_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."register_network_media_asset"(p_bucket text, p_object_path text, p_thumbnail_path text, p_media_kind text, p_entity_type text, p_entity_id text, p_mime_type text, p_bytes bigint, p_thumbnail_bytes bigint, p_width integer, p_height integer) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."request_network_media_asset_delete"(p_asset_id uuid, p_reason text) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."resend_network_participation_invitation"(p_network_id uuid, p_invitation_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."revoke_network_participation_invitation"(p_network_id uuid, p_invitation_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."set_network_media_asset_archived"(p_asset_id uuid, p_archived boolean) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."track_public_participation"(p_event_type text, p_public_member_id uuid, p_channel text, p_session_token text) FROM PUBLIC, "anon", "authenticated", "service_role";
