-- TRUSTWEAVE D12 CANONICAL CURRENT-STATE BASELINE.
-- Materialized after fresh-project structural/security/API/behavior/product parity on 2026-09-20.
-- DO NOT apply these files to the historical golden project as an upgrade sequence.
-- Historical supabase/migrations/001..123 remain immutable upgrade history.

GRANT EXECUTE ON FUNCTION "public"."create_network_notification"(p_network_id uuid, p_user_id uuid, p_type text, p_title text, p_body text, p_surface text, p_entity_type text, p_entity_id uuid, p_priority text, p_metadata jsonb, p_actor_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."create_network_notification"(p_network_id uuid, p_user_id uuid, p_type text, p_title text, p_body text, p_surface text, p_entity_type text, p_entity_id uuid, p_priority text, p_metadata jsonb, p_actor_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."create_network_notification"(p_network_id uuid, p_user_id uuid, p_type text, p_title text, p_body text, p_surface text, p_entity_type text, p_entity_id uuid, p_priority text, p_metadata jsonb, p_actor_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."create_network_notification"(p_network_id uuid, p_user_id uuid, p_type text, p_title text, p_body text, p_surface text, p_entity_type text, p_entity_id uuid, p_priority text, p_metadata jsonb, p_actor_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_my_engagement_notification_preferences"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_my_engagement_notification_preferences"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_engagement_notification_preferences"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_my_engagement_notification_preferences"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_my_notification_preferences"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_my_notification_preferences"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_notification_preferences"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_my_notification_preferences"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_my_notification_unread_count"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_my_notification_unread_count"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_notification_unread_count"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_my_notification_unread_count"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_my_notifications"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_my_notifications"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_notifications"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_my_notifications"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_my_notifications"(p_limit integer, p_unread_only boolean) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_my_notifications"(p_limit integer, p_unread_only boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_notifications"(p_limit integer, p_unread_only boolean) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_my_notifications"(p_limit integer, p_unread_only boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_network_notification_roles"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_network_notification_roles"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_network_notification_roles"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_network_notification_roles"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_notification_preferences"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_notification_preferences"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_notification_preferences"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_notification_preferences"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."mark_all_notifications_read"(p_network_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."mark_all_notifications_read"(p_network_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."mark_all_notifications_read"(p_network_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."mark_all_notifications_read"(p_network_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."mark_notification_read"(p_notification_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."mark_notification_read"(p_notification_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."mark_notification_read"(p_notification_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."mark_notification_read"(p_notification_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."notification_engagement_category"(p_type text, p_metadata jsonb) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."notification_engagement_category"(p_type text, p_metadata jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."notification_engagement_category"(p_type text, p_metadata jsonb) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."notification_engagement_category"(p_type text, p_metadata jsonb) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."notification_engagement_category"(p_type text, p_metadata jsonb) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."remove_network_notification_role"(p_role_key text, p_user_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."remove_network_notification_role"(p_role_key text, p_user_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."remove_network_notification_role"(p_role_key text, p_user_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."save_my_engagement_notification_preferences"(p_push_enabled boolean, p_quiet_start time without time zone, p_quiet_end time without time zone, p_timezone text, p_urgent_bypass_quiet boolean, p_categories jsonb) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."save_my_engagement_notification_preferences"(p_push_enabled boolean, p_quiet_start time without time zone, p_quiet_end time without time zone, p_timezone text, p_urgent_bypass_quiet boolean, p_categories jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."save_my_engagement_notification_preferences"(p_push_enabled boolean, p_quiet_start time without time zone, p_quiet_end time without time zone, p_timezone text, p_urgent_bypass_quiet boolean, p_categories jsonb) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."save_my_engagement_notification_preferences"(p_push_enabled boolean, p_quiet_start time without time zone, p_quiet_end time without time zone, p_timezone text, p_urgent_bypass_quiet boolean, p_categories jsonb) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."save_my_notification_preferences"(p_digest text, p_special_days boolean, p_memories boolean, p_gatherings boolean) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."save_my_notification_preferences"(p_digest text, p_special_days boolean, p_memories boolean, p_gatherings boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."save_my_notification_preferences"(p_digest text, p_special_days boolean, p_memories boolean, p_gatherings boolean) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."save_my_notification_preferences"(p_digest text, p_special_days boolean, p_memories boolean, p_gatherings boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."save_notification_preferences"(p_birthdays boolean, p_anniversaries boolean, p_invitations boolean, p_memories boolean, p_gatherings boolean, p_contributions boolean) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."save_notification_preferences"(p_birthdays boolean, p_anniversaries boolean, p_invitations boolean, p_memories boolean, p_gatherings boolean, p_contributions boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."save_notification_preferences"(p_birthdays boolean, p_anniversaries boolean, p_invitations boolean, p_memories boolean, p_gatherings boolean, p_contributions boolean) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."save_notification_preferences"(p_birthdays boolean, p_anniversaries boolean, p_invitations boolean, p_memories boolean, p_gatherings boolean, p_contributions boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."set_network_notification_role"(p_role_key text, p_label text, p_user_id uuid, p_active boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."set_network_notification_role"(p_role_key text, p_label text, p_user_id uuid, p_active boolean) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."set_network_notification_role"(p_role_key text, p_label text, p_user_id uuid, p_active boolean) TO "service_role";
REVOKE ALL ON FUNCTION "public"."create_network_notification"(p_network_id uuid, p_user_id uuid, p_type text, p_title text, p_body text, p_surface text, p_entity_type text, p_entity_id uuid, p_priority text, p_metadata jsonb, p_actor_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_my_engagement_notification_preferences"() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_my_notification_preferences"() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_my_notification_unread_count"() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_my_notifications"() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_my_notifications"(p_limit integer, p_unread_only boolean) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_network_notification_roles"() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_notification_preferences"() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."mark_all_notifications_read"(p_network_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."mark_notification_read"(p_notification_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."notification_engagement_category"(p_type text, p_metadata jsonb) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."remove_network_notification_role"(p_role_key text, p_user_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."save_my_engagement_notification_preferences"(p_push_enabled boolean, p_quiet_start time without time zone, p_quiet_end time without time zone, p_timezone text, p_urgent_bypass_quiet boolean, p_categories jsonb) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."save_my_notification_preferences"(p_digest text, p_special_days boolean, p_memories boolean, p_gatherings boolean) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."save_notification_preferences"(p_birthdays boolean, p_anniversaries boolean, p_invitations boolean, p_memories boolean, p_gatherings boolean, p_contributions boolean) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."set_network_notification_role"(p_role_key text, p_label text, p_user_id uuid, p_active boolean) FROM PUBLIC, "anon", "authenticated", "service_role";
