-- TRUSTWEAVE D12 CANONICAL CURRENT-STATE BASELINE.
-- Materialized after fresh-project structural/security/API/behavior/product parity on 2026-09-20.
-- DO NOT apply these files to the historical golden project as an upgrade sequence.
-- Historical supabase/migrations/001..123 remain immutable upgrade history.

GRANT EXECUTE ON FUNCTION "public"."create_federation_umbrella"(p_name text, p_slug text, p_umbrella_type text, p_summary text, p_location_label text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."create_federation_umbrella"(p_name text, p_slug text, p_umbrella_type text, p_summary text, p_location_label text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."create_federation_umbrella"(p_name text, p_slug text, p_umbrella_type text, p_summary text, p_location_label text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."create_federation_umbrella"(p_name text, p_slug text, p_umbrella_type text, p_summary text, p_location_label text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_my_federation_umbrellas"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_my_federation_umbrellas"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_federation_umbrellas"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_my_federation_umbrellas"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_my_network_effect_pulse"(p_days integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_my_network_effect_pulse"(p_days integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_network_effect_pulse"(p_days integer) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_my_network_effect_pulse"(p_days integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_my_network_umbrella_affiliations"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_my_network_umbrella_affiliations"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_network_umbrella_affiliations"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_my_network_umbrella_affiliations"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_my_trusted_introductions"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_my_trusted_introductions"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_trusted_introductions"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_my_trusted_introductions"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_my_umbrella_runtime_summaries"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_my_umbrella_runtime_summaries"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_umbrella_runtime_summaries"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_my_umbrella_runtime_summaries"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_umbrella_network_participants"(p_umbrella_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_umbrella_network_participants"(p_umbrella_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_umbrella_network_participants"(p_umbrella_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_umbrella_network_participants"(p_umbrella_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."is_federation_umbrella_admin"(p_umbrella_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."is_federation_umbrella_admin"(p_umbrella_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."is_federation_umbrella_admin"(p_umbrella_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."is_federation_umbrella_admin"(p_umbrella_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."record_network_effect_event"(p_source_network_id uuid, p_bridge_id uuid, p_event_type text, p_event_count integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."record_network_effect_event"(p_source_network_id uuid, p_bridge_id uuid, p_event_type text, p_event_count integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."record_network_effect_event"(p_source_network_id uuid, p_bridge_id uuid, p_event_type text, p_event_count integer) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."record_network_effect_event"(p_source_network_id uuid, p_bridge_id uuid, p_event_type text, p_event_count integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."request_network_umbrella_affiliation"(p_network_id uuid, p_umbrella_slug text, p_relationship_type text, p_context_label text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."request_network_umbrella_affiliation"(p_network_id uuid, p_umbrella_slug text, p_relationship_type text, p_context_label text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."request_network_umbrella_affiliation"(p_network_id uuid, p_umbrella_slug text, p_relationship_type text, p_context_label text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."request_network_umbrella_affiliation"(p_network_id uuid, p_umbrella_slug text, p_relationship_type text, p_context_label text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."request_trusted_introduction"(p_candidate_id uuid, p_message text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."request_trusted_introduction"(p_candidate_id uuid, p_message text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."request_trusted_introduction"(p_candidate_id uuid, p_message text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."request_trusted_introduction"(p_candidate_id uuid, p_message text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."review_network_umbrella_affiliation"(p_affiliation_id uuid, p_approve boolean) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."review_network_umbrella_affiliation"(p_affiliation_id uuid, p_approve boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."review_network_umbrella_affiliation"(p_affiliation_id uuid, p_approve boolean) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."review_network_umbrella_affiliation"(p_affiliation_id uuid, p_approve boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."review_trusted_introduction"(p_introduction_id uuid, p_accept boolean) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."review_trusted_introduction"(p_introduction_id uuid, p_accept boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."review_trusted_introduction"(p_introduction_id uuid, p_accept boolean) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."review_trusted_introduction"(p_introduction_id uuid, p_accept boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."revoke_network_umbrella_affiliation"(p_affiliation_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."revoke_network_umbrella_affiliation"(p_affiliation_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."revoke_network_umbrella_affiliation"(p_affiliation_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."revoke_network_umbrella_affiliation"(p_affiliation_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."search_federation_umbrellas"(p_query text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."search_federation_umbrellas"(p_query text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."search_federation_umbrellas"(p_query text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."search_federation_umbrellas"(p_query text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."suspend_network_umbrella_affiliation"(p_affiliation_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."suspend_network_umbrella_affiliation"(p_affiliation_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."suspend_network_umbrella_affiliation"(p_affiliation_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."suspend_network_umbrella_affiliation"(p_affiliation_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."create_federation_umbrella"(p_name text, p_slug text, p_umbrella_type text, p_summary text, p_location_label text) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_my_federation_umbrellas"() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_my_network_effect_pulse"(p_days integer) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_my_network_umbrella_affiliations"() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_my_trusted_introductions"() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_my_umbrella_runtime_summaries"() FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_umbrella_network_participants"(p_umbrella_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."is_federation_umbrella_admin"(p_umbrella_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."record_network_effect_event"(p_source_network_id uuid, p_bridge_id uuid, p_event_type text, p_event_count integer) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."request_network_umbrella_affiliation"(p_network_id uuid, p_umbrella_slug text, p_relationship_type text, p_context_label text) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."request_trusted_introduction"(p_candidate_id uuid, p_message text) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."review_network_umbrella_affiliation"(p_affiliation_id uuid, p_approve boolean) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."review_trusted_introduction"(p_introduction_id uuid, p_accept boolean) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."revoke_network_umbrella_affiliation"(p_affiliation_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."search_federation_umbrellas"(p_query text) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."suspend_network_umbrella_affiliation"(p_affiliation_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
