-- TRUSTWEAVE D12 CANONICAL CURRENT-STATE BASELINE.
-- Materialized after fresh-project structural/security/API/behavior/product parity on 2026-09-20.
-- DO NOT apply these files to the historical golden project as an upgrade sequence.
-- Historical supabase/migrations/001..123 remain immutable upgrade history.

GRANT EXECUTE ON FUNCTION "public"."clear_memory_reaction"(p_memory_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."clear_memory_reaction"(p_memory_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."clear_memory_reaction"(p_memory_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."clear_memory_reaction"(p_memory_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."create_member_life_event"(p_member_id uuid, p_event_type character varying, p_title character varying, p_event_date date, p_location character varying, p_description text, p_visibility character varying) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."create_member_life_event"(p_member_id uuid, p_event_type character varying, p_title character varying, p_event_date date, p_location character varying, p_description text, p_visibility character varying) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."create_member_life_event"(p_member_id uuid, p_event_type character varying, p_title character varying, p_event_date date, p_location character varying, p_description text, p_visibility character varying) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."create_member_life_event"(p_member_id uuid, p_event_type character varying, p_title character varying, p_event_date date, p_location character varying, p_description text, p_visibility character varying) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."create_memory"(p_member_id uuid, p_title character varying, p_story text, p_photo_url text, p_visibility character varying) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."create_memory"(p_member_id uuid, p_title character varying, p_story text, p_photo_url text, p_visibility character varying) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."create_memory"(p_member_id uuid, p_title character varying, p_story text, p_photo_url text, p_visibility character varying) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."create_memory"(p_member_id uuid, p_title character varying, p_story text, p_photo_url text, p_visibility character varying) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."delete_member_life_event"(p_event_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."delete_member_life_event"(p_event_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."delete_member_life_event"(p_event_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."delete_member_life_event"(p_event_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."delete_memory"(p_memory_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."delete_memory"(p_memory_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."delete_memory"(p_memory_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."delete_memory"(p_memory_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_member_life_events"(p_member_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_member_life_events"(p_member_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_member_life_events"(p_member_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_member_life_events"(p_member_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_memory_people"(p_memory_ids uuid[]) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_memory_people"(p_memory_ids uuid[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_memory_people"(p_memory_ids uuid[]) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_memory_people"(p_memory_ids uuid[]) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_memory_reactions"(p_memory_ids uuid[]) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_memory_reactions"(p_memory_ids uuid[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_memory_reactions"(p_memory_ids uuid[]) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_memory_reactions"(p_memory_ids uuid[]) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."link_memory_to_event"(p_memory_id uuid, p_event_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."link_memory_to_event"(p_memory_id uuid, p_event_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."link_memory_to_event"(p_memory_id uuid, p_event_id uuid) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."link_memory_to_event"(p_memory_id uuid, p_event_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."review_profile_submission"(p_submission_id uuid, p_status character varying, p_review_note text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."review_profile_submission"(p_submission_id uuid, p_status character varying, p_review_note text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."review_profile_submission"(p_submission_id uuid, p_status character varying, p_review_note text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."review_profile_submission"(p_submission_id uuid, p_status character varying, p_review_note text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."set_memory_people"(p_memory_id uuid, p_member_ids uuid[]) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."set_memory_people"(p_memory_id uuid, p_member_ids uuid[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."set_memory_people"(p_memory_id uuid, p_member_ids uuid[]) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."set_memory_people"(p_memory_id uuid, p_member_ids uuid[]) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."set_memory_reaction"(p_memory_id uuid, p_reaction text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."set_memory_reaction"(p_memory_id uuid, p_reaction text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."set_memory_reaction"(p_memory_id uuid, p_reaction text) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."set_memory_reaction"(p_memory_id uuid, p_reaction text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."update_member_life_event"(p_event_id uuid, p_event_type character varying, p_title character varying, p_event_date date, p_location character varying, p_description text, p_visibility character varying) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."update_member_life_event"(p_event_id uuid, p_event_type character varying, p_title character varying, p_event_date date, p_location character varying, p_description text, p_visibility character varying) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."update_member_life_event"(p_event_id uuid, p_event_type character varying, p_title character varying, p_event_date date, p_location character varying, p_description text, p_visibility character varying) TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."update_member_life_event"(p_event_id uuid, p_event_type character varying, p_title character varying, p_event_date date, p_location character varying, p_description text, p_visibility character varying) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."validate_profile_submission_media"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."validate_profile_submission_media"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."validate_profile_submission_media"() TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."validate_profile_submission_media"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."validate_profile_submission_media"() TO PUBLIC;
REVOKE ALL ON FUNCTION "public"."clear_memory_reaction"(p_memory_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."create_member_life_event"(p_member_id uuid, p_event_type character varying, p_title character varying, p_event_date date, p_location character varying, p_description text, p_visibility character varying) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."create_memory"(p_member_id uuid, p_title character varying, p_story text, p_photo_url text, p_visibility character varying) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."delete_member_life_event"(p_event_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."delete_memory"(p_memory_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_member_life_events"(p_member_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_memory_people"(p_memory_ids uuid[]) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."get_memory_reactions"(p_memory_ids uuid[]) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."link_memory_to_event"(p_memory_id uuid, p_event_id uuid) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."review_profile_submission"(p_submission_id uuid, p_status character varying, p_review_note text) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."set_memory_people"(p_memory_id uuid, p_member_ids uuid[]) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."set_memory_reaction"(p_memory_id uuid, p_reaction text) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."update_member_life_event"(p_event_id uuid, p_event_type character varying, p_title character varying, p_event_date date, p_location character varying, p_description text, p_visibility character varying) FROM PUBLIC, "anon", "authenticated", "service_role";
REVOKE ALL ON FUNCTION "public"."validate_profile_submission_media"() FROM PUBLIC, "anon", "authenticated", "service_role";
