import {test,expect} from '@playwright/test';
import {createClient} from '@supabase/supabase-js';
import {authenticatedClient,activate,seedState} from '../lib/role-client';
import {login} from '../lib/login';
const png=Uint8Array.from([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,1,0,0,0,1,8,6,0,0,0,31,21,196,137,0,0,0,13,73,68,65,84,8,215,99,248,207,192,240,31,0,5,0,1,255,137,153,61,29,0,0,0,0,73,69,78,68,174,66,96,130]);
const service=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}});

test.describe('Phase-5C production release-candidate gate',()=>{
 test('health/readiness and anonymous protected-route denial are release-safe',async({request})=>{for(const p of ['/api/health','/api/ready']){const r=await request.get(p);expect([200,503]).toContain(r.status());expect((r.headers()['content-type']||'')).toContain('application/json');await r.json()}const denied=await request.post('/api/v1/networks/create',{headers:{'idempotency-key':crypto.randomUUID()},data:{kind:'organization',name:'anonymous should never create'}});expect([400,401,403,404]).toContain(denied.status());expect(denied.status()).not.toBe(500)});
 test('final owner/admin/member browser boundary and Tenant-B isolation hold',async({browser,request})=>{const s=seedState();for(const role of ['owner','admin','member'] as const){await activate(role,s.networks.organization.id);const page=await browser.newPage();try{await login(page,role);await expect(page.getByTestId('qa-vertical-shell-organization')).toBeVisible();const admin=page.getByTestId('qa-nav-admin');if(role==='member')await expect(admin).toHaveCount(0);else await expect(admin).toBeVisible()}finally{await page.close()}}const owner=await authenticatedClient('owner');const cross=await request.get(`/api/v1/networks/${s.tenantB.id}/export`,{headers:{authorization:`Bearer ${owner.token}`}});expect([401,403,404]).toContain(cross.status())});
 test('invitation expiry, resend rotation, replay denial and revoke are enforced',async()=>{const s=seedState(),svc=service(),owner=await authenticatedClient('owner'),invitee=await authenticatedClient('invitee'),family=s.networks.family.id,email=s.users.invitee.email;await svc.from('network_memberships').delete().eq('network_id',family).eq('user_id',s.users.invitee.id);await svc.from('network_participation_invitations').delete().eq('network_id',family).eq('email',email);try{const expired=await owner.client.rpc('create_network_participation_invitation',{p_network_id:family,p_email:email,p_target_ref:null,p_target_kind:null,p_invited_role:'member',p_expires_days:14});expect(expired.error).toBeNull();expect(expired.data?.id).toBeTruthy();await svc.from('network_participation_invitations').update({expires_at:new Date(Date.now()-60_000).toISOString()}).eq('id',expired.data.id);expect((await invitee.client.rpc('accept_network_participation_invitation',{p_token:expired.data.token})).error).toBeTruthy();await svc.from('network_participation_invitations').delete().eq('id',expired.data.id);const fresh=await owner.client.rpc('create_network_participation_invitation',{p_network_id:family,p_email:email,p_target_ref:null,p_target_kind:null,p_invited_role:'member',p_expires_days:14});expect(fresh.error).toBeNull();const old=fresh.data.token;const resend=await owner.client.rpc('resend_network_participation_invitation',{p_network_id:family,p_invitation_id:fresh.data.id});expect(resend.error).toBeNull();expect(resend.data?.token).not.toBe(old);expect((await invitee.client.rpc('accept_network_participation_invitation',{p_token:old})).error).toBeTruthy();expect((await invitee.client.rpc('accept_network_participation_invitation',{p_token:resend.data.token})).error).toBeNull();expect((await invitee.client.rpc('accept_network_participation_invitation',{p_token:resend.data.token})).error).toBeTruthy();await svc.from('network_memberships').delete().eq('network_id',family).eq('user_id',s.users.invitee.id);const revoked=await owner.client.rpc('create_network_participation_invitation',{p_network_id:family,p_email:email,p_target_ref:null,p_target_kind:null,p_invited_role:'member',p_expires_days:14});expect(revoked.error).toBeNull();expect((await owner.client.rpc('revoke_network_participation_invitation',{p_network_id:family,p_invitation_id:revoked.data.id})).error).toBeNull();expect((await invitee.client.rpc('accept_network_participation_invitation',{p_token:revoked.data.token})).error).toBeTruthy()}finally{await svc.from('network_memberships').delete().eq('network_id',family).eq('user_id',s.users.invitee.id);await svc.from('network_participation_invitations').delete().eq('network_id',family).eq('email',email);await svc.from('profiles').update({active_network_id:null}).eq('id',s.users.invitee.id)}});
 test('private media signed-URL generation is limited to the target network membership',async()=>{const s=seedState(),owner=await authenticatedClient('owner'),member=await authenticatedClient('member'),tenantB=await authenticatedClient('tenantB');await activate('owner',s.networks.organization.id);await activate('member',s.networks.organization.id);const path=`${s.networks.organization.id}/community/${owner.userId}/phase5c-${Date.now()}.png`;try{const upload=await owner.client.storage.from('community-media').upload(path,png,{contentType:'image/png'});expect(upload.error).toBeNull();const os=await owner.client.storage.from('community-media').createSignedUrl(path,60);expect(os.error).toBeNull();expect(os.data?.signedUrl).toBeTruthy();const ms=await member.client.storage.from('community-media').createSignedUrl(path,60);expect(ms.error).toBeNull();expect(ms.data?.signedUrl).toBeTruthy();const tb=await tenantB.client.storage.from('community-media').createSignedUrl(path,60);expect(tb.error).toBeTruthy();const anon=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{auth:{persistSession:false,autoRefreshToken:false}});expect((await anon.storage.from('community-media').createSignedUrl(path,60)).error).toBeTruthy()}finally{try{await owner.client.storage.from('community-media').remove([path])}catch{}}});
 test('release backup remains logical/portable and member export stays denied',async({request})=>{const s=seedState();await activate('owner',s.networks.organization.id);const owner=await authenticatedClient('owner'),member=await authenticatedClient('member');const ok=await request.get(`/api/v1/networks/${s.networks.organization.id}/export`,{headers:{authorization:`Bearer ${owner.token}`}});expect(ok.status()).toBe(200);const j=await ok.json();expect(j.ok).toBeTruthy();expect(j.data?.networkId).toBe(s.networks.organization.id);expect(j.data?.media?.strategy).toBe('manifest');expect(j.data?.media?.contentIncluded).toBe(false);const denied=await request.get(`/api/v1/networks/${s.networks.organization.id}/export`,{headers:{authorization:`Bearer ${member.token}`}});expect([401,403]).toContain(denied.status())});
});
