import {test,expect} from '@playwright/test';import {assertMutationAllowed} from '../lib/safety';import {authenticatedClient} from '../lib/role-client';
test('institutional bootstrap certifies 100-row volume, pagination/search and idempotency',async({request})=>{
 test.skip(process.env.QA_MODE!=='staging'||process.env.QA_ALLOW_MUTATION!=='true','staging mutation suite');assertMutationAllowed();const a=await authenticatedClient('owner'),suffix=Date.now(),name=`QA Volume ${suffix}`,createKey=crypto.randomUUID();
 const c=await request.post('/api/v1/networks/create',{headers:{authorization:`Bearer ${a.token}`,'idempotency-key':createKey},data:{kind:'organization',name,contextValue:'Volume QA'}});expect(c.status()).toBe(201);const cj=await c.json(),id=cj.data?.networkId||cj.data?.id||cj.networkId;expect((await a.client.rpc('set_active_network',{p_network_id:id})).error).toBeNull();
 try{
  const rows=Array.from({length:100},(_,i)=>({kind:'person',label:`Volume Person ${suffix}-${String(i).padStart(3,'0')}`,metadata:{qa:true,index:i,city:i%2?'Pune':'Mumbai'}})),key=crypto.randomUUID(),h={authorization:`Bearer ${a.token}`,'idempotency-key':key};
  const one=await request.post('/api/v1/institutional/bootstrap',{headers:h,data:{rows}}),two=await request.post('/api/v1/institutional/bootstrap',{headers:h,data:{rows}});expect([200,201]).toContain(one.status());expect(two.status()).toBe(one.status());
  const governed=await a.client.rpc('get_network_affiliated_entities');expect(governed.error).toBeNull();const people=(governed.data||[]).filter((e:any)=>e.entity_kind==='person'&&String(e.entity_label||'').startsWith(`Volume Person ${suffix}-`)).sort((x:any,y:any)=>String(x.entity_label).localeCompare(String(y.entity_label)));expect(people.length).toBe(100);
  const page1=people.slice(0,25),page2=people.slice(25,50);expect(page1.length).toBe(25);expect(page2.length).toBe(25);expect(new Set([...page1,...page2].map((x:any)=>x.entity_id)).size).toBe(50);
  const search=people.filter((e:any)=>String(e.entity_label||'').toLowerCase().includes(`${suffix}-09`.toLowerCase()));expect(search.length).toBeGreaterThan(0);
  if(process.env.QA_RUN_LARGE_VOLUME==='true'){for(let batch=0;batch<2;batch++){const large=Array.from({length:500},(_,i)=>({kind:'person',label:`Large ${suffix}-${batch}-${i}`,metadata:{batch,i}}));const r=await request.post('/api/v1/institutional/bootstrap',{headers:{authorization:`Bearer ${a.token}`,'idempotency-key':crypto.randomUUID()},data:{rows:large}});expect([200,201]).toContain(r.status())}}
 }finally{await request.post(`/api/v1/networks/${id}/purge`,{headers:{authorization:`Bearer ${a.token}`},data:{confirmName:name}})}
});
