import {supabase} from "../../lib/supabase";import type {InvitationDelivery,NetworkParticipationInvitation} from "../../core/participation/contracts";
function required(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}
async function token(){const {data:{session},error}=await required().auth.getSession();if(error)throw error;if(!session?.access_token)throw new Error("Please sign in.");return session.access_token}
export async function listNetworkInvitations(networkId:string):Promise<NetworkParticipationInvitation[]>{const {data,error}=await required().rpc("list_network_participation_invitations",{p_network_id:networkId});if(error)throw error;return (data||[]).map((x:any)=>({id:String(x.id),email:String(x.email),targetRef:x.target_ref?String(x.target_ref):undefined,targetKind:x.target_kind||undefined,invitedRole:x.invited_role,status:x.status,expiresAt:String(x.expires_at),createdAt:String(x.created_at),resendCount:Number(x.resend_count||0)}))}
async function command(networkId:string,body:Record<string,unknown>){const r=await fetch(`/api/v1/networks/${encodeURIComponent(networkId)}/invitations`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${await token()}`},body:JSON.stringify(body)}),p=await r.json();if(!r.ok||!p?.ok)throw new Error(p?.error?.message||"Invitation action failed.");return p.data as InvitationDelivery}
export const createNetworkInvitation=(networkId:string,email:string,targetRef?:string)=>command(networkId,{action:"create",email,targetRef,targetKind:targetRef?"network_entity":undefined});
export const resendNetworkInvitation=(networkId:string,invitationId:string)=>command(networkId,{action:"resend",invitationId});
export async function revokeNetworkInvitation(networkId:string,invitationId:string){const {error}=await required().rpc("revoke_network_participation_invitation",{p_network_id:networkId,p_invitation_id:invitationId});if(error)throw error}
export async function acceptNetworkInvitation(inviteToken:string){const {data,error}=await required().rpc("accept_network_participation_invitation",{p_token:inviteToken});if(error)throw error;return String(data)}
