import {supabase} from "../../lib/supabase";
function required(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}
export type BallotOption={id:string;label:string;description?:string|null;candidate_entity_id?:string|null;votes?:number|null};
export type BallotNomination={id:string;nominee_entity_id:string;nominee_label:string;statement?:string|null;status:string;nominated_by_me:boolean};
export type NetworkBallot={id:string;ballot_type:"poll"|"election";title:string;description?:string|null;status:string;eligibility_mode:string;max_choices:number;secret_ballot:boolean;allow_nominations:boolean;opens_at?:string|null;closes_at?:string|null;eligible_count:number;participation_count:number;has_voted:boolean;can_vote:boolean;options:BallotOption[];nominations:BallotNomination[]};
export type BallotsSnapshot={is_admin:boolean;people:{id:string;label:string}[];ballots:NetworkBallot[]};
export async function fetchNetworkBallots(){const s=required();const {data,error}=await s.rpc("get_network_ballots_snapshot");if(error)throw error;const d=(data||{}) as any;return {is_admin:Boolean(d.is_admin),people:d.people||[],ballots:d.ballots||[]} as BallotsSnapshot}
export async function saveNetworkBallot(input:{id?:string|null;ballotType:string;title:string;description?:string;eligibilityMode:string;maxChoices:number;secretBallot:boolean;allowNominations:boolean;opensAt?:string|null;closesAt?:string|null}){const s=required();const {data,error}=await s.rpc("upsert_network_ballot",{p_id:input.id||null,p_ballot_type:input.ballotType,p_title:input.title,p_description:input.description||null,p_eligibility_mode:input.eligibilityMode,p_max_choices:input.maxChoices,p_secret_ballot:input.secretBallot,p_allow_nominations:input.allowNominations,p_opens_at:input.opensAt||null,p_closes_at:input.closesAt||null});if(error)throw error;return String(data)}
export async function addBallotOption(ballotId:string,label:string,description="",candidateEntityId?:string|null){const s=required();const {data,error}=await s.rpc("add_network_ballot_option",{p_ballot_id:ballotId,p_label:label,p_description:description||null,p_candidate_entity_id:candidateEntityId||null});if(error)throw error;return String(data)}
export async function submitBallotNomination(ballotId:string,nomineeEntityId:string,statement=""){const s=required();const {data,error}=await s.rpc("submit_network_ballot_nomination",{p_ballot_id:ballotId,p_nominee_entity_id:nomineeEntityId,p_statement:statement||null});if(error)throw error;return String(data)}
export async function reviewBallotNomination(id:string,action:"approved"|"rejected"){const s=required();const {error}=await s.rpc("review_network_ballot_nomination",{p_nomination_id:id,p_action:action});if(error)throw error}
export async function openNetworkBallot(id:string){const s=required();const {data,error}=await s.rpc("open_network_ballot",{p_ballot_id:id});if(error)throw error;return Number(data||0)}
export async function castNetworkBallotVote(id:string,optionIds:string[]){const s=required();const {data,error}=await s.rpc("cast_network_ballot_vote",{p_ballot_id:id,p_option_ids:optionIds});if(error)throw error;return String(data)}
export async function closeNetworkBallot(id:string){const s=required();const {error}=await s.rpc("close_network_ballot",{p_ballot_id:id});if(error)throw error}
export async function publishNetworkBallotResults(id:string){const s=required();const {error}=await s.rpc("publish_network_ballot_results",{p_ballot_id:id});if(error)throw error}
