-- M7-C — Guided Pilot & Admin Launch Console
create or replace function public.get_my_pilot_launch_console()
returns table(network_id uuid,network_name varchar,vertical_kind varchar,role varchar,seeded_items bigint,active_members bigint,claimed_identities bigint,accepted_bridges bigint,discovery_searches_30d bigint,introduction_requests_30d bigint,accepted_introductions_30d bigint,last_activity_at timestamptz,age_days integer)
language sql security definer stable set search_path=public as $$
 with mine as(select n.id,n.name,n.vertical_kind,n.created_at,nm.role from public.network_memberships nm join public.networks n on n.id=nm.network_id where nm.user_id=auth.uid() and nm.status='active' and nm.role in ('owner','admin') and n.status='active'),events as(select e.source_network_id,coalesce(sum(e.event_count) filter(where e.event_type='discovery_search' and e.created_at>=now()-interval '30 days'),0)::bigint discovery_searches,coalesce(sum(e.event_count) filter(where e.event_type='introduction_requested' and e.created_at>=now()-interval '30 days'),0)::bigint introduction_requests,coalesce(sum(e.event_count) filter(where e.event_type='introduction_accepted' and e.created_at>=now()-interval '30 days'),0)::bigint accepted_introductions,max(e.created_at) last_event_at from public.network_effect_events e join mine m on m.id=e.source_network_id group by e.source_network_id)
 select m.id,m.name,m.vertical_kind,m.role,case when m.vertical_kind='family' then (select count(*) from public.family_members fm where fm.network_id=m.id and fm.profile_status='approved') when m.vertical_kind='alumni' then (select count(*) from public.alumni_profiles ap where ap.network_id=m.id) else (select count(*) from public.network_entities ne where ne.network_id=m.id) end,(select count(*) from public.network_memberships nm where nm.network_id=m.id and nm.status='active'),case when m.vertical_kind='family' then (select count(*) from public.network_memberships nm where nm.network_id=m.id and nm.status='active' and nm.member_id is not null) when m.vertical_kind='alumni' then (select count(*) from public.alumni_profiles ap where ap.network_id=m.id and ap.claimed_by is not null) else (select count(*) from public.network_entities ne where ne.network_id=m.id and ne.owner_user_id is not null) end,(select count(*) from public.network_trust_bridges b where b.status='accepted' and m.id in(b.requester_network_id,b.recipient_network_id)),coalesce(ev.discovery_searches,0),coalesce(ev.introduction_requests,0),coalesce(ev.accepted_introductions,0),greatest(m.created_at,coalesce((select max(nm.joined_at) from public.network_memberships nm where nm.network_id=m.id),m.created_at),coalesce(ev.last_event_at,m.created_at)),greatest(0,floor(extract(epoch from(now()-m.created_at))/86400))::integer from mine m left join events ev on ev.source_network_id=m.id order by m.name;
$$;
revoke all on function public.get_my_pilot_launch_console() from public;
grant execute on function public.get_my_pilot_launch_console() to authenticated;
comment on function public.get_my_pilot_launch_console() is 'M7-C admin-scoped pilot portfolio snapshot. Aggregate counts/activity only; no cross-network identities, search text or member directory exposure.';
