-- HS-5 — Security, Compliance & Asset Operations
-- Additive + rerunnable. Security operators receive scoped operational access, not network-admin rights.

create table if not exists public.hs_security_operator_grants(
 id uuid primary key default gen_random_uuid(),network_id uuid not null references public.networks(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,
 scope varchar(30) not null default 'security' check(scope in ('security','facility','compliance')),active boolean not null default true,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(network_id,user_id,scope)
);
create table if not exists public.hs_visitors(
 id uuid primary key default gen_random_uuid(),network_id uuid not null references public.networks(id) on delete cascade,unit_entity_id uuid not null references public.network_entities(id) on delete cascade,
 visitor_name varchar(180) not null,phone varchar(40),visit_type varchar(24) not null default 'guest' check(visit_type in ('guest','delivery','service','cab','other')),purpose varchar(220),vehicle_number varchar(40),
 expected_at timestamptz,entered_at timestamptz,exited_at timestamptz,status varchar(20) not null default 'expected' check(status in ('expected','inside','exited','cancelled','denied')),
 created_by uuid references auth.users(id) on delete set null,checked_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create index if not exists idx_hs_visitors_network_status on public.hs_visitors(network_id,status,coalesce(expected_at,created_at) desc);

create table if not exists public.hs_domestic_staff(
 id uuid primary key default gen_random_uuid(),network_id uuid not null references public.networks(id) on delete cascade,name varchar(180) not null,
 staff_type varchar(24) not null default 'other' check(staff_type in ('maid','driver','cook','nanny','caregiver','cleaner','other')),phone varchar(40),identity_last4 varchar(8),verification_status varchar(20) not null default 'pending' check(verification_status in ('pending','verified','expired','rejected')),active boolean not null default true,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.hs_staff_unit_permissions(
 id uuid primary key default gen_random_uuid(),network_id uuid not null references public.networks(id) on delete cascade,staff_id uuid not null references public.hs_domestic_staff(id) on delete cascade,unit_entity_id uuid not null references public.network_entities(id) on delete cascade,starts_on date not null default current_date,ends_on date,status varchar(20) not null default 'active' check(status in ('active','revoked','expired')),created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),check(ends_on is null or ends_on>=starts_on)
);
create index if not exists idx_hs_staff_permissions on public.hs_staff_unit_permissions(network_id,unit_entity_id,status);

create table if not exists public.hs_move_requests(
 id uuid primary key default gen_random_uuid(),network_id uuid not null references public.networks(id) on delete cascade,unit_entity_id uuid not null references public.network_entities(id) on delete cascade,
 move_type varchar(16) not null check(move_type in ('move_in','move_out')),scheduled_on date not null,contact_name varchar(180),notes text,status varchar(20) not null default 'requested' check(status in ('requested','approved','rejected','completed','cancelled')),review_note text,created_by uuid references auth.users(id) on delete set null,reviewed_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.hs_renovation_requests(
 id uuid primary key default gen_random_uuid(),network_id uuid not null references public.networks(id) on delete cascade,unit_entity_id uuid not null references public.network_entities(id) on delete cascade,title varchar(220) not null,description text,contractor_name varchar(180),starts_on date,ends_on date,status varchar(20) not null default 'requested' check(status in ('requested','approved','rejected','in_progress','completed','cancelled')),noc_reference varchar(120),conditions text,created_by uuid references auth.users(id) on delete set null,reviewed_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_on is null or starts_on is null or ends_on>=starts_on)
);

create table if not exists public.hs_assets(
 id uuid primary key default gen_random_uuid(),network_id uuid not null references public.networks(id) on delete cascade,asset_code varchar(80) not null,name varchar(180) not null,category varchar(60) not null,location varchar(180),status varchar(20) not null default 'active' check(status in ('active','maintenance','inactive','retired')),commissioned_on date,warranty_until date,vendor_id uuid references public.hs_vendors(id) on delete set null,metadata jsonb not null default '{}'::jsonb,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(network_id,asset_code)
);
create table if not exists public.hs_asset_service_records(
 id uuid primary key default gen_random_uuid(),network_id uuid not null references public.networks(id) on delete cascade,asset_id uuid not null references public.hs_assets(id) on delete cascade,service_type varchar(80) not null,serviced_on date not null default current_date,next_due_on date,vendor_id uuid references public.hs_vendors(id) on delete set null,notes text,cost numeric(14,2),created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now()
);
create index if not exists idx_hs_asset_service_due on public.hs_asset_service_records(network_id,next_due_on);

create table if not exists public.hs_compliance_items(
 id uuid primary key default gen_random_uuid(),network_id uuid not null references public.networks(id) on delete cascade,category varchar(80) not null,title varchar(220) not null,due_on date,status varchar(20) not null default 'open' check(status in ('open','renewed','completed','expired','not_applicable')),owner_label varchar(160),document_url text,visibility varchar(20) not null default 'members' check(visibility in ('admin','members')),notes text,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create index if not exists idx_hs_compliance_due on public.hs_compliance_items(network_id,status,due_on);
create table if not exists public.hs_emergency_contacts(
 id uuid primary key default gen_random_uuid(),network_id uuid not null references public.networks(id) on delete cascade,category varchar(60) not null,label varchar(180) not null,phone varchar(60) not null,notes varchar(240),priority integer not null default 100,active boolean not null default true,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(network_id,category,label)
);

alter table public.hs_security_operator_grants enable row level security;alter table public.hs_visitors enable row level security;alter table public.hs_domestic_staff enable row level security;alter table public.hs_staff_unit_permissions enable row level security;alter table public.hs_move_requests enable row level security;alter table public.hs_renovation_requests enable row level security;alter table public.hs_assets enable row level security;alter table public.hs_asset_service_records enable row level security;alter table public.hs_compliance_items enable row level security;alter table public.hs_emergency_contacts enable row level security;

create or replace function public.hs5_is_operator(p_network_id uuid,p_scope text default 'security') returns boolean language sql security definer stable set search_path=public as $$select public.is_network_admin(p_network_id) or exists(select 1 from public.hs_security_operator_grants g where g.network_id=p_network_id and g.user_id=auth.uid() and g.active and (g.scope=p_scope or (p_scope='security' and g.scope='facility')))$$;
revoke all on function public.hs5_is_operator(uuid,text) from public;grant execute on function public.hs5_is_operator(uuid,text) to authenticated;

do $$ begin
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='hs_security_operator_grants' and policyname='hs_security_grants_admin_read') then create policy hs_security_grants_admin_read on public.hs_security_operator_grants for select using(public.is_network_admin(network_id)); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='hs_visitors' and policyname='hs_visitors_scoped_read') then create policy hs_visitors_scoped_read on public.hs_visitors for select using(public.hs5_is_operator(network_id,'security') or exists(select 1 from public.hs_unit_occupancy_history o join public.network_entities p on p.id=o.subject_entity_id where o.network_id=hs_visitors.network_id and o.unit_entity_id=hs_visitors.unit_entity_id and o.ends_on is null and p.owner_user_id=auth.uid())); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='hs_domestic_staff' and policyname='hs_staff_operator_read') then create policy hs_staff_operator_read on public.hs_domestic_staff for select using(public.hs5_is_operator(network_id,'security')); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='hs_staff_unit_permissions' and policyname='hs_staff_permissions_scoped_read') then create policy hs_staff_permissions_scoped_read on public.hs_staff_unit_permissions for select using(public.hs5_is_operator(network_id,'security') or exists(select 1 from public.hs_unit_occupancy_history o join public.network_entities p on p.id=o.subject_entity_id where o.network_id=hs_staff_unit_permissions.network_id and o.unit_entity_id=hs_staff_unit_permissions.unit_entity_id and o.ends_on is null and p.owner_user_id=auth.uid())); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='hs_move_requests' and policyname='hs_move_requests_scoped_read') then create policy hs_move_requests_scoped_read on public.hs_move_requests for select using(public.is_network_admin(network_id) or exists(select 1 from public.hs_unit_occupancy_history o join public.network_entities p on p.id=o.subject_entity_id where o.network_id=hs_move_requests.network_id and o.unit_entity_id=hs_move_requests.unit_entity_id and o.ends_on is null and p.owner_user_id=auth.uid())); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='hs_renovation_requests' and policyname='hs_renovation_scoped_read') then create policy hs_renovation_scoped_read on public.hs_renovation_requests for select using(public.is_network_admin(network_id) or exists(select 1 from public.hs_unit_occupancy_history o join public.network_entities p on p.id=o.subject_entity_id where o.network_id=hs_renovation_requests.network_id and o.unit_entity_id=hs_renovation_requests.unit_entity_id and o.ends_on is null and p.owner_user_id=auth.uid())); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='hs_assets' and policyname='hs_assets_member_read') then create policy hs_assets_member_read on public.hs_assets for select using(public.is_network_member(network_id)); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='hs_asset_service_records' and policyname='hs_asset_service_member_read') then create policy hs_asset_service_member_read on public.hs_asset_service_records for select using(public.is_network_member(network_id)); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='hs_compliance_items' and policyname='hs_compliance_visibility_read') then create policy hs_compliance_visibility_read on public.hs_compliance_items for select using(public.is_network_admin(network_id) or (visibility='members' and public.is_network_member(network_id))); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='hs_emergency_contacts' and policyname='hs_emergency_member_read') then create policy hs_emergency_member_read on public.hs_emergency_contacts for select using(public.is_network_member(network_id)); end if;
end $$;

create or replace function public.hs5_assert_network() returns uuid language plpgsql security definer stable set search_path=public as $$declare nid uuid:=public.current_network_id();begin if nid is null or not public.is_network_member(nid) then raise exception 'Housing Society membership required.' using errcode='42501';end if;if coalesce((select vertical_kind from public.networks where id=nid),'')<>'housing-society' then raise exception 'HS-5 is available only for housing-society networks.' using errcode='22023';end if;return nid;end $$;
revoke all on function public.hs5_assert_network() from public;grant execute on function public.hs5_assert_network() to authenticated;

create or replace function public.hs5_get_snapshot() returns jsonb language plpgsql security definer stable set search_path=public as $$
declare nid uuid:=public.hs5_assert_network(); isadm boolean:=public.is_network_admin(nid); issec boolean:=public.hs5_is_operator(nid,'security');
begin return jsonb_build_object(
 'isSecurityOperator',issec,
 'visitors',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'unitEntityId',v.unit_entity_id,'unitLabel',u.label,'visitorName',v.visitor_name,'phone',case when issec then v.phone else null end,'visitType',v.visit_type,'purpose',v.purpose,'vehicleNumber',v.vehicle_number,'expectedAt',v.expected_at,'enteredAt',v.entered_at,'exitedAt',v.exited_at,'status',v.status) order by coalesce(v.expected_at,v.created_at) desc) from public.hs_visitors v join public.network_entities u on u.id=v.unit_entity_id where v.network_id=nid and (issec or exists(select 1 from public.hs_unit_occupancy_history o join public.network_entities p on p.id=o.subject_entity_id where o.network_id=nid and o.unit_entity_id=v.unit_entity_id and o.ends_on is null and p.owner_user_id=auth.uid())) and v.created_at>now()-interval '30 days'),'[]'::jsonb),
 'staff',case when issec then coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'name',s.name,'staffType',s.staff_type,'phone',s.phone,'identityLast4',s.identity_last4,'verificationStatus',s.verification_status,'active',s.active,'units',coalesce((select jsonb_agg(jsonb_build_object('permissionId',p.id,'unitEntityId',p.unit_entity_id,'unitLabel',u.label,'startsOn',p.starts_on,'endsOn',p.ends_on,'status',p.status)) from public.hs_staff_unit_permissions p join public.network_entities u on u.id=p.unit_entity_id where p.staff_id=s.id and p.status='active'),'[]'::jsonb)) order by s.name) from public.hs_domestic_staff s where s.network_id=nid),'[]'::jsonb) else '[]'::jsonb end,
 'moveRequests',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'unitEntityId',r.unit_entity_id,'unitLabel',u.label,'moveType',r.move_type,'scheduledOn',r.scheduled_on,'contactName',r.contact_name,'notes',r.notes,'status',r.status,'reviewNote',r.review_note) order by r.scheduled_on desc) from public.hs_move_requests r join public.network_entities u on u.id=r.unit_entity_id where r.network_id=nid and (isadm or r.created_by=auth.uid())),'[]'::jsonb),
 'renovations',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'unitEntityId',r.unit_entity_id,'unitLabel',u.label,'title',r.title,'description',r.description,'contractorName',r.contractor_name,'startsOn',r.starts_on,'endsOn',r.ends_on,'status',r.status,'nocReference',r.noc_reference,'conditions',r.conditions) order by r.created_at desc) from public.hs_renovation_requests r join public.network_entities u on u.id=r.unit_entity_id where r.network_id=nid and (isadm or r.created_by=auth.uid())),'[]'::jsonb),
 'assets',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'assetCode',a.asset_code,'name',a.name,'category',a.category,'location',a.location,'status',a.status,'commissionedOn',a.commissioned_on,'warrantyUntil',a.warranty_until,'nextServiceOn',(select min(s.next_due_on) from public.hs_asset_service_records s where s.asset_id=a.id and s.next_due_on>=current_date)) order by a.category,a.name) from public.hs_assets a where a.network_id=nid),'[]'::jsonb),
 'compliance',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'category',c.category,'title',c.title,'dueOn',c.due_on,'status',c.status,'ownerLabel',c.owner_label,'documentUrl',c.document_url,'visibility',c.visibility,'notes',c.notes) order by c.due_on nulls last,c.title) from public.hs_compliance_items c where c.network_id=nid and (isadm or c.visibility='members')),'[]'::jsonb),
 'emergencyContacts',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'category',e.category,'label',e.label,'phone',e.phone,'notes',e.notes,'priority',e.priority) order by e.priority,e.label) from public.hs_emergency_contacts e where e.network_id=nid and e.active),'[]'::jsonb)
 );end $$;
revoke all on function public.hs5_get_snapshot() from public;grant execute on function public.hs5_get_snapshot() to authenticated;

create or replace function public.hs5_create_visitor(p_unit_entity_id uuid,p_visitor_name text,p_visit_type text default 'guest',p_expected_at timestamptz default null,p_purpose text default null,p_phone text default null,p_vehicle_number text default null) returns uuid language plpgsql security definer set search_path=public as $$declare nid uuid:=public.hs5_assert_network();rid uuid;allowed boolean;begin
 allowed:=public.hs5_is_operator(nid,'security') or exists(select 1 from public.hs_unit_occupancy_history o join public.network_entities p on p.id=o.subject_entity_id where o.network_id=nid and o.unit_entity_id=p_unit_entity_id and o.ends_on is null and p.owner_user_id=auth.uid());if not allowed then raise exception 'Current-flat resident or security access required.' using errcode='42501';end if;
 insert into public.hs_visitors(network_id,unit_entity_id,visitor_name,visit_type,expected_at,purpose,phone,vehicle_number,created_by) values(nid,p_unit_entity_id,trim(p_visitor_name),p_visit_type,p_expected_at,nullif(trim(p_purpose),''),nullif(trim(p_phone),''),nullif(upper(trim(p_vehicle_number)),'') ,auth.uid()) returning id into rid;return rid;end $$;
revoke all on function public.hs5_create_visitor(uuid,text,text,timestamptz,text,text,text) from public;grant execute on function public.hs5_create_visitor(uuid,text,text,timestamptz,text,text,text) to authenticated;

create or replace function public.hs5_update_visitor_status(p_visitor_id uuid,p_status text) returns void language plpgsql security definer set search_path=public as $$declare nid uuid:=public.hs5_assert_network();begin if not public.hs5_is_operator(nid,'security') then raise exception 'Security operator access required.' using errcode='42501';end if;if p_status not in ('inside','exited','cancelled','denied') then raise exception 'Invalid visitor status.';end if;update public.hs_visitors set status=p_status,entered_at=case when p_status='inside' then coalesce(entered_at,now()) else entered_at end,exited_at=case when p_status='exited' then now() else exited_at end,checked_by=auth.uid(),updated_at=now() where id=p_visitor_id and network_id=nid;if not found then raise exception 'Visitor not found.';end if;end $$;
revoke all on function public.hs5_update_visitor_status(uuid,text) from public;grant execute on function public.hs5_update_visitor_status(uuid,text) to authenticated;

create or replace function public.hs5_grant_operator(p_user_id uuid,p_scope text default 'security',p_active boolean default true) returns uuid language plpgsql security definer set search_path=public as $$declare nid uuid:=public.hs5_assert_network();rid uuid;begin if not public.is_network_admin(nid) then raise exception 'Society admin access required.' using errcode='42501';end if;insert into public.hs_security_operator_grants(network_id,user_id,scope,active,created_by) values(nid,p_user_id,p_scope,p_active,auth.uid()) on conflict(network_id,user_id,scope) do update set active=excluded.active,updated_at=now() returning id into rid;return rid;end $$;
revoke all on function public.hs5_grant_operator(uuid,text,boolean) from public;grant execute on function public.hs5_grant_operator(uuid,text,boolean) to authenticated;

create or replace function public.hs5_upsert_staff(p_id uuid,p_name text,p_staff_type text,p_phone text default null,p_identity_last4 text default null,p_verification_status text default 'pending') returns uuid language plpgsql security definer set search_path=public as $$declare nid uuid:=public.hs5_assert_network();rid uuid;begin if not public.hs5_is_operator(nid,'security') then raise exception 'Security operator access required.' using errcode='42501';end if;if p_id is null then insert into public.hs_domestic_staff(network_id,name,staff_type,phone,identity_last4,verification_status,created_by) values(nid,trim(p_name),p_staff_type,nullif(trim(p_phone),''),nullif(trim(p_identity_last4),''),p_verification_status,auth.uid()) returning id into rid;else update public.hs_domestic_staff set name=trim(p_name),staff_type=p_staff_type,phone=nullif(trim(p_phone),''),identity_last4=nullif(trim(p_identity_last4),''),verification_status=p_verification_status,updated_at=now() where id=p_id and network_id=nid returning id into rid;end if;return rid;end $$;
revoke all on function public.hs5_upsert_staff(uuid,text,text,text,text,text) from public;grant execute on function public.hs5_upsert_staff(uuid,text,text,text,text,text) to authenticated;

create or replace function public.hs5_authorize_staff_unit(p_staff_id uuid,p_unit_entity_id uuid,p_starts_on date default current_date,p_ends_on date default null) returns uuid language plpgsql security definer set search_path=public as $$declare nid uuid:=public.hs5_assert_network();rid uuid;begin if not public.hs5_is_operator(nid,'security') then raise exception 'Security operator access required.' using errcode='42501';end if;insert into public.hs_staff_unit_permissions(network_id,staff_id,unit_entity_id,starts_on,ends_on,created_by) values(nid,p_staff_id,p_unit_entity_id,coalesce(p_starts_on,current_date),p_ends_on,auth.uid()) returning id into rid;return rid;end $$;
revoke all on function public.hs5_authorize_staff_unit(uuid,uuid,date,date) from public;grant execute on function public.hs5_authorize_staff_unit(uuid,uuid,date,date) to authenticated;

create or replace function public.hs5_create_move_request(p_unit_entity_id uuid,p_move_type text,p_scheduled_on date,p_contact_name text default null,p_notes text default null) returns uuid language plpgsql security definer set search_path=public as $$declare nid uuid:=public.hs5_assert_network();rid uuid;begin if not(public.is_network_admin(nid) or exists(select 1 from public.hs_unit_occupancy_history o join public.network_entities p on p.id=o.subject_entity_id where o.network_id=nid and o.unit_entity_id=p_unit_entity_id and o.ends_on is null and p.owner_user_id=auth.uid())) then raise exception 'Current-flat resident or admin required.' using errcode='42501';end if;insert into public.hs_move_requests(network_id,unit_entity_id,move_type,scheduled_on,contact_name,notes,created_by) values(nid,p_unit_entity_id,p_move_type,p_scheduled_on,nullif(trim(p_contact_name),''),nullif(trim(p_notes),''),auth.uid()) returning id into rid;return rid;end $$;
revoke all on function public.hs5_create_move_request(uuid,text,date,text,text) from public;grant execute on function public.hs5_create_move_request(uuid,text,date,text,text) to authenticated;

create or replace function public.hs5_create_renovation_request(p_unit_entity_id uuid,p_title text,p_description text default null,p_contractor_name text default null,p_starts_on date default null,p_ends_on date default null) returns uuid language plpgsql security definer set search_path=public as $$declare nid uuid:=public.hs5_assert_network();rid uuid;begin if not(public.is_network_admin(nid) or exists(select 1 from public.hs_unit_occupancy_history o join public.network_entities p on p.id=o.subject_entity_id where o.network_id=nid and o.unit_entity_id=p_unit_entity_id and o.ends_on is null and p.owner_user_id=auth.uid())) then raise exception 'Current-flat resident or admin required.' using errcode='42501';end if;insert into public.hs_renovation_requests(network_id,unit_entity_id,title,description,contractor_name,starts_on,ends_on,created_by) values(nid,p_unit_entity_id,trim(p_title),nullif(trim(p_description),''),nullif(trim(p_contractor_name),''),p_starts_on,p_ends_on,auth.uid()) returning id into rid;return rid;end $$;
revoke all on function public.hs5_create_renovation_request(uuid,text,text,text,date,date) from public;grant execute on function public.hs5_create_renovation_request(uuid,text,text,text,date,date) to authenticated;

create or replace function public.hs5_review_request(p_kind text,p_id uuid,p_status text,p_note text default null,p_noc_reference text default null) returns void language plpgsql security definer set search_path=public as $$declare nid uuid:=public.hs5_assert_network();begin if not public.is_network_admin(nid) then raise exception 'Society admin access required.' using errcode='42501';end if;if p_kind='move' then update public.hs_move_requests set status=p_status,review_note=nullif(trim(p_note),''),reviewed_by=auth.uid(),updated_at=now() where id=p_id and network_id=nid;elsif p_kind='renovation' then update public.hs_renovation_requests set status=p_status,conditions=nullif(trim(p_note),''),noc_reference=nullif(trim(p_noc_reference),''),reviewed_by=auth.uid(),updated_at=now() where id=p_id and network_id=nid;else raise exception 'Invalid request kind.';end if;end $$;
revoke all on function public.hs5_review_request(text,uuid,text,text,text) from public;grant execute on function public.hs5_review_request(text,uuid,text,text,text) to authenticated;

create or replace function public.hs5_upsert_asset(p_id uuid,p_asset_code text,p_name text,p_category text,p_location text default null,p_warranty_until date default null) returns uuid language plpgsql security definer set search_path=public as $$declare nid uuid:=public.hs5_assert_network();rid uuid;begin if not public.is_network_admin(nid) then raise exception 'Society admin access required.' using errcode='42501';end if;if p_id is null then insert into public.hs_assets(network_id,asset_code,name,category,location,warranty_until,created_by) values(nid,upper(trim(p_asset_code)),trim(p_name),trim(p_category),nullif(trim(p_location),''),p_warranty_until,auth.uid()) on conflict(network_id,asset_code) do update set name=excluded.name,category=excluded.category,location=excluded.location,warranty_until=excluded.warranty_until,updated_at=now() returning id into rid;else update public.hs_assets set asset_code=upper(trim(p_asset_code)),name=trim(p_name),category=trim(p_category),location=nullif(trim(p_location),''),warranty_until=p_warranty_until,updated_at=now() where id=p_id and network_id=nid returning id into rid;end if;return rid;end $$;
revoke all on function public.hs5_upsert_asset(uuid,text,text,text,text,date) from public;grant execute on function public.hs5_upsert_asset(uuid,text,text,text,text,date) to authenticated;

create or replace function public.hs5_add_asset_service(p_asset_id uuid,p_service_type text,p_serviced_on date default current_date,p_next_due_on date default null,p_notes text default null,p_cost numeric default null) returns uuid language plpgsql security definer set search_path=public as $$declare nid uuid:=public.hs5_assert_network();rid uuid;begin if not(public.is_network_admin(nid) or public.hs5_is_operator(nid,'facility')) then raise exception 'Facility operator access required.' using errcode='42501';end if;insert into public.hs_asset_service_records(network_id,asset_id,service_type,serviced_on,next_due_on,notes,cost,created_by) values(nid,p_asset_id,trim(p_service_type),coalesce(p_serviced_on,current_date),p_next_due_on,nullif(trim(p_notes),''),p_cost,auth.uid()) returning id into rid;return rid;end $$;
revoke all on function public.hs5_add_asset_service(uuid,text,date,date,text,numeric) from public;grant execute on function public.hs5_add_asset_service(uuid,text,date,date,text,numeric) to authenticated;

create or replace function public.hs5_upsert_compliance(p_id uuid,p_category text,p_title text,p_due_on date,p_owner_label text default null,p_document_url text default null,p_visibility text default 'members') returns uuid language plpgsql security definer set search_path=public as $$declare nid uuid:=public.hs5_assert_network();rid uuid;begin if not(public.is_network_admin(nid) or public.hs5_is_operator(nid,'compliance')) then raise exception 'Compliance operator access required.' using errcode='42501';end if;if p_id is null then insert into public.hs_compliance_items(network_id,category,title,due_on,owner_label,document_url,visibility,created_by) values(nid,trim(p_category),trim(p_title),p_due_on,nullif(trim(p_owner_label),''),nullif(trim(p_document_url),''),p_visibility,auth.uid()) returning id into rid;else update public.hs_compliance_items set category=trim(p_category),title=trim(p_title),due_on=p_due_on,owner_label=nullif(trim(p_owner_label),''),document_url=nullif(trim(p_document_url),''),visibility=p_visibility,updated_at=now() where id=p_id and network_id=nid returning id into rid;end if;return rid;end $$;
revoke all on function public.hs5_upsert_compliance(uuid,text,text,date,text,text,text) from public;grant execute on function public.hs5_upsert_compliance(uuid,text,text,date,text,text,text) to authenticated;

create or replace function public.hs5_upsert_emergency_contact(p_category text,p_label text,p_phone text,p_notes text default null,p_priority integer default 100) returns uuid language plpgsql security definer set search_path=public as $$declare nid uuid:=public.hs5_assert_network();rid uuid;begin if not public.is_network_admin(nid) then raise exception 'Society admin access required.' using errcode='42501';end if;insert into public.hs_emergency_contacts(network_id,category,label,phone,notes,priority,created_by) values(nid,trim(p_category),trim(p_label),trim(p_phone),nullif(trim(p_notes),''),coalesce(p_priority,100),auth.uid()) on conflict(network_id,category,label) do update set phone=excluded.phone,notes=excluded.notes,priority=excluded.priority,active=true,updated_at=now() returning id into rid;return rid;end $$;
revoke all on function public.hs5_upsert_emergency_contact(text,text,text,text,integer) from public;grant execute on function public.hs5_upsert_emergency_contact(text,text,text,text,integer) to authenticated;

insert into public.platform_feature_flags(feature_key,bundle_key,rollout_state,pilot_network_ids,vertical_kind) values
 ('housing-society.security.visitors','community','released','{}'::uuid[],'housing-society'),('housing-society.security.staff','admin','released','{}'::uuid[],'housing-society'),('housing-society.security.move-approvals','community','released','{}'::uuid[],'housing-society'),('housing-society.assets.registry','admin','released','{}'::uuid[],'housing-society'),('housing-society.compliance.calendar','admin','released','{}'::uuid[],'housing-society'),('housing-society.security.emergency','core','released','{}'::uuid[],'housing-society')
on conflict(feature_key) do update set bundle_key=excluded.bundle_key,rollout_state=excluded.rollout_state,vertical_kind=excluded.vertical_kind;

do $$ begin if to_regclass('public.hs_visitors') is null or to_regclass('public.hs_domestic_staff') is null or to_regclass('public.hs_assets') is null or to_regclass('public.hs_compliance_items') is null then raise exception 'HS-5 compatibility check failed: security/compliance tables missing.';end if;if to_regprocedure('public.hs5_get_snapshot()') is null or to_regprocedure('public.hs5_create_visitor(uuid,text,text,timestamptz,text,text,text)') is null or to_regprocedure('public.hs5_upsert_asset(uuid,text,text,text,text,date)') is null then raise exception 'HS-5 compatibility check failed: RPCs missing.';end if;end $$;
