-- HS-6 — Founder Society Pilot & Commercialization
-- Additive + rerunnable. Turns the completed housing vertical into a repeatable, measurable pilot system.

create table if not exists public.hs_pilot_runs(
 id uuid primary key default gen_random_uuid(),
 network_id uuid not null references public.networks(id) on delete cascade,
 phase varchar(8) not null default 'B' check(phase in ('A','B','C','D')),
 status varchar(20) not null default 'planning' check(status in ('planning','active','paused','completed','stopped')),
 cohort_label varchar(180),
 target_units integer not null default 20 check(target_units between 1 and 5000),
 started_on date,
 ended_on date,
 notes text,
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 check(ended_on is null or started_on is null or ended_on>=started_on)
);
create unique index if not exists uq_hs_pilot_one_active on public.hs_pilot_runs(network_id) where status='active';
create index if not exists idx_hs_pilot_runs_network on public.hs_pilot_runs(network_id,created_at desc);

create table if not exists public.hs_pilot_checkpoints(
 id uuid primary key default gen_random_uuid(),
 network_id uuid not null references public.networks(id) on delete cascade,
 pilot_run_id uuid not null references public.hs_pilot_runs(id) on delete cascade,
 checkpoint_on date not null default current_date,
 admin_hours_saved numeric(8,2) check(admin_hours_saved is null or admin_hours_saved>=0),
 offline_operations_remaining integer check(offline_operations_remaining is null or offline_operations_remaining>=0),
 willingness_to_pay varchar(20) not null default 'unknown' check(willingness_to_pay in ('unknown','no','maybe','yes')),
 renewal_intent varchar(20) not null default 'unknown' check(renewal_intent in ('unknown','no','maybe','yes')),
 repeatable_onboarding_confirmed boolean not null default false,
 founder_specific_code_required boolean not null default false,
 committee_note text,
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now()
);
create index if not exists idx_hs_pilot_checkpoints_run on public.hs_pilot_checkpoints(pilot_run_id,checkpoint_on desc,created_at desc);

create table if not exists public.hs_pilot_pricing_experiments(
 id uuid primary key default gen_random_uuid(),
 network_id uuid not null references public.networks(id) on delete cascade,
 pilot_run_id uuid references public.hs_pilot_runs(id) on delete set null,
 pricing_model varchar(30) not null check(pricing_model in ('per_unit_month','society_annual','base_plus_modules','setup_fee','undecided')),
 amount numeric(14,2) check(amount is null or amount>=0),
 currency varchar(8) not null default 'INR',
 response varchar(20) not null default 'untested' check(response in ('untested','rejected','neutral','interested','accepted')),
 notes text,
 tested_on date not null default current_date,
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now()
);
create index if not exists idx_hs_pilot_pricing_network on public.hs_pilot_pricing_experiments(network_id,tested_on desc);

create table if not exists public.hs_pilot_usage_events(
 id bigint generated by default as identity primary key,
 network_id uuid not null references public.networks(id) on delete cascade,
 user_id uuid references auth.users(id) on delete set null,
 unit_entity_id uuid references public.network_entities(id) on delete set null,
 event_key varchar(40) not null check(event_key in ('home_view','my_flat_view','directory_view','notice_view','complaint_view','maintenance_view','amenity_view','governance_view','security_view','pilot_export')),
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
create index if not exists idx_hs_pilot_usage_network_time on public.hs_pilot_usage_events(network_id,created_at desc,event_key);
create index if not exists idx_hs_pilot_usage_unit_time on public.hs_pilot_usage_events(network_id,unit_entity_id,created_at desc);

create table if not exists public.hs_notice_reads(
 network_id uuid not null references public.networks(id) on delete cascade,
 notice_id uuid not null references public.hs_notices(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 read_at timestamptz not null default now(),
 primary key(network_id,notice_id,user_id)
);
create index if not exists idx_hs_notice_reads_network_time on public.hs_notice_reads(network_id,read_at desc);

alter table public.hs_pilot_runs enable row level security;
alter table public.hs_pilot_checkpoints enable row level security;
alter table public.hs_pilot_pricing_experiments enable row level security;
alter table public.hs_pilot_usage_events enable row level security;
alter table public.hs_notice_reads enable row level security;
revoke all on table public.hs_pilot_runs,public.hs_pilot_checkpoints,public.hs_pilot_pricing_experiments,public.hs_pilot_usage_events,public.hs_notice_reads from anon,authenticated;

create or replace function public.hs6_assert_network() returns uuid language plpgsql security definer stable set search_path=public as $$
declare nid uuid:=public.current_network_id();begin
 if nid is null or not public.is_network_member(nid) then raise exception 'Housing Society membership required.' using errcode='42501';end if;
 if coalesce((select vertical_kind from public.networks where id=nid),'')<>'housing-society' then raise exception 'HS-6 is available only for housing-society networks.' using errcode='22023';end if;
 return nid;
end $$;
revoke all on function public.hs6_assert_network() from public;grant execute on function public.hs6_assert_network() to authenticated;

create or replace function public.hs6_assert_admin_network() returns uuid language plpgsql security definer stable set search_path=public as $$
declare nid uuid:=public.hs6_assert_network();begin if not public.is_network_admin(nid) then raise exception 'Society admin access required.' using errcode='42501';end if;return nid;end $$;
revoke all on function public.hs6_assert_admin_network() from public;grant execute on function public.hs6_assert_admin_network() to authenticated;

create or replace function public.hs6_start_pilot(p_phase text default 'B',p_target_units integer default 20,p_cohort_label text default null,p_notes text default null) returns uuid language plpgsql security definer set search_path=public as $$
declare nid uuid:=public.hs6_assert_admin_network();rid uuid;begin
 if p_phase not in ('A','B','C','D') then raise exception 'Invalid pilot phase.' using errcode='22023';end if;
 if coalesce(p_target_units,0)<1 or p_target_units>5000 then raise exception 'Pilot target must be between 1 and 5000 units.' using errcode='22023';end if;
 update public.hs_pilot_runs set status='paused',updated_at=now() where network_id=nid and status='active';
 insert into public.hs_pilot_runs(network_id,phase,status,cohort_label,target_units,started_on,notes,created_by)
 values(nid,p_phase,'active',nullif(trim(coalesce(p_cohort_label,'')),''),p_target_units,current_date,nullif(trim(coalesce(p_notes,'')),''),auth.uid()) returning id into rid;
 return rid;
end $$;
revoke all on function public.hs6_start_pilot(text,integer,text,text) from public;grant execute on function public.hs6_start_pilot(text,integer,text,text) to authenticated;

create or replace function public.hs6_update_pilot_status(p_run_id uuid,p_status text) returns void language plpgsql security definer set search_path=public as $$
declare nid uuid:=public.hs6_assert_admin_network();begin
 if p_status not in ('planning','active','paused','completed','stopped') then raise exception 'Invalid pilot status.' using errcode='22023';end if;
 if p_status='active' then update public.hs_pilot_runs set status='paused',updated_at=now() where network_id=nid and status='active' and id<>p_run_id;end if;
 update public.hs_pilot_runs set status=p_status,started_on=case when p_status='active' then coalesce(started_on,current_date) else started_on end,ended_on=case when p_status in ('completed','stopped') then coalesce(ended_on,current_date) else null end,updated_at=now() where id=p_run_id and network_id=nid;
 if not found then raise exception 'Pilot run not found.';end if;
end $$;
revoke all on function public.hs6_update_pilot_status(uuid,text) from public;grant execute on function public.hs6_update_pilot_status(uuid,text) to authenticated;

create or replace function public.hs6_record_checkpoint(p_run_id uuid,p_admin_hours_saved numeric default null,p_offline_operations_remaining integer default null,p_willingness_to_pay text default 'unknown',p_renewal_intent text default 'unknown',p_repeatable_onboarding_confirmed boolean default false,p_founder_specific_code_required boolean default false,p_committee_note text default null) returns uuid language plpgsql security definer set search_path=public as $$
declare nid uuid:=public.hs6_assert_admin_network();rid uuid;begin
 if not exists(select 1 from public.hs_pilot_runs where id=p_run_id and network_id=nid) then raise exception 'Pilot run not found.';end if;
 insert into public.hs_pilot_checkpoints(network_id,pilot_run_id,admin_hours_saved,offline_operations_remaining,willingness_to_pay,renewal_intent,repeatable_onboarding_confirmed,founder_specific_code_required,committee_note,created_by)
 values(nid,p_run_id,p_admin_hours_saved,p_offline_operations_remaining,p_willingness_to_pay,p_renewal_intent,coalesce(p_repeatable_onboarding_confirmed,false),coalesce(p_founder_specific_code_required,false),nullif(trim(coalesce(p_committee_note,'')),''),auth.uid()) returning id into rid;
 return rid;
end $$;
revoke all on function public.hs6_record_checkpoint(uuid,numeric,integer,text,text,boolean,boolean,text) from public;grant execute on function public.hs6_record_checkpoint(uuid,numeric,integer,text,text,boolean,boolean,text) to authenticated;

create or replace function public.hs6_record_pricing_experiment(p_run_id uuid,p_pricing_model text,p_amount numeric default null,p_currency text default 'INR',p_response text default 'untested',p_notes text default null) returns uuid language plpgsql security definer set search_path=public as $$
declare nid uuid:=public.hs6_assert_admin_network();rid uuid;begin
 if p_run_id is not null and not exists(select 1 from public.hs_pilot_runs where id=p_run_id and network_id=nid) then raise exception 'Pilot run not found.';end if;
 insert into public.hs_pilot_pricing_experiments(network_id,pilot_run_id,pricing_model,amount,currency,response,notes,created_by)
 values(nid,p_run_id,p_pricing_model,p_amount,upper(coalesce(nullif(trim(p_currency),''),'INR')),p_response,nullif(trim(coalesce(p_notes,'')),''),auth.uid()) returning id into rid;
 return rid;
end $$;
revoke all on function public.hs6_record_pricing_experiment(uuid,text,numeric,text,text,text) from public;grant execute on function public.hs6_record_pricing_experiment(uuid,text,numeric,text,text,text) to authenticated;

create or replace function public.hs6_record_usage_event(p_event_key text,p_metadata jsonb default '{}'::jsonb) returns void language plpgsql security definer set search_path=public as $$
declare nid uuid:=public.hs6_assert_network();uid uuid;begin
 select o.unit_entity_id into uid from public.hs_unit_occupancy_history o join public.network_entities p on p.id=o.subject_entity_id where o.network_id=nid and o.ends_on is null and p.owner_user_id=auth.uid() order by o.is_primary desc,o.starts_on desc limit 1;
 insert into public.hs_pilot_usage_events(network_id,user_id,unit_entity_id,event_key,metadata) values(nid,auth.uid(),uid,p_event_key,coalesce(p_metadata,'{}'::jsonb));
end $$;
revoke all on function public.hs6_record_usage_event(text,jsonb) from public;grant execute on function public.hs6_record_usage_event(text,jsonb) to authenticated;

create or replace function public.hs6_mark_notice_reads(p_notice_ids uuid[]) returns integer language plpgsql security definer set search_path=public as $$
declare nid uuid:=public.hs6_assert_network();n integer:=0;begin
 insert into public.hs_notice_reads(network_id,notice_id,user_id)
 select nid,n.id,auth.uid() from public.hs_notices n where n.network_id=nid and n.id=any(coalesce(p_notice_ids,'{}'::uuid[]))
 on conflict(network_id,notice_id,user_id) do update set read_at=greatest(public.hs_notice_reads.read_at,excluded.read_at);
 get diagnostics n=row_count;return n;
end $$;
revoke all on function public.hs6_mark_notice_reads(uuid[]) from public;grant execute on function public.hs6_mark_notice_reads(uuid[]) to authenticated;

create or replace function public.hs6_get_pilot_snapshot() returns jsonb language plpgsql security definer stable set search_path=public as $$
declare
 nid uuid:=public.hs6_assert_admin_network();run_row public.hs_pilot_runs%rowtype;latest_cp jsonb;units integer;occupied integer;claimed integer;active_units integer;members integer;notices30 integer;notice_readers integer;complaints30 integer;resolved30 integer;median_hours numeric;maintenance_views integer;billing_cycles integer;payments integer;meetings integer;security_cycles integer;imports integer;readiness integer;signals jsonb;
begin
 select * into run_row from public.hs_pilot_runs where network_id=nid order by (status='active') desc,created_at desc limit 1;
 select count(*) into units from public.network_entities where network_id=nid and kind='unit';
 select count(distinct unit_entity_id) into occupied from public.hs_unit_occupancy_history where network_id=nid and ends_on is null;
 select count(distinct o.unit_entity_id) into claimed from public.hs_unit_occupancy_history o join public.network_entities p on p.id=o.subject_entity_id where o.network_id=nid and o.ends_on is null and p.owner_user_id is not null;
 select count(distinct unit_entity_id) into active_units from public.hs_pilot_usage_events where network_id=nid and created_at>=now()-interval '7 days' and unit_entity_id is not null;
 select count(*) into members from public.network_memberships where network_id=nid and status='active';
 select count(*) into notices30 from public.hs_notices where network_id=nid and created_at>=now()-interval '30 days';
 select count(distinct user_id) into notice_readers from public.hs_notice_reads where network_id=nid and read_at>=now()-interval '30 days';
 select count(*) into complaints30 from public.hs_complaints where network_id=nid and created_at>=now()-interval '30 days';
 select count(*) into resolved30 from public.hs_complaints where network_id=nid and resolved_at is not null and resolved_at>=now()-interval '30 days';
 select round((percentile_cont(0.5) within group(order by extract(epoch from (resolved_at-created_at))/3600.0))::numeric,1) into median_hours from public.hs_complaints where network_id=nid and resolved_at is not null and resolved_at>=now()-interval '30 days';
 select count(*) into maintenance_views from public.hs_pilot_usage_events where network_id=nid and event_key='maintenance_view' and created_at>=now()-interval '30 days';
 select count(*) into billing_cycles from public.hs_billing_cycles where network_id=nid and status in ('issued','closed');
 select count(*) into payments from public.hs_payments where network_id=nid and status='recorded';
 select count(*) into meetings from public.hs_governance_meetings where network_id=nid and status='completed';
 select (select count(*) from public.hs_visitors where network_id=nid and status='exited')+(select count(*) from public.hs_asset_service_records where network_id=nid)+(select count(*) from public.hs_compliance_items where network_id=nid and status in ('compliant','completed')) into security_cycles;
 select count(*) into imports from public.hs_import_batches where network_id=nid and status='committed';
 select to_jsonb(c) into latest_cp from public.hs_pilot_checkpoints c where c.network_id=nid order by checkpoint_on desc,created_at desc limit 1;
 signals:=jsonb_build_array(
  jsonb_build_object('key','mapped_import','label','Mapped import completed','passed',imports>0),
  jsonb_build_object('key','target_units','label','Pilot unit target represented','passed',run_row.id is not null and units>=run_row.target_units),
  jsonb_build_object('key','claimed_units','label','Residents claimed real unit profiles','passed',claimed>0),
  jsonb_build_object('key','weekly_usage','label','Weekly active occupied units observed','passed',active_units>0),
  jsonb_build_object('key','notice_reach','label','Resident notice readership observed','passed',notice_readers>0),
  jsonb_build_object('key','complaint_loop','label','Complaint resolved end-to-end','passed',resolved30>0),
  jsonb_build_object('key','maintenance_cycle','label','Maintenance bill cycle represented','passed',billing_cycles>0),
  jsonb_build_object('key','governance_cycle','label','Committee/AGM meeting completed','passed',meetings>0),
  jsonb_build_object('key','operations_cycle','label','Security/compliance/asset operation completed','passed',security_cycles>0),
  jsonb_build_object('key','repeatable_onboarding','label','Second-society onboarding confirmed without founder-specific code','passed',coalesce((latest_cp->>'repeatable_onboarding_confirmed')::boolean,false) and not coalesce((latest_cp->>'founder_specific_code_required')::boolean,false))
 );
 select round(100.0*count(*) filter(where (x->>'passed')::boolean)/greatest(count(*),1))::integer into readiness from jsonb_array_elements(signals) x;
 return jsonb_build_object(
  'run',case when run_row.id is null then null else jsonb_build_object('id',run_row.id,'phase',run_row.phase,'status',run_row.status,'cohortLabel',run_row.cohort_label,'targetUnits',run_row.target_units,'startedOn',run_row.started_on,'endedOn',run_row.ended_on,'notes',run_row.notes) end,
  'readiness',coalesce(readiness,0),'signals',signals,
  'metrics',jsonb_build_object('totalUnits',units,'occupiedUnits',occupied,'claimedUnits',claimed,'claimRate',case when units=0 then 0 else round(100.0*claimed/units)::integer end,'weeklyActiveUnits',active_units,'activeMembers',members,'notices30d',notices30,'noticeReaders30d',notice_readers,'noticeReadReach',case when members=0 then 0 else least(100,round(100.0*notice_readers/members)::integer) end,'complaints30d',complaints30,'resolvedComplaints30d',resolved30,'medianResolutionHours',coalesce(median_hours,0),'maintenanceViews30d',maintenance_views,'billingCycles',billing_cycles,'paymentsRecorded',payments,'completedMeetings',meetings,'securityComplianceCycles',security_cycles,'committedImports',imports),
  'latestCheckpoint',latest_cp,
  'checkpoints',coalesce((select jsonb_agg(to_jsonb(c) order by c.checkpoint_on desc,c.created_at desc) from (select * from public.hs_pilot_checkpoints where network_id=nid order by checkpoint_on desc,created_at desc limit 12)c),'[]'::jsonb),
  'pricingExperiments',coalesce((select jsonb_agg(to_jsonb(p) order by p.tested_on desc,p.created_at desc) from (select * from public.hs_pilot_pricing_experiments where network_id=nid order by tested_on desc,created_at desc limit 12)p),'[]'::jsonb)
 );
end $$;
revoke all on function public.hs6_get_pilot_snapshot() from public;grant execute on function public.hs6_get_pilot_snapshot() to authenticated;

insert into public.platform_feature_flags(feature_key,bundle_key,rollout_state,pilot_network_ids,vertical_kind) values
 ('housing-society.pilot.readiness','admin','released','{}'::uuid[],'housing-society'),
 ('housing-society.pilot.metrics','admin','released','{}'::uuid[],'housing-society'),
 ('housing-society.pilot.pricing','admin','released','{}'::uuid[],'housing-society')
on conflict(feature_key) do update set bundle_key=excluded.bundle_key,rollout_state=excluded.rollout_state,vertical_kind=excluded.vertical_kind;

do $$ begin
 if to_regclass('public.hs_pilot_runs') is null or to_regclass('public.hs_pilot_checkpoints') is null or to_regclass('public.hs_pilot_usage_events') is null or to_regclass('public.hs_notice_reads') is null then raise exception 'HS-6 compatibility check failed: pilot evidence tables missing.';end if;
 if to_regprocedure('public.hs6_get_pilot_snapshot()') is null or to_regprocedure('public.hs6_start_pilot(text,integer,text,text)') is null or to_regprocedure('public.hs6_record_usage_event(text,jsonb)') is null then raise exception 'HS-6 compatibility check failed: pilot RPCs missing.';end if;
end $$;
