import type {LaunchDataset,LaunchSeedLineageRow,LaunchSeedOptions} from "../../core/launch-seed/contracts";
import {buildLaunchCoreReview} from "./core-review";
import {sectionRef,sectionRows} from "./dataset";
import {LaunchSeedRunner} from "./runner";
import {commitProductizedWorkbook} from "../import/productized-workbook";
import {fetchNetworkAffiliatedEntities} from "../affiliation/remote";
import {assignFcaRole,createNetworkEntityRelationship,createNetworkFund,fetchFcaAdminSnapshot,fetchNetworkEntityRelationships,recordNetworkFundTransaction,setFcaFamilyMembership,submitNetworkContribution,updateFcaSettings,upsertFcaMembershipYear,upsertNetworkEntity} from "../template-product/remote";
import {addNetworkPostComment,createNetworkActivity,createNetworkGroup,createNetworkPost,joinNetworkGroup,respondNetworkEvent,setNetworkActivityPinned} from "../activity/remote";
import {addBallotOption,closeNetworkBallot,openNetworkBallot,publishNetworkBallotResults,saveNetworkBallot} from "../participation/voting-remote";
import {createNetworkInvitation} from "../participation/remote";
import {uploadMediaAsset,type MediaKind} from "../../lib/storage";
import {upsertLaunchFcaRole} from "./remote";

const s=(v:any)=>String(v??"").trim(),n=(v:any)=>Number(v||0),b=(v:any)=>v===true||["true","yes","1","y"].includes(s(v).toLowerCase());
const sectionId=(runner:LaunchSeedRunner,section:string,ref:string)=>runner.priorRow(section,ref)?.remoteId||undefined;
async function fixtureFile(){const response=await fetch("/launch-demo/fixtures/community-demo.png",{cache:"no-store"});if(!response.ok)throw new Error("Synthetic media fixture is unavailable.");const blob=await response.blob();return new File([blob],"community-demo.png",{type:"image/png"})}
function roleType(key:string){if(["president","president-elect","past-president","secretary","treasurer"].includes(key))return "office_bearer";if(key.includes("director"))return "director";if(key.includes("chair"))return "chairperson";if(key.includes("mentor"))return "mentor";if(key.includes("volunteer"))return "volunteer";return "committee"}
function yearStatus(v:any){const x=s(v).toLowerCase();if(x==="active")return "open";if(["planned","open","closed","archived"].includes(x))return x;return "planned"}
function mapMembershipStatus(v:any){const x=s(v).toLowerCase();return ["pending","active","grace","inactive","removed","transferred"].includes(x)?x:"active"}

export async function seedFamilyCommunityLaunchDataset(data:LaunchDataset,lineage:LaunchSeedLineageRow[],networkId:string,options:LaunchSeedOptions={}){
 const allSections=["core_import.families","core_import.people","core_import.household_membership","core_import.association_membership","family_detail.people_extended","family_detail.family_relationships","membership.years","membership.family_membership","membership.role_catalog","membership.role_assignments","community.events","community.rsvps","community.announcements","finance.funds","finance.transactions","governance.ballots","governance.ballot_options","community.posts","community.post_comments","community.memories","community.groups","community.group_membership","build_together.invitations","build_together.contribution_prompts","media"];
 const total=allSections.reduce((sum,path)=>sum+sectionRows(data,path).length,0);const runner=new LaunchSeedRunner(data,"family-association",lineage,total,options);
 let corePromise:Promise<Map<string,{id:string;kind:string;label:string;metadata:Record<string,any>;affiliations:Record<string,string[]>}>>|null=null;
 const loadEntities=async()=>{const entities=await fetchNetworkAffiliatedEntities();const map=new Map<string,{id:string;kind:string;label:string;metadata:Record<string,any>;affiliations:Record<string,string[]>}>();for(const e of entities){const ref=s(e.entity.metadata?.importStableId).toUpperCase();if(ref)map.set(ref,{id:e.entity.id,kind:e.entity.kind,label:e.entity.label,metadata:(e.entity.metadata||{}) as Record<string,any>,affiliations:e.affiliations})}return map};
 const ensureCore=async()=>{if(!corePromise)corePromise=(async()=>{await commitProductizedWorkbook(buildLaunchCoreReview(data,"family-association","TRUSTWEAVE-LAUNCH-DEMO-FAMILY-COMMUNITY-20-FAMILIES.xlsx"));return loadEntities()})();return corePromise};
 for(const path of ["core_import.families","core_import.people","core_import.household_membership","core_import.association_membership"]){for(const [i,row] of sectionRows(data,path).entries()){const ref=sectionRef("family-association",path,row,i);await runner.row(path,ref,row,async()=>{const entities=await ensureCore();if(path==="core_import.families")return entities.get(s(row["Family ID"]).toUpperCase())?.id;if(path==="core_import.people")return entities.get(s(row["Person ID"]).toUpperCase())?.id;return "guided-import"})}runner.sectionDone(path)}
 const entities=corePromise?await corePromise:await loadEntities();for(const row of sectionRows(data,"core_import.families")){const ref=s(row["Family ID"]);const e=entities.get(ref.toUpperCase());if(e&&!runner.priorRow("core_import.families",ref)?.remoteId)await runner.remember("core_import.families",ref,row,e.id)}for(const row of sectionRows(data,"core_import.people")){const ref=s(row["Person ID"]);const e=entities.get(ref.toUpperCase());if(e&&!runner.priorRow("core_import.people",ref)?.remoteId)await runner.remember("core_import.people",ref,row,e.id)}
 const entityId=(ref:any)=>entities.get(s(ref).toUpperCase())?.id||sectionId(runner,s(ref).startsWith("F")?"core_import.families":"core_import.people",s(ref));

 const settings=Object.fromEntries((data.network_settings||[]).map((r:any)=>[s(r.Setting),r.Value]));if(data.network_settings?.length){try{await updateFcaSettings({dependentAgeLimit:n(settings["Dependent Age Limit"])||21,gracePeriodDays:n(settings["Grace Period Days"])||30,maxAutoChildren:2,onboardingPolicy:"join_review_later",financeVisibility:s(settings["Finance Visibility"])||"members"})}catch(e:any){runner.warnings.push(`network_settings: ${e.message||e}`)}}
 for(const row of sectionRows(data,"family_detail.people_extended")){const ref=s(row["Person ID"]),entity=entities.get(ref.toUpperCase());await runner.row("family_detail.people_extended",ref,row,async existing=>{const id=existing||entity?.id;if(!id||!entity)throw new Error(`Person ${ref} was not resolved.`);const metadata={...entity.metadata,date_of_birth:s(row["Date of Birth"])||undefined,phone:s(row.Phone)||undefined,family_role:s(row["Family Role"])||undefined,profile_visibility:s(row["Profile Visibility"])||"members",contact_visibility:s(row["Contact Visibility"])||"members",interests:s(row.Interests)||undefined};await upsertNetworkEntity({id,kind:"person",label:entity.label,metadata,visibility:s(row["Profile Visibility"])==="private"?"private":"members"});entity.metadata=metadata;return id})}runner.sectionDone("family_detail.people_extended");
 const rels=await fetchNetworkEntityRelationships();const edgeKeys=new Set(rels.map(r=>`${r.fromEntityId}|${r.toEntityId}|${r.relationshipType}`));
 for(const row of sectionRows(data,"family_detail.family_relationships")){const ref=s(row["Relationship Ref"]),from=entityId(row["From Person ID"]),to=entityId(row["To Person ID"]),relationship=s(row.Relationship).toLowerCase();if(relationship==="child"){await runner.warningRow("family_detail.family_relationships",ref,row,"Child is the inverse of an explicit Parent row in this dataset; TrustWeave stores the canonical parent_of edge and does not duplicate an unsupported child_of edge.");continue}await runner.row("family_detail.family_relationships",ref,row,async()=>{if(!from||!to)throw new Error("Family relationship person reference was not resolved.");const type=relationship==="spouse"?"spouse_of":"parent_of",key=`${from}|${to}|${type}`;if(edgeKeys.has(key))return rels.find(r=>`${r.fromEntityId}|${r.toEntityId}|${r.relationshipType}`===key)?.id;const id=await createNetworkEntityRelationship(from,to,type,{launchDataset:data.version});edgeKeys.add(key);return id},{immutableAfterCreate:true})}runner.sectionDone("family_detail.family_relationships");

 const initialFca=await fetchFcaAdminSnapshot();const yearByLabel=new Map<string,string>((initialFca.years||[]).map((y:any)=>[s(y.label).toLowerCase(),s(y.id)]));
 for(const row of sectionRows(data,"membership.years")){const ref=s(row["Year Ref"]),label=s(row.Label);await runner.row("membership.years",ref,row,async existing=>{const id=existing||yearByLabel.get(label.toLowerCase())||null;const result=await upsertFcaMembershipYear({id,label,startDate:s(row["Start Date"]),endDate:s(row["End Date"]),familyFee:n(row["Family Fee"]),gracePeriodDays:n(row["Grace Days"]),status:yearStatus(row.Status)});yearByLabel.set(label.toLowerCase(),result);return result})}runner.sectionDone("membership.years");
 const yearId=(ref:any)=>sectionId(runner,"membership.years",s(ref));
 for(const row of sectionRows(data,"membership.family_membership")){const ref=s(row["Membership Ref"]);await runner.row("membership.family_membership",ref,row,async()=>{const yid=yearId(row["Year Ref"]),fid=entityId(row["Family ID"]),pid=entityId(row["Representative Person ID"]);if(!yid||!fid)throw new Error("Membership year/family reference was not resolved.");const id=await setFcaFamilyMembership({yearId:yid,familyEntityId:fid,representativeEntityId:pid||null,status:mapMembershipStatus(row.Status),paymentStatus:s(row["Payment Status"])||"unpaid",amountPaid:n(row["Amount Paid"]),paymentReference:s(row["Payment Reference"])});if(pid){const key=`${fid}|${pid}|represented_by`;if(!edgeKeys.has(key)){try{await createNetworkEntityRelationship(fid,pid,"represented_by",{launchDataset:data.version});edgeKeys.add(key)}catch{}}}return id})}runner.sectionDone("membership.family_membership");
 for(const row of sectionRows(data,"membership.role_catalog")){const ref=s(row["Role Ref"]),key=s(row["Role Key"]);await runner.row("membership.role_catalog",ref,row,()=>upsertLaunchFcaRole({datasetVersion:data.version,roleKey:key,label:s(row.Label),roleType:roleType(key),portfolio:s(row.Portfolio)}))}runner.sectionDone("membership.role_catalog");
 const roleId=(ref:any)=>sectionId(runner,"membership.role_catalog",s(ref));
 for(const row of sectionRows(data,"membership.role_assignments")){const ref=s(row["Assignment Ref"]);await runner.row("membership.role_assignments",ref,row,()=>{const yid=yearId(row["Year Ref"]),pid=entityId(row["Person ID"]),rid=roleId(row["Role Ref"]);if(!pid||!rid)throw new Error("Role assignment person/role reference was not resolved.");return assignFcaRole({yearId:yid||null,personEntityId:pid,roleCatalogId:rid,startsOn:s(row["Starts On"])||null,endsOn:s(row["Ends On"])||null,notes:s(row.Notes)})},{immutableAfterCreate:true})}runner.sectionDone("membership.role_assignments");

 for(const row of sectionRows(data,"community.events")){const ref=s(row["Event Ref"]);await runner.row("community.events",ref,row,()=>createNetworkActivity({type:"event",title:s(row.Title),body:s(row.Description),startsAt:s(row.Date)?`${s(row.Date)}T18:30:00+05:30`:undefined,place:s(row.Venue),visibility:"members"}),{immutableAfterCreate:true})}runner.sectionDone("community.events");
 const eventId=(ref:any)=>sectionId(runner,"community.events",s(ref));const rsvpUsed=new Set<string>();
 for(const row of sectionRows(data,"community.rsvps")){const ref=s(row["RSVP Ref"]),eventRef=s(row["Event Ref"]),eid=eventId(eventRef);if(!eid){await runner.warningRow("community.rsvps",ref,row,`Event ${eventRef} was not resolved.`);continue}if(rsvpUsed.has(eventRef)){await runner.warningRow("community.rsvps",ref,row,"Synthetic directory people are not fabricated as login accounts. Their source RSVP remains in the dataset, while the product RSVP table only stores real authenticated members.",eid);continue}rsvpUsed.add(eventRef);await runner.row("community.rsvps",ref,row,async()=>{await respondNetworkEvent(eid,(s(row.Response)||"going") as "going"|"maybe"|"declined");return eid})}runner.sectionDone("community.rsvps");
 for(const row of sectionRows(data,"community.announcements")){const ref=s(row["Announcement Ref"]);await runner.row("community.announcements",ref,row,()=>createNetworkActivity({type:"announcement",title:s(row.Title),body:`${s(row.Body)}\nAudience: ${s(row.Audience)}`,visibility:"members"}),{immutableAfterCreate:true})}runner.sectionDone("community.announcements");

 for(const row of sectionRows(data,"finance.funds")){const ref=s(row["Fund Ref"]);await runner.row("finance.funds",ref,row,()=>createNetworkFund({name:s(row.Name),fundKind:s(row["Fund Kind"]),purpose:s(row.Purpose),targetAmount:n(row["Target Amount"])||null,openingBalance:n(row["Opening Balance"]),visibility:s(row.Visibility)||"members",membershipYearId:yearId(row["Year Ref"])||null,activityId:eventId(row["Event Ref"])||null}),{immutableAfterCreate:true})}runner.sectionDone("finance.funds");
 const fundId=(ref:any)=>sectionId(runner,"finance.funds",s(ref));
 for(const row of sectionRows(data,"finance.transactions")){const ref=s(row["Transaction Ref"]),fid=fundId(row["Fund Ref"]);await runner.row("finance.transactions",ref,row,()=>{if(!fid)throw new Error("Fund reference was not resolved.");return recordNetworkFundTransaction({fundId:fid,transactionKind:s(row["Transaction Kind"]),amount:n(row.Amount),sourceEntityId:entityId(row["Source Family ID"])||null,membershipYearId:yearId(row["Year Ref"])||null,paymentMethod:s(row["Payment Method"]),reference:s(row.Reference),note:s(row.Note),visibility:s(row.Visibility)||"members"})},{immutableAfterCreate:true})}runner.sectionDone("finance.transactions");
 for(const row of sectionRows(data,"governance.ballots")){const ref=s(row["Ballot Ref"]);await runner.row("governance.ballots",ref,row,async existing=>{const id=await saveNetworkBallot({id:existing||null,ballotType:s(row["Ballot Type"]),title:s(row.Title),description:s(row.Description),eligibilityMode:s(row["Eligibility Mode"]),maxChoices:n(row["Max Choices"])||1,secretBallot:b(row["Secret Ballot"]),allowNominations:b(row["Allow Nominations"]),opensAt:s(row["Opens At"])||null,closesAt:s(row["Closes At"])||null});const desired=s(row["Desired Status"]);if(desired==="open")await openNetworkBallot(id);else if(desired==="closed")await closeNetworkBallot(id);else if(desired==="published"){await closeNetworkBallot(id);await publishNetworkBallotResults(id)}return id})}runner.sectionDone("governance.ballots");
 const ballotId=(ref:any)=>sectionId(runner,"governance.ballots",s(ref));
 for(const row of sectionRows(data,"governance.ballot_options")){const ref=s(row["Option Ref"]),bid=ballotId(row["Ballot Ref"]);await runner.row("governance.ballot_options",ref,row,()=>{if(!bid)throw new Error("Ballot reference was not resolved.");return addBallotOption(bid,s(row.Label),s(row.Description),entityId(row["Candidate Person ID"])||null)},{immutableAfterCreate:true})}runner.sectionDone("governance.ballot_options");

 for(const row of sectionRows(data,"community.posts")){const ref=s(row["Post Ref"]);await runner.row("community.posts",ref,row,async()=>{const id=await createNetworkPost({title:s(row.Title),body:s(row.Body),importance:(s(row.Importance)||"normal") as "normal"|"important"|"urgent",notifyAll:b(row["Notify All"])});if(b(row.Pinned))await setNetworkActivityPinned(id,true);return id},{immutableAfterCreate:true})}runner.sectionDone("community.posts");
 const postId=(ref:any)=>sectionId(runner,"community.posts",s(ref));
 for(const row of sectionRows(data,"community.post_comments")){const ref=s(row["Comment Ref"]),pid=postId(row["Post Ref"]);await runner.row("community.post_comments",ref,row,()=>{if(!pid)throw new Error("Post reference was not resolved.");return addNetworkPostComment(pid,s(row.Body))},{immutableAfterCreate:true})}runner.sectionDone("community.post_comments");
 for(const row of sectionRows(data,"community.memories")){const ref=s(row["Memory Ref"]);await runner.row("community.memories",ref,row,()=>createNetworkActivity({type:"memory",title:s(row.Title),body:`${s(row.Caption)}${row["Photo Count"]?`\nPhotos in source memory: ${row["Photo Count"]}`:""}`,startsAt:s(row.Date)?`${s(row.Date)}T12:00:00+05:30`:undefined,visibility:"members"}),{immutableAfterCreate:true})}runner.sectionDone("community.memories");
 const memoryId=(ref:any)=>sectionId(runner,"community.memories",s(ref));
 for(const row of sectionRows(data,"community.groups")){const ref=s(row["Group Ref"]);await runner.row("community.groups",ref,row,()=>createNetworkGroup({name:s(row.Name),groupType:s(row.Type)||"group",description:s(row.Description)}),{immutableAfterCreate:true})}runner.sectionDone("community.groups");
 const groupId=(ref:any)=>sectionId(runner,"community.groups",s(ref));const groupJoined=new Set<string>();
 for(const row of sectionRows(data,"community.group_membership")){const ref=s(row["Membership Ref"]),groupRef=s(row["Group Ref"]),gid=groupId(groupRef);if(!gid){await runner.warningRow("community.group_membership",ref,row,`Group ${groupRef} was not resolved.`);continue}if(groupJoined.has(groupRef)){await runner.warningRow("community.group_membership",ref,row,"Network groups are account memberships, not synthetic directory-person memberships. The real signed-in seed operator joins each group once; remaining source memberships are retained as dataset intent.",gid);continue}groupJoined.add(groupRef);await runner.row("community.group_membership",ref,row,async()=>{await joinNetworkGroup(gid);return gid})}runner.sectionDone("community.group_membership");
 for(const row of sectionRows(data,"build_together.invitations")){const ref=s(row["Invitation Ref"]),target=entityId(row["Family ID"]);await runner.row("build_together.invitations",ref,row,async()=>{const delivery=await createNetworkInvitation(networkId,s(row.Email),target);return delivery.invitationId},{immutableAfterCreate:true})}runner.sectionDone("build_together.invitations");
 for(const row of sectionRows(data,"build_together.contribution_prompts")){const ref=s(row["Prompt Ref"]);await runner.row("build_together.contribution_prompts",ref,row,()=>submitNetworkContribution(entityId(row["Target Person ID"])||null,s(row.Message),{launchDataset:data.version,promptType:s(row.Type),stableRef:ref}),{immutableAfterCreate:true})}runner.sectionDone("build_together.contribution_prompts");
 for(const row of sectionRows(data,"media")){const ref=s(row["Media Ref"]),entityRef=s(row["Entity Ref"]),entityType=s(row["Entity Type"]);await runner.row("media",ref,row,async()=>{let target:string|undefined;if(entityType==="event")target=eventId(entityRef);else if(entityType==="memory")target=memoryId(entityRef);else if(entityType==="network_post")target=postId(entityRef);if(!target)throw new Error(`Media target ${entityRef} was not resolved.`);const kind=(s(row["Media Kind"])||"other") as MediaKind;const asset=await uploadMediaAsset(await fixtureFile(),kind,{entityType:"activity",entityId:target});return asset.assetId},{immutableAfterCreate:true})}runner.sectionDone("media");
 return runner.result();
}
