import type {LaunchDataset,LaunchSeedLineageRow,LaunchSeedOptions} from "../../core/launch-seed/contracts";
import {buildLaunchCoreReview} from "./core-review";
import {sectionRef,sectionRows} from "./dataset";
import {LaunchSeedRunner} from "./runner";
import {commitHousingWorkbook} from "../import/housing-workbook";
import {fetchNetworkAffiliatedEntities} from "../affiliation/remote";
import {createNetworkActivity,createNetworkPost,addNetworkPostComment,setNetworkActivityPinned} from "../activity/remote";
import {addBallotOption,closeNetworkBallot,openNetworkBallot,publishNetworkBallotResults,saveNetworkBallot} from "../participation/voting-remote";
import {uploadMediaAsset,type MediaKind} from "../../lib/storage";
import {createHsAmenityBooking,createHsComplaint,createHsNotice,createHsVendorContract,addHsComplaintComment,reviewHsAmenityBooking,setHsComplaintRoute,updateHsComplaint,upsertHsAmenity,upsertHsVendor} from "../../verticals/housing-society/runtime/operations-remote";
import {addHsBillAdjustment,createHsBillingCycle,fetchHsFinanceSnapshot,generateHsCycleBills,recordHsExpense,recordHsPayment,upsertHsBudgetLine,upsertHsChargeHead,upsertHsFund} from "../../verticals/housing-society/runtime/finance-remote";
import {addHsAgendaItem,addHsGovernanceDocument,assignHsCommitteeRole,closeHsResolution,createHsCommitteeTerm,createHsGovernanceAction,createHsGovernanceMeeting,createHsResolution,publishHsMinutes,updateHsGovernanceAction} from "../../verticals/housing-society/runtime/governance-remote";
import {addHsAssetService,authorizeHsStaffUnit,createHsMoveRequest,createHsRenovationRequest,createHsVisitor,reviewHsOperationalRequest,updateHsVisitorStatus,upsertHsAsset,upsertHsCompliance,upsertHsEmergencyContact,upsertHsStaff} from "../../verticals/housing-society/runtime/security-remote";

const s=(v:any)=>String(v??"").trim(),n=(v:any)=>Number(v||0),b=(v:any)=>v===true||["true","yes","1","y"].includes(s(v).toLowerCase());
const sectionId=(runner:LaunchSeedRunner,section:string,ref:string)=>runner.priorRow(section,ref)?.remoteId||undefined;
function rowBy(rows:Record<string,any>[],key:string,value:string){return rows.find(r=>s(r[key])===value)}
async function fixtureFile(name:string){const response=await fetch(`/launch-demo/fixtures/${name}`,{cache:"no-store"});if(!response.ok)throw new Error("Synthetic media fixture is unavailable.");const blob=await response.blob();return new File([blob],name,{type:"image/png"})}

export async function seedHousingLaunchDataset(data:LaunchDataset,lineage:LaunchSeedLineageRow[],options:LaunchSeedOptions={}){
 const allSections=["core_import.units","core_import.residents","core_import.occupancy","core_import.vehicles","core_import.parking","operations.vendors","operations.vendor_contracts","operations.amenities","operations.notices","operations.complaints","operations.complaint_comments","operations.bookings","finance.charge_heads","finance.billing_cycles","finance.bill_expectations","finance.adjustments","finance.payments","finance.funds","finance.budget","finance.expenses","governance.committee_terms","governance.committee_assignments","governance.meetings","governance.agenda","governance.minutes","governance.actions","governance.resolutions","governance.documents","governance.ballots","governance.ballot_options","security.visitors","security.staff","security.staff_access","security.move_requests","security.renovations","security.assets","security.asset_service","security.compliance","security.emergency_contacts","community.events","community.posts","community.post_comments","community.media"];
 const total=allSections.reduce((sum,path)=>sum+sectionRows(data,path).length,0);const runner=new LaunchSeedRunner(data,"housing-society",lineage,total,options);
 let corePromise:Promise<{units:Map<string,string>;residents:Map<string,string>}>|null=null;
 const loadCoreMaps=async()=>{const entities=await fetchNetworkAffiliatedEntities();const unitEntities=entities.filter(e=>e.entity.kind==="unit"),personEntities=entities.filter(e=>e.entity.kind==="person");const units=new Map<string,string>(),residents=new Map<string,string>();for(const row of sectionRows(data,"core_import.units")){const ref=s(row["Unit ID"]),label=s(row["Unit / Flat"]);const found=unitEntities.find(e=>e.entity.label.toLowerCase()===label.toLowerCase());if(found)units.set(ref,found.entity.id)}for(const row of sectionRows(data,"core_import.residents")){const ref=s(row["Resident ID"]),email=s(row.Email).toLowerCase(),label=s(row["Resident Name"]);const found=personEntities.find(e=>(email&&s(e.entity.metadata?.email).toLowerCase()===email)||e.entity.label.toLowerCase()===label.toLowerCase());if(found)residents.set(ref,found.entity.id)}return {units,residents}};
 const ensureCore=async()=>{if(!corePromise)corePromise=(async()=>{await commitHousingWorkbook(buildLaunchCoreReview(data,"housing-society","TRUSTWEAVE-LAUNCH-DEMO-RESIDENTIAL-25-FLATS.xlsx"));return loadCoreMaps()})();return corePromise};
 for(const path of ["core_import.units","core_import.residents","core_import.occupancy","core_import.vehicles","core_import.parking"]){const rows=sectionRows(data,path);for(let i=0;i<rows.length;i++){const row=rows[i],ref=sectionRef("housing-society",path,row,i);await runner.row(path,ref,row,async()=>{const maps=await ensureCore();if(path==="core_import.units")return maps.units.get(s(row["Unit ID"]));if(path==="core_import.residents")return maps.residents.get(s(row["Resident ID"]));return "hs1-import"})}runner.sectionDone(path)}
 const coreMaps=corePromise?await corePromise:await loadCoreMaps();for(const [ref,id] of coreMaps.units)if(!runner.priorRow("core_import.units",ref)?.remoteId){const row=rowBy(sectionRows(data,"core_import.units"),"Unit ID",ref);if(row)await runner.remember("core_import.units",ref,row,id)}for(const [ref,id] of coreMaps.residents)if(!runner.priorRow("core_import.residents",ref)?.remoteId){const row=rowBy(sectionRows(data,"core_import.residents"),"Resident ID",ref);if(row)await runner.remember("core_import.residents",ref,row,id)}
 const unitId=(ref:any)=>coreMaps.units.get(s(ref))||sectionId(runner,"core_import.units",s(ref));const residentId=(ref:any)=>coreMaps.residents.get(s(ref))||sectionId(runner,"core_import.residents",s(ref));

 for(const row of sectionRows(data,"operations.vendors")){const ref=s(row["Vendor Ref"]);await runner.row("operations.vendors",ref,row,id=>upsertHsVendor({id:id||undefined,name:s(row.Name),category:s(row.Category),contactName:s(row["Contact Name"]),phone:s(row.Phone),email:s(row.Email),status:s(row.Status)||"active"}));}runner.sectionDone("operations.vendors");
 const vendorId=(ref:any)=>sectionId(runner,"operations.vendors",s(ref));
 for(const row of sectionRows(data,"operations.vendor_contracts")){const ref=s(row["Contract Ref"]),vid=vendorId(row["Vendor Ref"]);await runner.row("operations.vendor_contracts",ref,row,()=>{if(!vid)throw new Error(`Vendor ${row["Vendor Ref"]} was not seeded.`);return createHsVendorContract({vendorId:vid,title:s(row.Title),startsOn:s(row["Starts On"])||null,endsOn:s(row["Ends On"])||null,sla:s(row.SLA)||null,amount:n(row.Amount)||null})},{immutableAfterCreate:true})}runner.sectionDone("operations.vendor_contracts");
 for(const row of sectionRows(data,"operations.amenities")){const ref=s(row["Amenity Ref"]);await runner.row("operations.amenities",ref,row,id=>upsertHsAmenity({id:id||undefined,name:s(row.Name),description:s(row.Description),location:s(row.Location),capacity:n(row.Capacity)||null,bookingMode:s(row["Booking Mode"])||"approval",status:s(row.Status)||"active"}))}runner.sectionDone("operations.amenities");
 for(const row of sectionRows(data,"operations.notices")){const ref=s(row["Notice ID"]);await runner.row("operations.notices",ref,row,()=>createHsNotice({title:s(row.Title),body:s(row.Body),noticeType:s(row["Notice Type"]),pinned:b(row.Pinned),expiresAt:s(row["Expires At"])||null}),{immutableAfterCreate:true})}runner.sectionDone("operations.notices");
 for(const row of sectionRows(data,"operations.complaints")){const ref=s(row["Complaint Ref"]),uid=unitId(row["Unit ID"]),vid=vendorId(row["Assigned Vendor Ref"]);const role=s(row["Assigned Role"]);await runner.row("operations.complaints",ref,row,async existing=>{if(role)await setHsComplaintRoute(s(row.Category),role).catch(()=>{});const id=existing||await createHsComplaint({unitEntityId:uid||null,category:s(row.Category),title:s(row.Title),description:s(row.Description),priority:s(row.Priority)});await updateHsComplaint({id,status:s(row.Status)||"open",assignedVendorId:vid||null,slaDueAt:s(row["SLA Due At"])||null,resolutionNote:s(row["Resolution Note"])||null});return id})}runner.sectionDone("operations.complaints");
 for(const row of sectionRows(data,"operations.complaint_comments")){const ref=s(row["Comment Ref"]),cid=sectionId(runner,"operations.complaints",s(row["Complaint Ref"]));await runner.row("operations.complaint_comments",ref,row,()=>{if(!cid)throw new Error(`Complaint ${row["Complaint Ref"]} was not seeded.`);return addHsComplaintComment(cid,s(row.Body))},{immutableAfterCreate:true})}runner.sectionDone("operations.complaint_comments");
 const amenityId=(ref:any)=>sectionId(runner,"operations.amenities",s(ref));
 for(const row of sectionRows(data,"operations.bookings")){const ref=s(row["Booking Ref"]),aid=amenityId(row["Amenity Ref"]);await runner.row("operations.bookings",ref,row,async()=>{if(!aid)throw new Error(`Amenity ${row["Amenity Ref"]} was not seeded.`);const id=await createHsAmenityBooking({amenityId:aid,unitEntityId:unitId(row["Unit ID"])||null,startsAt:s(row["Starts At"]),endsAt:s(row["Ends At"]),purpose:s(row.Purpose)});const status=s(row["Expected Status"]);if(status==="approved"||status==="rejected"||status==="cancelled")await reviewHsAmenityBooking(id,status);return id},{immutableAfterCreate:true})}runner.sectionDone("operations.bookings");

 for(const row of sectionRows(data,"finance.charge_heads")){const ref=s(row["Charge Head Ref"]);await runner.row("finance.charge_heads",ref,row,id=>upsertHsChargeHead({id:id||undefined,code:s(row.Code),label:s(row.Label),category:s(row.Category),amount:n(row.Amount),active:b(row.Active)}))}runner.sectionDone("finance.charge_heads");
 for(const row of sectionRows(data,"finance.billing_cycles")){const ref=s(row["Cycle Ref"]);await runner.row("finance.billing_cycles",ref,row,async existing=>{if(existing)return existing;const id=await createHsBillingCycle({label:s(row.Label),periodStart:s(row["Period Start"]),periodEnd:s(row["Period End"]),dueOn:s(row["Due On"]),graceDays:n(row["Grace Days"]),penaltyRateMonthly:n(row["Penalty Rate Monthly"])});if(b(row["Generate Bills"]))await generateHsCycleBills(id);return id},{immutableAfterCreate:true})}runner.sectionDone("finance.billing_cycles");
 const financeSnap=await fetchHsFinanceSnapshot();const unitRows=sectionRows(data,"core_import.units"),cycleRows=sectionRows(data,"finance.billing_cycles");
 for(const row of sectionRows(data,"finance.bill_expectations")){const ref=s(row["Bill Ref"]),cycleRef=s(row["Cycle Ref"]),unitRef=s(row["Unit ID"]),cycleLabel=s(rowBy(cycleRows,"Cycle Ref",cycleRef)?.Label),unitLabel=s(rowBy(unitRows,"Unit ID",unitRef)?.["Unit / Flat"]);await runner.row("finance.bill_expectations",ref,row,async()=>{const bill=financeSnap.bills.find(x=>x.cycleLabel===cycleLabel&&x.unitLabel===unitLabel);if(!bill)throw new Error(`Generated bill for ${cycleLabel}/${unitLabel} was not found.`);const expected=n(row["Expected Total"]);if(expected&&Math.abs(bill.totalAmount-expected)>.01)runner.warnings.push(`Bill ${ref}: generated total ${bill.totalAmount} differs from dataset expectation ${expected}; product-generated ledger was preserved.`);return bill.id})}runner.sectionDone("finance.bill_expectations");
 const billId=(ref:any)=>sectionId(runner,"finance.bill_expectations",s(ref));
 for(const row of sectionRows(data,"finance.adjustments")){const ref=s(row["Adjustment Ref"]),bid=billId(row["Bill Ref"]);await runner.row("finance.adjustments",ref,row,()=>{if(!bid)throw new Error(`Bill ${row["Bill Ref"]} was not resolved.`);return addHsBillAdjustment({billId:bid,type:s(row.Type) as "credit"|"debit"|"waiver"|"penalty",amount:n(row.Amount),reason:s(row.Reason)})},{immutableAfterCreate:true})}runner.sectionDone("finance.adjustments");
 for(const row of sectionRows(data,"finance.payments")){const ref=s(row["Payment Ref"]),bid=billId(row["Bill Ref"]);await runner.row("finance.payments",ref,row,()=>{if(!bid)throw new Error(`Bill ${row["Bill Ref"]} was not resolved.`);return recordHsPayment({billId:bid,amount:n(row.Amount),paidOn:s(row["Paid On"]),paymentMode:s(row["Payment Mode"]),paymentReference:s(row.Reference),receiptNumber:s(row["Receipt Number"])})},{immutableAfterCreate:true})}runner.sectionDone("finance.payments");
 for(const row of sectionRows(data,"finance.funds")){const ref=s(row["Fund Ref"]);await runner.row("finance.funds",ref,row,id=>upsertHsFund({id:id||undefined,code:s(row.Code),label:s(row.Label),openingBalance:n(row["Opening Balance"]),visibility:(s(row.Visibility)==="admin"?"admin":"members")}))}runner.sectionDone("finance.funds");
 const fundId=(ref:any)=>sectionId(runner,"finance.funds",s(ref));
 for(const [i,row] of sectionRows(data,"finance.budget").entries()){const ref=sectionRef("housing-society","finance.budget",row,i);await runner.row("finance.budget",ref,row,()=>upsertHsBudgetLine({financialYear:s(row["Financial Year"]),category:s(row.Category),label:s(row.Label),budgetAmount:n(row["Budget Amount"]),visibility:s(row.Visibility)==="admin"?"admin":"members"}))}runner.sectionDone("finance.budget");
 for(const row of sectionRows(data,"finance.expenses")){const ref=s(row["Expense Ref"]);await runner.row("finance.expenses",ref,row,()=>recordHsExpense({category:s(row.Category),description:s(row.Description),amount:n(row.Amount),incurredOn:s(row["Incurred On"]),fundId:fundId(row["Fund Ref"])||null,vendorId:vendorId(row["Vendor Ref"])||null,paymentReference:s(row["Payment Reference"]),visibility:s(row.Visibility)==="admin"?"admin":"members"}),{immutableAfterCreate:true})}runner.sectionDone("finance.expenses");

 for(const row of sectionRows(data,"governance.committee_terms")){const ref=s(row["Term Ref"]);await runner.row("governance.committee_terms",ref,row,()=>createHsCommitteeTerm({label:s(row.Label),startsOn:s(row["Starts On"]),endsOn:s(row["Ends On"])||null,notes:s(row.Notes)}),{immutableAfterCreate:true})}runner.sectionDone("governance.committee_terms");
 const termId=(ref:any)=>sectionId(runner,"governance.committee_terms",s(ref));
 for(const row of sectionRows(data,"governance.committee_assignments")){const ref=s(row["Assignment Ref"]);await runner.row("governance.committee_assignments",ref,row,()=>{const tid=termId(row["Term Ref"]),pid=residentId(row["Resident ID"]);if(!tid||!pid)throw new Error("Committee term/resident reference was not resolved.");return assignHsCommitteeRole({termId:tid,personEntityId:pid,roleKey:s(row["Role Key"]),roleLabel:s(row["Role Label"]),startsOn:s(row["Starts On"]),endsOn:s(row["Ends On"])||null})},{immutableAfterCreate:true})}runner.sectionDone("governance.committee_assignments");
 for(const row of sectionRows(data,"governance.meetings")){const ref=s(row["Meeting Ref"]);await runner.row("governance.meetings",ref,row,()=>createHsGovernanceMeeting({meetingType:s(row["Meeting Type"]),title:s(row.Title),scheduledAt:s(row["Scheduled At"]),location:s(row.Location),quorumRequired:n(row["Quorum Required"])||null}),{immutableAfterCreate:true})}runner.sectionDone("governance.meetings");
 const meetingId=(ref:any)=>sectionId(runner,"governance.meetings",s(ref));
 for(const row of sectionRows(data,"governance.agenda")){const ref=s(row["Agenda Ref"]),mid=meetingId(row["Meeting Ref"]);await runner.row("governance.agenda",ref,row,()=>{if(!mid)throw new Error("Meeting reference was not resolved.");return addHsAgendaItem(mid,s(row.Title),s(row.Description))},{immutableAfterCreate:true})}runner.sectionDone("governance.agenda");
 for(const [i,row] of sectionRows(data,"governance.minutes").entries()){const ref=sectionRef("housing-society","governance.minutes",row,i),mid=meetingId(row["Meeting Ref"]);await runner.row("governance.minutes",ref,row,async()=>{if(!mid)throw new Error("Meeting reference was not resolved.");await publishHsMinutes(mid,s(row.Minutes),n(row["Attendee Count"])||null);return mid})}runner.sectionDone("governance.minutes");
 for(const row of sectionRows(data,"governance.actions")){const ref=s(row["Action Ref"]),mid=meetingId(row["Meeting Ref"]);await runner.row("governance.actions",ref,row,async existing=>{const id=existing||await createHsGovernanceAction({meetingId:mid||null,title:s(row.Title),ownerLabel:s(row["Owner Label"]),dueOn:s(row["Due On"])||null});const status=s(row.Status) as "open"|"in_progress"|"done"|"cancelled";if(status&&status!=="open")await updateHsGovernanceAction(id,status);return id})}runner.sectionDone("governance.actions");
 for(const row of sectionRows(data,"governance.resolutions")){const ref=s(row["Resolution Ref"]),mid=meetingId(row["Meeting Ref"]);await runner.row("governance.resolutions",ref,row,async existing=>{const id=existing||await createHsResolution({meetingId:mid||null,resolutionNumber:s(row["Resolution Number"]),title:s(row.Title),body:s(row.Body),voteMode:(s(row["Vote Mode"])||"approval") as "advisory"|"approval",opensAt:s(row["Opens At"])||null,closesAt:s(row["Closes At"])||null,quorumPercent:n(row["Quorum Percent"])});const status=s(row.Status);if(["approved","rejected","closed","withdrawn"].includes(status))await closeHsResolution(id,status as any,"Synthetic launch dataset result");return id})}runner.sectionDone("governance.resolutions");
 const resolutionId=(ref:any)=>sectionId(runner,"governance.resolutions",s(ref));
 for(const row of sectionRows(data,"governance.documents")){const ref=s(row["Document Ref"]);await runner.row("governance.documents",ref,row,()=>addHsGovernanceDocument({meetingId:meetingId(row["Meeting Ref"])||null,resolutionId:resolutionId(row["Resolution Ref"])||null,documentType:s(row["Document Type"]),title:s(row.Title),versionLabel:s(row["Version Label"]),documentUrl:s(row["Document URL"]),visibility:s(row.Visibility)==="admin"?"admin":"members"}),{immutableAfterCreate:true})}runner.sectionDone("governance.documents");
 for(const row of sectionRows(data,"governance.ballots")){const ref=s(row["Ballot Ref"]);await runner.row("governance.ballots",ref,row,async existing=>{const id=await saveNetworkBallot({id:existing||null,ballotType:s(row["Ballot Type"]),title:s(row.Title),description:s(row.Description),eligibilityMode:s(row["Eligibility Mode"]),maxChoices:n(row["Max Choices"])||1,secretBallot:b(row["Secret Ballot"]),allowNominations:b(row["Allow Nominations"]),opensAt:s(row["Opens At"])||null,closesAt:s(row["Closes At"])||null});const desired=s(row["Desired Status"]);if(desired==="open")await openNetworkBallot(id);else if(desired==="closed")await closeNetworkBallot(id);else if(desired==="published"){await closeNetworkBallot(id);await publishNetworkBallotResults(id)}return id})}runner.sectionDone("governance.ballots");
 const ballotId=(ref:any)=>sectionId(runner,"governance.ballots",s(ref));
 for(const row of sectionRows(data,"governance.ballot_options")){const ref=s(row["Option Ref"]),bid=ballotId(row["Ballot Ref"]);await runner.row("governance.ballot_options",ref,row,()=>{if(!bid)throw new Error("Ballot reference was not resolved.");return addBallotOption(bid,s(row.Label),s(row.Description),residentId(row["Candidate Resident ID"])||null)},{immutableAfterCreate:true})}runner.sectionDone("governance.ballot_options");

 for(const row of sectionRows(data,"security.visitors")){const ref=s(row["Visitor Ref"]);await runner.row("security.visitors",ref,row,async existing=>{const uid=unitId(row["Unit ID"]);if(!uid)throw new Error("Visitor unit reference was not resolved.");const id=existing||await createHsVisitor({unitId:uid,visitorName:s(row["Visitor Name"]),visitType:s(row["Visit Type"]),expectedAt:s(row["Expected At"])||null,purpose:s(row.Purpose),phone:s(row.Phone),vehicleNumber:s(row["Vehicle Number"])});const status=s(row["Desired Status"]);if(status&&status!=="expected")await updateHsVisitorStatus(id,status);return id})}runner.sectionDone("security.visitors");
 for(const row of sectionRows(data,"security.staff")){const ref=s(row["Staff Ref"]);await runner.row("security.staff",ref,row,id=>upsertHsStaff({id:id||undefined,name:s(row.Name),staffType:s(row["Staff Type"]),phone:s(row.Phone),identityLast4:s(row["Identity Last4"]),verificationStatus:s(row["Verification Status"])}))}runner.sectionDone("security.staff");
 const staffId=(ref:any)=>sectionId(runner,"security.staff",s(ref));
 for(const row of sectionRows(data,"security.staff_access")){const ref=s(row["Access Ref"]);await runner.row("security.staff_access",ref,row,()=>{const sid=staffId(row["Staff Ref"]),uid=unitId(row["Unit ID"]);if(!sid||!uid)throw new Error("Staff/unit reference was not resolved.");return authorizeHsStaffUnit(sid,uid,s(row["Starts On"]),s(row["Ends On"])||null)},{immutableAfterCreate:true})}runner.sectionDone("security.staff_access");
 for(const row of sectionRows(data,"security.move_requests")){const ref=s(row["Move Ref"]);await runner.row("security.move_requests",ref,row,async existing=>{const uid=unitId(row["Unit ID"]);if(!uid)throw new Error("Unit reference was not resolved.");const id=existing||await createHsMoveRequest({unitId:uid,moveType:s(row["Move Type"]) as "move_in"|"move_out",scheduledOn:s(row["Scheduled On"]),contactName:s(row["Contact Name"]),notes:s(row.Notes)});const status=s(row["Desired Status"]);if(status&&status!=="pending")await reviewHsOperationalRequest("move",id,status,"Synthetic launch dataset");return id})}runner.sectionDone("security.move_requests");
 for(const row of sectionRows(data,"security.renovations")){const ref=s(row["Renovation Ref"]);await runner.row("security.renovations",ref,row,async existing=>{const uid=unitId(row["Unit ID"]);if(!uid)throw new Error("Unit reference was not resolved.");const id=existing||await createHsRenovationRequest({unitId:uid,title:s(row.Title),description:s(row.Description),contractorName:s(row["Contractor Name"]),startsOn:s(row["Starts On"])||null,endsOn:s(row["Ends On"])||null});const status=s(row["Desired Status"]);if(status&&status!=="pending")await reviewHsOperationalRequest("renovation",id,status,"Synthetic launch dataset","DEMO-NOC");return id})}runner.sectionDone("security.renovations");
 for(const row of sectionRows(data,"security.assets")){const ref=s(row["Asset Ref"]);await runner.row("security.assets",ref,row,id=>upsertHsAsset({id:id||undefined,assetCode:s(row["Asset Code"]),name:s(row.Name),category:s(row.Category),location:s(row.Location),warrantyUntil:s(row["Warranty Until"])||null}))}runner.sectionDone("security.assets");
 const assetId=(ref:any)=>sectionId(runner,"security.assets",s(ref));
 for(const row of sectionRows(data,"security.asset_service")){const ref=s(row["Service Ref"]),aid=assetId(row["Asset Ref"]);await runner.row("security.asset_service",ref,row,()=>{if(!aid)throw new Error("Asset reference was not resolved.");return addHsAssetService({assetId:aid,serviceType:s(row["Service Type"]),servicedOn:s(row["Serviced On"]),nextDueOn:s(row["Next Due On"])||null,notes:s(row.Notes),cost:n(row.Cost)||null})},{immutableAfterCreate:true})}runner.sectionDone("security.asset_service");
 for(const row of sectionRows(data,"security.compliance")){const ref=s(row["Compliance Ref"]);await runner.row("security.compliance",ref,row,id=>upsertHsCompliance({id:id||undefined,category:s(row.Category),title:s(row.Title),dueOn:s(row["Due On"])||null,ownerLabel:s(row["Owner Label"]),documentUrl:s(row["Document URL"]),visibility:s(row.Visibility)==="admin"?"admin":"members"}))}runner.sectionDone("security.compliance");
 for(const [i,row] of sectionRows(data,"security.emergency_contacts").entries()){const ref=sectionRef("housing-society","security.emergency_contacts",row,i);await runner.row("security.emergency_contacts",ref,row,()=>upsertHsEmergencyContact({category:s(row.Category),label:s(row.Label),phone:s(row.Phone),notes:s(row.Notes),priority:n(row.Priority)||100}))}runner.sectionDone("security.emergency_contacts");

 for(const row of sectionRows(data,"community.events")){const ref=s(row["Activity Ref"]);await runner.row("community.events",ref,row,()=>createNetworkActivity({type:"event",title:s(row.Title),body:`${s(row.Description)}${row["Expected Participants"]?`\n\nExpected participants: ${row["Expected Participants"]}`:""}`,startsAt:s(row.Date)?`${s(row.Date)}T18:30:00+05:30`:undefined,visibility:"members"}),{immutableAfterCreate:true})}runner.sectionDone("community.events");
 for(const row of sectionRows(data,"community.posts")){const ref=s(row["Post Ref"]);await runner.row("community.posts",ref,row,async()=>{const id=await createNetworkPost({title:s(row.Title),body:s(row.Body),importance:(s(row.Importance)||"normal") as "normal"|"important"|"urgent",notifyAll:b(row["Notify All"])});if(b(row.Pinned))await setNetworkActivityPinned(id,true);return id},{immutableAfterCreate:true})}runner.sectionDone("community.posts");
 const postId=(ref:any)=>sectionId(runner,"community.posts",s(ref));
 for(const row of sectionRows(data,"community.post_comments")){const ref=s(row["Comment Ref"]),pid=postId(row["Post Ref"]);await runner.row("community.post_comments",ref,row,()=>{if(!pid)throw new Error("Post reference was not resolved.");return addNetworkPostComment(pid,s(row.Body))},{immutableAfterCreate:true})}runner.sectionDone("community.post_comments");
 for(const row of sectionRows(data,"community.media")){const ref=s(row["Media Ref"]),entityRef=s(row["Entity Ref"]),entityType=s(row["Entity Type"]);await runner.row("community.media",ref,row,async()=>{let target:string|undefined,storageType="activity";if(entityType==="network_post")target=postId(entityRef);else if(entityType==="event")target=sectionId(runner,"community.events",entityRef);else if(entityType==="hs_complaint"){target=sectionId(runner,"operations.complaints",entityRef);storageType="hs_complaint"}if(!target)throw new Error(`Media target ${entityRef} was not resolved.`);const kind=(s(row["Media Kind"])||"other") as MediaKind;const file=await fixtureFile(kind==="complaint"?"complaint-demo.png":"residential-demo.png");const asset=await uploadMediaAsset(file,kind,{entityType:storageType,entityId:target});return asset.assetId},{immutableAfterCreate:true})}runner.sectionDone("community.media");
 return runner.result();
}
