import {supabase} from "../../lib/supabase";
import {postCommand} from "../../lib/api-client";
import {deleteOwnedNetworkPermanently} from "../../lib/network-lifecycle";
import type {BootstrapInstitutionResult,ClaimIdentityResult,CreateGraphRelationshipResult,CreateNetworkResult,JoinNetworkResult} from "../../core/api/contracts";
import type {ProductizedVerticalKind} from "../../templates/productized/config";
function required(){if(!supabase)throw new Error("Shared Supabase mode is required.");return supabase}
export type TemplateNetworkSettings={templateId:string;contextLabel:string;contextValue:string;description?:string|null};
export type NetworkEntityRelationship={id:string;fromEntityId:string;toEntityId:string;fromLabel:string;toLabel:string;relationshipType:string;label:string;metadata?:Record<string,unknown>};
export type GenericContribution={id:string;entityId?:string|null;entityLabel?:string|null;message:string;payload:Record<string,unknown>;status:"open"|"accepted"|"rejected";createdAt:string;createdBy?:string|null};
export async function createTemplateNetwork(kind:ProductizedVerticalKind,name:string,contextValue:string,description=""){return postCommand<CreateNetworkResult>("/api/v1/networks/create",{kind,name,contextValue,description},{idempotent:true})}
export async function fetchTemplateNetworkSettings(){const s=required();const {data,error}=await s.rpc("get_productized_network_settings");if(error)throw error;const r=(data||[])[0];return r?{templateId:String(r.template_id),contextLabel:String(r.context_label||"Network"),contextValue:String(r.context_value||""),description:r.description} as TemplateNetworkSettings:null}
export async function upsertNetworkEntity(input:{id?:string;kind:string;label:string;metadata?:Record<string,unknown>;affiliations?:Record<string,string|string[]>;visibility?:"members"|"private"}){const s=required();const {data,error}=await s.rpc("upsert_productized_network_entity",{p_entity_id:input.id||null,p_kind:input.kind,p_label:input.label,p_metadata:input.metadata||{},p_affiliations:input.affiliations||{},p_visibility:input.visibility||"members"});if(error)throw error;return String(data)}
export async function deleteNetworkEntity(id:string){const s=required();const {error}=await s.rpc("delete_productized_network_entity",{p_entity_id:id});if(error)throw error}
export async function importNetworkEntities(rows:{kind?:string;label:string;metadata?:Record<string,unknown>;affiliations?:Record<string,string|string[]>}[]){return postCommand<BootstrapInstitutionResult>("/api/v1/institutional/bootstrap",{rows},{idempotent:true})}
export async function fetchNetworkEntityRelationships(){const s=required();const {data,error}=await s.rpc("get_productized_network_relationships");if(error)throw error;return (data||[]).map((r:any)=>({id:String(r.id),fromEntityId:String(r.from_entity_id),toEntityId:String(r.to_entity_id),fromLabel:String(r.from_label),toLabel:String(r.to_label),relationshipType:String(r.relationship_type),label:String(r.relationship_label||r.relationship_type),metadata:r.metadata||{}})) as NetworkEntityRelationship[]}
export async function createNetworkEntityRelationship(fromEntityId:string,toEntityId:string,relationshipType:string,metadata:Record<string,unknown>={}){const data=await postCommand<CreateGraphRelationshipResult>("/api/v1/graph/relationships",{fromEntityId,toEntityId,relationshipType,metadata});return data.relationshipId}
export async function deleteNetworkEntityRelationship(id:string){const s=required();const {error}=await s.rpc("delete_productized_network_relationship",{p_relationship_id:id});if(error)throw error}
export async function getOrCreateNetworkJoinCode(){const s=required();const {data,error}=await s.rpc("get_or_create_network_join_code");if(error)throw error;return String(data||"")}
export async function regenerateNetworkJoinCode(){const s=required();const {data,error}=await s.rpc("regenerate_network_join_code");if(error)throw error;return String(data||"")}
export async function joinProductizedNetworkByCode(code:string){const data=await postCommand<JoinNetworkResult>("/api/v1/networks/join",{kind:"productized",code});return data.networkId}
export async function submitNetworkContribution(entityId:string|null,message:string,payload:Record<string,unknown>={}){const s=required();const {data,error}=await s.rpc("submit_productized_network_contribution",{p_entity_id:entityId,p_message:message,p_payload:payload});if(error)throw error;return String(data)}
export async function fetchNetworkContributions(){const s=required();const {data,error}=await s.rpc("get_productized_network_contributions");if(error)throw error;return (data||[]).map((r:any)=>({id:String(r.id),entityId:r.entity_id?String(r.entity_id):null,entityLabel:r.entity_label||null,message:String(r.message),payload:r.payload||{},status:r.status,createdAt:r.created_at,createdBy:r.created_by})) as GenericContribution[]}
export async function reviewNetworkContribution(id:string,action:"accepted"|"rejected"){const s=required();const {error}=await s.rpc("review_productized_network_contribution",{p_contribution_id:id,p_action:action});if(error)throw error}

export type ClaimableProductizedEntity={entityId:string;entityKind:string;entityLabel:string;networkId:string;networkName:string};
export async function fetchClaimableProductizedEntities(){const s=required();const {data,error}=await s.rpc("get_my_claimable_productized_entities");if(error)throw error;return (data||[]).map((r:any)=>({entityId:String(r.entity_id),entityKind:String(r.entity_kind),entityLabel:String(r.entity_label),networkId:String(r.network_id),networkName:String(r.network_name)})) as ClaimableProductizedEntity[]}
export async function claimProductizedEntity(entityId:string){const data=await postCommand<ClaimIdentityResult>("/api/v1/identities/claim",{kind:"productized",subjectId:entityId});return data.networkId}

export type ProductizedNetworkMember={userId:string;email?:string|null;role:"owner"|"admin"|"member";status:string;entityLabel?:string|null;joinedAt?:string};
export async function fetchProductizedNetworkMembers(){const s=required();const {data,error}=await s.rpc("get_productized_network_memberships");if(error)throw error;return (data||[]).map((r:any)=>({userId:String(r.user_id),email:r.email||null,role:r.role,status:r.status,entityLabel:r.entity_label||null,joinedAt:r.joined_at})) as ProductizedNetworkMember[]}
export async function setProductizedNetworkMemberRole(userId:string,role:"admin"|"member"){const s=required();const {error}=await s.rpc("set_productized_network_member_role",{p_user_id:userId,p_role:role});if(error)throw error}
export async function removeProductizedNetworkMember(userId:string){const s=required();const {error}=await s.rpc("remove_productized_network_member",{p_user_id:userId});if(error)throw error}

export type AssociationHouseholdAdminContext={householdId:string;householdLabel:string;canManage:boolean;userId:string;entityLabel:string;isHouseholdAdmin:boolean;isRepresentative:boolean};
export async function fetchMyAssociationHouseholdAdminContext(){const s=required();const {data,error}=await s.rpc("get_my_association_household_admin_context");if(error)throw error;return (data||[]).map((r:any)=>({householdId:String(r.household_id),householdLabel:String(r.household_label),canManage:Boolean(r.can_manage),userId:String(r.user_id),entityLabel:String(r.entity_label),isHouseholdAdmin:Boolean(r.is_household_admin),isRepresentative:Boolean(r.is_representative)})) as AssociationHouseholdAdminContext[]}
export async function setAssociationHouseholdAdmin(householdId:string,userId:string,enabled:boolean){const s=required();const {error}=await s.rpc("set_association_household_admin",{p_household_id:householdId,p_user_id:userId,p_enabled:enabled});if(error)throw error}

export async function leaveProductizedNetwork(){const s=required();const {data,error}=await s.rpc("leave_productized_network");if(error)throw error;return data?String(data):null}
export async function archiveProductizedNetwork(confirmName:string){const s=required();const {error}=await s.rpc("archive_productized_network",{p_confirm_name:confirmName});if(error)throw error}
export async function deleteProductizedNetworkPermanently(networkId:string,confirmName:string){return deleteOwnedNetworkPermanently(networkId,confirmName)}
// E6 — shared network funds / membership collections / event collections.
export type NetworkFundRow={id:string;name:string;fund_kind:string;purpose?:string|null;target_amount?:number|null;opening_balance:number;visibility:string;status:string;membership_year_id?:string|null;activity_id?:string|null;activity_title?:string|null;year_label?:string|null;collected:number;spent:number;balance:number};
export type NetworkFundTransactionRow={id:string;fund_id:string;fund_name:string;transaction_kind:string;amount:number;signed_amount:number;source_entity_id?:string|null;source_label?:string|null;receipt_no?:string|null;payment_method?:string|null;reference?:string|null;note?:string|null;visibility:string;occurred_on:string;created_at:string};
export type NetworkMembershipDueRow={membership_id:string;membership_year_id:string;year_label:string;family_entity_id:string;family_label:string;representative_label?:string|null;amount_due:number;amount_paid:number;outstanding:number;payment_status:string;status:string};
export type NetworkFundsSnapshot={is_admin:boolean;visibility_mode:string;funds:NetworkFundRow[];transactions:NetworkFundTransactionRow[];membership_dues:NetworkMembershipDueRow[];events:{id:string;title:string;starts_at?:string|null}[]};
export async function fetchNetworkFundsSnapshot(){const s=required();const {data,error}=await s.rpc("get_network_funds_snapshot");if(error)throw error;const d=(data||{}) as any;return {is_admin:Boolean(d.is_admin),visibility_mode:String(d.visibility_mode||"admins"),funds:(d.funds||[]) as NetworkFundRow[],transactions:(d.transactions||[]) as NetworkFundTransactionRow[],membership_dues:(d.membership_dues||[]) as NetworkMembershipDueRow[],events:(d.events||[]) as any[]} as NetworkFundsSnapshot}
export async function createNetworkFund(input:{name:string;fundKind:string;purpose?:string;targetAmount?:number|null;openingBalance?:number;visibility?:string;membershipYearId?:string|null;activityId?:string|null}){const s=required();const {data,error}=await s.rpc("create_network_fund",{p_name:input.name,p_fund_kind:input.fundKind,p_purpose:input.purpose||null,p_target_amount:input.targetAmount??null,p_opening_balance:input.openingBalance||0,p_visibility:input.visibility||"members",p_membership_year_id:input.membershipYearId||null,p_activity_id:input.activityId||null});if(error)throw error;return String(data)}
export async function recordNetworkFundTransaction(input:{fundId:string;transactionKind:string;amount:number;sourceEntityId?:string|null;activityId?:string|null;membershipYearId?:string|null;paymentMethod?:string;reference?:string;note?:string;visibility?:string;occurredOn?:string}){const s=required();const {data,error}=await s.rpc("record_network_fund_transaction",{p_fund_id:input.fundId,p_transaction_kind:input.transactionKind,p_amount:input.amount,p_source_entity_id:input.sourceEntityId||null,p_activity_id:input.activityId||null,p_membership_year_id:input.membershipYearId||null,p_payment_method:input.paymentMethod||null,p_reference:input.reference||null,p_note:input.note||null,p_visibility:input.visibility||"members",p_occurred_on:input.occurredOn||new Date().toISOString().slice(0,10)});if(error)throw error;return String(data)}
