import {supabase} from "../../lib/supabase";
import type {LaunchSeedContext,LaunchSeedDiagnostic,LaunchSeedKind,LaunchSeedLineageRow,LaunchSeedLineageStatus} from "../../core/launch-seed/contracts";
function db(){if(!supabase)throw new Error("Shared Supabase mode is required for launch seeding.");return supabase}
export async function authorizeLaunchDemoSeed(datasetVersion:string,networkName:string,allowRealNetwork=false){const {data,error}=await db().rpc("authorize_launch_demo_seed",{p_dataset_version:datasetVersion,p_confirm_network_name:networkName,p_allow_real_network:allowRealNetwork});if(error)throw error;return data as LaunchSeedContext}
export async function fetchLaunchSeedContext(datasetVersion:string){const {data,error}=await db().rpc("get_launch_demo_seed_context",{p_dataset_version:datasetVersion});if(error)throw error;const d=(data||{}) as any;return {networkId:d.network_id,networkName:d.network_name,verticalKind:d.vertical_kind,datasetVersion:d.dataset_version,authorized:Boolean(d.authorized),allowRealNetwork:Boolean(d.allow_real_network),isPlatformOwner:Boolean(d.is_platform_owner),isAdmin:Boolean(d.is_admin)} as LaunchSeedContext}
export async function fetchLaunchSeedLineage(datasetVersion:string){const {data,error}=await db().rpc("get_launch_demo_seed_lineage",{p_dataset_version:datasetVersion});if(error)throw error;return (data||[]).map((r:any)=>({sectionKey:String(r.section_key),rowRef:String(r.row_ref),payloadHash:String(r.payload_hash),remoteId:r.remote_id?String(r.remote_id):null,status:String(r.status||"committed") as LaunchSeedLineageStatus,lastMessage:r.last_message||null,updatedAt:r.updated_at})) as LaunchSeedLineageRow[]}
export async function recordLaunchSeedLineage(input:{datasetVersion:string;sectionKey:string;rowRef:string;payloadHash:string;remoteId?:string|null;status?:LaunchSeedLineageStatus;message?:string}){const {error}=await db().rpc("record_launch_demo_seed_lineage",{p_dataset_version:input.datasetVersion,p_section_key:input.sectionKey,p_row_ref:input.rowRef,p_payload_hash:input.payloadHash,p_remote_id:input.remoteId||null,p_status:input.status||"committed",p_message:input.message||null});if(error)throw error}
export async function startLaunchSeedRun(datasetVersion:string,kind:LaunchSeedKind,totalRows:number){const {data,error}=await db().rpc("start_launch_demo_seed_run",{p_dataset_version:datasetVersion,p_vertical_kind:kind,p_total_rows:totalRows});if(error)throw error;return String(data)}
export async function recordLaunchSeedRunIssue(runId:string,diagnostic:LaunchSeedDiagnostic){const {error}=await db().rpc("record_launch_demo_seed_issue",{p_run_id:runId,p_severity:diagnostic.severity,p_section_key:diagnostic.section,p_row_ref:diagnostic.rowRef,p_operation:diagnostic.operation,p_error_code:diagnostic.code||null,p_message:diagnostic.message,p_details:diagnostic.details||null,p_hint:diagnostic.hint||null,p_retryable:!!diagnostic.retryable});if(error)throw error}
export async function finishLaunchSeedRun(runId:string,result:{created:number;updated:number;skipped:number;errors:number;warnings:number},status?:"completed"|"completed_with_errors"|"failed"){const finalStatus=status||(result.errors?"completed_with_errors":"completed");const {error}=await db().rpc("finish_launch_demo_seed_run",{p_run_id:runId,p_status:finalStatus,p_created:result.created,p_updated:result.updated,p_skipped:result.skipped,p_errors:result.errors,p_warnings:result.warnings});if(error)throw error}
export async function fetchLaunchSeedRunReport(runId:string){const {data,error}=await db().rpc("get_launch_demo_seed_run_report",{p_run_id:runId});if(error)throw error;return data}
export async function upsertLaunchFcaRole(input:{datasetVersion:string;roleKey:string;label:string;roleType:string;portfolio?:string}){const {data,error}=await db().rpc("launch_demo_upsert_fca_role_catalog",{p_dataset_version:input.datasetVersion,p_role_key:input.roleKey,p_label:input.label,p_role_type:input.roleType,p_portfolio:input.portfolio||null});if(error)throw error;return String(data)}
export async function createLaunchSeedRelationship(datasetVersion:string,fromEntityId:string,toEntityId:string,relationshipType:string,metadata:Record<string,unknown>={}){const {data,error}=await db().rpc("launch_demo_create_relationship",{p_dataset_version:datasetVersion,p_from_entity_id:fromEntityId,p_to_entity_id:toEntityId,p_relationship_type:relationshipType,p_metadata:metadata});if(error)throw error;return String(data)}
export async function openLaunchSeedBallot(datasetVersion:string,ballotId:string){const {data,error}=await db().rpc("launch_demo_open_ballot",{p_dataset_version:datasetVersion,p_ballot_id:ballotId});if(error)throw error;return Number(data||0)}
