import fs from 'node:fs';import path from 'node:path';import {VERTICALS} from './runtime/catalog.mjs';
const readJson=(f,d=null)=>{try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return d}};
const readNd=(f)=>{try{return fs.readFileSync(f,'utf8').split(/\r?\n/).filter(Boolean).map(x=>JSON.parse(x))}catch{return []}};
const exists=f=>fs.existsSync(f);const now=new Date().toISOString();const findings=[];
const subsystem=(x)=>{const s=`${x.code||''} ${x.title||''} ${x.source||''}`.toLowerCase();if(/rls|tenant|storage|permission|invite.*token|authorization/.test(s))return 'security / tenant isolation';if(/migration|database|rpc|sql/.test(s))return 'database / RPC';if(/import|workbook|bootstrap/.test(s))return 'import / onboarding';if(/accessibility|axe|mobile|webkit|firefox/.test(s))return 'accessibility / responsive / browser';if(/crawler|navigation|vertical|shell/.test(s))return 'shared shell / vertical runtime';if(/api/.test(s))return 'HTTP API';return 'application runtime'};
const add=(x)=>findings.push({severity:x.severity||'P2',code:x.code||'RUNTIME',title:x.title||x.test||x.message||'QA finding',details:x.details||x.error||x.message||'',url:x.url||null,evidence:x.evidence||x.attachments||null,source:x.source||'automation',vertical:x.vertical||null,role:x.role||null});
for(const x of readJson('qa-results/test-failures.json',[])||[])add({...x,code:'PLAYWRIGHT_FAILURE',title:x.test,details:x.error,source:'playwright',evidence:x.attachments});
for(const x of readNd('qa-results/issues/runtime.ndjson'))add({severity:x.status>=500?'P1':'P2',code:`RUNTIME_${String(x.type||'issue').toUpperCase()}`,title:`${x.type}: ${x.test}`,details:x.message,url:x.url,source:'runtime-watch'});
for(const x of readNd('qa-results/issues/findings.ndjson'))add({...x,source:'runtime'});
const pre=readJson('qa-results/preflight.json');if(pre)for(const x of pre.results||[])if(x.status!=='passed')add({severity:'P1',code:'PREFLIGHT',title:`Preflight failed: ${x.name}`,details:x.error||x.command,source:'preflight'});
for(const [file,code,defaultSeverity] of [
 ['qa-results/db/database-integrity.json','DB_INTEGRITY','P1'],['qa-results/db/rpc-permission-audit.json','RPC_PERMISSION','P1'],['qa-results/db/rpc-smoke.json','RPC_FAIL','P1'],['qa-results/security/rls-adversarial.json','RLS_FAIL','P0']
]){const r=readJson(file);if(r?.status==='failed')for(const x of r.checks||[])if(x.status==='failed')add({severity:x.severity||defaultSeverity,code,title:x.name||`${x.role||''} ${x.vertical||''} ${x.rpc||''}`.trim(),details:x.error||x,source:file,role:x.role,vertical:x.vertical});if(r?.status==='blocked')add({severity:'P2',code:'CERTIFICATION_BLOCKED',title:`${code} not executed`,details:r.reason||file,source:file})}
const replay=readJson('qa-results/db/migration-replay.json');if(replay){for(const mode of ['upgrade','fresh']){const r=replay[mode];if(r?.status==='failed'){const failed=(r.phases||[]).flatMap(p=>p.migrations||[]).find(x=>x.status==='failed');add({severity:'P1',code:'MIGRATION_REPLAY',title:`${mode} migration replay failed`,details:failed?.stderr||failed||r,source:'database'})}if(r?.status==='blocked')add({severity:'P2',code:'CERTIFICATION_BLOCKED',title:`${mode} migration replay not executed`,details:r.reason||'Database URL not configured',source:'database'})}}
// Crawler expected-vs-discovered failures are also independently readable even if Playwright reporter failed early.
for(const role of ['owner','admin','member'])for(const v of VERTICALS){const f=`qa-results/crawl/${role}-${v.kind}-inventory.json`,r=readJson(f);if(r?.missingExpected?.length)add({severity:'P1',code:'CRAWLER_COVERAGE_GAP',title:`Crawler missed required ${v.kind} surfaces for ${role}`,details:{missing:r.missingExpected,discovered:r.discoveredTestIds},source:f,role,vertical:v.kind})}
const rank={P0:0,P1:1,P2:2,P3:3};const uniq=[];const seen=new Set();for(const f of findings.sort((a,b)=>(rank[a.severity]??9)-(rank[b.severity]??9))){const k=`${f.code}|${f.title}|${JSON.stringify(f.details).slice(0,300)}`;if(!seen.has(k)){seen.add(k);uniq.push(f)}}uniq.forEach((x,i)=>{x.id=`QA-${String(i+1).padStart(3,'0')}`;x.suspectedSubsystem=subsystem(x);x.regressionTestId=`REG-${x.id.slice(3)}`});
fs.mkdirSync('qa-results',{recursive:true});fs.writeFileSync('qa-results/findings.json',JSON.stringify(uniq,null,2)+'\n');

// Flatten Playwright result for machine-readable runtime coverage.
const pw=readJson('qa-results/playwright.json');const specs=[];
function walk(suites=[],parents=[]){for(const s of suites||[]){const next=[...parents,s.title].filter(Boolean);for(const spec of s.specs||[]){const title=[...next,spec.title].filter(Boolean).join(' > ');for(const t of spec.tests||[]){const statuses=(t.results||[]).map(r=>r.status);const status=statuses.some(x=>['failed','timedOut','interrupted'].includes(x))?'failed':statuses.some(x=>x==='passed')?'passed':statuses.length?'skipped':'not-run';specs.push({title,project:t.projectName||'',status})}}walk(s.suites||[],next)}}
if(pw)walk(pw.suites||[]);
const statusFor=(predicate)=>{const rows=specs.filter(predicate);if(!rows.length)return 'not-run';if(rows.some(x=>x.status==='failed'))return 'failed';if(rows.every(x=>x.status==='skipped'))return 'blocked';return 'passed'};
const roleVertical=[];for(const v of VERTICALS)for(const role of ['owner','admin','member']){const smoke=statusFor(x=>x.title.includes(`[vertical:${v.kind}]`)&&x.title.includes(`[role:${role}]`));const crawlerFile=`qa-results/crawl/${role}-${v.kind}-inventory.json`,crawler=readJson(crawlerFile);const crawlerStatus=!crawler?'not-run':crawler.missingExpected?.length?'failed':'passed';roleVertical.push({vertical:v.kind,role,smoke,crawler:crawlerStatus,evidence:{playwright:'qa-results/playwright.json',crawler:crawlerFile}})}
const crawlerAll=roleVertical.every(x=>x.crawler==='passed')?'passed':roleVertical.some(x=>x.crawler==='failed')?'failed':'not-run';
const pwStatus=!pw?'not-run':statusFor(()=>true);
const suites=[
 {area:'Preflight: unit/contracts/types/build/source',status:pre?.status||'not-run',evidence:'qa-results/preflight.json'},
 {area:'Migration replay: staging rerunnability',status:replay?.upgrade?.status||'not-run',evidence:'qa-results/db/migration-replay.json'},
 {area:'Migration replay: fresh + historical checkpoint upgrade',status:replay?.fresh?.status||'not-run',evidence:'qa-results/db/migration-replay.json'},
 {area:'Database integrity/residue',status:readJson('qa-results/db/database-integrity.json')?.status||'not-run',evidence:'qa-results/db/database-integrity.json'},
 {area:'RPC runtime smoke',status:readJson('qa-results/db/rpc-smoke.json')?.status||'not-run',evidence:'qa-results/db/rpc-smoke.json'},
 {area:'RPC privilege/exposure audit',status:readJson('qa-results/db/rpc-permission-audit.json')?.status||'not-run',evidence:'qa-results/db/rpc-permission-audit.json'},
 {area:'RLS two-tenant + storage + invitation adversarial',status:readJson('qa-results/security/rls-adversarial.json')?.status||'not-run',evidence:'qa-results/security/rls-adversarial.json'},
 {area:'Playwright runtime suite',status:pwStatus,evidence:'qa-results/playwright.json'},
 {area:'9 vertical × 3 role smoke',status:roleVertical.every(x=>x.smoke==='passed')?'passed':roleVertical.some(x=>x.smoke==='failed')?'failed':'not-run',evidence:'qa-results/playwright.json'},
 {area:'Expert crawler 9 vertical × 3 role expected coverage',status:crawlerAll,evidence:'qa-results/crawl/'},
 {area:'Guided workbook browser round-trip',status:statusFor(x=>/guided workbook browser/i.test(x.title)),evidence:'qa-results/playwright.json'},
 {area:'Accessibility + responsive',status:statusFor(x=>/axe violations|mobile member shell|keyboard reachable/i.test(x.title)),evidence:'qa-results/playwright.json'},
 {area:'Controlled lifecycle/import/purge residue',status:statusFor(x=>/controlled staging lifecycle/i.test(x.title)),evidence:'qa-results/playwright.json'},
 {area:'100/1000-row volume + idempotency/pagination',status:statusFor(x=>/institutional bootstrap certifies/i.test(x.title)),evidence:'qa-results/playwright.json'},
 {area:'Resilience/slow/outage handling',status:statusFor(x=>/slow backend|transient backend outage/i.test(x.title)),evidence:'qa-results/playwright.json'},
 {area:'Firefox smoke',status:statusFor(x=>x.project==='firefox-smoke'),evidence:'qa-results/playwright.json'},
 {area:'WebKit smoke',status:statusFor(x=>x.project==='webkit-smoke'),evidence:'qa-results/playwright.json'}
];
fs.writeFileSync('qa-results/COVERAGE-MATRIX.json',JSON.stringify({generatedAt:now,verticals:VERTICALS.map(v=>v.kind),roles:['owner','admin','member','anonymous','invitee','tenantB'],suites,roleVertical},null,2)+'\n');
fs.writeFileSync('qa-results/COVERAGE-MATRIX.md',['# QA Coverage Matrix','',`Generated: ${now}`,'','## Certification layers','','| Area | Status | Evidence |','|---|---|---|',...suites.map(x=>`| ${x.area} | **${String(x.status).toUpperCase()}** | \`${x.evidence}\` |`),'','## Role × vertical runtime','','| Vertical | Owner smoke/crawl | Admin smoke/crawl | Member smoke/crawl |','|---|---|---|---|',...VERTICALS.map(v=>{const cell=r=>{const x=roleVertical.find(y=>y.vertical===v.kind&&y.role===r);return `${x?.smoke||'not-run'} / ${x?.crawler||'not-run'}`};return `| ${v.kind} | ${cell('owner')} | ${cell('admin')} | ${cell('member')} |`})].join('\n'));

const counts=Object.fromEntries(['P0','P1','P2','P3'].map(p=>[p,uniq.filter(x=>x.severity===p).length]));
const bug=['# TrustWeave Runtime Certification Bug Report','',`Generated: ${now}`,'',`Captured findings: **${uniq.length}** — P0 ${counts.P0}, P1 ${counts.P1}, P2 ${counts.P2}, P3 ${counts.P3}`,'','## Findings',''];if(!uniq.length)bug.push('No automated defects were captured in the executed scope. Certification still requires every mandatory layer above to be PASSED.','');for(const f of uniq){bug.push(`### ${f.id} · [${f.severity}] ${f.title}`,'',`- Code: \`${f.code}\``,`- Suspected subsystem: ${f.suspectedSubsystem}`,f.vertical?`- Vertical: ${f.vertical}`:'',f.role?`- Role: ${f.role}`:'',f.url?`- URL: ${f.url}`:'',`- Source: ${f.source}`,`- Evidence: ${typeof f.details==='string'?f.details.replace(/\s+/g,' ').slice(0,3000):JSON.stringify(f.details).slice(0,3000)}`,f.evidence?`- Attachments/evidence: \`${JSON.stringify(f.evidence).slice(0,1800)}\``:'',`- Permanent regression ID: \`${f.regressionTestId}\``,'','**Remediation rule:** fix the root cause, bind/strengthen the permanent automated assertion for this exact flow, rerun the affected role/vertical layer, then rerun `npm run qa:certify`.','')};fs.writeFileSync('qa-results/BUG-REPORT.md',bug.filter(x=>x!==undefined&&x!=='').join('\n\n'));
const blast=f=>/security|tenant|database|shared shell/.test(f.suspectedSubsystem)?'high':'localized';const plan=['# Prioritized QA Remediation Plan','',`Generated: ${now}`,'','Priority is severity → security/tenant blast radius → shared platform blast radius → vertical-local defects. Do not close a runtime defect without its regression test.',''];for(const p of ['P0','P1','P2','P3']){const xs=uniq.filter(x=>x.severity===p);if(!xs.length)continue;plan.push(`## ${p}`);for(const x of xs)plan.push(`- **${x.id} — ${x.title}** [${x.suspectedSubsystem}; ${blast(x)} blast radius] — ${typeof x.details==='string'?x.details.replace(/\s+/g,' ').slice(0,600):JSON.stringify(x.details).slice(0,600)} — regression: \`${x.regressionTestId}\``);plan.push('')};if(!uniq.length)plan.push('No defect remediation is queued from executed automation. Any BLOCKED/not-run certification layer must still be resolved before release.');fs.writeFileSync('qa-results/REMEDIATION-PLAN.md',plan.join('\n'));
const mandatory=suites.filter(x=>!['100/1000-row volume + idempotency/pagination'].includes(x.area)||process.env.QA_RUN_LARGE_VOLUME==='true'||true);const hardBlocked=mandatory.some(x=>['not-run','blocked','unknown'].includes(String(x.status)));const hardFailed=mandatory.some(x=>x.status==='failed');const status=counts.P0||counts.P1||hardFailed?'FAILED':hardBlocked?'BLOCKED':'CERTIFIED';const summary={generatedAt:now,status,counts,hardBlocked,hardFailed,suites,roleVertical};fs.writeFileSync('qa-results/CERTIFICATION-SUMMARY.json',JSON.stringify(summary,null,2)+'\n');console.log(`QA report generated: ${status}; P0=${counts.P0} P1=${counts.P1} P2=${counts.P2}; mandatory layers=${suites.length}`);
